jj-vcs/jj

lib/src/working_copy.rs
=> working_copy: extract `visit_directory` function for snapshotting

lib/src/working_copy.rs
=> working_copy: send updates via `channel`

Cargo.lock, lib/Cargo.toml, lib/src/matchers.rs, lib/src/working_copy.rs
=> working_copy: traverse filesystem in parallel

docs/git-comparison.md
Many new users coming from Git get confused that branches don't automatically follow commits. Call this out and give hints to the expected workflow.
If applicable:
=> docs: call out manual branch management

lib/src/working_copy.rs
=> working_copy: rename `WorkItem` -> `DirectoryToVisit`

lib/src/default_revset_graph_iterator.rs
=> revset_graph: discard cache of edges that won't be accessed anymore

README.md
=> readme: fix typo (fix adopted from #1942)

.github/PULL_REQUEST_TEMPLATE.md
As requested in PR #1942.
If applicable:
=> github: mention Google CLA requirement in PR template

CHANGELOG.md, Cargo.lock, Cargo.toml, src/commands/mod.rs, tests/test_init_command.rs
Addresses #1249.
Note: added allow_duplicates to the init test so make it work, but it seems the original code didn't really assert anything using insta (since the snapshot files are not checked in) - not sure what the intention there is.
=> Allow initializing with bare git repositories

docs/config.md, src/config-schema.json, src/diff_util.rs, src/merge_tools.rs, tests/common/mod.rs, tests/test_diff_command.rs
=> cli: load default diff command from "ui.diff.tool" config

lib/tests/test_view.rs
This is the same kind of fix as in 8e7e3271. I should have just fixed all instances then.
If applicable:
=> tests: attempt to fix more flaky tests in `test_view.rs`

lib/tests/test_view.rs
This is another commit like 0f3bd7fb03e2 and 8e7e32710d29. I don't know how I didn't catch all remaining instances last time :(
If applicable:
=> tests: another attempt to fix remaining flaky tests in `test_view.rs`

cli/build.rs
Since the recent move of `builds.rs` to `cli/build.rs`, incremental builds re-calcuate the version number and thus result in some re-compilation and lots of re-linking.
If applicable:
=> build: in cli build script, fix relative path to root

cli/build.rs
=> build: update rerun-if conditions to watch .git/HEAD in colocated repo

lib/src/git.rs
=> git: refactor `import_refs()`

lib/src/working_copy.rs
=> Some working-copy instrumentation and cleanup

lib/src/op_store.rs, lib/src/refs.rs, lib/src/simple_op_store.rs
=> refs: rename RefTarget::as_conflict() to as_merge()

CHANGELOG.md, cli/src/config-schema.json, cli/tests/test_git_push.rs, docs/config.md, lib/src/settings.rs
=> config: Rename `push.branch-prefix` option to `git.push-branch-prefix` and test it

lib/src/local_backend.rs
=> local_backend: don't reference uninitialized memory

docs/FAQ.md
I didn't find time to review the PR while it was out (no, I don't mean that I think it was merged too soon), so I reviewed it in my editor and made fixes while reviewing instead.
If applicable:
=> faq: minor fixes and cleanups

CHANGELOG.md, cli/src/commands/git.rs, docs/git-compatibility.md, lib/src/git.rs
=> Add support for ed25519 keys (#440)

lib/src/git.rs
=> git: ensure that remote branches never diverge

lib/tests/test_git.rs, lib/tests/test_view.rs, lib/testutils/src/lib.rs
=> test that git::import_refs() can update conflicted remote branch

lib/src/merge.rs, lib/src/merged_tree.rs, lib/src/op_store.rs, lib/src/tree.rs
=> merge: minor API cleanups

cli/src/commands/git.rs, cli/tests/test_git_clone.rs
=>  cli: clean up .git directory if "jj git clone --colocate" failed

CHANGELOG.md, cli/src/cli_util.rs, cli/tests/test_init_command.rs
=> cli: detect .git symlink as a colocated workspace

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/mod.rs, cli/src/config.rs, cli/src/config/misc.toml, cli/src/config/unix.toml, cli/src/config/windows.toml, docs/config.md, docs/config.toml, docs/tutorial.md
Discussed in #2027
If applicable:
=> Use Notepad as default editor on Windows

cli/src/cli_util.rs
=> cli: handle invalid ui.editor configuration

lib/src/working_copy.rs
=> working_copy: avoid an unused variable on Windows

cli/src/commands/mod.rs, cli/src/diff_util.rs, cli/src/merge_tools.rs, cli/src/ui.rs, cli/tests/test_diff_command.rs
=> cli: warn if diff command exited with non-zero status, attach child stderr to pager

cli/src/cli_util.rs, cli/src/commands/git.rs, lib/src/git.rs, lib/tests/test_git.rs
=> git: propagate errors for missing commits when importing refs

cli/src/commands/mod.rs, cli/src/diff_util.rs, cli/src/merge_tools.rs, lib/src/conflicts.rs, lib/src/merge.rs, lib/src/merged_tree.rs, lib/src/tree.rs, lib/src/working_copy.rs, lib/tests/test_conflicts.rs
=> Minor refactoring of `merge`/`conflict` and `merge_tree`

cli/src/merge_tools.rs, lib/src/conflicts.rs, lib/src/merge.rs, lib/src/working_copy.rs, lib/tests/test_conflicts.rs
=> conflicts: make `update_from_content()` work with only `FileId`s

cli/src/config/windows.toml, docs/config.md
Windows environments typically don't have a good pager, it seems, so let's disable pagination for now.
If applicable:
=> windows: disable pagination by default (#2040)

cli/src/cli_util.rs, cli/src/ui.rs
=> cli: fix --no-pager to persist across layered config loading

cli/src/commands/git.rs, cli/src/commands/mod.rs, cli/tests/test_git_clone.rs
=> cli: on "git clone --colocate", set up .git/info/exclude to ignore .jj dir

lib/src/working_copy.rs
=> Preparing the working copy for tree-level conflicts

cli/src/config-schema.json
=> docs: add `diff-instructions` to config schema

docs/config.md, docs/operation-log.md
Addresses the parenthetical about finding the user config toml in #2054.
If applicable:
=> docs: two small fixes

cli/src/diff_util.rs, cli/src/merge_tools.rs
=> merge_tools: rename `MergeTool` -> `ExternalMergeTool`

lib/src/default_index_store.rs, lib/src/repo.rs
=> index: rewrite topological sort by leveraging dag_walk function

lib/src/default_index_store.rs, lib/src/gitignore.rs, lib/src/local_backend.rs, lib/src/working_copy.rs, lib/src/workspace.rs
=> cleanup: use `fs:read()` instead of `File::open().read_to_end()`

docs/technical/architecture.md
=> docs: correct stale info about which backends are dynamically chosen

CHANGELOG.md, cli/src/commands/mod.rs, cli/src/config-schema.json, cli/tests/test_commit_command.rs, cli/tests/test_describe_command.rs, docs/config.md
=> cli: add support for setting default description

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/mod.rs
=> Allow editing user-specific config file outside of a repo

cli/src/merge_tools/mod.rs
=> merge_tools: extract external merge tool functions

lib/src/git.rs, lib/src/repo.rs
=> git: scan new commits all at once from multiple heads

docs/config.md
=> docs: `ui.difftool` -> `ui.diff-editor`

cli/src/merge_tools/external.rs, cli/src/merge_tools/mod.rs
=> merge_tools: move symbols to `external.rs`

docs/git-comparison.md
Based on https://github.com/martinvonz/jj/discussions/2068#discussioncomment-6717072
If applicable:
=> Small addition to index comparison

cli/src/cli_util.rs
=> add error message when running from a non-existent directory

cli/src/commands/mod.rs, cli/tests/test_chmod_command.rs
=> Minor cleanup of `jj chmod`

cli/src/config.rs, cli/tests/test_config_command.rs, cli/tests/test_duplicate_command.rs, cli/tests/test_git_clone.rs, cli/tests/test_git_colocated.rs, cli/tests/test_log_command.rs, cli/tests/test_revset_output.rs, cli/tests/test_templater.rs, cli/tests/test_workspaces.rs, lib/src/git.rs, lib/src/revset.rs, lib/src/working_copy.rs
=> cleanup: fix warnings from nightly clippy

cli/tests/test_branch_command.rs, lib/src/commit.rs, lib/src/dag_walk.rs, lib/src/default_index_store.rs, lib/src/git.rs, lib/src/repo.rs
=> index: import commits in chronological order

lib/src/working_copy.rs
=> Write conflicts from working copy snapshot on receiver side of channel

lib/src/merged_tree.rs, lib/src/working_copy.rs, lib/tests/test_merged_tree.rs
=> Get current tree value from MergedTree when snapshotting working copy

CHANGELOG.md, cli/src/commands/mod.rs, cli/tests/test_split_command.rs
=> cli: when splitting change without description, skip it on second part

cli/src/cli_util.rs, cli/tests/test_global_opts.rs
I did use `jj` to make this change :)
=> Fixed missing quote in "jj config set" help

CHANGELOG.md, Cargo.lock, Cargo.toml, cli/tests/test_revset_output.rs, docs/revsets.md, lib/Cargo.toml, lib/src/default_revset_engine.rs, lib/src/revset.rs, lib/tests/test_revset.rs
=> revset: add literal:"string" pattern syntax

lib/src/revset.rs
=> revset: remove unused MineWithoutUserName error variant

lib/src/working_copy.rs
=> More working copy refactorings for tree-level conflicts

cli/src/config/templates.toml
Figured I'd ask the question in the form of a PR. Thoughts?
---
If applicable:
=> templates: add placeholder label for no description

.github/PULL_REQUEST_TEMPLATE.md, docs/config.md, docs/templates.md
=> docs: Fix missed paths from src->cli/src move

CHANGELOG.md, docs/contributing.md
=> docs: nits

CHANGELOG.md, cli/src/template_builder.rs, cli/tests/test_commit_template.rs, docs/templates.md
=> Timestamp utc

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/mod.rs, cli/tests/test_workspaces.rs, lib/src/id_prefix.rs, lib/src/revset.rs, lib/tests/test_id_prefix.rs, lib/tests/test_revset.rs
=> revset: resolve "@" symbol's workspace id earlier (while parsing)

cli/tests/test_diffedit_command.rs
To me, this behavior seems a bit unexpected. We may want to fix it later
If applicable:
=> test_diffedit_command: Show that diffedit ignores unknown files

lib/src/default_index_store.rs, lib/src/stacked_table.rs, lib/tests/test_merge_trees.rs
=> cleanup: replace `x[n..n+l]` by `x[n..][..l]`

cli/src/cleanup_guard.rs
=> No need for Lazy in LIVE_GUARDS

cli/src/merge_tools/external.rs
There's no need for it to allocate the variable names, and the only place it's currently used can benefit from returning early if `$output` is found
If applicable:
=> Make `find_all_variables` lazy, and not allocate

lib/src/working_copy.rs
=> Fix performance regression in snapshotting

docs/design/tracking-branches.md
#1136, #1666, #1734
If applicable:
=> doc: add plan for non-tracking branches support (RFC)

cli/src/cli_util.rs, cli/src/commands/git.rs, cli/tests/test_git_remotes.rs, lib/src/git.rs
=> git: refactor `jj git remote` error handling

cli/Cargo.toml, lib/Cargo.toml, lib/gen-protos/Cargo.toml, lib/testutils/Cargo.toml
=> Use `{ workspace = true }` to appease VS Code's `Cargo.toml` parser

lib/src/backend.rs, lib/src/git_backend.rs
=> backend: reduce `BackendError` size somewhat

CHANGELOG.md, cli/src/commands/git.rs, cli/tests/test_git_fetch.rs
=> git: add --all-remotes to git fetch

cli/src/cli_util.rs, cli/src/commands/mod.rs, lib/src/merged_tree.rs, lib/src/tree_builder.rs
=> tree_builder: add a `set_or_remove()` and simplify callers

cli/src/config/colors.toml, cli/src/config/templates.toml, cli/tests/test_commit_template.rs
Also, see https://github.com/martinvonz/jj/pull/2100.
If applicable:
=> templates: colorize description_placeholder

cli/src/commit_templater.rs, cli/src/operation_templater.rs, cli/tests/test_log_command.rs, cli/tests/test_operations.rs
=> templater: make .short(negative_len) return 0-length string

cli/src/cli_util.rs, cli/src/commands/mod.rs, lib/src/merged_tree.rs, lib/src/working_copy.rs, lib/tests/test_merged_tree.rs, lib/tests/test_working_copy.rs
=> Use MergedTree more in the working copy

cli/src/commands/mod.rs, cli/src/merge_tools/mod.rs, lib/src/conflicts.rs, lib/src/merge.rs, lib/tests/test_conflicts.rs
=> Docs and cleanups for `Merge` 

CHANGELOG.md, lib/src/revset.pest, lib/src/revset.rs, lib/tests/test_revset.rs
=> revset: parse `name@remote` like operator

lib/src/backend.rs, lib/src/commit.rs, lib/src/commit_builder.rs, lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/merge.rs, lib/src/protos/git_store.proto, lib/src/protos/git_store.rs, lib/src/protos/local_store.proto, lib/src/protos/local_store.rs, lib/src/tree_builder.rs, lib/src/working_copy.rs
=> Simplify representation of root tree id

CHANGELOG.md, cli/src/config/templates.toml, cli/src/template_builder.rs, cli/src/templater.rs, cli/tests/test_commit_template.rs, cli/tests/test_templater.rs
=> templater: move empty signature placeholder to user template

cli/src/cli_util.rs, cli/src/commands/mod.rs, cli/src/merge_tools/external.rs, lib/src/backend.rs, lib/src/commit.rs, lib/src/merged_tree.rs, lib/src/protos/working_copy.proto, lib/src/protos/working_copy.rs, lib/src/store.rs, lib/src/working_copy.rs, lib/tests/test_merged_tree.rs, lib/tests/test_working_copy.rs, lib/tests/test_working_copy_concurrent.rs, lib/tests/test_working_copy_sparse.rs, lib/testutils/src/lib.rs
=> Finish making working copy support tree-level conflicts

cli/src/cli_util.rs, cli/src/commands/mod.rs, cli/src/diff_util.rs, cli/src/merge_tools/external.rs, cli/src/merge_tools/mod.rs
=> Support tree-level conflicts in `merge_tools`

cli/src/commands/mod.rs, cli/src/diff_util.rs, cli/tests/test_interdiff_command.rs, cli/tests/test_obslog_command.rs
=> Support tree-level conflicts in `diff_util`

cli/src/cli_util.rs, cli/src/commands/git.rs, cli/src/commands/mod.rs, cli/src/commit_templater.rs, cli/src/diff_util.rs, lib/src/backend.rs, lib/src/commit.rs, lib/src/commit_builder.rs, lib/src/default_revset_engine.rs, lib/src/merged_tree.rs, lib/src/repo.rs, lib/src/rewrite.rs, lib/src/tree.rs, lib/tests/test_commit_builder.rs, lib/tests/test_git.rs, lib/tests/test_id_prefix.rs, lib/tests/test_init.rs, lib/tests/test_merge_trees.rs, lib/tests/test_merged_tree.rs, lib/tests/test_mut_repo.rs, lib/tests/test_revset.rs, lib/tests/test_rewrite.rs, lib/testutils/src/lib.rs
We're getting pretty close to being able to remote the old APIs now
If applicable:
=> More migrations to the `MergedTree` API

lib/src/merged_tree.rs, lib/src/tree.rs, lib/tests/test_commit_builder.rs, lib/tests/test_diff_summary.rs
=> Delete single-tree diff iterator 

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/branch.rs, cli/src/commands/git.rs, cli/src/commands/mod.rs, cli/src/commit_templater.rs, cli/tests/test_git_fetch.rs, cli/tests/test_git_remotes.rs, lib/src/git.rs, lib/src/revset.rs, lib/tests/test_git.rs
=> git: prevent import from / creation of remote named "git"

lib/src/commit.rs, lib/src/commit_builder.rs, lib/src/merged_tree.rs, lib/src/tree.rs, lib/tests/test_commit_builder.rs, lib/tests/test_diff_summary.rs, lib/tests/test_merge_trees.rs, lib/tests/test_merged_tree.rs, lib/tests/test_revset.rs, lib/tests/test_rewrite.rs, lib/tests/test_working_copy.rs, lib/tests/test_working_copy_concurrent.rs, lib/tests/test_working_copy_sparse.rs, lib/testutils/src/lib.rs
=> Migrate more of the test  to `MergedTree` API

cli/src/cli_util.rs, cli/src/commands/git.rs, cli/src/commands/mod.rs, cli/src/commit_templater.rs, cli/src/diff_util.rs, cli/src/merge_tools/external.rs, lib/src/commit.rs, lib/src/default_revset_engine.rs, lib/src/merged_tree.rs, lib/src/repo.rs, lib/src/rewrite.rs, lib/src/working_copy.rs, lib/tests/test_commit_builder.rs, lib/tests/test_git.rs, lib/tests/test_init.rs, lib/tests/test_merge_trees.rs, lib/tests/test_merged_tree.rs, lib/tests/test_mut_repo.rs, lib/tests/test_revset.rs, lib/tests/test_rewrite.rs, lib/tests/test_working_copy.rs
=> Cleanups following migration to `MergedTree` API

cli/src/merge_tools/mod.rs
=> merge_tools: rename `MergeTool::Internal` -> `MergeTool::Builtin`

lib/src/rewrite.rs, lib/src/store.rs, lib/src/working_copy.rs, lib/tests/test_commit_builder.rs, lib/tests/test_git.rs, lib/tests/test_id_prefix.rs, lib/tests/test_init.rs, lib/tests/test_merged_tree.rs, lib/tests/test_mut_repo.rs, lib/tests/test_revset.rs, lib/tests/test_working_copy.rs, lib/testutils/src/lib.rs
=> Minor `MergedTree`-related cleanups

lib/src/op_heads_store.rs
=> op_heads_store: propagate errors from `OpStore`

cli/src/diff_util.rs, cli/tests/test_diff_command.rs
=> Fix a crash in diff stat (`jj diff --stat` etc) and trim paths to fit

lib/src/merge.rs, lib/src/merged_tree.rs, lib/tests/test_merged_tree.rs
=> Fix `jj restore` from conflict with tree-level conflicts

cli/src/cli_util.rs, cli/src/commands/mod.rs, cli/tests/test_working_copy.rs, lib/src/working_copy.rs, lib/tests/test_working_copy.rs, lib/tests/test_working_copy_concurrent.rs
=> Add hint when snapshot fails due to large file

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/diff_util.rs, cli/src/progress.rs, cli/src/text_util.rs, cli/tests/test_diff_command.rs
=> cli: make diff stat calculate path length based on unicode width

lib/src/conflicts.rs
=> conflicts: leverage `Merge::map()` in `materialize_merge_result()`

lib/src/store.rs
=> store: don't include cached objects in `Debug` format

cli/src/template_builder.rs, cli/src/template_parser.rs, cli/tests/test_templater.rs, docs/templates.md
=> templater: add boolean literals

CHANGELOG.md
=> changelog: more orphan entries under headings

cli/src/cli_util.rs, cli/src/commands/mod.rs
=> cli: label working copies when writing commit summaries

docs/FAQ.md
=> faq: add entry about accidentally amended working copy

lib/src/repo_path.rs
=> repo_path: avoid repeated copying of `PathBuf` in `to_fs_path()`

lib/tests/test_revset.rs, lib/tests/test_view.rs
=> tests: remove `set_git_ref_target()` with arbitrary ref name

cli/src/cli_util.rs, cli/tests/test_global_opts.rs
Cc: https://github.com/martinvonz/jj/issues/2254
If applicable:
=> cli docs: document that --config-toml can be repeated

docs/git-compatibility.md
As suggested by @yuja in
https://github.com/martinvonz/jj/issues/1841#issuecomment-1720451152
=> docs: mention `git pack-refs` for co-located repos

CHANGELOG.md, cli/src/config.rs, cli/src/config/misc.toml, cli/src/config/revsets.toml, cli/tests/test_builtin_aliases.rs, docs/revsets.md
=> feat: add trunk alias with default to main/master/root

lib/src/content_hash.rs, lib/src/lib.rs, lib/src/merged_tree.rs, lib/tests/test_merged_tree.rs, lib/testutils/src/lib.rs, lib/testutils/src/test_backend.rs
=> Add commit backend for tests, fix bug in `MergedTree`

docs/revsets.md
=> docs: use branch@remote syntax in trunk() example

cli/src/merge_tools/builtin.rs, lib/src/merged_tree.rs, lib/tests/test_conflicts.rs, lib/tests/test_refs.rs, lib/tests/test_rewrite.rs, lib/tests/test_view.rs, lib/tests/test_working_copy.rs, lib/tests/test_working_copy_concurrent.rs, lib/tests/test_working_copy_sparse.rs, lib/testutils/src/lib.rs
=> Use the new test backend more in tests, fix another `MergedTree` bug

lib/src/git.rs
=> git: update comment about remote-tracking branches to be exported

lib/src/tree.rs
=> tree: leverage `Merge::try_map()` when reading file contents to merge

lib/src/revset.rs
=> revset: simplify RevsetAliasesMap getters to not construct id

CHANGELOG.md
=> changelog: fix broken link to revsets.md

lib/tests/test_default_revset_graph_iterator.rs, lib/tests/test_diff_summary.rs, lib/tests/test_index.rs, lib/tests/test_load_repo.rs, lib/tests/test_merge_trees.rs, lib/tests/test_revset.rs, lib/tests/test_rewrite.rs, lib/tests/test_workspace.rs, lib/testutils/src/lib.rs
=> test: use test backend in most remaining tests too

lib/src/git.rs, lib/tests/test_git.rs
=> git: make fetch() import local tags in addition to remote branches

docs/config.md
=> docs: add missing word to config.md

docs/design/tracking-branches.md
The original idea was to completely replace git_refs with remotes["git"] by introducing "forgotten" state, but it turned out to break "fetch && undo" scenario. There are other ways around, but they also have problems:
* Sets tombstone on forgotten/deleted remote refs, exports remote refs without comparing to the known refs.
* `jj undo` would need to insert tombstone by diffing old/new views.
* `jj branch forget` would need to preserve the `@git` branch whereas the other remote branches would be forgotten.
* Always overwrites remote refs on export.
* `jj git export` without importing would discard remote refs.
So, I decided to not remove git_refs. Apparently, it also improves the undo behavior. In the new model, `jj git fetch && jj undo && jj git fetch` works even if git_refs isn't rolled …
=> doc: adjust tracking branches design to deal with "fetch/push && undo"

docs/config.md
=> docs: use code block for `ui.pager` config example

cli/tests/test_git_colocated.rs, lib/src/git.rs, lib/tests/test_git.rs
=> git: add hack to unset Git HEAD by using random ref name

CHANGELOG.md, cli/src/config/misc.toml, cli/tests/test_chmod_command.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_git_push.rs, cli/tests/test_immutable_commits.rs, cli/tests/test_obslog_command.rs, cli/tests/test_resolve_command.rs, cli/tests/test_restore_command.rs, cli/tests/test_tree_level_conflicts.rs, cli/tests/test_workspaces.rs
I'll update documentation separately soon.
If applicable:
=> cli: enable tree-level conflicts by default

lib/src/git_backend.rs, lib/src/revset.rs
=> git_backend: on read_commit(), fall back to importing extras as needed

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/mod.rs, cli/tests/test_gitignores.rs, lib/src/local_working_copy.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_local_working_copy_sparse.rs
=> Fix updating to commit where ignored file is tracked (#976)

README.md
This makes a one-word change suggested in
https://discord.com/channels/968932220549103686/968932220549103689/1160641833349689464
Thanks to @solson for the idea.
=> README.md: "quite" -> "fairly" feature complete

cli/src/commands/mod.rs
=> cli: describe what workspaces are in `jj workspace` help

cli/src/commands/operation.rs, cli/tests/test_git_import_export.rs, lib/src/git.rs, lib/tests/test_git.rs
=> git: refactor and migrate `export_refs()`, make non-colocated `undo` preserve `git_refs`

lib/src/refs.rs, lib/src/repo.rs
=> repo: rewrite diffing of named refs to compare each targets pair

cli/src/commands/git.rs, lib/src/git.rs, lib/src/refs.rs, lib/src/view.rs
=> add iterator of local/remote branch pairs, use it to compute push action

cli/src/cli_util.rs, cli/src/commands/debug.rs, lib/src/lib.rs, lib/src/local_working_copy.rs, lib/src/working_copy.rs, lib/src/workspace.rs, lib/tests/test_local_working_copy_sparse.rs
=> Start defining a working copy trait

cli/src/commands/branch.rs, cli/src/commands/git.rs, cli/src/commands/operation.rs, cli/src/commit_templater.rs, cli/tests/test_concurrent_operations.rs, cli/tests/test_debug_command.rs, cli/tests/test_operations.rs, cli/tests/test_workspaces.rs, lib/src/op_store.rs, lib/src/refs.rs, lib/src/revset.rs, lib/src/simple_op_store.rs, lib/src/view.rs, lib/tests/test_git.rs, lib/tests/test_view.rs
=> view: migrate in-memory structure to per-remote branches map

lib/src/default_index_store.rs, lib/src/default_submodule_store.rs, lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/repo.rs, lib/src/simple_op_heads_store.rs, lib/src/simple_op_store.rs
I copied the example set by `DefaultSubmoduleStore`.
If applicable:
=> backends: deduplicate definition of backend names

lib/src/repo.rs
=> repo: levarage the new static <backend type>::name() functions

cli/tests/test_branch_command.rs
=> tests: remove stale comment about remote named "git"

cli/src/commands/branch.rs, cli/src/commands/git.rs, cli/src/commands/mod.rs, cli/src/commit_templater.rs, lib/src/git.rs, lib/src/op_store.rs, lib/src/repo.rs, lib/src/revset.rs, lib/src/simple_op_store.rs, lib/src/view.rs, lib/tests/test_git.rs, lib/tests/test_mut_repo.rs, lib/tests/test_revset.rs, lib/tests/test_rewrite.rs, lib/tests/test_view.rs
=> view: prepare for adding tracking state to remote branches

cli/src/cli_util.rs, cli/src/commands/debug.rs, cli/src/commands/mod.rs, lib/src/local_working_copy.rs, lib/src/working_copy.rs, lib/src/workspace.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_local_working_copy_concurrent.rs, lib/tests/test_local_working_copy_sparse.rs, lib/testutils/src/lib.rs
=> Store and pass abstract working copy types everywhere (except for a few debug commands)

lib/src/git_backend.rs
=> git: use forward slashes in relative path to backing git repo

docs/revsets.md
=> docs: mention the `immutable_heads()` in our list of built-in aliases

CHANGELOG.md, cli/src/commands/debug.rs, cli/tests/test_chmod_command.rs, lib/src/merge.rs, lib/tests/test_conflicts.rs
=> Allow resolving conflicts in executable files

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/branch.rs, cli/src/commands/git.rs, cli/tests/test_git_fetch.rs, lib/src/git.rs, lib/src/str_util.rs, lib/tests/test_git.rs
=> cli: parse "git fetch --branch" parameter as string pattern

docs/github.md
=> docs: fix broken Markdown in `github.md`, plus various cleanups

CHANGELOG.md, cli/src/commands/git.rs, cli/tests/test_git_push.rs, lib/src/view.rs
=> cli: add string pattern support to "git push --branch"

cli/src/cli_util.rs, cli/src/commands/mod.rs, cli/src/diff_util.rs, cli/src/merge_tools/builtin.rs, cli/src/merge_tools/external.rs, lib/src/conflicts.rs, lib/src/local_working_copy.rs, lib/src/merge.rs, lib/src/merged_tree.rs, lib/src/store.rs, lib/src/tree.rs, lib/tests/test_commit_builder.rs, lib/tests/test_diff_summary.rs, lib/tests/test_merged_tree.rs
=> Propagate backend errors in diff iterator

CHANGELOG.md, cli/src/commit_templater.rs, cli/tests/test_commit_template.rs, docs/templates.md
=> templater: add local/remote_branches keywords

cli/src/commands/abandon.rs, cli/src/commands/backout.rs, cli/src/commands/cat.rs, cli/src/commands/checkout.rs, cli/src/commands/chmod.rs, cli/src/commands/commit.rs, cli/src/commands/config.rs, cli/src/commands/describe.rs, cli/src/commands/diff.rs, cli/src/commands/diffedit.rs, cli/src/commands/mod.rs
=> Move commands in separate files

cli/src/commands/duplicate.rs, cli/src/commands/mod.rs
=> commands: move duplicate code to duplicate.rs

cli/src/commands/edit.rs, cli/src/commands/mod.rs
=> commands: move edit code to edit.rs

cli/src/commands/files.rs, cli/src/commands/mod.rs
=> commands: move files code to files.rs

lib/src/backend.rs
The idea was to support phases like in hg, but that hasn't happened yet. We can add back this simple enum if we do add support for phases.
If applicable:
=> backend: delete unused `Phase` enum

lib/src/rewrite.rs
=> rewrite: replace use of "lift"ed function application with try_collect()

cli/src/commands/rebase.rs
=> cli rebase: Move misplaced paragraph, fixup to 8bc3f5fd67

docs/FAQ.md
=> add FAQ for divergent changes

cli/tests/test_git_colocated.rs, lib/src/git.rs
Closes: #2210
Depends on: #2330 
If applicable:
=> git: preserve HEAD when possible

CHANGELOG.md, cli/src/commands/branch.rs, cli/tests/test_branch_command.rs
=> cli: add "branch list [NAMES]..." filter

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: release version 0.11.0

CHANGELOG.md
As reported by several people on Discord.
If applicable:
=> Fix 0.11 title in CHANGELOG.md

cli/src/cli_util.rs, cli/src/commands/mod.rs, lib/src/rewrite.rs, lib/tests/test_rewrite.rs
=> cli: add a function for restoring part of a tree from another tree

cli/src/merge_tools/builtin.rs, cli/src/merge_tools/external.rs, lib/src/rewrite.rs
Should make these things faster at Google once `diff_stream()` is concurrent (#2517)
If applicable:
=> Use `MergedTree::diff_stream()` a bit more

docs/contributing.md
=> contributing.md: suggest making the `gh-pages` branch immutable

cli/src/merge_tools/external.rs, cli/tests/test_diff_command.rs
=> merge_tools: do not follow or change permission of symlinks

Cargo.toml, cli/Cargo.toml, lib/Cargo.toml
=> cargo: sort dependencies list alphabetically

cli/src/commands/cat.rs, cli/src/diff_util.rs, lib/src/conflicts.rs, lib/src/local_working_copy.rs
=> Prepare for reading file contents concurrently when checking out

cli/src/commands/branch.rs, cli/tests/test_branch_command.rs
=> cli: include branch names in bulk branch creation/update warning

lib/src/repo.rs
=> repo: reimplement DirtyCell without using unsafe

cli/src/diff_util.rs, lib/src/conflicts.rs
=> More preparations for reading files concurrently

cli/src/diff_util.rs
=> diff_utils: return `&str` from `basic_diff_file_type()`

CHANGELOG.md, cli/src/commands/branch.rs, cli/tests/test_branch_command.rs, cli/tests/test_git_colocated.rs, cli/tests/test_git_fetch.rs, cli/tests/test_git_push.rs, cli/tests/test_git_remotes.rs, cli/tests/test_log_command.rs, cli/tests/test_next_prev_commands.rs
=> cli: disallow to create new branch by "jj branch set"

cli/src/cli_util.rs, cli/src/commands/workspace.rs, lib/src/op_store.rs, lib/src/simple_op_store.rs
=> better `read_operation()` errors 

docs/git-comparison.md
This question was raised on the discord, it might be helpful for others.
If applicable:
=> git-comparison.md: show log of ancestors

cli/src/cli_util.rs, cli/src/commands/operation.rs, lib/src/dag_walk.rs, lib/src/default_index_store.rs, lib/src/op_heads_store.rs, lib/src/operation.rs, lib/src/transaction.rs
=> operation: propagate OpStoreError from `parents()`

docs/git-comparison.md
=> docs: add forgotten code tags

cli/tests/test_commit_command.rs, cli/tests/test_diff_command.rs
=> clippy: fix new issues spotted by nightly version

Cargo.lock, lib/Cargo.toml, lib/src/merged_tree.rs, lib/src/tree.rs
=> Drop dependency on ouroborus

lib/src/local_working_copy.rs, lib/src/protos/working_copy.proto, lib/src/protos/working_copy.rs
=> working_copy: don't randomize file states order by intermediate HashMap

lib/src/merged_tree.rs
=> Inline non-recursive iterators in merged_tree.rs

lib/src/merged_tree.rs
=> merged_tree: remove dead code from ConflictIterator

cli/src/commands/diff.rs
=> cli diff: add short description, more details to `jj help`

cli/src/cli_util.rs, cli/src/config.rs, cli/src/ui.rs
=> cli: show executable name in error message, include underlying error details

lib/src/fsmonitor.rs, lib/src/local_working_copy.rs
=> working_copy: lazily construct file_states BTreeMap

cli/src/commands/new.rs, cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/src/commands/rebase.rs, lib/src/git.rs, lib/src/repo.rs, lib/src/revset.rs, lib/src/rewrite.rs, lib/tests/test_revset.rs
=> Add a helper for evaluating programmatic revset

cli/src/commands/init.rs, cli/tests/test_init_command.rs
=> cli: show hint of non-tracking remote branches on "jj init --git-repo"

lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/local_working_copy.rs, lib/src/merged_tree.rs, lib/src/repo_path.rs, lib/src/tree.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_merged_tree.rs
=> repo_path: trivial API cleanup

lib/src/rewrite.rs, lib/tests/test_rewrite.rs
=> rewrite: fix check for newly-empty commit in optimized path

lib/src/local_working_copy.rs, lib/src/matchers.rs, lib/src/merged_tree.rs, lib/src/repo_path.rs, lib/src/tree_builder.rs
=> repo_path: API cleanup

lib/src/local_working_copy.rs, lib/src/repo_path.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_local_working_copy_sparse.rs
=> working_copy: lazy file states loading rework, wrap proto data

lib/src/merged_tree.rs
=> merged_tree: simplify diff iterator a bit

docs/git-compatibility.md, docs/technical/conflicts.md
=> docs: update description of conflicts to be about tree-level conflicts

cli/examples/custom-backend/main.rs, lib/src/backend.rs, lib/src/commit_builder.rs, lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/repo.rs, lib/src/store.rs, lib/testutils/src/test_backend.rs
=> signing: pass SigningFn by reference

cli/examples/custom-backend/main.rs, cli/examples/custom-command/main.rs, cli/examples/custom-working-copy/main.rs, cli/src/commands/bench.rs, cli/src/commands/debug.rs, cli/src/commands/git.rs, cli/src/commands/mod.rs, cli/src/commands/operation.rs, cli/src/commands/util.rs, cli/src/commands/workspace.rs
=> Naming cleanup in cli/src/commands/

cli/examples/custom-working-copy/main.rs, lib/src/repo.rs, lib/src/workspace.rs, lib/tests/test_git.rs
=> repo, workspace: remove 'static lifetime bound from initializer functions

cli/src/commands/debug.rs, cli/src/commands/util.rs
Replaces #2661, since GitHub decided to close that.
If applicable:
=> Split up cmd_util() and cmd_debug() into one function per subcommand (again)

cli/src/cli_util.rs, cli/tests/test_init_command.rs, lib/src/git_backend.rs, lib/src/workspace.rs
=> git_backend: don't fully canonicalize .git symlink

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: release version 0.12.0

lib/src/git_backend.rs, lib/tests/test_git.rs, lib/tests/test_init.rs
=> git_backend: do not try to resolve git_target path as working directory path

lib/src/index.rs
=> index: remove unneeded Any trait bound from MutableIndex

Cargo.lock, Cargo.toml, cli/tests/test_git_clone.rs, lib/src/git_backend.rs
=> cargo: bump gix and git2, minor code & test fixes

CHANGELOG.md, cli/src/config-schema.json, cli/tests/test_branch_command.rs, cli/tests/test_builtin_aliases.rs, cli/tests/test_commit_template.rs, cli/tests/test_git_clone.rs, cli/tests/test_git_colocated.rs, cli/tests/test_git_fetch.rs, cli/tests/test_git_push.rs, cli/tests/test_init_command.rs, docs/config.md, docs/design/tracking-branches.md, docs/github.md, lib/src/settings.rs, lib/tests/test_git.rs
=> git: turn git.auto-local-branch off by default

lib/src/default_index/mod.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/default_index/store.rs, lib/src/index.rs
=> index: prep for propagating read errors + minor cleanup

docs/config.md
=> docs `config.md` Vim instructions: link to the Wiki instead of a gist

lib/src/default_index/readonly.rs
=> index: update file format comment about ReadonlyIndexSegment

lib/src/default_index/readonly.rs, lib/src/default_index/store.rs
=> index: attach file name to both io and corrupt errors

cli/src/cli_util.rs
removed_heads..added_heads won't stop if new head is added on top of non-head commit for example. I'm not pretty sure, but I think what we need here is ::added_heads & ~::old_heads.
#2729
If applicable:
=> cli: don't look for added/resolved conflicts across old/new heads

README.md
As noted by Martin and Waleed on Discord.
Change-Id: I9cba734774a7e89dfd65c8202e76c2f4
=> readme: do some cleanup

Cargo.lock, Cargo.toml, lib/Cargo.toml, lib/src/default_index/readonly.rs, lib/src/lock.rs, lib/src/stacked_table.rs
=> clean up remaining `read`/`write_u32()`

cli/src/cli_util.rs, lib/src/default_index/store.rs, lib/src/git.rs, lib/src/repo.rs, lib/tests/test_git.rs, lib/tests/test_index.rs, lib/tests/test_mut_repo.rs
=> index, repo: propagate store error from topological sort function

cli/src/cli_util.rs, cli/tests/test_alias.rs
=> cli: don't panic on empty alias substitution

Cargo.lock, Cargo.toml, cli/src/merge_tools/builtin.rs
WIP -- need to actually release a new version of `scm-record` so that we don't have a `git` dependency in Cargo.toml.
If applicable:
=> merge_tools: upgrade version of scm-record

cli/src/diff_util.rs, lib/src/local_working_copy.rs
=> Read file contents concurrently

cli/src/cli_util.rs, cli/src/commands/debug.rs, cli/src/commands/operation.rs, cli/tests/test_operations.rs, lib/src/lib.rs, lib/src/op_heads_store.rs, lib/src/op_walk.rs, lib/src/operation.rs, lib/src/repo.rs
=> op_walk: extract operation id resolution helpers from cli

lib/src/operation.rs
=> operation: make parent_ids() return slice instead of Vec reference

docs/branches.md
=> docs: reorder and partially rewrite remote branches section to reflect changes

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: release version 0.13.0

cli/tests/test_git_import_export.rs, lib/src/default_revset_engine.rs, lib/src/id_prefix.rs, lib/src/object_id.rs, lib/src/op_store.rs, lib/src/op_walk.rs, lib/src/refs.rs, lib/src/settings.rs, lib/src/simple_op_store.rs, lib/tests/test_commit_builder.rs, lib/tests/test_local_working_copy.rs
=> op_store: add resolve_operation_id_prefix() trait method that uses readdir()

mkdocs.yml
The website will also adjust to the system default theme now.  I mostly did this because I am a darkkmode user and we didn't provide it yet.
=> docs: Make the website's theme adjustable.

lib/src/default_index/composite.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/default_index/revset_engine.rs, lib/src/index.rs, lib/src/repo.rs, lib/src/revset.rs, lib/tests/test_index.rs, lib/tests/test_revset.rs
=> Move change_id_index() from Revset to Index

lib/src/default_index/composite.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/index.rs, lib/src/repo.rs, lib/tests/test_index.rs
=> index: move lifetimed change_id_index() to MutableIndex, rename 'static version

lib/src/git.rs, lib/src/git_backend.rs, lib/tests/test_git.rs
=> git_backend: teach "format.tree-level-conflicts" config by constructor

cli/src/cli_util.rs
=> cli: fix missing word in help of --ignore-working-copy

cli/src/commands/debug.rs
=> cli: run "debug index"/"reindex" without loading repo

cli/src/cli_util.rs, cli/src/diff_util.rs
=> cli: group diff formatting options in help

lib/src/operation.rs, lib/src/repo.rs
=> operation: remove operation::View wrapper in favor of view::View

cli/src/commands/operation.rs, cli/tests/test_operations.rs, lib/src/op_walk.rs, lib/tests/test_operations.rs
=> cli: run "op abandon" without loading repo, reject --at-op

cli/src/cli_util.rs, cli/src/commands/operation.rs, cli/src/operation_templater.rs, cli/tests/test_concurrent_operations.rs, lib/src/op_walk.rs
=> cli: run "op log" without loading repo or merging concurrent ops

lib/src/local_working_copy.rs, lib/src/protos/working_copy.proto, lib/src/protos/working_copy.rs
By marking it reserved, we prevent accidental use. We can still read working copy protos that have the field.
If applicable:
=> working_copy: mark commit_id field in proto reserved

cli/src/cli_util.rs, cli/src/commands/init.rs, cli/src/commands/workspace.rs
Extracted from #2813
If applicable:
=> cli: minor snapshot() API cleanup

cli/src/commands/operation.rs, cli/tests/test_concurrent_operations.rs, cli/tests/test_debug_command.rs, cli/tests/test_operations.rs, cli/tests/test_workspaces.rs, lib/src/op_store.rs, lib/src/protos/op_store.proto, lib/src/protos/op_store.rs, lib/src/repo.rs, lib/src/simple_op_store.rs, lib/src/view.rs, lib/tests/test_mut_repo.rs, lib/tests/test_operations.rs, lib/tests/test_view.rs
=> view: drop tracking of public heads

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/operation.rs, cli/src/config/templates.toml, cli/src/operation_templater.rs, cli/tests/test_concurrent_operations.rs, cli/tests/test_debug_command.rs, cli/tests/test_operations.rs, cli/tests/test_workspaces.rs, docs/templates.md, lib/src/op_store.rs, lib/src/repo.rs, lib/src/simple_op_store.rs, lib/tests/test_commit_concurrent.rs, lib/tests/test_operations.rs
=> Add virtual root operation

lib/src/repo.rs
=> repo: optimize enforce_view_invariants() to not traverse ancestors until root

cli/src/commands/operation.rs, lib/src/op_walk.rs, lib/src/simple_op_store.rs, lib/tests/test_operations.rs
=> follow up for virtual root operation

lib/src/git.rs, lib/src/git_backend.rs
=> git_backend: ensure no-gc refs are created for reimported head commits

cli/src/cli_util.rs, cli/src/commands/branch.rs
Needed in another upcoming diff, as Gerrit needs to parse remote names for pushing refs.
=> cli: move `RepoBranchName(Pattern)` to `crate::cli_utils`

flake.nix
Summary: Pure QOL improvement, not that this was too awful as it stood. But this ultimately makes all builds faster, effectively for free; on my Linux machine, debug link time for jj-cli goes from 3s to 1s.
This was originally submitted as part of https://github.com/martinvonz/jj/pull/1864, and backed out as part of https://github.com/martinvonz/jj/pull/1982, because the default `mold` package did not have the proper "wrapper script" that allowed it to find the right external libraries. Using the `mold-wrapped` package however fixes this.
On top of that, let's go ahead and make `mold` the default linker in the Nix package/flake as well; this should improve the `nix build` speed since a lot of tests need to be linked.
On my machine, the following command, which causes a relink of all tests …
=> nix: use mold linker on Linux

CHANGELOG.md, cli/src/commands/mod.rs, cli/src/commands/tag.rs, cli/tests/test_tag_command.rs
=> Implement `tag list` command.

lib/tests/test_conflicts.rs
=> conflicts: test materialization with with negative snapshots

CHANGELOG.md, lib/src/local_working_copy.rs, lib/tests/test_local_working_copy.rs
=>  working_copy: don't follow symlinks when visiting files in gitignored directory

cli/src/commands/util.rs, cli/tests/test_util_command.rs
When looking at how workspaces behave when their operation doesn't exist, I tried to create such a situation by abandoning operations (in another workspace) and then GCing, but found that I could only prune old operations. Here's a patch that allows immediate pruning.
The name of the param ("--prune") and the accepted value ("now") is chosen to be the same as Git. Right now that's the only value we support, but this is forwards compatible with expanding what we accept as the pruning time.
The commit message below was autopopulated and I will leave it here:
This only affects pruning of the operation log for now, and only supports the string "now" for now.
If applicable:
=> util gc: allow specifying prune time

lib/src/git_backend.rs
=> git_backend: fix import_head_commits() to not issue duplicated ref edits

docs/FAQ.md
It seems that "amended" is not clear enough for users. So use simpler terms.
Suggestion from ilyagr in [Discord](https://discord.com/channels/968932220549103686/1201196831653236756/1201268055678931147).
=> FAQ: Make a question clearer.

docs/windows.md, mkdocs.yml
I discovered there's at least one other jj user on Windows after [a question came up in chat](https://discord.com/channels/968932220549103686/1200419885008830666) about dealing with `@` being part of PowerShell's syntax. I thought it would be a good idea to list out the things Windows users probably need to be aware of.
If applicable:
=> docs: add notes for Windows users

lib/src/default_index/store.rs
=> index: on reinit(), delete all segment files to save disk space

cli/src/cli_util.rs
This gives the ability for custom extension to run startup code against the `CommandHelper` before anything else happens.  For instance, auto-configuring user info in a corporate environment.
If applicable:
=> cli_util: allow extensions to run custom code before all commands

cli/src/cli_util.rs, cli/src/commands/debug.rs, cli/src/commands/sparse.rs, cli/src/commands/workspace.rs, cli/tests/test_edit_command.rs, cli/tests/test_global_opts.rs, cli/tests/test_next_prev_commands.rs, lib/src/repo.rs
=> cli: better internal error formatting

cli/src/commands/workspace.rs
=> cli: print "workspace root" without loading repo

cli/src/cli_util.rs, cli/src/commands/git.rs, cli/src/commands/init.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_init_command.rs, cli/tests/test_next_prev_commands.rs, cli/tests/test_resolve_command.rs, cli/tests/test_working_copy.rs
=> cli: better user error formatting

cli/src/cli_util.rs, cli/src/git_util.rs, cli/src/merge_tools/builtin.rs, cli/src/merge_tools/external.rs, cli/src/merge_tools/mod.rs, cli/src/template_parser.rs, cli/tests/test_git_colocated.rs, cli/tests/test_git_import_export.rs, lib/src/backend.rs, lib/src/default_index/readonly.rs, lib/src/default_index/store.rs, lib/src/fsmonitor.rs, lib/src/git.rs, lib/src/git_backend.rs, lib/src/local_working_copy.rs, lib/src/op_store.rs, lib/src/repo.rs, lib/src/revset.rs, lib/src/signing.rs, lib/src/simple_op_store.rs, lib/src/tree.rs, lib/src/working_copy.rs, lib/src/workspace.rs
=> clean up ": {source}" error message

CHANGELOG.md, cli/src/config/colors.toml, cli/src/diff_util.rs, cli/tests/common/mod.rs, cli/tests/test_diff_command.rs
fixes https://github.com/martinvonz/jj/issues/2757
If applicable:
=> don't try to diff binary files

cli/src/commands/util.rs, cli/tests/cli-reference@.md.snap
=> document that `jj util completion` defaults to bash

CHANGELOG.md, cli/src/commands/util.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_shell_completion.rs
as suggested in https://github.com/martinvonz/jj/pull/2941#discussion_r1477417234
If applicable:
=> cli: use a positional argument for `jj util completion`

CHANGELOG.md, cli/src/template_builder.rs, docs/templates.md
=> templater: add surround(prefix, suffix, content) function

docs/contributing.md
We want to avoid conflicts of interest (both real and apparent). Better to document this before it happens.
By the way, Ilya and I both work for Google and we have approved lots of each others' PRs, but we work in very different parts of the company and I don't think any of the PRs have been specific to Google's interests.
If applicable:
=> docs: explain that approving your coworker's PRs should be avoided

cli/src/cli_util.rs, cli/tests/test_global_opts.rs
=> cli: suggest "jj git init" if workspace looks like a plain git repo

cli/src/commands/git.rs, cli/src/commands/init.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_git_init.rs
=> cli: rename `jj git init --colocated` flag to `--colocate`, fix doc

cli/src/config/templates.toml
=> templates: use surround() function in default "show" template

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: release version 0.14.0

cli/src/commands/split.rs
This commit is intended to improve readability and makes no functional changes.
=> Add comments to cmd_split() and rename some variables

docs/config.md, docs/config.toml
Someone on Discord asked this exact question, but these options apparently weren't documented when they were added in the `0.7.0` release.
If applicable:
=> docs: document `git.fetch` and `git.push` config options

cli/src/template.pest, cli/src/template_builder.rs, cli/src/template_parser.rs, docs/templates.md
=> templater: parse negative integer as unary operator and literal

docs/git-comparison.md
=> document the jj equivalent of `git reset --soft`

lib/src/repo_path.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_merged_tree.rs, lib/tests/test_rewrite.rs
@yuja, @martinvonz, does the last commit look correct to you?
=> Code cleanup, mostly suggested by clippy

lib/src/repo.rs
=> Use `Transaction` API for adding initial operation in `ReadonlyRepo::init()`

CHANGELOG.md, cli/src/template_builder.rs, cli/tests/test_commit_template.rs, docs/templates.md
=> templater: add a local() method on Timestamps (#2900)

lib/src/default_index/composite.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs
=> index: remove unused flag field, compact parent encoding

cli/src/config/colors.toml
=> cli: change `workspace@` symbol color to green (the color of `HEAD@git`)

lib/src/default_index/store.rs
=> index: make reindexing message less scary

lib/tests/test_git.rs
=> tests: fix concurrent git read/write test to retry on ref lock contention

cli/src/commands/util.rs, cli/tests/cli-reference@.md.snap, docs/install-and-setup.md, flake.nix
The command was updated and the docs were forgotten
If applicable:
=> completion: Update docs for new style with positional argument

CHANGELOG.md, cli/src/commands/rebase.rs, cli/tests/test_abandon_command.rs, cli/tests/test_rebase_command.rs, lib/src/rewrite.rs, lib/tests/test_rewrite.rs
=> Stop simplifying ancestor merges

lib/src/gpg_signing.rs, lib/tests/test_gpg.rs
=> signing: change default gpg program, add --keyid-format option accordingly

.github/workflows/codespell.yml
This seems like it might have been some debugging leftover or copy-and-paste error?
=> github: fix codespell ignore list

lib/tests/test_gpg.rs
=> tests: disable most gpg integration tests on Windows

docs/testimonials.md, mkdocs.yml
Show our positive reviews to the world. It's also not completly serious, in a similar fashion to Phabricator.
[Rendered](https://github.com/martinvonz/jj/blob/push-rvuprqxytrtu/docs/testimonials.md)
cc @thoughtpolice
=> docs: Add a Testmonials page.

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/git.rs, cli/src/commands/init.rs, cli/tests/test_git_init.rs, cli/tests/test_global_opts.rs, cli/tests/test_init_command.rs, docs/git-comparison.md, docs/git-compatibility.md, docs/github.md, lib/src/workspace.rs
=> cli: unblock "jj git init --colocate" in existing Git repo directory

cli/src/commit_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, cli/src/templater.rs, cli/tests/test_log_command.rs, cli/tests/test_operations.rs
=> templater: add runtime error handling

cli/src/merge_tools/builtin.rs
This make :builtin render conflicts as conflict markers instead of panicking. To support conflicts properly, we also need to parse the conflict markers (calling `update_from_content()`) after the user closes the editor.
If applicable:
=> merge-tools: make :builtin materialize conflicts

cli/src/template_builder.rs, cli/src/templater.rs, cli/src/time_util.rs
=> templater: propagate <out-of-range date> as an error

cli/src/cli_util.rs
=> cli: don't use "check-out" as a verb (because it's not)

docs/revsets.md
=> docs: update revset alias example to something very different from builtins

cli/src/git_util.rs, cli/src/merge_tools/external.rs, lib/src/gpg_signing.rs, lib/src/ssh_signing.rs
=> signing, cli: ensure child processes are wait()ed on I/O error

cli/src/cli_util.rs, cli/src/commands/abandon.rs, cli/src/commands/next.rs, cli/src/commands/operation.rs, cli/src/commands/status.rs, cli/src/commands/workspace.rs, cli/src/commit_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs
=> templater: code cleanup + prep for generic templating support

CHANGELOG.md, cli/src/commands/config.rs, cli/src/config/colors.toml, cli/src/config/templates.toml, cli/src/generic_templater.rs, cli/src/lib.rs, cli/src/template_builder.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_config_command.rs
=> templater: add generic templating, migrate `config list` as example

cli/src/cli_util.rs, cli/src/commands/checkout.rs, cli/src/commands/commit.rs, cli/src/commands/describe.rs, cli/src/commands/new.rs, cli/src/commands/squash.rs, cli/src/description_util.rs
=> cli: move join_message_paragraphs() to description_util

Cargo.lock, cli/tests/common/mod.rs
=> cargo: upgrade chrono from 0.4.34 to 0.4.35

cli/tests/test_diffedit_command.rs, cli/tests/test_git_colocated.rs, cli/tests/test_git_push.rs, cli/tests/test_next_prev_commands.rs, cli/tests/test_squash_command.rs, cli/tests/test_unsquash_command.rs
=> tests: avoid deprecated `jj co`

CHANGELOG.md, Cargo.lock, Cargo.toml, lib/proc-macros/Cargo.toml
=> Try to fix publishing to crates.io

lib/src/default_index/composite.rs, lib/src/default_index/mod.rs, lib/src/default_index/rev_walk.rs, lib/tests/test_index.rs
=> index: hide walk_revs() and related types

CHANGELOG.md
=> changelog: clarify that commit signing support is partial

cli/src/command_error.rs, cli/tests/test_global_opts.rs, cli/tests/test_revset_output.rs, lib/src/local_working_copy.rs, lib/src/repo_path.rs
=> repo_path: show more detailed error if filesystem path failed to parse

cli/src/commit_templater.rs
=> commit_templater: allow extension methods to capture repo

docs/install-and-setup.md
=> Add archlinux instructions to install-and-setup.md

CHANGELOG.md, cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/debug.rs, cli/src/commit_templater.rs, cli/src/lib.rs, cli/src/revset_util.rs, cli/src/template_builder.rs, cli/tests/test_commit_template.rs, cli/tests/test_immutable_commits.rs, docs/templates.md
=> commit_templater: add self.immutable() method

cli/src/commands/debug.rs, cli/tests/test_debug_command.rs
Sometimes only a tree has been created, so we shouldn't require a commit for `jj debug tree`.
If applicable:
=> debug-tree: allow looking up tree by path and id, not just revision

docs/config.md
Does this warrant a changelog entry ?
If applicable:
=> docs: mention the signing key can be a file path too

cli/src/command_error.rs, cli/tests/test_git_fetch.rs
=> cli: don't bury GitImportError sources

cli/tests/test_branch_command.rs, cli/tests/test_revset_output.rs, lib/src/revset.rs, lib/src/str_util.rs
Fixes #3222 
This does not really fix the issue per-se but it should make it much easier to diagnostic the issue and move on. I'm unsure if we want something more substantial now or if this will be enough to direct users to the solution.
If applicable:
=> lib: improve error message for invalid string pattern, suggesting to use one of the known one

cli/examples/custom-operation-templater/main.rs, cli/src/cli_util.rs, cli/src/commands/operation.rs, cli/src/operation_templater.rs
This follows in the same pattern as https://github.com/martinvonz/jj/pull/3221
If applicable:
=> Support extensions of the OperationTemplateLanguage

cli/src/cli_util.rs, cli/src/commands/branch.rs, cli/src/commands/duplicate.rs, cli/src/commands/log.rs, cli/tests/test_duplicate_command.rs, lib/src/default_index/composite.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/index.rs
=> remove `Index::topo_order()`

cli/src/commands/git.rs, cli/tests/test_git_push.rs
=> cli: better warning if "git push" revisions match no branches

Cargo.lock, Cargo.toml
=> cargo: bump gix to 0.61.0

lib/src/default_index/readonly.rs, lib/src/default_index/store.rs
=> index: print a milder "reindex..." message on version mismatch

lib/src/rewrite.rs
It seems incorrect that `simplify_ancestor_merge` is ignored when it's part of the helper's input.
If applicable:
=> rewrite: fix rebase_commit_with_options handling of options

CHANGELOG.md
=> changelog: fix a typo `move than` -> `more than`

cli/src/commands/resolve.rs, cli/src/commands/status.rs, cli/src/commit_templater.rs, cli/src/diff_util.rs, cli/src/formatter.rs, cli/src/git_util.rs, cli/src/operation_templater.rs, cli/src/templater.rs, cli/src/text_util.rs
=> formatter: use write!() or writeln!() thoroughly, remove .write_str()

cli/examples/custom-commit-templater/main.rs, cli/examples/custom-operation-templater/main.rs, cli/src/commands/config.rs, cli/src/commit_templater.rs, cli/src/generic_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, cli/src/templater.rs
=> templater: add helper methods to map property like Option/Result

cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/config.rs, cli/src/commands/git.rs, cli/src/commands/merge.rs, cli/src/commands/resolve.rs, cli/src/ui.rs, cli/tests/test_log_command.rs, cli/tests/test_new_command.rs, cli/tests/test_rebase_command.rs
=> cli: make `CommandError` hint global, make it `Vec<String>`

cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/tests/test_next_prev_commands.rs
=> next, prev: fix choice from more than two targets

CHANGELOG.md, cli/src/config/templates.toml, cli/src/template_builder.rs, cli/src/templater.rs, docs/config.md, docs/templates.md
=> templater: add coalesce() function that selects first non-empty content

cli/src/commands/sparse.rs, lib/src/repo_path.rs
=> simplify path handling in `jj sparse set --edit`

cli/examples/custom-command/main.rs, cli/src/cli_util.rs, cli/src/commands/bench.rs, cli/src/commands/branch.rs, cli/src/commands/debug.rs, cli/src/commands/diff.rs, cli/src/commands/diffedit.rs, cli/src/commands/git.rs, cli/src/commands/interdiff.rs, cli/src/commands/log.rs, cli/src/commands/move.rs, cli/src/commands/rebase.rs, cli/src/commands/resolve.rs, cli/src/commands/restore.rs, cli/src/commands/squash.rs
=> cli: unimplement Deref for RevisionArg

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: release version 0.16.0

cli/src/commands/squash.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_squash_command.rs
=> squash: accept multiple --from arguments

CHANGELOG.md
=> doc: move new changelog entry to the unreleased section

lib/src/commit.rs
=> commit: actually remove boxing from CommitIteratorExt::ids()

docs/config.md
Makes it easier to figure out how to pass arguments.
If applicable:
=> docs: use command with argument as example for `ui.default-command`

CHANGELOG.md, cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/cat.rs, cli/src/commands/chmod.rs, cli/src/commands/commit.rs, cli/src/commands/debug.rs, cli/src/commands/diff.rs, cli/src/commands/files.rs, cli/src/commands/interdiff.rs, cli/src/commands/log.rs, cli/src/commands/move.rs, cli/src/commands/resolve.rs, cli/src/commands/restore.rs, cli/src/commands/split.rs, cli/src/commands/squash.rs, cli/src/commands/status.rs, cli/src/commands/untrack.rs, cli/testing/bench-revsets-git.txt, cli/tests/test_log_command.rs, cli/tests/test_revset_output.rs, docs/filesets.md, docs/revsets.md, lib/src/fileset.rs, lib/src/revset.rs, mkdocs.yml
=> cli: add support for file kind:pattern syntax

cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/debug.rs, cli/src/template_parser.rs, cli/tests/test_debug_command.rs, docs/filesets.md, lib/src/dsl_util.rs, lib/src/fileset.pest, lib/src/fileset.rs, lib/src/fileset_parser.rs, lib/src/lib.rs, lib/src/revset.rs
=> fileset: add parser and debug command

CHANGELOG.md, cli/src/cli_util.rs, cli/src/config-schema.json, cli/src/config/misc.toml, cli/tests/test_log_command.rs, docs/filesets.md, lib/src/fileset.rs
=> cli: parse path arguments as fileset expressions

cli/src/commands/new.rs, cli/src/commands/parallelize.rs, cli/src/commands/rebase.rs, cli/src/commands/split.rs, lib/src/repo.rs, lib/src/rewrite.rs, lib/tests/test_merge_trees.rs, lib/tests/test_rewrite.rs
=> Prep for `MutableRepo::transform_descendants()`

cli/src/commands/cat.rs, cli/tests/test_diff_command.rs, docs/filesets.md, lib/src/fileset.rs, lib/src/matchers.rs
=> fileset: parse cwd/root-glob patterns

cli/src/commands/config.rs, cli/src/commands/log.rs, cli/src/commands/obslog.rs, cli/src/commands/operation.rs, cli/src/config/templates.toml, cli/src/templater.rs, cli/tests/test_templater.rs
=> cli: set "node" template labels globally

docs/branches.md, docs/git-comparison.md
Also move some sentences away from "check out" to "create a new revision ...", even if it isn't the phrasing we want.
Fixes #3487
=> docs: Replace some mentions of `jj co` with `jj new`.

cli/src/commit_templater.rs
=> templater: cache immutable revset fn globally

cli/src/commands/git.rs, cli/tests/cli-reference@.md.snap, demos/run_scripts.sh, docs/contributing.md, docs/design/run.md
=> Fixes a few minor typos in docs and CLI

docs/install-and-setup.md
=> docs: make "Arch Linux" a subheading under "Linux"

cli/src/commit_templater.rs, cli/src/generic_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, cli/src/template_parser.rs, cli/tests/test_commit_template.rs, cli/tests/test_templater.rs
=> templater: include actual type name in error messages

CHANGELOG.md, cli/src/config/templates.toml, cli/tests/test_log_command.rs, cli/tests/test_obslog_command.rs, cli/tests/test_operations.rs, cli/tests/test_show_command.rs, cli/tests/test_templater.rs
=> templates: extract common parts from commit_summary templates

cli/tests/test_diff_command.rs
=> tests: avoid a use of deprecated `jj move`

docs/config.md
=> docs: Add information about configuring delta pager

cli/src/command_error.rs, cli/tests/test_commit_template.rs
=> cli: show hint for inner fileset/revset/template errors

CHANGELOG.md, cli/src/config/revsets.toml, lib/src/settings.rs
=> Drop support for `ui.default-revset`, move `revsets.log` to config file

docs/tutorial.md
Follows up on #3599. I also moved the discussion of other diff editors to a footnote, as it didn't seem to fit well into the flow of the text.
If applicable:
=> tutorial: edits to the diff editor explanation

CHANGELOG.md
=> fixup to 70b517c: remove errant conflict marker

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Release 0.17.1

cli/src/commands/commit.rs, cli/src/commands/diff.rs, cli/src/commands/restore.rs, cli/src/commands/split.rs, cli/src/commands/squash.rs, cli/src/commands/status.rs, cli/src/commands/unsquash.rs, cli/src/commit_templater.rs, cli/src/diff_util.rs, cli/src/merge_tools/builtin.rs, lib/src/commit.rs, lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/local_working_copy.rs, lib/src/merge.rs, lib/src/merged_tree.rs, lib/src/repo.rs, lib/src/rewrite.rs, lib/testutils/src/test_backend.rs
=> Add a `Commit::parent_tree()` helper

cli/src/commands/util.rs, cli/tests/cli-reference@.md.snap
Cc: https://github.com/martinvonz/jj/pull/2949#issuecomment-2098710774
If applicable:
=> cli `jj util completion --help`: Make the terminal output a bit prettier

CHANGELOG.md, cli/src/commands/branch.rs, cli/src/commit_templater.rs, cli/src/config/templates.toml, cli/tests/cli-reference@.md.snap, cli/tests/test_branch_command.rs, cli/tests/test_commit_template.rs, docs/templates.md
=> cli: port "branch list" to template

cli/src/commands/branch.rs, cli/tests/test_branch_command.rs, cli/tests/test_git_fetch.rs, cli/tests/test_git_push.rs, cli/tests/test_undo.rs
=> cli: print deleted branch hints at end of "branch list" output

cli/src/cli_util.rs, cli/src/ui.rs
=> cli: insert tracing at editor/pager invocation

cli/src/commands/config.rs
=> cli: reuse ConfigLevelArgs for "config list --user/--repo"

lib/src/gpg_signing.rs
=> gpg: drop redundant "exit status" from error message

CHANGELOG.md
=> fix: changelog entry for PR #3600

cli/src/cli_util.rs
=> cli: remove unneeded lifetime bound from check_rewritable()

docs/cli-reference.md
Perhaps this will help with issues like
https://github.com/martinvonz/jj/issues/3667
If applicable:
=> docs CLI reference: explain that argument help is truncated

lib/src/repo.rs
=> merge_view: remove heads removed by other side also in Google repos

docs/branches.md
=> docs: conflicted branches have two "?" as suffix

cli/src/template_builder.rs, cli/src/template_parser.rs, cli/tests/test_templater.rs, lib/src/fileset_parser.rs
=> templater: refactor alias substitution (prep for extracting generic functions)

docs/config.md
=> docs: Add `Log` header

cli/tests/test_git_colocated.rs, cli/tests/test_git_push.rs
=> tests: use get_branch_output() helper thoroughly in test_git_*

cli/src/revset_util.rs, cli/src/template_parser.rs, lib/src/dsl_util.rs, lib/src/revset.rs, lib/src/revset_parser.rs
=> revset, templater: extract generic AliasesMap<P> type

.github/workflows/release.yml, CHANGELOG.md
If applicable:
I was able to make a [test release](https://github.com/senekor/jj/releases/tag/test-2922) on my fork.
The binaries work as expected on my raspberry pi.
closes #3717
=> github: add linux-aarch64 build

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/config.rs, cli/src/config/templates.toml, cli/tests/test_alias.rs, cli/tests/test_config_command.rs
=> cli: config: leverage toml_edit::Value to serialize values

cli/examples/custom-commit-templater/main.rs, cli/examples/custom-operation-templater/main.rs, cli/src/commit_templater.rs, cli/src/generic_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, cli/src/template_parser.rs, lib/src/fileset.rs, lib/src/fileset_parser.rs
=> templater, fileset: implement `expect_*_arguments()` helpers as methods

cli/src/cli_util.rs, cli/src/commands/cat.rs, cli/src/commands/git.rs, cli/src/merge_tools/builtin.rs, cli/src/merge_tools/mod.rs, lib/src/local_working_copy.rs, lib/src/merged_tree.rs, lib/src/tree.rs, lib/src/tree_builder.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_merge_trees.rs, lib/tests/test_merged_tree.rs, lib/tests/test_rewrite.rs, lib/testutils/src/lib.rs
=> Propagate more errors when reading/writing trees

cli/src/diff_util.rs, cli/src/merge_tools/builtin.rs, lib/src/conflicts.rs, lib/src/local_working_copy.rs
=> conflicts: indicate executable conflict in git-format diff

cli/src/cli_util.rs, cli/src/commands/config.rs, cli/src/config.rs
=> cli: make a few functions in `commands/config.rs` public

lib/src/merged_tree.rs
=> tree: make `MergedTreeVal::to_merge()` public

Cargo.lock, Cargo.toml, cli/tests/test_git_colocated.rs, cli/tests/test_git_import_export.rs
=> cargo: upgrade gix to version 0.63

lib/src/merged_tree.rs, lib/src/tree.rs
=> tree: make `sub_tree_recursive()` public

lib/src/merged_tree.rs, lib/src/tree.rs
=> tree: take sub_tree_recursive() argument as &RepoPath

cli/src/template_parser.rs, lib/src/dsl_util.rs, lib/src/fileset_parser.rs
=> fileset, templater: extract basic AST node types

.github/workflows/codespell.yml, docs/code-of-conduct.md
=> github: silence codespell false-positive "NotIn"

lib/src/rewrite.rs
=> rewrite: minor simplification of `rebase_with_empty_behavior()`

CHANGELOG.md, Cargo.lock, Cargo.toml
Fixes #3357.
I'm not sure where in the changelog this should go?
If applicable:
=> deps: upgrade `scm-record` from v0.2.0 to v0.3.0

cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/debug.rs, cli/src/diff_util.rs, lib/src/fileset.rs, lib/src/repo_path.rs, lib/src/revset.rs, lib/tests/test_revset.rs
=> Add abstraction for formatting and parsing `RepoPath`

CHANGELOG.md, cli/tests/test_abandon_command.rs, lib/src/commit.rs, lib/src/repo.rs, lib/tests/test_mut_repo.rs, lib/tests/test_rewrite.rs
=> Don't treat merge commits differently when abandoning them

cli/tests/test_git_init.rs, lib/src/git.rs, lib/tests/test_git.rs
=> git: unset unborn HEAD ref on export

cli/examples/custom-commit-templater/main.rs, cli/tests/test_revset_output.rs, lib/src/dsl_util.rs, lib/src/revset.rs, lib/src/revset_parser.rs
=> revset: split AST-level parsing and expression lowering stages

lib/src/revset.pest, lib/src/revset_parser.rs
=> revset: clean up parsing functions

cli/src/commands/git.rs
=> cli: git: split loop that collects push directions and new targets

cli/examples/custom-commit-templater/main.rs, cli/src/command_error.rs, cli/tests/test_commit_template.rs, cli/tests/test_revset_output.rs, lib/src/revset.rs, lib/src/revset_parser.rs
=> revset: clean up AST processing functions

CHANGELOG.md, cli/src/commands/new.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_advance_branches.rs, cli/tests/test_new_command.rs
=> new: allow `--insert-before` and `--insert-after` simultaneously 

CHANGELOG.md, Cargo.lock, Cargo.toml
Martin is out this week so I'm setting up the release. Thanks to everyone who contributed!
If applicable:
=> release: version 0.18.0

CHANGELOG.md
hi!
I also changed my github username a few weeks ago to be a little bit more "me" haha :)
=> changelog: fix @tdaron username

CHANGELOG.md, cli/tests/test_revset_output.rs, lib/src/revset.pest, lib/src/revset.rs, lib/src/revset_parser.rs
=> revset: consolidate modifier parsing rules

cli/tests/test_fix_command.rs, lib/src/merged_tree.rs, lib/tests/test_merged_tree.rs
=> merged_tree: make tree builder attempt to resolve conflicts

cli/src/merge_tools/builtin.rs
=> diff-editor: pass reference to store into `apply_diff_builtin()`

docs/config.md, docs/windows.md
Quick fix to #3850.
I haven't tested this (might boot up a Windows VM at some point), but I think it is correct.
=> docs: update windows docs to mention minus, update minus docs

.envrc.recommended
Just a simple update to the `.envrc` tooling that I noticed while setting up jj on my Mac.
If applicable:
=> nix: update nix-direnv 2.3.0 -> 3.0.5

CHANGELOG.md, cli/src/revset_util.rs, cli/src/template_parser.rs, cli/tests/test_immutable_commits.rs, cli/tests/test_revset_output.rs, cli/tests/test_templater.rs, docs/revsets.md, docs/templates.md, lib/src/dsl_util.rs, lib/src/revset_parser.rs
=> revset, templater: implement arity-based alias overloading

lib/src/conflicts.rs
=> conflicts: remove redundant information from ReadFile error

CHANGELOG.md
=> changelog: remove mention of `jj file cat/ls` aliases

.github/workflows/build.yml
=> github: run CI on push, not only on PRs

docs/revsets.md
=> docs: add examples for some revset functions too

docs/revsets.md
=> docs: use bullet lists in revset examples to save vertical space

docs/sapling-comparison.md
=> docs: explain that jj was started 3 years before Sapling announcement

docs/community_tools.md, mkdocs.yml
=> docs: hyphenate "community-built"

Cargo.lock
Reissue of https://github.com/martinvonz/jj/pull/3892 now that we have updated to `watchman_client` 0.9, which should fix this issue based on reading the source code.
If applicable:
=> cargo: run full `cargo update`

cli/src/commands/debug/mod.rs, cli/src/commands/git/mod.rs, cli/src/commands/git/remote/mod.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_operations.rs
=> cli: sort debug/git subcommands, rename "debug workingcopy"

cli/tests/test_workspaces.rs, lib/src/revset.rs
=> revset: clarify error about missing working-copy commit for workspace

cli/src/commands/operation/mod.rs, cli/tests/cli-reference@.md.snap
=> cli: minor commands.operation cleanup

Cargo.lock
=> cargo: update off of yanked version of `subtle`

lib/src/dag_walk.rs
=> dag_walk: do one less clone() in heads_ok()

cli/src/diff_util.rs
=> cli: add label for line numbers in `--color-words` diff

flake.lock, flake.nix
Also has a minor fix in the `follows` directive.
If applicable:
=> nix: flake updates

docs/design/copy-tracking.md, lib/src/merged_tree.rs
=> cleanup: leverage `BoxStream`/`BoxFuture` type aliases

lib/src/fileset.rs, lib/src/revset.rs
=> tests: filter snapshots of fileset/revset expressions to save vertical space

cli/tests/test_diff_command.rs
Extracted from #3958
If applicable:
=> tests: add word-level hunks and capture some colorized diff outputs

cli/src/commands/debug/local_working_copy.rs, cli/src/commands/debug/mod.rs, cli/src/commands/debug/working_copy.rs, cli/tests/test_operations.rs
=> Make `jj debug working-copy` work for non-default working copies

cli/src/diff_util.rs
=> diff: inline hunk processing in get_diff_stat()

CHANGELOG.md, docs/config.md
=> docs: add customization example of color-words diff style

cli/src/diff_util.rs, cli/tests/test_diff_command.rs
=> cli: refactor `unified_diff_hunks()`, fix number of last context lines

CHANGELOG.md, Cargo.lock, Cargo.toml
I'm doing the release commit again as Martin is on vacation. Thanks to everyone who contributed!
If applicable:
=> release: 0.19.0

CHANGELOG.md, cli/src/commands/backout.rs, cli/tests/runner.rs, cli/tests/test_backout_command.rs, lib/src/rewrite.rs
This is an alternative to https://github.com/martinvonz/jj/pull/3583.
If applicable:
=> backout: include backed out commit's subject in new commit

cli/src/commands/branch/create.rs, cli/src/commands/branch/delete.rs, cli/src/commands/branch/forget.rs, cli/src/commands/branch/move.rs, cli/src/commands/branch/set.rs, cli/src/commands/branch/track.rs, cli/src/commands/branch/untrack.rs, cli/tests/test_branch_command.rs, cli/tests/test_git_colocated.rs, cli/tests/test_git_push.rs, cli/tests/test_immutable_commits.rs, cli/tests/test_revset_output.rs
=> cli: show commit summary at end of "branch create"/"set"

CHANGELOG.md, cli/src/commands/backout.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_backout_command.rs
Closes #3339.
If applicable:
-
=> backout: accept multiple revisions to back out

CHANGELOG.md, cli/src/commands/git/clone.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_git_clone.rs
=> feat(cli): recursively create clone destination path

README.md
If applicable:
- [NA] I have updated `CHANGELOG.md`
- [NA] I have added tests to cover my changes
=> readme: include link to wiki "Media" page and fix broken changelog link

lib/src/revset_parser.rs
=> revset: rename expect_literal_with() to expect_expression_with()

cli/src/formatter.rs
=> formatter: minor cleanup in --color=debug handling

Cargo.lock
Noticed in Benjamin's PR https://github.com/martinvonz/jj/pull/4080
=> cargo: update yanked crate and update deps

CHANGELOG.md, cli/src/diff_util.rs, cli/tests/test_acls.rs, cli/tests/test_concurrent_operations.rs, cli/tests/test_diff_command.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_gitignores.rs, cli/tests/test_interdiff_command.rs, cli/tests/test_log_command.rs, cli/tests/test_obslog_command.rs, cli/tests/test_resolve_command.rs
=> diff: do not emit unified diff for binary files

Cargo.lock, cli/Cargo.toml
=> cli: remove unused dependency on gix-filter

docs/git-compatibility.md
=> docs/git-comparison.md: update the Signed_commits bullet

lib/src/conflicts.rs, lib/tests/test_conflicts.rs
This is the uncontroversial part of https://github.com/martinvonz/jj/pull/4088.
Cc @yuja
=> lib conflicts: minor bugfix + tests

mkdocs.yml
Missed in #3574. Also cleaned up some formatting in `mkdocs.yml`.
If applicable:
=> docs: add copy tracking design doc to MkDocs

lib/src/commit_builder.rs, lib/src/repo.rs
=> commit_builder: inline mut_repo.write_commit()

cli/src/cli_util.rs, cli/tests/test_commit_template.rs
=> cli_util: add tx.commit_summary_template() and related helper functions

CHANGELOG.md, cli/src/command_error.rs, cli/tests/test_branch_command.rs, cli/tests/test_commit_template.rs, cli/tests/test_revset_output.rs, docs/revsets.md, lib/src/str_util.rs, lib/tests/test_revset.rs
=> str_util: add regex pattern

CHANGELOG.md, cli/src/config/misc.toml, cli/tests/test_diff_command.rs, cli/tests/test_global_opts.rs, cli/tests/test_log_command.rs, docs/filesets.md
=> cli: enable fileset by default

cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/operation/diff.rs, cli/src/diff_util.rs, cli/src/formatter.rs, cli/tests/test_commit_template.rs
=> diff: add "diff" label globally by outer show_diff/patch() functions

docs/FAQ.md
=> FAQ: remove workaround for fixed bug (#2476)

cli/src/ui.rs
=> ui: refactor pager functions

google814a1b457964a443.html
This will allow me to use the Google search console, https://search.google.com/search-console, to see how Google crawled our docs and whether I can ask it to recrawl.
See also https://developers.google.com/search/docs/crawling-indexing/ask-google-to-recrawl.
I'm assuming there would also be a way to give others (e.g. Martin) access. Certainly, it's possible to later replace this file with another one generated for another account (use use a file Martin generates now).
=> (direct website push) SEO: Add Google ownership verification file

cli/src/description_util.rs
=> cli: minor parse_bulk_edit_message() cleanup

docs/branches.md
=> docs: minor updates to description of branch conflicts

docs/tutorial.md
I was thinking of updating the tutorial in #4168, but conversations like [this one on
Discord](https://discord.com/channels/968932220549103686/968932220549103689/1269803837070377076) suggest that many people aren't reading it anyway.
So, this is an attempt to quickly patch up the most relevant things before the upcoming release.
Let me know whether you think this is a good idea or needs more editing.
Cc @steveklabnik
=> tutorial: link to Steve Klabnik's tutorial, mention `jj log -r ::`

cli/src/commands/run.rs
=> jj run: describe it as a stub in the help text

Cargo.lock, Cargo.toml, cli/src/cli_util.rs
=> cargo: bump gix to 0.64.0

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: release version 0.20.0

lib/src/merged_tree.rs, lib/src/store.rs, lib/tests/test_merged_tree.rs
=> Remove `MergedTree::Legacy`

lib/src/merged_tree.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_merged_tree.rs
=> merged_tree: refactor iterator internals

cli/src/cli_util.rs, cli/tests/test_gitignores.rs
=> git: resolve relative core.excludesFile path at workspace root

lib/src/merged_tree.rs
While measuring file(path) query, I noticed BTreeMap lookup appears in perf. It actually has a measurable cost if the history is linear and parent trees don't have to be merged dynamically. For merge-heavy history, the cost of tree merges is more significant. I'll address that separately.
```
% hyperfine --sort command --warmup 3 --runs 50 -L bin jj-1,jj-2 \
'target/release-with-debug/{bin} -R ~/mirrors/git --ignore-working-copy \
log -r "::trunk() & ~merges() & file(root:builtin)" --no-graph -n100'
Benchmark 1: target/release-with-debug/jj-1 ..
Time (mean ± σ):     239.7 ms ±   7.1 ms    [User: 192.1 ms, System: 46.5 ms]
Range (min … max):   222.2 ms … 249.7 ms    50 runs
Benchmark 2: target/release-with-debug/jj-2 ..
Time (mean ± σ):     201.7 ms ±   6.9 ms    [User: 153.7 ms, System: …
```
=> merged_tree: do not re-look up non-conflicting tree values by name

lib/src/merged_tree.rs, lib/src/tree.rs
=> merged_tree: add merge-join iterator over Merge<Tree> entries

lib/src/merge.rs, lib/src/merged_tree.rs, lib/src/tree.rs, lib/tests/test_merged_tree.rs
=> merged_tree: replace MergedTreeVal<'_> by Merge<Option<&TreeValue>>

lib/src/default_index/revset_engine.rs, lib/src/merged_tree.rs
=> revset: avoid merging whole parent trees by file()/diff_contains() query

CHANGELOG.md, cli/src/diff_util.rs, cli/tests/test_diff_command.rs, cli/tests/test_show_command.rs
=> copy-tracking: implement copy-tracking for --types

cli/tests/test_rebase_command.rs, lib/src/rewrite.rs
=> `rewrite::move_commits()`: preserve order of parent commits

cli/src/diff_util.rs
=> cli: propagate BackendError from tree diffs

cli/src/diff_util.rs, lib/src/diff.rs, lib/src/files.rs
=> diff: refactor DiffLineIterator API

CHANGELOG.md, cli/src/commit_templater.rs, cli/src/diff_util.rs, cli/tests/test_acls.rs, cli/tests/test_diff_command.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_git_init.rs, cli/tests/test_show_command.rs, lib/src/git_backend.rs
=> copy-tracking: add support for `diff --git`

cli/src/diff_util.rs, lib/src/files.rs
=> files: simplify DiffLineIterator a bit

CHANGELOG.md, cli/src/diff_util.rs, cli/tests/test_diff_command.rs
=> copy-tracking: implement copy tracking for external tools

cli/tests/test_diff_command.rs
=> tests: restore snapshots of line/word-oriented diff hunks

cli/src/diff_util.rs, cli/tests/test_diff_command.rs, lib/src/diff.rs, lib/src/files.rs
=> diff: split color-words diffing to line-based and refinement stages

cli/src/config/misc.toml, lib/src/git_backend.rs, lib/src/repo.rs, lib/src/settings.rs, lib/src/store.rs
=> drop "support" for legacy tree config

lib/benches/diff_bench.rs, lib/src/diff.rs
=> diff: inline Diff::default_refinement() in diff()

flake.lock
Just a regularly scheduled update.
=> nix: run `nix flake update`

CHANGELOG.md, cli/src/commands/status.rs, cli/tests/test_status_command.rs, lib/src/local_backend.rs, lib/testutils/src/test_backend.rs
=> Support copy/renames in `jj status`

cli/src/commit_templater.rs, cli/tests/test_commit_template.rs
=> templater: integrate copy tracking in commit.diff() template

cli/src/config-schema.json, docs/revsets.md
=> fix doc typo and config schema

cli/src/commands/file/show.rs, cli/src/diff_util.rs, cli/src/merge_tools/builtin.rs, cli/src/merge_tools/external.rs, cli/src/merge_tools/mod.rs, lib/src/conflicts.rs, lib/src/default_index/revset_engine.rs, lib/src/files.rs, lib/src/local_working_copy.rs, lib/src/merge.rs, lib/src/tree.rs
=> conflicts: pass around conflict contents without materialization

cli/src/cli_util.rs, cli/src/commands/operation/abandon.rs, cli/src/commands/operation/log.rs, cli/src/commands/workspace/update_stale.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_concurrent_operations.rs, cli/tests/test_new_command.rs, cli/tests/test_operations.rs, cli/tests/test_workspaces.rs, docs/branches.md, docs/operation-log.md, docs/technical/concurrency.md, lib/src/repo.rs, lib/tests/test_git.rs, lib/tests/test_view.rs
=> op log: change "resolve concurrent" to "reconcile divergent"

lib/src/local_working_copy.rs
=> local_working_copy: delete obsolete comment about libgit2

cli/src/cli_util.rs
=> cli: make `WorkspaceCommandHelper` keep an `Arc<CommandHelper>`

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release version 0.21.0

docs/roadmap.md
=> docs(roadmap): minor typo, `as` should be `ask`

Cargo.lock, cli/examples/custom-backend/main.rs, cli/src/commands/fix.rs, cli/src/merge_tools/builtin.rs, cli/src/merge_tools/external.rs, lib/src/backend.rs, lib/src/commit_builder.rs, lib/src/conflicts.rs, lib/src/default_index/revset_engine.rs, lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/local_working_copy.rs, lib/src/merged_tree.rs, lib/src/secret_backend.rs, lib/src/store.rs, lib/src/tree.rs, lib/src/tree_builder.rs, lib/tests/test_local_working_copy.rs, lib/testutils/Cargo.toml, lib/testutils/src/lib.rs, lib/testutils/src/test_backend.rs
=> Make backend methods async

lib/src/tree.rs
=> tree: when merging files, read all sides concurrently

README.md, mkdocs.yml
These are some fixups to https://github.com/martinvonz/jj/pull/4380.
@martinvonz, this just collects my thoughts, let me know if you disagree with anything and I'll remove it.
=> roadmap: minor fixups

cli/src/commands/squash.rs, cli/tests/test_squash_command.rs
=> cli squash: explain --into in error message for merge commits

cli/tests/common/mod.rs
=> tests: set `$COLUMNS` when running CLI tests

cli/src/config-schema.json, docs/config.md, lib/src/settings.rs
=> signing: allow disabling by setting backend to empty string

CHANGELOG.md, lib/src/conflicts.rs, lib/tests/test_conflicts.rs
=> Fix panic when parsing conflict markers

cli/src/commands/operation/diff.rs, cli/src/commands/operation/show.rs, cli/tests/test_operations.rs, lib/src/repo.rs
=> op show: accept root operation + minor cleanup

cli/src/commands/evolog.rs, cli/src/commands/interdiff.rs, cli/src/commands/operation/diff.rs, cli/src/diff_util.rs, cli/tests/test_operations.rs
=> diff: extract inter-diff helper

cli/src/config-schema.json
=> config-schema: add signing.backend=none to the list of enum variants

lib/src/working_copy.rs, lib/tests/test_local_working_copy.rs, lib/testutils/src/lib.rs
=> local_working_copy: pass max file size to snapshot directly

cli/examples/custom-working-copy/main.rs, cli/src/cli_util.rs, cli/src/commands/file/untrack.rs, cli/src/merge_tools/diff_working_copies.rs, lib/src/local_working_copy.rs, lib/src/working_copy.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_local_working_copy_concurrent.rs, lib/testutils/src/lib.rs
=> working_copy: pass SnapshotOptions by reference

cli/src/cli_util.rs, lib/src/workspace.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_local_working_copy_concurrent.rs, lib/tests/test_local_working_copy_sparse.rs, lib/tests/test_workspace.rs, lib/testutils/src/lib.rs
=> workspace: make workspace_root() and repo_path() return slice &Path

docs/FAQ.md
[This sort of question comes up often in Discord](https://discord.com/channels/968932220549103686/968932220549103689/1282681491234619422), maybe it would be useful to have it in the FAQ?
If applicable:
=> faq: Add "Should I co-locate my repository?"

cli/src/cli_util.rs, cli/src/commands/branch/list.rs, cli/src/commands/branch/track.rs, cli/src/commands/debug/revset.rs, cli/src/commands/evolog.rs, cli/src/commands/git/push.rs, cli/src/commands/log.rs, cli/src/commands/operation/diff.rs, cli/src/commands/operation/log.rs, cli/src/commands/operation/show.rs, cli/src/commands/status.rs, cli/src/commands/tag.rs, cli/src/git_util.rs
=> cli: extract non-repo part from `WorkspaceCommandHelper`, prep for `op log --op-diff`

lib/src/protos/op_store.proto, lib/src/protos/op_store.rs, lib/src/simple_op_store.rs
=> bookmarks: rename proto symbols from "branch"

docs/FAQ.md
=> FAQ: Add another problem to be aware of when co-locating a repo

cli/src/config-schema.json
=> config-schema: update stale `push-branch-prefix` config

CHANGELOG.md
=> changelog: remove an unclear "in lieu of"

cli/src/cli_util.rs, cli/tests/test_file_chmod_command.rs, cli/tests/test_repo_change_report.rs, cli/tests/test_resolve_command.rs, cli/tests/test_restore_command.rs, cli/tests/test_squash_command.rs, cli/tests/test_status_command.rs
Fixes https://github.com/martinvonz/jj/issues/3561
If applicable:
- I don't know if that needs mention as a new feature or not, let me know if it does
=> Highlight change ids in rebase advice

docs/working-copy.md
=> Fix missing word in working-copy.md

cli/src/commands/git/push.rs, cli/tests/test_git_private_commits.rs, cli/tests/test_git_push.rs, cli/tests/test_operations.rs
=> git-push: just say "Changes to push to <REMOTE>"

cli/src/cli_util.rs, cli/src/commands/operation/diff.rs, cli/src/commands/operation/show.rs
=> cli: add helper to set up op template environment for the current repo state

lib/src/hex_util.rs
=> hex_util: simplify common_hex_len() a bit to compare input bytes once

CHANGELOG.md, cli/examples/custom-working-copy/main.rs, cli/src/command_error.rs, cli/src/commands/workspace/mod.rs, cli/src/commands/workspace/rename.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_workspaces.rs, lib/src/local_working_copy.rs, lib/src/repo.rs, lib/src/view.rs, lib/src/working_copy.rs
=> cli: Support renaming workspaces

cli/src/commands/squash.rs, cli/tests/cli-reference@.md.snap
=> squash doc: --keep-emptied let the description unchanged

Cargo.lock, cli/Cargo.toml
=> cli: remove unused dependency on hex

cli/src/commands/diffedit.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_global_opts.rs
Noticed because of https://github.com/martinvonz/jj/pull/4489#pullrequestreview-2310996976
=> diffedit: separate extra help information in its own paragraph

cli/src/diff_util.rs
=> diff: refactor color-words hunk printing

cli/src/cli_util.rs, cli/src/commands/git/push.rs, cli/src/commands/status.rs, cli/src/commit_templater.rs, cli/src/revset_util.rs, cli/tests/test_commit_template.rs
=> cli: cache immutable heads revset expression

lib/src/op_heads_store.rs
=> op_heads_store: don't test "no heads" error without acquiring lock

docs/templates.md
=> docs: add some scripting template examples

cli/src/commands/commit.rs, cli/src/commands/describe.rs, cli/src/operation_templater.rs, lib/src/backend.rs, lib/src/commit_builder.rs, lib/src/op_store.rs, lib/src/settings.rs, lib/src/transaction.rs, lib/tests/test_revset.rs
If applicable:
Based on https://github.com/martinvonz/jj/pull/4466
=> refactor: mark `Timestamp` struct as `Copy`

lib/src/diff.rs
=> diff: refactor some indexing ops

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: release version 0.22.0

docs/revsets.md
=> doc: add comment to explain the syntax of folded examples

.github/workflows/codespell.yml
=> CI: add a last name to the list of spelling exceptions

docs/revsets.md
=> Fix typo in docs

cli/tests/runner.rs, cli/tests/test_file_show_command.rs
=> tests: rename test_file_print_command.rs to_file_show_command.rs

Cargo.lock, Cargo.toml, lib/Cargo.toml, lib/src/diff.rs
(Not meant for inclusion in the October release)
If applicable:
=> diff: add machinery to ignore whitespace changes

docs/community_tools.md
=> docs: add link to VisualJJ

lib/src/revset.rs
=> revset: use Self to refer to expressions of the same type

cli/src/commands/bookmark/list.rs, cli/tests/test_bookmark_command.rs
=> bookmarks-list: fix typo

CHANGELOG.md
=> changelog: fix conflict resolution error in 95344f9e

cli/src/cli_util.rs, cli/tests/cli-reference@.md.snap
=> cli: remove additional space in `--quiet` help message

cli/src/config/windows.toml
=> fix: use correct program for merge-editor = "vscode" on Windows

cli/src/diff_util.rs, lib/src/diff.rs
=> diff: inline contents and ranges vecs up to two sides
