jj-vcs/jj

cli/tests/test_abandon_command.rs
Illustrates #2600, in addition to being IMO a useful test.
This is similar to the following test:
https://github.com/martinvonz/jj/blob/5186066cf5064564466e58096b79fba6b0c0ecfd/cli/tests/test_rebase_command.rs#L264-L269 
from https://github.com/martinvonz/jj/pull/538.
If applicable:
=> test_abandon_command: test we don't create commits that are both direct and indirect descendants

docs/install-and-setup.md
The instructions in the docs for installing `jj` with `cargo-binstall` used the flag `--strategy` which should be `--strategies` ([source](https://github.com/cargo-bins/cargo-binstall/blob/469fc1783e5caa1b1e1f7e4af57c4ad49834e497/crates/bin/src/args.rs#L155)).  This change just fixes that typo.
If applicable:
=> install-and-setup.md: `--strategy` -> `--strategies` for `cargo binstall`

mkdocs.yml
The documentation at https://martinvonz.github.io/jj/v0.11.0/technical/architecture/#design-of-the-library-crate includes a Mermaid diagram.
Unfortunately the Mermaid plugin is not enabled in your MkDocs theme. This PR just follows the instructions at https://squidfunk.github.io/mkdocs-material/reference/diagrams/ to enable it.
If applicable:
- ~[ ] I have updated `CHANGELOG.md`~
- ~[ ] I have updated the documentation (README.md, docs/, demos/)~
- ~[ ] I have updated the config schema (cli/src/config-schema.json)~
- ~[ ] I have added tests to cover my changes~
=> docs: add mermaid plugin for diagrams

cli/src/cli_util.rs, cli/src/merge_tools/builtin.rs, cli/src/ui.rs, lib/src/default_index_store.rs, lib/src/working_copy.rs
=> cleanup: don't use debug format to print source errors

lib/src/fsmonitor.rs, lib/src/local_working_copy.rs, lib/src/repo_path.rs, lib/tests/test_local_working_copy.rs
=> watchman: minor code cleanup

cli/src/cli_util.rs, cli/src/ui.rs
Follows up on be1d95284a.
The information I added is explained in that commit's description, but I feel like it could reduce confusion for future readers of the code.
=> cli diff editor: Add a comment

CHANGELOG.md, cli/src/commands/new.rs, cli/tests/test_new_command.rs
=> cli `new`: add `--no-edit` flag, allow repeating some flags

cli/examples/custom-backend/main.rs, lib/src/backend.rs, lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/store.rs, lib/testutils/src/test_backend.rs
I feel like this is the least convoluted way of doing it, after all.
Continuing to move small atomic pieces into main :)
Yeah just noticed that because I moved the `write_commit` to `write_commit_impl` it's hard to see the diff.. I've already described the gist of it in discord a few days ago
If applicable:
=> sign: Implement generic commit signing on the backend

CHANGELOG.md, cli/src/commands/rebase.rs, lib/src/repo.rs, lib/src/rewrite.rs, lib/tests/test_rewrite.rs
Fixes issue #229. See the issue for discussions.
- Add test helper functions to give full control over the tree.
- Implement plumbing to add RebaseOptions to rebase_commit and DescendentRebaser.
- Implement skipping of empty commits.
- Add a --skip-empty flag to rebase
If applicable:
=> Implement rebase --skip-empty

cli/tests/test_abandon_command.rs, lib/src/rewrite.rs
One of these is a copy-paste error, the other is more meaningful.
There will hopefully be a follow-up PR for `rewrite.rs`, but I was thinking of merging the rename earlier to prevent merge conflicts.
=> rewrite.rs and test_abandon_command: rename a field and a test

Cargo.lock, Cargo.toml, lib/Cargo.toml, lib/src/backend.rs, lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/local_working_copy.rs, lib/src/matchers.rs, lib/src/merged_tree.rs, lib/src/repo_path.rs, lib/src/tree.rs, lib/src/tree_builder.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_merge_trees.rs, lib/tests/test_merged_tree.rs
=> repo_path: split RepoPathComponent into owned and borrowed types

cli/src/commands/run.rs
Adress the post-merge comments from #2486, which found a doc comment inaccurate and to not blindly ignore `-j 0` which would've worked until now. I've also reduced the default `jobs` size to one, as it's user-visible configuration
which determines how many processes should run.
Thanks to @necauqua the controversial `unsafe` usage was already removed.
I've omitted to change `revisions` from an Vec to a RevisonArg for the moment,  as I will keep working on the file anyway.
If applicable:
=> run: Fix up various things.

cli/src/commands/rebase.rs, lib/src/repo.rs
This follows up on @matts1 's https://github.com/martinvonz/jj/pull/2609.
We still allow the `-r` commit to become empty. I would be more comfortable if
there was a test for that, but I haven't done that (yet?) and it seems pretty
safe. If that's a problem, I'm happy to forbid `-r --skip-empty` entirely,
since it is far less useful than `-s --skip-empty` or `-b --skip-empty`.
I think it is undesired to abandon emptied descendants. As far as descendants
of `A` are concerned, `jj rebase -r A` should be equivalent to `jj abandon A`,
and `jj abandon` does not remove emptied commits. It also doesn't seem very
useful to do that, since I think descendant commits of an abandoned (or moved
with `-r`) commit only become empty in pathological cases.
Additionally, if we did want -r to empty …
=> cli rebase: do not allow `-r --skip-empty` to empty descendants

cli/examples/custom-working-copy/main.rs, cli/src/diff_util.rs, lib/src/local_working_copy.rs, lib/src/matchers.rs, lib/src/merged_tree.rs, lib/src/repo_path.rs, lib/src/tree.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_merge_trees.rs, lib/tests/test_merged_tree.rs
=> repo_path: turn RepoPath into String wrapper

cli/src/commands/rebase.rs, cli/tests/test_rebase_command.rs, lib/src/rewrite.rs
This follows up on 3967f63 (see that commit's description for more motivation) and @matts1 's e79c8b6.
In a discussion linked below, it was decided that forbidding `-r --skip-empty` entirely is preferable to the mixed behavior introduced in 3967f63.
https://github.com/martinvonz/jj/commit/3967f637dc31abdf8ed8817a377defab70821e37#commitcomment-133539911
If applicable:
- n/a I have updated `CHANGELOG.md`
- n/a I have updated the documentation (README.md, docs/, demos/)
- n/a I have updated the config schema (cli/src/config-schema.json)
=> cli rebase: do not allow `-r --skip-empty`

cli/src/commands/run.rs
Apparently, this conversion is infallible.
=> clippy: fix a nightly clippy warning

CHANGELOG.md, cli/src/commands/init.rs, cli/tests/test_init_command.rs
Allowing `jj init --git` in an existing Git repo creates a second Git store in `.jj/repo/store/git`, totally disconnected from the existing Git store. This will only produce extremely confusing bugs for users, since any operations they make in Git will *not* be reflected in the jj repo.
Note: this is a tweak to the behavior as originally implemented in #687.
If applicable:
- N/A: ~~I have updated the documentation (README.md, docs/, demos/)~~
- N/A: ~~I have updated the config schema (cli/src/config-schema.json)~~
=> Do not allow `jj init --git` in existing Git repo

cli/src/commands/rebase.rs, cli/tests/common/mod.rs, cli/tests/test_rebase_command.rs
In Git, a commit's direct parent is allowed to also be an indirect ancestor at the same time. `jj` currently tries to prevent this situation, but does allow it. The correctness of `rebase -r A -d descendant_of_A` currently depends on this jj-specific behavior; we should change that.
Cc #2600
---------------
Aside: I have plans to refactor jj rebase -r so that it becomes straightforward to conclude that it does not block fixing #2600, hopefully in the near future. It's slowed down slightly by my wanting to refactor `jj new` and DescendantRebaser at the same time and have them all use the same code.
If applicable:
=> cli `rebase`: add tests for weird ancestry, fix an assumption in a comment

Cargo.lock, cli/examples/custom-backend/main.rs, cli/examples/custom-working-copy/main.rs, cli/src/cli_util.rs, cli/src/config-schema.json, lib/src/backend.rs, lib/src/commit.rs, lib/src/commit_builder.rs, lib/src/git_backend.rs, lib/src/lib.rs, lib/src/local_backend.rs, lib/src/repo.rs, lib/src/settings.rs, lib/src/signing.rs, lib/src/store.rs, lib/src/workspace.rs, lib/tests/test_git.rs, lib/tests/test_signing.rs, lib/testutils/Cargo.toml, lib/testutils/src/lib.rs, lib/testutils/src/test_backend.rs, lib/testutils/src/test_signing_backend.rs
~~Relatively small piece, just adding `signing.rs` stuff, which is to be amended depending on future cli work (and actual signing backend impls), and integrate it with store initialization~~
Basically implemented all of the abstract signing backend management, only things left are the actual impls and the user-facing cli/templater/hints.
Self-review tells me this is small and digestable enough, but I was always wrong about that :)
But writing this felt like all the lego pieces clicking into places, it seems nice
If applicable:
=> sign: Define signing backend API and integrate it

cli/tests/test_abandon_command.rs
See comments inline for details.
The tests ended up weirder than expected because
of https://github.com/martinvonz/jj/issues/2600#issuecomment-1835418824. Even though,
right now, the behavior of tests is unaffected by that issue, the *expected* behavior is different.
In particular, I wanted to make sure these behaviors are not affected by https://github.com/martinvonz/jj/pull/2646.
They don't seem to be.
If applicable:
=> `test_abandon_command`: create another test for bug 2600

CHANGELOG.md, lib/src/merged_tree.rs, lib/src/tree.rs, lib/tests/test_merged_tree.rs
=> merged_tree: don't add empty subtree to parent, remove canceling terms prior to resolving file-level conflict

CHANGELOG.md, cli/examples/custom-backend/main.rs, cli/src/commands/util.rs, docs/git-compatibility.md, lib/src/backend.rs, lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/store.rs, lib/testutils/src/test_backend.rs
This adds an initial `jj util gc` command, which simply calls `git gc` when using the Git backend. That should already be useful in non-colocated repos because it's not obvious how to GC (repack) such repos. In my own jj repo, it shrunk `.jj/repo/store/` from 2.4 GiB to 780 MiB, and `jj log --ignore-working-copy` was sped up from 157 ms to 86 ms.
I haven't added any tests because the functionality depends on having `git` binary on the PATH, which we don't yet depend on anywhere else. I think we'll still be able to test much of the future parts of garbage collection without a `git` binary because the interesting parts are about manipulating the Git repo before calling `git gc` on it.
If applicable:
=> gc: implement basic GC for Git backend

cli/src/config/merge_tools.toml
In https://github.com/martinvonz/jj/pull/2665#issuecomment-1837552283, a user used `$base` instead of one of the `$output`s and nothing worked. This seems like a natural mistake to make, the config is confusing.
=> merge_tools.toml: add a comment to `meld-3` definition

cli/src/cli_util.rs, cli/src/commands/git.rs, lib/src/git.rs, lib/tests/test_git.rs
=> git: migrate export_refs() to gix::Repository

cli/src/commands/debug.rs, lib/src/default_index_store.rs, lib/tests/test_default_revset_graph_iterator.rs, lib/tests/test_index.rs
=> index: rename readonly index types, move `impl Index` to wrapper type

cli/src/cli_util.rs, cli/tests/test_branch_command.rs, cli/tests/test_git_colocated.rs, cli/tests/test_git_import_export.rs, lib/src/git.rs
=> cli: print failed git export reason for each ref

lib/src/default_index_store.rs, lib/src/default_revset_engine.rs, lib/tests/test_index.rs
=> index: add DefaultMutableIndex wrapper, rename segment type

CHANGELOG.md, cli/src/cli_util.rs, cli/tests/test_chmod_command.rs, cli/tests/test_repo_change_report.rs, cli/tests/test_resolve_command.rs, cli/tests/test_restore_command.rs
=> cli: print a message about new and resolved conflicts

lib/src/default_index_store.rs, lib/src/default_revset_engine.rs
=> revset: refactor collect_dag_range() and walk_*() helpers

cli/src/commands/branch.rs, cli/tests/test_branch_command.rs
This tries to clarify the fact that the branches must be remote and the syntax for specifying them as globs.
Cc @yuja, https://github.com/martinvonz/jj/pull/2625#discussion_r1423379351
Here is the result (excerpt):
```
$ jj branch track --help
Start tracking given remote branches
A tracking remote branch will be imported as a local branch of the same name. Changes to it
will propagate to the existing local branch on future pulls.
Usage: jj branch track [OPTIONS] <BRANCH@REMOTE>...
Arguments:
<BRANCH@REMOTE>...
Remote branches to track
By default, the specified name matches exactly. Use `glob:` prefix to select
branches by wildcard pattern. For details, see
https://github.com/martinvonz/jj/blob/main/docs/revsets.md#string-patterns.
Examples: branch@remote, glob:main@*, …
```
=> cli `branch track`, `branch untrack`: document remote branches in `jj help`

lib/src/default_index/composite.rs, lib/src/default_index/mod.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/default_index/store.rs
=> index: split readonly/mutable index types to sub modules

lib/src/rewrite.rs, lib/tests/test_rewrite.rs
This could be reviewed now or together with the other refactors that would happen in subsequent commits (making `new_parents` a public function, etc). If you prefer the latter, let me know. You can also look at https://github.com/ilyagr/jj/tree/refactor, but it's still
unpolished.
I'm posting this mainly to illustrate my plans, and so that you can let me know if there is some fatal problem with them.
---------------------
Previously, the function relied on both the `self.parent_mapping` and `self.rebased`. If `(A,B)` was in `parent_mapping` and `(B,C)` was in `rebased`, `new_parents` would map `A` to `C`.
Now, `self.rebased` is ignored by `new_parents`. In the same situation, DescendantRebaser is changed so that both `(A,B)` and `(B,C)` are in `parent_mapping` before. `new_parents` now …
=> `rewrite.rs`: refactor `new_parents` to depend only on `parent_mapping`

lib/src/default_index/composite.rs, lib/src/default_index/entry.rs, lib/src/default_index/mod.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/default_index/rev_walk.rs
=> index: split `IndexEntry`, etc. to sub module

lib/src/default_index/readonly.rs
=> index: use loaded readonly data without splitting into vecs

.github/dependabot.yml
I noticed some cargo dependencies aren't caught by the dependabot. For example, there are gix updates, but the dependabot somehow thinks it's not possible to update.
```
updater | 2023/12/14 15:57:52 INFO <job_762380319> Checking if gix 0.55.2 needs updating
proxy | 2023/12/14 15:57:52 [063] GET https://crates.io:443/api/v1/crates/gix
proxy | 2023/12/14 15:57:52 [063] 200 https://crates.io:443/api/v1/crates/gix
updater | 2023/12/14 15:57:53 INFO <job_762380319> Latest version is 0.56.0
...
updater | 2023/12/14 15:58:00 INFO <job_762380319> Requirements to unlock update_not_possible
updater | 2023/12/14 15:58:00 INFO <job_762380319> Requirements update strategy bump_versions
updater | 2023/12/14 15:58:00 INFO <job_762380319> No update possible for gix 0.55.2
```
I don't know what's wrong, …
=> github: try without grouped cargo updates

lib/src/default_index/entry.rs, lib/src/default_index/mod.rs, lib/src/default_revset_engine.rs
=> revset: remove 'index lifetime from InternalRevset

cli/src/commands/debug.rs, lib/src/default_index/composite.rs, lib/src/default_index/mod.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/default_revset_engine.rs, lib/src/index.rs, lib/src/lib.rs, lib/src/repo.rs, lib/tests/test_default_revset_graph_iterator.rs, lib/tests/test_index.rs
=> revset: add 'static version of `evaluate_revset()`, forbid `unsafe`

lib/src/default_revset_engine.rs
=> revset: clean up combinator types a bit

cli/src/commands/branch.rs, cli/tests/test_branch_command.rs, cli/tests/test_git_fetch.rs, cli/tests/test_git_push.rs, cli/tests/test_undo.rs
=> cli: colorize inline "jj branch" command hints

Cargo.lock
=> cargo: update gix-ref to 0.39.1 which includes fix for Windows mmap issue

.github/dependabot.yml
The dependabot refused to update some dependencies anyway. Maybe it conservatively checks if all intra dependencies meet a certain version?
```
updater | 2023/12/15 15:56:45 INFO <job_762807265> No update possible for cargo_metadata 0.17.0
updater | 2023/12/15 15:56:54 INFO <job_762807265> No update possible for crossterm 0.26.1
updater | 2023/12/15 15:57:04 INFO <job_762807265> No update possible for itertools 0.11.0
updater | 2023/12/15 15:57:16 INFO <job_762807265> No update possible for zstd 0.12.4
updater | 2023/12/15 15:57:16 INFO <job_762807265> No update possible for jj-cli 0.12.0
updater | 2023/12/15 15:57:27 INFO <job_762807265> No update possible for toml_edit 0.19.15
updater | 2023/12/15 15:57:38 INFO <job_762807265> No update possible for prost-build 0.11.9
updater | …
```
=> github: reenable grouped cargo updates

cli/src/commands/git.rs, cli/tests/test_git_clone.rs, docs/design/tracking-branches.md
=> cli: ensure default remote branch is imported by "git clone"

CHANGELOG.md, cli/src/commands/branch.rs, cli/tests/test_branch_command.rs
This is really a simple change that does the following in a transaction:
* Set the new branch name to point to the same commit as the old branch name.
* Set the old branch name to point to no commit (hence deleting the old name).
Before it starts, it confirms that the new branch name is not already in use.
1. Add `Rename` variant to `BranchSubcommands` enum.
2. Create `BranchRenameArgs` struct needed by `BranchSubcommands::Rename`
3. Implement `cmd_branch_rename`
Fixed: #1457
If applicable:
> N/A
> N/A
=> Implement a `rename` subcommand for the `branch` command.

lib/src/file_util.rs, lib/src/local_working_copy.rs, lib/src/simple_op_store.rs, lib/src/stacked_table.rs
=> file_util: don't try to overwrite existing content-addressed file on Windows

cli/src/commands/untrack.rs
Make it clearer what the command does, make the error message when the file
is not ignored less of a surprise.
Also, I think it's nice to mention `.git/info/exclude`, since the path is
not trivial to remember.
--------
This is a bit of a draft; I think it's OK as is, but it's not perfect. Are there FAQ 
entries I could link to? Should we recommend something instead of `.git/info/exclude`
for non-colocated repos?
=> cli `untrack --help`: mention that files need to be already be ignored

lib/src/default_index/mod.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/default_index/store.rs, lib/src/index.rs, lib/src/repo.rs
=> index: propagate some of index load errors

cli/src/commands/describe.rs, docs/git-comparison.md
1. Document the use of `JJ_USER='Foo Bar' JJ_EMAIL=foo.bar@example.com describe --reset--author` to set the author, mentioned by @dbarnett in https://github.com/martinvonz/jj/issues/328#issuecomment-1475583173
2. In git-comparison.md, propose a way to do `git grep foo` -- `grep foo $(jj files)`.
=> two minor documentation improvements

lib/src/default_index/composite.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/stacked_table.rs
=> index, stacked_table: clean up integer cast and serialization

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/git.rs, cli/src/commands/init.rs, cli/tests/test_alias.rs, cli/tests/test_global_opts.rs
=> cli: use cwd-relative workspace config to resolve default command and aliases

lib/src/default_index/composite.rs, lib/src/default_index/mutable.rs, lib/src/default_index/store.rs
=> index: refactor maybe_squash_with_ancestors()

lib/src/default_index/store.rs, lib/tests/test_index.rs
=> index: fix partial reindexing to not lose commits only reachable from one side

cli/src/commands/move.rs, cli/src/commands/split.rs, cli/tests/test_split_command.rs, lib/src/commit_builder.rs, lib/src/repo.rs, lib/tests/test_rewrite.rs
After this PR, the soon-to-be-internal APIs are used only in tests. The second part of this will be #2738.
The goal is to be able to more freely refactor DescendantRebaser after this. The new public API is not necessarily final or perfect, but should already be more manageable.
If applicable:
=> Refactor MutRepo to make DescendantRebaser private (pt 1)

cli/src/commands/bench.rs, lib/src/default_index/composite.rs, lib/src/default_index/entry.rs, lib/src/default_index/mod.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/id_prefix.rs, lib/src/index.rs, lib/src/revset.rs
=> index: IndexSegment API cleanup

cli/src/commands/debug.rs, cli/src/merge_tools/builtin.rs, lib/src/default_index/mod.rs, lib/src/default_index/store.rs, lib/src/repo.rs, lib/tests/test_index.rs, lib/testutils/src/test_backend.rs
=> on "debug reindex" failed, report operation id containing missing commits

cli/src/commands/branch.rs, cli/src/commands/git.rs, cli/src/commands/operation.rs, cli/src/commands/rebase.rs
=> cli: add missing copyright header to cli/src/commands/*.rs

docs/FAQ.md
This question is mildly popular on Discord so it's finally time to have an answer.
We should do something better in the future but the current solution is good enough for today.
cc @thoughtpolice 
If applicable:
=> FAQ: Describe how to integrate with Gerrit.

cli/src/commands/operation.rs, cli/tests/test_operations.rs, docs/operation-log.md, lib/src/index.rs, lib/src/op_walk.rs, lib/tests/test_operations.rs, lib/testutils/src/lib.rs
=> op_walk: clean up and add `op_id+` (child) operator support

lib/src/repo.rs, lib/src/rewrite.rs, lib/tests/test_commit_builder.rs, lib/tests/test_mut_repo.rs, lib/tests/test_rewrite.rs, lib/testutils/src/lib.rs
This finishes up #2737, making DescendantRebaser private to the library crate, and removing the use of the newly internal APIs from all the tests.
If applicable:
=> Refactor MutRepo to make DescendantRebaser private (pt 2)

lib/src/repo.rs, lib/src/rewrite.rs
This prevents a clone and does not affect the public API, as suggested
in https://github.com/martinvonz/jj/pull/2738#discussion_r1438903463.
=> DescendantRebaser: change `rebased()` method to `into_map()` that consumes the rebaser

docs/branches.md
This tries to explain Jujutsu's branch tracking for a newcomer. 
It is based on it's design doc in `docs/design/tracking-branches.md`.
I'd like to have some opinions on it, before finishing it. 
cc @yuja, @ilyagr 
If applicable:
=> docs: Add branch tracking to branches.md. 

cli/src/commands/rebase.rs, lib/src/rewrite.rs, lib/tests/test_rewrite.rs
Fixes #2760
Given the tree:
```
A-B-C
\
B2
```
And the command `jj rebase -s B -d B2`
We were previously marking B as abandoned, despite the comment stating that we were marking it as being succeeded by B2. This resulted in a call to `rewrite(rewrites={}, abandoned={B})` instead of `rewrite(rewrites={B=>B2}, abandoned={})`, which then made the new parent of `C` into `A` instead of `B2`
=> Rewrite instead of abandoning empty commits.

CHANGELOG.md, cli/src/commands/operation.rs, cli/tests/test_operations.rs, lib/src/op_walk.rs, lib/src/simple_op_heads_store.rs, lib/tests/test_operations.rs
In order to implement GC (#12), we'll need to somehow prune old operations. Perhaps the easiest implementation is to just remove unwanted operation files and put tombstone file instead (like git shallow.) However, the removed operations might be referenced by another jj process running in parallel. Since the parallel operation thinks all the historical head commits are reachable, the removed operations would have to be resurrected (or fix up index data, etc.) when the op heads get merged.
The idea behind this patch is to split the "op log" GC into two steps:
1. recreate operations to be retained and make the old history unreachable,
2. delete unreachable operations if the head was created e.g. 3 days ago. The latter will be run by "jj util gc". I don't think GC can be implemented 100% …
=> add "op abandon root..head" command that "reparents" operations

lib/src/default_index/mod.rs, lib/src/object_id.rs, lib/src/simple_op_store.rs, lib/tests/test_revset.rs
=> object_id: don't allow ObjectId::from_hex() a dynamically allocated string

Cargo.toml
I considered also updating the "homepage", but I think it's nice that it points to the README.
This complements @PhilipMetzger's suggestion from
https://discord.com/channels/968932220549103686/1167230861448581167/1192559848777334834
=> Cargo.toml: update documentation site

Cargo.toml, cli/src/cli_util.rs
We would like to use a non-static version string at Google. We have a workaround using Lazy, but it seems unfortunate to have to do that. Using dynamic strings requires Clap's `string` feature, which increases the binary size by 140 kiB (0.6%).
If applicable:
=> cli: allow non-static version strings from custom binaries

.github/workflows/build.yml
This is quite minor, but it took me a few minutes to figure out
the correct command. (I wanted to check whether CI would fail
without running CI or making a pull request).
It might be slightly better to print this text inside the build
logs, where people will be looking for certain if the CI fails,
but I didn't immediately find a good way to do so without
complicating the config too much.
=> GitHub workflow: document how one can install old Poetry locally

CHANGELOG.md, cli/src/commands/branch.rs, cli/tests/test_branch_command.rs
Fixed #1457 
If applicable:
> N/A
> N/A
=> Issue warning if renaming branch with a remote tracking branch.

docs/tutorial.md
Update the tutorial with current CLI outputs which seem to have changed substantially since the Tutorial was written, like expanded status output with change IDs and conflicts, longer log output, etc. The old data like commit IDs, change IDs, and author dates are kept, though the old author date could potentially be confusing.
Also some minor fixes in wording around the built-in merge tool and formatting.
If applicable:
=> docs: update CLI output in Tutorial

CHANGELOG.md, cli/src/commands/util.rs, cli/tests/test_util_command.rs, lib/src/file_util.rs, lib/src/op_store.rs, lib/src/operation.rs, lib/src/simple_op_store.rs, lib/tests/test_operations.rs
=> op_store: implement GC of unreachble operations and views

cli/src/cli_util.rs, lib/src/default_index/composite.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/default_index/revset_engine.rs, lib/src/index.rs, lib/src/revset.rs, lib/tests/test_revset.rs
=> revset: remove unused lifetime parameter from Revset<'index>

docs/git-comparison.md
To make the jj command more discoverable.
This seems like a clearly useful thing to add, irrespective of the outcome of the other PR.
If applicable:
=> docs: add git comparison for `jj workspace root`

lib/src/default_index/store.rs, lib/src/view.rs, lib/tests/test_index.rs
=> index: fix reindexing to scan all referenced commits such as hidden remote refs

docs/git-comparison.md
Sadly, ripgrep won't honor the .gitignore files in the absence of a .git directory, so we need to pass an annoying flag (for non-colocated repos).
That seems worth adding despite the existing suggestion, because rg is faster, and for existing users for rg, it would teach them how to make rg work as expected.
If applicable:
=> doc: suggest ripgrep as an equivalent of `git grep`

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/nix-update-flake.yml, .github/workflows/release.yml
The security scanner doesn't like depending on a tag version (because tags can be moved).
If applicable:
=> github: avoid using tags in action version specifiers

CHANGELOG.md, cli/src/commands/config.rs, cli/tests/test_config_command.rs
fix #2828 
```shell
 ~/workspace/jj ❯ ./target/debug/jj config list       
ui.editor="emacs -nw -q"
ui.pager="bat -l toml --plain"
user.name="Daehyeok Mun"
git.fetch="upstream"
git.push="orgin"
user.email="daehyeok@google.com"
 ~/workspace/jj ❯ ./target/debug/jj config list  --include-overridden
ui.editor="emacs -nw -q"
ui.pager="bat -l toml --plain"
user.name="Daehyeok Mun"
git.fetch="upstream"
git.push="orgin"
user.email="daehyeok@google.com"
```
If applicable:
=> Allow printing overridden config values via `--include-overridden`.

lib/src/default_index/composite.rs, lib/src/default_index/mod.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/index.rs
`GitBackend::gc()` will recreate no-gc refs for the indexed heads. We could collect all historical heads by traversing operation log, but it isn't enough because there may be predecessor links to hidden commits, and "git gc" isn't aware of predecessors.
If applicable:
=> RFC: index: add all_heads() that iterates heads of all indexed commits

CHANGELOG.md, cli/src/commands/config.rs, cli/tests/test_config_command.rs
Fix #2827
user level configuration file(`"$HOME/Library/Application Support/jj/config.toml"`)
```toml
[user]
name = "Daehyeok Mun"
email = "daehyeok@gmail.com"
[ui]
pager = "bat -l toml --plain"
editor = "emacs -nw -q"
```
repo level configuration file(`.jj/repo/config.toml`)
```toml
[user]
email = "daehyeok@google.com"
```
example outputs.
```bash
#Release binary(v0.13.0)
~/workspace/jj ❯ jj config list
ui.editor="emacs -nw -q"
ui.pager="bat -l toml --plain"
user.name="Daehyeok Mun"
user.email="daehyeok@google.com"
#jj config list without any argument
#Doens't change anything.
~/workspace/jj ❯ ./target/debug/jj config list
ui.editor="emacs -nw -q"
ui.pager="bat -l toml --plain"
user.name="Daehyeok Mun"
user.email="daehyeok@google.com"
#print config options which defined in user level …
```
=> Support `--user` and `--repo` argument for `config list` command

flake.lock
Summary: Includes a newer version of `cargo nextest`, which has some nice little features (like the `binary_id()` filter.)
Change-Id: Ie6f822d3a5c16ec30e41bc830ee4b580a6547428
=> chore: `nix flake update`

Cargo.lock
A version of smallvec was yanked from crates.io, causing failures like the one in #2848. This should fix that.
=> cargo: run `cargo update`

cli/src/cli_util.rs, cli/src/commands/git.rs, cli/src/commands/init.rs, cli/src/git_util.rs, cli/src/lib.rs
Gerrit also needs to be able to push low-level refs into upstream remotes, just like `jj git push` does. Doing so requires providing callbacks e.g. for various password entry mechanisms, which was private to the `git` command module.
Pull these out to a new module `git_utils` so we can reuse it across the two call sites.
This also moves a few other strictly Git-related functions into `git_utils` as well, just for the sake of consistency.
Note: This was cut out of #2845 to keep the review smaller and also because it's largely procedural and simple.
=> cli: move some git utilities to new `crate::git_utils`

docs/contributing.md
On my machine, this halves the time taken by `cargo insta test --workspace
--test-runner nextest`.
I don't believe there would be a worthwhile improvement when not using
`nextest`. I also documented how to tell whether using `mold` is
worthwhile.
I was reminded of this by https://github.com/martinvonz/jj/pull/2858.
=> docs `contributing.md`: document using `mold` linker with `nextest`

docs/git-comparison.md
Someone felt that our "Not needed" sounded dismissive. This patch tries to clarify that it's the *command* (not the use case) we consider not needed.
If applicable:
=> git-comparison: explain why equivalent of `git stash` is not needed

CHANGELOG.md, cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/src/ui.rs, cli/tests/common/mod.rs, cli/tests/test_next_prev_commands.rs
Adds `ui.prompt...()` functions and uses them to fix issue #2126
If applicable:
=> Improve prompt support in JJ

cli/Cargo.toml, cli/src/commands/branch.rs, cli/tests/test_branch_command.rs, lib/Cargo.toml, lib/src/default_index/revset_engine.rs, lib/src/revset.rs
This is so that backends (especially backends that don't have all commits locally, but this is also useful for backends that do, since commit walking is not cost-free) don't need to walk commits unnecessarily when calculating ahead/behind when reporting branches.
I don't think this warrants a change in CHANGELOG.md, but if you think this should go under "New features" or "Fixed bugs", let me know and I'll amend the commit.
If applicable:
=> Teach the Revset trait a way to estimate commit counts

docs/git-comparison.md
Wol on lwn.net pointed out that our current description in the Git Comparison doc for why there is no staging area can be interpreted as saying that it's because it simplifies the CLI. It took me a while to see that interpretation, but it makes sense to me now. This patch tries to clarify that we have better tools than the staging area for manipulating commits.
If applicable:
=> docs: try to clarify that jj doesn't need a staging area

cli/src/ui.rs
=> ui: remove redundant .to_lowercase() from prompt_yes_no()

lib/tests/test_rewrite.rs
This demonstrates the minor bug discussed in
https://github.com/martinvonz/jj/pull/2766#discussion_r1442365389 AKA https://github.com/martinvonz/jj/issues/2869.
It's also interesting whether changing the definition of "discardable" commit would affect this test, see
https://github.com/martinvonz/jj/issues/2859#issuecomment-1903275884
(I think it won't, but still)
=> `test_rebase_abandoning_empty`: Demonstrate effects on children of an empty `@`

cli/src/commands/next.rs
=> cli: colorize choices of prev/next commits

CHANGELOG.md, cli/src/commands/resolve.rs, cli/tests/test_resolve_command.rs
Often, I resolve a file, close my merge editor, then wonder exactly which file I was resolving conflicts in. I've found this information helpful.
If applicable:
=> cli: display which file's conflicts are being resolved

cli/src/cli_util.rs, cli/src/commands/sparse.rs, cli/src/description_util.rs
This consolidates a bunch of boilerplate io+tempfile code used in sparse.rs and description_util.rs into cli_util.rs, making the two call sites much simpler.  This makes it easier for future callers to invoke the workflow of 'have the user edit this arbitrary string' without going through extra setup.
If applicable:
=> cli_util: make running an editor on a tempfile easier

docs/branches.md, docs/glossary.md
This follows up on #2625 and updates all sections of `branches.md` to represent the new default of `git.auto-local-branch=false`.
I also realized that the paragraph we discussed for so long with @PhilipMetzger actually repeats information that was already present a bit earlier in the file. So, I removed most of it and moved the rest. Sorry I didn't notice this earlier.
=> docs `branches.md`: explain the new defaults and reorganize 

cli/examples/custom-working-copy/main.rs, cli/src/cli_util.rs, cli/src/commands/workspace.rs, lib/src/local_working_copy.rs, lib/src/working_copy.rs, lib/src/workspace.rs, lib/tests/test_workspace.rs
This combines the `WorkingCopyInitializer` and `WorkingCopyFactory` types into a single `WorkingCopyFactory` trait that implements both. This allows `jj workspace add` to create new working copies for custom implementations with minimal changes.
If applicable:
=> Refactor working copy initializers

cli/src/commands/branch.rs
This goes with `c`, `s`, `f`. I feel like it's a relatively common command now that `auto-local-branch` defaults to `false`.
I didn't add `u` for `untrack` because it seems a little ambiguous (un-what?); there may be other `branch` commands that undo something in the future.
=> cli `branch`: add alias `t` for `track`

CHANGELOG.md, cli/src/commands/mod.rs, cli/src/commands/root.rs, cli/tests/test_root.rs
This is a convenient command when scripting around, for things like: $ cd $(jj root) && do something
Currently this fails if the path to the repo contains non-utf8 bytes, similarly to `jj status` failing on non-utf8 paths inside the repo.
This is a proposal out of the blue, but since this is a small change and it seems not contentious, I figured if it was simpler to do it and possibly argue about the utility of the PR, rather than have a round of discussion followed by a round of PR.
If applicable:
=> cli: implement jj root

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/git.rs, cli/src/commands/init.rs, cli/tests/test_git_colocated.rs, cli/tests/test_init_command.rs, lib/src/git.rs, lib/src/op_store.rs, lib/tests/test_git.rs
=> cli: reorder import of git head/refs and snapshot 

CHANGELOG.md, cli/src/diff_util.rs, cli/tests/test_diff_command.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_restore_command.rs
@joyously ponted out that `R` could be interpreted as "renamed" instead of "removed".  "Deleted" is unambiguous.
I'm not sure if this qualifies as a breaking change, but I put it there for now.
If applicable:
- (n/a?) I have updated the documentation (README.md, docs/, demos/)
=> cli: change `R` to `D` for "deleted" in diff summary

CHANGELOG.md, cli/examples/custom-backend/main.rs, cli/src/commands/util.rs, lib/src/backend.rs, lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/store.rs, lib/tests/test_git_backend.rs, lib/testutils/src/test_backend.rs
=> git_backend: on gc(), remove unreachable no-gc refs and compact them 

cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/src/commands/rebase.rs, cli/tests/cli-reference@.md.snap
This prevents rust doctests from trying to compile the code blocks.
I don't think we use doctests much or at all, but I'd like `cargo insta test --test-runner nextest --accept --workspace` to pass.
If applicable:
=> docs: fixup to b318b200, mark code blocks in help as text

lib/src/rewrite.rs
Seeing #2901 made me decide to send these commits I wrote a few days ago before they go stale. It doesn't look like anything conflicts with that PR. FYI, I'm working on #2600 a little bit here and there. I guess I should assign that to myself. I'll do that.
If applicable:
=> Minor cleanup of DescendantRebaser 

lib/src/op_heads_store.rs, lib/src/op_store.rs, lib/src/simple_op_heads_store.rs, lib/src/simple_op_store.rs
It's useful for custom commands to be able to downcast to custom backend types.
If applicable:
=> backends: implement as_any() on OpStore and OpHeadsStore too

docs/git-comparison.md, docs/revsets.md
I couldn't come up with a Git analogue of `jj log`, but I think it's OK leaving it as a TODO makes the point. Perhaps somebody can figure it out.
Also, all the correspondences are not completely precise, so I didn't emphasize it every single time.
=> docs: emphasize and clarify log revsets relevant to people coming from git

docs/design/sparse-v2.md, mkdocs.yml
Proposal for a Sparse Patterns rewrite, to address multiple feature gaps.
Looking for feedback and approval before moving forward with real changes.
If applicable:
=> sparse-v2: design doc proposition for Sparse Patterns refactoring

CHANGELOG.md, cli/src/commands/config.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_config_command.rs, docs/config.md
Instead of `jj config path`, I considered suggesting
EDITOR=echo jj config edit --user
but Windows. Also, I'm not sure whether that trick would please or annoy people.
If applicable:
=> config cli and docs: make it easier for users to find the config file

cli/src/commands/init.rs, lib/src/file_util.rs
Split from #2807 
* Refactor out file_util::create_or_reuse_dir() which will be used by all 'init' functionality to create the repo root directory.
=> cli: Refactor workspace root directory creation

cli/src/cli_util.rs, cli/src/commands/git.rs, cli/src/commands/init.rs
* Move git_init() to cli/src/commands/git.rs and call it from there.
* Move print_trackable_remote_branches into cli_util since it's not git specific, but would apply to any backend that supports remote branches.
* A no-op change. A follow up PR will make use of this.
* This completes the refactoring of init.rs
=> cli: Move git_init() from init.rs to git.rs

Cargo.lock
Noticed CI on #[2928](https://github.com/martinvonz/jj/pull/2928) was broken
=> chore: Bump yanked `iana-time-zone` crate

CHANGELOG.md, cli/src/commands/checkout.rs, cli/src/commands/merge.rs, cli/src/commands/mod.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_checkout.rs, cli/tests/test_git_colocated.rs, cli/tests/test_new_command.rs, docs/git-comparison.md, docs/tutorial.md
As discussed on Discord and in previously in #1713, this deprecates `jj checkout` and `jj merge`, as they are simply specializations for existing functionality under `jj new`.
Both commands are now hidden by default from `help`.
Supersedes #1713.
If applicable:
=> cli: deprecate `jj checkout` and `jj merge`

lib/src/rewrite.rs, lib/tests/test_rewrite.rs
This mostly reverts https://github.com/martinvonz/jj/pull/2901 as well as its fixup https://github.com/martinvonz/jj/pull/2903. The related bug is reopened, see https://github.com/martinvonz/jj/issues/2869#issuecomment-1920367932.
The problem is that while the fix did fix #2869 in most cases, it did reintroduce the more severe bug https://github.com/martinvonz/jj/issues/2760 in one case, if the working copy is the commit being rebased.
For example, suppose you have the tree
```
root -> A -> B -> @ (empty) -> C
```
`jj rebase -s B -d root --skip-empty` would work perfectly before this commit, resulting in
```
root -> A
\-------B -> C
\- @ (new, empty)
```
Unfortunately, if you run `jj rebase -s @ -d A --skip-empty`, you'd have the following result (before this commit), which shows the …
=> `jj rebase --skip-empty`: revert commits cfcc7c5e and becbc889

cli/tests/cli-reference@.md.snap, cli/tests/test_generate_md_cli_help.rs
There are many minor bugs that are difficult to fix in the short-term.
See also the commit message for https://github.com/martinvonz/jj/commit/a197409b2b9bd61c297c12207a2bd088c5c1a723
The warning looks like this:
=> docs CLI reference: add a warning that it is experimental

cli/src/commands/git.rs, cli/tests/test_git_push.rs
Previously, `jj git push; jj git push` would tell the user that "No branches point to the specified revisions.". I found this confusing, even though strictly speaking it is correct (as the default revset only considers revisions that haven't been pushed to the remote).
Fixes #2241
If applicable:
- n/a I have updated `CHANGELOG.md`
- n/a I have updated the documentation (README.md, docs/, demos/)
- n/a I have updated the config schema (cli/src/config-schema.json)
=> cli `git push`: change warning if default revset contains no branches

cli/src/commands/util.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_shell_completion.rs
A few minor updates after 0f27152 AKA #2945
Specifically, I tried to change the help text so that it looks better as Markdown. I also reworded the deprecation warning and added a hint.
=> cli: minor updates to `jj util completion`

CHANGELOG.md, cli/src/commands/git.rs, cli/src/commands/init.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_git_init.rs
Implement `jj git init`
There are two flags which work as mostly expected.
See `GitInitArgs` for details.
Some improvements around `colocated` repos vs `--git-repo=.` will come after this PR is merged.
The actual delta in this PR is tiny. The only thing new here is hooking up the `jj git init` command itself and inside `git_init` handling `--colocated` differently.
The rest of the PR is test and documentation.
If applicable:
=> cli: Add a `jj git init` command.

docs/FAQ.md
Working with Gerrit requires directly invoking git commands, which is awkward without a co-located repo. Add a hint to use a co-located repo.
This is something I tripped over. it was unclear from the instructions whether or not I should use `jj git push` or underlying `git`).
This becomes irrelevant if #2845 is merged.
If applicable:
=> docs: add co-located repo hint to Gerrit question

CHANGELOG.md, cli/src/commands/git.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_git_push.rs
=> cli `git push`: add `--tracked` option to push all *tracked* branches

cli/src/cli_util.rs, cli/src/commands/git.rs, cli/src/git_util.rs, cli/tests/test_git_init.rs
=> cli: do initial import of Git refs without touching HEAD 

cli/src/cli_util.rs, cli/tests/test_global_opts.rs
When the user doesn't have a configured default command, we show a hint saying to set `ui.default-command`. I think the user is very likely to want to set that in the user-wide config, so let's include the command in the hint.
If applicable:
=> cli: include command to set config in hint about default command

cli/examples/custom-working-copy/main.rs, cli/src/cli_util.rs, cli/src/commands/untrack.rs, lib/src/local_working_copy.rs, lib/src/working_copy.rs, lib/tests/test_local_working_copy.rs
Our virtual file system at Google (CitC) would like to know the commit so it can scan backwards and find the closest mainline tree based on it. Since we always record an operation id (which resolves to a working-copy commit) when we write the working-copy state, it doesn't seem like a restriction to require a commit.
If applicable:
=> working_copy: make reset() take a commit instead of a tree

docs/FAQ.md
New users often want to know how to just see what `git log` would show. Putting it in the FAQ isn’t perfect but might help a bit.
=> docs: Add FAQ item for `git log`

cli/src/commands/branch.rs, cli/tests/test_branch_command.rs
A version of this was previously part of #2935
=> cli `branch rename`: change warning when renaming a branch with remotes

cli/src/commands/git.rs, cli/tests/cli-reference@.md.snap
It tries to push all deleted branches, but can only succeed for tracked branches.
Closes #2946, as there's probably no need to have `--deleted --tracked` that would only be different in that the warnings wouldn't be printed. Thanks to @yuja for pointing this out.
=> docs: document that `git push --deleted` only pushes tracked branches

lib/src/view.rs
Mostly, I was a bit confused that some of these functions return a `TrackingRefPair` but don't seem to take into account whether the remote branch is being tracked or not.
-------------------
This fell out of #2935.
Please let me know if the new version is not clearer, or especially if I misunderstood.
=> view.rs: clarify some internal function docstrings

cli/src/commands/git.rs, lib/src/refs.rs, lib/src/view.rs
As discussed in
https://github.com/martinvonz/jj/pull/2962#discussion_r1479384841, the previous name is confusing since the struct is used for pairs where the remote branch is not tracked by the local branch.
------------
Another name I considered was just `RefPair`. If you don't like either, we could keep it as is for now.
=> lib refs.rs: rename `TrackingRefPair` to `LocalAndRemoteRef`

CHANGELOG.md, cli/src/template.pest, cli/src/template_builder.rs, cli/src/template_parser.rs, cli/tests/test_templater.rs, docs/templates.md
=> templater: add support for logical operators: `||`, `&&`, `!`

README.md
Apparently this previously-beta markdown syntax from GitHub "graduated" to a full feature in such a way that it it actually regressed in features, so doing this `[!WARNING]` inline inside of a list is no longer valid. Sigh. Scoot it up a level in the document, and just make it part of the section and not inside the list.
=> readme: fix `[!WARNING]` section

cli/examples/custom-working-copy/main.rs, cli/src/cli_util.rs, cli/src/commands/workspace.rs, cli/tests/test_workspaces.rs, lib/src/local_working_copy.rs, lib/src/working_copy.rs
In the commit message, I've added a discussion of alternate ways of how we can handle this situation, with my rationale for how I ended up doing it in the commit. If there are other (and maybe better) ways of handling this, feel free to let us know.
If applicable:
=> workspace: recover from missing operation

cli/src/commands/workspace.rs
Using workspace_command means that we record the command arguments into the ops log.
This also allows us to avoid a clone of an Arc.
If applicable:
=> workspace: create transaction using workspace_command

docs/config.md
I enabled automerge for #2994, but forgot to actually *push* my changes before resolving all the conversations, so GitHub insta-merged it.
This just addresses Ilya and Philip's final comments on #2994.
=> docs: fix some automerge fallout

.github/workflows/build.yml, CHANGELOG.md, Cargo.toml, cli/tests/test_git_clone.rs, docs/contributing.md, flake.lock, flake.nix, lib/src/default_index/revset_graph_iterator.rs, lib/src/tree_builder.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_revset.rs
Summary: I was testing 1.72.0, but in order to see if some clippy bugs had been fixed, I bumped it to 1.73.0. The bugs weren't fixed; but I guess we can just bump things here, anyway.
Change-Id: I038346d8a821f83f62cbf122a79c8f30
If applicable:
=> rust: bump MSRV to 1.76.0

CHANGELOG.md, cli/src/commands/show.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_show_command.rs
This makes `jj show` accept `-T`/`--template` option to render its output. I've looked how `jj log` does it for inspiration :)
Closes #2969
If applicable:
=> Make `jj show` accept a template to render its output

cli/src/merge_tools/mod.rs
=> cli: inform the user of the command which disables the hint

CHANGELOG.md, cli/src/commands/git.rs, cli/tests/cli-reference@.md.snap
Adding short `-b` option for `--branch` in `jj git fetch` makes it consistent among other commands – `jj git push` and `jj rebase`.
I don't think a test for this change is needed but if you think otherwise I'll happily add it.
If applicable:
=> cli: add short `-b` option for `--branch` in `jj git fetch`

CHANGELOG.md, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/default_index/store.rs, lib/src/file_util.rs, lib/tests/test_index.rs
=> index: move segment files to sub directory, add version number

CHANGELOG.md, cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_next_prev_commands.rs
=> Make `next/prev` infer `--edit` from running on non-head

CHANGELOG.md, Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/config/windows.toml, cli/src/ui.rs, docs/config.md
Added a built-in pager since the solution in #2928 felt hacky. Also should address #2044
If applicable:
- [X ] I have updated `CHANGELOG.md`
- [X ] I have updated the documentation (README.md, docs/, demos/)
- [X ] I have updated the config schema (cli/src/config-schema.json)
=> Use `minus` as a builtin pager

lib/src/index.rs, lib/tests/test_index.rs
=> index: fix change id resolution test to not depend on deterministic order

lib/src/default_index/readonly.rs
=> index: adjust binary search function to conform to std behavior

README.md
This bundles all Jujutsu related media (the talk, its slides and the three articles we were featured in) 
into a section.
Also update the news section to mention the recent deprecations and the three articles we recently 
were featured in. 
Thanks to everyone who wrote one.
[Rendered](https://github.com/martinvonz/jj/tree/push-mtrqnqsyrwrt)
=> Readme: Add a related media section and tidy up the news a bit. 

Cargo.toml
This is recommended by the insta documentation.
See: https://docs.rs/insta/latest/insta/#optional-faster-runs.
Running on an M1 MacBook Pro
Before:
```
________________________________________________________
Executed in   31.10 secs    fish           external
usr time  118.87 secs  107.00 micros  118.87 secs
sys time   46.19 secs  847.00 micros   46.19 secs
```
After:
```
________________________________________________________
Executed in   29.73 secs    fish           external
usr time  119.58 secs    0.13 millis  119.58 secs
sys time   46.27 secs    1.74 millis   46.27 secs
```
This doesn't seem like a huge change, and there's noise in the measurements, but I don't think it can hurt and insta recommends it.
=> Compile insta and similar in opt mode for faster testing

lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs
=> index: extract id lookup helpers

cli/tests/test_concurrent_operations.rs, cli/tests/test_debug_command.rs, cli/tests/test_operations.rs, cli/tests/test_util_command.rs, cli/tests/test_workspaces.rs, lib/src/backend.rs, lib/src/content_hash.rs, lib/src/op_store.rs, lib/src/simple_op_store.rs, lib/tests/test_operations.rs
The `ContentHash` documentation specifies that implementations for enums should hash the ordinal number of the variant contained in the enum as a 32-bit little-endian number and then hash the contents of the variant, if any.
The current implementations for `std::Option` and `MergedTreeId` are non-conformant since they hash the ordinal number as a u8 with platform specific endianness.
Fixes #3051
=> Fix the ContentHash implementations for std::Option and MergedTreeId and RemoteRefState

lib/src/content_hash.rs
This is for completeness and to avoid accidents such as someone calling `ContentHash::hash(1234u32.to_le_bytes())` and expecting it to hash properly as a u32 instead of a 4 byte slice, which produces a different hash due to hashing the length of the slice before its contents.
=> Implement ContentHash for u32 and u64

lib/src/op_store.rs
It no longer makes sense after e1fd402d3948 "Fix the ContentHash implementations for std::Option, MergedTreeId, and RemoteRefState."
If applicable:
=> op_store: remove unneeded repr(u8) from RemoteRefState

lib/src/working_copy.rs, lib/tests/test_workspace.rs
If we make WorkingCopy Send, then Workspace will be Send, which is useful for long-running servers. All existing impls are Send already, so this is just a marker.
If applicable:
=> working_copy: add Send supertrait

cli/src/commands/log.rs, cli/src/commands/obslog.rs, cli/src/commands/operation.rs, cli/src/graphlog.rs
`graphlog::Edge` is used somewhat inconsistently. I've replaced `Edge::Present` with two distinct `Edge::Direct` and `Edge::Indirect` which simplifies the construction of the enum.
If applicable:
=> graphlog: refactor graphlog::Edge enum and its usage

CHANGELOG.md, cli/src/commands/workspace.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_workspaces.rs
=> Make new workspace inherit sparse patterns

cli/tests/test_log_command.rs, lib/src/default_index/composite.rs, lib/src/default_index/entry.rs, lib/src/default_index/mod.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/tests/test_index.rs
=> index: build and use persistent change id lookup table (with non-lazy reachability test)

lib/src/default_index/readonly.rs
=> index: clean up base data offsets calculation

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/git.rs, cli/src/git_util.rs, cli/tests/test_branch_command.rs, cli/tests/test_git_clone.rs, cli/tests/test_git_colocated.rs, cli/tests/test_git_fetch.rs, cli/tests/test_git_import_export.rs, lib/src/git.rs
Adds imported branches list for git fetch.
```
jj git fetch
From origin
* [new untracked branch]  test2
```
If applicable:
=> cli: list new remote branches during git fetch

CHANGELOG.md, cli/src/commands/move.rs, cli/tests/cli-reference@.md.snap
I find myself often using `jj move` when working and having shorthands for `--from/--to` would be very useful
If applicable:
=> cli: move: Add -f/-t for --from/--to to `jj move`

lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs
=> index: don't store commit ids in sorted lookup table to save disk space

.github/workflows/build.yml, CHANGELOG.md, cli/src/config-schema.json, docs/config.md, flake.nix, lib/src/gpg_signing.rs, lib/src/lib.rs, lib/src/signing.rs, lib/src/ssh_signing.rs, lib/tests/runner.rs, lib/tests/test_gpg.rs, lib/tests/test_ssh_signing.rs
This is an expansion on the work that was started by @necauqua in #2728 with the intent of getting the core implementation ready to land.
This involved some small behavioural tweaks such as adding config to control whether or not commit signatures are verified and displayed by default. This also involved a lot of massaging to get the test suite green again.
One significant addition to the original work is the addition of an SSH signing backend which works as closely as possible to the git SSH signing workflow.
If applicable:
=> Commit signing backend implementation

cli/src/cli_util.rs, cli/tests/test_concurrent_operations.rs, cli/tests/test_debug_command.rs, cli/tests/test_operations.rs, cli/tests/test_util_command.rs, cli/tests/test_workspaces.rs, lib/src/op_store.rs, lib/src/protos/op_store.proto, lib/src/protos/op_store.rs, lib/src/simple_op_store.rs, lib/src/transaction.rs, lib/tests/test_operations.rs
It should be useful at least in the presentation layer to know which operations correspond to working-copy snapshots. They might be rendered differently in the graph, for example. Or maybe an undo command wants to warn if you just undid a snapshot operation. This patch just introduces a field in the metadata to store the information.
If applicable:
=> op_store: add metadata flag for ops representing working-copy snapshot

Cargo.lock, Cargo.toml, cli/examples/custom-working-copy/main.rs, cli/src/cli_util.rs, cli/src/commands/untrack.rs, lib/Cargo.toml, lib/src/gitignore.rs, lib/src/local_working_copy.rs, lib/src/working_copy.rs
This PR rebase and fix broken test cases from #2499
If path is ends with slash(/) consider it as a directory. All dir path is passed after calling [`to_internal_dir_string`](https://github.com/martinvonz/jj/blob/ce295f8bc2a30a7baaffea0b4ad9fd2707357522/lib/src/repo_path.rs#L277). So it might not a problem. (any file system allowed to create file with slash??)
Here is some regressions with previous implements. See `gitignore.rs` test cases 
| before  | after | 
| ------------- | ------------- |
| `assert!(!matches(b"\\w\n", "w"));`  |  `assert!(matches(b"\\w\n", "w"));`  | 
ignore module throw `Glob { glob: Some("a b \\"), err: "dangling '\\'" }` error
| before  | after | 
| ------------- | ------------- |
| `assert!(matches(b"a b \\  \n", "a b  "));` | …
=> Switch to ignore crate for gitignore handling.

lib/src/backend.rs, lib/src/content_hash.rs, lib/src/object_id.rs, lib/src/op_store.rs, lib/src/repo_path.rs
This is a pure refactor with no behavior changes.
=> Replace uses of content_hash! with #[derive(ContentHash)]

lib/proc-macros/src/content_hash.rs
Consider this code:
```
struct NoContentHash {}
#[derive(ContentHash)]
enum Hashable {
NoCanHash(NoContentHash),
Empty,
}
```
Before this commit, it generates an error like this:
```
error[E0277]: the trait bound `NoContentHash: ContentHash` is not satisfied
--> lib/src/content_hash.rs:150:10
|
150 | #[derive(ContentHash)]
|          ^^^^^^^^^^^ the trait `ContentHash` is not implemented for `NoContentHash`
151 | enum Hashable {
152 |     NoCanHash(NoContentHash),
|     --------- required by a bound introduced by this call
|
= help: the following other types implement trait `ContentHash`:
bool
i32
i64
u8
u32
u64
std::collections::HashMap<K, V>
BTreeMap<K, V>
and 35 others
For more information about this error, try `rustc --explain E0277`.
```
After this commit, it generates a better error …
=> Output better error messages when deriving ContentHash for an enum fails

lib/src/fsmonitor.rs, lib/src/local_working_copy.rs, lib/src/settings.rs, lib/src/working_copy.rs, lib/tests/test_local_working_copy.rs
I wanted to see how the `ignore` update (#3071) changed the snapshot performance on nixpkgs, but I don't want to generally turn off the fsmonitor since it's useful there. Add the ability to disable it through an explicit `"none"` option.
I also thought about fixing this in `fsmonitor_kind()` by short-circuiting the `"none"` string in `settings.rs`, but this seems more type safe and is only 1 or 2 extra lines.
If applicable:
=> fsmonitor: allow `core.fsmonitor = "none"` to disable

lib/tests/test_gpg.rs
This adds a cargo feature `signing-tests` which is used to disable the gpg and ssh signing tests unless set.
This is done in order to avoid requiring all collaborators to have setup all the tools on their local machines that are required to test commit signing.
---
Not sure if this is the best way to address this.
Closes #3096
=> sign: Hide tests behind feature

flake.nix
This matches the behavior of the actual `nix build` more closely, and might also help Anton, since he was debugging some recompilation issues on his machine, where `RUSTFLAGS` might have become inconsistent due to VS Code.
=> nix: overwrite, don't append, to `$RUSTFLAGS`

cli/testing/bench-revsets-git.txt, lib/src/default_index/revset_engine.rs
=> revset: ad-hoc optimization for range queries containing unwanted wanted heads

CHANGELOG.md, cli/src/commands/log.rs, cli/src/config-schema.json, cli/tests/cli-reference@.md.snap, cli/tests/test_immutable_commits.rs, lib/src/settings.rs
=> cli: change default log revset to not include all tagged heads

cli/src/commit_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, docs/templates.md, lib/src/operation.rs
=> templater: translate keywords to "self" methods by core template engine

cli/src/commands/diff.rs, cli/tests/cli-reference@.md.snap
The description of `jj diff` was lost in commit b5e4e670. We later got a short description for it in b5e4e670. This patch restores the original description.
If applicable:
=> cli: restore documentation of `jj diff` lost in split of commands module

.github/workflows/build.yml, .github/workflows/nix-linux.yml
This should nerf some of the impact of the flaky Windows GPG tests right now, which are currently non-deterministically running into hangs, causing a lot of PRs to stall out. 15 minutes was chosen as a good trade-off between "pretty far from our current build times" while also catching obvious bugs and flakes.
=> github: cap builds to 15 minutes

.github/workflows/nix-linux.yml, flake.nix
When running the `nix build`, the `buildRustPackage` function -- which builds the `jj` crates -- calls `cargo build --release` with flags like `HOST_CXX` set. This is called the `buildPhase`. Then, it runs the `checkPhase`, which calls `cargo nextest`, in our case. However, it does not set `HOST_CXX`, for some reason.
The intent of `buildRustPackage` is that the `buildPhase` and `checkPhase` have their compilation options fully aligned so that they reuse the local cargo `target/` cache directory, avoiding a full recompilation. However, the lack of `HOST_CXX` above among others causes a cache miss, and a bunch of cascading recompilations. The net impact is that we compile all of the codebase once in `buildPhase`, then again in `checkPhase`, making the Nix CI build 2x slower on average than …
=> github(nix): don't build `jj` twice when testing

cli/src/commit_templater.rs, cli/src/operation_templater.rs, lib/src/backend.rs, lib/src/default_index/revset_engine.rs, lib/src/git_backend.rs, lib/src/op_heads_store.rs, lib/src/op_walk.rs, lib/src/operation.rs, lib/tests/test_operations.rs
=> templater: clean up `build_*_keyword()` functions

CHANGELOG.md, cli/src/template_builder.rs, docs/templates.md
=> templater: add special "self" variable to refer to top-level object

CHANGELOG.md, cli/src/commands/rebase.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_rebase_command.rs, lib/src/rewrite.rs, lib/tests/test_rewrite.rs
=> Make `jj rebase --skip-empty` keep already empty commits

CHANGELOG.md, cli/src/commands/branch.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_branch_command.rs, docs/branches.md
=> cli `branch list`: list tracked branches

cli/src/commit_templater.rs, cli/src/operation_templater.rs
=> templater: extract Commit methods to HashMap

cli/src/commands/abandon.rs, cli/src/commands/git.rs, cli/src/commands/move.rs, cli/src/commands/rebase.rs, cli/src/commands/squash.rs, cli/src/commands/unsquash.rs, cli/tests/cli-reference@.md.snap
=> cli: document that we create a new working-copy commit for abandoned one

docs/windows.md
Attempts to add prescriptive guidance for dealing with LF line endings on Windows.
If applicable:
=> docs: add guidance for handling CRLF on Windows

cli/src/commit_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, cli/src/template_parser.rs
=> templater: migrate non-core methods to symbol table

cli/src/commands/workspace.rs, cli/tests/test_workspaces.rs
The recovery commit we create when we run into a stale working copy with a missing operation currently has an empty tree. Our commit backend at Google creates an index of which files changed in each commit. That gets really expensive when a commit deletes all files in the repo, as these recovery commits do. So for our backend, it is much better to make the recovery commit empty instead. That's what this patch does.
It almost doesn't matter functionally what tree we use for it since we don't care much about the current tree when snapshotting the working copy. It does matter in a few cases, however. One case is for conflicts. In that case, it's likely better to use the recovery commit's parent as base tree (as we do by making the recovery commit empty) than to use an empty tree, as that …
=> workspace: make recovery commit empty instead of deleting everything

lib/src/backend.rs, lib/src/object_id.rs
This allows us to define documentation comments for types implemented using the id_type! macro. Comments defined above the type inside the macro will be captured and visible in generated docs.
Example:
```
id_type!(
/// Stable identifier for a [`Commit`]. Unlike the `CommitId`, the `ChangeId`
/// follows the commit and is not updated when the commit is rewritten.
pub ChangeId
);
```
This commit also adds documentation for the `CommitId` and `ChangeId` types defined using the `id_type!` macro.
=> Allow id_type! to capture doc comments

Cargo.lock, cli/Cargo.toml, cli/src/cli_util.rs, cli/src/commit_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, cli/src/template_parser.rs, cli/tests/test_revset_output.rs, cli/tests/test_templater.rs
=> templater: migrate core methods to table lookup, add typo hints

.github/workflows/build-nix.yml, flake.nix
The `jj-proc-macros` crate caused the nix-on-macOS build to regress, due to https://github.com/nextest-rs/nextest/issues/267. Work around this, and add nix-on-macOS to the CI matrix.
Closes #3161.
=> nix: fix build on macOS

cli/src/diff_util.rs, cli/src/merge_tools/mod.rs, cli/tests/common/mod.rs, cli/tests/test_diff_command.rs, cli/tests/test_git_init.rs, cli/tests/test_global_opts.rs, cli/tests/test_init_command.rs
=> cli: don't ignore `diff --tool=:builtin`, report error

cli/src/template_builder.rs, cli/tests/test_commit_template.rs, docs/templates.md
=> templater: add `.len()` method, make `.substr()` byte-index based

cli/examples/custom-commit-templater/main.rs, cli/src/cli_util.rs, cli/src/commit_templater.rs, cli/src/template_builder.rs
If this pattern looks good, I'll look into providing hooks for the OperationTemplateLanguage as well as the Revset language in a similar fashion; this PR is something of a dry-run.  I added some `examples` to show how this would look in a custom binary.
This doesn't support custom types (yet), I'm not sure if that's something we really care to support or if there's a good way to do it. Open to suggestions
If applicable:
=> Support extensions of the commit template language

cli/src/cli_util.rs, cli/src/commands/commit.rs, cli/src/commands/diffedit.rs, cli/src/commands/move.rs, cli/src/commands/resolve.rs, cli/src/commands/split.rs, cli/src/commands/squash.rs, cli/src/commands/unsquash.rs, cli/src/merge_tools/external.rs, cli/src/merge_tools/mod.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_resolve_command.rs
Prep for #2575.
If applicable:
=> merge_tools: extract tool configuration from invocation path

cli/src/cli_util.rs, cli/src/commands/commit.rs, cli/src/commands/diffedit.rs, cli/src/commands/move.rs, cli/src/commands/resolve.rs, cli/src/commands/split.rs, cli/src/commands/squash.rs, cli/src/commands/unsquash.rs, cli/src/config/misc.toml, cli/src/merge_tools/mod.rs, lib/src/settings.rs
=> merge_tools: clean up Diff/MergeEditor interface

docs/branches.md
This is something which should've been written down long ago. This is a follow-up upon  another question from Julia Evans in Discord. 
Thank you again for asking such good questions.
=> docs: Add a short section on branch movement.

lib/src/repo.rs
This is just a clean-up to silence a lint that complains that the functions are defined in a different order than they are in the trait.
=> Reorder functions in `impl Repo for MutableRepo` to match trait

lib/src/commit_builder.rs
There's no need to have a block of code at the beginning of the function to cache the rewrite source id. We can simply check the necessary condition before calling record_rewritten_commit.
This tweak makes the function a little easier to read since we don't check the condition until we're ready to do the work.
=> Make a minor simplification to CommitBuilder::write

lib/src/backend.rs, lib/src/fsmonitor.rs, lib/src/object_id.rs, lib/src/workspace.rs
These comments are intended to make it easier for new developers to get up to speed with the project. This is just a starting point... there are other types and functions that could benefit from documentation.
=> Add documentation comments for several types

cli/src/cli_util.rs, cli/src/merge_tools/builtin.rs, lib/src/backend.rs, lib/src/content_hash.rs, lib/src/default_index/revset_engine.rs, lib/src/git_backend.rs, lib/src/id_prefix.rs, lib/src/local_backend.rs, lib/src/simple_op_store.rs, lib/src/ssh_signing.rs
There are a few additional warnings because of
https://github.com/rust-lang/rust-clippy/issues/12377, which is a
nightly-only bug that will hopefully be fixed.
=> Nightly clippy fixes

lib/src/commit_builder.rs, lib/src/repo.rs
MutableRepo and CommitBuilder both define public (now crate-public) functions which should only be called by each other. This commit adds documentation and restricts visibility of these functions to the jj_lib crate. It might be even better to move CommitBuilder to the same module as MutableRepo so that these co-dependent functions can be private to the module to avoid misuse.
=> Adjust visibility of codependent MutableRepo and CommitBuilder functions

lib/src/transaction.rs
This PR makes a few minor refactoring changes to `UnpublishedOperation`. The behavior is left unchanged.
Happy to split this into separate PRs if that's easier, but these three commits together complete the cleanup.
=> Clean up the UnpublishedOperation struct

docs/git-comparison.md
=> Docs: Add note about `jj edit` to Git comparison

lib/src/gpg_signing.rs, lib/tests/test_gpg.rs
=> gpg_signing: fix EPIPE handling in verify path

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/commit.rs, cli/src/commands/diffedit.rs, cli/src/commands/move.rs, cli/src/commands/resolve.rs, cli/src/commands/split.rs, cli/src/commands/squash.rs, cli/src/commands/unsquash.rs, cli/src/merge_tools/mod.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_commit_command.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_global_opts.rs, cli/tests/test_resolve_command.rs, cli/tests/test_unsquash_command.rs
=> cli: add --tool=<name> option to diff/merge editing commands

docs/config.md
There was a question on Discord about why using Difftastic wasn't working as the diff tool. The root cause was putting `ui.diff.tool` in the wrong toml section, when the `ui.` component actually refers to the `[ui]` section itself.
This reads kind of weirdly too because _immediately_ after this, the alternative option of using the `merge-tools` section is suggested; except it uses `[merge- tools.<name>]` which makes it immediately clear it's a section on its own.
This simply these two examples more consistent with each other, by using `[ui]` instead of `ui.` to make it clear `ui.` is a top-level section.
=> docs: make it clear `ui.` refers to a toml section

Cargo.lock
`mio 0.8.10` was yanked due to RUSTSEC-2024-0019. Do an update to unblock the CI system from this.
=> cargo: run `cargo update mio`

CHANGELOG.md
Seen while reading over the changelog in preparation for the release this week.
=> changelog: minor copy edits

cli/src/cli_util.rs, lib/src/fsmonitor.rs
`cargo doc` complains that two URLs aren't actually links:
```
warning: this URL is not a hyperlink
--> lib/src/fsmonitor.rs:66:6
|
66 | /// (https://facebook.github.io/watchman/). Requires `watchman` to already be
|      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://facebook.github.io/watchman/>`
|
= note: bare URLs are not automatically turned into clickable links
= note: `#[warn(rustdoc::bare_urls)]` on by default
warning: `jj-lib` (lib doc) generated 1 warning (run `cargo fix --lib -p jj-lib` to apply 1 suggestion)
Documenting jj-cli v0.14.0 (/Users/emesterhazy/oss/github.com/martinvonz/jj/cli)
Documenting testutils v0.14.0 (/Users/emesterhazy/oss/github.com/martinvonz/jj/lib/testutils)
warning: this URL is not a hyperlink
--> …
```
=> Make URLs in docs hyperlinks

Cargo.lock, lib/src/settings.rs
Normally this would be done by dependabot, but the `whoami` crate deprecated the default `whoami::hostname()` function in its 1.5.0 release, meaning that the dependabot PRs to fix this (such as #3208) fail CI because clippy warns about said deprecations.
This upgrades `whoami` to 1.5.0 and fixes the clippy failure at the same time. This also includes some security fixes for Illumos, as Rain has noted. Likewise, we update `insta` and `pest` too, since dependabot tried to bundle them up.
Finally, I ran a blanket `cargo update` to keep all of our transitive dependencies fresh as well.
Subsumes and replaces #3208
=> cargo: dependency updates

cli/src/commit_templater.rs
Ideally I also want to make the caching functionality extensible here, but I'm not sure of a good way to go about that yet.  I really want some sort of thread-safe `HashMap<TypeId, Box<dyn Any (of TypeId)>>` that can hold arbitrary cache objects in it but I don't know if that exists.
If applicable:
=> commit_templater: make various attributes accessible to extensions

CHANGELOG.md, cli/src/diff_util.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_diff_command.rs
Allows specifying the number of lines of context to show around diffs. The logic was already in place, just some plumbing was needed.
If applicable:
=> Add --context flag for diffs.

CHANGELOG.md, Cargo.lock, Cargo.toml, cli/tests/common/mod.rs, docs/windows.md, lib/Cargo.toml, lib/src/file_util.rs, lib/src/local_working_copy.rs, lib/tests/test_local_working_copy.rs
=> working_copy: implement symlinks on Windows with a helper function

CHANGELOG.md, cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/template_parser.rs, cli/tests/test_log_command.rs, cli/tests/test_obslog_command.rs, cli/tests/test_operations.rs, cli/tests/test_show_command.rs
This is another implementation variant to improve discoverability of template-aliases (#3175)
If accepted, supersedes the solution implemented in #3189 PR. Thanks to @yuja for the suggestion.
Several `jj` commands accept `--template <TEMPLATE>` argument. When the argument is empty, `jj` will show the list of defined symbol names.
```
λ jj log -T
error: a value is required for '--template <TEMPLATE>' but none was supplied
For more information, try '--help'.
The following symbol names are defined:
- builtin_change_id_with_hidden_and_divergent_info
- builtin_log_comfortable
- builtin_log_compact
- builtin_log_detailed
- builtin_log_oneline
- builtin_op_log_comfortable
- builtin_op_log_compact
- commit_summary_separator
- description_placeholder
- email_placeholder
- name_placeholder
```
If …
=> cli: enrich the error about required template value with a hint

CHANGELOG.md, Cargo.lock, Cargo.toml
=> release: release version 0.15.0

cli/src/commands/checkout.rs, cli/src/config/misc.toml
This way users can override `jj co` to mean `jj new` if they want to get rid of the warning.
If applicable:
=> cli: move `jj co` alias to config file, so it can be overridden

CHANGELOG.md
Commit b4c4d911 introduced this entry in the changelog, but put it in the 0.15.0 section rather than the new unreleased section.
This was probably just because the original commit was authored before the 0.15.0 release, but merged after. Such is life.
=> changelog: put entry in the right version section

cli/src/cli_util.rs
=> cli: propagate type error of "ui.default-command"

docs/working-copy.md
We have had support for `GIT_DIR/info/exclude` since 8336c48 (almost exactly two years ago).
If applicable:
=> docs: say that we support `$GIT_DIR/info/exclude`

lib/src/default_index/composite.rs, lib/src/default_index/entry.rs, lib/src/default_index/rev_walk.rs, lib/src/default_index/revset_engine.rs
=> index: migrate RevWalk constructors to builder API

CHANGELOG.md, cli/src/config-schema.json, cli/src/graphlog.rs, cli/tests/test_log_command.rs, lib/src/settings.rs
=> Add configuration options for node symbols in the graphs

cli/src/commands/squash.rs, cli/src/commands/unsquash.rs, cli/src/config/misc.toml, docs/config.md
The `amend/unamend` aliases exist for smoothen onboarding for Git/Mercurial users; I don't think we should recommend that users use them, so I think it's fine if users override them as they like. Therefore, I think they belong in the config.
If applicable:
=> cli: move `jj amend/unamend` aliases to config

lib/src/default_index/rev_walk.rs, lib/src/default_index/revset_engine.rs
=> index: allow to detach `CompositeIndex<'_>` from `RevWalk`

lib/src/default_index/revset_engine.rs, lib/src/revset.rs, lib/tests/test_revset.rs
Suggested in #3234
If applicable:
=> revset: introduce more performant way to check if a commit is in a revset

cli/src/commands/commit.rs, cli/src/commands/diffedit.rs, cli/src/commands/move.rs, cli/src/commands/resolve.rs, cli/src/commands/split.rs, cli/src/commands/squash.rs, cli/src/commands/unsquash.rs
Probably just a bad copy&paste.
If applicable:
=> cli: make `*Args::tool` fields non-public, except for `DiffFormatArgs`

cli/tests/test_chmod_command.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_git_push.rs, cli/tests/test_immutable_commits.rs, cli/tests/test_obslog_command.rs, cli/tests/test_repo_change_report.rs, cli/tests/test_resolve_command.rs, cli/tests/test_restore_command.rs, cli/tests/test_tree_level_conflicts.rs, cli/tests/test_workspaces.rs, lib/src/git_backend.rs
We haven't used custom Git commit headers for two main reasons:
1. I don't want commits created by jj to be different from any other commits. I don't want Git projects to get annoyed by such commit and reject them.
2. I've been concerned that tools don't know how to handle such headers, perhaps even resulting in crashes.
The first argument doesn't apply to commits with conflicts because such commits would never be accepted by a project whether or not they use custom commit headers. The second argument is less relevant for conflicted commits because most tools will be confused by such commits anyway.
Storing conflict information in commit headers means that we can transfer them via the regular Git wire protocol. We already include the tree objects nested inside the root-level tree, so they …
=> git_backend: write trees involved in conflict in git commit header

cli/src/commands/move.rs, cli/src/commands/squash.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_immutable_commits.rs, cli/tests/test_squash_command.rs
This is prep work for teaching `jj squash --from/--to` and for making it support multiple `--from` revisions (and maybe multiple `-r` revisions)
If applicable:
=> Make `jj squash` and `jj move` share more code

lib/src/default_index/revset_engine.rs
=> revset: consolidate early-return condition of PositionsAccumulator

lib/src/default_index/composite.rs, lib/src/default_index/entry.rs, lib/src/default_index/mod.rs, lib/src/default_index/mutable.rs, lib/src/default_index/readonly.rs, lib/src/default_index/rev_walk.rs, lib/src/default_index/revset_engine.rs, lib/src/default_index/revset_graph_iterator.rs, lib/tests/test_index.rs
=> index: turn CompositeIndex into transparent reference type

CHANGELOG.md, README.md, cli/src/commands/move.rs, cli/src/commands/squash.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_immutable_commits.rs, cli/tests/test_move_command.rs, cli/tests/test_squash_command.rs, docs/FAQ.md, docs/git-comparison.md, docs/tutorial.md
=> Teach `jj squash` `--from/--into`, deprecate `jj move`

CHANGELOG.md, cli/src/commands/log.rs, cli/src/config-schema.json, cli/src/config/misc.toml, cli/tests/cli-reference@.md.snap, cli/tests/test_log_command.rs
=> Render synthetic nodes in `jj log` by default

cli/src/commands/log.rs, cli/src/commands/obslog.rs, cli/src/commands/operation.rs, cli/src/graphlog.rs, lib/src/settings.rs
Now as default and elided node symbols come from the config, the next logical step is to use them directly bypassing GraphLog. Note that commands like `jj op log` and `jj obslog` do not use the elided node symbol at all.
If applicable:
=> graphlog: refactor out node symbols from GraphLog

lib/src/default_index/rev_walk.rs, lib/src/default_index/revset_engine.rs
=> revset: detach index from internal evaluation tree

cli/examples/custom-commit-templater/main.rs, cli/src/commit_templater.rs, lib/src/extensions_map.rs, lib/src/lib.rs
This uses OnceMap to support adding data to a shared reference, since CommitTemplateLanguage is not shared mutably
If applicable:
=> commit_templater: support custom cache extensions

lib/src/default_index/revset_engine.rs, lib/src/revset.rs
=>  revset: extend lifetime of `containing_fn()` and iterators

cli/src/config/templates.toml, cli/tests/test_commit_template.rs, cli/tests/test_operations.rs
=> templates: add missing "\n" to builtin "root" output

cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/tests/cli-reference@.md.snap
This drops the trailing period for consistency with other commands, and rephrases them a bit for consistency between each other.
If applicable:
=> next/prev: make first line of help text consistent

docs/FAQ.md
In the FAQ question "How do I integrate Jujutsu with Gerrit?", the link to the glossary entry for "co-located repos" was pointing to the entry for "change-id".
=> docs: Fix FAQ reference to glossary entry for co-located repos

cli/src/commands/log.rs, lib/src/default_index/mod.rs, lib/src/default_index/revset_engine.rs, lib/src/default_index/revset_graph_iterator.rs, lib/src/revset.rs, lib/tests/test_default_revset_graph_iterator.rs
=> revset: extend lifetime of graph iterator (for API consistency)

lib/src/default_index/composite.rs, lib/src/default_index/mod.rs, lib/src/index.rs
I am reading through the code and trying to add documentation as I go.
=> Add documentation to lib/src/index.rs and lib/src/default_index/

cli/src/commands/edit.rs, cli/tests/cli-reference@.md.snap, docs/FAQ.md
This change updates the language of `jj edit`'s help message to be more clear as to the nature of the command. It also adds a  recommendation for a more idiomatic/safer workflow. This recommendation is also elaborated in a new FAQ entry.
If applicable:
=> Update help message of `jj edit`, add FAQ on idiomatic change switching

cli/src/merge_tools/diff_working_copies.rs, cli/src/merge_tools/external.rs, cli/src/merge_tools/mod.rs
The main goal is to merge the parts of https://github.com/martinvonz/jj/pull/3292 that are likely to cause merge conflicts with other PRs, so that I can polish that PR up without worrying too much.
The intention is to have `external.rs`, `builtin-web.rs`, and `builtin.rs` as separate files. The latter could be renamed to `builtin-tui.rs` later. Another option would be to keep external diff editors and `diffedit3`-based diff editor in the same file, as they are very similar from jj's perspective for now.`
=> external diff editors: extract utility functions to a separate file in preparation for #3292

cli/src/commit_templater.rs, cli/src/generic_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, cli/src/template_parser.rs, cli/tests/test_templater.rs
=> templater: migrate global functions to table-based lookup

cli/src/cli_util.rs, cli/src/commands/bench.rs, cli/src/commands/branch.rs, cli/src/commands/log.rs, cli/src/commit_templater.rs, cli/src/revset_util.rs
=>  cli: move revset::optimize() invocation from parse() to evaluate()

cli/src/merge_tools/diff_working_copies.rs, cli/src/merge_tools/external.rs
As suggested by @yuja in https://github.com/martinvonz/jj/pull/3296#discussion_r1525829712
=> merge tools: split DiffEditWorkingCopies from DiffWorkingCopies

cli/examples/custom-working-copy/main.rs, cli/src/commands/workspace.rs, cli/tests/test_workspaces.rs, lib/src/local_working_copy.rs, lib/src/working_copy.rs
=> Fix `jj workspace update-stale` with missing operation and sparse patterns

cli/src/revset_util.rs, cli/testing/bench-revsets-git.txt, lib/src/revset.rs, lib/tests/test_revset.rs
=> revset: substitute '~(::x)' to 'x..'

cli/src/commands/abandon.rs, cli/src/commands/duplicate.rs, cli/tests/test_abandon_command.rs, cli/tests/test_duplicate_command.rs
=> cli: update empty revset handling in duplicate and abandon

CHANGELOG.md, cli/src/config-schema.json, cli/src/formatter.rs, docs/config.md
I made this change partly to scratch a very minor personal itch, but mainly as a first step to get my head around the codebase, build process, etc. TBH I was surprised how easy it was to support this (being English the hardest part was writing color vs colour!). Given how little complexity it adds to the code, I'd hope it would be considered.
That said, all new features are overhead, and I will not be offended if this is unwanted. I've enjoyed getting it working and learnt a lot, which was my main goal.
Thanks everyone for all the work on jujutsu. I'm really enjoying using it.
If applicable:
=> cli: allow colors in form '#rrggbb'

CHANGELOG.md, cli/src/config/templates.toml, cli/src/template_builder.rs, cli/tests/common/mod.rs, cli/tests/test_abandon_command.rs, cli/tests/test_builtin_aliases.rs, cli/tests/test_commit_template.rs, cli/tests/test_diff_command.rs, cli/tests/test_git_import_export.rs, cli/tests/test_git_init.rs, cli/tests/test_git_push.rs, cli/tests/test_global_opts.rs, cli/tests/test_immutable_commits.rs, cli/tests/test_init_command.rs, cli/tests/test_log_command.rs, cli/tests/test_obslog_command.rs, cli/tests/test_show_command.rs, cli/tests/test_tree_level_conflicts.rs, cli/tests/test_workspaces.rs, docs/config.md
As discussed in #2900, the milliseconds are rarely useful, and it can be confusing with different timezones because it makes harder to compare timestamps.
Closes #2900
If applicable:
=> cli: show timestamp in local timezone and without millis and offset

README.md
https://github.com/steveklabnik/jujutsu-tutorial/commit/2d62f22de1677c759afcbe10a098229293e1fe2f reorganized some things, and so this link became broken
=> Fix link to my tutorial

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/log.rs, cli/src/commands/obslog.rs, cli/src/commands/operation.rs, cli/src/config-schema.json, cli/tests/test_log_command.rs, cli/tests/test_obslog_command.rs, cli/tests/test_operations.rs, docs/config.md, lib/src/settings.rs
No-op change styling wise for now. I suspect there will be room for bikeshedding the default style after this.
Hopefully I'm not stepping on @zummenix's toes too much here after the great idea in #3260 to just use a separate template for the elided node. :sweat_smile:
Some stuff is a bit odd still, like what template to even use for the elided node? Commit template for the root it happens to be associated with? Just make it not a template and let it be a string?
Still need to update docs.
Hopefully just dropping the symbol configs I added recently is fine, especially considering there hasn't been a release with them included.
If applicable:
=> Make node symbols templatable in the graphs

cli/examples/custom-commit-templater/main.rs, cli/examples/custom-operation-templater/main.rs, cli/src/cli_util.rs, cli/src/commands/abandon.rs, cli/src/commands/branch.rs, cli/src/commands/config.rs, cli/src/commands/log.rs, cli/src/commands/next.rs, cli/src/commands/obslog.rs, cli/src/commands/operation.rs, cli/src/commands/show.rs, cli/src/commands/status.rs, cli/src/commands/workspace.rs, cli/src/commit_templater.rs, cli/src/generic_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, cli/src/templater.rs
=> templater: don't define TemplateLanguage::Context statically

cli/src/cli_util.rs, cli/tests/test_new_command.rs, cli/tests/test_rebase_command.rs
There is no point of showing the hint for non-existent revision.
Also appends ':' to the 'all' to make the hint more precise.
Closes #2451
If applicable:
=> cli: avoid bad hint "Prefix the expression with 'all'..."

CHANGELOG.md, cli/src/commands/git.rs, cli/src/git_util.rs, cli/src/ui.rs, lib/src/git.rs
Closes #3236.
Here's what this looks like pushing this branch:
```
❯ ./target/debug/jj git push -c @-
Creating branch bnjmnt4n/push-zuqnruqlvnyl for revision @-
Branch changes to push to origin:
Add branch bnjmnt4n/push-zuqnruqlvnyl to 3ffca99209d2
remote:
remote: Create a pull request for 'bnjmnt4n/push-zuqnruqlvnyl' on GitHub by visiting:
remote:      https://github.com/martinvonz/jj/pull/new/bnjmnt4n/push-zuqnruqlvnyl
remote:
```
This is implemented by printing sideband messages from the Git protocol as they arrive. This is aligned as much as possible with Git's implementation: https://github.com/git/git/blob/43072b4ca132437f21975ac6acc6b72dc22fd398/sideband.c#L178.
I didn't write any tests for this, since it would likely involve having to create a custom git backend with the ability …
=> cli: Display messages from remote after `jj git push`

CHANGELOG.md, cli/src/commands/branch.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_branch_command.rs
As requested in #1471, I added a new flag for `jj branch list` to only show branches that are conflicted.
Adds a unit test to check for listing only conflicted branches and regenerates the cli output to incorporate the new flag.
Closes #1471
reformat
If applicable:
=> cli: add option to list only conflicted branches

Cargo.lock, Cargo.toml
The first commit downgrades `gix`, and the second just runs a bulk `cargo update`.
Needed to unblock CI due to a `gix` yank; see https://github.com/martinvonz/jj/actions/runs/8403639711/job/23014353542
=> cargo: downgrade (yanked) `gix` package, update transitive deps

CHANGELOG.md, cli/src/commands/log.rs, cli/src/commands/obslog.rs, cli/src/commit_templater.rs, cli/tests/test_log_command.rs, docs/config.md, docs/templates.md, lib/src/settings.rs
=> commit_templater: encode elided node as `Option<Commit>`

cli/src/commands/git.rs, cli/tests/test_git_push.rs
=> git-push: fix bad combination of `--change` and `--branch`

cli/src/cli_util.rs, cli/src/commands/abandon.rs, cli/src/commands/branch.rs, cli/src/commands/config.rs, cli/src/commands/log.rs, cli/src/commands/next.rs, cli/src/commands/obslog.rs, cli/src/commands/operation.rs, cli/src/commands/show.rs, cli/src/commands/status.rs, cli/src/commands/workspace.rs, cli/src/commit_templater.rs, cli/src/generic_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, cli/src/templater.rs
=> templater: remove unused context parameter from `Template<C>`

cli/src/template_builder.rs, docs/templates.md
=> templater: turn logical `&&` and `||` into short-circuiting operators

cli/src/cli_util.rs, cli/tests/test_checkout.rs, cli/tests/test_new_command.rs, cli/tests/test_rebase_command.rs
=> cli: indent commits summary in single revset resolution hint

cli/src/commands/split.rs, lib/src/commit_builder.rs, lib/src/repo.rs, lib/src/rewrite.rs, lib/tests/test_mut_repo.rs, lib/tests/test_rewrite.rs
=> Preparations for moving `DescendantRebaser` state into `MutableRepo`

lib/src/repo.rs, lib/src/rewrite.rs, lib/tests/test_rewrite.rs
=> Make `DescendantRebaser` use rewrite state from `MutableRepo`

cli/src/command_error.rs, cli/src/config/colors.toml, cli/tests/test_global_opts.rs
=> cli: highlight error source headers as well

lib/src/repo.rs, lib/src/rewrite.rs
This makes the `rebase_one()` step of `DescendantRebaser` simpler and safer. References are now updated after all commits have been rebased.
If applicable:
=> Simplify `DescendantRebaser`

cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/formatter.rs, cli/tests/test_global_opts.rs
=> cli: colorize commits summary embedded in single revset resolution hint

cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commit_templater.rs, cli/src/revset_util.rs, cli/src/template_builder.rs, cli/src/template_parser.rs, cli/tests/test_commit_template.rs, cli/tests/test_log_command.rs, cli/tests/test_revset_output.rs, cli/tests/test_templater.rs, lib/src/revset.rs
=> revset, templater: simplify error structure, consolidate error handling

CHANGELOG.md, cli/src/commands/abandon.rs, cli/src/commands/duplicate.rs, cli/src/commands/new.rs, cli/tests/cli-reference@.md.snap
Commands like `new`, `duplicate`, and `abandon` can take multiple revset arguments which results in their collective union. They take the revisions directly as arguments. But for consistency with many other commands, they can also take the `-r` argument, which is a no-op. However, due to the flag being specified as a `bool`, the `-r` option can only be specified once, so e.g. `abandon -r x -r y` often fails. I normally use `-r` for consistency and muscle memory, so this bites me often.
Instead, use `clap::ArgAction::Count` in order to allow `-r` to be specified multiple times. It remains unused, of course.
With this change, all the following invocations are equivalent. Before this change, the second example would fail due to  giving `-r` multiple times.
jj abandon x y
jj abandon -r x -r y …
=> cli(duplicate, abandon): allow multiple `-r` options

CHANGELOG.md, cli/src/commands/sparse.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_sparse_command.rs
=> sparse: parse/print workspace-relative paths, extract more subcommands

cli/src/commands/rebase.rs, cli/tests/test_duplicate_command.rs, cli/tests/test_rebase_command.rs
=> rebase: do not modify commit IDs if commit is unchanged after rebase

cli/src/commit_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, cli/src/templater.rs
=> templater: evaluate template strictly if it's converted back to string property

cli/src/cli_util.rs, cli/src/commands/branch.rs, cli/src/commands/git.rs, cli/src/commands/tag.rs, lib/src/str_util.rs
This commit moves the parse_string_pattern helper function into the str_util module in jj lib and adds tests for it.
I'd like to reuse this code in a function defined by `UserSettings`, which is part of the jj lib crate and cannot use functions from the cli crate.
=> Move parse_string_pattern in cli to StringPattern::parse in lib

cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/new.rs, cli/src/commands/rebase.rs, cli/src/commands/workspace.rs, cli/tests/test_abandon_command.rs, cli/tests/test_new_command.rs, cli/tests/test_rebase_command.rs, lib/src/backend.rs, lib/src/git_backend.rs, lib/src/tree.rs
=> cli: let backend decide whether merge with root can be performed

lib/src/repo.rs, lib/src/rewrite.rs
=> rewrite: simplify `update_heads()`

cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/new.rs, cli/tests/test_abandon_command.rs, cli/tests/test_new_command.rs, cli/tests/test_rebase_command.rs, lib/src/merged_tree.rs, lib/src/repo.rs, lib/src/rewrite.rs, lib/src/tree.rs
=> clean up "merge with root" handling and related revset evaluation

cli/examples/custom-commit-templater/main.rs, cli/examples/custom-operation-templater/main.rs, cli/src/command_error.rs, cli/src/commit_templater.rs, cli/src/template_builder.rs, cli/src/template_parser.rs, cli/tests/test_branch_command.rs, cli/tests/test_revset_output.rs, lib/src/revset.rs, lib/src/str_util.rs
=> cli: render string pattern suggestion as a hint

lib/src/repo.rs, lib/src/rewrite.rs
This simplifies the code and reduces the risk of inconsistencies in the data.
Thanks to Yuya for the suggestion.
If applicable:
=> repo: merge rewrite state into single `parent_mapping` with enum

CHANGELOG.md, cli/src/commands/branch.rs, cli/tests/test_branch_command.rs
As discussed on discord  [here](https://discord.com/channels/968932220549103686/969291218347524238/1221084605617279016), the change allows `--all` to be used with `-r` when listing branches.
Also discussed was renaming `--all` to `--all-remotes`, but this change is a bit longer and will be followed in a separate PR.
If applicable:
=> cli: allow branch list to combine -r and -a

cli/src/commands/rebase.rs, cli/tests/cli-reference@.md.snap
I think the word "with" is missing and trees should be plural.
=> Fix the description of the --source arg in the jj rebase --help docs

cli/src/cli_util.rs, cli/src/commands/abandon.rs, cli/src/commands/bench.rs, cli/src/commands/branch.rs, cli/src/commands/duplicate.rs, cli/src/commands/git.rs, cli/src/commands/log.rs, cli/src/commands/run.rs, cli/src/revset_util.rs
=> cli: add convenient wrapper for user revset evaluation

CHANGELOG.md, cli/src/commands/branch.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_branch_command.rs, cli/tests/test_git_clone.rs, cli/tests/test_git_colocated.rs, cli/tests/test_git_fetch.rs, cli/tests/test_git_import_export.rs, cli/tests/test_git_init.rs, cli/tests/test_git_push.rs, cli/tests/test_init_command.rs, cli/tests/test_undo.rs
A follow up to #3406 
If applicable:
=> cli: rename --all to --all-remotes in branch list

CHANGELOG.md, cli/examples/custom-command/main.rs, cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/abandon.rs, cli/src/commands/bench.rs, cli/src/commands/branch.rs, cli/src/commands/debug.rs, cli/src/commands/describe.rs, cli/src/commands/diffedit.rs, cli/src/commands/duplicate.rs, cli/src/commands/edit.rs, cli/src/commands/git.rs, cli/src/commands/init.rs, cli/src/commands/new.rs, cli/src/commands/operation.rs, cli/src/commands/rebase.rs, cli/src/commands/resolve.rs, cli/src/commands/restore.rs, cli/src/commands/split.rs, cli/src/commands/untrack.rs, cli/src/commands/util.rs, cli/src/commands/workspace.rs, cli/src/git_util.rs, cli/src/merge_tools/mod.rs, cli/src/ui.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_global_opts.rs, cli/tests/test_resolve_command.rs
=> Add global `--quiet` flag to suppress non-primary output

CHANGELOG.md, cli/src/commands/rebase.rs, cli/src/commands/split.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_split_command.rs
If the --siblings option is used, the target commit is split into two sibling commits instead of parent and child commits. Any children of the original commit will have both siblings as their new parents.
#2274
=> Add a --siblings option to the jj split command

cli/tests/test_split_command.rs
When a commit is split, any branches pointing to it are moved to the second commit created by the split. This is true even if the --siblings option is used.
#3419
=> Update jj split tests to show what happens to branches

CHANGELOG.md, docs/revsets.md, lib/src/revset.rs, lib/tests/test_revset.rs
It includes the working copy commit of every workspace of the repo.
Implements #3384
If applicable:
=> revset: add working_copies() function

cli/src/cli_util.rs, cli/src/commands/new.rs, cli/src/commands/rebase.rs, cli/src/commands/squash.rs, cli/src/commands/workspace.rs, cli/src/revset_util.rs, cli/tests/test_new_command.rs
=> cli: refactor single/default_single revset evaluation helpers

docs/install-and-setup.md
While walking through the documentation to try out `jj`, I noticed that when installing the bash completion you get a warning every time a shell opens that `--bash` is no longer support.
I assume that not giving any parameters means it assumes `--bash`, which causes the warning. So I guess there are two solutions:
- Either address the documentation to always add `bash` (which I did here).
- Or make the default be `bash` instead of `--bash`.
As I always like explicit over implicit, I went the first route. But I can fully understand if you think the second route would be better.
Also: first commit+push via `jj` \o/
If applicable:
=> docs: "bash" is no longer optional for command-line completion

CHANGELOG.md, cli/src/commands/branch.rs, cli/tests/test_branch_command.rs
=> cli: unblock "branch list --all-remotes" with name patterns

cli/src/cli_util.rs, cli/tests/test_revset_output.rs, lib/src/revset.pest, lib/src/revset.rs
=> revset: parse "all:" prefix rule by pest

CHANGELOG.md, cli/src/commands/squash.rs
I keep typing `--to` since I'm used to `jj move` interface. It is also shorter.
Currently, if I type `--to`, clap unhelpfully suggests whether I
meant `--tool`.
If applicable:
=> cmd `squash`: alias `--to` for the `--into` flag

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/log.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_log_command.rs, docs/config.md
Implementation for #2475
If applicable:
=> Implement #2475

cli/src/cli_util.rs, cli/tests/test_immutable_commits.rs, docs/contributing.md
=> cli: add better error message when immutable_heads() cannot be resolved

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/resolve.rs, cli/src/commands/status.rs, cli/tests/test_chmod_command.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_repo_change_report.rs, cli/tests/test_resolve_command.rs, cli/tests/test_restore_command.rs
This is disabled when the global `--quiet` flag is used, as suggested by https://github.com/martinvonz/jj/pull/975#issuecomment-1371580761.
If applicable:
=> cli: print conflicted paths whenever the working copy is changed

cli/src/cli_util.rs, cli/src/commands/abandon.rs, cli/src/commands/chmod.rs, cli/src/commands/describe.rs, cli/src/commands/diffedit.rs, cli/src/commands/edit.rs, cli/src/commands/new.rs, cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/src/commands/rebase.rs, cli/src/commands/resolve.rs, cli/src/commands/restore.rs, cli/src/commands/split.rs, cli/src/commands/squash.rs, cli/src/commands/unsquash.rs, lib/src/commit.rs
This function doesn't actually need commits, it only needs their IDs. In some contexts we may only have commit IDs, so there's no need to require an iterator of Commits.
This commit also adds a `CommitIteratorExt` that makes it easy to convert an iterator of `&Commit` to an iterator of `&CommitId`.
=> Make check_rewritable take an iterator of &CommitId instead of &Commit

cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/tests/cli-reference@.md.snap
Offset is a more descriptive noun for this argument. This commit also tweaks the help message for the argument.
This isn't an option/flag, so this change should be transparent to users.
=> Rename the "AMOUNT" argument for `jj prev` and `jj next` to OFFSET

cli/src/template.pest, cli/src/template_parser.rs
=> templater: relax operator precedence rule to reduce possibility of large reparse

CHANGELOG.md, cli/src/commit_templater.rs, cli/tests/test_commit_template.rs, docs/templates.md
=> template: add method mine() to commit type

CHANGELOG.md, cli/src/cli_util.rs, cli/src/config-schema.json, cli/src/config/misc.toml, cli/tests/test_rebase_command.rs, docs/config.md
This lets users use "large" revsets in commands such as `jj rebase`, without needing the `all:` modifier.
If applicable:
=> cli: add `ui.always-allow-large-revsets` option

lib/src/matchers.rs
=> matchers: make combinators generic, add UnionMatcher

cli/src/commit_templater.rs, cli/src/ui.rs, lib/src/commit_builder.rs, lib/src/local_backend.rs, lib/src/local_working_copy.rs, lib/src/stacked_table.rs
I'm experimenting with using nightly inside the Nix build, in order to use the parallel rustc frontend and cranelift, and this really helps avoid bogus/spurious clippy warnings.
I suspect @ilyagr might have opinions on this, since he's tracked a bunch of these regressions along with me.
As an alternative to `#[allow(unknown_lints)]` &mdash; which I am not a huge fan of &mdash; I think we could also wire up a `build.rs` that detects the rustc version and emits `cargo:rustc-cfg=nightly` which would allow us to conditionalize the macro on `#[cfg(nightly)]`. But maybe this is good enough.
=> clippy: disable bogus lints for nightly clippy

CHANGELOG.md, cli/src/commands/mod.rs, cli/src/commands/parallelize.rs, cli/tests/cli-reference@.md.snap, cli/tests/runner.rs, cli/tests/test_immutable_commits.rs, cli/tests/test_parallelize_command.rs
This is an implementation of the simple version of `jj parallelize` from FR #1079.
---
Parallelize revisions by making them siblings
Running `jj parallelize 1::2` will transform the history like this:
```text
3
|             3
2            / \
|    ->     1   2
1            \ /
|             0
0
```
Each of the target revisions is rebased onto the parents of the root(s) of
the target revset (not to be confused with the repo root). The children of
the head(s) of the target revset are rebased onto the target revisions.
The target revset is the union of the REVISIONS arguments.
The target revset being parallelized must satisfy several conditions,
otherwise the command will fail.
1. The heads of the target revset must not have different children.
2. The roots of the target revset must not …
=> Implement jj parallelize

CHANGELOG.md, cli/src/commands/status.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_status_command.rs
I often work in multiple subtrees of a monorepo at once, and want to list modified files only in the current subtree, as supported by `git status .` or `hg status .`.
Example (applied to this change itself):
If applicable:
=> cli: support filtering by paths in `status`

cli/src/cli_util.rs, cli/src/commands/log.rs, lib/src/default_index/revset_engine.rs, lib/src/fileset.rs, lib/src/lib.rs, lib/src/matchers.rs, lib/src/repo_path.rs, lib/src/revset.rs, lib/tests/test_revset.rs
=> fileset: add basic AST-level object and matcher builder

CHANGELOG.md, cli/src/template.pest, cli/src/template_parser.rs, lib/src/dsl_util.rs, lib/src/lib.rs, lib/src/revset.pest, lib/src/revset.rs
=> revset: backport `\`-escape parsing from templater

cli/src/commands/prev.rs, cli/tests/cli-reference@.md.snap
This will hopefully make it clear that `jj prev` does not move by [OFFSET] relative to `@`, which is a misconception that I had and I think others may also have.
I am suggesting this change as a result of the vigorous discussion in these two issues:
- https://github.com/martinvonz/jj/issues/3426
- https://github.com/martinvonz/jj/pull/3445
We should make similar changes to `jj next` as well since it follows similar rules.
=> Improve the documentation of `jj prev`

cli/src/commands/parallelize.rs, cli/src/commands/prev.rs, cli/tests/cli-reference@.md.snap
Per discussion on another PR, we're going to avoid ALL CAPS for argument names in the documentation even though Clap uses that style for the `--help` output.
- https://github.com/martinvonz/jj/pull/3453#discussion_r1554169975
=> Make a minor formatting change to the help page for `jj parallelize`

cli/src/commands/next.rs, cli/src/commands/parallelize.rs, cli/src/commands/prev.rs, cli/tests/cli-reference@.md.snap
This is to match the recent changes made to the docs for `jj prev`.
=> Update the documentation for `jj next`

CHANGELOG.md, cli/src/config/templates.toml, cli/src/operation_templater.rs, docs/templates.md
I think that ideally there will be elided nodes for consecutive snapshots in the log, and the full oplog as it's shown now will require something like an `--all` flag.
But I looked at how `jj log` does elision and it went just a bit over my head atm :upside_down_face: 
Also I wrote those hooks to use the implicit `self` since passing everything as args, especially when there's a possibility more things will be added (like `snapshot`) is unwieldy.
When I added `builtin_log_root(change_id, commit_id)` I just did not realize I could do that 🤷
And also those are hooks, not builtins, so the builtin_ name is bad, it's more consistent for them to be one of the format_ functions - see the comment about maybe having some sort of `deprecated` templater function that'll make jj emit warnings about …
=> templater: Add operation.snapshot() boolean and default template hook

lib/src/revset.rs
The current documentation is wrong. This is a follow up for https://github.com/martinvonz/jj/pull/3461#discussion_r1555011289
=> Fix documentation for `RevsetExpression::ancestors_at` and `descendants_at`

cli/tests/test_next_prev_commands.rs
This commit adds commit graphs to most of the tests for `jj prev` to make it
clearer where `@` points before and after `prev` is run.
In addition, there were a couple of tests where the comments suggested the test
meant to have `@` pointing to a specific commit, but it actually pointed to an
empty child of that commit.
This sort of issue also exists in `test_prev_editing`. The test is supposed to
check that `--edit` is implied if you run `jj prev` on an interior commit, but
it actually caused a new empty commit to be created since `@` was sitting on a
tip commit.
=> Fix a few minor issues with the jj prev tests

CHANGELOG.md, cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/tests/test_next_prev_commands.rs
Before this commit `jj prev` fails if the current working copy commit is a merge commit. After this commit it will prompt the user to choose the ancestor they want to select.
#2126
If applicable:
=> Make `jj prev` and `jj next` work when the working copy is a merge commit

cli/src/cli_util.rs, cli/src/commands/chmod.rs, cli/src/commands/diff.rs, cli/tests/test_chmod_command.rs, cli/tests/test_diff_command.rs, lib/src/fileset.rs
=> cli: migrate "chmod" to matcher API, warn unmatched "diff" paths

CHANGELOG.md, cli/src/commands/split.rs, cli/tests/test_split_command.rs
Ilya reported this in https://github.com/martinvonz/jj/issues/3483.
The bug was introduced in https://github.com/martinvonz/jj/commit/976320726d99659936eeab0e71b42d816dffbac0.
Before this fix, `jj split` dropped any parents what weren't involved in the split when it rebased the children of the commit being split. This meant that any children which were merge commits lost their other parents unintentionally.
Fixes #3483
=> Fix a bug when the target of `jj split` has merge commit children

CHANGELOG.md, cli/src/commands/debug.rs, cli/src/config-schema.json, docs/config.md, lib/src/fsmonitor.rs
=> Document Watchman config better, new `jj debug watchman status` command

cli/tests/test_split_command.rs
This is the same as the `test_split_siblings_with_merge_child` added in https://github.com/martinvonz/jj/pull/3485, but without the siblings flag. I forgot to add the non-siblings version in that PR.
#3485
=> Add a test for splitting the parent of a merge commit without `--siblings`

cli/examples/custom-backend/main.rs, cli/examples/custom-commit-templater/main.rs, cli/examples/custom-operation-templater/main.rs, cli/examples/custom-working-copy/main.rs, cli/src/cli_util.rs, cli/src/commands/operation.rs, cli/src/commit_templater.rs, cli/src/operation_templater.rs, lib/src/repo.rs, lib/src/workspace.rs
If we ever implement some sort of ABI for dynamic extension loading, we'll need these underlying APIs to support multiple extensions, so we might as well do that first.
If applicable:
=> cli_util: support multiple extensions consistently

cli/src/commands/diffedit.rs, cli/src/commands/split.rs, cli/tests/cli-reference@.md.snap
The default is now `:builtin`.
=> docs: stop mentioning `meld` as the default diff editor

lib/src/git.rs, lib/tests/test_git.rs
=> git: on fetch, pin visible untracked remote refs

README.md, docs/conflicts.md, docs/related-work.md, lib/src/merge.rs
=> politics: delete references to Pijul

CHANGELOG.md, cli/src/commands/move.rs, cli/src/commands/squash.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_squash_command.rs
If `-d/--drop-message` is passed to `jj squash`, the descriptions of the commits being squashed are dropped and the message of the destination commit is used.
This is useful since I often find myself squashing a commit with a non-empty placeholder name such as "WIP: do something" or even "SQUASH: some change". Without this option `jj squash` always opens the diff editor and I need to navigate to the bottom of the description to remove the placeholder description. This is annoying and error-prone, and sometimes I accidentally leave something from the message that I wanted to discard.
I'm not tied to the name `--drop-message`, but I think that whatever name we use should have a short version as well. I also considered `--abandon-message/-a`, which might be better since it avoids ambiguity …
=> Add a --use-destination-message option to `jj squash`

lib/src/repo.rs, lib/src/rewrite.rs
=> Make `MutableRepo::parent_mapping` private by moving code onto the type

cli/src/config/colors.toml, cli/src/config/templates.toml, cli/tests/test_log_command.rs, cli/tests/test_obslog_command.rs, cli/tests/test_operations.rs, cli/tests/test_show_command.rs, cli/tests/test_templater.rs
Possible future defaults, for opt-in testing.
Considering we'll keep these in the configs for now I'll use the split setup I use in my own config where labeling and symbols are separate, which grants you some goodies like the working change symbol changing color on a conflicted commit.
If applicable:
=> Add template aliases with node symbol configs

lib/src/fileset.rs, lib/src/matchers.rs
=> matchers: refactor RepoPathTree (prep for glob matcher)

cli/src/commands/cat.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_cat_command.rs
=> cli: migrate "cat" to matcher API, print symlink target

CHANGELOG.md, cli/src/merge_tools/builtin.rs
This fixes several issues that made working with empty files difficult using the builtin diff editor.
1. The scm-record library used for the editor expects each file to have at least one section. For empty files this should be a file mode section. jj wasn't rendering this mode section, which prevented empty files from being selected at all.
2. The scm-record library returns `SelectedContents::Absent` if the file has no contents after the diff editor is invoked. This can be because of several reasons: 1) the file is new and empty; 2) the file was empty before and is still empty; 3) the file has been deleted. Perhaps this is a bug in scm-record and it should return `SelectedContents::Unchanged` or `SelectedContents::Present` if the file hasn't been deleted. Until this is patched upstream, …
=> Fix empty files can't be selected in builtin diff editor

cli/Cargo.toml, lib/Cargo.toml, lib/proc-macros/Cargo.toml, lib/proc-macros/LICENSE
=> Make `cargo publish` less scary to run in non-colocated repo

lib/src/git.rs
https://github.com/libgit2/libgit2/issues/3178 is now fixed.
=> lib `git.rs`: remove workaround for a now-fixed libgit2 bug

Cargo.lock, Cargo.toml
This upgrade includes a fix for
https://github.com/advisories/GHSA-rrjw-j4m2-mf34
If applicable:
=> cargo: upgrade gix from 0.61.0 to 0.62.0

cli/src/command_error.rs, cli/tests/test_global_opts.rs, lib/src/repo_path.rs
=> cli: suggest root:"<path>" if cwd-relative path is not in workspace

cli/src/commands/parallelize.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_parallelize_command.rs, lib/src/repo.rs, lib/src/rewrite.rs, lib/tests/runner.rs, lib/tests/test_rewrite_transform.rs
@bnjmnt4n: This PR includes the `transform_descendants()` function.
@emesterhazy: FYI, this is how I'm planning to rewrite `jj parallelize`.
If applicable:
=> Implement `transform_descendants()`, rewrite `jj parallelize`

cli/src/commands/new.rs, cli/src/commands/rebase.rs, cli/src/commands/workspace.rs
This replaces `.map(|c| c.id().clone())` with `.ids().cloned()`.
This is a minor cleanup to use nicer syntax for getting `CommitId`s from an iterator of commits using the `CommitIteratorExt` trait.
=> Use CommitIteratorExt to replace `.map(|c| c.id().clone())`

CHANGELOG.md, cli/src/command_error.rs, cli/tests/test_working_copy.rs, docs/config.md, lib/src/settings.rs
Motivated by the discussion in [#3439](https://github.com/martinvonz/jj/discussions/3439).
See the (detailed, as usual) commit message for `cli: allow snapshot.max-new-file-size to be a raw u64` in particular.
If applicable:
=> cli: improve, document, and bugfix `snapshot.max-new-file-size`

cli/examples/custom-working-copy/main.rs, cli/src/cli_util.rs, lib/src/local_working_copy.rs, lib/src/working_copy.rs, lib/src/workspace.rs
It's reasonable for a `WorkingCopy` implementation to want to return an error. `LocalWorkingCopyFactory` doesn't because it loads all data lazily. The VFS-based one at Google wants to be able to return an error, however.
If applicable:
=> working_copy: allow `load_working_copy()` to return error

cli/src/config/templates.toml
Maybe it's personal preference, but the hash sign looks bigger compared to the normal "o" nodes, and is slanted. This makes immutable commits stand out too much. I think "+" is closer to the diamond character used in the unicode template.
If applicable:
=> templates: use "+" instead of "#" to denote immutable node in ascii graph

cli/src/cli_util.rs, cli/src/commands/commit.rs, cli/src/commands/new.rs, cli/src/config-schema.json, cli/tests/runner.rs, cli/tests/test_advance_branches.rs, lib/src/view.rs
This is an *experimental* feature that allows users to configure branches which will automatically advance when a new commit is created with `jj commit` or `jj new`. This feature may change or be removed in the future.
This behavior can be enabled by default for all branches by setting
the following in the `config.toml`:
```
[experimental-advance-branches]
enabled-branches = ["glob:*"]
```
Specific branches can also be disabled:
```
[experimental-advance-branches]
enabled-branches = ["glob:*"]
disabled-branches = ["main", "glob:push-*"]
```
Branches that match a disabled pattern will not be advanced, even if they also
match an enabled pattern.
- When `jj commit` and `jj new` are run, they target a specific revision, the "target revision". For `jj commit` this is always `@`, and for `jj …
=> Implement FR #2338 for current branches / automatically advancing branches

docs/config.md, docs/revsets.md
While this is arguably not part of the revset language, this is a likely place for a user to look.
See https://discord.com/channels/968932220549103686/968932220549103689/1228065431281995837
If applicable:
=> revsets.md: document the `all:` prefix

cli/src/commands/rebase.rs, cli/src/commands/split.rs, cli/tests/test_split_command.rs
This is following on the rewrite for `parallelize`.
- https://github.com/martinvonz/jj/pull/3521
Since rebase_descendants from rebase.rs is no longer used outside of that file, it can be made private again.
=> Rewrite rebasing in `jj split` using `transform_descendants()`

cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/tests/cli-reference@.md.snap
I'm not sure if this was an intentional omission, but I think it would be useful to have `-e` as a short flag for `--edit`. I don't usually edit commits, but I do use `prev` and `next` with edit to navigate to a commit that I want to squash. Often this is easier than typing `--from` and `--into` plus the change IDs.
If people want to edit commits we shouldn't stand in their way.
=> Add short a `-e` alias for `--edit` to prev and next

cli/src/config/templates.toml
Basically, clean up instances of `if\(([^,]+), \1,`. Also fix one annoying comma without a following space.
=> cli: Clean up template to use `coalesce` where relevant.

cli/src/commands/split.rs, lib/src/rewrite.rs, lib/tests/test_rewrite_transform.rs
CommitIds are often manipulated by reference, so this makes the API more flexible for cases where the caller doesn't already have a Vec or array of owned CommitIds.
In many cases, `rewrite_parents()` does not even need to clone the input CommitIds.  This refactor allows the clone to be avoided if it's unnecessary.
There might be other APIs that would benefit from a similar change. In general, it seems like there are a lot of places where we're writing `&[commit_x.id().clone, commit_y.id().clone()]` and similar.
- [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/flexibility.html#functions-minimize-assumptions-about-parameters-by-using-generics-c-generic)
=> CommitRewriter::rewrite_parents(): Take `IntoIterator` instead of `&[CommitId]`

lib/src/git_backend.rs, lib/tests/test_git_backend.rs
#3537
@thoughtpolice can you try this patch? I cannot reproduce the problem reliably at my end.
If applicable:
=> tests: fix mtime flakiness in git gc tests

cli/src/commands/rebase.rs, cli/tests/common/mod.rs, cli/tests/test_rebase_command.rs
=> rebase: rewrite `rebase_revision` to use `transform_descendants`

cli/tests/test_chmod_command.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_git_push.rs, cli/tests/test_immutable_commits.rs, cli/tests/test_obslog_command.rs, cli/tests/test_repo_change_report.rs, cli/tests/test_resolve_command.rs, cli/tests/test_restore_command.rs, cli/tests/test_squash_command.rs, cli/tests/test_tree_level_conflicts.rs, cli/tests/test_workspaces.rs, lib/src/git_backend.rs
When you use e.g. `git switch` to check out a conflicted commit, you're going to end up with the `.jjconflicts-*` directories in your working copy. It's probably not obvious what those mean. This patch adds a README file to the root tree to try to explain to users what's going on and how to recover.
The authoritative information about conflicts is stored in the `jj:trees` commit header. The contents of conflicted commits is only used for preventing GC. We can therefore add contents to the tree without much consequence.
If applicable:
=> git_backend: add a README to conflicted commits

cli/src/cli_util.rs, cli/src/commands/debug.rs, docs/filesets.md, lib/src/fileset.pest, lib/src/fileset.rs, lib/src/fileset_parser.rs
=> fileset: fall back to bare pattern/string if no operator-like character found

CHANGELOG.md, cli/src/template.pest, cli/src/template_parser.rs, docs/filesets.md, docs/revsets.md, docs/templates.md, lib/src/fileset.pest, lib/src/fileset_parser.rs, lib/src/revset.pest, lib/src/revset.rs
=> fileset, revset, templater: add support for single-quoted raw string literals

docs/contributing.md
=> docs: fixed usage of old "checkout" command in contributing docs

CHANGELOG.md, cli/src/cli_util.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_global_opts.rs, cli/tests/test_immutable_commits.rs
=> cli: add global `--ignore-immutable`

cli/examples/custom-commit-templater/main.rs, cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/bench.rs, cli/src/commands/debug.rs, cli/src/commit_templater.rs, cli/src/revset_util.rs, lib/src/id_prefix.rs, lib/src/revset.rs, lib/tests/test_revset.rs
This also sets up some container types for other types of revset extensions, plumbed through CliRunner.
If applicable:
=> Support extensions of the SymbolResolver in revset evaluation

CHANGELOG.md, cli/src/commands/rebase.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_rebase_command.rs, cli/tests/test_repo_change_report.rs
=> rebase: allow `-r` to accept multiple revisions

CHANGELOG.md, cli/src/commit_templater.rs, cli/tests/test_commit_template.rs, docs/templates.md
Adds a new method to commit objects in templates to check whether they're contained within a given revset
Use cases:
- distinct coloring for commits that are local/on remote branches (`label(if(self.contained_in(::remote_branches()), "remote"), builtin_change_id_with_hidden_and_divergent_info)`)
- different node symbols for heads
- distinct styling for merge commits
- ...?
If applicable:
=> template: add contained_in method to commit object in templates

CHANGELOG.md
=> doc: fix typo of contained_in() template method

docs/tutorial.md
Added a mention of obslog after the part mentioning rewriting history with squash/edit.
If applicable:
=> docs: mention obslog in tutorial

cli/src/commands/rebase.rs, cli/tests/test_rebase_command.rs
As discussed in https://github.com/martinvonz/jj/pull/3396#discussion_r1582284065.
If applicable:
=> rebase: do not print out commit summaries of skipped commits

CHANGELOG.md, cli/src/commands/squash.rs, cli/tests/test_move_command.rs, cli/tests/test_squash_command.rs, lib/src/rewrite.rs, lib/tests/test_rewrite_transform.rs
=> Make `jj squash <path>` not rewrite unmatched commits

cli/src/commands/cat.rs, cli/src/commands/chmod.rs, cli/tests/test_chmod_command.rs, cli/tests/test_debug_command.rs, lib/src/merged_tree.rs, lib/tests/test_local_working_copy.rs, lib/tests/test_merged_tree.rs, lib/testutils/src/lib.rs
We shouldn't panic if we fail to read a tree from the backend.
If applicable:
=> merged_tree: propagate errors from `TreeEntriesIterator`

cli/src/cli_util.rs, cli/src/commands/status.rs, cli/tests/test_status_command.rs
Fixes #3108
Example output (which takes into account my own jj config and PWD so it's a little wonkier than the test, the screen is to show colors):
If applicable:
I don't know if this deserves a changelog entry ? It's a small polish thing
=> cli: status: when current change has conflicts, display instructions to resolve them

docs/tutorial.md
The built-in diff editor (https://github.com/arxanas/scm-record#scm-diff-editor) is confusing to use for new users. The tutorial should teach the basic usage of the tool and suggest another tool directly.
Related: https://github.com/arxanas/scm-record/issues/25
If applicable:
=> docs: add tutorial on how to use `:builtin` diff editor

cli/src/commands/obslog.rs, cli/tests/cli-reference@.md.snap
Please correct me if this is wrong, I have never used Mercurial.
If applicable:
=> docs: update obslog description and mention origin of name

docs/config.md
I wanted to have a reference point for the built-in revsets, but `jj config get revsets.log` doesn't turn anything up since it has special handling for the legacy config key
`ui.default-revset`. So I had to dig into the source code of jj to get it.
I think it might help others to be able to reason about revsets to have the log default shown in the settings documentation.
If applicable:
=> Add default value of revsets.log to config docs

cli/src/command_error.rs, cli/src/merge_tools/external.rs, cli/src/merge_tools/mod.rs
I've heard of one instance of a person being confused by the error.
Previously, the error was:
```
Error: Failed to load tool configuration
Caused by: To use `diffedit3` as a merge tool, the config `merge-tools.diffedit3.merge-args` must be defined (see docs for details)
```
Now, it is:
```
Error: The tool `diffedit3` cannot be used as a merge tool with `jj resolve`.
Hint: To use `diffedit3` as a merge tool, the config `merge-tools.diffedit3.merge-args` must be defined (see docs for details)
```
TODO for future PR: allow setting `merge-tools.TOOL.edit-args = false` so that attempting to use TOOL as a diff editor fails. This would be helpful, for example, for the `vscode` tool.
If applicable:
=> External merge tools: better error message for unsupported usage

CHANGELOG.md, cli/tests/test_cat_command.rs, cli/tests/test_chmod_command.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_interdiff_command.rs, cli/tests/test_obslog_command.rs, cli/tests/test_resolve_command.rs, cli/tests/test_restore_command.rs, cli/tests/test_squash_command.rs, lib/src/conflicts.rs, lib/tests/test_conflicts.rs
For example, 
```
<<<<<<< Conflict 1 of 3
+++++++ Contents of side #1
left 3.1
left 3.2
left 3.3
%%%%%%% Changes from base to side #2
-line 3
+right 3.1
>>>>>>>
```
or
```
<<<<<<< Conflict 1 of 1
%%%%%%% Changes from base to side #1
-line 3
+right 3.1
+++++++ Contents of side #2
left 3.1
left 3.2
left 3.3
>>>>>>>
```
Before this PR, I found the difference between such conflicts to be quite hard to keep track of as a user.
----------------------
Currently, there is no way to disable these, this is TODO for a future PR. Other TODOs for future PRs: make these labels configurable. After that, we could
support a `diff3/git`-like conflict format as well, in principle.
Counting conflicts helps with knowing whether you fixed all the conflicts while
you are in the editor.
While labeling "side #1", …
=> conflcts.rs: label conflict markers with conflict #, side #, whether it's a side or a diff

cli/examples/custom-commit-templater/main.rs, cli/src/cli_util.rs, cli/src/commit_templater.rs, cli/src/revset_util.rs, lib/src/default_index/revset_engine.rs, lib/src/revset.rs, lib/tests/test_revset.rs
This doesn't support _everything_ an extension might want to do with the revset language, but it covers a large portion of it and for much less internal cost than the previous proposal.
If applicable:
=> Support extending revset functionality with custom functions and programmatic filters

lib/src/repo.rs
=> repo: move new commit ids into `RewriteType` enum

CHANGELOG.md, cli/src/commands/status.rs
Fixes #3628
Verified manually
If applicable:
=> cli: status: only scan through mutable changes to find conflicts

cli/src/commands/status.rs
=> cli: status: evaluate conflicts revset as a user expression

poetry.lock, pyproject.toml
I'm hoping this will fix version switching.
https://github.com/squidfunk/mkdocs-material/issues/7160
This does prevent us from upgrading to the new 1.6 version of MkDocs, but hopefully the bug will be fixed in the foreseeable future.
Cc: @jyn514 
If applicable:
=> docs: downgrade `mkdocs-material`

cli/src/config/merge_tools.toml, docs/config.md
This is instead of https://github.com/martinvonz/jj/pull/3292, which would make `diffedit3` built into `jj`. I still have some hope of eventually making `diffedit3` into the default diff editor that is available without any configuration, which probably requires building it into `jj`, but this may not happen, and it wouldn't hurt to test `diffedit3` first. Some examples of concerns (see also the discussion in that PR):
- It is only a guess on my part that this would make a good default. The editor might not be polished enough, and most users are not used to 3-pane diff editing. I think most users would like it if they tried it, but this might be plain wrong.
- There are concerns about adding a heavyweight dependency on `jj`. While I tried to make it as lightweight as possible, it still …
=> config.md: advertise `diffedit3` as an alternative to `meld-3` diff editor

cli/src/commit_templater.rs, cli/src/operation_templater.rs, cli/src/template_builder.rs, cli/src/templater.rs, cli/tests/test_global_opts.rs, cli/tests/test_tag_command.rs, docs/templates.md
=> templater: prep for "branch list -Ttemplate" + minor cleanup

cli/src/cli_util.rs, cli/src/commands/log.rs, cli/src/commands/squash.rs, cli/src/commit_templater.rs, cli/tests/test_log_command.rs, cli/tests/test_revset_output.rs
=> cli: parse out redundant "all:" revset modifier

lib/src/default_index/store.rs, lib/src/index.rs, lib/src/transaction.rs
This is more consistent with the other method and it makes some extension operations easier, by giving access to the OpStore and other relevant context for custom index extensions.
=> index_store: add more scope to write_index()

CHANGELOG.md, cli/src/commands/split.rs, cli/src/commit_templater.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_immutable_commits.rs, cli/tests/test_split_command.rs, lib/src/commit.rs
Rationale: The user may be confused by the empty diff in the diff editor tool if they accidentally run `jj split` on a wrong (empty) commit.
If applicable:
=> Refuse to split an empty commit with `jj split`.

lib/src/lib.rs, lib/src/revset.rs, lib/src/revset_parser.rs
=> revset: extract parsing types and functions to separate module

CHANGELOG.md, cli/src/cli_util.rs, cli/src/config-schema.json, cli/src/formatter.rs, cli/src/template_builder.rs, cli/src/text_util.rs, cli/src/ui.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_commit_template.rs, cli/tests/test_global_opts.rs, cli/tests/test_log_command.rs, docs/config.md
=> cli: add `ui.color = "debug"`

cli/src/formatter.rs, cli/src/ui.rs
=> ui: refactor formatter selection

lib/src/repo.rs
=> repo: add a workaround for merging repo views with Google's index

cli/src/cli_util.rs, cli/src/commands/diffedit.rs, cli/src/commands/obslog.rs, cli/src/commands/rebase.rs, cli/src/commands/squash.rs, cli/src/commands/status.rs, cli/src/commands/unsquash.rs, cli/src/commands/workspace.rs, cli/src/commit_templater.rs, lib/src/commit.rs, lib/src/default_index/revset_engine.rs, lib/src/repo.rs, lib/src/rewrite.rs, lib/tests/test_commit_builder.rs, lib/tests/test_init.rs, lib/tests/test_mut_repo.rs
=> Propagate errors from `Commit::parents()` and `Commit::predecessors()`

cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/diff.rs, cli/src/commands/interdiff.rs, cli/src/commands/log.rs, cli/src/commands/obslog.rs, cli/src/commands/show.rs, cli/src/commands/status.rs, cli/src/description_util.rs, cli/src/diff_util.rs
=> diff_util: remove `WorkspaceCommandHelper` dependency

cli/src/commit_templater.rs
=> templater: propagate error from commit.parents() method

cli/src/merge_tools/external.rs, cli/tests/test_diff_command.rs, cli/tests/test_diffedit_command.rs, lib/src/ssh_signing.rs
=> remove repeated "exit status" from SSH signing error, use default formatting in merge tools

CHANGELOG.md, cli/src/cli_util.rs, cli/tests/test_immutable_commits.rs
Hi ! 
I am currently trying to write a fix for #3201 
If applicable:
=> creating new wc commit when @ becomes immutable

docs/design/run.md, docs/github.md, docs/glossary.md, mkdocs.yml, poetry.lock, pyproject.toml
Following up on #3676, we can use the nice features of MkDocs 1.6 and upgrade other dependencies.
If applicable:
=> docs: ask MkDocs to fail on non-existent anchors, update python dependencies

CHANGELOG.md, Cargo.lock, Cargo.toml, cli/src/commands/branch.rs, cli/tests/test_branch_command.rs
Fix #3681 
I didn't add the one line context as i thought the output of branch list would be explicit enough IMO
If applicable:
=> cli: make jj branch track show conflicts

CHANGELOG.md, cli/src/cli_util.rs, cli/tests/test_alias.rs
happened to notice this while working on https://github.com/martinvonz/jj/issues/2866
If applicable:
=> give a warning when redefining a built-in command

docs/git-compatibility.md
If applicable:
Personal note:
I started using jj last week and I'm already completely sold. (thank you!) Support for submodules and git-lfs are the only blockers for me right now. Submodules I think I can solve with a colocated repo and maybe even some hacky shell hooks to trigger git commands when jj updates something and ignores the submodules. So I tested the workflow of converting a pure jj repo to colocated - in case I need to add submodules.
=> docs: fix converting a repo into a co-located one

cli/tests/test_cat_command.rs, cli/tests/test_chmod_command.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_interdiff_command.rs, cli/tests/test_obslog_command.rs, cli/tests/test_resolve_command.rs, cli/tests/test_restore_command.rs, cli/tests/test_squash_command.rs, lib/src/conflicts.rs, lib/tests/test_conflicts.rs
This follows up on https://github.com/martinvonz/jj/pull/3459 and adds a label to the closing delimeter of each conflict, e.g.  "Conflict 1 of 3 ends".
I didn't initially put any label at the ending delimeter since the
starting delimeter is already marked with "Conflict 1 of 3". However,
I'm realizing that when I resolve conflicts, I usually go from top to
bottom and removing the first delimeter is the very first thing I do. It
is when I get to the *end* of the conflict that I wonder whether there
are any more conflicts left in the file.
=> conflicts: label closing delimeter with e.g. "Conflict 2 of 3 ends"

CHANGELOG.md, cli/src/commands/config.rs, cli/tests/test_config_command.rs
Fixes #1322. There may be more places where keys need escaping, I'm not completely sure.
If applicable:
=> `jj config list`: escape keys

CHANGELOG.md, cli/tests/test_revset_output.rs, docs/revsets.md, lib/src/default_index/revset_engine.rs, lib/src/lib.rs, lib/src/revset.rs, lib/src/union_find.rs, lib/tests/test_revset.rs
I couldn't see a way to make this work without eager evaluation so I implemented a basic UnionFind algorithm for it.
If applicable:
=> revset: implement a "reachable()" expression

.github/scripts/docs-build-deploy, .github/workflows/docs.yml, mkdocs.yml, poetry.lock, pyproject.toml
The version selector will look like:
The "main" and "latest" labels were not previously there. Later, I'll change the "main" to "nightly"; this requires changing `versions.json` directly on the`gh-pages` branch.
(this is not the most important change in the PR, but the one that needs a picture)
=> docs: stop redirecting `latest/` pages, set canonical version for SEO, show version alias in selector

CHANGELOG.md, cli/src/config/revsets.toml, docs/revsets.md
I add them as aliases, since a user may instead choose to define `immutable_heads()`, for example, as `heads(immutable())`, and the define `immutable()` instead.
If applicable:
- [NA] I have added tests to cover my changes
=> Add the revsets `mutable` and `immutable`.

cli/src/cli_util.rs, cli/src/commands/config.rs, cli/src/config.rs, cli/tests/test_config_command.rs
=> config: add workaround for config path expression parsing

CHANGELOG.md, cli/src/commands/config.rs, cli/src/config.rs, cli/tests/test_config_command.rs, docs/contributing.md
=> config: migrate "config get"/"set" to TOML-based name argument parsing

lib/src/git_backend.rs
=> git_backend: forcibly invalidate in-memory packed-refs cache on gc()

cli/src/cli_util.rs, cli/tests/test_git_colocated.rs
=> cli: don't abandon non-discardable old wc commit by import_git_head()

cli/src/config/templates.toml, cli/tests/test_alias.rs, cli/tests/test_config_command.rs
=> cli: add space around `=` in `jj config list` output

Cargo.lock
Without this, the `time` crate fails to compile on today's nightly. This problem occurred sometime between `nightly-2024-05-11` and today's nightly.
Unfortunately, a full `cargo update` seems to break Watchman
on Windows:
https://github.com/martinvonz/jj/actions/runs/9233007115/job/25404996847?pr=3755
=> `cargo update time`, required for recent nightlies

lib/src/git.rs, lib/tests/test_git.rs
In chromium/src.git, this gives an approximate ~0.83s speedup for commands if the Git index is empty, and a ~0.14s slowdown if the Git index is non-empty.
As most users using jj will likely be using jj to write to a colocated repo - and therefore avoid modifying the Git index - this should be a general speedup for most colocated checkouts.
If applicable:
=> git: Only reset Git index if non-empty

CHANGELOG.md, cli/src/commands/git.rs, cli/tests/test_git_push.rs, lib/src/git.rs, lib/tests/test_git.rs, lib/tests/test_refs.rs
Previously, `jj git push` only made sure that the branch is in the expected
location on the remote server when pushing a branch forward (as opposed to
sideways or backwards). Now, `jj git push` makes a safety check in all cases
and fails whenever `jj git fetch` would have introduced a conflict.
In other words, previously branches that moved sideways or backward were
pushed similarly to Git's `git push --force`; now they have protections
similar to `git push --force-with-lease` (though not identical to it, to match
the behavior of `jj git fetch`). Note also that because of the way `jj git
fetch` works, `jj` does not suffer from the same problems as Git's `git push
--force-with-lease` in situations when `git fetch` is run in the background.
-------------------------
There are a few TODOs …
=> `jj git push`: safety checks when pushing branch sideways, similar to `git push --force-with-lease`

lib/src/git.rs
This shares some common code to both the root and the non-root case, and provides easier access to `mut_repo` in the function - as `set_git_head_target` mutably borrows `mut_repo`.
This will be used for a cleaner implementation of #3767.
If applicable:
=> git: Refactor `reset_head` to share `set_git_head_target` call

cli/tests/test_git_push.rs
One more test I thought I'd add to #3522. Deleting a branch both in GitHub UI and locally and then pushing is the one case where I actually encounter pushing to a branch in an unexpected location to succeed.
=> test_git_push: test unexpectedly deleted branch

lib/src/git.rs
This accounts for commit message-only changes which do not change the tree ID, as well as checkouts between commits with identical tree contents.
See #3748 for previous work on avoiding resetting HEAD when the *commits* are identical.
If applicable:
=> git: Avoid resetting Git index when trees are identical

cli/src/template_builder.rs, cli/src/template_parser.rs, lib/src/dsl_util.rs, lib/src/fileset_parser.rs
=> revset: prep for migrating parser and alias substition function

docs/config.md
On Windows `code` works in the shell, but not when specified to jj, because the executable is actually named `code.cmd`! This is a feature of Windows, where certain file extensions (defined by the PATHEXT environment variable) are automatically treated as executable and can have their extensions omitted.
Presumably, jj doesn't support this feature on Windows, though perhaps it should. For now, avoid adding an explanation of PATHEXT so as to not clutter things too much, and just suggest `code.cmd` on Windows. Most readers should be able to put two and two together from there.
If applicable:
=> docs: document code.cmd editor on Windows

cli/src/commands/config.rs, cli/src/config.rs
=> cli: move `to_toml_value()` to `src/config.rs`

CHANGELOG.md, cli/src/progress.rs
Clear the rest of the cursor line (from the cursor to the end of the row) after drawing the progress bar rather than clearing the entire line before drawing. This reduces flickering on terminal emulators which are able to redraw rapidly.
It's not possible to capture this via asciinema, so I present two screen recordings instead:
**Before**
https://github.com/martinvonz/jj/assets/8965202/07725e05-e569-41b6-a09c-33554a7edc0b
**After**
https://github.com/martinvonz/jj/assets/8965202/05e954d7-b4bc-4633-b481-d6d2436bab0b
If applicable:
=> cli: clear line after writing

cli/src/command_error.rs, cli/src/commands/cat.rs, cli/src/config/colors.toml, cli/src/diff_util.rs, cli/src/merge_tools/builtin.rs, cli/tests/runner.rs, cli/tests/test_acls.rs, cli/tests/test_cat_command.rs, lib/src/backend.rs, lib/src/conflicts.rs, lib/src/lib.rs, lib/src/local_working_copy.rs, lib/src/repo.rs, lib/src/secret_backend.rs, lib/tests/test_local_working_copy.rs, lib/testutils/Cargo.toml, lib/testutils/src/lib.rs
=> backend: add error variant for access denied, handle when diffing

lib/src/local_working_copy.rs, lib/src/protos/working_copy.proto, lib/src/protos/working_copy.rs
See #2651 and a935a4f70c9c4c4a76009f9aee3bdaa1f7b9084e for more background.
This speeds up `jj log` in a large repo with watchman enabled by around 9%:
```
$ hyperfine --sort command --warmup 3 --runs 20 -L bin \
jj-before,jj-after "target/release/{bin} -R ~/chromiumjj/src log"
Benchmark 1: target/release/jj-before -R ~/chromiumjj/src log
Time (mean ± σ):     788.3 ms ±   3.4 ms    [User: 618.6 ms, System: 168.8 ms]
Range (min … max):   783.1 ms … 793.3 ms    20 runs
Benchmark 2: target/release/jj-after -R ~/chromiumjj/src log
Time (mean ± σ):     713.4 ms ±   5.2 ms    [User: 536.1 ms, System: 176.2 ms]
Range (min … max):   706.6 ms … 724.7 ms    20 runs
Relative speed comparison
1.11 ±  0.01  target/release/jj-before -R ~/chromiumjj/src log
1.00          target/release/jj-after -R …
```
=> working_copy: Add `is_file_states_sorted` to tree state proto

cli/src/commands/git.rs, cli/tests/cli-reference@.md.snap, docs/branches.md
As discussed in
https://discord.com/channels/968932220549103686/1226363798483636265/1226415448615288864
=> `jj git push` docs: document safety checks

cli/src/commands/checkout.rs, cli/src/commands/mod.rs, cli/src/commands/move.rs, cli/tests/cli-reference@.md.snap
The first commit fixes #3807
The second commit puts a deprecation message in `jj move -h`, `jj checkout -h`, and `jj merge -h`. I can get rid of this commit, but I can't think of a reason not to do it.
If applicable:
=> hide `move` form CLI reference, mark `move`, `checkout`, and `merge` as deprecated

cli/src/commands/git.rs, cli/tests/test_git_push.rs
"Move forward" instead of "Move", "Move sideways" or "Move backward"
instead of (now misleading) "Force...".
Previously discussed in https://github.com/martinvonz/jj/pull/3522#discussion_r1615391352, and based on that PR (which contains 8 of the currently 9 commits).
If applicable:
=> cli git push: clearer user-facing messages 

cli/src/commands/git.rs, cli/tests/cli-reference@.md.snap
Previously, it sounded like `jj git` might only include highly-technical commands, while IMO the most important commands in here are `jj git fetch` and `jj git push`.
If applicable:
=> `jj help git`: Include "Git remotes" in the title 

docs/revsets.md
Fixes #3822.
This is a pretty trivial change. I didn't alter other unquoted logging examples, but there's a number of them in the docs. I would not be surprised if some of them eventually cause someone else problems. It may be safest to quote all revset examples.
If applicable:
=> docs: Fix zsh-breaking logging example

docs/glossary.md
=> docs: fix another missing shell quoting around root()

CHANGELOG.md, cli/src/commands/git.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_git_push.rs
This commit adds an optional flag to be able to push commits with an empty description to a remote git repo. While the default behavior is ideal we might need to interact with a repo that has an empty commit description in it. I ran into this issue a few weeks ago pushing commits from an open source repo to an empty repo and had to go back to using git for that push as I would not want to rewrite the history which was many many years long just for that.
This flag allows users an escape hatch for pushing empty descriptions for commits and they're sure that they want that behavior.
This commit adds the flag to the `git push` command and updates the docs for the command. It also adds a new test to make sure that the flag works as intended alongside the old test which makes sure to reject an …
=> cli: add --allow-empty-description flag to push

CHANGELOG.md
I have renamed myself from @mlcui-google to @mlcui-corp, but the changelog still had the old username.
(That username is now taken by a squatter...)
If applicable:
=> changelog: Fix @mlcui-corp username

docs/filesets.md, docs/revsets.md, docs/templates.md
=> docs: sort operators in precedence order, clarify parents/children can be empty

.github/workflows/docs.yml
This is an alternative to https://github.com/martinvonz/jj/pull/3732. I think it's pretty important to show the "latest" alias. I don't know a way to not show any alias for "prerelease" in the version selector without deleting all of them. 
I'll have to then separately delete the directories for the aliases on
the gh-pages branch, so that the URL does not resolve to outdated pages.
=> docs: disable `main` and `nightly` aliases for `prerelease` version

docs/install-and-setup.md
I am not sure how to order the other entries, but "From Source" seems to me like the most important one.
=> docs install_and_setup: move Arch Linux after From Source

CHANGELOG.md, cli/src/cli_util.rs, cli/src/config.rs, cli/tests/test_config_command.rs
This addresses issue #3317, where as discussed we want to show the paths to configuration files if they contain errors, to make it easier for the user to locate them.
If applicable:
=> Show paths of config files when configurations contain errors

.github/workflows/build.yml, CHANGELOG.md, lib/Cargo.toml, lib/src/lib.rs, lib/src/repo.rs, lib/src/revset.rs, lib/src/simple_op_store.rs, lib/src/workspace.rs, lib/tests/test_index.rs
Feel free to tell me that we should wait 10 year with this :)
If applicable:
=> Make Git support optional in the lib crate

flake.lock, flake.nix
Part of a tree of patches I've been holding onto. These are mostly useful for my iterations since I think I'm the only one actively developing in a Nix devShell, but:
- Moves to using `rustc` nightly for our Nix builds, on macOS and Linux. This applies to both development shells *and* `nix build`-built packages (e.g. `nix profile install github:martinvonz/jj`.)
- As a result, this also adds a nightly-enabled build entry into the Matrix, so we can track regressions against it, too.
- It also enables the parallel `rustc` frontend for dev shell usage, which has some marginal improvements in from scratch compile times (1m30s to 1m17s or something last I remember, for incremental it's much smaller.)
- It enables zstd-compressed debug sections in mold, on Linux, which improves debug binary …
=> nix: use nightly `rustc` and improve devShell

CHANGELOG.md, cli/src/commands/fix.rs, cli/src/config-schema.json, cli/src/config/revsets.toml, cli/tests/cli-reference@.md.snap, cli/tests/test_fix_command.rs
=> Add `revsets.fix` config with new default `reachable(@, mutable())`

CHANGELOG.md, docs/revsets.md, lib/src/revset.rs, lib/tests/test_revset.rs
If applicable:
- (N/A) I have updated the config schema (cli/src/config-schema.json)
=> revset: give descendants() a generation limit arg

CHANGELOG.md, cli/src/cli_util.rs, cli/src/merge_tools/mod.rs, cli/tests/test_resolve_command.rs, cli/tests/test_status_command.rs, lib/src/conflicts.rs, lib/src/merge.rs, lib/tests/test_conflicts.rs, lib/tests/test_local_working_copy.rs
=> conflicts: materialize simplified conflicts for each file

lib/src/revset.rs
=> revset: forward RevsetExpression::parents()/children() to inner functions

CHANGELOG.md, cli/src/commands/split.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_split_command.rs
=> cli: deprecate `jj split --siblings` in favor of `jj split --parallel`

deny.toml
Without this, `cargo deny` fails after a `cargo update` (https://github.com/martinvonz/jj/actions/runs/9531433728/job/26272377250?pr=3892 failed, but once it includes this commit, #3892 no longer has a `cargo deny` failure. The windows failure is unrelated))
=> Add Unicode-3.0 to allowed licenses

docs/revsets.md
=> Add examples to revset doc

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/debug.rs, cli/src/commands/untrack.rs, cli/src/config-schema.json, cli/src/merge_tools/diff_working_copies.rs, docs/config.md, lib/src/fsmonitor.rs, lib/src/fsmonitor_watchman_extensions.rs, lib/src/lib.rs, lib/src/local_working_copy.rs, lib/src/settings.rs, lib/src/working_copy.rs, lib/tests/test_local_working_copy.rs
https://github.com/facebook/watchman/pull/1221
I have not done anything in the checklist yet, just offering this for early review.
If applicable:
=> FR: register for watchman trigger

cli/src/merge_tools/builtin.rs, cli/src/merge_tools/mod.rs, lib/src/backend.rs, lib/src/conflicts.rs, lib/src/working_copy.rs, lib/tests/test_conflicts.rs
=> conflicts: propagate error from conflict materialization

docs/community_tools.md, mkdocs.yml
Thank you all for building tools around it.
[Rendered](https://github.com/martinvonz/jj/blob/push-xrlxkrmmywwq/docs/community_tools.md)
If applicable:
=> docs: Add a page for community built tools.

CHANGELOG.md, cli/src/commands/file/list.rs, cli/src/commands/file/mod.rs, cli/src/commands/mod.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_alias.rs, cli/tests/test_sparse_command.rs, cli/tests/test_untrack_command.rs, cli/tests/test_working_copy.rs
=> cli: create `jj file list` and deprecate `jj files`

cli/src/cli_util.rs, cli/src/commands/branch.rs, cli/src/commands/git.rs, cli/src/commands/util.rs, cli/src/formatter.rs, cli/src/git_util.rs, cli/src/merge_tools/mod.rs, cli/src/ui.rs
=> ui: remove `Option<_>` wrapping from `ui.hint_()` helpers

cli/src/commands/file/mod.rs, cli/tests/cli-reference@.md.snap
Otherwise they wouldn't be sorted in help. I also reordered the match statement. Since subcommands are split to per-file modules, there's no point to keep some logical ordering.
If applicable:
=> cli: file: sort subcommands chronologically

CHANGELOG.md, cli/src/commands/branch.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_branch_command.rs
=>  cli: branch: add "move" command that can update branches by revset or name

docs/revsets.md
This makes the examples in
https://martinvonz.github.io/jj/prerelease/revsets/#operators render properly at the cost of worse (but readable) rendering on GitHub.
Also fixes a typo.
=> docs revsets.md: fixup 4d08c2c

cli/src/commands/debug/mod.rs, cli/src/commands/debug/snapshot.rs, cli/tests/test_workspaces.rs, lib/src/fsmonitor.rs
The command only takes a snapshot and avoids other overhead, so it can be used as a target for the watchman trigger that gets installed.
If applicable:
=> Add `jj debug snapshot` command and use it in trigger

cli/src/diff_util.rs, cli/src/merge_tools/builtin.rs, lib/src/conflicts.rs, lib/src/diff.rs, lib/src/files.rs
=> diff: minor cleanup of tokenizer functions

CHANGELOG.md, cli/src/diff_util.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_diff_command.rs
=> cli: Add an option to diff to output only paths.

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/src/commands/status.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_next_prev_commands.rs, lib/src/revset.rs
Tests are complete, although I need help there. 
If applicable:
=> cli: Add `prev/next --conflict`, which allows you to jump to the next conflict. 

CHANGELOG.md, cli/src/commands/branch/delete.rs, cli/src/commands/branch/forget.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_branch_command.rs, cli/tests/test_git_fetch.rs
=> cli: branch: drop support for deprecated --glob option

cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/tests/test_next_prev_commands.rs
=> next/prev: fix a few bugs in `--conflict`

CHANGELOG.md, cli/src/commands/branch/set.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_branch_command.rs
=> cli: branch: make "set" do upsert as before

CHANGELOG.md, cli/src/commands/git/remote/mod.rs, cli/src/commands/git/remote/set_url.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_git_remotes.rs, lib/src/git.rs
=> cli: git: add `remote set-url`

cli/src/cli_util.rs
It's unlikely that the immutable set is defined by short hashes, and more importantly, the cache must not be initialized by using tx.repo().
If applicable:
=> cli: stop using shared id prefix context to compute immutable heads

CHANGELOG.md, cli/src/commands/git/push.rs, cli/src/revset_util.rs, cli/tests/test_git_push.rs
=> cli: Ignore `immutable()` in `jj git push` conflict/desc/user checks

docs/design/copy-tracking.md
=> copy-info: initial design doc

lib/src/dag_walk.rs
=> Make `dag_walk::heads_ok()` terminate early in common cases

cli/src/config/colors.toml
This helps better visualize changes that contain leading and/or trailing whitespace.
It looks like this: (hmm...maybe the underlines would be confused with underscores)
If applicable:
=> diff: underline added/removed parts by default

cli/src/config/colors.toml, cli/src/diff_util.rs
=> cli: underline added/removed lines only in color-words diffs

CHANGELOG.md, cli/src/commands/file/mod.rs, cli/src/commands/file/show.rs, cli/src/commands/mod.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_acls.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_file_chmod_command.rs, cli/tests/test_file_print_command.rs, cli/tests/test_fix_command.rs, cli/tests/test_global_opts.rs, cli/tests/test_move_command.rs, cli/tests/test_new_command.rs, cli/tests/test_squash_command.rs, cli/tests/test_unsquash_command.rs
We now have two `cmd_show` in the repo. I think this one should become `cmd_file_show`, but this should be done uniformly over all the commands for consistency.
I did *not* keep `print` as an alias (I couldn't find a compelling reason to do it), but let me know if anyone feels like keeping it.
(This was discussed in https://github.com/martinvonz/jj/issues/3812. We should decide before the release next week whether or not to do this).
If applicable:
=> cli: rename `jj file print` (formerly `jj cat`) to `jj file show`

cli/examples/custom-commit-templater/main.rs, lib/src/default_index/revset_engine.rs, lib/src/revset.rs
=> revset: drop Eq/PartialEq from RevsetExpression and related types

cli/src/commands/branch/create.rs, cli/src/commands/branch/delete.rs, cli/src/commands/branch/forget.rs, cli/src/commands/branch/mod.rs, cli/src/commands/branch/move.rs, cli/src/commands/branch/rename.rs, cli/src/commands/branch/set.rs, cli/src/commands/branch/track.rs, cli/src/commands/branch/untrack.rs, lib/src/repo.rs, lib/src/view.rs, lib/tests/test_git.rs
=> clean up remainder of old branch API, with minor behavior changes in CLI output

cli/src/commands/branch/create.rs, cli/src/commands/branch/mod.rs, cli/src/commands/branch/rename.rs, cli/src/commands/branch/set.rs, cli/tests/test_branch_command.rs
=> cli: branch: on create/set/rename, assume deleted tracking local branch still exists

CHANGELOG.md, lib/src/id_prefix.rs, lib/tests/test_id_prefix.rs
Fixes https://github.com/martinvonz/jj/issues/2476.
Previously, if there was a change id match within the short prefix
lookup set, `jj` would not look for commits with that same change id
outside the short prefix set. So, it wouldn't find the conflicted
commits for a commit with a divergent (AKA conflicted) change id.
If applicable:
- n/a I have updated the documentation (README.md, docs/, demos/)
- n/a I have updated the config schema (cli/src/config-schema.json)
=> lib id_prefix: look for divergent changes outside short prefix set 

cli/src/commit_templater.rs
=> templater: use .map_or() to silence clippy without sacrificing readability

docs/contributing.md, docs/design_doc_blueprint.md, docs/design_docs.md, mkdocs.yml
This adds the basic outline of _when_ a Design Doc should be written. See the next
commit in the stack for the blueprint. 
By adding this we hopefully can prevent unnecessary churn from new and longtime contributors, 
when they want to add a major feature or rewrite a core part of Jujutsu. The text is written
as a guideline, not a rule.
=> docs: Formalize our design docs process a bit.

flake.nix
The new parallel macOS linker reduces link time for the debug `jj` binary from 3s to 0.7s on my M2 Macbook Air, which is a significant reduction for nearly no cost at all.
However, enabling it is rather strange because we have to give a full path to the /Applications directory, and I don't know of a good way to encapsulate it with existing Nix primitives inside Nixpkgs...
This change requires Sonoma and Xcode 15, but in theory I think we could target a lower macOS SDK version in order to produce binaries that are more backwards compatible, so the only real cost is that developers who also use Nix would require Sonoma.
If applicable:
=> nix: use `-ld_new` on macOS

.github/workflows/build-binaries.yml
This will cause every `push` to main to produce some binary artifacts that users can enjoy.
Fixes #2544.
=> github: publish binaries on push to main

cli/src/command_error.rs, cli/src/commands/workspace.rs, lib/src/file_util.rs
At work, a user encountered a panic upon attempting to create a dir at the line in the diff below, but it turned out to be difficult to debug because I didn't know what the path was. There already is a mechanism to add path context in the lib crate; make it available in the cli crate as well, and use the mechanism to add path context to "workspace add".
If applicable:
=> workspace add: add filename context to FS error

cli/testing/fake-editor.rs, cli/tests/test_config_command.rs
This allows us to assert the expected path in the test itself, rather than in the fake editor.
(This will be used for when we de-UNC-ify invocations of the editor, see #3986 for more details.)
If applicable:
=> fake-editor: replace expectpath with dump-path

CHANGELOG.md, cli/src/commands/commit.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_commit_command.rs
Since `jj describe --reset-author` works, I also expected `jj commit --reset-author` to work, so I think this would be a good option to add.
If applicable:
=> commit: add `--reset-author` option

CHANGELOG.md, cli/src/commands/move.rs, cli/src/commands/squash.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_squash_command.rs
If the user was thinking in terms of files, instead of commits, then we shouldn't abandon the commit, as that can have side effects such as moving branch pointers.
Fixes #3815
If applicable:
- [N/A] I have updated the config schema (cli/src/config-schema.json)
=> feat(squash): Add `--keep-emptied` flag

cli/src/commands/new.rs, cli/src/commands/rebase.rs
=> cli: remove deprecated --allow-large-revsets flag at all

CHANGELOG.md
Thanks @scott2000 for catching this.
If applicable:
=> fix(changelog): Move --keep-emptied to the correct release.

Cargo.lock
Gitoxide, which is used to parse git commits, previously failed to parse some malformed author/committer lines.
In 0.31.4, this parsing was made more lenient so as to better match Git's parsing and avoid breaking on "in-the-wild" repositories such as https://github.com/LibreOffice/core
Refs: https://github.com/Byron/gitoxide/issues/1438
Fixes: https://github.com/martinvonz/jj/issues/4008
If applicable:
=> cargo: bump gix-actor to v0.31.4

CHANGELOG.md, cli/src/config-schema.json, cli/src/diff_util.rs, cli/src/merge_tools/external.rs, cli/src/merge_tools/mod.rs, cli/testing/fake-diff-editor.rs, cli/tests/test_diff_command.rs, docs/config.md
=> diff: add a file-by-file variant for external diff tools

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/examples/custom-backend/main.rs, cli/src/commands/debug/copy_detection.rs, cli/src/commands/debug/mod.rs, cli/tests/runner.rs, cli/tests/test_copy_detection.rs, lib/Cargo.toml, lib/src/backend.rs, lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/secret_backend.rs, lib/testutils/Cargo.toml, lib/testutils/src/test_backend.rs
The usage of this is not tied into the rest of `jj` so I have not updated the changelog, but I would like to move forward with this.
If applicable:
=> copy-tracking: Initial Implementation

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/cli_util.rs, cli/tests/test_commit_command.rs, cli/tests/test_config_command.rs, cli/tests/test_describe_command.rs, cli/tests/test_move_command.rs, cli/tests/test_sparse_command.rs, cli/tests/test_split_command.rs, cli/tests/test_squash_command.rs, cli/tests/test_unsquash_command.rs
~~**This PR depends on #3995. Please only review the last commit until that PR has been merged.**~~
See https://github.com/martinvonz/jj/issues/3986 for more details. This is a no-op for non-Windows.
If applicable:
=> windows: avoid UNC paths in `run_ui_editor`

cli/src/commands/branch/delete.rs, cli/src/commands/branch/forget.rs, cli/src/commands/branch/track.rs, cli/src/commands/branch/untrack.rs, cli/tests/test_branch_command.rs, cli/tests/test_git_colocated.rs
Extracted from #3967, with no code changes.
cc @ilyagr 
If applicable:
=> cli: branch: print stats even if just one branch is updated

CHANGELOG.md, cli/src/commands/rebase.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_rebase_command.rs
This is based on @martinvonz's comment in #3830 about the inconsistency between squash --keep-emptied and rebase --skip-empty.
If applicable:
=> feat(rebase): Rename --skip-empty to --skip-emptied.

Cargo.toml
I saw this while looking over the Cargo file and remembered Martin removed usage of this a while back.
=> cargo: remove unused `ouroboros` dependency

CHANGELOG.md
=> changelog: move "rebase --skip-emptied" entry to unreleased section

CHANGELOG.md, cli/src/commands/git/clone.rs, cli/src/commands/git/init.rs, cli/tests/test_git_clone.rs, cli/tests/test_git_init.rs, docs/revsets.md, lib/src/git.rs
=> git init, git clone: add revset alias for `trunk()`

cli/src/commands/branch/move.rs, cli/tests/test_branch_command.rs
=> cli: show commit summary at end of "branch move"

CHANGELOG.md, cli/src/commands/workspace.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_workspaces.rs, lib/src/repo.rs, lib/tests/test_mut_repo.rs, lib/tests/test_view.rs
Sometimes I create a temporary workspace and then forget it when I'm done, but currently it leaves behind a working copy commit which I have to manually abandon. I think it would be more convenient if it was abandoned automatically like `jj` already does for discardable commits in other situations.
While working on this, I also noticed that if two workspaces are editing the same discardable commit, it will be abandoned whenever either workspace's working copy moves (and then it is immediately created again, but with a new change ID). I think that working copies should be treated similarly to branches and should also prevent discardable commits from being abandoned like branches do, so I included that change as well since it seems related. I don't feel strongly about this, so if this …
=> workspace: abandon discardable working copy on forget

CHANGELOG.md, cli/src/diff_util.rs, cli/tests/test_diff_command.rs, docs/config.md
default style:
with bg color:
If applicable:
=> diff: highlight word-level changes in git diffs

lib/src/revset.rs, lib/src/revset_parser.rs
=> revset: update tests to not require private field access to err.kind

cli/src/cli_util.rs, cli/tests/test_commit_template.rs
I've run into change ID prefixes being 4-5 characters instead of the usual 1-2 characters in commands like `jj duplicate` and `jj split` fairly often, and it seems like this should resolve that. I tried to avoid creating a new `IdPrefixContext` unless changes have already been made in the transaction, since several commands call `tx.format_commit_summary()` before making any changes.
If applicable:
=> cli_util: short-prefixes for commit summary in transaction

cli/tests/test_obslog_command.rs, lib/src/diff.rs, lib/src/files.rs
The last patch is copied from #763 with a few modifications.
If applicable:
=> diff: stricter uncommon lcs, match up leading/trailing ranges instead

cli/src/diff_util.rs, cli/src/merge_tools/builtin.rs, lib/src/conflicts.rs, lib/src/diff.rs, lib/src/files.rs
=> diff: add short for Diff::for_tokenizer(_, find_line_ranges)

cli/src/cli_util.rs, cli/src/commands/commit.rs, cli/src/commands/diffedit.rs, cli/src/commands/split.rs, cli/src/commands/squash.rs, cli/src/commands/unsquash.rs, cli/src/merge_tools/mod.rs, cli/testing/fake-diff-editor.rs, cli/tests/test_commit_command.rs, cli/tests/test_diffedit_command.rs, cli/tests/test_split_command.rs, cli/tests/test_squash_command.rs, cli/tests/test_unsquash_command.rs
Suggested in #4046.
If applicable:
=> cli: skip formatting instructions if not required

CHANGELOG.md, cli/src/commands/git/push.rs, docs/revsets.md, lib/src/default_index/revset_engine.rs, lib/src/revset.rs, lib/src/str_util.rs, lib/tests/test_revset.rs
See the commit message for details. This resolves an old TODO and came up during the rework of https://github.com/martinvonz/jj/pull/3951. ~~I’m not totally sure about the defaults here, but the functionality seems good to have.~~
If applicable:
=> str_util: support case‐insensitive string patterns

lib/src/fileset.rs, lib/src/fileset_parser.rs, lib/src/revset.rs, lib/src/revset_parser.rs, lib/tests/test_revset.rs
=> fileset, revset: flatten union nodes in AST to save recursion stack

cli/src/formatter.rs, cli/tests/test_commit_template.rs, cli/tests/test_diff_command.rs, cli/tests/test_global_opts.rs
I noticed this when doing the diff whitespace work.
(notice the repeated "diff removed line_number" labels) From
```
[38;5;1m<<diff removed line_number:: >><<diff removed line_number:: >><<diff removed line_number:: >><<diff removed line_number::1>>[39m<<diff:: >><<diff::    : >>[4m[38;5;1m<<diff removed token::foo>>[24m[39m
```
to
```
[38;5;1m<<diff removed line_number::   1>>[39m<<diff::     : >>[4m[38;5;1m<<diff removed token::foo>>[24m[39m
```
If applicable:
=> --color=debug: combine segments with same labels

docs/FAQ.md
The people in #323 think that we should document all patterns there are to deal with ignored files.
If applicable:
=> FAQ: Add some more variants on how to deal with temporary files

lib/src/local_working_copy.rs, lib/tests/test_gpg.rs
This PR fixes warnings ending up on stdout.
As suggested by @crackcomm on discord, use eprintln!() to print warnings
to avoid messing up template output, e.g.:
jj --no-pager --ignore-working-copy show --tool true -T change_id -r rv...
rv...ignoring git submodule at "some/submodule"
=> Fix stdout warnings

CHANGELOG.md, cli/src/commands/git/push.rs, docs/revsets.md, lib/src/revset.rs, lib/tests/test_revset.rs
Mentioned in #3528 and #3529.
If applicable:
=> revset: add tracked/untracked_remote_branches()

Cargo.lock, Cargo.toml, cli/src/diff_util.rs, cli/src/merge_tools/builtin.rs, lib/Cargo.toml, lib/src/conflicts.rs, lib/src/diff.rs, lib/src/files.rs
=> diff: leverage BStr for debug printing

CHANGELOG.md, cli/src/config-schema.json, cli/src/config/revsets.toml, docs/config.md, docs/contributing.md, docs/revsets.md
I used to use "remote_branches() & ~mine()" to exclude "their" branches from the default log, and I don't think that's uncommon requirement. Suppose untracked branches are usually read-only, it's probably okay to make them immutable by default.
If applicable:
=> cli: include untracked remote branches in default immutable_heads()

lib/tests/runner.rs, lib/tests/test_copy_tracking.rs
=> diff: add unit tests for copy tracking in the git backend

cli/src/commands/obslog.rs, cli/tests/test_obslog_command.rs, cli/tests/test_squash_command.rs
Currently, when there is a commit with two predecessors, the graph splits into two branches, and all of the predecessors on the first branch are printed before all of the predecessors on the second branch. This causes the graph to grow wider with each squashed commit, since the second branch must always get indented one level farther each time a commit is squashed. I have some commits where the graph is indented more than 10 levels due to squashing more than 10 times, making it very difficult to read.
Reversing the order and printing the second branch before the first branch prevents this unnecessary indentation and makes the graph easier to read. This does not change the order of the edges in the graph (i.e. the first predecessor is still the first edge and the second predecessor is …
=> obslog: reverse order of predecessors in topo traversal

CHANGELOG.md, cli/tests/test_revset_output.rs, docs/revsets.md, lib/src/fileset.rs, lib/src/fileset_parser.rs, lib/src/revset.rs, lib/src/revset_parser.rs, lib/tests/test_revset.rs
=> revset: parse file() argument as fileset expression

cli/src/cli_util.rs, cli/tests/test_file_chmod_command.rs, cli/tests/test_repo_change_report.rs, cli/tests/test_resolve_command.rs, cli/tests/test_restore_command.rs, cli/tests/test_squash_command.rs, cli/tests/test_status_command.rs, docs/tutorial.md
Added a missing 'to' and updated the docs as well.
If applicable:
=> cli_util: add missing word in conflict resolution instructions

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/src/cli_util.rs, cli/src/commit_templater.rs, cli/src/diff_util.rs, cli/tests/test_commit_template.rs, docs/templates.md
=> templater: add `commit.diff().<format>()` methods

.cargo/config.toml, CHANGELOG.md
Avoids a runtime dependency on vcruntime140.dll.
Closes #4005.
If applicable:
=> cargo: build with crt-static on windows

CHANGELOG.md, cli/src/diff_util.rs, docs/revsets.md, lib/src/conflicts.rs, lib/src/default_index/revset_engine.rs, lib/src/revset.rs, lib/tests/test_revset.rs
=> revset: add `diff_contains(text[, files])` to search diffs

cli/src/merge_tools/builtin.rs, lib/src/conflicts.rs, lib/src/files.rs, lib/src/tree.rs
=> files: relax requirement of merge() inputs

cli/src/commands/branch/create.rs, cli/src/commands/branch/set.rs
Now that `jj move` does not accept `-r` (since it has `--from` and `--to`), `jj set --to` seems more useful
than `jj set -r`. `create --to` is also added for ease of switching
between `branch create` and `branch move`.
If applicable:
=> cli `branch create/set`: add `--to` aliases to `-r`

cli/tests/test_diff_command.rs, docs/filesets.md, lib/src/fileset.pest, lib/src/fileset_parser.rs
=> fileset: parse glob characters as identifier

CHANGELOG.md, cli/src/commands/branch/mod.rs, cli/tests/test_branch_command.rs
Prevents a warning from being printed when renaming branches in a colocated repo, since git tracking branches were being considered as remote tracking branches.
Resolves #4111.
If applicable:
=> branch: ignore git tracking branches for rename warning

cli/src/commands/workspace.rs, cli/tests/test_workspaces.rs
The user probably would expect the path to be relative to their current directory rather than the workspace root. For instance, if the user is in a child directory and runs `jj workspace add ../../name`, then they might be surprised if we printed `"../name"` instead of `"../../name"`.
Noticed while implementing #4128, but it seems independent so I'm putting it in a separate PR.
If applicable:
=> workspace: use cwd for printing relative path

CHANGELOG.md, cli/src/commands/operation/diff.rs, cli/src/commands/operation/mod.rs, cli/src/commands/operation/show.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_operations.rs, lib/src/repo.rs
=> cli: add `jj operation show` and `jj operation diff` commands

docs/community_tools.md
I just finished building a Neovim plugin which can be used as an alternative `diff-editor` for Jujutsu.
You can find it here: https://github.com/julienvincent/hunk.nvim
I wanted to make it a bit discoverable so figured it would be appropriate to add it here.
If applicable:
=> Add hunk.nvim to list of community tools

lib/src/commit_builder.rs, lib/src/repo.rs
=> RFC: commit_builder: add public interface that writes temporary commit to store

lib/src/repo.rs
=> repo: load index eagerly to simplify error handling

CHANGELOG.md, cli/src/commands/git/push.rs, cli/tests/cli-reference@.md.snap, cli/tests/runner.rs, cli/tests/test_git_private_commits.rs, docs/config.md
Closes #3376.
If commits in `git.private-commits` are already immutable, they can be pushed. When `cmd_git_push` is checking if commits being pushed have descriptions, author information, or conflicts, we don't check immutable commits. I kept this behavior because it seemed reasonable and I couldn't find a non-tedious way to check privacy and report it in the "Won't push commit {} since {}" message.
- Should `jj git push --allow-private` be named differently?
If applicable:
=> Add private-commits setting to prevent commits from being pushed

Cargo.lock, Cargo.toml
```
error[yanked]: detected yanked crate (try `cargo update -p tokio`)
┌─ /github/workspace/Cargo.lock:316:1
│
316 │ tokio 1.39.0 registry+https://github.com/rust-lang/crates.io-index
│ ------------------------------------------------------------------ yanked version
```
If applicable:
=> cargo: bump tokio to 1.39.1 as previous version is yanked

cli/examples/custom-command/main.rs, cli/src/cli_util.rs, cli/src/commands/git/clone.rs, cli/src/commands/git/init.rs, cli/src/commands/init.rs, cli/src/commands/operation/abandon.rs, cli/src/commands/operation/diff.rs, cli/src/commands/operation/show.rs, cli/src/commands/workspace.rs, cli/tests/test_git_clone.rs, cli/tests/test_git_init.rs, cli/tests/test_init_command.rs, cli/tests/test_operations.rs, cli/tests/test_workspaces.rs
=> cli: fix/disable workspace-creation commands with `--at-op`/`--ignore-working-copy`

CHANGELOG.md, cli/tests/test_git_colocated.rs, lib/src/git.rs, lib/tests/test_git.rs
This basically reverts 20eb9ecec10f "git: don't abandon HEAD commit when it loses a branch." I think the new behavior is more consistent because the Git HEAD is equivalent to @- in jj, so it shouldn't be considered a named ref.
Note that we've made old HEAD branch not considered at 92cfffd84377 "git: on external HEAD move, do not abandon old branch."
#4108
If applicable:
=> git: on abandoning unreachable commits, don't count HEAD ref

cli/tests/test_util_command.rs, cli/tests/test_workspaces.rs, lib/src/backend.rs, lib/tests/test_local_working_copy.rs, lib/testutils/src/lib.rs
=> Remove a few references to `MergedTree::Legacy`

cli/src/commands/commit.rs, cli/src/commands/describe.rs, cli/src/commands/split.rs, cli/tests/test_commit_command.rs, cli/tests/test_describe_command.rs, cli/tests/test_split_command.rs
=> cli: preparation for commit description template

cli/src/commands/run.rs
Waleed noticed this in #4021.
If applicable:
=> run: Treat `jj run -j0 <command>` as use all available cores

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/commit.rs, cli/src/commands/describe.rs, cli/src/commands/split.rs, cli/src/config/templates.toml, cli/src/description_util.rs, cli/tests/test_commit_command.rs, cli/tests/test_describe_command.rs, cli/tests/test_split_command.rs, docs/config.md, lib/src/commit_builder.rs
=> cli: port description template to templater

CHANGELOG.md, cli/src/commands/fix.rs, cli/src/config-schema.json, cli/testing/fake-formatter.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_fix_command.rs, cli/tests/test_util_command.rs, docs/config.md
=> Add multi-tool config for `jj fix`

cli/src/commands/workspace.rs, cli/tests/test_immutable_commits.rs, cli/tests/test_workspaces.rs
Users may try to run `jj workspace add <name>` without specifying a path, which results in the workspace being created in the current directory. This can be confusing, since the workspace contents will also be snapshotted in the original workspace if it is not sparse. Adding a warning should reduce confusion in this case.
Resolves #865.
If applicable:
=> workspace: warn if destination doesn't contain path separator

CHANGELOG.md, Cargo.toml
This PR succeeds #4120. 
This changes less than it seems. Our CI builds already mostly linked a vendored copy of libgit2. This is because before this commit, it turns out that `git2` could link `libgit2` *either* statically or dynamically based on whether it could find a version of libgit2 it liked to link dynamically. Our CI builds usually did not provide such a version AFAIK.
This made the kind of binary `cargo install` would produce unpredictable and may have contributed to #2896. I was once very surprised when I did `brew upgrade libgit2` and then
`cargo build --release` suddenly switched from building dynamically linked `jj` to the vendored version.
Instead, if a packager wants to link `libgit2` dynamically, they should set an environment variable, as described inside the diff of …
=> cargo: enable vendored-libgit2, document how to properly dynamically link libgit2

cli/src/commands/fix.rs
=> cli: fix: replace obsolete todo with a new one

cli/src/cli_util.rs, cli/src/commands/diff.rs, cli/src/commands/interdiff.rs, cli/src/commands/log.rs, cli/src/commands/obslog.rs, cli/src/commands/operation/diff.rs, cli/src/commands/show.rs, cli/src/commands/status.rs, cli/src/diff_util.rs, cli/src/ui.rs, cli/tests/test_log_command.rs
=> diff: specify available terminal width by caller, subtract graph width

lib/src/repo.rs, lib/src/workspace.rs
Many places in jj_cli assume a working std::fs for interrogating repo storage types before loading the repos.  Rather than abstract all of that away and introduce complexity, let's expose a couple simple constructor methods to allow a determined client to bypass std::fs interactions in environments that don't support them (for instance, when the repo is stored in a cloud filesystem that isn't mounted locally).
If applicable:
=> Expose some internal constructors

CHANGELOG.md, cli/src/commands/status.rs, cli/tests/test_status_command.rs
Fixes #4147 
Change behaviour to consider the state of the working commit, instead of the state of the tree. In particular:
* If working commit has conflicts: Print the existing message we print today.                                                                                                                                                                                
* If working commit has no conflicts:                                                                                                             
* If any parent has conflicts, print: "Conflict in parent is resolved in working copy"                                                                 
* If no parent has any conflicts: no message  
This behaviour resolves the issue raised in #4147. …
=> polish/4147: Change conflict hint if decendants resolves conflict.  

CHANGELOG.md, Cargo.lock, Cargo.toml, cli/src/cli_util.rs, cli/tests/test_revset_output.rs, docs/revsets.md, lib/Cargo.toml, lib/src/default_index/revset_engine.rs, lib/src/lib.rs, lib/src/revset.rs, lib/src/settings.rs, lib/src/time_util.rs, lib/tests/test_revset.rs
=> add author_date and committer_date revset functions

docs/conflicts.md
Example of Git conflict in "diff3" syntax was incorrect - base should start with `|||||||` marker and split marker `=======` should have no label (see linked documentation for examples: https://git-scm.com/docs/git-merge#_how_conflicts_are_presented).
As a way to test - Visual Studio Code correctly renders updated example (while old version didn't have conflict markers rendered).
If applicable:
=> docs: Fix example with Git conflicts markers

CHANGELOG.md, cli/src/cli_util.rs, cli/src/command_error.rs, cli/src/commands/debug/index.rs, cli/src/commands/debug/reindex.rs, cli/src/commands/git/clone.rs, cli/src/commands/git/init.rs, cli/src/commands/init.rs, cli/src/commands/operation/abandon.rs, cli/src/commands/operation/log.rs, cli/src/commands/util.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_concurrent_operations.rs, cli/tests/test_global_opts.rs, cli/tests/test_operations.rs, lib/src/op_walk.rs, lib/tests/test_operations.rs
=> cli: merge op heads and snapshot working copy by "op log" by default

cli/Cargo.toml, cli/src/ui.rs
This will hopefully improve the experience of users who encounter #4182.
If applicable:
=> built-in pager: write a message to the user if pager doesn't start

CHANGELOG.md, cli/src/command_error.rs, cli/src/commands/describe.rs, cli/src/description_util.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_describe_command.rs
If multiple commits are provided, the description of each commit will be combined into a single file for editing.
Closes https://github.com/martinvonz/jj/issues/3120.
If applicable:
=> describe: allow updating the description of multiple commits

cli/src/ui.rs
Extracted from #4203
If applicable:
=> ui: include error sources in pager warning

CHANGELOG.md, cli/src/ui.rs
=> ui: do not write() to channel if builtin pager has terminated

.github/workflows/build.yml, deny.toml
An alternative to #4202. Cc: https://github.com/martinvonz/jj/pull/4200/files
**Update:** Now also includes a commit upgrading the cargo-deny-action
--------
This is needed because old keys are becoming unsupported in the next version of the `cargo-deny` action.
This was obtained as follows:
- Run `cargo deny init`
- Modify (only) the `licenses.allow` field to match what we had before.
=> cargo-deny: use the new default for `deny.toml`, add MPL-2.0, upgrade action

cli/src/description_util.rs, cli/tests/test_describe_command.rs
This follows up on #3828, cc @bnjmnt4n (and thanks again for implementing this!). It also includes an additional line of explanation.
Calling this an "experimental feature" seems appropriate to me, but let me know if this feels excessive.
I don't think we will or should try to fix all the slightly rough edges by the Wednesday release.
Ultimately, I wonder if we can make this work smoothly with some form of `rebase --interactive`, including things like squashing and reordering commits.
**Update:** I also added a third commit with a new test. This ended up leading me to add `op restore` to the existing tests as well. Let me know if this should be a separate discussion in a separate PR, or I could just drop it.
=> describe: warn user of limitations of describing multiple commits interface

CHANGELOG.md, cli/src/commands/interdiff.rs, cli/src/commands/obslog.rs, cli/src/commands/operation/diff.rs, cli/tests/test_obslog_command.rs, lib/src/rewrite.rs
=>  cli: obslog: show diffs from all predecessors, not first predecessor

cli/src/commands/operation/abandon.rs, cli/tests/test_operations.rs, lib/src/op_walk.rs
=> cli: make "op abandon" not fail with multiple op heads

lib/src/default_index/revset_engine.rs, lib/src/merged_tree.rs, lib/tests/test_local_working_copy_sparse.rs, lib/tests/test_merged_tree.rs
=> merged_tree: remove .diff() method in favor of .diff_stream()

cli/src/commands/config/set.rs, cli/src/commands/git/clone.rs, cli/src/commands/git/init.rs, cli/src/config.rs
=> config: do not parse TOML value expression by write_config_value_to_file()

cli/src/commands/operation/show.rs
The alias has no effect for positional arguments AFAIK, this makes it more consistent with `jj show`.
If applicable:
=> cli: op show: remove visible alias for positional arg

lib/src/default_index/revset_engine.rs, lib/src/local_working_copy.rs, lib/src/merge.rs, lib/src/merged_tree.rs, lib/src/rewrite.rs, lib/src/tree.rs, lib/src/tree_builder.rs, lib/tests/test_revset.rs
=> merged_tree: split function that merges trees without resolving conflicts

CHANGELOG.md, cli/examples/custom-backend/main.rs, cli/src/commands/debug/copy_detection.rs, cli/src/commands/diff.rs, cli/src/commands/fix.rs, cli/src/commands/interdiff.rs, cli/src/commands/obslog.rs, cli/src/commands/operation/diff.rs, cli/src/commands/status.rs, cli/src/commit_templater.rs, cli/src/diff_util.rs, cli/src/merge_tools/builtin.rs, cli/src/merge_tools/diff_working_copies.rs, cli/tests/test_diff_command.rs, lib/src/backend.rs, lib/src/conflicts.rs, lib/src/default_index/revset_engine.rs, lib/src/git_backend.rs, lib/src/local_backend.rs, lib/src/local_working_copy.rs, lib/src/merged_tree.rs, lib/src/rewrite.rs, lib/src/secret_backend.rs, lib/src/store.rs, lib/tests/test_commit_builder.rs, lib/tests/test_git_backend.rs, lib/tests/test_local_working_copy_sparse.rs, lib/tests/test_merged_tree.rs, lib/testutils/src/test_backend.rs
Re-approach copy tracking with a simpler signature.  Push through end-to-end copy for `diff -s`.
This is not ready to submit, but is complete enough that I would like feedback on the direction.  Remaining things to do:
=> copy-tracking: plumb copy tracking through diff detection

docs/install-and-setup.md
I feel like this is worth documenting, as it shouldn't require Homebrew.
~~TODO: I need to double-check that this works (planning to do this in a VM) and to check for typos.~~ **Update:** this works fine. Also, `--bin jj` is no longer necessary, but maybe it's helpful in emphasizing that the package is `jj-cli` rather than `jj`.
=> docs: document how to compile a statically linked binary on Mac

Cargo.lock, Cargo.toml, cli/tests/test_git_push.rs, lib/src/git.rs
This includes a bump of `libgit2` to v1.8.1.
If applicable:
=> cargo: bump `git2` to 0.19.0

CHANGELOG.md, cli/src/cli_util.rs, cli/src/git_util.rs, docs/config.md, lib/src/file_util.rs, lib/src/ssh_signing.rs
Add home directory expansion for SSH key filepaths. This allows the `signing.key` configuration value to work more universally across both Linux and macOS without requiring an absolute path.
This moved and renamed the previous `expand_git_path` function to a more generic location, and the prior use was updated accordingly.
If applicable:
=> config: expand tilde in ssh key filepaths

CHANGELOG.md, cli/src/commit_templater.rs, cli/src/diff_util.rs, cli/tests/test_diff_command.rs, lib/src/repo_path.rs
=> copy-tracking: improve --summary and add --stat

cli/src/diff_util.rs, cli/tests/test_show_command.rs
This allow `jj show --summary` and other commands to include copy tracking information.
If applicable:
=> diff_util: add copy records tracking to `DiffRenderer::show_patch`

.github/workflows/build-binaries.yml, .github/workflows/build.yml, .github/workflows/release.yml, CHANGELOG.md
We all noticed that x86 macOS binaries are no longer being provided on release, due to `macos-11` runners going the way of the Dodo a while back. Nobody alterted us to this, funny enough.
After some quick discussion, we concluded some things:
- x86 macOS runners are likely oversubscribed, and hurt CI latency badly
- `macos-12` is also deprecated; `macos-13` is the best x86 runner available
- GitHub probably isn't going to expand macOS runner capacity; `macos-13` will one day go away
- Some people are still using `jj` on Intel Macs. We didn't get alerted because they do their own builds for now, but may not always do that.
- We can just try to build on `macos-13` and make it optional for merges.
So that's what this does. It might be mergeable outright, but we can also use it to measure …
=> github: build on macos-13 for x86_64

cli/tests/test_next_prev_commands.rs
Add gratuitous `jj log` output to more points in the tests. This makes it easier to understand the intended changes by literally visualizing the commit tree we are after each movement.
This is at least useful for me since I find the new+squash workflow confusing.
Part of #3947
If applicable:
=> no-op: Add `jj log` output to more prev_next tests.

cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/src/lib.rs, cli/src/movement_util.rs, cli/tests/test_next_prev_commands.rs
The code in both cli/src/commands/{next,prev}.rs is identical except for the direction of movement. This PR pull the parts that make sense out into cli/src/movement_util.rs so it's easier to see the differences. No new behavious is introduced.
Part of #3947
If applicable:
=> next/prev: refactor movement utilities into cli/src/movement_utils.rs

cli/examples/custom-working-copy/main.rs, lib/src/local_working_copy.rs, lib/src/working_copy.rs, lib/tests/test_local_working_copy_sparse.rs
We don't currently use the `path()` method. Not all working copies even have a relevant path. For example, working copies on Google's server don't.
If applicable:
=> working_copy: delete `path()` method from trait

cli/tests/test_rebase_command.rs, lib/src/rewrite.rs
=> rebase: `move_commits`: do not remove parents of target commits which are outside the target set

cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/src/movement_util.rs
Follow up on post-submission comments in #4282.
* Derive a bunch of standard and useful traits for `movement_util::Direction`
as it is a simple type. Importantly `Copy`.
* Return `&'static str` from Direction.cmd()
* Refactor out `MovementArgs` to reduce the number of arguments
to `movement_util::move_to_commit`.
* Implement `From<&NextArgs/&PrevArgs>` for MovementArgs
Part of #3947
If applicable:
=> Follow ups on post #4282 submission comments.

cli/src/commands/diff.rs, cli/src/commands/fix.rs, cli/src/commit_templater.rs, cli/src/diff_util.rs, cli/src/merge_tools/builtin.rs, cli/src/merge_tools/diff_working_copies.rs, lib/src/backend.rs, lib/src/conflicts.rs, lib/src/copies.rs, lib/src/default_index/revset_engine.rs, lib/src/lib.rs, lib/src/local_working_copy.rs, lib/src/merged_tree.rs, lib/src/rewrite.rs, lib/tests/test_commit_builder.rs, lib/tests/test_local_working_copy_sparse.rs, lib/tests/test_merged_tree.rs
@fowles, I think this is a step on the way to making the behavior around deleted rename sources more consistent.
If applicable:
=> Add separate stream item type with copy info

CHANGELOG.md, cli/src/commands/config/set.rs, cli/tests/test_config_command.rs
=> Warn user about the working copy when configuring the author

CHANGELOG.md, cli/src/commands/next.rs, cli/src/commands/prev.rs, cli/src/config/misc.toml, cli/src/movement_util.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_next_prev_commands.rs
* We started with a tristate flag where:
- Auto - Maintain current behaviour. This edits if
the wc parent is not a head commit. Else, it will
create a new commit on the parent of the wc in
the direction of movement.
- Always - Always edit
- Never - Never edit, prefer the new+squash workflow.
However, consensus the review thread is that `auto` mode where we try to infer when to
switch to `edit mode`, should be removed. So `ui.movement.edit` is a boolean flag now.
- true: edit mode
- false: new+squash mode
* Also add a `--no-edit` flag as the explicit inverse of `--edit` and
ensure both flags take precedence over the config.
* Update tests that assumed edit mode inference, to specify `--edit` explicitly.
NOTE: #4302 was squashed into this commit, so see that closed PR for review history. …
=> Add config flag to control `prev/next` edit behaviour.

docs/install-and-setup.md
There is an ebuild available in the Gentoo GURU repository (the official project for user-contributed packages).
I added information about how to get Jujutsu via the GURU repo to the installation guide.
=> Added docs about installation under Gentoo Linux

CHANGELOG.md, cli/src/commit_templater.rs, cli/src/config-schema.json, cli/src/config/misc.toml, cli/src/diff_util.rs, cli/tests/test_diff_command.rs, docs/config.md
If applicable:
---
original (inline everything):
`max-inline-alternation = 3`:
=> diff: add option to display complex color-words diffs without inlining

cli/src/commands/diff.rs, cli/src/commit_templater.rs, cli/src/diff_util.rs, cli/tests/test_diff_command.rs, cli/tests/test_show_command.rs, lib/src/copies.rs, lib/tests/test_merged_tree.rs
=> copies: filter rename source entries by CopiesTreeDiffStream

cli/src/commands/fix.rs, cli/src/commit_templater.rs, cli/src/diff_util.rs, cli/src/merge_tools/builtin.rs, lib/src/conflicts.rs, lib/src/copies.rs, lib/src/default_index/revset_engine.rs, lib/src/local_working_copy.rs, lib/src/merged_tree.rs, lib/src/rewrite.rs, lib/tests/test_commit_builder.rs, lib/tests/test_merged_tree.rs
=> copies: determine copy/rename operation by CopiesTreeDiffStream

cli/src/movement_util.rs, cli/tests/test_next_prev_commands.rs
If movement commands don't find a target commit, they fail. However,                                                                              
it's usually not intuitive why they fail because in non-edit mode the                                                                             
start commit is the parent of the working commit.                                                                                                 
Adding the start commit change hash to the error message makes it easier                                                                          
for the user to figure out what is going on. 
Part of #3947 
If applicable:
=> Update error message when no movement target is found.

cli/src/cli_util.rs
Useful for third party tools to override, along with the version.
=> cli: add `name()` and `about()` methods to `CliRunner`

CHANGELOG.md, cli/src/commit_templater.rs, cli/src/config-schema.json, cli/src/config/misc.toml, cli/tests/test_diff_command.rs, docs/config.md
=> cli: change default inline threshold of color-words diffs

cli/src/commands/parallelize.rs, lib/src/repo.rs, lib/src/rewrite.rs, lib/tests/test_rewrite.rs
=> rewrite: deduplicate parent ids per remap iteration

Cargo.lock, Cargo.toml, lib/Cargo.toml, lib/src/store.rs
=> store: switch in-memory cache to LRU-based HashMap to cap memory usage

cli/src/cli_util.rs, lib/src/workspace.rs
Similar to other changes, this small API change allows extensions to take over repo and working copy loading entirely when the factory types cannot be obtained through the local filesystem.
If applicable:
=> workspace: turn WorkspaceLoader into a trait

lib/src/repo.rs, lib/tests/test_rewrite.rs
=> rewrite: do not resolve transitive parents repeatedly when updating refs

lib/src/repo.rs
=> rewrite: remove redundant branch/workspace lookup

lib/src/refs.rs, lib/tests/test_refs.rs
This helps resolve diverged refs by abandoning both sides:
D  ref = [D]
|\
| C       C  ref = [B - D + C]
| |       |
B |     B |     B  ref = [B - D + A]
|/      |/      |
A       A       A       A  ref = [A - D + A]
If applicable:
=> refs: retry trivial resolution after merging targets

docs/FAQ.md
(I'm fine with having this whole PR changed or even rejected. Since this is a docs change, I figured it was easiest to just make the PR rather than trying to pre-approve it in chat.)
The question "How do I avoid committing changes to files?" comes up a lot in chat, and the solution is not obvious. It will be useful to have a description with an example we can link to.
The wording of the similar question "How can I keep my scratch files in the repository?" was tweaked to emphasize the difference between keeping untracked files in the workspace and keeping changes tracked files out of published history.
If applicable:
=> docs: Add FAQ for keeping changes to tracked files

cli/src/config/colors.toml, cli/tests/test_commit_template.rs
Right now, renamed and copied files don't have any color in the output of `jj status`, and it makes them stand out. I think it's reasonable to color renamed files the same as modified files, since renaming is like modifying the path, and to color copied files the same as added files, since they're basically just added files that happen to have similar contents to an existing file.
Before this change:
After this change (I couldn't get copied to show up):
If applicable:
=> config: add color for renamed and copied in summary

docs/config.md
MkDocs did not render this list in
https://martinvonz.github.io/jj/prerelease/config/#node-style properly before.
I don't understand the reason; we have other lists that are formatted similarly to how this one was, and they look fine in MkDocs. This might be a bug in one of the MkDocs extensions for lists that we use.
**Update:** For a laugh, here's the relevant portion of the config. I made that, but I'm not touching it with a 10-ft pole unless I'm forced to :). Weird old Markdown parser is one of the major downsides of MkDocs.
https://github.com/martinvonz/jj/blob/52499e84cca5f72162d1f954ef18de73ccaed2c3/mkdocs.yml#L58-L72
=> docs: minor fix to Markdown formatting

README.md, docs/roadmap.md
=> docs: add a roadmap

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/build.rs
When building this project with [Nix/Crane](https://github.com/ipetkov/crane/discussions/693), if the `jj-cli` dependency is specified in `Cargo.toml` as a git-based crate, `cargo vendor` splits this workspace up into sub-crate directories, which causes `cargo metadata` to fail when searching for relative deps in the workspace root. 
This PR simply changes how the crate version is determined, using Cargo's built-in environment variable [`CARGO_PKG_VERSION`](https://doc.rust-lang.org/cargo/reference/environment-variables.html)
Let me know if this is problematic change! 
If applicable:
=> cli/build-rs: remove metadata command dependency in favor of env vars

CHANGELOG.md, cli/src/commands/evolog.rs, cli/src/commands/log.rs, cli/src/commands/operation/diff.rs, cli/src/commands/operation/log.rs, cli/src/commands/operation/show.rs, cli/src/config/misc.toml, cli/src/graphlog.rs, cli/tests/test_log_command.rs, lib/src/settings.rs
=> graphlog: add `enum GraphStyle` to replace string parameter

CHANGELOG.md, cli/src/commands/fix.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_fix_command.rs
This enables workflows like "insert a commit that reformats the code in one of my project directories".
`jj fix --include-unchanged-files` is an easy way to fix everything in the repo.
`jj fix --include-unchanged-files <file...>` fixes all of the `<files>` even if they are unchanged.
This is mostly orthogonal to other features, so not many tests are added.
This is a significant and simple enough improvement that I think it's appropriate to make it here instead of waiting for a `jj run`-based solution.
If applicable:
`jj diff -r tumtymnsotvq` shows the change a bit more clearly than Github.
=> cli: fix: add --include-unchanged-files flag to allow fixing as yet unchanged files

Cargo.lock
Go ahead and do a blanket update while we're here.
Advisory: <https://github.com/martinvonz/jj/security/dependabot/33>
GHSA ID: GHSA-m8rp-vv92-46c7
=> security: `cargo update` with vuln fix for `gix-path < 0.10.11`

CHANGELOG.md, cli/src/commands/workspace/add.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_workspaces.rs
This flag implements three modes:
- `copy`: copy sparse patterns from parent
- `none`: do not copy sparse patterns from parent
- `empty`: clear all paths, equal to `set --clear`
This is useful for various tooling like tools that want to run a parallel
process that queries the build system (without running into locks/blocking.)
I think continuing to copy sparse patterns makes sense as the default behavior.
If applicable:
=> cli: implement `workspace add --sparse-patterns`

cli/src/commands/workspace/add.rs
Since it's a ValueEnum, clap knows how to stringify the default value.
If applicable:
=> cli: remove unneeded Display for SparseInheritance

cli/src/cli_util.rs, cli/src/commands/commit.rs, cli/src/commands/describe.rs, cli/src/commands/git/clone.rs, cli/src/commands/git/init.rs, cli/src/commands/sparse.rs, cli/src/commands/split.rs, cli/src/commands/squash.rs, cli/src/commands/unsquash.rs, cli/src/commands/workspace/add.rs, cli/src/description_util.rs, lib/src/repo.rs, lib/src/workspace.rs, lib/tests/test_bad_locking.rs, lib/tests/test_commit_concurrent.rs, lib/tests/test_git.rs, lib/tests/test_index.rs, lib/tests/test_init.rs, lib/tests/test_load_repo.rs, lib/tests/test_operations.rs, lib/tests/test_workspace.rs, lib/testutils/src/lib.rs, lib/testutils/src/test_backend.rs
=> Remove `ReadonlyRepo::repo_path`

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/file/mod.rs, cli/src/commands/file/track.rs, cli/src/commands/file/untrack.rs, cli/src/config/misc.toml, cli/src/merge_tools/diff_working_copies.rs, cli/tests/cli-reference@.md.snap, cli/tests/runner.rs, cli/tests/test_file_track_untrack_commands.rs, cli/tests/test_working_copy.rs, docs/FAQ.md, docs/working-copy.md, lib/src/local_working_copy.rs, lib/src/working_copy.rs
=> cli: make paths to auto-track configurable, add `jj track`

CHANGELOG.md, lib/src/repo.rs, lib/tests/test_mut_repo.rs
`jj new <commit>` automatically adds the checked out commits into the view head ids. However, `jj edit` does not.
To reproduce:
```
jj git init test
cd test
jj commit -m "my commit"
jj log -r @- -T commit_id # Save the id
jj abandon -r @-
jj edit <saved_id>
jj log -r :: # Does not show the currently editing commit 
```
If applicable:
=> Update `jj edit <commit>` to add commit into view heads if not already

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/evolog.rs, cli/src/commands/log.rs, cli/src/commands/operation/diff.rs, cli/src/commands/operation/log.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_operations.rs
=> op log: add --op-diff option to embed operation diffs

cli/src/config/colors.toml, cli/tests/test_commit_template.rs
=> cli: fix missed working-copy "bookmark" colors

docs/governance/temporary-voting.md, mkdocs.yml
Hi! I'm Emily, part of the governance working group. I am not a regular contributor to jj, but part of my role at Google is to guide open source projects in Martin's and my organization, helping make sure our upstream communities are healthy and productive.
The governance working group (me, @arxanas, @thoughtpolice, and @martinvonz) wants to be able to get community approval on governance structure changes. Bootstrapping is hard - how do you get community approval for a process to get community approval? - so we're introducing this process by the normal pull request workflow.
Things to keep in mind:
* This process is temporary! It will go away, replaced by something longer-lasting and more robust.
* Until this PR is merged, the governance working group is open to suggestions to clarify …
=> Introduce temporary voting process to approve jj governance structures

CHANGELOG.md, cli/src/commands/git/push.rs, cli/tests/test_git_push.rs, lib/src/settings.rs
=> git: restore support for `git.push-branch-prefix` config but deprecate it

lib/src/id_prefix.rs, lib/tests/test_id_prefix.rs
=> id_prefix: fix crash on hidden change id disambiguation

CHANGELOG.md, cli/src/commands/git/clone.rs, cli/tests/cli-reference@.md.snap, cli/tests/test_git_clone.rs, docs/git-comparison.md, docs/git-compatibility.md, docs/github.md
This feature is discussed in https://github.com/martinvonz/jj/discussions/4447.
If applicable:
=> git: add --remote option to clone command

lib/src/default_index/revset_graph_iterator.rs, lib/src/graph.rs
=> revset: use generic GraphEdge type in default graph iterator

CHANGELOG.md, cli/src/cli_util.rs, cli/src/commands/operation/diff.rs, cli/src/commands/operation/undo.rs, cli/src/config/templates.toml, cli/tests/test_duplicate_command.rs, cli/tests/test_evolog_command.rs, cli/tests/test_git_colocated.rs, cli/tests/test_git_fetch.rs, cli/tests/test_git_import_export.rs, cli/tests/test_log_command.rs, cli/tests/test_operations.rs, cli/tests/test_show_command.rs, cli/tests/test_templater.rs
Fixes https://github.com/martinvonz/jj/issues/4431
If applicable:
=> Report what operation has been undone in `jj op undo`
