CHANGELOG.md
cli/src/commands/squash.rs
cli/tests/cli-reference@.md.snap

This eases the workflow in which a commit in the middle of the tree is repeatedly squashed into its parent.
The issue came while discussing #4468.
If applicable:

squash: accept -k as a shorthand for --keep-emptied

---

lib/src/hex_util.rs

Comparing each byte before comparing the nibbles is more efficient. A benchmark comparing the old and new implementations with various common prefix lengths shows:
```
Common hex len/old/3    time:   [7.5444 ns 7.5807 ns 7.6140 ns]
Common hex len/new/3    time:   [1.2100 ns 1.2144 ns 1.2192 ns]
Common hex len/old/6    time:   [11.849 ns 11.879 ns 11.910 ns]
Common hex len/new/6    time:   [1.9950 ns 2.0046 ns 2.0156 ns]
Common hex len/old/32   time:   [63.030 ns 63.345 ns 63.718 ns]
Common hex len/new/32   time:   [6.4647 ns 6.4800 ns 6.4999 ns]
```
[Benchmark source](https://git.sr.ht/~rfc1149/common-hex-len-benchmark/tree/main/item/benches/hex.rs) (I know that internal hex strings are not ASCII but a byte is a byte)
If applicable:

lib: optimize common prefix computation of two hex strings

---

Cargo.lock
Cargo.toml

1.20.0 was yanked: https://github.com/matklad/once_cell/issues/264

Downgrade once_cell to 1.19.0

---

cli/src/movement_util.rs
cli/tests/test_next_prev_commands.rs

See context in [this discussion](https://github.com/martinvonz/jj/pull/3935#discussion_r1649520967)
This is the last planned change for this issue, so marking this as the fixing PR.
Fixes https://github.com/martinvonz/jj/issues/3947
If applicable:

next/prev: Fetch descendants with more correctness

---

cli/src/config/misc.toml
cli/tests/test_alias.rs
docs/bookmarks.md

`jj bookmark` is a frequently used command. Its subcommands already have one letter aliases. Defining `jj b` as an alias for `jj bookmarks` make bookmarks really easy to use.
If applicable:

bookmark: add "b" alias

---

CHANGELOG.md
cli/src/commit_templater.rs
cli/tests/test_commit_template.rs
docs/templates.md

This doesn't do much for CommitId but outputs the "forward" hex for
ChangeId, which can be useful to use as Gerrit Change-Id.
If applicable:

templates: add .normal_hex() for {Commit,Change}Id

---

CHANGELOG.md
cli/src/commands/git/fetch.rs
cli/tests/test_git_fetch.rs

* First fetch from remote.
* Then check tx.{base_repo(),repo}.view().remote_bookmarks_matching(<branch>, <remote>).
This has to happen after the fetch has been done so the tx.repo() is updated.
* Warn if a branch is not found in any of the remotes used in the fetch. Note that the remotes
used in the fetch can be a subset of the remotes configured for the repo, so the language
of the warning tries to point that out.
Fixes: #4293
If applicable:

cli: Warn if specified remote branch not found for `jj git fetch`

---

CHANGELOG.md
cli/src/commands/commit.rs
cli/src/commands/describe.rs
cli/src/text_util.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_commit_command.rs
cli/tests/test_describe_command.rs

If applicable:
Fixes https://github.com/martinvonz/jj/issues/4170

cli: add `--author` argument for `commit` and `describe`

---

CHANGELOG.md
cli/src/cli_util.rs
cli/tests/test_file_chmod_command.rs
cli/tests/test_repo_change_report.rs
cli/tests/test_resolve_command.rs
cli/tests/test_restore_command.rs
cli/tests/test_squash_command.rs

* See #4239 for details.
* For now, update working copy before reporting repo changes, so that potential errors in reporting changes don't leave the repo in a stale state.
Fixes: #4239
If applicable:

cli: reorder updating and reporting for consistency.

---

cli/examples/custom-commit-templater/main.rs
cli/examples/custom-operation-templater/main.rs
cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/commands/debug/fileset.rs
cli/src/commands/debug/revset.rs
cli/src/commands/fix.rs
cli/src/commit_templater.rs
cli/src/generic_templater.rs
cli/src/operation_templater.rs
cli/src/revset_util.rs
cli/src/template_builder.rs
cli/src/template_parser.rs
cli/tests/test_commit_template.rs
cli/tests/test_revset_output.rs
cli/tests/test_templater.rs
lib/src/dsl_util.rs
lib/src/fileset.rs
lib/src/fileset_parser.rs
lib/src/revset.rs
lib/src/revset_parser.rs
lib/tests/test_revset.rs

revset, templater: add deprecation warnings

---

cli/src/commands/describe.rs
cli/tests/test_describe_command.rs

cli: get author timestamp of description template in consistent way

---

CHANGELOG.md
cli/src/commands/diffedit.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_diffedit_command.rs
cli/tests/test_global_opts.rs
lib/src/repo.rs
lib/tests/test_mut_repo.rs

This adds to `diffedit` something that `unsquash` could do and `squash` could not. This would ease the deprecation of `unsquash` (see #4479).
If applicable:

diffedit: add --restore-descendants flag

---

CHANGELOG.md
cli/src/commands/abandon.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_abandon_command.rs

This factors out the code to emit an extra message "(while preserving their content)" when descendant commits have been reparented instead of rebased, and adds the `--restore-descendants` option to `abandon`, akin to `diffedit --restore-descendants`
If applicable:

New flag: `abandon --restore-descendants`

---

CHANGELOG.md
cli/tests/test_log_command.rs
cli/tests/test_revset_output.rs
docs/revsets.md
lib/src/revset.rs
lib/tests/test_revset.rs

See discussion thread in linked issue.
With this PR, all revset functions in [BUILTIN_FUNCTION_MAP](https://github.com/martinvonz/jj/blob/8d166c764251042287626ab37a1148386cef8371/lib/src/revset.rs#L570)
that return multiple values are either named in plural or the naming is hard to misunderstand (e.g. `reachable`)
Fixes: #4122
If applicable:

Rename `conflict` revset to `conflicts`.

---

CHANGELOG.md

I missed this update in #4334.
Issue: #4122
If applicable:

Update CHANGELOG to mention deprecation of `file()` for `files()`.

---

cli/src/commands/operation/restore.rs
cli/src/commands/operation/undo.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_import_export.rs
cli/tests/test_rebase_command.rs

cli: print operation summary on "op restore"

---

CHANGELOG.md

Move this update under `Unreleased`. I started the change before the last release and after rebasing, forgot to move it. Fixing it now thanks to @yuja catching this on time.
Issue: #4122
If applicable:

changelog: `conflict()` and `file()` deprecations are yet unreleased.

---

CHANGELOG.md

@essiene I think that the new warning you implemented is a new feature, it does not fix a bug in jj, it enhances its usage. What do you think?

changelog: warning on `jj git fetch` is a new feature, not a bugfix

---

CHANGELOG.md

The space inconsistencies between the "New features" and "Fixed bugs" sections of the upcoming release even led me to introduce one more when moving an item in a previous change.
If applicable:

changelog: make indentation consistent

---

CHANGELOG.md
cli/src/commands/split.rs
cli/tests/test_split_command.rs

Allowing to put everything into the first commit closes #4533.
**Question:** should we suggest using `jj undo` if everything was put into one of the two commits in case the user didn't want to do this? Or, do we want this only if, in addition, the empty commit has an empty description, because there should be no reason to create an empty commit?
If applicable:

split: do not prevent all changes from going into the parent commit, and a fix

---

lib/src/diff.rs

diff: remove unneeded hash map lookup

---

CHANGELOG.md
cli/src/config/colors.toml
cli/tests/test_commit_template.rs
cli/tests/test_show_command.rs

Included the details in the commit message. There is probably a better way to do this, but I've been running with these changes in my local config.toml and seem to be working well with no other color conflicts. Suggestions welcome.
If applicable:

Color signature names yellow within the log

---

poetry.lock
pyproject.toml

This will hopefully make the version switcher stay on the same page as it includes
https://github.com/squidfunk/mkdocs-material/pull/7559. Unfortunately, it might break again for reasons explained there.

docs: update mkdocs-material with bugfix, `poetry update`

---

lib/src/diff.rs

diff: intersect unchanged ranges by word-range indices, not by byte ranges

---

CHANGELOG.md
cli/src/commands/log.rs
cli/src/config-schema.json
cli/src/config/revsets.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_commit_template.rs
docs/config.md
lib/src/revset.rs
lib/tests/test_revset.rs

cli: make default log revset work without working-copy commit

---

lib/src/revset.rs
lib/tests/test_revset.rs

revset: fix crash on "log --at-op 00000000 -r 'root()'"

---

lib/src/diff.rs

diff: handle "matching" regions of different lengths, minor cleanup

---

docs/bookmarks.md

bookmarks: update docs to try to clarify mapping to Git branches

---

cli/src/cli_util.rs
cli/tests/test_global_opts.rs

Typoed `user.name` as `user.nane` and got confused why my entire user didn't get recognized, warning on each command. 
If applicable:

Be more specific when warning the user about missing identity configs

---

CHANGELOG.md
lib/src/fileset.pest
lib/src/fileset_parser.rs
lib/src/revset.pest
lib/src/revset_parser.rs

Currently, `5` is a valid function name. This seems incorrect
If applicable:

Fix: Disallow revset names starting with a number.

---

cli/src/command_error.rs
cli/tests/test_global_opts.rs
cli/tests/test_revset_output.rs

Inspired by #4509.
If applicable:

cli: add pointer to the documentation in case of fileset syntax error

---

cli/src/cli_util.rs
cli/src/config.rs
lib/proc-macros/src/lib.rs
lib/src/conflicts.rs
lib/src/diff.rs
lib/src/fsmonitor.rs
lib/src/merge.rs
lib/src/merged_tree.rs
lib/src/rewrite.rs
lib/src/stacked_table.rs
lib/src/transaction.rs
lib/src/workspace.rs
lib/testutils/src/lib.rs
lib/testutils/src/test_backend.rs

This removes the need for ignoring the `too_long_first_doc_paragraph` lint.

Short first doc paragraph

---

docs/config.md
docs/working-copy.md

I forgot to add the `snapshot.auto-track` config option to `config.md` when I added it. This patch copies it from `working-copy.md` and modifies it slightly.
If applicable:

docs: mention `snapshot.auto-track` in `config.md` too

---

cli/src/commands/git/fetch.rs
cli/src/commands/git/push.rs

git: allow both `--branch`/`--bookmark` for `git fetch/push`

---

cli/src/template_parser.rs
lib/src/dsl_util.rs
lib/src/revset_parser.rs

For #3673, we will have aliases such as:
```toml
'upload(revision)' = [
["fix", "-r", "$revision"],
["lint", "-r", "$revision"],
["git", "push", "-r", "$revision"],
]
```
Template aliases:
1) Start as Config::Value
2) Are converted to String
3) Are placed in the alias map
4) Expand to a TemplateExpression type via expand_defn.
However, command aliases:
1) Start as Config::Value
2) Are converted to Vec<Vec<String>>
3) Are placed in an alias map
4) Do not expand
Thus, AliasesMap will need to support non-string values.
If applicable:

refactor: Allow the aliases map to map to arbitrary types.

---

cli/src/ui.rs
cli/tests/test_next_prev_commands.rs

ui: redirect prompt messages to stderr

---

docs/contributing.md

More details about commit messages in contributing.md

---

CHANGELOG.md
cli/src/commands/mod.rs
cli/src/commands/simplify_parents.rs
cli/tests/cli-reference@.md.snap
cli/tests/runner.rs
cli/tests/test_simplify_parents_command.rs

simplify-parents: add a command to remove redundant parents

---

cli/src/cli_util.rs
cli/src/commands/operation/abandon.rs
cli/src/commands/workspace/update_stale.rs
cli/tests/test_concurrent_operations.rs
cli/tests/test_debug_command.rs
cli/tests/test_duplicate_command.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_import_export.rs
cli/tests/test_operations.rs
cli/tests/test_rebase_command.rs
cli/tests/test_util_command.rs
cli/tests/test_workspaces.rs
lib/src/default_index/revset_engine.rs
lib/src/op_store.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/simple_op_store.rs
lib/src/transaction.rs
lib/src/workspace.rs
lib/tests/test_commit_concurrent.rs
lib/tests/test_operations.rs
lib/tests/test_revset.rs
lib/testutils/src/lib.rs

repo: pretend root commit exists in the root operation

---

CHANGELOG.md
cli/src/commit_templater.rs
cli/tests/test_immutable_commits.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
lib/src/id_prefix.rs
lib/src/revset.rs
lib/tests/test_id_prefix.rs
lib/tests/test_revset.rs

propagate `revsets.short-prefixes` evaluation error, prep for `at_operation()` revset

---

cli/src/commands/commit.rs
cli/src/commands/describe.rs
cli/src/commands/split.rs
cli/src/commands/squash.rs
cli/src/commands/unsquash.rs
cli/src/description_util.rs
lib/src/rewrite.rs

This allows 'squash' to be executed more easily from a programmatic context
If applicable:

squash: move the core functionality to jj_lib

---

CHANGELOG.md
docs/revsets.md
lib/src/repo.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: add at_operation(op, expression)

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/help.rs
cli/src/commands/mod.rs
cli/tests/cli-reference@.md.snap
cli/tests/runner.rs
cli/tests/test_global_opts.rs
cli/tests/test_help_command.rs

Accept early args after help command

---

lib/src/diff.rs

diff: minor cleanup of unchanged regions

---

CHANGELOG.md
cli/src/commands/squash.rs
cli/tests/cli-reference@.md.snap

I use these frequently and would like to type less :)
If applicable:

squash: add -f/-t shorthands for --from/--[in]to

---

CHANGELOG.md
cli/src/commands/evolog.rs
cli/src/commands/log.rs
cli/src/commands/operation/diff.rs
cli/src/commands/operation/log.rs
cli/src/diff_util.rs
cli/src/formatter.rs
cli/src/template.pest
cli/src/template_builder.rs
cli/src/template_parser.rs
cli/src/templater.rs
docs/templates.md
lib/src/dsl_util.rs
lib/src/fileset.pest
lib/src/fileset_parser.rs
lib/src/revset.pest
lib/src/revset_parser.rs

Templates can be formatted (using labels) and are usually sanitized
(unless for plain text output).
`raw_escape_sequence(content)` bypasses both.
```toml
'hyperlink(url, text)' = '''
raw_escape_sequence("\e]8;;" ++ url ++ "\e\\") ++
text ++
raw_escape_sequence("\e]8;;\e\\")
'''
```
In this example, `raw_escape_sequence` not only outputs the intended
escape codes, it also strips away any escape codes that might otherwise
be part of the `url` (from any labels attached to the `url` content).
---
If applicable:

templates: add raw_escape_sequence

---

cli/src/commands/evolog.rs
cli/src/commands/log.rs
cli/src/commands/operation/diff.rs
cli/src/commands/operation/log.rs
cli/src/diff_util.rs
cli/src/formatter.rs
cli/src/templater.rs

formatter: flush color escape sequence when raw() stream is requested

---

cli/src/cli_util.rs
cli/src/commands/operation/diff.rs
cli/src/commands/operation/restore.rs
cli/src/commands/operation/undo.rs
cli/src/config/templates.toml
cli/tests/test_duplicate_command.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_import_export.rs
cli/tests/test_operations.rs
cli/tests/test_rebase_command.rs

This is meant to be a quick fix before I update the demos in the README. The primary reason to update them is the branch -> bookmark transition, but I noticed that `jj undo`'s output is currently not very pretty.
I believe printing both the start and end times is excessive for a summary. For a long-running operation like `jj describe` with the editor open for a long time, the ending time seems more meaningful.
I was a bit torn on whether to use `format_timestamp(self.time().end())` or `self.time().end().ago()`. The latter looks better (`finished 2 seconds ago` instead of `finished 2024-10-07 15:46:03`), but is less configurable and worse for dates long ago. In the future, we could add a `format_op_summary_timestamp` function and/or a template function that uses `.ago()` for recent dates …

templates: make `op_summary` in e.g. `jj undo` output more readable and colorful

---

CHANGELOG.md
cli/src/command_error.rs
cli/src/commands/git/clone.rs
cli/src/commands/git/fetch.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_git_clone.rs
docs/git-compatibility.md
lib/src/git.rs
lib/src/git_backend.rs
lib/tests/test_git.rs

Fixes https://github.com/martinvonz/jj/issues/675
If applicable:

git_backend: Support shallow git repositories

---

CHANGELOG.md

The change was originally made during the last release cycle, so the hunks were based and rebased on top of the previous release section.
If applicable:

changelog: move shallow clone support to unreleased section

---

CHANGELOG.md
cli/src/config/templates.toml
cli/tests/test_operations.rs

For a second, I thought about replacing the word "lasted" with "after" to make it clearer, but I think it's not necessary.
If applicable:

operation templates: use end time instead of start time 

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Fixes #4001
Fixes #4635 
If applicable:

cargo: bump scm-record to 0.4.0

---

cli/src/commands/new.rs

We were discussing whether `jj backout` and `jj duplicate` should support `-d/-A/-B` just like `jj rebase` does. `jj new` already accepts `-A/-B` but it does not accept `-d`. It does support `-r`, however. It seems like `-d` is a better match for `jj new` since it creates a commit on top. So this patch adds support for that flag too. I now think `-r` sounds misleading for `jj new`, but I left it in for now.
If applicable:

cli: allow (and ignore) `-d` flag for `jj new`

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/operation/log.rs
cli/src/commands/operation/show.rs
cli/src/config/colors.toml
cli/tests/test_operations.rs

Cleans up after 7051effa8f
It's split into "operation log" and "operation summary". The color labels use "operation".
If applicable:
- [?] It doesn't seem to be mentioned in the docs

formatter & colors.toml: replace `op_log` color label

---

CHANGELOG.md
docs/revsets.md
lib/src/default_index/revset_engine.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: add `coalesce(revsets...)`

---

CHANGELOG.md
cli/src/template_builder.rs
cli/tests/test_commit_template.rs
docs/templates.md

This allows for more fine-grained control of timestamp formatting, for example:
```
[template-aliases]
'format_timestamp(timestamp)' = '''
if(timestamp.before("1 week ago"),
timestamp.format("%b %d %Y %H:%M"),
timestamp.ago()
)
'''
```
Closes #3782.
If applicable:

templates: Timestamp: add `after`, `before` methods

---

docs/git-comparison.md
docs/glossary.md

This fixes up git-comparison.md. The changes to the glossary could be moved to a separate commit/PR.

docs glossary & git-comparison: fixup & update bookmark->branch transition

---

cli/src/commands/bookmark/move.rs

Reasoning TLDR: we don't want it confused with --force. This follows up on #4612, which *did* add these shortcuts for `jj move`.
I was initially going to add them, but people imagining `jj branch move --force` (as people were worried in #4612) is a real possibility, since `jj branch move --allow-backwards` is a thing.
The reason I would like us to think about this is that I was looking at adding some shorthands like `jj b m` to git-comparison.md (just a few, where the `jj` version looks especially long), and I'm not sure whether to use `-t` or `--to` there.

RFC: `branch move`: document that we don't want to support `-f` for `--from`

---

docs/config.md

docs: update `immutable_heads()` examples to use `builtin_immutable_heads()`

---

lib/src/rewrite.rs

`[].to_vec()` looks like a manual implementation of `vec![]`.

rewrite: build `Vec` instances directly

---

cli/src/formatter.rs
cli/src/graphlog.rs
lib/src/default_index/revset_engine.rs
lib/src/diff.rs
lib/src/files.rs
lib/src/id_prefix.rs
lib/src/revset.rs
lib/src/workspace.rs

Clippy 1.83 (currently in beta) detects more cases of unneeded lifetimes, namely in trait implementation declarations. Since this lint is warn by default (this is not something we opted in specifically), we will have to fix those instances to get a clean CI.

style: remove unneeded lifetimes from trait implementations

---

cli/src/text_util.rs

text_util: add functions to truncate labeled text

---

cli/examples/custom-commit-templater/main.rs
cli/src/cli_util.rs
cli/src/commands/bookmark/list.rs
cli/src/commands/debug/revset.rs
cli/src/commands/duplicate.rs
cli/src/commands/fix.rs
cli/src/commands/git/push.rs
cli/src/commands/log.rs
cli/src/commands/new.rs
cli/src/commands/operation/diff.rs
cli/src/commands/rebase.rs
cli/src/commands/simplify_parents.rs
cli/src/commands/status.rs
cli/src/revset_util.rs
lib/src/annotate.rs
lib/src/default_index/revset_engine.rs
lib/src/git.rs
lib/src/graph.rs
lib/src/id_prefix.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/rewrite.rs
lib/tests/test_default_revset_graph_iterator.rs
lib/tests/test_revset.rs

Revset: allow returning errors during iteration

---

flake.lock

This is needed to build with the latest nixpkgs, as it contains the https://github.com/oxalica/rust-overlay/commit/c48c2d76b68dd9ede0815fec53479375c61af857 fix.

nix: update rust-overlay dependency

---

Cargo.toml
docs/install-and-setup.md

docs: mention that that Rust 1.76 is required to install from source

---

CHANGELOG.md
cli/src/formatter.rs
cli/src/template.pest
cli/src/template_builder.rs
cli/src/template_parser.rs
cli/src/text_util.rs
docs/templates.md
lib/src/dsl_util.rs
lib/src/revset_parser.rs

templater: add pad/truncate functions

---

docs/config.md

docs: fix typos in `immutable_heads()` example

---

lib/src/rewrite.rs
lib/tests/test_merge_trees.rs

rewrite: don't resolve intermediate parent tree when rebasing

---

cli/src/commands/bookmark/forget.rs
cli/src/commands/bookmark/mod.rs
cli/src/commands/bookmark/move.rs
cli/src/commands/git/push.rs
cli/src/commit_templater.rs
lib/src/default_index/revset_engine.rs
lib/src/default_index/revset_graph_iterator.rs
lib/src/graph.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: add error propagation path to other Revset methods

---

cli/src/commands/bookmark/list.rs
cli/tests/cli-reference@.md.snap

The current links result in a 404. Replace them with the actual location of the respective pages.
If applicable:

bookmark: fix doc links

---

cli/src/commands/bookmark/list.rs
cli/src/commands/bookmark/mod.rs
cli/tests/cli-reference@.md.snap

Found a few more broken links beyond those in 9b5cdf2.
If applicable:
- n/a I have updated `CHANGELOG.md`
- n/a I have updated the documentation (README.md, docs/, demos/)
- n/a I have updated the config schema (cli/src/config-schema.json)
- n/a I have added tests to cover my changes

bookmark: fix broken docs URLs that lead to 404 errors

---

CHANGELOG.md
cli/src/commands/bookmark/list.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_bookmark_command.rs

I find myself quite often willing to run `jj bookmark list --remote upstream` to check the bookmarks belonging to one particular remote.
If applicable:

bookmark list: add --remote to filter remote bookmarks listing

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/config/misc.toml
cli/src/diff_util.rs
cli/tests/test_diff_command.rs
docs/config.md

I'm used to more context by default.
If applicable:

diff: Allow setting the default level of context in config.

---

docs/install-and-setup.md

docs: fix a typo (-locked vs --locked) in Mac install section

---

docs/git-comparison.md

This part of the git-comparison table was implying you need to manually check and clear staged changes in order to only update the previous commit's message. That isn't the case, though. As mentioned in the [`git-commit` documentation][1], this can be directly achieved by using the `--only` flag with `--amend`:
> If this option is specified together with --amend, then no paths need
> to be specified, which can be used to amend the last commit without
> committing changes that have already been staged.
[1]: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--o

docs: Replace "first make sure that nothing is staged" comment with equivalent `--only` flag

---

CHANGELOG.md
cli/src/commands/config/mod.rs
cli/src/commands/config/unset.rs
cli/src/config.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_config_command.rs

Allow unsetting config values similar to `git config unset`.
```bash
$ jj config set --user some-key some-val
$ jj config get some-key
some-val
$ jj config unset --user some-key
$ jj config get some-key
Config error: configuration property "some-key" not found
For help, see https://martinvonz.github.io/jj/latest/config/.
```
Unsetting a key, which is part of a table, might leave that table empty. For now we do not delete such empty tables, as there may be cases where an empty table is semantically meaningful (https://github.com/martinvonz/jj/issues/4458#issuecomment-2407109269).
For example:
```toml
[table]
key = "value"
[another-table]
key = "value"
```
Running `jj config unset --user table.key` will leave us with `table` being empty:
```toml
[table]
[another-table]
key = "value"
```
--- …

Add new command `jj config unset`

---

CHANGELOG.md
cli/src/commands/help.rs
cli/src/commands/mod.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_help_command.rs

It would be nice to not need to go the documentation website. This aims to solve that by introducing the concept of categories to the help command.
Basically, categories are things that we want to add help messages to, but they don't necessarily have an associated subcommand.
For now we only have two categories:
- `revsets`: Shows the docs for revsets
- `tutorial`: Shows the tutorial that is on the documentation
You get the category content by tipping `jj help revsets`.
It would be nice to have all the documentation on the categories, maybe a next commit could do it.
If applicable:

help: Add a keyword feature

---

.github/workflows/docs.yml

If applicable:
I have manually tested this change on my own fork confirming that the job doesn't run. If I replace "martinvonz" with "senekor", it runs again (but obviously failing), so it should continue to run on the main repo.

ci: don't run website deployment on forks

---

cli/src/cli_util.rs
cli/tests/test_global_opts.rs

cli: insert dummy -h/--help flag when parsing early args

---

cli/src/revset_util.rs
cli/tests/test_debug_command.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: refactor as a prep for introducing type-safe resolution state

---

cli/src/git_util.rs

cli: do not stringify git2::Error too early

---

cli/src/commands/git/push.rs
lib/tests/test_revset.rs

revset: remove callers of .evaluate_programmatic() who depend on symbol resolution

---

docs/FAQ.md

As discussed on [Discord](https://discord.com/channels/968932220549103686/968932220549103689/1302302710393208943), this describes ways to monitor `jj log` output as it evolves in the FAQ.

docs/FAQ.md: answer monitoring `jj log` with watch and TUIs

---

.github/workflows/build-nix.yml
.github/workflows/build.yml
.github/workflows/codespell.yml
.github/workflows/dependabot.yml

When a pull request is pushed multiple times in sequence (e.g. to fix small errors that are noticed post-submission), a backlog of builds ends up needing to be cleared out before your new update can be built. If you push N times, N builds are queued and need to clear out first.
This can cause higher latency for *every* PR since the pool of public runners is shared, and in general seems uneconomical and inefficient since 99% of the time you want to build the new version ASAP.
Luckily GHA has a universal solution to this: use the `concurrency` directive to group all builds for a PR under a name, and when a new build appears in that group, cancel all builds in the group that are in-progress.
Taken from this useful blog post: "Simple trick to save environment and money when using GitHub …

github: cancel in-progress builds on stale PRs

---

cli/src/commands/workspace/update_stale.rs
cli/tests/test_workspaces.rs

cli: workspace update-stale: set description on recovery commit

---

cli/src/commands/git/push.rs
cli/src/commands/log.rs
cli/tests/cli-reference@.md.snap

If applicable:
---
Initially I wanted to have a uniform way to reference settings, eg. like this
but it turned out that `clap` mangles lists unless you use `verbatim_doc_comment` -- see https://github.com/clap-rs/clap/issues/2389. So I just went with prose.

cli: reference config settings for 'jj log -T' and 'jj git push -c'

---

CHANGELOG.md
Cargo.lock
Cargo.toml
cli/src/cli_util.rs
cli/src/commands/bookmark/rename.rs
cli/src/complete.rs
cli/src/lib.rs
cli/tests/runner.rs
cli/tests/test_completion.rs
docs/install-and-setup.md

This is a second attempt to solve https://github.com/martinvonz/jj/issues/1217.
Currently, it's just a proof of concept to gather feedback. What it does is complete local bookmark names for `jj bookmark rename`.
To test it yourself, source the new completions scripts in your shell. For bash, as example:
```sh
source <(COMPLETE=bash ./target/debug/jj)
```
Instructions for each shell are [here](https://docs.rs/clap_complete/latest/clap_complete/env/index.html).

add dynamic completions

---

cli/src/cli_util.rs
cli/tests/test_fix_command.rs
cli/tests/test_immutable_commits.rs

Previously, attempting to modify an immutable commit only showed the ID of the commit being modified, which wasn't very helpful when trying to figure out which immutable commit is being modified at a quick glance.
This commit prints the commit summary as a hint to make it simpler for the user to see what the immutable commit is without having to run `jj show <commit-id>`.
If applicable:

cli: include commit summary when attempting to modify an immutable commit

---

cli/src/commands/bookmark/mod.rs
cli/tests/cli-reference@.md.snap

Unlike other documented aliases, it can be redefined by the user. However, I think it's important for people to be informed that `b` exists.
I left `amend`, `unamend`, and `ci` undocumented, since I think we were considering removing or at least discouraging them.
We could also instead make b a normal built-in alias, now that it won't interfere with completion if we define them as in the previous commit (**Update:** This is no longer the case). I am not sure if letting people redefine it is worth the special case.

cli: document `b` as a "default alias"

---

lib/src/local_working_copy.rs
lib/tests/test_local_working_copy.rs

local_working_copy: ignore submodule updates, skip dir->file conflicts

---

cli/src/commands/rebase.rs
cli/tests/test_duplicate_command.rs
cli/tests/test_rebase_command.rs
cli/tests/test_repo_change_report.rs

This commit extracts out the common code printing out the `MoveCommitsStats` information into a shared function. The printed output was also inconsistent between `-r` and `-s`/`-b` code paths, so I standardized it to say "Rebased ? commits onto destination" for both cases.
If applicable:

cli: rebase: extract out common `print_move_commits_stats` function

---

CHANGELOG.md
cli/src/commands/rebase.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_rebase_command.rs

Now everything supports `-A`/`-B`!
If applicable:

cli: rebase -b: add support for `--insert-after` and `--insert-before` options

---

cli/src/commands/bookmark/delete.rs
cli/src/commands/bookmark/forget.rs
cli/src/commands/bookmark/list.rs
cli/src/commands/bookmark/move.rs
cli/src/commands/bookmark/set.rs
cli/src/commands/bookmark/track.rs
cli/src/commands/bookmark/untrack.rs
cli/src/complete.rs
cli/tests/test_completion.rs

completion: teach commands about bookmark names

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/commands/workspace/update_stale.rs
cli/src/config-schema.json
cli/src/config/misc.toml
cli/tests/test_workspaces.rs
lib/src/working_copy.rs

workspace-update-stale: add a config knob to run automatically

---

docs/config.md

I was a bit confused why adding this to the end of my config didn't do anything:
```toml
revset-aliases."immutable_heads()" = "..."
```
It turns out that I had a `[snapshot]` earlier in the file, so either I had to add that key at the beginning or it needs its own table header:
```toml
[revset-aliases]
"immutable_heads()" = "..."
```
IMO the config examples should all use that syntax to be unambiguous. If that sounds good I can go through all the examples in this file.
If applicable:

docs: switch all toml examples to heading notation

---

flake.nix

The most relevant part (and the motivation for this change) is the addition of the `mainProgram` attribute. This allows getting the executable name from inside nix expressions with ease:
```nix
lib.getExe' jujutsu "jj"
"${jujutsu}/bin/jj"
#or (when using it as a flake input)
inputs.jj.apps.${system}.default.program
```
```nix
lib.getExe jujutsu
```
Everything is copied verbatim from the `nixpkgs` expression (without the maintainer list and changelog link, which depends on the version).
I also deleted the `apps` output. Its only use was to provide an easy way to get the path to the executable AFAICT, but it's redundant now.
If applicable:

nix: Add meta field to package

---

cli/src/cli_util.rs
cli/tests/test_git_clone.rs

cli: warn if `trunk()` cannot be resolved after each transaction

---

cli/src/commands/git/fetch.rs
cli/src/commands/git/push.rs
cli/tests/cli-reference@.md.snap

cli: git push: exclude new bookmarks tracking other remotes if no --remote set

---

CHANGELOG.md
docs/revsets.md
lib/src/default_index/revset_engine.rs
lib/src/revset.rs
lib/tests/test_revset.rs

This can be used to find the best common ancestors of a revset with an arbitrary number of commits, which cannot be done currently.
If applicable:

revset: add `fork_point` function

---

README.md

It feels extraneous. People can just look at whether the GitHub UI shows a checkmark next to the commit.
This creates more space for the IRC badge.
This was originally part of #4881, but it might be simpler to merge it separately.

README: Remove the "build passing" badge

---

README.md

People will often look for contributing instructions from https://github.com/martinvonz/jj, this makes it easier to find.
It will also lead more people to read the contributing docs on the website as opposed to GitHub. This is becoming desireable, see the discussion at
https://github.com/martinvonz/jj/pull/4822#discussion_r1844611306

README: add Contributing bullet

---

cli/src/complete.rs
cli/tests/test_completion.rs

This is adapted from @bnjmnt4n 's fish completions [here](https://gist.github.com/bnjmnt4n/9f47082b8b6e6ed2b2a805a1516090c8#file-jj-fish-L117). It's very nice for auto-generated bookmarks to see the description of the commit they currently point to.
If applicable:

completion: add help text for bookmark names

---

docs/roadmap.md
mkdocs.yml

This also fixes the Xethub link, by pointing it to the web archive, which no longer is available.

docs: Make the Roadmap a toplevel website entry

---

CHANGELOG.md
cli/src/config.rs
cli/tests/test_config_command.rs

cli: fix "config unset" to not delete a whole table

---

Cargo.lock
cli/Cargo.toml
cli/src/commands/config/get.rs
cli/src/commands/config/list.rs
cli/src/commands/config/set.rs
cli/src/commands/config/unset.rs
cli/src/commands/util/config_schema.rs
cli/src/complete.rs
cli/src/config.rs
cli/tests/test_completion.rs

There are two known limitations right now:
- Only statically known keys are suggested.
- Keys that the user did not set are still suggested for `jj config get`. Running that suggestion may result in an error. The error message will be appropriate though and there is some value in letting the user know that this config value theoretically exists. Some users may try to explore what configurations are available via the completions.
If applicable:

completion: teach config about keys

---

CHANGELOG.md
cli/src/commands/git/push.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_bookmark_command.rs
cli/tests/test_completion.rs
cli/tests/test_git_private_commits.rs
cli/tests/test_git_push.rs
cli/tests/test_undo.rs
docs/bookmarks.md
docs/github.md

This basically implements https://github.com/martinvonz/jj/pull/4730#issuecomment-2451082883
If applicable:

cli: git push: do not push new bookmarks by default

---

CHANGELOG.md
docs/revsets.md
lib/src/revset.rs
lib/src/view.rs
lib/tests/test_revset.rs

revset: allow tags() to take a pattern for an argument

---

lib/src/diff.rs

diff: reuse precomputed hash values

---

CHANGELOG.md
cli/src/commands/log.rs
cli/tests/test_bookmark_command.rs
cli/tests/test_commit_template.rs
cli/tests/test_concurrent_operations.rs
cli/tests/test_duplicate_command.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_push.rs
cli/tests/test_log_command.rs
cli/tests/test_next_prev_commands.rs
cli/tests/test_operations.rs
cli/tests/test_parallelize_command.rs
cli/tests/test_rebase_command.rs
cli/tests/test_squash_command.rs
cli/tests/test_workspaces.rs
lib/src/graph.rs

log: emit working-copy branch first if included in the revset

---

cli/tests/test_duplicate_command.rs
lib/src/rewrite.rs
lib/tests/runner.rs
lib/tests/test_rewrite_duplicate.rs

rewrite: fix duplicated commits to be rebased onto destination

---

cli/src/diff_util.rs
cli/src/merge_tools/builtin.rs
cli/src/merge_tools/external.rs
lib/src/annotate.rs
lib/src/conflicts.rs
lib/src/default_index/revset_engine.rs
lib/src/local_working_copy.rs
lib/tests/test_conflicts.rs

conflicts: refactor materialize_merge_result()

---

docs/git-compatibility.md

Use `jj new` instead of `jj new @-` at the end of converting to a co-located repository, because the latter "stashes" newly added working copy changes into a sibling commit.
See also: https://github.com/martinvonz/jj/discussions/4945
If applicable:

docs/git-compatibility.md: preserve working copy files when co-locating

---

docs/tutorial.md

I ran through the tutorial using jj version 0.23 and there were some output changes compared to the tutorial so I updated those, fixed a few wording things, added a few hints and (hopefully) clarified the section around diffedit.
I'm a bit confused why the whole documentation exists twice in the repo. This PR currently only updates a single copy but when the changes are good I'm happy to update the second copy as well.
If applicable:

Update tutorial for 0.23 and clarify diffedit

---

lib/src/conflicts.rs
lib/tests/test_conflicts.rs

I noticed these while working on #4897 and I thought I'd make a PR for them.
If applicable:

conflicts: whitespace parsing fixes

---

cli/src/commands/git/push.rs
cli/tests/cli-reference@.md.snap

I commonly end up typing it. It's long and hard to complete

cli `git push`: short alias -N for --allow-new

---

docs/FAQ.md

I think the user in #4965 was wondering about this. And if they weren't, I know I've heard the question many times before anyway.
If applicable:

faq: add an entry about why merge commits are often empty

---

docs/tutorial.md

Fixes formatting issue from #4872. The current formatting is likely due to creating the files without a newline at the end of the file, which would result in the materialization issue described in #3968. Since the tutorial uses `echo`, which adds a newline automatically, this shouldn't be the output that users see when following the tutorial.

tutorial: fix conflict formatting issue

---

cli/src/command_error.rs
cli/tests/test_working_copy.rs

A super minor cleanup to an error message's grammar and test cases.  I don't think it warrants being called out in the change log or docs but happy to update if others feel it is necessary.
If applicable:

cli: Fix error message grammar and associated tests

---

CHANGELOG.md
cli/src/commands/simplify_parents.rs
cli/src/config-schema.json
cli/src/config/revsets.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_simplify_parents_command.rs

This adds a new `revsets.simplify-parents` configuration option (similar to `revsets.fix`) which serves as the default revset for `jj simplify-parents` if no `--source` or `--revisions` arguments are provided.
If applicable:

cli: simplify-parents: add default `revsets.simplify-parents` config

---

cli/src/cli_util.rs
cli/src/commands/config/list.rs
cli/src/config.rs

config: move resolved_config_values() to free function

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/config/merge_tools.toml
cli/src/merge_tools/external.rs
cli/src/merge_tools/mod.rs
cli/tests/test_diff_command.rs
cli/tests/test_diffedit_command.rs
cli/tests/test_resolve_command.rs
docs/config.md

Follow-up to #4897.
If applicable:

merge_tools: allow setting conflict marker style per-tool

---

cli/src/cli_util.rs
cli/src/complete.rs
cli/src/config.rs

config: make ConfigEnv public, replace global functions

---

flake.nix

As reported by @lilyball on Discord, the recent nixpkgs update this week brought with it an entirely new Darwin stdenv, which had a behavioral change versus the prior one, causing builds inside the developer shell to fail, as the new super-duper parallel linker could not be used.
However, rather than giving up and throwing away *billions* of precious CPU cycles, @emilazy and @lilyball instead doubled down and diagnosed the issue. The result is a new impenetrable line of Nix code, which is fully explained by the comments within.
If applicable:

nix: fix usage of new parallel linker in Darwin devShell

---

cli/src/commands/debug/tree.rs
lib/src/merge.rs
lib/src/merged_tree.rs
lib/src/store.rs
lib/src/tree.rs
lib/src/tree_builder.rs
lib/tests/test_local_working_copy.rs
lib/tests/test_merge_trees.rs
lib/tests/test_merged_tree.rs
lib/testutils/src/lib.rs

Just some little cleanups I noticed while trying to make some functions async
If applicable:

Not performance improvements :)

---

cli/src/commands/commit.rs
cli/src/commands/diff.rs
cli/src/commands/file/annotate.rs
cli/src/commands/file/chmod.rs
cli/src/commands/file/show.rs
cli/src/commands/file/untrack.rs
cli/src/commands/interdiff.rs
cli/src/commands/resolve.rs
cli/src/commands/restore.rs
cli/src/commands/split.rs
cli/src/commands/squash.rs
cli/src/complete.rs
cli/tests/test_completion.rs

This is heavily based on Benjamin Tan's fish completions:
https://gist.github.com/bnjmnt4n/9f47082b8b6e6ed2b2a805a1516090c8
Some differences include:
- The end of a `--from`, `--to` range is also considered.
- `jj log` is not completed (yet). It has a different `--revisions` argument
that requires some special handling.
If applicable:

completion: teach commands about files

---

CHANGELOG.md
docs/install-and-setup.md

docs: clarify dynamic completion features

---

cli/src/cli_util.rs
cli/src/commands/config/list.rs
cli/src/merge_tools/mod.rs
lib/src/config.rs
lib/src/git_backend.rs
lib/src/settings.rs
lib/tests/test_commit_builder.rs
lib/tests/test_init.rs
lib/tests/test_operations.rs
lib/tests/test_signing.rs
lib/testutils/src/lib.rs

settings: own StackedConfig by UserSettings, migrate tests to use config layer

---

cli/src/cli_util.rs
cli/src/commands/config/edit.rs
cli/src/commands/config/mod.rs
cli/src/commands/config/path.rs
cli/src/commands/config/set.rs
cli/src/commands/config/unset.rs
cli/src/config.rs

cli: move get_new_config_file_path() to commands::config

---

Cargo.lock
cli/Cargo.toml
cli/src/commands/commit.rs
cli/src/commands/diff.rs
cli/src/commands/interdiff.rs
cli/src/commands/resolve.rs
cli/src/commands/restore.rs
cli/src/commands/split.rs
cli/src/commands/squash.rs
cli/src/complete.rs
cli/tests/test_completion.rs

stacked on #4887 (teach commands about files)
If there are multiple files in a subdirectory that are candidates for completion, only complete the common directory prefix to reduce the number of completion candidates shown at once.
This matches the normal shell completion of file paths.
If applicable:

completion: suggest file paths incrementally

---

lib/src/git.rs
lib/tests/test_git.rs

* GitFetch{} separates `fetch()` from `import_refs()`.
* This allows more control over the stages of the fetch so multiple fetches
can happen before `import_refs` resolves the changes in the local jj repo.
* Implement `git::fetch` in terms of the new api.
* Add a test case for initial fetch from a repo without `HEAD` set. This tests
the default branch retrieving behaviour.
Issue: #4923
If applicable:

jj-lib: abstract a lower-level api for fetching from git.

---

cli/src/commands/util/gc.rs
cli/tests/cli-reference@.md.snap

This is a followup to the discussion in
https://github.com/martinvonz/jj/pull/4953#discussion_r1855328098

cli `util gc`: document the fact that evolution log limits gc

---

CHANGELOG.md
cli/src/commands/describe.rs
cli/src/commands/status.rs
cli/tests/cli-reference@.md.snap

This backs out commit fd271d39ad54 "cli: make `jj desc` and `jj st` aliases hidden."
As we discussed in https://github.com/martinvonz/jj/pull/4811, completion of flags doesn't work for hidden aliases.
If applicable:

cli: make `jj desc` and `jj st` aliases visible again

---

cli/src/commands/duplicate.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_duplicate_command.rs

I'm thinking of deprecating `jj duplicate REV` (without `-r`), but that might be controversial.
If applicable:

cli: duplicate: parse -rREV option properly

---

cli/src/cli_util.rs
cli/src/commands/config/list.rs
cli/src/complete.rs
cli/src/config.rs
cli/src/formatter.rs
cli/src/merge_tools/mod.rs
cli/src/text_util.rs
cli/src/ui.rs
lib/src/config.rs

config: migrate off `config.merge()`

---

CHANGELOG.md
cli/src/commands/sparse.rs
cli/src/config/templates.toml
cli/src/description_util.rs
cli/tests/test_commit_command.rs
cli/tests/test_describe_command.rs
cli/tests/test_split_command.rs
cli/tests/test_squash_command.rs
cli/tests/test_unsquash_command.rs

cli: consider "JJ:" lines as comments also when not followed by space

---

cli/src/commands/git/push.rs
cli/tests/test_git_private_commits.rs
cli/tests/test_git_push.rs

First time-contributor, so feedback at any level of pedantry is fine while I adjust to the project norms!
Related to #5002.
If applicable:

cli: git push: optionally describe commits that would fail push

---

flake.lock
flake.nix

This was highlighted in @necauqua in Discord [here](https://discord.com/channels/968932220549103686/969291218347524238/1313984464447344661) and I agreed with the concern. The first commit enacts the pinning, the second one automated updates. I arbitrarily chose the same weekly cron schedule as the scorecards workflow.
Anecdotally a number of Rust-adjacent Nix libraries (such as Crane) also use this GHA. I myself used it for a long time as well:
https://github.com/shanesveller/nix-flake-lock-targets/blob/0ce982a5d1c115d8ba0683da3cd4af131309c26e/.github/workflows/update.yml
Feedback very welcome about further adjusting or populating the action arguments as lightly documented [here](https://github.com/DeterminateSystems/update-flake-lock/tree/a2bbe0274e3a0c4194390a1e445f734c597ebc37?tab=readm …

nix: Pin nixpkgs input to current registry definition, automate lock updates

---

Cargo.lock
Cargo.toml
flake.nix

cargo: enable zlib-ng and fast sha1 in gix

---

cli/src/commands/log.rs
cli/src/complete.rs
cli/tests/test_completion.rs

stacked on #4895 (suggest file paths incrementally)
If applicable:

completion: teach log about files

---

CHANGELOG.md
cli/src/diff_util.rs
cli/tests/test_absorb_command.rs
cli/tests/test_diff_command.rs
cli/tests/test_diffedit_command.rs
cli/tests/test_evolog_command.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
cli/tests/test_restore_command.rs

diff: fix unified diff to emit one-lower start line number for empty hunks

---

CHANGELOG.md
cli/src/progress.rs
cli/src/ui.rs

@Ralith, can you take a look and see if this preserves the behavior you intended?
Closes #5057.
If applicable:

Fix performance of progress bar in Git fetch

---

lib/src/local_working_copy.rs
lib/tests/test_local_working_copy.rs

If applicable:
---
Benchmark:
1. original
2. per-directory spawn
3. per-directory deleted files
4. shorter path comparison
gecko-dev (~357k files, ~25k dirs)
```
% JJ_CONFIG=/dev/null hyperfine --sort command --warmup 3 --runs 30 ..
Benchmark 1: target/release-with-debug/jj-1 -R ~/mirrors/gecko-dev debug snapshot
Time (mean ± σ):     764.9 ms ±  16.7 ms    [User: 3274.7 ms, System: 2183.3 ms]
Range (min … max):   731.9 ms … 814.2 ms    30 runs
Benchmark 2: target/release-with-debug/jj-2 -R ~/mirrors/gecko-dev debug snapshot
Time (mean ± σ):     710.7 ms ±   9.1 ms    [User: 3070.7 ms, System: 2142.6 ms]
Range (min … max):   695.9 ms … 740.1 ms    30 runs
Benchmark 3: target/release-with-debug/jj-3 -R ~/mirrors/gecko-dev debug snapshot
Time (mean ± σ):     480.1 ms ±   8.8 ms    [User: …
```

local_working_copy: spawn snapshot job per directory,  filter deleted files per job

---

CHANGELOG.md
Cargo.lock
Cargo.toml
cli/src/cli_util.rs
cli/src/commands/config/get.rs
cli/src/commands/config/list.rs
cli/src/commands/fix.rs
cli/src/config.rs
cli/src/formatter.rs
cli/src/revset_util.rs
cli/tests/test_alias.rs
cli/tests/test_config_command.rs
cli/tests/test_fix_command.rs
cli/tests/test_global_opts.rs
cli/tests/test_log_command.rs
lib/src/config.rs
lib/src/settings.rs

config: migrate underlying data structure to toml_edit

---

CHANGELOG.md
cli/src/config/misc.toml
cli/src/formatter.rs
cli/src/template_builder.rs
cli/src/ui.rs
cli/tests/test_global_opts.rs

config: detect error in ui.color and colors table

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/config.rs
cli/src/config/misc.toml
cli/src/revset_util.rs
cli/tests/test_config_command.rs
docs/config.md
lib/src/config.rs

config: merge and print inline tables as values

---

Cargo.toml
docs/contributing.md
rust-toolchain.toml

This backs out commit 89d57ffb29577c99f0f5187b76bff369f19c5886.
This is causing a CI failure because we can't build musl binaries, presumably because the rust-toolchain file overriding the chosen musl toolchain for some reason. Backout until we can reapply a proper fix.
If applicable:

Back out 89d57ffb: "build: add `rust-toolchain.toml`"

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/config.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_completion.rs
cli/tests/test_global_opts.rs
docs/config.md
lib/src/config.rs

cli: add --config-file=PATH argument

---

cli/src/commands/new.rs
cli/tests/cli-reference@.md.snap

I followed the recommendation in the `jj new` doc to use `jj new main @` to make a merge commit and ended up with a merge commit that GitHub did not like. The PR diff included both the relevant changes from that branch plus everything I merged in. @papertigers pointed out that swapping the two args produces a merge commit GitHub understands better. Happy to add a line explaining that the order matters, but it might be too much detail for this spot. The linked doc https://martinvonz.github.io/jj/latest/working-copy/ also does not explain this.
If applicable:

Docs: swap order of `@` and `main` in `jj new` doc comment

---

cli/src/command_error.rs
cli/src/commands/config/mod.rs
cli/src/commands/config/set.rs
cli/src/commands/config/unset.rs
cli/src/commands/git/clone.rs
cli/src/commands/git/init.rs
cli/src/commands/git/mod.rs
cli/src/config.rs
cli/tests/test_config_command.rs
lib/src/config.rs

config: refactor and move config set/unset functions to jj-lib

---

CHANGELOG.md
cli/src/commands/config/edit.rs
cli/src/commands/config/mod.rs
cli/src/commands/config/path.rs
cli/src/commands/config/set.rs
cli/src/commands/config/unset.rs
cli/src/config.rs
cli/tests/common/mod.rs
cli/tests/test_config_command.rs
lib/src/config.rs

cli: let "config set"/"unset" continue if file to edit can be disambiguated

---

cli/src/commands/split.rs
cli/tests/cli-reference@.md.snap

cli: make jj split more explicit about filesets

---

cli/examples/custom-working-copy/main.rs
cli/tests/test_working_copy.rs
lib/src/gitignore.rs

From Discord question: https://discord.com/channels/968932220549103686/1317492522712436826
If applicable:

gitignore: add more detail to errors on invalid pattern

---

cli/src/cli_util.rs
docs/contributing.md

Using the default `RUST_LOG` environment variable conflicts when working on unrelated Rust projects.
Supersedes #4350, which is stale.
Closes #4219 #4350
I am unsure whether this has to be listed as a breaking change in the CHANGELOG.

feat: use `JJ_LOG` to specify log configuration

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/config/set.rs
cli/src/complete.rs
cli/src/config.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_completion.rs
cli/tests/test_config_command.rs
cli/tests/test_global_opts.rs
docs/config.md

cli: add simpler --config=NAME=VALUE argument

---

lib/src/gitignore.rs

I looked through the code for the `ignore` crate, and this optional path is not used anywhere. The only reason to pass it would be to be able to get the path from the `Glob` when we call `Gitignore::matched` or `Gitignore::matched_path_or_any_parents`, but we ignore the returned `Glob` completely anyway. Passing the path would require an unnecessary clone of the path for each line in every .gitignore file, so it's better not to pass it since we don't need it.
https://github.com/martinvonz/jj/pull/5113#discussion_r1887769952
If applicable:

gitignore: remove FIXME comment about passing path

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/complete.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_builtin_aliases.rs
cli/tests/test_commit_command.rs
cli/tests/test_commit_template.rs
cli/tests/test_completion.rs
cli/tests/test_config_command.rs
cli/tests/test_describe_command.rs
cli/tests/test_diff_command.rs
cli/tests/test_diffedit_command.rs
cli/tests/test_evolog_command.rs
cli/tests/test_git_private_commits.rs
cli/tests/test_git_push.rs
cli/tests/test_global_opts.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
cli/tests/test_rebase_command.rs
cli/tests/test_resolve_command.rs
cli/tests/test_revset_output.rs
cli/tests/test_templater.rs
cli/tests/test_unsquash_command.rs
cli/tests/test_util_command.rs
cli/tests/test_working_copy.rs
cli/tests/test_workspaces.rs
demos/demo_juggle_conflicts.sh
docs/config.md
lib/src/fsmonitor.rs

cli: deprecate --config-toml

---

cli/src/cli_util.rs
cli/src/complete.rs
cli/src/merge_tools/mod.rs
cli/tests/test_revset_output.rs
lib/src/git_backend.rs
lib/src/settings.rs
lib/tests/test_commit_builder.rs
lib/tests/test_init.rs
lib/tests/test_operations.rs
lib/tests/test_signing.rs
lib/testutils/src/lib.rs

settings: propagate error from UserSettings::from_config()

---

CHANGELOG.md
cli/src/config/templates.toml
docs/config.md

Adds an extension point for changing which date is displayed in log formats. The function should return a timestamp, not a formatted string.
Fixes: #5132 
If applicable:

config: Add `commit_timestamp(commit)` template alias

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/config/mod.rs
cli/src/complete.rs
cli/src/config.rs
cli/tests/test_config_command.rs
cli/tests/test_global_opts.rs
docs/config.md
lib/src/config.rs
lib/src/config_resolver.rs
lib/src/lib.rs

config: add conditional tables

---

CHANGELOG.md
cli/src/cli_util.rs
lib/src/gitignore.rs

I discovered `jj` a few days ago, and it seems pretty neat!
While I familiarize myself with the codebase (there will be an actual PR at some point, I promise), here's a few typos `typos` was screaming at me for.

Fixed auto-detected typos

---

docs/config.md
lib/src/config_resolver.rs

config: remove check for relative path patterns, add doc about path equivalence

---

docs/github.md

docs: Git doesn't use bookmarks, jj does

---

cli/tests/common/mod.rs
cli/tests/test_config_command.rs
cli/tests/test_describe_command.rs
cli/tests/test_diff_command.rs
cli/tests/test_diffedit_command.rs
cli/tests/test_fix_command.rs

tests: use toml_edit::Value to escape string and array

---

lib/src/dag_walk.rs
lib/tests/test_operations.rs
lib/tests/test_rewrite.rs

This commit fixes typos unintentionally introduced in d9c68e08, when renaming `jj branch` to `jj bookmark`.
If applicable:

lib: fix various typos

---

CHANGELOG.md
cli/src/merge_tools/external.rs
cli/tests/test_resolve_command.rs

merge_tools: preserve executable bit on resolve

---

CHANGELOG.md
cli/src/commands/git/clone.rs
cli/tests/common/mod.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_push.rs

cli: git clone: convert local Git remote path to slash-separated path

---

CHANGELOG.md
lib/src/revset.rs
lib/src/settings.rs
lib/src/transaction.rs
lib/tests/test_revset.rs

settings: propagate configuration error of commit and operation parameters

---

CHANGELOG.md
cli/src/merge_tools/external.rs
cli/testing/fake-editor.rs
cli/tests/test_resolve_command.rs
docs/config.md

Discussed previously here: https://github.com/jj-vcs/jj/pull/4969#discussion_r1859088488
Git supports passing the conflict marker length to merge drivers using "%L". It would be useful if we also had a way to pass the marker length to merge tools, since it would allow Git merge drivers to be used with `jj resolve` in more cases. Without this variable, any merge tool that parses or generates conflict markers could fail on files which require conflict markers longer than 7 characters.
https://git-scm.com/docs/gitattributes#_defining_a_custom_merge_driver
If applicable:

merge_tools: add `"$marker_length"` variable

---

CHANGELOG.md
cli/src/config/templates.toml
cli/src/description_util.rs
cli/tests/test_describe_command.rs
docs/config.md

Implements #4210
~~Instead of a scissor _line_, this implements a scissor _section_. Everything between a pair of scissor lines is ignored. This allows it to work with #3828, as long as you put the ending line. Currently the beginning and ending lines are the same, so only one alias is required. Could easily be separated.~~
Implements a single scissor line, since `JJ: describe` lines are parsed first. Everything after a scissor line, before a `JJ: describe` line is ignored.
Open to other ideas on the style of the scissor lines. Additionally, the `scissor` template alias does *not* insert the "Do not modify or remove the line above." line from git --- should it? I lean softly towards no, since the user would have to seek out the alias to end up with it.
```toml
[templates] …
```

describe: add ignore-rest directive

---

docs/conflicts.md

I think this would be good to explain so that users aren't confused if they see this.
If applicable:

docs: explain long conflict markers

---

README.md

It has seriously gone out of date, so update it for 2025 and mention the new `jj-vcs` org. The suggestion came from melutovich in the #jujutsu Libera IRC chat.

docs: Update the News section of the README

---

cli/tests/test_config_command.rs
lib/src/config.rs

config: preserve key formatting on set_value()

---

README.md

Addresses https://github.com/jj-vcs/jj/issues/5191
If applicable:

README: replace outdated claim about lacking git blame support

---

.github/workflows/build.yml
lib/src/time_util.rs
lib/src/union_find.rs

Follow-up from https://github.com/martinvonz/jj/pull/5052. This isn't critical, so we can drop this PR if we think it's not important or not worth resolving the outstanding questions for now.
Questions:
- What is our policy/strategy for new top-level checks vs embedding steps into existing checks?
- I chose to make new top-level checks since I figured the feedback loop would be faster that way:
- When a problem occurs, it's obvious at the top-level display that it's not a "real" test failure, just a rustdoc issue.
- When you're fixing the problem, you don't have to wait the entire test suite.
- However, it probably induces additional overall load to compile/process the codebase again?
- What is our policy for setting the Rust toolchain for the new checks?
- I chose MSRV for the doctests …

ci: check Rust documentation

---

CHANGELOG.md
Cargo.lock
Cargo.toml

release: 0.25.0

---

lib/src/signing.rs
lib/src/store.rs

signing: cap number of cached verification results

---

cli/src/commands/squash.rs

cli: squash: reorganize `move_diff()` to fix "too many arguments"

---

flake.nix

Have been used in nixpkgs since the update to 0.24. This makes dynamic completions the default for those who use jj directly from the jj repo as well.
If applicable:

nix: use dynamic completions in installPhase

---

flake.nix

This changes the `$name` environment variable from `nix-shell-env` to `jujutsu-env` when inside the nix-provided devshell.
Looks nicer / more descriptive if you use it as part of your prompt.
If applicable:

nix: add name to devshell

---

Cargo.toml
cli/src/diff_util.rs

The code is already clean, except for one occurrence of a useless call to `Into::into()`.

Enable `useless_conversion` clippy lint

---

cli/src/merge_tools/external.rs

Using `.last()` needs to go through all components first instead of splitting only the last one.

perf: use `.next_back()` to get the last component

---

CHANGELOG.md
cli/src/commands/evolog.rs
cli/src/graphlog.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_evolog_command.rs

Resolves https://github.com/jj-vcs/jj/issues/5088
If applicable:

Add `--reversed` flag to `evolog`

---

cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/commands/commit.rs
cli/src/commands/config/edit.rs
cli/src/commands/describe.rs
cli/src/commands/sparse/edit.rs
cli/src/commands/split.rs
cli/src/commands/squash.rs
cli/src/commands/unsquash.rs
cli/src/description_util.rs
cli/tests/test_describe_command.rs

cli: add "ui.editor" type that captures configuration

---

docs/bookmarks.md

Some places used "bookmark" instead, which makes it harder to differentiate between jj's and Git's differing concepts.

docs: Use "branch" consistently when talking about Git's branches

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/merge_tools/mod.rs
cli/tests/test_commit_command.rs
cli/tests/test_split_command.rs

cli: fix interactive diff selection to not retain unmatched files

---

cli/src/cli_util.rs
cli/src/commands/status.rs
cli/src/config/colors.toml
cli/tests/test_status_command.rs
lib/src/local_working_copy.rs
lib/src/working_copy.rs

This adds the plumbing to get the untracked files from the snapshot to the status command and displays them similar to mercurial. I am not sure if this is the right way to do this.
This might be the last thing to fix https://github.com/jj-vcs/jj/issues/323.
If applicable:

show untracked files in jj status

---

CHANGELOG.md

I am not sure this belongs in breaking changes or new features. I have it as breaking right now because it changes the output of the status command.
If applicable:

added changelog entry for showing untracked files in `jj status`

---

CHANGELOG.md
cli/src/cli_util.rs
cli/tests/test_git_colocated.rs
lib/src/git.rs
lib/tests/test_git.rs

I had some free time over the holidays, so I thought I'd take a shot at #3979. I think this matches what was agreed upon as the best "step 1" in the issue discussion.
If applicable:

git: use merged parent tree for git index

---

.github/workflows/build-nix.yml
.github/workflows/build.yml
.github/workflows/codespell.yml
.github/workflows/dependabot.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/scorecards.yml

This gets rid of an annoying warning in the Actions tab, but we already rely on this for the build-binaries workflow, and it's probably better to be explicit about this anyway.
If applicable:

github: migrate all actions to `ubuntu-24.04`

---

lib/src/rewrite.rs
lib/tests/test_merge_trees.rs

Roll back 9d4a973 (resolve intermediate parent tree when rebasing merge commits)

---

lib/src/local_working_copy.rs
lib/tests/test_local_working_copy.rs

local_working_copy: on snapshot, ignore submodule in ignored directories

---

.github/workflows/build-nix.yml
.github/workflows/build.yml
.github/workflows/codespell.yml
.github/workflows/dependabot.yml

These are the workflows that run on PRs, so they need to have the `merge_group` event added to them if we want to use the merge queue.
If applicable:

github: add `merge_group` event to several workflows

---

.github/workflows/build.yml

This seems to have no impact on the CI runners (I thought it might, but oh well.) It's at least more consistent with how we run the test ourselves, and I think the output looks nicer, so I consider it a win anyway.
If applicable:

github: install and use nextest for GHA

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/merge_tools/external.rs
cli/src/merge_tools/mod.rs
cli/tests/test_diff_command.rs
docs/config.md

#5250
Certain tools (`diff`, `delta`) exit with code 1 to indicate there was
a difference. This allows selectively suppressing the "Tool exited with
... status" warning from jj when generating a diff.
example:
```toml
[merge.tools.delta]
diff-expected-exit-codes = [1]
```
If applicable:

diff: add `merge-tools.*.diff-expected-exit-codes`

---

.github/workflows/build.yml
Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/commands/bookmark/list.rs
cli/src/commands/bookmark/mod.rs
cli/src/commands/bookmark/untrack.rs
cli/src/commands/debug/copy_detection.rs
cli/src/commands/mod.rs
cli/src/commands/operation/diff.rs
cli/src/git_util.rs
cli/src/lib.rs
cli/src/progress.rs
flake.nix
lib/Cargo.toml
lib/src/git.rs
lib/src/lib.rs
lib/src/local_backend.rs
lib/src/protos/op_store.proto
lib/src/protos/op_store.rs
lib/src/revset.rs
lib/src/simple_op_store.rs

There are some experiments to try and compile `jj` to WebAssembly, so that we might be able to do things like interactive web tutorials. One step for that is making `git` support in `jj-cli` optional, because we can stub it out for something more appropriate and it's otherwise a lot of porting annoyance for both gitoxide and libgit2.
(On top of that, it might be a useful build configuration for other experiments of mine where removing the need for the large libgit2 depchain is useful.)
As part of this, we need to mark `jj-lib` as having `default-features = false` in the workspace dependency configuration; otherwise, the default behavior for Cargo is to compile with all its default features, i.e. with git support enabled, ignoring the `jj-cli` features clauses.
Other than that, it is …

cli: make git support optional

---

.github/workflows/build-nix.yml
.github/workflows/build.yml
.github/workflows/codespell.yml

The new `merge_group` event will already attach all the CI events from the various workflows where it applies. If the merge queue is drained and merges to `main`, having `push` on these workflows will cause them to be run again, doubling the number of CI checks. We don't need `push` anymore, basically.
Also, because checks can be cancelled now, the current double running can probably lead to an awkward setup like:
- Merge Queue merges A to main, starts `push` workflows
- Merge Queue then merges B and C to main, starts `push` workflows
- `A`'s workflows get cancelled if it's not yet done
- This makes it look like `A` has failing tests somehow, but it doesn't
Therefore, just removing the double builds is the first step to cut down on the CI times for our repo.
We also run the build …

github: don't run build workflows twice on push to `main`

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/commands/resolve.rs
cli/src/merge_tools/builtin.rs
cli/src/merge_tools/external.rs
cli/src/merge_tools/mod.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_resolve_command.rs
lib/src/repo_path.rs

If many files are conflicted, it would be nice to be able to resolve all conflicts at once without having to run `jj resolve` multiple times. This is especially nice for merge tools which try to automatically resolve conflicts without user input, but it can also be used for regular merge editors like VS Code.
If applicable:

resolve: try to resolve all conflicted files in fileset

---

CHANGELOG.md
cli/src/config/templates.toml
cli/tests/test_evolog_command.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
cli/tests/test_show_command.rs
cli/tests/test_templater.rs

I find one-line logs a *lot* more readable, so I really appreciate `jj log -T builtin_log_oneline` and would like to have the same available for `jj op log`:
If applicable:
- I don't think this needs a special mention, as `builtin_log_oneline` doesn't have one either
Occasionally the single line won't be enough to display all the information
In that case I think I would prefer to have `lasted t milliseconds -> lasted 5ms` and maybe shorten the commit id in the message, but that's something for another PR / personal configuration.

add builtin_op_log_oneline template

---

docs/contributing.md
flake.nix

As of https://github.com/watchexec/cargo-watch/commit/9f27bc1c96d93ff85347619ec4a2bf72fc90fe68, `cargo-watch` is on minimal development and officially recommends `bacon` as a successor.
If applicable:

contributing: recommend bacon over cargo-watch

---

cli/tests/test_git_init.rs
cli/tests/test_simplify_parents_command.rs
cli/tests/test_workspaces.rs

tests: insert insta::allow_duplicates! { .. } per snapshot

---

lib/src/git.rs
lib/tests/test_git.rs

git: remove PartialEq requirement from GitPushError

---

.github/workflows/build-nix.yml
.github/workflows/build.yml

Like `main`, we don't want to double build these branches since they will be handled by `merge_group` already.
If applicable:

github: don't run `dependabot` or `gh-readonly-queue` builds twice

---

cli/tests/test_config_command.rs
lib/src/config.rs
lib/src/config_resolver.rs

config: allow inline table syntax in mutation and conditional scope API

---

CHANGELOG.md
cli/src/commands/fix.rs
cli/src/config-schema.json
cli/tests/cli-reference@.md.snap
cli/tests/test_fix_command.rs

cli: remove handling of deprecated fix.tool-command config

---

flake.nix

There's some duplication in the `flake.nix`, with required packages being listed both in `packages.jujutsu.{nativeB,b}uildInput` and `devShells.default.packages`. This removes the duplication.
If applicable:

nix: clean up flake

---

docs/install-and-setup.md

In recent times multiple users showed up and were confused _why_ some completions didn't show up, so make it explicit that they're opt-in until the Clap upstream has made it so.
Also remove the link to the dynamic completions improvements issue, as it was closed
a while ago.
If applicable:

docs: Make dynamic completions a bit more visible

---

.github/workflows/docs.yml

It contained a check for `repo_owner == 'martinvonz'` which meant that it hasn't run in 4 weeks. This is another great example showing why current CI systems suck, as it always was "successful" in doing nothing with no warning whatsoever.
I also only noticed it because I wanted to check my latest doc change on the prerelease site.
cc @thoughtpolice

workflows: fix the pre-release docs workflow

---

cli/src/commands/operation/diff.rs
cli/tests/test_operations.rs

op diff: remove redundant "Change {change_id}" from changed commits graph

---

cli/src/complete.rs
cli/tests/test_completion.rs

When running `cmd.spawn()` rust will by default inherit the stderr of the parent, so `jj log test<TAB>`, would print `There is no jj repo in "."` into the prompt if you aren't in a repository.

cli: complete: fix stderr during autocomplete of revsets

---

lib/src/dag_walk.rs

This commit fixes more typos unintentionally introduced in d9c68e08, when renaming `jj branch` to `jj bookmark`.
If applicable:

lib: dag_walk: fix doc comment typos

---

CHANGELOG.md
cli/src/commands/git/push.rs
cli/src/config-schema.json
cli/src/config/misc.toml
cli/tests/test_git_push.rs
docs/config.md

This adds the `git.sign-on-push` configuration which can be used to
automatically sign unsigned commits before pushing to a Git remote.
If applicable:

cli: git push: allow signing commits on push

---

cli/src/cli_util.rs
cli/src/complete.rs
cli/tests/test_completion.rs

cli: autocomplete: complete `--config` with possible configuration keys

---

cli/src/cli_util.rs
cli/src/complete.rs
cli/tests/test_completion.rs

Now `jj --config ui.con<TAB><TAB>` will autocomplete
```
ui.conflict-marker-style=diff
ui.conflict-marker-style=snapshot
ui.conflict-marker-style=git
```
Booleans are completed as `false`, `true`, the remaining types are left without completions.
If applicable:
- ~[ ] I have updated `CHANGELOG.md`~
- ~[ ] I have updated the documentation (README.md, docs/, demos/)~
- ~[ ] I have updated the config schema (cli/src/config-schema.json)~

cli: autocomplete: complete config values in addition to keys

---

CHANGELOG.md
cli/src/commands/fix.rs
cli/src/config-schema.json
cli/tests/cli-reference@.md.snap
cli/tests/test_fix_command.rs
docs/config.md

As inspired by @ilyagr: https://discord.com/channels/968932220549103686/969291218347524238/1276278608729608243
Adds an optional `fix.tools.TOOL.enabled` config that disables use of a fix tool (if omitted, the tool is enabled). This is useful for defining tools in the user's configuration without enabling them for all repositories:
```toml
[fix.tools.rustfmt]
enabled = false
command = ["rustfmt", "--emit", "stdout"]
patterns = ["glob:'**/*.rs'"]
```
Then to enable it in a repository:
```shell
$ jj config set --repo fix.tools.rustfmt.enabled true
```
This also allows Jujutsu to ship some built-in tool configurations that are disabled by default.
If applicable:

fix: Add `enabled` config for fix tools

---

CHANGELOG.md
Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/ui.rs
deny.toml
docs/config.md
docs/windows.md

switch builtin pager to streampager

---

CHANGELOG.md
docs/config-schema.json
docs/config.md

When landed and published, this will expose the config file as:
https://jj-vcs.github.io/jj/latest/config-schema.json
Exposing the schema like that will allow users to reference in their `~/.config/jj/config.toml` like:
```toml
"$schema" = 'https://jj-vcs.github.io/jj/latest/config-schema.json'
```
At which point any user with a configured LSP for TOML files will get inline documentation, suggestions on valid keys, &c.
Some example screenshots of this working in my local NeoVim setup (using a local `mkdocs serve` of these changes), but the same works in any editor with an LSP setup for TOML files.
If applicable:

docs: Expose `config-schema.json` in the docs site

---

docs/config.md

This seems non-trivial to discover and could be useful for people transitioning form `--config-toml`.

docs config: an advanced example of `--config` syntax

---

CHANGELOG.md
cli/src/commands/git/push.rs
cli/src/config-schema.json
cli/src/config/misc.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_git_push.rs

cli: add "git.push-new-bookmarks" config knob to enable --allow-new by default

---

cli/tests/test_log_command.rs
cli/tests/test_revset_output.rs
lib/src/revset.pest
lib/src/revset_parser.rs

revset: parse unicode XID_CONTINUE characters as symbol

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/config/colors.toml
cli/src/config/misc.toml
cli/src/config/templates.toml
cli/tests/test_commit_template.rs
docs/config.md

Cryptographic signature support in templates was added in c99c97c6467fee3f3269d2934c10c758e041f834, but has to be manually configured. This adds some defaults to the built-in config.
Instead of having separate `builtin_log_*_with_sig` aliases, this adds to the aliases that actually format commits. Since signature verification is slow, this is disabled by default. To enable it, override the `should_show_cryptographic_signature()` template alias like so:
[template-aliases]
'should_show_cryptographic_signature()' = 'true'
'format_short_cryptographic_signature(signature)' = ...
'format_detailed_cryptographic_signature(signature)' = ...
Note that the two formatting functions take `Option<Signature>`, not `Signature`. This allows you to display a custom message if a signature is not found, but …

templates: add cryptographic_signature display to default formats

---

cli/src/commands/absorb.rs
cli/tests/test_absorb_command.rs
lib/src/absorb.rs

absorb: print status if source commit still contains diffs

---

cli/src/commands/debug/watchman.rs
cli/src/ui.rs
lib/src/backend.rs
lib/src/fsmonitor.rs
lib/src/local_backend.rs
lib/src/settings.rs
lib/src/signing.rs

I noticed that some config structures do not use their "Default" implementation, and have their default specified in a TOML file. I think specifying defaults in TOML is great, and it'd be good to delete those Default implementations, so that it does not diverge from the default in the TOML file.
I then kept going with a few more structures that seem better off without Default implemented.
If applicable:

style/cleanup: remove a bunch of Default implementations

---

CHANGELOG.md
cli/tests/test_revset_output.rs
docs/revsets.md
lib/src/default_index/revset_engine.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: split author()/committer() into _name()/email() predicates

---

cli/src/commands/git/clone.rs
cli/tests/test_git_clone.rs

cli: handle remote configuration error on "git clone"

---

.github/workflows/codespell.yml
cli/tests/test_fix_command.rs

It is having a fit for some reason, see e.g.
https://github.com/jj-vcs/jj/actions/runs/12897590111/job/35963026619?pr=5414
Not sure what changed, but here is a quick fix

actions: fix codespell CI failure

---

CHANGELOG.md
cli/src/commands/describe.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_describe_command.rs

The --edit flag forces the editor to be shown, even if it would have been hidden due to the --no-edit flag or another flag that implies it (such as --message or --stdin).
This fixes #5379  
If applicable:

Add a --edit flag

---

.github/workflows/build.yml
CHANGELOG.md
cli/src/commands/git/clone.rs
cli/src/commands/git/push.rs
cli/src/config-schema.json
cli/src/git_util.rs
cli/tests/common/mod.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_push.rs
docs/config.md
flake.nix
lib/src/config/misc.toml
lib/src/git.rs
lib/src/git_subprocess.rs
lib/src/lib.rs
lib/src/settings.rs
lib/tests/test_git.rs

`jj` fails to push/fetch over ssh depending on the system.
Issue #4979 lists over 20 related issues on this and proposes spawning
a `git` subprocess for tasks related to the network (in fact, just push/fetch
are enough).
This PR implements this.
Users can either enable shelling out to git in a config file:
```toml
[git]
subprocess = true
```
This PR implements shelling out to `git` via `std::process::Command`.
There are 2 sharp edges with the patch:
- it relies on having to parse out git errors to match the error codes
(and parsing git2's errors in one particular instance to match the
error behaviour). This seems mostly unavoidable
- to ensure matching behaviour with git2, the tests are maintained across the
two implementations. This is done using test_case, as with the rest
of the …

git: spawn a separate git process for network operations

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/config.rs
cli/tests/test_config_command.rs
docs/config.md
lib/src/config_resolver.rs

Closes #5217 
Adds a new config scope resolution `--when.commands`. This is a list of space-separated commands:
```toml
--when.command = ["file"]        # matches `jj file show`, `jj file list`, etc
--when.command = ["file show"]   # matches `jj file show`, but *NOT* `jj file list`
--when.command = ["file", "log"] # matches `jj file` *OR* `jj log` (or subcommand of either)
```
If applicable:

config: add `--when.commands` scope

---

flake.lock
flake.nix

bacon 3.6.0 -> 3.8.0, shows output with nextest 0.9.86 (Canop/bacon#280)
If applicable:

nix: flake update

---

.github/workflows/build-nix.yml

Apparently, Magic Nix Cache will stop working on Feb 1st, because the underlying APIs are being sunset by GitHub, and there are no open replacements for it quite yet. Since it's just an optimization, we'll have to live with it.
If applicable:

github: remove Magic Nix Cache

---

CHANGELOG.md

Other links in CHANGELOG.md have the issue number as the text, and the full URL as a link. They're swapped here, meaning the link points to a non-existent anchor in the CHANGELOG.md file.

Fix a broken link in CHANGELOG.md

---

.github/workflows/build.yml
cli/tests/common/mod.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_push.rs
cli/tests/test_util_command.rs
flake.nix
lib/tests/test_git.rs

Currently, the Git subprocess tests only work on Linux due to a default path being used for the `git` executable when `$PATH` is unset. This can break if Git isn't installed at the expected path. Also, I believe it is currently necessary to set the `$TEST_GIT_EXECUTABLE_PATH` environment variable on Windows for tests to pass. Instead, we should use the user's `$PATH` to locate the `git` executable, as well as any other executables that are needed. This also makes `$TEST_GIT_EXECUTABLE_PATH` no longer necessary, so it can be removed.
Discussed in #5463.
If applicable:

tests: keep user's `$PATH` while running `jj` commands

---

CHANGELOG.md
cli/src/commands/evolog.rs
cli/src/commands/log.rs
cli/src/commands/operation/log.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_evolog_command.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
lib/src/revset.rs

 cli: apply log --limit before --reversed

---

CHANGELOG.md
lib/src/conflicts.rs
lib/tests/test_conflicts.rs

Fixes #3968. Alternative to #5181 and #4088.
If applicable:

conflicts: allow missing newlines at end of file (based on previous content)

---

cli/src/git_util.rs

`ui.prompt_password()` already adds ": " to the end of the prompt. Remove the extra at the (only) callsite, to keep similarity to the above `terminal_get_pw()`.
If applicable:

cli: remove double ": : " on git password prompt

---

cli/src/commands/log.rs
cli/src/commands/operation/log.rs
cli/tests/cli-reference@.md.snap

Fixes #5490 (we can catch other instances of this manually)
Seems to work fine via `mkdocs serve`.
Note that it links to the `latest` even if you are looking at the `prerelease` docs. This is not ideal, but seems annoying to fix.

cli reference & `jj log --help`: render URLs in CLI refrerence

---

docs/templates.md

I was very confused by the example for a moment before realising that it made sense if `commit_id` became `change_id`.
I also found another typo in the file that I figured I may as well fix while I was there.
If applicable:

Fix typo in templating language example

---

CHANGELOG.md
cli/src/commands/git/clone.rs
cli/src/commands/git/fetch.rs
cli/src/commands/git/push.rs
cli/src/git_util.rs
cli/tests/test_git_fetch.rs
lib/src/git.rs
lib/tests/test_git.rs

Make the new GitFetch api public.
- Move git::fetch to lib/tests/test_git.rs as git_fetch, to minimize churn in the tests. Update test call sites to use git_fetch
- Delete the git::fetch from lib/src/git.rs.
- Update jj git clone and git_fetch in cli/src/git_utils.rs to use the new api directly. Removing one redundant layer of indirection.
- This fixes https://github.com/jj-vcs/jj/issues/4920 as it first fetches from all remotes before import_refs() is called, so there is no race condition if the same commit is treated differently in different remotes specified in the same command.
Original commit by @essiene https://github.com/jj-vcs/jj/pull/4960
If applicable:

git: update jj git clone|fetch to use new GitFetch api directly

---

cli/src/commands/git/clone.rs
cli/src/commands/git/fetch.rs
cli/src/commands/git/push.rs
cli/src/git_util.rs
lib/src/git.rs
lib/src/git_subprocess.rs

Git remotes can send messages on fetch/push. 
A pressing example is Github, which sends a URL to open a Pull Request when a branch is pushed.
This PR implements forwarding these messages to the UI (via the pre-existing `RemoteCalbacks`) from the `git` subprocess.
Since this depends on the remote sending the message, it is hard to test this. The following script is a way to verify that the `remote: ` messages are being reported:
```zsh
USER="bsdinis"
REPO="jj"
cargo build
JJ=$(readlink -f './target/debug/jj')
dir=$(mktemp -d)
pushd $dir
jj git clone git@github.com:${USER}/${REPO} || rm -rf $dir
pushd jj
touch a
$JJ describe -m "x"
$JJ status
$JJ log
$JJ --config="git.subprocess = true" git push -c @ || rm -rf $dir
rm -rf $dir
```

git: forward remote messages to output

---

.config/nextest.toml
.github/workflows/build.yml
flake.nix

Also includes an extra tidbit to track down slow tests in CI.
If applicable:

Build Nix flake checks in `test` mode

---

docs/conflicts.md

The meaning of `[noeol]` might not be immediately clear to a user, so it would be good to document it on our documentation page for conflicts. We may also want to improve the conflict marker comments we use for this case in the future (possibly after receiving user feedback).
Follow up to #5186.
If applicable:

docs: explain `[noeol]` conflict marker comment

---

CHANGELOG.md
cli/src/commands/git/mod.rs
cli/tests/test_git_clone.rs
lib/src/dsl_util.rs
lib/src/revset.rs
lib/src/revset_parser.rs

escape bookmark and remote names in `trunk()` config

---

lib/tests/test_git.rs
lib/tests/test_rewrite.rs
lib/tests/test_rewrite_transform.rs

When we don't need a mutable reference, we should be using `repo()`.
If applicable:

cleanup: prefer `MutableRepo::repo()` over `repo_mut()`

---

cli/src/config-schema.json
docs/config.md

This option was introduced in #4283, but was not documented apart from `prev` and `next`'s help text on the --edit/--no-edit flags.
If applicable:

docs: document the ui.movement.edit config option

---

docs/conflicts.md
lib/src/conflicts.rs
lib/tests/test_conflicts.rs

Suggested by @arxanas in https://github.com/jj-vcs/jj/pull/5497#pullrequestreview-2582188101
If applicable:

conflicts: use clearer wording for missing newline comment

---

cli/src/git_util.rs

cli: move cursor to first column after printing git progress bar

---

cli/src/git_util.rs
lib/src/git_subprocess.rs

git: show fetch progress with `git.subprocess = true`

---

cli/src/cli_util.rs
cli/src/complete.rs
cli/src/ui.rs

Example of how it looked like in fish when a warning was printed during completion:
If applicable:

Use null `Ui` in completion to prevent writing warnings into completions

---

cli/src/cli_util.rs
cli/src/commands/bookmark/list.rs
cli/src/commands/config/list.rs
cli/src/commands/evolog.rs
cli/src/commands/log.rs
cli/src/commands/operation/log.rs
cli/src/commands/show.rs
cli/src/commands/tag.rs
cli/src/complete.rs
cli/tests/test_completion.rs

based on #5539 
It would be nice to filter them down to only applicable ones, but I don't think that type information is present in the toml definitions.
If applicable:

cli: complete: complete `-T` template aliases

---

cli/src/commands/git/clone.rs
lib/src/git.rs
lib/tests/test_git.rs

git: split function that queries remote default branch, call only when needed

---

docs/git-comparison.md
docs/tutorial.md

`jj amend` is discouraged and no longer a visible alias of `jj squash` since 6d78d92. This is the only remaining occurrence of it in the docs. We should recommend using `jj squash` directly instead.
If applicable:

docs: remove references to `jj amend`

---

docs/FAQ.md
docs/config.md
docs/conflicts.md
docs/filesets.md
docs/install-and-setup.md
docs/revsets.md
docs/tutorial.md

docs: add language identifiers to code blocks to improve syntax highlighting

---

pyproject.toml

We've been using `uv 0.4` syntax, but we only support `uv` 0.5.1+. The newer `uv 0.5` syntax follows an approved PEP, and the older syntax will probably be removed at some point.
The CI verifies that this works with uv 0.5.1.

pyproject.toml: update to newer syntax

---

cli/src/commands/squash.rs
cli/src/commands/unsquash.rs
cli/src/description_util.rs
cli/tests/test_squash_command.rs
lib/src/rewrite.rs

squash: use draft description template to generate editor content

---

docs/windows.md

Improve docs on handling line endings on Windows

---

docs/install-and-setup.md

The name `Linuxbrew` is no longer used since Homebrew 2.0.0: https://brew.sh/2019/02/02/homebrew-2.0.0/
If applicable:

docs/install-and-setup: replace `linuxbrew` with `Homebrew`

---

docs/windows.md

The only usage of this link was removed in 2d0b715.
If applicable:

docs/windows: remove unused link

---

CHANGELOG.md
cli/src/template_builder.rs
cli/src/text_util.rs
docs/templates.md

I started out trying to implement a `pad_between` function as suggested on the feature request, but got bogged down because all of the template wrapping expects a single content argument. If you think it's still worth pursuing that approach, I can spend Monday working on it, but I thought it might be more useful to get a simpler fix out faster.
Fixes #5066.
If applicable:

templater: add pad_center template function

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/config/misc.toml
cli/src/ui.rs
docs/config.md

I've been going back and forth on naming of the `alternate-screen` option. It has many subtle effects that seem hard to describe without thinking of the alternate screen (e.g. if we call it `clear-screen`), at least if we want to allow the `if-long-or-slow` behavior. If we are OK with forbidding it, we could have a simple `quit-if-one-page` boolean, but I think it might just be useful enough to keep.
Streampager's naming of the corresponding [`interface_mode` option](https://github.com/facebook/sapling/blob/0280ed4ab533abbaa4836abc0854b66ac13a10fa/eden/scm/lib/third-party/streampager/src/config.rs#L14) seems more confusing to me: the Direct mode seems useless, there are two hybrid modes (one of which is called Hybrid) that are hard to distinguish unless you think in terms of the alternate …

builtin pager: add configuration options, change default options

---

cli/tests/test_git_fetch.rs
lib/src/git_subprocess.rs

git: force git subprocess to not localize error messages

---

docs/config.md
docs/github.md

This is consistent with the rest of the docs.
If applicable:

docs: use styled admonition blocks for warnings

---

docs/install-and-setup.md

It seems that in 38daa9a the 'Cargo Binstall' section should have been inserted above the 'prelease version' sentence instead.
If applicable:

docs/install-and-setup: move 'prerelease version' sentence to after 'Cargo Binstall' section

---

docs/contributing.md

Filing this as a suggestion but can close if it doesn't feel right.
The commit guidelines feel like they're relevant before documentation
about the code review process - they could conceivably apply while
developing a change.
These often seem to get missed and raised during reviews - giving them
their own section may increase visibility.
If applicable:

docs: Split out commit guidelines into their own section

---

cli/src/commands/log.rs
cli/src/commands/squash.rs
cli/tests/test_global_opts.rs
cli/tests/test_log_command.rs
cli/tests/test_squash_command.rs

cli: update "only_path" warnings to say fileset expression instead of path

---

cli/src/config-schema.json

When adding a `"$schema"` to my config, it flagged `backends.ssh.allowed-signers` as boolean. This fixes the type to string and removes the default (as I don't think there is one?).
Let me know if I need to change things anywhere else.
If applicable:

Fix backends.ssh.allowed-signers type in config-schema

---

CHANGELOG.md
cli/tests/test_status_command.rs
lib/src/local_working_copy.rs
lib/tests/test_local_working_copy.rs

local_working_copy: scan directory entries excluded by auto-track pattern

---

.github/workflows/build-binaries.yml
.github/workflows/build-nix.yml
.github/workflows/build.yml
.github/workflows/release.yml

We no longer need to do cross compilation, and these instances seem pretty fast. Enable them everywhere across the board.
If applicable:

github: migrate to GHA aarch64 runners

---

CHANGELOG.md
cli/src/template_builder.rs
cli/src/text_util.rs
docs/templates.md

If an ellipsis arg is given to the truncate_* template functions, append (or prepend) the ellipsis when the template content is truncated to fit the maximum width.
Fixes #5085.
I went with "ellipsis" rather than "tail", because we already use "ellipsis" for the very similar `elide_*` functions in `text_util.rs`.
I did not use the `elide_*` functions directly, because they assume `&str` content, whereas IIUC, templates can be arbitrary bytes.
To determine whether or not the content should be truncated, I followed the example of the `write_padded_*` functions, which lossily convert the template args to strings to check their width; I assume that's OK, but would appreciate a confirmation.
As you can see in some of the tests, the prepended/appended ellipsis is not colored, even when the …

templater: add optional ellipsis arg to truncate template functions

---

lib/src/git_subprocess.rs

git: skip running pre-push hooks when subprocessing to match git2 behaviour

---

cli/src/commands/git/push.rs
cli/tests/cli-reference@.md.snap

Currently, the rendering in
https://jj-vcs.github.io/jj/prerelease/cli-reference/#jj-git-push is incorrect.
Fixup to 5b5a9e7

cli reference: fix `jj git push` link formatting

---

SECURITY.md

The previous "on this page" statement is wrong more often than not. Unfortunately there is no "Report a vulnerability" button on https://github.com/jj-vcs/jj/security/policy, and looking for such a button from https://github.com/jj-vcs/jj?tab=security-ov-file leads to confusion.
This is not the end of the world, but I don't see much security downside to clarifying it (that is, I don't think *not* having a link protects against phishing in any real way).

SECURITY.md: insert an explicit URL

---

CHANGELOG.md
cli/src/commands/operation/undo.rs
cli/tests/test_undo.rs

One common issue that users run into with `jj undo` is that they expect it to behave like an "undo stack", in which every consecutive `jj undo` execution moves the current state further back in history. This is (currently) an incorrect intuition - running multiple `jj undo` commands back-to-back will only result in the previous non-undo change being reverted, then un-reverted, then reverted, and so on.
This change adds a hint when the user runs `jj undo` multiple times consecutively, suggesting that they may be looking for `jj restore`, which allows them to revert the whole state of the repository back to a previous snapshot.
See also #3700
If applicable:

Show a warning when undoing an undo operation

---

cli/src/commands/simplify_parents.rs
lib/src/default_index/composite.rs
lib/src/default_index/mod.rs
lib/src/default_index/mutable.rs
lib/src/default_index/readonly.rs
lib/src/index.rs
lib/src/repo.rs
lib/src/rewrite.rs

index: Return Result from heads

---

.github/scripts/docs-build-deploy
.github/workflows/docs.yml
.github/workflows/release.yml
docs/contributing.md
mkdocs.yml

The main goal here is to make it easier to tell when you are viewing the prerelease docs vs other docs. This makes the prerelease docs have an adjusted header and a metallic grey header instead of the blue header all other docs have.
There is also a refactoring commit that also adjusts the contributing docs somewhat. This can be split into a separate PR, the main reason I put them together is because I wanted to change the convention for how environment variables inside `mkdocs.yml` are named.
Before:
After:
(The dropdown will not change, it's missing below because I used `mkdocs serve`)
Light theme:
See the commit descriptions for more details and thoughts.

docs: label prerelease docs with different title and header color, refactor mkdocs.yml

---

lib/src/repo.rs

The previous name violated the "snake case" convention for variable names. I suspect the intention was to use `RewriteRootCommit` as a type declaration, not the argument name. Since the argument isn't used, we can use an underscore as the name and leave the type declaration.
#cleanup

repo: Change name for unused closure argument

---

cli/src/commands/config/set.rs
cli/tests/cli-reference@.md.snap

cli: describe how to set a config value with apostrophes

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/complete.rs
cli/src/config-schema.json
cli/src/config/misc.toml
cli/tests/test_completion.rs
cli/tests/test_global_opts.rs
cli/tests/test_log_command.rs

The "fileset" language has been enabled by default since v0.20.
If applicable:

cli: remove `ui.allow-filesets` configuration option

---

lib/src/git_subprocess.rs

For further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern
Apparently this got moved to "pedantic" in 1.80, but I ran clippy 1.79 and saw it. Seems harmless to fix though.

cli: Fix single-character string constant used as pattern clippy warning

---

lib/src/repo.rs

See the discussion in #5623. This prevents future accidents if member variables are added to RewriteRootCommit which need to be propagated to EditCommitError during conversion.

repo: Use thiserror #[from] with EditCommitError::RewriteRootCommit

---

CHANGELOG.md
lib/src/ssh_signing.rs

I'm very new to rust so not sure this is the best approach - happy to hear any suggestions. I'll add tests and a changelog entry in a bit.
Fixes #5625
If applicable:

sign: Support ~/ path expansion for allowed-signers

---

cli/tests/test_split_command.rs

When a commit is split, the second commit produced by the split becomes the working copy commit for all workspaces whose working copy commit was the target of the split.
This commit adds two tests for this behavior:
1. Split a commit which is the working copy commit for two workspaces.
2. Split a commit which is the working copy commit for only one of the two workspaces.
These tests check that the working copy commits for the workspaces are updated correctly. Both parallel and non-parallel splits are tested.

cli split: Test how the working copy commit changes across multiple workspaces

---

GOVERNANCE.md
docs/governance/GOVERNANCE.md
mkdocs.yml

After lots of discussion, we've finally achieved a draft of the governance document!
**This is a draft, as it is fundamentally incomplete; that will require the election of the initial set of 5 Jujutsu Maintainers, after an open self-nomination period**! Stay tuned for more on that.
---
This is the result of a lot of back and forth, the weekly efforts of the governance working group, currently consisting of:
- Martin von Zweigbergk (martinvonz)
- Waleed Khan (arxanas)
- Emily Shaffer (nasamuffin)
- Austin Seipp (thoughtpolice; yours truly)
Many thanks as well to emeritus member Khionu Sybiern, who helped kickstart this whole process.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1209241374115307

meta: add initial `GOVERNANCE.md`

---

CHANGELOG.md
cli/src/config-schema.json
cli/tests/test_git_clone.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_push.rs
docs/config.md
lib/src/config/misc.toml
lib/src/settings.rs

Given the previously‐stated intention of making this default for the 0.27 release, prepare for that decision ahead of time by enabling subprocessing by default on trunk. This will help surface any regressions and workflow incompatibilities and therefore give us more information to decide whether to keep or revert this commit, without inconveniencing any users who haven’t already opted in to the bleeding edge.
Please feel free to revert without hesitation if any major issues arise; this is not intended as a strong commitment to enable this option for the next stable release if it turns out to not be ready. In that case, it’s better that we learn that early on in the cycle, rather than having to revert at the last minute or, worse, cutting a stable release that we later find contains a …

git: enable subprocessing by default

---

cli/src/config-schema.json
cli/tests/test_util_command.rs

Fixes #5607 in particular.
This can be thought of as a companion to @steadmon 's #5651.

config-schema.json: fixes to the schema

---

cli/tests/common/git.rs
cli/tests/test_git_init.rs
cli/tests/test_gitignores.rs

Another patch in service of more tests being done with gitoxide.
#5548

cli/tests: migrate more tests from `git2` to `gitoxide`

---

CHANGELOG.md
cli/src/config-schema.json

config-schema: expand options for `ui.editor`, `ui.diff.tool`, and `ui.pager`

---

cli/src/config-schema.json
cli/tests/test_util_command.rs

The fix settings weren't indented consistent with the rest of the settings, causing them to appear in the redacted snapshot in the test_util_config_schema test.

json schema: Fix bad indentation for `jj fix` settings

---

docs/config.md

Removes nonexistent Sublime TOML LSP server link in docs. I looked, but since I wasn't able to find an alternative, I removed the Sublime bit entirely.
Fixes #5664 
If applicable:

Remove broken Sublime LSP TOML reference in config.md

---

lib/src/git.rs

`gix::Repository` instances are larger than 1KB on 64-bit machines. This makes Clippy warn about an unbalance between variants of `GitFetchImpl`: the `Git2` variant requires 8 bytes, while the `Subprocess` variant requires 1128 bytes.
Boxing the `gix::Repository` makes `GitFetchImpl` instances smaller, as well as the other structs embedding them such as `GitFetch`.

git: box `gix::Repository` large instances

---

docs/cli-reference.md
pyproject.toml
uv.lock

It's been about ~~three~~ five months, and it seems best to occasionally try updating. Let's see if this causes any problems.
There was also a minor breaking change to
`mkdocs-include-markdown-plugin`, I added an option to keep the old behavior (which seems nice in this case).
To do these kinds of updates, `uv tree --outdated` is useful.

mkdocs: update mkdocs-material and mkdocs-include-markdown-plugin

---

CHANGELOG.md
cli/src/commands/split.rs
cli/src/config-schema.json
cli/tests/test_split_command.rs

Currently, `jj split` moves bookmarks from the target revision to the second
revision created by the split. Since the first revision inherits the change id
of the target revision, moving the bookmarks to the first revision is less
surprising (i.e. the bookmarks stay with the change id). This no-implicit-move
behavior also aligns with how `jj abandon` drops bookmarks instead of moving
them to the parent revision.
Two releases from now, `jj split` will no longer move bookmarks to the second
revision created by the split. Instead, local bookmarks associated with the
target revision will move to the first revision created by the split (which
inherits the target revision's change id). You can opt out of this change by
setting `split.legacy-bookmark-behavior = true`, but this will likely be …

cli split: Add a config option controlling how bookmarks move during splits

---

docs/contributing.md
docs/paid_contributors.md

This adds a record of all contributing employees of companies who pay for contributions. The purpose is to help make possible conflicts of interest easier to spot. As far as we know, only Google currently pays right now.
If applicable:

docs: record contributors whose employer pays for contributions

---

cli/src/commands/split.rs
cli/tests/test_split_command.rs

It only occurred to me after I rebuilt jj and actually had to run the command that we should probably recommend a change to the user config instead of the repo config.
#3419
If applicable:

cli split: Recommend `jj config set --user` instead of `--repo` in deprecation warning

---

.github/workflows/ci.yml
cli/tests/runner.rs
cli/tests/test_config_schema.rs
flake.nix

An example failure (after intentionally breaking `cli/src/config/windows.toml`) can be found here:
https://github.com/steadmon/jj/actions/runs/13318732695/job/37198937640#step:7:323
If applicable:

config-schema: validate default configs in tests with taplo

---

.github/workflows/binaries.yml
.github/workflows/ci.yml
.github/workflows/dependabot.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/scorecards.yml

This adds a series of changes to the workflow files suggested by the [`zizmor`](https://woodruffw.github.io/zizmor/) tool, an automated security scanner for GitHub Actions Workflows. At the very end, it also adds a new workflow which will automatically run `zizmor` on all changes going forward.
Context: there was [a recent compromise of a very popular pypi package named `ultralytics`](https://blog.yossarian.net/2024/12/06/zizmor-ultralytics-injection) that occurred due to template injection through a pushed tag. GHA has also had a long string of security vulnerabilities
---
Almost all of the suggested changes were low-priority, related to:
1) Overly broad permissions (we granted `read-all` when we either didn't need it, or only needed it for extremely few steps), and
2) Persisting GitHub …

github: scope/narrow permissions, prevent template injection via GHA, enable zizmor workflow

---

CHANGELOG.md
cli/src/commit_templater.rs
cli/tests/test_bookmark_command.rs
lib/src/commit.rs
lib/src/repo.rs
lib/tests/test_mut_repo.rs

This was [discussed in Discord][dc] a while ago,  and this is the logical and consistent
conclusion. Implementing it as such makes it consistent with both `jj edit` and `jj new`
which unhide any predecessor.
If applicable:
[dc]: https://discord.com/channels/968932220549103686/968932220549103689/1298729954670022676

bookmark: Make `bookmark {create, set, move}` unhide hidden commits

---

cli/src/commands/fix.rs

https://discord.com/channels/968932220549103686/1339741938324340927/1339741938324340927
There's currently no way to tell what `jj fix` is doing. This adds some traces such that `jj fix --debug` will at least tell you what's being run and what it's exit code is, similar to other subprocessing code.
If applicable:

fix: add simple debugging logs

---

CHANGELOG.md
cli/src/commands/file/annotate.rs
cli/src/commit_templater.rs
cli/src/config/templates.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_file_annotate_command.rs
docs/templates.md

Discord discussion: https://discord.com/channels/968932220549103686/1337969561793990757
Allows:
* self.commit()
* self.line_number()
* self.first_line_in_hunk()
Certain pagers (like `delta`), when used for `git blame`, only show the
commit information for the first line in a hunk. This would be a nice
addition to `jj file annotate`.
`jj file annotate` already uses a template to control the rendering of
commit information --- `templates.annotate_commit_summary`. Instead of
a custom CLI flag, the tools necessary to do this should be available in
the template language.
If `1 % 2` or `1.is_even()` was available in the template language, this
would also allow alternating colors (using `raw_escape_sequence`).
Example:
```toml
[templates]
annotate_commit_summary = '''
if(first_line_in_hunk, …
```

annotate: make AnnotationLine template type

---

CHANGELOG.md
cli/src/commands/split.rs
cli/src/config/misc.toml
cli/tests/test_split_command.rs

After even more discussion on Discord, we decided to use the new bookmark behavior immediately and only print a warning during `jj split` if the user has opted out of the new behavior using the `split.legacy-bookmark-behavior` config setting.
The reasoning is that if the behavior change breaks someone's workflow or is very disruptive, they are likely to check the changelog and learn about the config option. For users that are not adversely impacted, printing a warning that can only be silenced by changing their config is also disruptive.
#3419
If applicable:

cli split: Move bookmarks to the first commit instead of the second

---

CHANGELOG.md
cli/src/config/templates.toml
docs/config.md

Same as `format_short_change_id`.
We can't use `format_short_id` because `operation.id()` does not have `shortest()` method.
If applicable:

templates: add hook points for users to customize the default operation id

---

CHANGELOG.md
cli/src/commands/bookmark/delete.rs
cli/src/commands/bookmark/forget.rs
cli/src/commands/bookmark/untrack.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_bookmark_command.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_push.rs

Fixes #5524. This solution was suggested by @yuja in #5546.
If applicable:

cli: untrack remote bookmarks on `bookmark forget`

---

cli/src/cli_util.rs
cli/src/commands/file/track.rs
cli/src/commands/file/untrack.rs
cli/tests/test_working_copy.rs

Fixes #5718
This is one of the proposed fixes, the other option needs more discussion I think.
If applicable:

working_copy: adjust max-size hint to fit all configurations

---

docs/templates.md

I find myself going to this page and ending up wanting to see the list of templates in `templates.toml`.
If applicable:

docs templates: add link to templates toml file

---

cli/src/command_error.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_push.rs
cli/tests/test_git_remotes.rs
lib/src/git.rs

Although this behaviour is accepted by git, it's a degenerate case. Especially because we implicitely rely on being able to parse out the remote from the refname (i.e., `refs/remotes/<remote>/<branch>`).
Branches can have forward slashes, but if remotes can also have them, parsing the refname becomes ambiguous, and a pain. Especially because it would be totally legal to have a branch "c" on remote "a/b" and a branch "b" on remote "a".
Fixes #5731
If applicable:

git: reject remotes with forward slashes

---

lib/src/git_subprocess.rs

This makes the fetch invisible to other people, which seems to improve the experience with tools like visual jj.

git: pass --no-write-fetch-head to `git`

---

cli/src/command_error.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_remotes.rs

Existing hint suggests using `jj git remote rename`, but that's not applicable to `jj git clone`.
This commit removes that hint
If applicable:

cli: remove error hint for invalid remote names

---

lib/src/git_subprocess.rs

git: remove --bare flag from git commands

---

CHANGELOG.md

This was originally a deprecation until we made it the default behavior in https://github.com/jj-vcs/jj/pull/5697. Since the default behavior has changed, we should list this a breaking change.

changelog: Move `jj split` working copy change to "breaking changes"

---

cli/tests/common/test_environment.rs
cli/tests/test_global_opts.rs

tests: add helper to snapshot command output and exit status all at once

---

cli/tests/test_bookmark_command.rs

An in-flight PR snuck in another git2 usage, moved to gitoxide
If applicable:

cli/tests: move bookmark_command test to gitoxide

---

cli/src/cli_util.rs
cli/src/commands/file/track.rs
cli/src/commands/file/untrack.rs
cli/src/commands/status.rs
cli/src/commands/workspace/update_stale.rs
cli/tests/test_working_copy.rs

Since every command first runs an automatic snapshot, we don't need to explicitly snapshot a file that would've been matched by the auto-matcher previously. This would in some cases lead to double hints being printed (see snapshot test case).
This is a quick followup to https://github.com/jj-vcs/jj/pull/5722#discussion_r1958525279
If applicable:

track: only print snapshot stats and hints once

---

lib/tests/test_git.rs
lib/tests/test_init.rs

As per #5548, this moves the majority of the tests in lib/test over to gitoxide
If applicable:

lib/tests: port lib tests to gitoxide

---

cli/src/cli_util.rs
cli/tests/test_alias.rs

Aliases and `ui.default-command` are loaded before `--config` and `--config-file` arguments are parsed (#5282).
There is supposed to be a warning when the result of these arguments would change the parsed args: #5286.
However, that warning was not being printed if the arguments failed to parse due to an unrecognized subcommand. Example:
```bash
$ jj --config ui.default-command=nonsense
Warning: Command aliases cannot be loaded from -R/--repository path or --config/--config-file arguments.
$ jj --config aliases.some-alias=nonsense some-alias
error: unrecognized subcommand 'some-alias'
$ jj --config aliases.some-alias=nonsense some-alias
Warning: Command aliases cannot be loaded from -R/--repository path or --config/--config-file arguments.
error: unrecognized subcommand 'some-alias'
```
If …

cli: warn when command differs after --config, including when subcommand not found

---

CHANGELOG.md
cli/src/commands/fix.rs
cli/tests/test_fix_command.rs

Motivating discord discussion: https://discord.com/channels/968932220549103686/1339369275915501599
Previously, tools invoked by `jj fix` did not have their `.current_dir()` set, and would just run from whatever directory the user was in.
Now, the tools will always be invoked from the same directory that `jj root` gives.
As a motivating example, consider a configuration path that's always at the workspace root:
```toml
[fix.tools.something]
command = ["cmd", "--config", "$root/tool.toml"]
command = ["cmd", "--config", "./tool.toml"]
```
If applicable:

fix: invoke tools from the workspace root

---

CHANGELOG.md
cli/src/cli_util.rs
cli/tests/test_absorb_command.rs
cli/tests/test_fix_command.rs
cli/tests/test_immutable_commits.rs
docs/config.md

There have been a number of users confused about why their commits are immutable, or what to do about it, ex. #5659.
Separately, I feel that the cli is too quick to suggest `--ignore-immutable`, without context of the consequences. A new user could see that the command is failing, see a helpful hint to make it not fail, apply it and move on. This has wildly different consequences, from `jj squash --into someone_elses_branch@origin` rewriting a single commit, to `jj edit 'root()+'` rewriting your entire history.
This commit does two things for any commit that suggests `--ignore-immutable`:
* Adds a short description of what immutable commits are, and a link to the relevant docs, to the hint message.
* Shows the number of immutable commits that would be rewritten if passed.
If applicable:

cli: improve hint message when suggesting `--ignore-immutable`

---

.github/workflows/scorecards.yml

In https://github.com/jj-vcs/jj/actions/runs/13490171888, we got this error:
```
Invalid workflow file: .github/workflows/scorecards.yml#L48
The workflow is not valid. .github/workflows/scorecards.yml (Line: 48, Col: 9): Unexpected value 'permissions'
```
It looks like permissions can be set per job but not per step, so I moved the permission setting to the job level.
If applicable:

github: fix invalid permission settings for scorecards workflow

---

CHANGELOG.md
cli/src/commands/mod.rs
cli/src/commands/sign.rs
cli/src/commands/unsign.rs
cli/tests/cli-reference@.md.snap
cli/tests/runner.rs
cli/tests/test_immutable_commits.rs
cli/tests/test_sign_command.rs
cli/tests/test_sign_unsign_commands.rs
docs/config.md

Implement `jj sign` and `jj unsign` commands

---

.github/workflows/docs.yml
.github/workflows/release.yml

(See also the commit description)
Some notes:
- I'm not sure whether the env var should be `GH_PAGES` or `GITHUB_PAGES`, but several places in the docs suggested using the former. We can try this as is, or we can set both.
- It bothers me that there is no easy way I can think of to test these things after 514a009, or to experiment with it outside of production. WDYT, @thoughtpolice ?
Sample error: https://github.com/jj-vcs/jj/actions/runs/13548628896/job/37866477622

docs workflow: try to fix it again

---

.github/workflows/docs.yml
.github/workflows/release.yml

See commit description for more.
cc @thoughtpolice @neongreen @martinvonz
See https://github.com/jj-vcs/jj/actions/runs/13559508098/job/37899985506 . The `GH_PAGES` variable is populated, but we get the same error.

docs workflow: try to fix it a third time

---

README.md
cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/commands/bookmark/list.rs
cli/src/commands/bookmark/mod.rs
cli/src/commands/config/list.rs
cli/src/commands/config/mod.rs
cli/src/commands/evolog.rs
cli/src/commands/file/annotate.rs
cli/src/commands/file/list.rs
cli/src/commands/log.rs
cli/src/commands/operation/log.rs
cli/src/commands/show.rs
cli/src/commands/tag.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_alias.rs
cli/tests/test_bookmark_command.rs
cli/tests/test_commit_template.rs
cli/tests/test_config_command.rs
cli/tests/test_fix_command.rs
cli/tests/test_git_clone.rs
cli/tests/test_global_opts.rs
cli/tests/test_immutable_commits.rs
cli/tests/test_log_command.rs
cli/tests/test_revset_output.rs
cli/tests/test_working_copy.rs

Relates to #5306
I wasn't aware that `jj help -k <keyword>` exists.
If applicable:

docs: Add pointers to usage of `jj help -k <keyword>`

---

CHANGELOG.md
cli/src/commands/sign.rs
cli/src/config-schema.json
cli/src/config/revsets.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_sign_unsign_commands.rs

Add default revisions for `jj sign`

---

cli/src/command_error.rs
cli/src/commands/bookmark/create.rs
cli/src/commands/bookmark/rename.rs
cli/src/commands/bookmark/set.rs
cli/src/revset_util.rs
cli/tests/test_bookmark_command.rs
lib/src/revset.rs
lib/src/revset_parser.rs

cli: provide better hint on bookmark name parse error

---

cli/src/commands/split.rs

This has bothered me for a while... It's useful to describe the target of the split command as the "target commit", and it's a little confusing to have a variable named "commit" in the code when we are dealing with several different commits in the command.
I think this improves readability by being more precise.

cli split: Rename the "commit" variable to "target_commit"

---

CHANGELOG.md
cli/src/commands/split.rs
cli/src/config/misc.toml
cli/tests/test_split_command.rs

The consensus about this change, if one ever existed, seems to have dissolved into two cohorts, one which is happy with the change, and one which thinks we should move both the bookmark and change id to the child commit instead of leaving them on the parent.
We may decide to add flags to allow users to choose between the two behaviors, but there are also other concerns such as where @ should go (parent or child). Until we agree on a path forward it seems reasonable to delay the breaking change by disabling it via the config option we added. I don't think it's necessary to fully revert the code and new tests since we aren't announcing the option.
#3419
If applicable:

Disable the new bookmark behavior for `jj split`

---

lib/src/git.rs
lib/src/git_backend.rs

git: use gix::ObjectId::from_bytes_or_panic() consistently

---

cli/src/cli_util.rs
cli/src/commands/duplicate.rs
cli/src/commands/new.rs
cli/src/commands/rebase.rs
cli/tests/test_new_command.rs

This will be used to compute the location to place commits from the
`--destination`, `--insert-after`, and `--insert-before` options. This
is used across the `new`, `duplicate`, and `rebase` commands, and can be
used for further commands as well.
If applicable:

cli_util: extract shared `compute_commit_location` function

---

cli/tests/test_git_clone.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_init.rs
cli/tests/test_git_push.rs
cli/tests/test_git_remotes.rs
cli/tests/test_undo.rs
lib/tests/test_git.rs
lib/testutils/src/git.rs

As per #5548, this concludes the port of the current tests to gitoxide.
If applicable:

cli/tests: move remaining tests to gitoxide

---

cli/src/commands/debug/init_local.rs
cli/src/config-schema.json
cli/src/config/misc.toml
cli/tests/test_debug_init_local_command.rs
demos/demo_juggle_conflicts.sh

Not sure whether I should merge this before or after the release, feel free to tell me.
---------------
It is not needed to gate `jj debug init-local` on an option now that the command is no longer called `jj init`.
This also includes a separate fixup to #5845 in demos/
If applicable:

debug init-local: fixups, docs,remove the `ui.allow-init-native` option

---

cli/src/commands/split.rs
cli/src/commands/squash.rs
lib/src/rewrite.rs

This change moves the code for prompting the user to select changes for the first commit to a helper function. There are no functional changes.
Resulting from the discussion in https://github.com/jj-vcs/jj/pull/5828 we are planning to add several new flags (-B, -A, and -d) to jj split.
Since this may change how the user selects changes (i.e. they may select changes to remove from the target commit, rather than what stays in the target commit), I want to move the selection logic to a function to make the main split function more readable.
If applicable:

cli split: Refactor and move tree selection to a function

---

cli/src/command_error.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_push.rs
lib/src/git.rs

git: reject reserved remote name early in fetch() function

---

deny.toml
pyproject.toml

The paste crate hasn't had a maintainer since Oct. 2024. We don't use it directly, but it's used by ratatui, and there's no direct replacement for it AFAIK.
Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0436
This is currently blocking PRs because ci fails:
```
error[unmaintained]: paste - no longer maintained
┌─ /github/workspace/Cargo.lock:262:1
│
262 │ paste 1.0.15 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
│
├ ID: RUSTSEC-2024-0436
├ Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0436
├ The creator of the crate `paste` has stated in the [`README.md`](https://github.com/dtolnay/paste/blob/master/README.md) 
that this project is not longer maintained as well as …
```

cargo-deny: Ignore paste crate deprecation

---

CHANGELOG.md
cli/src/commit_templater.rs
cli/src/config/colors.toml
cli/tests/test_revset_output.rs
cli/tests/test_templater.rs
lib/src/revset.rs

revset, templater: remove deprecated "branches" aliases, etc.

---

cli/src/complete.rs
cli/src/diff_util.rs
cli/src/progress.rs
cli/src/revset_util.rs
cli/src/template_builder.rs
cli/src/templater.rs
cli/src/ui.rs
lib/src/commit.rs
lib/src/conflicts.rs
lib/src/copies.rs
lib/src/default_index/composite.rs
lib/src/default_index/entry.rs
lib/src/default_index/readonly.rs
lib/src/default_index/revset_engine.rs
lib/src/diff.rs
lib/src/dsl_util.rs
lib/src/local_working_copy.rs
lib/src/matchers.rs
lib/src/merged_tree.rs
lib/src/op_walk.rs
lib/src/operation.rs
lib/src/revset.rs
lib/src/str_util.rs
lib/src/view.rs
lib/tests/test_annotate.rs

cleanup: switch to use<'_> capturing syntax

---

CHANGELOG.md
cli/src/commands/operation/log.rs
cli/tests/cli-reference@.md.snap

`--op-diff` is often more useful than `-p`/`--patch`.
If applicable:
- ~~[ ] I have updated the documentation (README.md, docs/, demos/)~~
- ~~[ ] I have updated the config schema (cli/src/config-schema.json)~~
- ~~[ ] I have added tests to cover my changes~~

cli `op log`: short `-d` alias for `--op-diff`

---

cli/src/commands/debug/copy_detection.rs

It looks like the help text was copied from another command and not updated.
If applicable:

cli: debug copy-detection: fix help text

---

Cargo.lock
Cargo.toml

Revival of https://github.com/jj-vcs/jj/pull/5315. We have the necessary version in Nixpkgs now, and it looks like Arch does as well.
cc @demize for Gentoo
If applicable:

cargo: bump git2 to 0.20.0

---

cli/src/config-schema.json

Hello!
The docs show that the diff-editor, and merge-editor settings
can be a string or an array of strings. This updates the config
schema to reflect that.
Thanks!
If applicable:

config: update diff-editor and merge-editor schema

---

cli/src/command_error.rs
cli/src/commands/git/clone.rs
cli/src/commands/git/init.rs
cli/src/commands/git/remote/add.rs
cli/src/commands/git/remote/remove.rs
cli/src/commands/git/remote/rename.rs
cli/src/commands/git/remote/set_url.rs
cli/src/git_util.rs
cli/tests/test_git_remotes.rs
lib/src/git.rs
lib/tests/test_git.rs

(Plus one more change to remove the other remaining `git_util::get_git_repo` caller.)
I’m not wholly confident in the first commit here, but the rest should hopefully be good. It feels like there might be awkward race conditions in here but I think Git is just like that.
@Byron 👋 I thought you might be interested in some API UX feedback I came up with while working on this. If you’d like me to open issues/discussions on the `gix` side for any of these please let me know.
* It’s awkward that `gix::Remote::save_to` handles the fussy details of removing the other sections for that remote from the config, but leaves you to reimplement it yourself if you need it in any other context. It would be nice if the removal logic was exposed separately, or perhaps if there was a specific way to tell …

git: port remote management to `gix`

---

lib/src/revset.rs

It became unused in 75605e36.
If applicable:

revset: remove unused lifetime parameter from RevsetIteratorExt

---

CHANGELOG.md
cli/src/commands/bookmark/move.rs
cli/tests/cli-reference@.md.snap

Hello!
If `--to` is going to become a required argument, it should have a short alias as it will be used quite frequently.
Additionally, I would argue in favor of using `-f` for `--from`, given that is it used for other commands and we should be consistent (if users can use `-f` as an alias for `--from` on other commands then logically they would assume they can use it for this one). Not allowing it because users might mistake it to mean `--force` isn't that big of a concern in my book given that `--force` is not used as an option anywhere else (as far as I am aware) and the option requires an argument so it will fail even if a user does try to use it for such a purpose.
If this is acceptable then I can send a follow up PR to add the alias for `--from` (or edit the current commit). …

cli: bookmark move: allow short aliases for `--to`/`--from`

---

docs/FAQ.md

The FAQ entry explaining why `jj log` doesn't show all commits explained that the behavior is configurable but it didn't explain what the rationale for not showing all commits is. Users coming from Git are used to seeing all commits and probably read this FAQ entry to find an answer. We don't want them to just update their config without understanding why we have the default we have.
If applicable:

faq: in entry about default `jj log` revset, explain rationale

---

cli/src/git_util.rs
cli/tests/test_git_import_export.rs
lib/src/git.rs
lib/tests/test_git.rs

git: use translated remote symbols in import_refs()

---

cli/src/command_error.rs
cli/tests/test_bookmark_command.rs
cli/tests/test_commit_template.rs
cli/tests/test_revset_output.rs

This is the first commit from https://github.com/jj-vcs/jj/pull/5944.

revset globs: explain case-insensitive string prefixes

---

cli/src/cli_util.rs
cli/tests/test_alias.rs

As an aside, I didn't touch `revert` to avoid conflicts with https://github.com/jj-vcs/jj/pull/5932.
If applicable:
- ~~[ ] I have updated `CHANGELOG.md`~~
- ~~[ ] I have updated the documentation (README.md, docs/, demos/)~~
- ~~[ ] I have updated the config schema (cli/src/config-schema.json)~~

cli clone and init: remove unhelpful parts of clap error 

---

CHANGELOG.md
cli/src/diff_util.rs
cli/tests/test_log_command.rs

diff: fix inconsistent handling of "short" format arguments

---

cli/src/config.rs
cli/src/config/misc.toml
cli/src/diff_util.rs

cli: emit warning for deprecated diff.format, move default to config/misc.toml

---

CHANGELOG.md
cli/src/commands/config/edit.rs
cli/src/commands/config/mod.rs
cli/src/commands/config/set.rs
cli/src/commands/config/unset.rs
cli/tests/common/test_environment.rs
cli/tests/test_config_command.rs
lib/src/config.rs

Hello!
This allows the user to select a particular file when using multiple configs. In the event that a prompt cannot be displayed, the first file will be automatically selected.
This is part of my work on #5971 but was relatively independent so decided to send it.
Thanks!
If applicable:

cli: config {edit,set,unset}: prompt when multiple files exist

---

CHANGELOG.md
cli/src/commands/config/list.rs
cli/src/config.rs
cli/src/config/colors.toml
cli/src/config/templates.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_completion.rs
cli/tests/test_config_command.rs
cli/tests/test_evolog_command.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
cli/tests/test_show_command.rs
cli/tests/test_templater.rs
docs/config.md
lib/src/config.rs

Hello!
This adds the config origin to the end of the line for each config value in the list.
Options coming from files will show the file path.
Thanks!
Closes #1047
If applicable:

cli: config list: show origin of config values

---

cli/tests/test_git_push.rs
lib/src/git.rs
lib/src/git_subprocess.rs

When we push a ref to a git remote, we use `--force-with-lease`
Our understanding was that this could fail iff the expected location of
the ref on the remote was not that of the local tracking ref
However, if the ref is from a protected branch (e.g., main) it will be
rejected by the remote for a different reason.
This commit solves this, by detecting this difference.
If applicable:

git: properly detect remote refusal on push

---

cli/src/config/templates.toml

For `builtin_log_compact` you can specify how you want signatures to be displayed via `format_short_signature`, but the same wasn't possible for `builtin_log_compact_oneline` which always chose `email().local()`.
Is this worth a changelog entry? 
If applicable:

templates: expose `format_short_signature_oneline` template alias hook

---

.github/workflows/ci.yml

Whoops.
https://docs.github.com/en/webhooks/webhook-events-and-payloads#merge_group
If applicable:

github: fix `ci` workflow concurrency setting in the queue

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/commands/config/list.rs
cli/src/commands/config/mod.rs
cli/src/commands/config/path.rs
cli/src/commands/config/set.rs
cli/src/commands/config/unset.rs
cli/src/complete.rs
cli/src/config.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_config_command.rs
docs/config.md

~~The `platform_config_path` now defaults to the `jj` directory as opposed to the `config.toml` file. This loads all configuration files in the directory by default, removing the need to set JJ_CONFIG for a multi-file approach.~~
Multiple user configs are now supported and are loaded in the following precedence order:
- `$HOME/.jjconfig.toml`
- `$XDG_CONFIG_HOME/jj/config.toml`
- `$XDG_CONFIG_HOME/jj/conf.d/*.toml`
which removes the need to set `JJ_CONFIG` for a multi-file approach.
Later files override earlier files and the `JJ_CONFIG` environment
variable can be used to override the default paths.
The `JJ_CONFIG` environment variable can now contain multiple paths separated
by a colon (or semicolon on Windows).
Thanks!
If applicable:

cli: config: support multiple user configuration files

---

cli/tests/test_config_command.rs
lib/src/config.rs

This helps avoid loading errors should the JJ_CONFIG environment variable be set to a directory that
contains other file types.
If applicable:

config: only load toml files in a directory

---

CHANGELOG.md
docs/config.md
lib/src/gpg_signing.rs
lib/tests/test_gpg.rs

If a signing key is not configured, the user's email will be used as the signing key. This aligns with `git`'s behavior and allows the users to not have to specify the key in their configs given that they have a key associated with their email.
Thanks!
If applicable:

sign: gpg: automatically use user email as signing key

---

cli/src/cli_util.rs
docs/contributing.md

The current behaviour means (transitively) dependent crates' debug logs end up
in our logs when `--debug` is active.
The biggest offender here is `globset`, imported from the `ignore
crate`. These logs are extremely noisy and mostly irrelevant from our usecase.
This commit changes this behaviour to whitelist `jj` related debug logs,
while allowing more debugging to come from env vars

cli: change debug logging behaviour to whitelist `jj` crates 

---

docs/config.md

cc @calebdw, @algmyr if you are interested
Screenshot of `uv run mkdocs serve`, in case it helps (without opening the info block) (**Update:** the screenshot is a bit obsolete):

config docs: touch up platform-specific config location docs

---

.github/workflows/ci.yml
Cargo.toml
cli/Cargo.toml
cli/src/command_error.rs
cli/src/config.rs
cli/tests/common/test_environment.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_push.rs
lib/Cargo.toml
lib/src/git.rs
lib/src/git_backend.rs
lib/src/lib.rs
lib/src/settings.rs
lib/tests/test_git.rs
lib/testutils/Cargo.toml
lib/testutils/src/lib.rs

This helps us prepare for removing the functionality down the line and makes things easier for people building or packaging their own Jujutsu.
If applicable:

git: make `git2` support optional

---

cli/src/command_error.rs
cli/src/commands/fix.rs
lib/src/fix.rs
lib/src/lib.rs
lib/tests/runner.rs
lib/tests/test_fix.rs

* The lib part should not deal with tools, or tool config, or running stuff in subprocesses. That stays in the CLI.
* Adds a fix_files function. This is the entry point.
* Adds a FileFixer trait with a single method to process a set of files. This is a high-level plugin point.
* Adds a ParallelFileFixer which implements the FileFixer trait and invokes a function to fix one file a time, in parallel.
* The CLI uses ParallelFileFixer.
If applicable:

Refactor jj fix CLI, move some logic to lib to make it usable elsewhere.

---

CHANGELOG.md
Cargo.lock
Cargo.toml
cli/src/merge_tools/builtin.rs

Extends https://github.com/jj-vcs/jj/pull/4078 but with a slightly different approach based on a discussion in Discord: https://discord.com/channels/968932220549103686/1325114717387100201
It relies on changes in https://github.com/arxanas/scm-record/pull/93 to function.
The code in this area gets significantly simpler, since there's no longer any ambiguity to resolve. The `scm-record` changes expect that any mode changes are represented by file mode sections, and adds UI hooks to simplify working with them (e.g. automatically de-selecting a deletion mode change if any lines in the file are de-selected, since the file still needs to exist to hold those lines).
As a result, mode changes always come back from `scm-record` as a `FileModeTransition` and we can handle them explicitly. 'No …

Allow deleting files in diffedit and split

---

lib/src/absorb.rs
lib/src/annotate.rs
lib/tests/test_annotate.rs

Suppose we add "jj file annotate" option to specify the search domain or depth, the root commit within the range can be displayed as the boundary commit. "git blame" for example displays boundary commits with ^ prefix.
If applicable:

annotate: report root commit id if no origin found within range

---

.github/actions/setup-windows/action.yml
.github/workflows/ci.yml

Fixes a one to two minute CI speed regression from https://github.com/jj-vcs/jj/pull/5956, and shaves another couple minutes off the Windows build. I’ll leave the GnuPG hack commit in here to demonstrate that it works in CI and remove it after this is approved. (https://github.com/jj-vcs/jj/pull/5854 is the longer‐term solution and we should land it.)
More ambitious wins to come, but these are really simple and should get the Windows build down from ~16 minutes to ~13. I’ve left the empty `setup-windows` action because I plan to put more stuff back in it.
If applicable:

github: simple CI speed‐ups

---

docs/install-and-setup.md

To avoid redundant computation, users who run `COMPLETE=fish jj | source`
in their ~/.config/fish/config.fish should eventually remove that, or move it
to ~/.config/fish/completions/jj.fish which overrides the default completions.
Ref: https://github.com/fish-shell/fish-shell/pull/11046

docs: fish shell enables completions by default

---

cli/tests/test_config_schema.rs
lib/tests/test_gpg.rs
lib/testutils/src/lib.rs

Fixes #5696
Example failure: https://github.com/jj-vcs/jj/actions/runs/13611152082/job/38048476201?pr=5854#step:7:1543
(This can wait; since the CI passes on the PR, we know the problem this PR aims to detect is not occurring, at least at the commit the PR is synced to).

ci: make sure tests fail in CI if `gpg` or `taplo` binaries are not found

---

lib/src/git.rs
lib/src/git_subprocess.rs

In recent bugs, it's been really hard to triage the behaviour from the existing debug logs.
In particular, there have been situations where the `git` command is not enough to triage, because the bug stems from a particular environment/config issue. Moreover, these bugs are either transient, and as such hard to replicate, or they only manifest when spawning `git` from `jj` (and as such re-running the `git` command does not yield useful information).
In those cases, seeing what the subprocessing code is seeing becomes very much useful. This commit adds some debug logging to help with this problem.
If applicable:

git: add more targetted debug logging for subprocess code

---

lib/src/repo.rs

repo: suppress warning about unused SimpleBackend on non-dev build

---

cli/src/commands/git/fetch.rs
lib/src/str_util.rs

Previously, globs were printed extremely verbosely and all the important arguments were repeated twice for no reason.
The two commits are independent, I can split them into separate PRs if one is more controversial than the other.
Running `jj git fetch --remote upstream --branch main  --branch master --branch 'glob:gh-readonly-queue*' --branch 'glob:ig/*' --debug`
Previously:
```
2025-03-18T05:11:35.515812Z  INFO jj_cli::cli_util: debug logging enabled
2025-03-18T05:11:35.528165Z DEBUG run_command:cmd_git_fetch{args=GitFetchArgs { branch: [Exact("main"), Exact("master"), Glob(Pattern { original: "gh-readonly-queue*", tokens: [Char('g'), Char('h'), Char('-'), Char('r'), Char('e'), Char('a'), Char('d'), Char('o'), Char('n'), Char('l'), Char('y'), Char('-'), Char('q'), Char('u'), Char('e'), …
```

Make debug output for StringPatttern::Glob and `jj git fetch --debug` less verbose

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/abandon.rs
cli/src/commands/absorb.rs
cli/src/commands/revert.rs
cli/src/commands/sign.rs
cli/src/commands/unsign.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_abandon_command.rs
cli/tests/test_absorb_command.rs
cli/tests/test_operations.rs

cli: truncate list of updated commits, remove `abandon --summary` flag

---

.github/workflows/ci.yml

This shaves over 3½ minutes off the tests, taking this from the slowest job to faster than Windows again. The macOS 13 builders presumably won’t be around forever, and the newer free builders are all Apple Silicon, but this is an easy substantial improvement for now.
If applicable:

github: use native builder for x86 macOS

---

lib/src/git_subprocess.rs
lib/src/gpg_signing.rs
lib/src/ssh_signing.rs

When used inside GUI application, git.subprocess=true option or enabled signing cause console window to appear temporarily.
std::process::Command needs special flags to prevent that. More details: https://stackoverflow.com/a/60958956
If applicable:

Don't show console on Windows

---

docs/install-and-setup.md

The name «NixOS» doesn't have a space in it.
If applicable:
- (I don't know whether this change is notable enough to warrant an entry there.)
- (This is a docs-only change, so it does update `docs/`. As it doesn't change the behavior of `jj`, not anything substantial about its development, no change to `README.md` or `demos/` is needed.)
- (Probably not needed for this change.)
- (Probably not warranted for this change.)

docs: fix spelling of «NixOS»

---

.github/workflows/dependabot.yml

This might be the cause of dependabot PRs not having automerge. Let's just revert it and see what happens when the next PRs roll in.
This backs out commit 47cd10669de28ecc36f0d7dbbb9964945124b730.
If applicable:

Back out "github: only run `dependabot` workflow on `dependabot/**` branches"

---

cli/src/config/templates.toml
cli/tests/test_completion.rs
cli/tests/test_evolog_command.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
cli/tests/test_show_command.rs
cli/tests/test_templater.rs

This moves the default template to `builtin_draft_commit_description` and points `draft_commit_description` to it. This makes it easier to override the template while still being able to refer to the default.
If applicable:

templates: create `builtin_draft_commit_description` template

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/config/set.rs
cli/src/config.rs
cli/tests/cli-reference@.md.snap
docs/config.md

config: relax bare string rule to accept middle apostrophes, etc.

---

cli/src/git_util.rs
cli/tests/test_bookmark_command.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_import_export.rs
lib/src/git.rs
lib/tests/test_git.rs

git: use translated remote symbols in export_refs(), refactor import_refs()

---

cli/src/cli_util.rs
cli/tests/test_absorb_command.rs
cli/tests/test_diffedit_command.rs
cli/tests/test_file_chmod_command.rs
cli/tests/test_repo_change_report.rs
cli/tests/test_resolve_command.rs
cli/tests/test_restore_command.rs
cli/tests/test_squash_command.rs

cli: do not print commit summary for previously-conflicted commits

---

cli/src/commands/file/show.rs
cli/src/diff_util.rs
cli/src/merge_tools/builtin.rs
lib/src/absorb.rs
lib/src/annotate.rs
lib/src/conflicts.rs
lib/src/default_index/revset_engine.rs
lib/src/local_working_copy.rs

conflicts: pack MaterializedTreeValue::File fields, use read_all() helper

---

cli/src/commands/git/init.rs
lib/src/git.rs

git: replace remaining caller of old parse_git_ref()

---

cli/tests/test_split_command.rs

It wasn't immediately obvious to me what was happening here, but once I understood it it seemed pretty simple. Perhaps it's worth a comment to explain it to the next reader.
If applicable:

cli split: Explain how the diff script works in test_split_interactive_with_paths

---

cli/tests/test_split_command.rs

The name of the flag was changed from --siblings to --parallel a while back, but the tests weren't renamed.
#cleanup
If applicable:

cli split: Rename "siblings" test to "parallel"

---

CHANGELOG.md
cli/src/commands/git/mod.rs
cli/src/commands/git/root.rs
cli/tests/cli-reference@.md.snap
cli/tests/runner.rs
cli/tests/test_git_root.rs

This was discussed briefly in [1], and makes it easier to execute scripts which require a reference to the Git directory.
[1]: https://github.com/jj-vcs/jj/discussions/5767#discussioncomment-12480764
If applicable:

cli: git: add `git root` command

---

lib/src/git_backend.rs
lib/tests/test_git_backend.rs

It is important for this case to be an error, because otherwise it would be possible to construct a non-conflicted commit which appears to have a different tree when viewed using `jj` than when viewed using Git. This could potentially be used to hide malicious code in commits in such a way that on GitHub, the code would appear normal, but it would become malicious when cloned using `jj`.
Prior to f7b14beacc678a9b351ae65224df43a96aa26392, if a commit had a `jj:trees` header with only a single tree, it would result in a panic of "root tree should have been initialized to a legacy id". This commit restores the error behavior by adding an explicit check for this case.
If applicable:

git_backend: don't allow single tree in `jj:trees` header

---

cli/tests/test_split_command.rs

This is to ensure two things:
1. That the evolog isn't missing the history from the target commit.
2. That the evolog doesn't include extra "temporary" commits due to the way `jj split` is implemented.
The impetus for this is the discussion in https://github.com/jj-vcs/jj/pull/5926. The changes added here detect the extra temporary commit added to the evolog when `split --parallel` is run using the implementation in #5926.
If applicable:

cli split: Check the evolog in two tests

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/formatter.rs
docs/config.md

The main goal here is to support formatting comparable to git's [diff-highlight](https://github.com/git/git/tree/master/contrib/diff-highlight). Using RGB colors is admittedly even better, but sadly not all terminals support them, notably macOS's Terminal.app.
I'd like to thank @gechr, as this is heavily based on his work on #5396.
If applicable:

formatter: add support for reversing colors

---

cli/src/command_error.rs
cli/src/commands/git/push.rs
cli/tests/test_git_push.rs
lib/src/git.rs
lib/src/git_subprocess.rs
lib/tests/test_git.rs

We've been finding that a lot of bug reports on `jj git push` come from
sub-standard error reporting on the reasons the failure happens.
It can come from a number of places:
- hook failure
- remote branch protection
- git config
This commit forwards the reason as explained by the ouptut of git push
to help users figure out what is happening.
If applicable:

git: forward rejection reason on push

---

cli/src/config/merge_tools.toml

Cc @scott2000
Now, vimdiff automatically navigates to the first conflict, and looks like this:
The main pane now shows jj's diff view, since you can see the snapshot in the top panes
If applicable:
- ~~[ ] I have updated the documentation (README.md, docs/, demos/)~~
- ~~[ ] I have updated the config schema (cli/src/config-schema.json)~~
- ~~[ ] I have added tests to cover my changes~~

vimdiff merge tool: use jj's diff conflict style and auto-navigate to conflicts

---

cli/src/commands/git/push.rs
cli/tests/test_git_push.rs

cli: git-push: remove support for existing long --change bookmark names

---

.github/CODEOWNERS

As discussed several times before, we want to restrict permission to approve PRs to the maintainers only. This patch adds a GitHub CODEOWNERS file for that purpose. Once this has been merged, I'm going to update the rulesets to make PRs requires approval from a maintainer.
If applicable:

github: add a CODEOWNERS file with only the maintainers in

---

CHANGELOG.md
cli/src/commands/log.rs
cli/src/config-schema.json
cli/src/config/revsets.toml

fixes #5506 
I've been using this for a while now, using
```toml
[revsets]
log-graph-prioritize = "coalesce(dev, present(main))"
```
where `dev` is my megamerge. I've found it to increase the readability of the graph by quite a lot.
**Before:**
**After:**
If applicable:

cli: add revsets.graph-prioritize setting

---

CHANGELOG.md
cli/src/command_error.rs
cli/src/commands/git/push.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_git_push.rs

Fixes https://github.com/jj-vcs/jj/issues/5472
If applicable:

cli `git push`: new `--named NAME=REVISION` argument to create and immediately push bookmark

---

cli/tests/common/test_environment.rs
cli/tests/test_git_remotes.rs

A subset of cli tests could fail if the system `/etc/gitconfig` had configuration interfering with the tests. The cause seems to be running of `jj` commands that would in turn use a `git` subprocess.
Fix this by setting `GIT_CONFIG_SYSTEM` and `GIT_CONFIG_GLOBAL`, like in `hermetic_git`.
Fixes #6159
If applicable:
- ~I have updated `CHANGELOG.md`~
- ~I have updated the documentation (README.md, docs/, demos/)~
- ~I have updated the config schema (cli/src/config-schema.json)~
- ~I have added tests to cover my changes~

cli/tests: Prevent git.subprocess from reading outside git config

---

cli/src/config/templates.toml
cli/src/description_util.rs
cli/tests/test_commit_command.rs
cli/tests/test_describe_command.rs
cli/tests/test_split_command.rs
cli/tests/test_squash_command.rs
docs/config.md

cli: pad empty description intro/instruction lines with "JJ:"

---

cli/src/config/templates.toml
cli/tests/test_commit_template.rs
cli/tests/test_completion.rs
cli/tests/test_evolog_command.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
cli/tests/test_show_command.rs
demos/demo_git_compat.sh

With this template, a `git format-patch` compatible email message can be generated using something like:
`jj show --git --template git_format_patch_email_headers <rev>`
If applicable:

templates: create new git_format_patch_email_headers template

---

CHANGELOG.md
cli/src/commands/resolve.rs
cli/src/merge_tools/mod.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_resolve_command.rs

This is a bit of a hack, but it would be useful to have these available for users until a proper solution is implemented.
Related to #1027.
If applicable:

merge_tools: add "ours" and "theirs" merge tools

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docs/releasing.md

Let me know if we want to add/remove anything in the the release highlights.
If applicable:

release: 0.28.0

---

cli/src/merge_tools/external.rs

I was trying to debug `mergiraf` behavior, and having such diagnostic would have been helpful.

cli external merge tools: add tracing when reparsing conflicts

---

Cargo.lock
cli/Cargo.toml
lib/Cargo.toml
lib/src/git.rs
lib/testutils/Cargo.toml
lib/testutils/src/lib.rs

Potential fix for the release issue. ~~If we don’t like the behaviour change here, we could set `JJ_DEBUG_HERMETIC_GIT` or something in `testutils::hermetic_git()` and condition on it.~~
If applicable:

tests: don’t use `git2` in `testutils`

---

cli/src/merge_tools/builtin.rs
cli/src/merge_tools/external.rs
cli/src/merge_tools/mod.rs
cli/tests/test_resolve_command.rs

These merge tools didn't work properly on conflicted trees with more than two sides since they didn't simplify the conflict before resolving.
https://discord.com/channels/968932220549103686/1357321005642678333
If applicable:

merge_tools: fix `:ours` and `:theirs` merge tools

---

CHANGELOG.md
Cargo.lock
Cargo.toml
cli/tests/test_git_colocated.rs
lib/src/git_backend.rs
lib/testutils/src/git.rs

Fix [GHSA-794x-2rpg-rfgr](https://github.com/jj-vcs/jj/security/advisories/GHSA-794x-2rpg-rfgr).
`gix::Repository::work_dir` was renamed to `workdir` (though strangely not the `gix::ThreadSafeRepository` version), and `lossy_config` is now off by default in all configurations.
If applicable:

cargo: bump `gix` to 0.71.0

---

docs/templates.md

In docs/templates.md, the Commit type and Operation type looked like:
`method() -> ReturnType`
rather than everything else, which looks like:
`.method() -> ReturnType`
This commit changes the Commit and Operation types to look more like the rest of the documentation.
If applicable:

docs: standardize on .method() syntax

---

.github/scripts/dragon-bureaucrat
.github/workflows/ci.yml

After some discussion on Discord yesterday, Emily floated this idea to have a check that fails if `Cargo.lock` has too many dependencies, where "too many" means "more than a random number I made up and sounds good."
This implements that, as a non-required check, and to do so it invokes the power of an extremely evil and annoying Dragon. We could also ask this Dragon to do other things too I suppose (pending future contract negotiations).
If applicable:

github: ward off future dependency bloat via dragon 

---

.github/scripts/count-cargo-lock-packages
.github/workflows/ci.yml

Follow-up to b1bb5e1
This creates a `.github/scripts/count-cargo-lock-packages` script to count packages with our methodology that one can run outside CI.
Cc @thoughtpolice 
-----
I initially thought of making the whole check a script, but I the dragon would be annoying if you were repeatedly invoking the script locally.

github: show counts and allow offline counting for dependency-counting check

---

cli/tests/test_git_push.rs

Follows up on https://github.com/jj-vcs/jj/pull/5698 and https://github.com/jj-vcs/jj/pull/6236.
The behavior of `--named` in corner cases differs. This wasn't detected
in https://github.com/jj-vcs/jj/pull/5698 because of a bug in the test. This commit better illustrates
the more important case where the behavior is the same, and the less
important case where it differs.

tests: make `git push --named` tests demo differences in subprocess and libgit2 logic

---

CHANGELOG.md

It would be tragic if 0.29 didn’t have any of these.
If applicable:

changelog: add missing release highlights section

---

cli/src/commands/abandon.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/tests/test_rewrite_transform.rs

The `new_parents_map` will allow the parents of each commit to be
customized before the `transform_descendents` callback is invoked. This
is useful when the order of commits needs to be changed, whereby setting
the new parents in the default callback might lead to repeated rebasing
and cycles if the new parent has not been visited in the reverse
topological order traversal.
If applicable:

repo: MutableRepo::transform_descendants_with_options: add `new_parents_map`

---

cli/src/commands/fix.rs
lib/src/fix.rs
lib/tests/test_fix.rs

It can be useful for fixers to record some information about the inputs they processed. For example, the `FileFixer` we use in our server at Google get more detailed error information back from its formatter tools. We may want to record these errors in our `FileFixer`'s state so we can then return that to the client.
If applicable:

fix: make `FileFixer::fix_files()` take `&mut self`

---

Cargo.lock

I realized what nuggets can hide in minor version updates after out 0.28.2; perhaps we should do this occasionally.
There's also some risk of breakage, so it seems to also good to do it in the beginning of a prerelease cycle.

cargo: general `cargo update`

---

cli/src/commands/describe.rs
cli/tests/test_describe_command.rs

cli: describe: reuse author field set to temporary builders

---

.github/workflows/ci.yml

It's implied for public repositories.
If applicable:

github: don't explicitly set `contents: read` for zizmor check

---

CHANGELOG.md
cli/src/commands/bookmark/list.rs
cli/src/config-schema.json
cli/src/config/misc.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_bookmark_command.rs
docs/config.md

This is a conclusion of #5849.
Config setting to list bookmarks in specified order.
Closes #3831
If applicable:

cli: Add config setting for bookmark list sort order

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/config/misc.toml
cli/src/diff_util.rs
cli/tests/test_diff_command.rs
cli/tests/test_interdiff_command.rs
docs/config.md
lib/src/files.rs

Closes #4062
If applicable:
cc @ilyagr

diff: add option to render color-words diffs without materializing conflicts

---

CHANGELOG.md
cli/src/commands/git/clone.rs
cli/src/commands/git/fetch.rs
cli/src/commands/git/push.rs
cli/src/config.rs
cli/src/git_util.rs
cli/tests/common/test_environment.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_push.rs
docs/config.md
docs/git-compatibility.md

~~Only intended for merge when we decide to start the deprecation process, but~~ should be ready ~~for code review now.~~
~~The first commit could be split out into another PR if we want to merge it now.~~
If applicable:

git: add deprecation warnings for `git.subprocess`

---

CHANGELOG.md
cli/src/config-schema.json
docs/git-compatibility.md
docs/glossary.md
lib/src/config/misc.toml
lib/src/git_backend.rs
lib/src/hex_util.rs
lib/src/settings.rs

When read/writing commits from the git-backend, populate the git commit header with a backwards hash of the `change-id`. This should enable preserving change identity across various git remotes assuming a cooperative git server that doesn't strip the git header.
This feature is behind a `git.change-id` configuration flag at least to start.
If applicable:

git_backend: derive the change ID from the git `change-id` header

---

cli/src/commands/new.rs
cli/tests/cli-reference@.md.snap

docs: add diagrams for jj new -A and -B

---

flake.nix

Latest rustc nightlies seem to have broken incremental compilation [0].
I apparently have the worst luck in this department, as I've gotten multiple ICEs within the last few hours alone. So, I'm putting future me out of her misery.
[0]: https://github.com/rust-lang/rust/issues/139110
If applicable:

nix: disable incremental builds within the dev shell

---

cli/src/commands/abandon.rs
cli/tests/test_abandon_command.rs

Bookmarks are no longer deleted on the next `jj git push` command, so this updates the language and downgrades the warning to a hint.
Thanks!
Related: https://github.com/jj-vcs/jj/pull/6189
If applicable:

cli abandon: convert deleted bookmark warning to hint

---

cli/src/template_parser.rs
cli/tests/test_operations.rs
lib/src/dsl_util.rs
lib/src/fileset_parser.rs
lib/src/git_subprocess.rs
lib/src/merge.rs
lib/src/revset_parser.rs
lib/tests/test_rewrite_duplicate.rs

cleanup: use new array methods instead of .collect_tuple()/.next_tuple()

---

cli/src/cli_util.rs
cli/src/command_error.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/simple_op_store.rs
lib/src/transaction.rs
lib/src/working_copy.rs
lib/src/workspace.rs
lib/tests/test_operations.rs

repo: propagate error from tx.write(), attach file path to op_store errors

---

CHANGELOG.md
docs/revsets.md
lib/src/default_index/revset_engine.rs
lib/src/revset.rs
lib/tests/test_revset.rs

Related to #5786
This PR adds a new `signed()` revset function that filters for signed commits.
cc @yuja 
If applicable:

revset: add `signed()` function

---

flake.nix

I imagine it may be a good idea to poke the Taplo folks about this, but this is a good stopgap in the meantime for the two people who use Jujutsu via Nix on macOS with the sandbox enabled. 😉
If applicable:

nix: fix tests in darwin sandbox

---

CHANGELOG.md
cli/src/command_error.rs
cli/src/commit_templater.rs
cli/src/diff_util.rs
cli/src/merge_tools/external.rs
cli/src/merge_tools/mod.rs
cli/tests/test_resolve_command.rs
lib/src/conflicts.rs
lib/src/local_working_copy.rs
lib/src/merge.rs
lib/src/tree.rs

cli: resolve: do not use .with_new_file_ids() to construct resolved file value

---

cli/src/merge_tools/builtin.rs

merge-tools: fix builtin merge editor to not ignore executable bit

---

lib/src/conflicts.rs
lib/src/merge.rs
lib/tests/test_conflicts.rs

merge: remove redundant .clone() from .simplify()

---

lib/src/git.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/rewrite.rs

revset: don't crash if revset engine returns non-BackendError

---

CHANGELOG.md
cli/src/commands/duplicate.rs
cli/src/config/templates.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_duplicate_command.rs
docs/config.md
lib/src/rewrite.rs
lib/tests/test_rewrite_duplicate.rs

This allows the customization of the duplicated commit descriptions.
An ideal use case for this is emulating `git cherry-pick -x`, as illustrated in the tests.
If applicable:

cli: duplicate: add setting for templating the new commit descriptions

---

cli/src/config/templates.toml
cli/tests/test_commit_template.rs
docs/config.md

for DCO Sign Off and Gerrit Change Id
this is based on #6088
If applicable:

templates: add commonly used trailers

---

mkdocs.yml

First commit adds this to the header:
Second commit adds this to all the pages:
If applicable:

docs: enable MkDocs' GitHub features

---

.github/dependabot.yml

A not-insignificant amount of our PR traffic is from Dependabot, even with the grouped update feature (something like 20% of all PRs in total are from Dependabot, last I checked.)
We don't really need daily updates, and with the the current crate dependency graph we practically get updates *every* day. Bump it to weekly instead to stem the tide a little.
If applicable:

github: make dependabot updates weekly

---

lib/src/repo.rs
lib/tests/test_mut_repo.rs

repo: mark view dirty after setting local bookmark target

---

docs/install-and-setup.md

I stumbled across https://github.com/jj-vcs/jj/issues/6241 
Since there seems to be an officially maintained package providing `jujutsu` for openSUSE Tumbleweed, I added the according documentation

docs: mention openSUSE installation method in docs

---

docs/index.md

Follow-up to 73e87bc.
If applicable:

docs/index: use sentence case consistently for docs page names

---

cli/src/commands/file/annotate.rs
lib/src/absorb.rs
lib/src/annotate.rs
lib/tests/test_annotate.rs

annotate: reorganize functions as restartable process

---

CHANGELOG.md
cli/src/commands/commit.rs
cli/src/commands/describe.rs
cli/src/commands/split.rs
cli/src/config-schema.json
cli/src/config.rs
cli/src/config/misc.toml
cli/tests/test_commit_command.rs
cli/tests/test_describe_command.rs
cli/tests/test_split_command.rs
docs/config.md

config: migrate ui.default-description to template alias

---

cli/tests/test_diff_command.rs
lib/src/copies.rs
lib/src/git_backend.rs
lib/tests/test_git_backend.rs
lib/tests/test_merged_tree.rs

git_backend: do not include renamed trees in copy records

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/config/misc.toml
cli/src/ui.rs
docs/config.md

cli: add config option for built-in pager's ruler

---

CHANGELOG.md
cli/src/commands/git/fetch.rs
cli/tests/test_git_fetch.rs

If `git.fetch` contains remotes that are not available, we currently error even if other remotes are available. For common fork workflows with separate `upstream` and `origin` remotes (for example), this requires a user to either set both remotes in their user config and override single-remote repos or set only one in their user config and override all multi-remote repos to fetch from `upstream` (or both).
This change updates fetching to only *warn* about unknown remotes **if** other remotes are available. If none of the configured remotes are available, an error is still raised as before.
If applicable:

git: tolerate unknown `git.fetch` remotes if others are available

---

CHANGELOG.md
cli/src/cli_util.rs
cli/tests/common/command_output.rs
cli/tests/test_completion.rs
cli/tests/test_global_opts.rs

Fixes #5377.
The fix ended up as exactly like @yuja mentioned in the issue and what the `TODO` comment in the code was already proposing. Still, it took a fair bit of fiddling around with the different shells to understand where they are differing in behavior exactly. 
I've gotten a wee bit carried away refactoring the existing tests to cover multiple shells (where sensible) without duplicating too much of the test code. Even so, insta needs a `match` over the different shell flavors to snapshot their output individually. For a while, I've entertained the idea of adding a `.normalize_shell_completions(shell)` function on the test output to basically strip away the comment (because bash doesn't have that) such that it would produce the same (normalized) output for each shell and we could …

completion: fix bash and zsh shell completion when completing aliases of multiple arguments

---

CHANGELOG.md
cli/src/commands/config/edit.rs
cli/tests/test_config_command.rs

This should fix #3905.
If applicable:
My implementation is quite simple: if an error is added to the config, jj will prompt the user if he wants to keep editing the config. If the user don't want to, then the bad config is overwritten with the previous working one (Without the need of any temporary file). Otherwise, the user can fix the error

cli config edit: Rollback to previous config when invalid TOML is saved

---

CHANGELOG.md
Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/cli_util.rs
cli/src/complete.rs
cli/src/config.rs
cli/src/git_util.rs
docs/config.md

Changing where the default config location is on macOS, switching to [etcetera][] from [dirs][].
Some points for discussion:
- I am treating the classic behaviour as a bug, not a feature; I do _not_ believe that it is correct in any way to place configuration in `~/Library/Application Support`, ever, and certainly not for CLI applications
- ~~Currently, if you run `jj config edit --user`, and you already have a config in `~/Library/Application Support`, you'll get a picker for both; this seems less than ideal? Perhaps advice would be good? Or we could ignore the normal file if the legacy file exists?~~
- ~~This has been changed as of latest patch set – it may be desireable to pull that patch out into its own PR. Let me know.~~
- ~~This bugfix has been pulled into its own PR: #6315~~
- …

config: Use XDG-standard config location on macOS

---

Cargo.lock
Cargo.toml
cli/tests/cli-reference@.md.snap

clap-markdown doesn't follow semver, so I pinned the version exactly.
If we don't like the changes, we could pin the older versions instead. The main goal is so to prevent this from messing up dependabot PRs.

docs cli reference: update and pin clap-markdown, include aliases in reference

---

docs/config.md

I was asked about this in Discord, so I wanted to make sure to have the information available in the docs and not just the code.

docs: add some more info on signing

---

docs/git-compatibility.md

I noticed that the docs for signed commits in https://jj-vcs.github.io/jj/v0.28.0/git-compatibility/#supported-features are outdated. The `jj sign` command is now supported.
If applicable:

docs: update git compatibility docs for commit signing

---

cli/examples/custom-commit-templater/main.rs
cli/examples/custom-operation-templater/main.rs
cli/src/cli_util.rs
cli/src/commands/bookmark/list.rs
cli/src/commands/bookmark/track.rs
cli/src/commands/config/list.rs
cli/src/commands/evolog.rs
cli/src/commands/file/annotate.rs
cli/src/commands/file/list.rs
cli/src/commands/log.rs
cli/src/commands/operation/diff.rs
cli/src/commands/operation/log.rs
cli/src/commands/operation/show.rs
cli/src/commands/tag.rs
cli/src/commit_templater.rs
cli/src/generic_templater.rs
cli/src/operation_templater.rs
cli/src/template_builder.rs

templater: move `wrap_*()` functions to property types

---

CHANGELOG.md

changelog: remove redundant entry about macOS config path

---

.github/workflows/binaries.yml
.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
cli/Cargo.toml
cli/src/command_error.rs
cli/src/commands/git/clone.rs
cli/src/commands/git/fetch.rs
cli/src/commands/git/push.rs
cli/src/config-schema.json
cli/src/config.rs
cli/src/git_util.rs
cli/tests/common/test_environment.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_push.rs
docs/config.md
docs/install-and-setup.md
flake.nix
lib/Cargo.toml
lib/src/config/misc.toml
lib/src/git.rs
lib/src/settings.rs
lib/tests/test_git.rs
lib/testutils/src/lib.rs

The last mile of the journey, for after https://github.com/jj-vcs/jj/pull/6047 is merged and the deprecation period is over.
The first couple of commits are functional changes and the rest are just very gradually removing a lot of dead code and tidying up. I’ve tried to structure them so that it's easy to review commit‐by‐commit and the largest commits are entirely mechanical.
I probably won’t rebase this much until it’s time to actually merge, but the approach should be ready for review.
If applicable:

git: remove `git.subprocess` setting

---

CHANGELOG.md
cli/src/commands/split.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_split_command.rs

to set the message on the first commit, where the selected changes are going. The commit with the remaining changes keeps the original description.
With this option it becomes possible to use split in a fully non-interactive way, in combination with the filset feature. It also makes jj split more consistent with other commands like squash, commit or new.
If applicable:

split: add the --message option

---

docs/config.md

I spent quite a while confused by the presence of
`if(!trailers.contains_key("Change-Id")` in the `commit_trailers` example. My thinking was: if `commit_trailers` already performs deduplication, then isn't this logic useless?
Eventually I realized that the `commit_trailers` deduplication works on the entire line, not just the key as I'd assumed. (And that makes sense for trailers like Signed-off-by that can appear more than once.)
I've reworded the `commit_trailers` documentation to try to make this more clear.
To be honest, I'm not thrilled with the way the wording turned out, so suggestions are welcome. In particular, I've tried to define each trailer as a "line in the template", but since `format_signed_off_by_trailer` and `format_gerrit_change_id_trailer` (helpfully!) include a …

docs: clarify commit_trailers deduplication

---

docs/git-command-table.yml

I just ran into this trying to figure out the equivalent to `git revert`. Turns out that backout is deprecated and revert does not have the same defaults.

Remove deprecated backout command from documentation table

---

lib/src/default_index/mod.rs

Fixup to 920debc that removed the line this comment was about.
If applicable:

cleanup: fixup to 920debc, delete now-irrelevant comment

---

Cargo.lock
Cargo.toml
cli/tests/test_global_opts.rs

A test has to be updated because argument aliases are now prefixed with `-` or `--` in the CLI help output. See also the open PR ConnorGray/clap-markdown#44 for updating the Markdown generated for the CLI reference similarly.
If applicable:

cargo: bump `clap` to v4.5.38

---

flake.nix
lib/tests/test_gpg.rs

This allows the logic in
https://github.com/nix-community/home-manager/pull/6994 to be applied.
If applicable:

nix flake: include package version in derivation attributes

---

docs/templates.md

In particular, this fixes the section heading for the `List<Trailer>` type. Before this commit, that heading was rendered incorrectly as 'List type'.
If applicable:

docs/templates: surround type names with backticks in section headings

---

docs/FAQ.md

Adapted from:
- https://gist.github.com/thoughtpolice/8f2fd36ae17cd11b8e7bd93a70e31ad6#file-jjconfig-toml-L247
- https://github.com/avamsi/dotfiles/blob/28a0e40439de56fe179a1b0e705727c85e075464/.jjconfig.toml#L150
I'm not sure if I should add tests. I can add them if needed.
If applicable:

docs: document code to avoid duplicating gerrit change-id

---

cli/src/commands/rebase.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_absorb_command.rs
cli/tests/test_duplicate_command.rs
cli/tests/test_rebase_command.rs
cli/tests/test_repo_change_report.rs

rebase: avoid using "onto destination" when argument can be `-A/-B`

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/diff_util.rs
cli/src/merge_tools/diff_working_copies.rs
cli/src/merge_tools/external.rs
cli/src/merge_tools/mod.rs
cli/testing/fake-diff-editor.rs
cli/tests/test_diff_command.rs

The temporary folder name can add significant noise to the produced diff when using an external diff tool if the tool displays paths prominently. Add a setting, `diff-do-chdir`, that chdirs to the temporary directory before running the tool.
Closes #5801
Disclaimer: I'm not a real Rust programmer, just cosplaying as one to get my pet change into jj. I'm also not sure about the `diff-do-chdir` name. Comments welcome!
If applicable:

diff: Add diff-do-chdir setting for external tool

---

CHANGELOG.md
lib/src/git_subprocess.rs

This workaround addressed #6440.
The issue itself that this addresses is likely an upstream issue in `git` itself, as I can reproduce it using raw `git` commands (this is demonstrated on the bug ticket).
The cliff's notes for the issue are as follows:
If the macOS-specific `fsmonitor` is enabled in the Global or System `.gitconfig`, The `fetch` operation that `jj` uses during `jj git clone --colocate` will hang forever if it is invoked *outside* of the actual working copy.
~~The workaround here, then, is pretty brain-dead: Change the working directory before calling `fetch` via the subprocess.~~
~~To avoid forcing everything to suddenly change directories all over the place, I added a `with_working_dir` helper that can be used to wrap a closure with the relevant directory changes.~~ …

Workaround `git` bug effecting `jj git clone --colocate` on Mac

---

CHANGELOG.md
cli/src/commands/rebase.rs
cli/src/commands/split.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_immutable_commits.rs
cli/tests/test_split_command.rs
lib/src/rewrite.rs

See the comments in the commit descriptions.
The last two commits implement `jj --parallel -r x` as `jj split -r x -A x- -B x+` as discussed in #3419, but I'm not sure to see the point, except to document `--parallel` as equivalent to `-A x- -B x+` (or `-d x-` if x has no descendant). I'm including them here to continue the discussion.
Still some tests to implement, but some early feedback would be appreciated!
If applicable:

split: implement -A/-B/-d flags

---

cli/src/commands/git/init.rs
cli/tests/test_git_init.rs

I often copy and run this command after running `jj git init --colocate`. Having it on a separate line makes it stand out more and easier to copy, especially if there are many bookmarks listed.
If applicable:

cli git init: show `jj bookmark track` command on new line

---

docs/technical/conflicts.md

I think its time to finally give our Conflict Algebra rule a name and a Glossary term. This is will make our documentation alot easier, and gives it a name for new design docs.
All credit goes to @martinvonz for coming up with the term in #4988.
If applicable:

conflicts: document the "same-change rule"

---

cli/src/commands/commit.rs
cli/tests/test_commit_command.rs

This implements something akin to what's described in @arxanas's suggestion at <https://github.com/jj-vcs/jj/issues/4414#issuecomment-2359123535>, with the exception that the editor contents don’t need to be completely cleared, since whether cleared or not it is not obvious whether the user intended to add an empty description or abort entirely.
If applicable:

commit: show a hint if `--message` is not provided and the description is empty

---

cli/src/revset_util.rs
cli/tests/test_new_command.rs

cli: improve hint to abandon commits when divergent change appears

---

cli/src/commands/bookmark/move.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_bookmark_command.rs

The usage line originally showed `--from <REVSETS>|NAMES`, which was confusing as it could be parsed as `--from (<REVSETS> or NAMES)`, rather than the correct `(--from <REVSETS>) or NAMES`.
The order of the two arguments are now swapped, so that Clap displays it as `NAMES|--from <REVSETS>` instead. Using bookmark names as the move targets should be more common anyway. This is also consistent with the order in which the two arguments are described in the command's doc comment.
If applicable:

cli bookmark move: move `names` argument before `--from` argument

---

cli/src/commands/split.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_split_command.rs

based on: https://github.com/jj-vcs/jj/pull/6458
The usage of "revision" and "commit" may not be fully consistent, as I'm not totally sure when to use one or the other.
If applicable:

split: use "selected/remaining changes" instead of "first/second commit"

---

CHANGELOG.md
cli/src/commit_templater.rs
cli/tests/test_templater.rs
docs/templates.md

templater: split ChangeId/CommitId types, deprecate CommitId::normal_hex()

---

CHANGELOG.md
cli/src/template.pest
cli/src/template_builder.rs
cli/src/template_parser.rs
cli/tests/test_templater.rs
docs/templates.md

Adds arithmetic operators on integers. Fixes #5982.
I ran into this when trying to do some alignment-type things inside a template. I'm currently using
```
'len(template)' = 'stringify(template).len()'
'repeat(str, int)' = 'stringify(pad_end(int, "", str))'
'spaces(int)' = 'repeat(" ", int)'
'add(a, b)' = '''
len(concat(spaces(a), spaces(b)))
'''
'sub(a, b)' = '''
len(spaces(a).substr(0, -b))
'''
```
~~I have not yet added tests, as I am unsure of the best place to put them. `test_templater.rs` seems the most applicable, although it seems currently to mostly test higher-level functionality and not specific templating operations.~~
If applicable:

templater: add arithmetic operators

---

cli/src/config.rs
cli/tests/test_config_command.rs

Instead of saying to move configuration files from `~/Library/Application Support` to `~/.config`, jj now tells you to move configuration files from `~/Library/Application Support/jj` to `~/.config/jj`.
Fixes #6533
If applicable:

config: clarify warning

---

cli/src/diff_util.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_diff_command.rs

cli: accept --tool=:<format> argument as builtin diff format

---

cli/src/commands/util/exec.rs
cli/tests/cli-reference@.md.snap
docs/config.md

It isn't necessary to include shebangs in scripts passed into `util exec` since you're already explicitly calling out the shell you'd like to use. This change removes shebangs from examples for `util exec` and adds a note below calling this out.
If applicable:

docs: Don't include unnecessary shebangs

---

cli/tests/test_concurrent_operations.rs
cli/tests/test_undo.rs

test: use `--at-op` and templates instead of manually parsing op ids from op log output

---

lib/src/repo.rs

This PR fixes a small typo in the `RepoLoader` docs that I noticed when viewing the `jj-lib` documentation on docs.rs.
If applicable:

lib: Fix a typo in the `RepoLoader` docs

---

cli/src/commands/describe.rs

This assertion is redundant given both the `conflicts_with = "edit"` declaration on the `no_edit` flag and the passing `test_edit_cannot_be_used_with_no_edit` test.
If applicable:

cli describe: remove redundant assertion of conflicting flags

---

CHANGELOG.md
cli/src/commands/rebase.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_rebase_command.rs
lib/src/rewrite.rs
lib/tests/test_rewrite.rs

This is a partial fix for #5381 and #2979. It doesn't handle the general case (it only detects duplicate changes between divergent commits with the same change ID), but I think it should handle many useful cases, especially for users with the `change-id` header enabled. I'm looking for feedback about whether this is a good general approach and about the implementation.
This serves a similar purpose to Git's patch ID mechanism, however it is slightly different in that it only compares commits which have the same change ID as each other (divergent changes), and it does a full comparison of the commits to see if they would have identical trees if rebased onto the same parents. Since most changes aren't divergent, I believe this should have a negligible performance cost in most cases.
I think …

rebase: skip duplicate divergent commits by default

---

lib/src/op_walk.rs
lib/tests/test_operations.rs

lib: return correct op set subexpression when reporting multiple operations found

---

cli/src/command_error.rs
cli/tests/test_resolve_command.rs

As suggested in Discord: https://discord.com/channels/968932220549103686/1370632916169920523
If applicable:

cli: resolve: show a hint towards editing the conflict markers manually if the conflict has >2 sides

---

lib/src/file_util.rs

Introduced in b970939804b865729a1d14cedb6ea045411882b8 and caught by `cargo check`.
If applicable:

cleanup: remove unused `mut`

---

cli/src/commands/operation/undo.rs
cli/tests/test_undo.rs

Based on refactoring in #6589.
To identify an `undo` operation, checking that the views of the "bad" op and its grandparent are equal is necessary but not sufficient. For example, creating a bookmark and then immediately deleting it also "resets" the view. This commit fixes this by also checking the "description" in the operation metadata to identify "double undo" properly.
With this commit, the "double undo" warning is now shown whether users undid the latest undo implicitly (with `jj (op) undo`) or explicitly (with `jj (op) undo <op set>` or `jj (op) undo @`).
If undoing an older undo (prior to `@`), the warning is not shown.
If applicable:

cli undo: detect "double undo" from operation metadata instead

---

docs/install-and-setup.md

Dynamic completions were added to fish [4.0.2]. To date there is no 4.1 yet.
[4.0.2]: https://github.com/fish-shell/fish-shell/releases/tag/4.0.2
If applicable:

docs: fix minimum fish version with dynamic completions enabled by default

---

cli/src/cli_util.rs
cli/tests/test_absorb_command.rs
cli/tests/test_file_chmod_command.rs
cli/tests/test_repo_change_report.rs
cli/tests/test_resolve_command.rs
cli/tests/test_restore_command.rs
cli/tests/test_squash_command.rs
cli/tests/test_status_command.rs
docs/tutorial.md

We already use "conflicted commit" at the very end of the hint, so I've reused that term here.
If applicable:

cli: use more precise wording in conflict resolution hint

---

cli/src/commands/operation/undo.rs

Fixup to 96e73bda.
Instead of checking if the parent op id is contained in the bad op's description metadata, we construct the "undo operation X" description for the bad op on the fly (using the parent op id X) and compare it with the existing bad op description.
If applicable:

cli undo: identify "double undo" by comparing operation descriptions

---

CHANGELOG.md
cli/src/commands/rebase.rs

Deprecated in b57dd4d2 (#4014) and v0.20.0.
If applicable:

cli rebase: remove deprecated `--skip-empty` flag

---

cli/src/cli_util.rs

This partially reverts f1765183 (from #6602) to avoid i18n issues as @yuja pointed out.
If applicable:

cli: use complete sentences for each case of conflict resolution hint

---

cli/tests/test_config_command.rs

Using the `cfg` attribute means the test is not compiled at all in non-macOS environments.
If applicable:

test: replace `cfg!` macro with `cfg_attr` attribute

---

CHANGELOG.md
cli/src/commands/parallelize.rs
cli/tests/test_immutable_commits.rs
cli/tests/test_parallelize_command.rs

closes #6587
Given a commit history like this:
```
○  ccc
○  bbb
◆  aaa
```
Parallelize *should* be able to create this:
```
○  ccc
│ ○  bbb
├─╯
│ ◆  aaa
├─╯
```
This is fine because `aaa` will not be rewritten --- its children will, but neither `aaa`'s parents nor author information needs to be changed.
However, the current implementation checks _all_ commits in the target set for rewritability, instead of only the commits that will be rewritten.
This commit changes that. Now, only the commits whose parents *will* change are checked for rewritability.
If applicable:

parallelize: only check to-be-rewritten commits for rewritability

---

docs/design/copy-tracking.md

If applicable:
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1209241374115289

Updated copy-tracing proposal to handle conflicts

---

CHANGELOG.md
cli/src/config.rs
cli/tests/test_config_command.rs

When `XDG_CONFIG_HOME` is specifically configured to `~/Library/Application Support`, jj will still warn about deprecated paths. This PR introduces an additional check to prevent this
If applicable:

Do not warn about deprecated config path if XDG_CONFIG_HOME is configured there

---

docs/releasing.md

- Use `jq -s` to read the entire input (could be several arrays due to GitHub API pagination) before running the filter just once.
- Deduplicate by `.author.login` in case a person with the same GitHub username has commits under different names within a release.
- Use string interpolation to format each line.
If applicable:

docs/releasing: update `jq` filter

---

lib/src/str_util.rs
lib/tests/test_revset.rs

str_util: parse regex-i:pattern as case-insensitive regex

---

cli/src/config-schema.json
cli/tests/common/config_schema_defaults.rs
cli/tests/common/mod.rs
cli/tests/datatest_config_schema.rs
cli/tests/datatest_runner.rs
cli/tests/runner.rs
cli/tests/test_config_command.rs
cli/tests/test_config_schema.rs
flake.nix

config-schema: add test asserting schema defaults match default config

---

CHANGELOG.md
cli/src/merge_tools/builtin.rs
lib/src/repo_path.rs
lib/tests/test_fix.rs
lib/tests/test_git.rs
lib/tests/test_local_working_copy.rs
lib/tests/test_rewrite.rs
lib/testutils/src/lib.rs

Fixes #5189. As discussed in the issue, I went ahead with property-based testing and followed the state machine approach mentioned by @arxanas. Thanks for the pointers you gave in https://github.com/jj-vcs/jj/issues/5189#issuecomment-2836104306; they were quite helpful to get my head wrapped around it.
You mentioned that it would be nice to create working copy states for other tests. AFAIU the split been the `ReferenceStateMachine` and `StateMachineTest` traits in `proptest-state-machine` is intended to facilitate this kind of reuse of the reference state machine while keeping the test's state separate, so I've created a dedicated `proptest` module in `testutils` containing the data structure implementing `ReferenceStateMachine` the and associated strategies. The `StateMachineTest` …

builtin merge-tool: fix edge cases found by property-based testing

---

Cargo.lock
Cargo.toml
lib/src/git.rs
lib/src/git_backend.rs
lib/testutils/src/git.rs

(See commit descriptions)
Cc: https://github.com/GitoxideLabs/gitoxide/pull/1935,
https://github.com/GitoxideLabs/gitoxide/pull/2038
If applicable:
- (n/a) I have updated `CHANGELOG.md`
- (n/a) I have updated the documentation (`README.md`, `docs/`, `demos/`)
- (n/a) I have updated the config schema (`cli/src/config-schema.json`)
- (n/a) I have added/updated tests to cover my changes

Update `gix` to 0.72.1, and adapt to its breaking changes.

---

CHANGELOG.md
docs/releasing.md

I'm also planning to update the release notes for 0.30 at https://github.com/jj-vcs/jj/releases/tag/v0.30.0 after I merge this, let me know if you think we should handle it differently.
I can't think of a better (simple) technical solution than just looking at the diff before every release. I briefly considered a presubmit check for this, but it doesn't seem fun or worth it to write or maintain (though people are welcome to if they feel otherwise). I think that, as long as it's part of a checklist, it shouldn't be onerous.
I noticed this because of https://github.com/keanemind/jjk/issues/127#issuecomment-2949223664.

CHANGELOG fixup: move diff-do-chdir entry to 0.30, add check in `releasing.md`

---

cli/src/commands/bench/common_ancestors.rs
lib/src/rewrite.rs

cleanup: use slice::from_ref() in non-test code

---

lib/src/config.rs
lib/src/git_subprocess.rs
lib/src/gpg_signing.rs
lib/src/ssh_signing.rs

* ~Add `#[allow(clippy::result_large_err)]` for functions that return `Result<T, ConfigLoadError>`.~
* Change `std::os::windows::process::CommandExt` to underscore imports.
* ~Change `&[target_commit.clone()]` to `std::slice::from_ref(target_commit)`.~
I just silence the clippy error for the large error type `ConfigLoadError` instead of fixing it, because fixing can introduce breaking changes in the API: `ConfigLoadError` is a public type used in public methods, e.g., `ConfigFile::load_or_empty`. I am Ok to further update this PR to fix that clippy error, but I need more instructions on:
* Can I just create a new `#[derive(Error)] struct ConfigLoadError(#[error(transparent)] Box<ConfigLoadErrorImpl>)` type to fix the clippy error or it would be better if I dig in the enum variants and …

clippy: fix clippy error

---

docs/git-compatibility.md

`jj` no longer uses libgit2, so the lack of support can't be blamed on it. We [still don't support partial clones](https://github.com/jj-vcs/jj/issues/6690#issuecomment-2946785320) though.
There's no real tracking issue for this. [This PR](https://github.com/jj-vcs/jj/pull/6451/) is as close as it gets, but it doesn't feel appropriate to link in the docs.
PS. Thanks for the detailed reply to my question @anguslees

Don't blame libgit2 for lack of partial clone support

---

Cargo.toml

Apparently this broke a dependabot update. Stop the bleeding for now.
If applicable:

cargo: set `toml_edit = "=0.22.26"` constraint

---

cli/examples/custom-backend/main.rs
lib/src/backend.rs
lib/src/git_backend.rs
lib/src/secret_backend.rs
lib/src/simple_backend.rs
lib/src/store.rs
lib/testutils/src/test_backend.rs

This is closer aligned to the type signature for `write_file` as well, which is currently:
```
async fn write_file(
&self,
path: &RepoPath,
contents: &mut (dyn AsyncRead + Send + Unpin),
) -> BackendResult<FileId>;
```
This change enables the jj-lib api to be used in multi-threaded executor contexts.
If applicable:

Add Send bounds to the AsyncRead future returned by read_file

---

CHANGELOG.md
lib/src/lock/unix.rs

This caused some issues with the Google internal NFS filesystem. Treating `ESTALE` (stale file handle) as a file deletion should be the right thing to do.
If applicable:

lib: Retry locking on ESTALE

---

CHANGELOG.md
cli/tests/test_file_annotate_command.rs
lib/src/revset.rs

Fixes #6713
If applicable:
cc @scott2000 as this might have conflicts with your patch.

revset: do not reinterpret `set&filter` intersection as filter

---

docs/github.md

With the move to the git subprocess stuff we should now be able to remove this reference.
If applicable:

docs: Remove now outdated reference to issue 469

---

cli/src/commands/diff.rs
cli/tests/cli-reference@.md.snap

cli: fix typo in `jj diff -r` doc comment

---

lib/src/default_index/composite.rs
lib/src/default_index/mod.rs
lib/src/default_index/revset_engine.rs
lib/src/revset.rs
lib/tests/test_revset.rs

Resolves #6656. Suggested by @yuja.
Currently, evaluating an expression like `heads(::@ ~ empty())` requires iterating over all commits in `::@` and checking the predicate against each commit, which can be very slow. This PR implements an optimization to convert expressions to the form `heads(x..y & filter)` when it is possible to do so efficiently. Expressions of this form can be evaluated using a specialized algorithm which terminates iteration early without checking all commits.
Benchmark results on Git repo:
```
revsets/heads(author(peff))     97.248% improvement
revsets/heads(::v2.40.0)        98.467% improvement
```
If applicable:

revset: optimize heads of a range with filters

---

cli/src/commands/backout.rs

Hi!
This builds on #6290 - I probably should have just tried `jj backout` before reading through many `--help` pages trying to understand when I'd rather use `backout` over `revert` and vice versa, but I think it'd be an improvement to simply put this at the top and in the tab completion help.
WDYT?
If applicable:

Prepend `backout` description with '(deprecated; use `revert`) '

---

lib/src/repo_path.rs

There are also quite a few instances of calling `Path::to_str()` in the test, where they can be just dropped (where the expected type of argument is `impl AsRef<Path>`, but as discussed in the ticket (#6738) I didn't touch those. If necessary this can be done as additional PR.
I used clippy lint `disallowed-methods = ["std::path::Path::to_str"]` to spot the usage of the `to_str` method. And I think there a couple of places where I left them untouched (besides tests) - I didn't feel that the change there would be appropriate or at least it won't be non-controversial.
Anyway, feel free to review and comment.
If applicable:

6738 path display

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/formatter.rs
docs/config.md

Fixes #6691, using @ilyagr's proposed syntax. My first instinct would have been a shorter `ansi<N>`, but I see that would be ambiguous with other escape codes.
Since the 256-color palette isn't well-known and hard to reason about without a lookup table, I included a link to [Wikipedia's article](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit). It goes around a bit with technical details, but the compact layout of the table itself is very nice for lookup. The best contender would be [Ditig's 256 colors cheat sheet](https://www.ditig.com/256-colors-cheat-sheet), which is the top result in most search engines, but AFAIK not a well-known website otherwise, and I find its vertical layout not very practical.
I'm also including fixes for typos I spotted in the changelog.
If applicable:

formatter: add support for ANSI 256-color palette

---

cli/src/config-schema.json

I would really like a more principled way to ensure that the schema is up to date; could we somehow ban retrieving undocumented config settings?
Change-Id: I6a6a69640755c60467c1be0eb362307c2c22e0ff
If applicable:

config-schema: fix missing private-commits setting

---

CHANGELOG.md
cli/src/commands/evolog.rs
cli/src/commands/log.rs
cli/src/commands/operation/log.rs
cli/src/config/templates.toml
cli/tests/test_templater.rs

This was noted in the discord. Back then we couldn't have implemented this logic in templates, but we now have the machinery to do so. So let's clean this thing up.
If applicable:

cli: Remove hard-coding of log symbols and put them in default templates

---

cli/src/graphlog.rs

cli: remove GraphStyle::is_ascii() which has been inlined in templates

---

lib/src/revset.rs

Now that `all()` contains all referenced commits, we can optimize `~all()` to `none()` and `~none()` to `all()`.
If applicable:

revset: optimize `~all()` and `~none()`

---

lib/src/git_backend.rs

git_backend: minor cleanup around extra header parsing

---

cli/src/template_builder.rs
docs/templates.md

docs: show which template types support implicit conversions

---

CHANGELOG.md
cli/tests/test_revset_output.rs
docs/revsets.md
lib/src/revset.rs
lib/tests/test_revset.rs

Resolves #3337.
If applicable:

revset: add `parents(x, depth)` and `children(x, depth)`

---

cli/src/commit_templater.rs
cli/src/generic_templater.rs
cli/src/operation_templater.rs
cli/src/template_builder.rs
docs/templates.md

templater: rename PlainText pseudo type to Stringify

---

CHANGELOG.md
cli/src/commands/operation/abandon.rs
cli/src/commands/util/gc.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_evolog_command.rs
lib/src/default_index/store.rs
lib/src/evolution.rs
lib/src/index.rs
lib/src/operation.rs
lib/src/view.rs
lib/tests/test_operations.rs

~I originally considered it would be a bad idea to ignore predecessors that don't exist in the store because doing that could shadow potential data corruption issues. However, we have index built from the op log, which knows all reachable commits. So we can ask index whether the predecessor id is supposed to exist. If a predecessor exists in the index but not in the Git object store, the repository is corrupted.~
~https://github.com/jj-vcs/jj/pull/4953#issuecomment-2495735683~
~In this implementation, we assume that predecessor commits are reachable from at least one of the historical views. Some commands (e.g. squash into descendants) may create transitive commits within an operation. In that case, the predecessor chain is initially preserved, but will be lost after reindexing. We might …

index: don't preserve commits not referred to by operations/views

---

lib/src/absorb.rs
lib/src/commit.rs
lib/src/default_index/revset_engine.rs
lib/src/fix.rs
lib/src/rewrite.rs
lib/src/store.rs

This is to prepare for making `annotate.rs` read trees concurrently across multiple commits.
If applicable:

Introduce async version of `Commit::tree()`

---

cli/src/template_builder.rs

I find the result harder to read correctly, but it doesn't seem worth maintaining a clippy exception for.

clippy: nightly clippy fix

---

docs/related-work.md

* HTTPS can't connect
* HTTP has cloudfront 403 error page - [as per web archive at least since 2023-10-18](https://web.archive.org/web/20231018153827/https://getsturdy.com/)
* Uncommented [issue ticket](https://github.com/sturdy-dev/sturdy/issues/1360) since 2024-02-18
If applicable:

Drop defunct Sturdy from related-work

---

cli/src/complete.rs
cli/tests/test_completion.rs

cli: complete: use diff template instead of parsing copied/renamed paths

---

CHANGELOG.md
cli/src/commands/fix.rs
cli/tests/test_fix_command.rs

The stderr from fix tools is currently all mixed together. I think the problem is worse on Windows: I regularly see line noise as multiple stderr streams are interleaved character-by-character. On Windows, this is _extremely_ slow and can make `jj fix` very annoying, if not unusable.
This change buffers the stderr output line-by-line, so at least there's some hope of reading it. I'm also prefixing the file name.
Ways this could be improved:
- Maybe prefix the commit ID and/or tool name as well as the file name: `path/to/file:clippy:a8b9c3d:This is some output`
- Instead of releasing the mutex holding the main process's Stderr after emitting each line, it would be nice to emit all available lines from a process before releasing the mutex. However, I didn't see a way to …

Buffer stderr from fix tools

---

CHANGELOG.md
cli/src/commands/status.rs
cli/tests/test_status_command.rs

I wanted to try out `jj` since it seemed cool, was happy that `snapshot.auto-track` was added since I keep many untracked files in my repos, however once I ran `jj st` it spat out a line for every single file in my untracked directories into a pager which is not optimal. This PR collapses directories which consist entirely of untracked files (i.e. without any files that are tracked in the working copy inside).
Note that this is purely a `jj status` post processing step and does not affect how untracked files are collected. It may also be nice to do something like this in other places. ~~I think git also does this for stuff like added files too so if you add a directory it just shows the directory, that just seems a bit more involved and is not a problem for me right now~~. git does not do …

status: collapse entirely untracked directories

---

CHANGELOG.md

I originally prepended the filename to each line of stderr output, but during PR it changed to just printing once before each subprocess' output.
If applicable:

fix: Revise description of how stderr is handled

---

cli/src/commands/describe.rs
cli/src/commands/status.rs
cli/src/config/misc.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_operations.rs
cli/tests/test_working_copy.rs
cli/tests/test_workspaces.rs

I'm sorry if we have already discussed this and rejected the idea for some reason.
If applicable:

cli: move `desc` and `st` aliases to config

---

CHANGELOG.md
cli/src/operation_templater.rs
cli/tests/test_operations.rs
docs/templates.md

Add a parents method for Operation, as requested in #6979 
If applicable:

Add parents() method for Operation template type

---

CHANGELOG.md
cli/src/config/merge_tools.toml
cli/src/diff_util.rs
cli/src/merge_tools/mod.rs
cli/tests/test_diff_command.rs
docs/config.md

If `diff-args` or `edit-args` are unset, default values are used.
This PR makes it so that explicitly setting them to `[]` causes them
to error. The last commit includes many examples where this is useful.
https://github.com/jj-vcs/jj/issues/4549
The first few commits are related touch-ups that could be independently
useful.
If applicable:
- n/a (?) I have updated the config schema (`cli/src/config-schema.json`)

merge tools: allow specifying that a tool does not support diff editing or viewing

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/config/misc.toml

This also adds a helpful message to the error if the user does `jj amend`. I don't think this is absolutely necessary, but I also don't see any harm in it.
------
We do use the term "the commit gets amended" in the docs a few times, but there's no mention of `jj amend` except in old changelog entries, I think.
I'm not sure this needs a test. It looks like this:
```console
$ cargo run -- amend --help
error: unrecognized subcommand 'amend'
For more information, try '--help'.
Hint: You probably want `jj squash`. You can configure `aliases.amend = ["squash"]` if you want `jj amend` to work.
```
- n/a? I have updated the documentation (`README.md`, `docs/`, `demos/`)
- n/a I have updated the config schema (`cli/src/config-schema.json`)
- [?] I have added/updated tests to cover my changes

cli: remove `amend` alias

---

cli/src/commands/file/track.rs
cli/tests/cli-reference@.md.snap
docs/FAQ.md
docs/config.md
docs/working-copy.md

1. `snapshot.auto-track` is described in several places, with its ability to disable auto-tracking of files. Next to it, `jj file untrack` is mentioned.
That sounded cool to me, but I couldn't figure out how to track files. One could make the connection between `untrack` and `track`, but I think it should be more explicit.
(BTW, the FAQ item where the "don't track anything" option is mentioned is discussing scratch files, but I think this option is enticing enough to people familiar with other VCS tools to deserve its own entry)
2. The documentation of `jj file track` starts with:
> New files in the working copy can be automatically tracked.
That "can" feels wrong to me - new files *are* automatically tracked by default. I changed the phrasing a bit, to move the default behavior to the …

Improve discoverability and documentation of `jj file track`

---

cli/src/commands/commit.rs
cli/src/config/misc.toml
cli/tests/cli-reference@.md.snap

Follows up on 59de83a.
Now, all of the aliases from `cli/src/config/misc.toml` will be documented in the same way. I think I was previously unsure whether we'll keep them, but they seem to be doing no harm.

cli help: document the `ci` alias

---

lib/src/default_index/revset_engine.rs
lib/tests/test_revset.rs

From Discord discussion: https://discord.com/channels/968932220549103686/968932220549103689/1396106445153374249
If applicable:

revset_engine: evaluate `X` as predicate in `reachable(X, Y)`

---

CHANGELOG.md
docs/revsets.md
lib/src/default_index/revset_engine.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: add naive version of `bisect()` function

---

cli/src/commands/git/clone.rs
cli/src/commands/git/init.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_init.rs

We hear every now and then from users who have run `git clean -fdx` and accidentally delete their repo. Let's at least warn users about it when the create a colocated repo.
We could perhaps allow the `.jj/` directory to be inside a `.git/` directory like Sapling does, but that seems a little ugly and it's a larger change.
If applicable:

cli: print warning about `git clean -fdx` when creating colocated repo

---

lib/src/revset.rs

Negated `first_ancestors()` can't be converted to a range currently, so it doesn't make sense to move it to the start when optimizing the order of an intersection.
If applicable:

revset: don't reorder `~first_ancestors(x)` to start

---

cli/testing/bench-revsets-git.txt
lib/src/revset.rs

This allows evaluating ancestors/ranges involving filters significantly faster. For instance, naively evaluating `::mine()` requires reading every commit in the repo to check `mine()` on each commit, then finding the ancestors of that set. This optimization rewrites `::mine()` to `::heads(mine())`, since `heads(mine())` can be evaluated more efficiently by only reading commits until the first successful match.
If someone is unaware of how revsets are implemented, this case can come up pretty easily, such as by including `~mine()` in `immutable_heads()` to make other people's commits immutable. In my local `jj` repo, this optimization reduces the runtime of `jj log` with `~mine()` in `immutable_heads()` from about 800ms down to about 50ms.
Benchmark results on Git repo:
``` …
```

revset: insert `HeadsRange` in `Ancestors` for nested range/filter 

---

docs/revsets.md
docs/templates.md

docs: display optional arguments more simply
I was initially planning to try adding an `nth` keyword argument to `parents()` instead of adding `first_parent()`, and I noticed that based on the current style, it would have been shown as one of the following in the revset documentation:
* `parents(x[, depth[, [nth=]index]])`
* `parents(x[, depth][, [nth=]index])`
These both seem difficult to read to me, so I'm proposing changing the style to something more like this:
* `parents(x, [depth], [[nth=]index])`
I also added a brief section explaining the syntax in case it isn't immediately obvious what the square brackets mean.
If applicable:

docs: display optional arguments more simply

---

cli/src/commands/restore.rs
cli/tests/test_restore_command.rs

Commands like `diff`, `squash` and `restore` are directional, taking `--from` and `--to`/`--into` parameters. The former two also support `-r`, as a shortcut when one wishes to operate on a revision in relation to its parent(s).
Users who know that might deduce then that `restore` would also support `-r`, but it doesn’t — at some point it was decided that `-r` would be ambiguous, and people could attempt `restore -r <revision>` when they actually mean `-f`. Searching for “restore r” on Discord, I found a few old messages where people seemingly made this exact mistake, so I presume it’s a fair concern, particularly for a command that could be so critical to newcomers.
The command does know people may try to use `-r`, though, and rathern than showing a generic “unexpected argument” error, …

restore: adjust error message for `--revision`

---

CHANGELOG.md
cli/src/commands/fix.rs
cli/src/config.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_fix_command.rs
docs/config.md

On Windows, spawning a child process finds the command relative to the parent's working directory. If a command is specified as `["path/inside/repo/tool.exe"]`, then tool won't be found if `jj fix` is run somewhere besides the workspace root.
There doesn't seem to be a good way to change this behavior, nor does it seem easy to convert `program` into an absolute path because `["tool.exe"]` could refer either to a file on the PATH or a file committed at the root of the repository.
So, we add a new variable `$root` that can be used in this situation. Workspace-relative tools on Windows should be defined using this variable:
```toml
command = ["tool.exe"]
command = ["$root/tool.exe"]
command = ["$root/nested/dir/tool.exe"]
```
On Unix, the command is relative to the child's working directory, …

fix: add `$root` variable that can be used in commands

---

docs/git-compatibility.md

Document the Windows specific issue that leads to #7176, with an appropriate alternative.
(I tried to build the docs but that's a faff on Windows too because of symlinks... So I hope it works!)

Fix 7176, document colocating a repo in Windows

---

lib/src/repo_path.rs

The problem was that the calculation of the suffix was overlapping into the the prefix for nested directories with the same name. We skipped the prefix to avoid this issue.
Closes: #6853
If applicable:

copy-tracking: fix path tracking for nested directories with equal names

---

.github/workflows/pr.yml

Adds a CI workflow that ensures commits within pull requests have subject lines formatted as `area or areas: Description of changes`.
When commits are not properly formatted, fails CI and leaves a review comment with the bad commits. The message is updated with all bad commits each push.
When commits are properly formatted, passes CI and dismisses any existing review from the workflow.
Thanks @thoughtpolice for the prior art: https://github.com/thoughtpolice/buck2-nix/blob/main/.github/workflows/pr.yml
If applicable:

github: Enforce commit subject line format

---

Cargo.lock

cargo: bump zerovec because previous version is yanked

---

CHANGELOG.md
cli/src/commands/git/clone.rs
cli/src/commands/git/init.rs
cli/src/config-schema.json
cli/tests/cli-reference@.md.snap
cli/tests/test_git_clone.rs
cli/tests/test_git_init.rs
docs/config.md
lib/src/config/misc.toml
lib/src/settings.rs

Closes #2507.
This is based on #2512.
That PR hasn't seen any love in a year, so I'm opening this to nudge it along :slightly_smiling_face:
The only things I changed compared to Austin's work are:
- Rebase on main, resolve merge conflicts and other breakages.
- Add two tests, one for `init` and one for `clone`.
@thoughtpolice Please let me know if you'd like me to handle your Signed-off-by trailer differently, I kept it as is for now.
Also related: My FR to colocate repos by default (#7189).
Apparantly the plan was to do that anyway once this config option lands.
I would be very happy about that!
If applicable:

git: add `git.colocate` to colocate repos by default

---

CHANGELOG.md
cli/src/diff_util.rs
cli/tests/test_diff_command.rs

This makes `jj diff --stat` show text like `(binary) +123 bytes` for binary files, rather than the current behavior of counting the newlines within the binary files.
If applicable:

make diff --stat show byte counts for binary files

---

cli/src/commands/describe.rs
cli/tests/cli-reference@.md.snap

This change adds a note about `--reset-author` also updating the author timestamp to the short description, rather than it only being buried in the long description. This came up from a discussion on Discord.
If applicable:

cli describe: Clarify short description for `--reset-author`

---

lib/src/fix.rs
lib/src/rewrite.rs

As a follow-up to https://github.com/jj-vcs/jj/pull/7184#discussion_r2272345293
If applicable:

lib: rename mut_repo() to repo_mut() in the rewriter

---

cli/tests/runner.rs
cli/tests/test_op_revert_command.rs
cli/tests/test_undo.rs

undo: move or duplicate tests to `op revert`

---

docs/style_guide.md

style-guide: say that we prefer lower-level tests over e2e test

---

cli/src/commands/util/exec.rs
cli/src/commands/workspace/add.rs

The only two cases where PathCompleter was used were simple enough to be replaced with clap::ValueHint directly (which is more consistent with all the other completion hints used everywhere else)
Follow up from https://github.com/jj-vcs/jj/pull/7335#discussion_r2296383976
If applicable:

cli: use clap::ValueHint over PathCompleter

---

CHANGELOG.md
README.md
cli/src/commands/operation/mod.rs
cli/src/commands/operation/revert.rs
cli/src/commands/undo.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_duplicate_command.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_import_export.rs
cli/tests/test_squash_command.rs
cli/tests/test_touch_command.rs
cli/tests/test_undo.rs
demos/operation_log.svg
docs/operation-log.md
docs/tutorial.md

undo: revert progressively older operations with repeated calls

---

lib/src/local_working_copy.rs

working_copy: Move `TreeState` struct definition closer to impl block

---

CHANGELOG.md
cli/src/command_error.rs
cli/src/commands/git/clone.rs
cli/src/commands/git/fetch.rs
cli/src/commands/git/mod.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_git_fetch.rs
lib/src/git.rs
lib/src/git_subprocess.rs
lib/tests/test_git.rs

Fixes https://github.com/jj-vcs/jj/issues/5323
Only fetch refspecs matching a very conservative set of patterns (i.e. no branch or remote renames, must be a forced refspec for `refs/heads/`, etc) is supported and everything outside of that will be (warned about) and ignored. We can always expand these in the future but for now it would be good to avoid ambiguities about how branch renaming ought to be handled.
If applicable:

cli: git fetch: fall back to remote fetch refspecs when -b not specified

---

CHANGELOG.md
cli/src/commands/squash.rs
cli/tests/cli-reference@.md.snap

See also https://github.com/jj-vcs/jj/pull/7162#issuecomment-3212555183
@glehmann, thanks for making this feature! Would you be OK with marking it as experimental for now?
As explained in the above link, I think the UI you created is great for experimenting with this feature, but not as good for new users learning how to `squash`. At the same one, improving the it does not seem trivial, and to do it well, we could benefit from people taking some time to experiment with the feature.
If applicable:
- (n/a) I have updated the config schema (`cli/src/config-schema.json`)

cli `squash`: mark `-A`/`-B`/`-d` options as experimental, add brief doc pointer to use them with `--from`

---

CHANGELOG.md
lib/src/default_index/store.rs
lib/src/file_util.rs
lib/src/local_working_copy.rs

file_util: insert fdatasync() before persisting temporary files

---

cli/tests/test_config_command.rs
docs/config.md
lib/src/config.rs

I tested this manually with both taplo and tombi, both work well with the comment directive. For example, running `jj config edit --repo` in a throwaway repo will open a new config with the generated directive in your editor, which allows for testing this easily.
If applicable:

config: use schema directive comment

---

cli/examples/custom-working-copy/main.rs
cli/src/cli_util.rs
cli/src/commands/sparse/mod.rs
cli/src/commands/workspace/add.rs
cli/src/merge_tools/diff_working_copies.rs
cli/src/merge_tools/external.rs
lib/src/config/misc.toml
lib/src/eol.rs
lib/src/local_working_copy.rs
lib/src/working_copy.rs
lib/src/workspace.rs
lib/tests/test_eol.rs
lib/tests/test_local_working_copy.rs
lib/tests/test_local_working_copy_concurrent.rs
lib/tests/test_local_working_copy_sparse.rs

This was reworked from #7244 
This would be the foundation for moving the `fsmonitor_settings` (and friends) out of the `SnapshotOptions`, however doing so requires updating the way we use it while testing and I'd prefer to avoid adding a new testing interface for that without prior design work. And I may leave that for another contributor
If applicable:

working_copy: Break out `TreeStateConfig` struct and move to `LocalWcSettings`

---

.config/mise.toml
.gitignore
Cargo.toml
docs/contributing.md

This is a continuation of #6081
I've tried to use the task hierarchy proposed by @arxanas in https://github.com/jj-vcs/jj/pull/6081#discussion_r2019971617 and used the `[vars]` to define the tool versions in the tasks.
The tools are only declared in each task in order to be able to build the docs without installing the rust toolchain for example.
There are still a few things that could be better:
* `mise run 'check:*'`  output is completely flooded by the `nextest` output when using the recommended `cargo insta test --test-runner nextest`, and it becomes difficult to find the output of the other failed checks. Moreover, the check outputs are losing the coloring.
* I'm not sure how to name the tasks using `bacon`
If applicable:

dev: add mise config

---

docs/git-compatibility.md
docs/github.md

This allows links to point to other pages in the generated mkdocs documentation output instead of pointing to external GitHub URLs.
If applicable:

docs: use relative links to Markdown files instead of linking to GitHub

---

CHANGELOG.md
cli/src/commands/commit.rs
cli/src/commands/describe.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_config_command.rs
cli/tests/test_describe_command.rs

previously discussed here: https://github.com/jj-vcs/jj/pull/7184#issuecomment-3189378788

cli: deprecate metaedit-functionality of commit and describe

---

lib/src/local_working_copy.rs

local_working_copy: remove stale clippy exemption

---

lib/src/local_working_copy.rs
lib/tests/test_local_working_copy.rs

tests: rewrite test_fsmonitor() to use TreeState API

---

CHANGELOG.md
cli/src/commands/gerrit/mod.rs
cli/src/commands/gerrit/upload.rs
cli/src/commands/mod.rs
cli/src/config-schema.json
cli/tests/cli-reference@.md.snap
cli/tests/runner.rs
cli/tests/test_gerrit_upload.rs

This is an update of PR #2845 created by @thoughtpolice, who said they didn't have enough time to finish their PR.
Main changes:
* Completely removed footer, as the concept of a "trailer" has since been introduced natively into jj.
* The git module appears to have changed, so some refactoring was required there
* Applied requested changes to the PR
* Added support for sending stacked changes.

cli: implement jj gerrit upload for sending changes to Gerrit

---

CHANGELOG.md
cli/src/commands/bookmark/create.rs
cli/src/commands/bookmark/move.rs
cli/src/commands/bookmark/set.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_bookmark_command.rs

@PhilipMetzger got this ball rolling with #7364, but he doesn't have time to get it over the finish line. By plan is to follow this up with a better warning / hint if people move bookmarks to an empty `@`, which is likely a mistake: https://github.com/jj-vcs/jj/issues/5374#issuecomment-3217160017

cli bookmark: un-deprecate default revset arguments

---

cli/src/commands/bookmark/list.rs

After updating nightly rust, this code generates a false positive (below). AFAICT, the new code is only a little more consistent, but it avoids the warning.
The warning is:
```
warning: unneeded cloning of iterator items
--> cli/src/commands/bookmark/list.rs:251:19
|
251 |           commits = bookmark_list_items
|  ___________________^
252 | |             .iter()
253 | |             .filter_map(|item| item.primary.target().added_ids().next())
254 | |             .cloned()
...   |
258 | |                     .map(|commit| (commit_id, commit.store_commit().clone()))
259 | |             })
| |______________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_iter_cloned
= note: `#[warn(clippy::redundant_iter_cloned)]` on by default …
```

nightly clippy: avoid false positive

---

lib/src/protos/simple_op_store.proto
lib/src/protos/simple_op_store.rs

op_store: remove stale TODO about renamed remote and view state

---

CHANGELOG.md
lib/src/git_subprocess.rs

This fixes the following bug.
I have `submodule.recurse=true` set in my `.gitconfig`. When trying to fetch repos with submodules (e.g. https://github.com/git/git), I get errors like these:
```console
$ jj git fetch
remote: Enumerating objects: 853, done.
remote: Total 853 (delta 448), reused 439 (delta 413), pack-reused 315 (from 2)
Error: Git process failed: External git program failed:
Could not access submodule 'sha1collisiondetection'
```
This error occured when fetching only, *not* when cloning. It occured even when there wasn't anything to fetch.
I only tested repositories that never had submodules initialized or fetched (which would have to be done with Git).
If applicable:
- (n/a) I have updated the documentation (`README.md`, `docs/`, `demos/`)
- (n/a) I have updated the config …

git_subprocess: make sure we do not try to fetch submodules regardless of .gitconfig

---

CHANGELOG.md
cli/src/commands/config/get.rs
cli/tests/test_config_command.rs

Up until now, trying to get a config value that was an array or a table would fail with an error indicating that only values that can be converted to a string can be displayed. This change fixes that issue by converting arrays and tables into TOML format.
If applicable:
- [ x] I have updated `CHANGELOG.md`
- [ x] I have added/updated tests to cover my changes

config get: add support for displaying arrays and tables

---

cli/build.rs

cli: lazily emit cargo:rerun-if-changed to avoid spurious rebuilds

---

CHANGELOG.md
cli/src/config/merge_tools.toml
cli/src/merge_tools/external.rs
cli/tests/test_resolve_command.rs
docs/config.md

This follows Git's merge driver interface which makes this information available using the `%P` variable. It is useful for merge drivers to adapt their behaviour based on the type of file supplied.
The motivation for this is that Mergiraf uses this information to determine the format of the file and parse its revisions accordingly. When the file format is determined by the file extension only, there is no need for this extra information as the file names of the base, left and right revisions will still have this extension (such as `base_main.rs`, `left_main.rs`, `right_main.rs`). But for files where the format is recognized by matching the entire file name, this will not work: `base_Makefile` isn't recognized on its own. However, when `-p src/Makefile` is provided, the tool is able to …

external_merge: pass the repo_path to the merge tool

---

cli/src/commands/bisect/run.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_bisect_command.rs
lib/src/bisect.rs

Inverting the condition for `jj bisect run` can be useful in cases where you might look for "when was this thing created" using `grep`/`ls` or similar. In such cases you are looking for when the check turned good.
The motivation for this is that inverting the exit code of a program is cumbersome, and even worse error-prone considering that `jj` places special consideration on some exit codes. So doing a naive thing that maps all >0 errors to 0 loses information that `jj` would have used.
I added very basic tests, not sure how much more valuable additional tests would be. If the existing bisect tests are at some point extended with more complicated cases a corresponding inverted test could be added.
If applicable:

bisect: Make bisect able to search for first good/bad revision in the range

---

CHANGELOG.md
cli/src/commands/metaedit.rs
cli/tests/test_metaedit_command.rs

I also added a test. I made a separate test case because that's how I was able to reproduce the issue.
If applicable:
- [x ] I have updated `CHANGELOG.md`
- [ x] I have added/updated tests to cover my changes

fixes #7602: calling `jj metaedit --author-timestamp` twice should not edit twice

---

CHANGELOG.md

I was updating the changelog for another PR and noticed that the links were out of sync.
If applicable:

changelog: Update links for v0.34.0 release

---

CHANGELOG.md
cli/src/commands/log.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_log_command.rs

cli: log `-G` is now the short form of `--no-graph`

---

cli/src/template_builder.rs

templater: remove unneeded special case from string.split() method

---

docs/config.md

Update `draft_commit_description` since a) we can use `separate` instead of `concat` to handle joining newlines and b) `builtin_draft_commit_description` already coalesces the description and includes the diff stats.
If applicable:

docs: update default-description to be more concise

---

cli/src/commit_templater.rs
cli/src/config/templates.toml
cli/tests/test_log_command.rs
docs/templates.md

Remote names are potentially sensitive? Unsure, so better to redact them.
For getting the "*": This could have been done without modifying the Rust side, with e.g. `stringify(bookmark).ends_with("*")`. However, this feels brittle.
With adding `.synced()` to the template language, bookmark formatting _could_ be done entirely in templates now. I don't know if that's desired, so leaving for a potential future commmit.
If applicable:

templates: add remote and `*` to bookmarks in `builtin_log_redacted`
