lib/src/fileset.rs

fileset: remove Eq + PartialEq from FilesetExpression/Pattern

---

docs/FAQ.md

If applicable:
~- [ ] I have updated `CHANGELOG.md`~
~- [ ] I have updated the documentation (README.md, docs/, demos/)~
~- [ ] I have updated the config schema (cli/src/config-schema.json)~
~- [ ] I have added tests to cover my changes~

docs/FAQ: fix incorrect change ID for commit removed as parent

---

cli/src/cli_util.rs
cli/src/commands/debug/revset.rs
cli/src/commit_templater.rs
cli/src/diff_util.rs
cli/src/merge_tools/builtin.rs
lib/src/backend.rs
lib/src/default_index/store.rs
lib/src/git.rs
lib/src/git_backend.rs
lib/src/hex_util.rs
lib/src/merge.rs
lib/src/object_id.rs
lib/src/op_store.rs
lib/tests/test_revset.rs
lib/testutils/src/lib.rs

impl Display on ObjectId, simplify reverse hex

---

cli/src/commands/config/mod.rs

cli: leverage clap's default ArgGroup to handle config --user|--repo

---

lib/src/default_index/rev_walk.rs
lib/src/default_index/revset_engine.rs
lib/src/default_index/revset_graph_iterator.rs
lib/src/revset.rs

revset: propagate errors from filter predicates

---

flake.nix

Reported by EsperLily in Discord.
My personal machine is seeing strange testsuite failures, so I'm posting this just to see how the CI goes.

nix: only use `rust-src` in `devShell` toolchain

---

cli/src/diff_util.rs
cli/tests/test_acls.rs
lib/src/local_working_copy.rs

trivial cleanup of workspace-related errors

---

cli/src/commands/bookmark/list.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_bookmark_command.rs

cc @samueltardieu
If applicable:

cli: bookmark list: refactor, and adjust `--remote` filter conditions

---

docs/FAQ.md

The current instructions ask the reader to convert the merge commit into a single-parent commit, then create a new merge.
It is probably simpler to follow instructions for inserting a new commit before the merge commit.
If applicable:

docs: Simplify instructions for using private commits

---

CHANGELOG.md
cli/src/config/templates.toml
cli/tests/test_evolog_command.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
cli/tests/test_show_command.rs
cli/tests/test_templater.rs
docs/config.md

Default template alias to show full description

---

lib/src/annotate.rs
lib/tests/runner.rs
lib/tests/test_annotate.rs

add lib tests for annotation function

---

lib/src/annotate.rs

annotate: merge map keyed by commit id, inline small functions

---

lib/src/annotate.rs
lib/tests/test_annotate.rs

annotate: refactor, fix propagation of duplicated lines at fork/merge point

---

cli/src/commands/file/annotate.rs
lib/src/annotate.rs
lib/tests/test_annotate.rs

annotate: do not collect result lines into Vec, return Iterator instead

---

docs/git-comparison.md

Just a small addition to the docs because this felt like a missing piece in the "cheatsheet"
If applicable:

docs: include remote add command

---

CHANGELOG.md
cli/src/commands/git/init.rs
cli/src/config-schema.json
cli/tests/test_bookmark_command.rs
cli/tests/test_builtin_aliases.rs
cli/tests/test_commit_template.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_init.rs
cli/tests/test_git_private_commits.rs
cli/tests/test_git_push.rs
cli/tests/test_init_command.rs
docs/design/tracking-branches.md
lib/src/settings.rs

bookmarks: add support for `git.auto-local-bookmark` (to match docs)

---

cli/src/commands/rebase.rs

rebase: fix typo

---

docs/working-copy.md

docs: add more detail to section about stale working copies

---

lib/tests/test_bad_locking.rs
lib/tests/test_commit_concurrent.rs
lib/tests/test_git.rs
lib/tests/test_index.rs
lib/tests/test_load_repo.rs
lib/tests/test_local_working_copy.rs
lib/tests/test_local_working_copy_concurrent.rs
lib/tests/test_workspace.rs
lib/testutils/src/lib.rs
lib/testutils/src/test_backend.rs

testutils: remove global TestBackendData mapping

---

lib/src/diff.rs

diff: extract hunk_ranges() iterator

---

docs/FAQ.md

[Discord Source](https://discord.com/channels/968932220549103686/968932220549103689/1302304018189521017)
[Rendered](https://github.com/martinvonz/jj/blob/pm/push-rluuuwpzszyz/docs/FAQ.md)
cc @martinvonz

FAQ: Mention when users should use `jj-lib` or integrate via the CLI

---

lib/src/local_working_copy.rs
lib/src/repo_path.rs
lib/tests/test_local_working_copy.rs

local_working_copy: lstat() path to test file existence if creation failed

---

CHANGELOG.md
Cargo.lock
Cargo.toml

I did some minor copy editing, mostly to group new features related commands, revsets, and templates near each other.
We have a security fix that I will merge before this PR. It's currently in a private repo.
If applicable:

release: release version 0.23.0

---

.github/workflows/release.yml

github: run release workflow on publish and edit

---

.github/workflows/release.yml

github: don't run release workflow after editing release

---

cli/src/commands/rebase.rs
cli/tests/test_rebase_command.rs

cli: error when `jj rebase -b` is used without `--destination`

---

CHANGELOG.md
cli/src/template.pest
cli/src/template_builder.rs
cli/src/template_parser.rs
cli/tests/test_templater.rs
docs/templates.md

template: add support for logical equality operator

---

cli/examples/custom-commit-templater/main.rs
cli/src/cli_util.rs
cli/src/commands/bench/revset.rs
cli/src/commands/new.rs
cli/src/commands/rebase.rs
cli/src/commit_templater.rs
cli/src/movement_util.rs
cli/src/revset_util.rs
lib/src/id_prefix.rs
lib/src/revset.rs
lib/tests/test_revset.rs

Supersedes https://github.com/martinvonz/jj/pull/4374
If applicable:

revset: introduce type-safe user/resolved expression states

---

cli/examples/custom-commit-templater/main.rs
cli/src/cli_util.rs
cli/src/commands/bench/revset.rs
cli/src/commands/debug/revset.rs
cli/src/commands/fix.rs
cli/src/commands/new.rs
cli/src/commands/rebase.rs
cli/src/commit_templater.rs
cli/src/movement_util.rs
cli/src/revset_util.rs
cli/tests/test_debug_command.rs
lib/src/annotate.rs
lib/src/git.rs
lib/src/id_prefix.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/rewrite.rs
lib/tests/test_revset.rs

revset: reorganize expression resolution/evaluation methods

---

cli/src/commands/rebase.rs
cli/tests/test_rebase_command.rs
lib/src/rewrite.rs

rebase: allow `-r` with `--skip-emptied`

---

docs/contributing.md
docs/design/run.md
docs/templates.md

docs: fix a few typos noticed by automation at Google

---

cli/src/commands/next.rs
cli/src/commands/prev.rs
cli/tests/cli-reference@.md.snap

next/prev: delete obsolete help text about inferring --edit

---

cli/tests/test_config_command.rs
lib/tests/test_git.rs

test_git: fix some clippy ref errors

---

cli/src/cli_util.rs
cli/tests/test_git_clone.rs

cli: do not swallow error when checking working copy that became immutable

---

cli/src/config-schema.json

config-schema: add missing docs for auto-track

---

CHANGELOG.md
cli/src/commit_templater.rs
cli/src/generic_templater.rs
cli/src/operation_templater.rs
cli/src/template.pest
cli/src/template_builder.rs
cli/src/template_parser.rs
cli/tests/test_templater.rs
docs/templates.md

templater: add abstraction for equality operation, add `!=` operator

---

Cargo.lock
Cargo.toml
deny.toml
lib/Cargo.toml
lib/src/lock/fallback.rs

fallback: replace use of `backoff` crate of by own implementation

---

cli/src/cli_util.rs
cli/tests/test_completion.rs

completion: resolve aliases

---

lib/src/repo.rs
lib/src/rewrite.rs
lib/tests/test_commit_builder.rs
lib/tests/test_mut_repo.rs
lib/tests/test_rewrite.rs

As suggested in https://github.com/martinvonz/jj/pull/4821.
If applicable:

repo: remove `MutableRepo::rebase_descendants_with_options` and `MutableRepo::rebase_descendants_return_map`

---

lib/tests/test_git.rs

tests: fix flakiness in shallow Git repo test

---

docs/install-and-setup.md

motivated by [this discussion](https://github.com/martinvonz/jj/pull/4737#discussion_r1839402140)
If applicable:

completion: improve docs for activation

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
lib/Cargo.toml

cargo: upgrade to `sapling-renderdag`

---

lib/src/local_working_copy.rs
lib/src/lock/fallback.rs
lib/src/lock/mod.rs
lib/src/lock/unix.rs
lib/src/op_heads_store.rs
lib/src/simple_op_heads_store.rs
lib/src/stacked_table.rs
lib/src/transaction.rs

lock: propagate error from lock(), remove panic from unlock path

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
lib/Cargo.toml
lib/src/git_backend.rs

 cargo: bump gix to 0.67.0

---

cli/src/commands/bookmark/list.rs
cli/src/commands/git/fetch.rs
cli/src/commands/git/push.rs
cli/src/commands/git/remote/remove.rs
cli/src/commands/git/remote/rename.rs
cli/src/commands/git/remote/set_url.rs
cli/src/complete.rs
cli/tests/test_completion.rs

completion: teach remote about existing names

---

cli/src/commands/git/fetch.rs
cli/src/commands/git/push.rs
cli/tests/test_completion.rs

These could've / should've been part of #4828, an oversight.
If applicable:

completion: teach git commands about bookmarks

---

cli/src/cli_util.rs
cli/src/commands/debug/operation.rs
cli/src/commands/operation/abandon.rs
cli/src/commands/operation/diff.rs
cli/src/commands/operation/restore.rs
cli/src/commands/operation/show.rs
cli/src/commands/operation/undo.rs
cli/src/complete.rs
cli/tests/test_completion.rs

completion: teach operation commands about ids

---

cli/src/commands/log.rs
cli/tests/cli-reference@.md.snap

log: describe the different graph node symbols in help text

---

cli/src/commands/log.rs
cli/tests/cli-reference@.md.snap

log: describe how to see all revisions, point to revset docs

---

docs/glossary.md

docs: try to clarify that changes are not a first-class concept

---

docs/community_tools.md

This PR contains two commits, one restores the alphabetical order in docs/community_tools.md, the other adds a blurb and link about jj-fzf, similar to the other tools.
If applicable:

Add jj-fzf to the community tools 

---

docs/git-compatibility.md

docs: say that support for Git's remote config is partial

---

README.md

I'm planning to ask the IRC channel for review and confirmation that they're OK with it before merging this.

README: add IRC badge

---

cli/src/cli_util.rs
cli/tests/test_completion.rs

completion: pad empty argument at $_CLAP_COMPLETE_INDEX

---

cli/src/commands/workspace/forget.rs
cli/src/complete.rs
cli/tests/test_completion.rs

completion: teach forget about workspaces

---

cli/src/commit_templater.rs
cli/src/git_util.rs
lib/src/default_index/revset_engine.rs
lib/src/default_index/store.rs
lib/src/git.rs
lib/src/matchers.rs

Gets rid of `.map_or(false, ...)`

nightly clippy fixes

---

.gitignore

Ignore .cargo/insta.yaml so folks to customize this locally.
See https://insta.rs/docs/settings/

Ignore .cargo/insta.yaml

---

docs/git-comparison.md

Add comparison for git blame and jj file annotate.
If applicable:

docs: git blame comparison

---

Cargo.lock
Cargo.toml
cli/src/config.rs

cargo: bump toml_edit to 0.22.22

---

cli/src/cli_util.rs
cli/src/command_error.rs
lib/src/gpg_signing.rs
lib/src/signing.rs
lib/src/ssh_signing.rs

signing: propagate config errors

---

cli/src/commands/simplify_parents.rs
cli/tests/test_simplify_parents_command.rs

cli: simplify-parents: avoid multiple rebases of the same commits

---

cli/src/cli_util.rs
cli/tests/cli-reference@.md.snap

cli: hyphenate "working-copy commit" in `--ignore-working-copy` help

---

lib/src/local_working_copy.rs

local_working_copy: fix documentation of `TreeState::snapshot()`

---

flake.lock

nix: flake update

---

cli/src/cli_util.rs
cli/src/commands/resolve.rs
cli/src/commands/status.rs
lib/src/merged_tree.rs
lib/tests/test_merged_tree.rs

Propagate errors from conflict iterator

---

cli/src/cli_util.rs
cli/src/commands/config/edit.rs
cli/src/commands/config/list.rs
cli/src/commands/config/mod.rs
cli/src/commands/config/path.rs
cli/src/commands/config/set.rs
cli/src/commands/config/unset.rs
cli/src/config.rs
cli/src/revset_util.rs
cli/tests/test_builtin_aliases.rs
lib/src/config.rs

config: extract layer management from cli LayeredConfigs to jj-lib

---

lib/src/local_working_copy.rs

local_working_copy: move comment about conflict file to the right place

---

cli/src/complete.rs
cli/tests/test_completion.rs

completion: include bookmarks and tags in revisions

---

cli/src/cli_util.rs
cli/src/commands/config/edit.rs
cli/src/commands/config/list.rs
cli/src/commands/config/set.rs
cli/src/commands/config/unset.rs
cli/src/complete.rs
cli/src/config.rs
cli/src/revset_util.rs
cli/tests/test_config_command.rs

config: replace LayeredConfigs with StackedConfig

---

Cargo.lock
Cargo.toml

cargo: bump gix and thiserror

---

lib/src/local_working_copy.rs

local_working_copy: minor code cleanup

---

cli/src/cli_util.rs
cli/src/commands/config/get.rs
cli/src/commands/config/list.rs
cli/src/commands/fix.rs
cli/src/config.rs
cli/src/merge_tools/mod.rs
cli/tests/test_config_command.rs
lib/src/config.rs
lib/src/settings.rs
lib/testutils/src/lib.rs

config: add StackedConfig method that looks up value from all layers, migrate settings API

---

lib/src/local_working_copy.rs

local_working_copy: factor out common visit_directory() parameters

---

cli/src/commands/commit.rs
cli/src/config/misc.toml

cli: move `ci` alias to config file

---

cli/src/commands/absorb.rs
cli/src/commands/bookmark/move.rs

These were simply forgotten in dd6479f104818513906b346e8909d76e956db038
If applicable:

completion: teach absorb and bookmark move about revisions

---

CHANGELOG.md

See commit message.
If applicable:

docs: add "Release highlights" section to latest release (v0.24.0)

---

docs/install-and-setup.md

docs: update installation docs to say that `cmake` is needed

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/config.rs
cli/tests/test_global_opts.rs

Better respect `$NO_COLOR`

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/complete.rs
cli/src/config.rs
cli/src/config/misc.toml
cli/src/merge_tools/mod.rs
cli/src/ui.rs
lib/src/config.rs
lib/tests/test_commit_builder.rs

config: don't use ConfigBuilder to merge tables, clean up one-line Ui functions

---

cli/src/config.rs

config: make AnnotatedValue test compatible with toml_edit::Value

---

cli/tests/test_working_copy.rs
lib/src/config.rs
lib/src/settings.rs

settings: explicitly convert integer to HumanByteSize 

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/fix.rs
cli/src/complete.rs
cli/src/formatter.rs
cli/tests/test_alias.rs
cli/tests/test_fix_command.rs
lib/src/config.rs
lib/src/settings.rs

config: replace `.get_table()` with `.table_keys()` and `.get([prefix, key])`

---

Cargo.lock

cargo: bump url and idna to address security advisory

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/command_error.rs
cli/src/config.rs
cli/tests/test_config_command.rs
cli/tests/test_fix_command.rs
cli/tests/test_global_opts.rs
lib/Cargo.toml
lib/src/config.rs
lib/testutils/Cargo.toml

config: add ConfigLoadError, replace uses of config::ConfigError

---

docs/FAQ.md
docs/bookmarks.md
docs/github.md

docs: suggest "jj bookmark move" where makes sense

---

cli/src/commands/rebase.rs
cli/tests/test_rebase_command.rs

Print "Nothing changed" in all no-op rebase cases

---

docs/git-compatibility.md
docs/working-copy.md

docs: mention "jj file untrack" in Git compatibility list

---

docs/github.md

First, describe that ::@ lists ancestors.
Second, to make the example useful, remote bookmarks need to be excluded with their ancestry, otherwise we would list a bunch of immutable commits without their bookmarks.
If applicable:
- [ x] I have updated the documentation (README.md, docs/, demos/)

Useful Revsets in docs/github.md: fix ::@ == ancestors and exclude bookmark ancestry

---

docs/working-copy.md

https://github.com/martinvonz/jj/blob/f87c6ed337bf6b274238671d38eaa0fa23f3ac93/cli/src/cli_util.rs#L1315
If applicable:

docs: fix incorrect gitignore path

---

README.md

Add links to release and license badges

---

cli/src/commands/git/push.rs
cli/tests/cli-reference@.md.snap

help: move "git push --remote" explanation to main paragraph, some clarification

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/commit.rs
cli/src/commands/describe.rs
cli/src/commands/file/track.rs
cli/src/commands/file/untrack.rs
cli/src/commands/git/clone.rs
cli/src/commands/git/import.rs
cli/src/commands/git/init.rs
cli/src/commands/git/push.rs
cli/src/commands/init.rs
cli/src/commands/log.rs
cli/src/commands/split.rs
cli/src/config/misc.toml
cli/src/git_util.rs
cli/tests/test_working_copy.rs
lib/src/settings.rs
lib/src/signing.rs

settings: inline CLI options to callers, propagate type error

---

CHANGELOG.md
cli/src/commands/absorb.rs
cli/src/commands/fix.rs
cli/src/commands/simplify_parents.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_absorb_command.rs
lib/src/absorb.rs
lib/src/commit.rs
lib/src/commit_builder.rs
lib/src/repo.rs
lib/src/rewrite.rs

absorb: abandon source commit if it becomes discardable

---

CHANGELOG.md
Cargo.lock
cli/src/cli_util.rs
cli/src/commands/git/clone.rs
cli/src/commands/git/init.rs
cli/src/commands/init.rs
cli/src/complete.rs
cli/src/config.rs
cli/src/git_util.rs
cli/tests/common/mod.rs
cli/tests/test_config_command.rs
lib/Cargo.toml
lib/src/git_backend.rs
lib/src/repo.rs
lib/src/workspace.rs
lib/tests/test_init.rs
lib/tests/test_workspace.rs

repo, workspace: use dunce::canonicalize() to normalize paths

---

cli/src/commands/log.rs
lib/src/graph.rs
lib/tests/test_revset.rs

graph: extract function that reverses graph edges

---

cli/src/commands/abandon.rs
cli/src/commands/describe.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_abandon_command.rs
cli/tests/test_describe_command.rs

cli: abandon, describe: parse -rREV option properly

---

cli/src/config.rs
cli/src/merge_tools/mod.rs
lib/src/config.rs
lib/src/config/README.md
lib/src/config/misc.toml
lib/src/fsmonitor.rs
lib/src/git_backend.rs
lib/src/gpg_signing.rs
lib/src/settings.rs
lib/src/ssh_signing.rs
lib/tests/test_commit_builder.rs
lib/tests/test_init.rs
lib/testutils/src/lib.rs

config: extract jj-lib's default values to embedded TOML file

---

cli/src/commands/config/list.rs
cli/src/config.rs
lib/src/config.rs

cli: config list: mark values overridden by table or parent value

---

cli/src/cli_util.rs

cli: minor code cleanup around `command.settings()`

---

docs/revsets.md

docs: fix typo in `builtin_immutable_heads()` description

---

docs/install-and-setup.md

Add a paragraph on how to install jj completions into Powershell.

---

flake.lock

Keeping the wheels greased.
If applicable:

chore: `nix flake update`

---

lib/src/settings.rs

settings: fall back to empty op hostname/username if default can't be obtained

---

cli/src/config.rs

cli: config: allow comma in bare TOML string

---

CHANGELOG.md
cli/src/commands/evolog.rs
cli/src/commands/log.rs
cli/src/commands/mod.rs
cli/src/commands/operation/log.rs
cli/src/commands/split.rs

cli: remove various deprecated commands/options

---

Cargo.lock
cli/Cargo.toml
cli/src/config.rs
cli/tests/test_global_opts.rs
lib/Cargo.toml
lib/src/config/misc.toml
lib/src/settings.rs

config: fall back to $USER if username couldn't be obtained by libc

---

CHANGELOG.md
cli/src/commands/restore.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_restore_command.rs

cli: restore: add --interactive flag

---

cli/src/commands/debug/mod.rs
cli/src/commands/file/mod.rs
cli/src/commands/git/init.rs
cli/src/commands/git/mod.rs
cli/src/commands/git/remote/mod.rs

cli: make commands sub modules private

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/git/clone.rs
cli/src/commands/git/init.rs
cli/src/commands/init.rs
cli/src/commands/operation/log.rs
cli/src/commands/workspace/add.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_init.rs
lib/src/settings.rs
lib/src/workspace.rs

cli: resolve settings for newly initialized/cloned workspace

---

cli/examples/custom-backend/main.rs
cli/examples/custom-working-copy/main.rs
cli/src/commands/bookmark/list.rs
cli/src/commands/bookmark/track.rs
cli/src/commands/commit.rs
cli/src/commands/debug/watchman.rs
cli/src/commands/describe.rs
cli/src/commands/evolog.rs
cli/src/commands/file/annotate.rs
cli/src/commands/fix.rs
cli/src/commands/git/fetch.rs
cli/src/commands/git/import.rs
cli/src/commands/git/push.rs
cli/src/commands/log.rs
cli/src/commands/operation/diff.rs
cli/src/commands/operation/show.rs
cli/src/commands/show.rs
cli/src/commands/simplify_parents.rs
cli/src/commands/split.rs
cli/src/commands/tag.rs
cli/src/movement_util.rs

cli: get settings from workspace where makes sense

---

cli/tests/test_root.rs
lib/tests/test_bad_locking.rs
lib/tests/test_commit_concurrent.rs
lib/tests/test_init.rs
lib/tests/test_local_working_copy.rs
lib/tests/test_local_working_copy_concurrent.rs
lib/tests/test_local_working_copy_sparse.rs
lib/tests/test_refs.rs
lib/tests/test_revset.rs
lib/tests/test_signing.rs
lib/tests/test_workspace.rs
lib/testutils/src/lib.rs

tests: add convenient method to initialize TestWorkspace with test settings

---

cli/src/cli_util.rs
cli/tests/test_alias.rs

cli: warn if command matches with aliases inserted by --config* arguments

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/config.rs
cli/src/config/misc.toml
cli/src/revset_util.rs
cli/tests/test_config_command.rs
docs/config.md
lib/src/config.rs
lib/src/config_resolver.rs

Back out "config: merge and print inline tables as values"

---

.github/workflows/build-nix.yml
.github/workflows/build.yml
.github/workflows/codespell.yml
.github/workflows/dependabot.yml

This will make sure the build on the main listing still looks clean, instead of previous builds being cancelled and making it look like things failed.
If applicable:

github: don't cancel concurrent builds on `main`

---

lib/src/files.rs
lib/src/merge.rs
lib/src/refs.rs
lib/src/tree.rs

Merge: make `trivial_merge()` take a single slice of interleaved terms

---

lib/src/files.rs
lib/src/merge.rs

merge: inline trivial_merge_inner()

---

cli/src/cli_util.rs
cli/src/commands/fix.rs
cli/src/commands/git/push.rs
cli/src/complete.rs
cli/src/config.rs
cli/src/config/misc.toml
cli/tests/test_git_push.rs
lib/src/config.rs
lib/src/config/misc.toml
lib/src/config_resolver.rs
lib/src/settings.rs

config: add simple migration logic to update deprecated variables

---

CHANGELOG.md
Cargo.lock
Cargo.toml
cli/src/commands/util/install_man_pages.rs
cli/src/commands/util/mod.rs
cli/tests/cli-reference@.md.snap
flake.nix

cli: util: rename `mangen` to `install-man-pages`

---

docs/git-comparison.md

docs: fix typo in in command

---

docs/install-and-setup.md

I didn't check the indentation as it _needs_ to be a codeblock to render correctly.
If applicable:

docs: fix the mkdocs admonition I recently added

---

docs/FAQ.md

A common question is asking how to show elided revisions. This FAQ explains why revisions are elided and how to display them.
If applicable:

docs: Explain what elided revisions are

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/config/list.rs
cli/src/commands/operation/log.rs
cli/src/commit_templater.rs
cli/src/generic_templater.rs
cli/src/operation_templater.rs
cli/src/template_builder.rs
cli/src/templater.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_templater.rs
docs/templates.md

Do we want this?
If applicable:

templater: add config(name) function

---

CHANGELOG.md
Cargo.lock
Cargo.toml

cc @emesterhazy
See: https://github.com/arxanas/scm-record/releases/tag/v0.5.0
If applicable:

cli: upgrade `scm-record` from v0.4.0 to v0.5.0

---

CHANGELOG.md
cli/src/commands/git/clone.rs
cli/src/commands/git/remote/add.rs
cli/src/commands/git/remote/set_url.rs
cli/src/git_util.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_git_remotes.rs

cli: git: store absolute remote path in config file

---

CHANGELOG.md
cli/src/commands/evolog.rs
cli/src/commands/log.rs
cli/src/commands/operation/diff.rs
cli/src/commands/operation/log.rs
cli/src/graphlog.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_operations.rs

cli: op log: add `--reversed` option

---

Cargo.lock
Cargo.toml
lib/src/git_backend.rs

cargo: bump gix to 0.69.1

---

cli/src/commands/describe.rs

This makes it clear that the rewritten commit will have the same tree as the original commit.
If applicable:

cli: describe: use `CommitRewriter::reparent`

---

cli/src/commands/git/push.rs
cli/src/config/misc.toml
cli/tests/cli-reference@.md.snap

cli: git: define default "git.private-commits" in config/misc.toml

---

docs/templates.md

docs templates: document the Email type methods in more detail

---

cli/src/commands/abandon.rs
cli/src/commands/operation/undo.rs
cli/src/commands/unsquash.rs
lib/src/git.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/src/transaction.rs
lib/tests/test_git.rs
lib/tests/test_id_prefix.rs
lib/tests/test_mut_repo.rs
lib/tests/test_rewrite.rs
lib/tests/test_view.rs

repo: propagate error of record_abandoned_commit()

---

docs/contributing.md

docs/contributing: fix incorrect bookmark name

---

cli/src/commands/rebase.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/tests/test_commit_builder.rs
lib/tests/test_mut_repo.rs
lib/tests/test_rewrite.rs
lib/testutils/src/lib.rs

repo: refactor `rebase_descendants_*()` API

---

CHANGELOG.md
cli/src/commands/restore.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_immutable_commits.rs
cli/tests/test_restore_command.rs
docs/FAQ.md

This is a part of #5394.
If applicable:

restore: add --into flag, make --to an alias to it

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/formatter.rs
docs/config.md

formatter: add support for italic text

---

CHANGELOG.md
docs/revsets.md
lib/src/default_index/revset_engine.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: add subject() predicate that matches first line of descriptions

---

CHANGELOG.md
cli/src/commands/abandon.rs
cli/src/commands/bookmark/delete.rs
cli/src/commands/rebase.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_abandon_command.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/tests/test_rewrite.rs

cli: abandon: delete bookmarks pointing to abandoned commits

---

cli/src/commands/rebase.rs
cli/tests/cli-reference@.md.snap

cli: rebase: say that `-r` allows set, clarify `-s X` vs `-r X::`

---

cli/src/commands/evolog.rs
cli/src/commands/log.rs
cli/src/commands/operation/log.rs
lib/src/graph.rs
lib/tests/test_revset.rs

 graph: make reverse_graph() accept separate node id type

---

cli/src/cli_util.rs
cli/src/command_error.rs
lib/src/config.rs
lib/src/config_resolver.rs

config: add more migration handlers

---

cli/src/commands/git/remote/list.rs
cli/src/git_util.rs

cli: migrate "git remote list" to gix

---

CHANGELOG.md
cli/src/commands/file/list.rs
cli/src/commit_templater.rs
cli/src/config/templates.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_acls.rs
cli/tests/test_commit_template.rs
docs/templates.md

cli: port "file list" to template

---

docs/config.md

Also includes a minor fixup further advertising Meld in a separate commit.
I initially had a section with more details, but then decided to move it to a gist.

config.md: document how to install Meld on a Mac 

---

CHANGELOG.md
cli/src/command_error.rs
cli/src/commit_templater.rs
cli/src/diff_util.rs
cli/tests/test_commit_template.rs

templater: load diff parameters from config file

---

CHANGELOG.md
cli/src/commit_templater.rs
cli/src/template_builder.rs
cli/tests/test_commit_template.rs
docs/templates.md

templater: add list.filter(predicate) method

---

docs/config.md

config.md: fixup to bb74a9e, `dehesselle` not `deheselle`

---

CHANGELOG.md
cli/src/commit_templater.rs
cli/src/diff_util.rs
cli/tests/test_commit_template.rs
docs/templates.md

templater: add diff.files() method

---

docs/install-and-setup.md

docs: fix typo in env variable `$COMPLETE`

---

cli/src/config-schema.json

config-schema.json: fixup to `default-command`

---

docs/technical/concurrency.md

docs: fix a mention of the deleted `jj checkout` command

---

Cargo.lock
Cargo.toml

cargo: bump gix to 0.70.0

---

cli/src/cli_util.rs
cli/src/commands/git/clone.rs

cli: git clone: reload workspace after configuring new remote

---

CHANGELOG.md
docs/config.md

docs: fix typo '--when.command' -> '--when.commands'

---

cli/src/diff_util.rs

diff: remove ad-hoc rename handling in show_diff_stat()

---

docs/install-and-setup.md

docs: point to jj-vcs for Nix install instructions

---

.github/workflows/build-binaries.yml
.github/workflows/release.yml

This will be more robust long term since e.g. native ARM runners use `ubuntu-24.04-arm` as their runner image, and the version number really isn't a big deal in this case.
If applicable:

github: replace some exact conditionals with prefix matches

---

lib/src/git.rs
lib/src/git_subprocess.rs

git: forward "remote: " lines when they arrive

---

docs/contributing.md

contributing.md: describe how to configure `jj fix` to run `rustfmt`

---

cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/commands/git/fetch.rs
cli/src/commands/git/mod.rs
cli/src/commands/git/push.rs
cli/src/commands/git/remote/list.rs
cli/src/git_util.rs
cli/tests/test_git_fetch.rs
lib/src/git.rs

git: reimplement get_all_remotes() by using gix API

---

cli/src/commands/git/clone.rs
cli/src/commands/git/fetch.rs
cli/src/commands/git/push.rs
cli/src/git_util.rs
lib/src/git.rs

git: enable sideband message callback globally

---

lib/src/git.rs
lib/src/git_subprocess.rs

git: test that local progress is emitted through callback

---

cli/src/command_error.rs
cli/src/commands/git/clone.rs
cli/src/commands/git/fetch.rs
cli/src/commands/git/push.rs
cli/src/git_util.rs
lib/src/git.rs
lib/src/git_subprocess.rs
lib/tests/test_git.rs

git: remove git2 from subprocess code path

---

docs/sapling-comparison.md

Update the comparison to sapling docs to take into account some of the features that have been added to jujutsu since they were last updated.
If applicable:
- [ x] I have updated the documentation (README.md, docs/, demos/)

Sapling comparison docs update

---

cli/src/complete.rs
cli/tests/test_completion.rs

based on #5539 
If applicable:

cli: complete: complete revset aliases

---

cli/src/commands/rebase.rs
cli/tests/cli-reference@.md.snap

rebase: fix grammar in doc comments

---

cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/commands/git/mod.rs
cli/src/revset_util.rs
cli/src/template_builder.rs
cli/src/template_parser.rs
cli/tests/test_alias.rs
cli/tests/test_bookmark_command.rs
cli/tests/test_commit_template.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_import_export.rs
cli/tests/test_git_init.rs
cli/tests/test_git_push.rs
cli/tests/test_global_opts.rs
cli/tests/test_immutable_commits.rs
cli/tests/test_log_command.rs
cli/tests/test_new_command.rs
cli/tests/test_rebase_command.rs
cli/tests/test_revset_output.rs
cli/tests/test_templater.rs
cli/tests/test_workspaces.rs
lib/src/dsl_util.rs
lib/src/fileset.rs
lib/src/fileset_parser.rs
lib/src/revset.rs
lib/src/revset_parser.rs
lib/src/str_util.rs
lib/src/time_util.rs
lib/tests/test_revset.rs

revset: escape symbols in "did you mean" hint

---

cli/src/commands/bookmark/list.rs

Noticed while importing the latest version into the Google repo (some of our tests failed).
If applicable:

cli: bookmarks: don't show Git hint in non-Git repos

---

CHANGELOG.md
cli/src/commit_templater.rs
cli/src/diff_util.rs
cli/tests/test_commit_template.rs
docs/templates.md

templater: add DiffStats type to provide raw stats values

---

docs/releasing.md
mkdocs.yml

docs: describe how to do a release

---

docs/install-and-setup.md

docs/install-and-setup: clarify wording re: binaries of latest GitHub release

---

lib/src/git_subprocess.rs

git: enable sideband progress on subprocess push

---

CHANGELOG.md
Cargo.lock
Cargo.toml

release: 0.26.0

---

.github/workflows/build.yml

github: fix build step names to use imperatives

---

docs/git-comparison.md

People moving from git may want to know what is the `jj` equivalent of `git merge`.
If applicable:

Add git merge to the git command equivalence table

---

docs/FAQ.md

faq: fix quoting of `git.private-commits` example

---

cli/src/merge_tools/builtin.rs

cli: delete unused variants of `BuiltinToolError`

---

docs/git-command-table.md

docs: undo another mistaken "branch->bookmark" change

---

cli/src/config/merge_tools.toml

Add difftastic as diff tool

---

lib/src/git_subprocess.rs

git: trim trailing space in sideband messages received from git subprocess

---

cli/tests/test_split_command.rs

We are planning to add a config option that controls how bookmarks and change ids move during `jj split` based on feedback in https://github.com/jj-vcs/jj/pull/5618. I think the tests will be more readable after the config option is added if we move the bookmark testing to its own test.
#3419

cli split: Move bookmark testing to a separate test

---

CHANGELOG.md
cli/src/template_builder.rs
docs/templates.md

fix #5648 
Feel free to reject or discuss more if it is needed. I was not sure about the process of FRs so I submitted the PR.
If applicable:

templater: add .escape_json method to string

---

CHANGELOG.md
cli/src/template_builder.rs
docs/templates.md

templater: add stringify(x) function to call string methods on template

---

cli/tests/common/git.rs
cli/tests/test_git_init.rs

tests: minor code cleanup in git tests

---

CHANGELOG.md
cli/src/commands/backout.rs
cli/src/config/templates.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_backout_command.rs

cli: backout: add `templates.backout_description` configuration

---

cli/src/commands/git/clone.rs
cli/src/commands/git/remote/add.rs
cli/src/commands/git/remote/set_url.rs

completion: mark git remote arguments as URL instead of path

---

Cargo.lock
Cargo.toml

cargo: upgrade to latest streampager

---

CHANGELOG.md
cli/src/commands/file/annotate.rs
cli/src/commit_templater.rs
cli/src/config/templates.toml
cli/src/templater.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_file_annotate_command.rs
docs/templates.md

templater: port annotation line content to template

---

lib/src/default_index/store.rs
lib/src/local_backend.rs
lib/src/simple_op_store.rs

index, op_store: write temporary files in destination directory

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/config.rs
cli/tests/test_commit_template.rs
cli/tests/test_completion.rs
docs/config.md
lib/src/settings.rs
lib/src/signing.rs
lib/tests/test_signing.rs

Fixes https://github.com/jj-vcs/jj/issues/4561
Supersedes https://github.com/jj-vcs/jj/pull/5408 
If applicable:

signing: allow specifying sign behavior

---

cli/src/commands/operation/undo.rs
cli/tests/test_undo.rs

Fix warning for double-undoing

---

cli/src/commands/bookmark/set.rs
cli/tests/test_bookmark_command.rs

cli: bookmark: remove hint about upsert behavior

---

cli/src/cli_util.rs
lib/src/local_working_copy.rs
lib/src/working_copy.rs
lib/tests/test_local_working_copy.rs

Call `WorkingCopy::check_out()` also when tree is unchanged

---

cli/src/ui.rs

https://github.com/facebook/sapling/pull/1011 is in, yay! 🎉
Follows up on https://github.com/jj-vcs/jj/pull/5415 and https://github.com/jj-vcs/jj/pull/5711

streampager: stop uselessly reading the config file (fix a TODO)

---

cli/src/cli_util.rs
cli/src/commands/resolve.rs
cli/src/commands/status.rs
cli/tests/test_absorb_command.rs
cli/tests/test_diffedit_command.rs
cli/tests/test_file_chmod_command.rs
cli/tests/test_fix_command.rs
cli/tests/test_git_colocated.rs
cli/tests/test_repo_change_report.rs
cli/tests/test_resolve_command.rs
cli/tests/test_restore_command.rs
cli/tests/test_squash_command.rs
cli/tests/test_status_command.rs
cli/tests/test_working_copy.rs

cli: status: do not label message lines as "conflict"

---

cli/src/config/merge_tools.toml

Added as per Martin's suggestion: https://discord.com/channels/968932220549103686/969291218347524238/1341910959601614893
If applicable:

cli: add mergiraf to the default merge tools config

---

CHANGELOG.md
cli/src/command_error.rs
cli/src/commands/bookmark/create.rs
cli/src/commands/bookmark/rename.rs
cli/src/commands/bookmark/set.rs
cli/tests/test_bookmark_command.rs
cli/tests/test_revset_output.rs
cli/tests/test_split_command.rs
lib/src/revset.pest
lib/src/revset.rs
lib/src/revset_parser.rs

Closes #5705
cc @0xdeafbeef 
If applicable:

cli: parse bookmark name to be created/updated as revset symbol

---

lib/src/default_index/mod.rs
lib/src/file_util.rs
lib/src/git_backend.rs
lib/src/lib.rs
lib/src/local_backend.rs
lib/src/lock/mod.rs
lib/src/repo_path.rs
lib/src/simple_op_store.rs
lib/src/stacked_table.rs

Extracted from #3888
If applicable:

lib: internalize testutils::new_temp_dir() for unit tests

---

lib/tests/test_revset.rs

tests: rewrite change ID resolution test to not rely on git::import_refs()

---

lib/tests/test_revset.rs

tests: accept duplicated snapshots in test_resolve_symbol_change_id()

---

cli/tests/common/test_environment.rs
cli/tests/test_file_track_untrack_commands.rs
cli/tests/test_global_opts.rs
cli/tests/test_help_command.rs
cli/tests/test_operations.rs

tests: compare CommandOutput where makes sense

---

CHANGELOG.md
cli/src/commands/status.rs
lib/src/local_working_copy.rs

Fixes #5728
Fixes #5602
If applicable:

working_copy: do not update watchman clock if untracked files exist

---

lib/src/git_backend.rs

This forces some code duplication to avoid depending on the testutils.
If applicable:

lib: move git_backend tests to gitoxide

---

.github/workflows/docs.yml

Similar to #5792. We haven't had any updates to the GitHub pages since #5076, AFAICT.
If applicable:

github: fix invalid permission settings for docs workflow

---

cli/src/cli_util.rs
cli/src/commands/bookmark/forget.rs
cli/src/commands/bookmark/mod.rs
cli/src/commands/bookmark/track.rs
cli/src/commands/bookmark/untrack.rs
cli/src/commands/git/clone.rs
cli/src/commands/git/init.rs
cli/src/commands/git/mod.rs
cli/src/commands/git/push.rs
cli/src/commands/operation/diff.rs
cli/src/commands/status.rs
cli/src/git_util.rs
cli/tests/test_git_clone.rs
lib/src/git.rs
lib/src/refs.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/revset_parser.rs
lib/src/view.rs
lib/tests/test_git.rs
lib/tests/test_index.rs
lib/tests/test_mut_repo.rs
lib/tests/test_revset.rs
lib/tests/test_rewrite.rs
lib/tests/test_view.rs

view: introduce struct replacing `(name, remote)` tuple, quote `name@remote` as needed

---

lib/tests/test_git.rs

lib/tests: move remaining git test to gitoxide

---

lib/src/git.rs
lib/tests/test_git.rs

git: on reset_head(), check if the actual HEAD points to known location

---

cli/src/commands/sign.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_sign_unsign_commands.rs
lib/src/commit_builder.rs

Add `--key` argument to `jj sign`

---

lib/testutils/src/git.rs

tests: clean up `git::IndexManager` a bit

---

cli/src/commands/sign.rs
cli/src/commands/unsign.rs
cli/tests/cli-reference@.md.snap

Add link to docs in `jj sign` and `jj unsign`

---

cli/tests/test_git_colocated.rs
lib/testutils/src/git.rs

cli/tests: move test_git_colocated to gitoxide

---

CHANGELOG.md
cli/src/commands/git/fetch.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_git_fetch.rs
docs/config.md

cli `git fetch`: support string pattern syntax in `remote` option

---

cli/tests/test_operations.rs
lib/src/simple_op_store.rs

op_store: validate operation/view id length to detect corruption earlier

---

docs/git-compatibility.md

docs: update the docs to best describe the authentication compatibility

---

cli/src/commands/debug/mod.rs

cli: sort debug commands lexicographically

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/mod.rs
cli/tests/test_alias.rs
cli/tests/test_help_command.rs

Closes #5335
Closes #5701
If applicable:

cli: reimplement "jj revert" stub as error hint

---

docs/FAQ.md

It was requested on Discord recently.
The result is almost a tutorial; we could consider actually moving it into the tutorial and providing a link in the FAQ. That could be done separately.
The `jj` commands outputs are faked in a few, hopefully inconspicuous, ways.
Hopefully, this is not distracting.

FAQ: detailed example for the "accidentally changed files in the wrong commit" question

---

docs/working-copy.md

docs: correct description of tracking of ignored files

---

docs/community_tools.md

Added a link and blurb about the VS Code extension Jujutsu Kaizen

Update community_tools.md with link to VS Code extension Jujutsu Kaizen

---

lib/tests/test_rewrite.rs

This is in preparation for adding a new function that inverts the selection.
If applicable:

lib rewrite: Add a test for CommitWithSelection

---

cli/src/cli_util.rs

cli: pass clap::Error to map_clap_cli_error()

---

docs/config.md

This is hidden gem of a feature, especially in combination.
`JJ_CONFIG` being a directory allows loading multiple TOML config files. `--when` can be used on the top level, which can lend itself to a much cleaner config than `[[--scope]]` tables.

docs: Update documentation wrt JJ_CONFIG and --when/--scope

---

lib/src/rewrite.rs

rewrite: fix a Clippy lint

---

cli/tests/common/mod.rs
cli/tests/test_abandon_command.rs
cli/tests/test_backout_command.rs
cli/tests/test_duplicate_command.rs
cli/tests/test_file_chmod_command.rs
cli/tests/test_git_fetch.rs
cli/tests/test_rebase_command.rs
cli/tests/test_resolve_command.rs
cli/tests/test_restore_command.rs
cli/tests/test_simplify_parents_command.rs
cli/tests/test_status_command.rs

cli tests: move `create_commit()` tests helpers to common/

---

cli/src/commands/bookmark/list.rs
cli/src/commit_templater.rs

https://github.com/jj-vcs/jj/pull/5849
If applicable:

cli: bookmark: collect all list items to temporary vec

---

cli/tests/common/mod.rs
cli/tests/common/test_environment.rs
cli/tests/test_global_opts.rs

tests: add workspace test helper, use it in test_global_opts.rs

---

lib/src/git.rs

Thanks to @yuja for pointing me to this!
If applicable:

git: use `try_collect`

---

cli/tests/common/mod.rs
cli/tests/common/test_environment.rs
cli/tests/test_abandon_command.rs
cli/tests/test_backout_command.rs
cli/tests/test_duplicate_command.rs
cli/tests/test_file_chmod_command.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_import_export.rs
cli/tests/test_operations.rs
cli/tests/test_rebase_command.rs
cli/tests/test_resolve_command.rs
cli/tests/test_restore_command.rs
cli/tests/test_simplify_parents_command.rs
cli/tests/test_status_command.rs
cli/tests/test_undo.rs
cli/tests/test_util_command.rs

tests: use TestWorkDir in test_abandon_command.rs

---

cli/src/command_error.rs
cli/tests/test_revset_output.rs
docs/filesets.md

A few minor improvements based on things that momentarily confused me.
See also #5944

filesets: add details and rearrange docs and errors

---

CHANGELOG.md
cli/src/commands/diff.rs
cli/src/complete.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_diff_command.rs
docs/git-command-table.md

cli: diff: support multiple revisions to `-r`

---

docs/revsets.md
lib/src/fileset.pest
lib/src/revset.pest

Closes #2101
cc @avamsi
If applicable:

fileset, revset: settle on optionally-quoted pattern syntax

---

cli/tests/common/test_environment.rs
cli/tests/test_absorb_command.rs
cli/tests/test_acls.rs
cli/tests/test_advance_bookmarks.rs
cli/tests/test_alias.rs
cli/tests/test_backout_command.rs
cli/tests/test_bookmark_command.rs

tests: port absorb, acls, advance_bookmarks, alias, backout, bookmark to TestWorkDir API

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/operation/diff.rs
cli/src/commands/workspace/list.rs
cli/src/commit_templater.rs
cli/tests/test_operations.rs
lib/src/op_store.rs
lib/src/refs.rs
lib/src/repo.rs
lib/src/simple_op_store.rs
lib/src/view.rs

If applicable:
- ~~[ ] I have updated the documentation (README.md, docs/, demos/)~~
- ~~[ ] I have updated the config schema (cli/src/config-schema.json)~~

cli `op diff`: show changes to working copy positions

---

cli/src/commands/file/chmod.rs
cli/src/merge_tools/external.rs

@steadmon, I had these (and some similar ones) sitting in my repo. They should help a little with your work on copy info.
If applicable:

Prepare for preserving copy id

---

.github/workflows/dependabot.yml

Split off from https://github.com/jj-vcs/jj/pull/5992. See https://github.com/jj-vcs/jj/pull/5992#issuecomment-2716432632 for (temporary) caveats.
If applicable:

github: `dependabot` workflow changes

---

.github/workflows/ci.yml

First batch of my attempt to improve the user experience of our CI. See commit messages for details.
I don’t really entirely know what I’m doing, and GitHub Actions is really difficult to test, so it’s entirely likely some of this stuff will break things. Scrutiny is more than welcome. @martinvonz will have to follow the instructions in “github: add `result` job to `ci`” if this is approved.
If applicable:

github: add `required-checks` job to `ci`

---

.github/workflows/ci.yml
.github/workflows/required-checks-hack.yml

github: attempt to fix `required-checks`

---

cli/tests/test_builtin_aliases.rs
cli/tests/test_commit_command.rs
cli/tests/test_commit_template.rs

tests: port builtin_aliases, commit, commit_template to TestWorkDir

---

cli/src/config.rs

config: externalize ConfigPath::Unavailable variant

---

cli/tests/test_completion.rs
cli/tests/test_concurrent_operations.rs
cli/tests/test_config_command.rs
cli/tests/test_copy_detection.rs
cli/tests/test_debug_command.rs

tests: port completion, concurrent_operation, config, copy_detection, debug to TestWorkDir API

---

.github/workflows/dependabot.yml

Won’t fix the checks, but should hopefully return us to something slightly better than the previous status quo.
If applicable:

github: fix `dependabot` workflow

---

cli/src/commands/bookmark/list.rs
cli/src/commands/bookmark/track.rs
cli/src/commands/tag.rs
cli/src/commit_templater.rs
cli/tests/cli-reference@.md.snap
docs/templates.md

templater: rename RefName type to CommitRef

---

cli/src/commands/config/list.rs
cli/src/config/templates.toml
cli/tests/test_completion.rs
cli/tests/test_config_command.rs
cli/tests/test_evolog_command.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
cli/tests/test_show_command.rs
cli/tests/test_templater.rs
lib/src/config.rs

config: minor cleanup around new path/source template handling

---

cli/tests/test_describe_command.rs
cli/tests/test_diff_command.rs
cli/tests/test_diffedit_command.rs

tests: port describe, diff, diffedit to TestWorkDir API

---

cli/src/commands/config/mod.rs
cli/src/movement_util.rs
cli/src/ui.rs
cli/tests/test_next_prev_commands.rs

cli: print prompt candidates to stderr, simplify choice handling

---

lib/src/git_subprocess.rs

When using old git versions, some of the options we use (namely, --no-write-fetch-head #5933), we want to report that the comes from the outdated git, instead of cryptically failing.
Closes #5933
If applicable:

git: add error for inadequate git version

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/config.rs

tests: simplify config TestCase tests

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/backout.rs
cli/src/commands/mod.rs
cli/src/commands/revert.rs
cli/src/config/templates.toml
cli/tests/cli-reference@.md.snap
cli/tests/runner.rs
cli/tests/test_alias.rs
cli/tests/test_backout_command.rs
cli/tests/test_help_command.rs
cli/tests/test_revert_command.rs

cli: add revert command and deprecate backout command

---

cli/tests/common/command_output.rs
cli/tests/common/mod.rs
cli/tests/common/test_environment.rs
cli/tests/test_config_command.rs
cli/tests/test_debug_command.rs
cli/tests/test_diff_command.rs
cli/tests/test_global_opts.rs

tests: split CommandOutput to module, add sub-dir helper

---

lib/tests/test_ssh_signing.rs

tests: do not mark SSH private key as executable

---

cli/src/commands/debug/init_simple.rs

This is barely worth doing, but since I did it once...
I feel that some people might treat the simple backend as an easter egg, and this will help them know what to expect.

simple backend: document the lack of fetching and pushing

---

cli/src/ui.rs

ui: extract prompt_choice_with(..callback)

---

cli/src/cli_util.rs
cli/src/commands/sparse/mod.rs
cli/tests/test_global_opts.rs
cli/tests/test_workspaces.rs

cli: minor output formatting changes in `finish_transaction()`

---

.github/actions/setup-windows/action.yml
.github/workflows/ci.yml

Shaves another couple minutes off the Windows CI time.
If applicable:

github: use the `D:` drive on Windows

---

cli/tests/test_duplicate_command.rs
cli/tests/test_edit_command.rs
cli/tests/test_evolog_command.rs
cli/tests/test_file_annotate_command.rs
cli/tests/test_file_chmod_command.rs
cli/tests/test_file_show_command.rs

tests: port duplicate, edit, evolog, annotate, chmod, file show to TestWorkDir API

---

cli/src/commands/git/push.rs

cli: git-push: use RemoteRefSymbol to format and pass name@remote around

---

.github/workflows/binaries.yml
.github/workflows/ci.yml

github: build timeout tweaks

---

cli/tests/test_git_clone.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_import_export.rs

tests: port git clone, colocated, fetch, import/export to TestWorkDir API

---

README.md
docs/design/run.md
docs/design_docs.md
docs/glossary.md

doc: update some references to "the native backend"

---

lib/src/fix.rs

fix: avoid an unnecessary clone

---

cli/tests/test_git_init.rs
cli/tests/test_git_private_commits.rs
cli/tests/test_git_push.rs
cli/tests/test_git_remotes.rs
cli/tests/test_gitignores.rs

tests: port git init, private commits, push, remote, gitignore to TestWorkDir API

---

lib/src/git_backend.rs

git_backend: stop writing tree ids to proto

---

cli/src/cli_util.rs
cli/src/commands/git/export.rs
cli/src/commands/git/init.rs
cli/src/git_util.rs
lib/src/git.rs
lib/tests/test_git.rs

git: rename "branch" in export code path

---

Cargo.lock
Cargo.toml
cli/tests/test_commit_template.rs
lib/Cargo.toml
lib/src/time_util.rs

time_util: replace use of `chrono-english` by `interim`

---

deny.toml

cargo-deny: remove chrono-english advisory from ignore list

---

CHANGELOG.md
cli/src/cli_util.rs
cli/tests/test_git_colocated.rs
cli/tests/test_git_init.rs
lib/src/git.rs

git: set --intent-to-add on new files

---

flake.lock

We all know the drill.
If applicable:

nix: regularly scheduled flake update

---

cli/examples/custom-commit-templater/main.rs
cli/src/cli_util.rs
cli/src/commands/debug/revset.rs
cli/src/commit_templater.rs
cli/src/revset_util.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: extract internal context struct from RevsetParseContext

---

cli/src/commands/bookmark/forget.rs
cli/src/commands/git/clone.rs
cli/src/commands/git/fetch.rs
cli/src/commands/git/init.rs
cli/src/commands/git/mod.rs
cli/src/commands/git/push.rs
cli/src/commands/git/remote/add.rs
cli/src/commands/git/remote/remove.rs
cli/src/commands/git/remote/rename.rs
cli/src/commands/git/remote/set_url.rs
lib/src/git.rs
lib/src/git_subprocess.rs
lib/src/op_store.rs
lib/src/ref_name.rs
lib/src/view.rs
lib/tests/test_git.rs

git: use RemoteName/RefName types in fetch, push, remote management fns

---

cli/src/complete.rs
cli/tests/test_completion.rs

cli: completion: fix renamed paths

---

cli/src/commands/git/init.rs
cli/src/commands/git/push.rs
lib/src/git.rs
lib/src/git_subprocess.rs
lib/src/op_store.rs
lib/src/ref_name.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/simple_op_store.rs
lib/src/view.rs
lib/tests/test_git.rs
lib/tests/test_revset.rs
lib/tests/test_view.rs

view: introduce GitRefName newtypes

---

cli/src/cli_util.rs
cli/src/commands/abandon.rs
cli/src/commands/bookmark/create.rs
cli/src/commands/bookmark/mod.rs
cli/src/commands/bookmark/rename.rs
cli/src/commands/bookmark/set.rs
cli/tests/test_abandon_command.rs

cli: abandon: show warning if deleted bookmarks had tracking remotes

---

mkdocs.yml

mkdocs cleanup

---

docs/revsets.md

docs/revsets: fix `fork_point()` example

---

cli/tests/test_immutable_commits.rs
cli/tests/test_interdiff_command.rs
cli/tests/test_log_command.rs
cli/tests/test_new_command.rs
cli/tests/test_next_prev_commands.rs

tests: port immutable_commits, interdiff, log, new, next/prev to TestWorkDir

---

docs/paid_contributors.md

They are technically employed for another week or so, but they're on vacation. Removing now before I forget.
If applicable:

paid_contributors: torquestomp has left Google

---

cli/src/cli_util.rs
cli/src/command_error.rs
cli/tests/test_git_colocated.rs
lib/src/git.rs
lib/tests/test_git.rs

 git: report HEAD export failure as warning

---

CHANGELOG.md

changelog: restore "Fixed bugs" heading removed at 68ef93ebd6e0

---

lib/src/git_backend.rs

This reverts commit b8ca9ae806e768c8a1e1d814ac78dc468232efd6.
In spite of the commit description, something in `jj 0.27` seems to rely on that data being written. As discussed in the linked issue, the problem seems to be that `jj 0.27` is missing f7b14be.
**Update:** Martin provided more details:
> In commit 4d42604 (a year ago), we started writing the trees involved in conflicted commits to the Git commit object in addition to the proto storage. We validated that the two record matched when reading commits until as recently as f7b14be (about a week ago). Just after that, in commit b8ca9ae, we stopped writing the tree ids to the proto storage. That means that any version of jj between 4d42604 and f7b14be would error fail when reading a conflicted commit created by new versions. While we …

Revert "git_backend: stop writing tree ids to proto"

---

cli/tests/test_resolve_command.rs
cli/tests/test_restore_command.rs
cli/tests/test_revert_command.rs
cli/tests/test_revset_output.rs

tests: port resolve, restore, revert, revset_output to TestWorkDir API

---

CHANGELOG.md
cli/src/commands/git/push.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_git_push.rs
cli/tests/test_operations.rs

cli: require --deleted to push deleted bookmarks

---

CHANGELOG.md
lib/src/fix.rs
lib/tests/test_fix.rs

(the command called) Fix: always rewrite descendants of fixed commits

---

cli/tests/test_show_command.rs
cli/tests/test_sign_unsign_commands.rs
cli/tests/test_simplify_parents_command.rs
cli/tests/test_sparse_command.rs
cli/tests/test_split_command.rs
cli/tests/test_squash_command.rs

tests: port show, sign/unsign, simplify-parents, sparse, split, squash to TestWorkDir

---

cli/tests/test_git_push.rs

tests: add missing insta::allow_duplicates! { .. }

---

cli/tests/test_status_command.rs
cli/tests/test_tag_command.rs
cli/tests/test_templater.rs
cli/tests/test_undo.rs
cli/tests/test_util_command.rs
cli/tests/test_working_copy.rs
cli/tests/test_workspaces.rs

tests: port status, tag, templater, undo, util, working_copy, workspaces to TestWorkDir

---

Cargo.toml

cargo: remove redundant default-features=false from testutils

---

cli/tests/test_git_push.rs

@ilyagr @bsdinis You might want to review the added conditionals here. Is it expected that it’s different with `git.subprocess = false`?
If applicable:

tests: fix subprocess toggle in `git push --named` tests

---

cli/tests/common/test_environment.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_fetch.rs
cli/tests/test_git_push.rs

Seems like this would have helped @ilyagr, so splitting it out of https://github.com/jj-vcs/jj/pull/6047.
If applicable:

tests: add `TestEnvironment::with_git_subprocess` helper

---

docs/config.md

Not sure if Helix is considered popular but I thought it should be mentioned anyway :)
If applicable:

docs: Mention Helix with taplo for config.toml validation

---

CHANGELOG.md
Cargo.lock
Cargo.toml

I removed the empty sections from `CHANGELOG.md`. Let me know if we want to format patch-release changelogs differently.
If applicable:

release: 0.28.1

---

cli/src/commands/bookmark/list.rs
cli/tests/test_bookmark_command.rs
cli/tests/test_git_push.rs

cli: fix warning about pushing deleted bookmark

---

.github/workflows/ci.yml

I think this check will only be useful if it actually blocks the build. Since the resolution is simple (just bump the limit), I think it’s okay to add a small amount of friction and ask people to take a moment to consider other options first.
If applicable:

github: give the dragon a promotion

---

CHANGELOG.md
Cargo.lock
deny.toml

cargo: bump gix and its dependencies recursively

---

docs/core_tenets.md
mkdocs.yml

This was taken out of the "Jujutsu from first principles" doc in another PR (#3089). It represents some of the common ideas which the project had around a year ago.
I think this can be modernized if the maintainers want it.

docs: Add Jujutsu's Developers core values

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deny.toml

Release 0.28.2

---

docs/config.md

docs: update list of builtin merge tools

---

cli/src/merge_tools/builtin.rs
lib/src/conflicts.rs
lib/src/files.rs
lib/src/merge.rs
lib/src/tree.rs
lib/tests/test_merged_tree.rs

files: add merge() functions that return result as Merge<_>/Option<_>

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Once this is approved, I plan to bypass the github rules and merge this to the main branch without rebasing
If applicable:

Merge 0.28 release branch into main

---

docs/testimonials.md

This is cobbled together from the "new" appreciation channel and something I saw on the Rust Zulip.
cc @InCogNiTo124  cc @fowles cc @davidbarsky

docs: add some more testimonials

---

Cargo.lock

cargo: run `cargo update` to update off of yanked `crossbeam-channel`

---

lib/src/git_backend.rs
lib/src/settings.rs

git_backend: propagate config error, minor cleanup

---

docs/contributing.md
docs/style_guide.md

docs: add a style guide

---

cli/src/config-schema.json

config-schema: add templates

---

lib/src/git_backend.rs

git_backend: load "git gc" executable name from settings

---

cli/src/commands/file/show.rs
cli/src/diff_util.rs
cli/src/merge_tools/builtin.rs
cli/src/merge_tools/external.rs
cli/src/merge_tools/mod.rs
cli/tests/test_resolve_command.rs
lib/src/absorb.rs
lib/src/annotate.rs
lib/src/conflicts.rs
lib/src/default_index/revset_engine.rs
lib/src/local_working_copy.rs

conflicts: extract function that materializes file conflict, use it in "jj resolve"

---

cli/tests/common/test_environment.rs
cli/tests/test_git_clone.rs
cli/tests/test_git_remotes.rs
lib/src/git.rs

git: work around `gix` global remote configuration issue

---

lib/src/default_index/revset_engine.rs
lib/tests/test_revset.rs

revset: compare conflict file contents without materializing as conflicts

---

lib/src/repo.rs

repo: reimplement merge of working-copy commits in the same way as other refs

---

cli/src/merge_tools/builtin.rs
lib/src/fileset.rs
lib/src/git_backend.rs
lib/src/local_working_copy.rs
lib/src/matchers.rs
lib/src/repo_path.rs
lib/src/simple_backend.rs
lib/tests/test_annotate.rs
lib/tests/test_commit_builder.rs
lib/tests/test_conflicts.rs
lib/tests/test_fix.rs
lib/tests/test_git.rs
lib/tests/test_git_backend.rs
lib/tests/test_local_working_copy.rs
lib/tests/test_local_working_copy_concurrent.rs
lib/tests/test_local_working_copy_sparse.rs
lib/tests/test_merge_trees.rs
lib/tests/test_merged_tree.rs
lib/tests/test_revset.rs
lib/tests/test_rewrite.rs
lib/tests/test_rewrite_duplicate.rs
lib/testutils/src/lib.rs

repo_path: remove assertion from constructors

---

lib/src/merge.rs

merge: clarify expectation of with_new_file_ids()

---

CHANGELOG.md
cli/src/commands/commit.rs
cli/src/description_util.rs
cli/tests/test_commit_command.rs

trailer support in the commit command
based on #6088 
If applicable:

commit: add trailer support

---

CHANGELOG.md
cli/src/commands/commit.rs
cli/src/commands/describe.rs
cli/src/commands/split.rs
cli/src/config-schema.json
cli/src/config.rs
cli/src/description_util.rs
cli/tests/test_commit_command.rs
cli/tests/test_describe_command.rs
cli/tests/test_split_command.rs
docs/config.md

Closes https://github.com/jj-vcs/jj/issues/6298.
If applicable:

cli: deprecate ui.default-description

---

CHANGELOG.md
cli/src/commands/new.rs
cli/tests/test_new_command.rs

based on #6088 
If applicable:

new: add trailer support

---

lib/src/repo.rs

repo: propagate error from `edit()` in `update_wc_commits()`

---

CHANGELOG.md
cli/src/commands/squash.rs
cli/src/description_util.rs
cli/tests/test_squash_command.rs

based on #6088 
If applicable:

squash: add trailer support

---

CHANGELOG.md
cli/src/commands/split.rs
cli/tests/test_split_command.rs

based on #6088 
If applicable:

split: add trailer support

---

docs/paid_contributors.md

Make it easier to scan the list by sorting it (case-insensitive).
If applicable:

paid_contributors: sort contributor list

---

CHANGELOG.md
cli/src/commands/git/push.rs
cli/tests/test_git_push.rs

cli: git-push: do not move existing local bookmarks by --change

---

cli/src/commands/squash.rs
cli/tests/test_squash_command.rs

squash: don't add trailers to an empty description

---

cli/src/command_error.rs
lib/src/revset.rs

revset: rename `StoreError` variants to `Backend`

---

lib/src/conflicts.rs
lib/src/merge.rs
lib/src/merged_tree.rs
lib/src/tree.rs

merge: add and use helpers for joining merge of futures

---

mkdocs.yml

mkdocs: add 'Style guide' to nav sidebar

---

lib/src/merge.rs
lib/src/merged_tree.rs

merge: make `to_tree_merge()` read trees concurrently

---

mkdocs.yml

mkdocs: enable readable anchor links for content tabs

---

docs/contributing.md
mkdocs.yml

mkdocs: enable code copy button globally

---

docs/config.md

Ref https://github.com/Homebrew/homebrew-cask/pull/209550
Ping @ilyagr in case you want to update your [Gist](https://gist.github.com/ilyagr/1b40f6061d8ad320cee4c12843df1a23).

docs: update `meld` install command

---

cli/src/commands/evolog.rs

cli: evolog: trivial cleanup

---

mkdocs.yml

This allows text typed into the search box to persist across page navigation, which is useful when users look up a term but aren't sure on which page they will eventually find the relevant information. See the [`mkdocs-material` docs][mm-docs] for more information.
[mm-docs]:
https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
If applicable:

mkdocs: enable instant loading

---

cli/src/cli_util.rs
cli/src/commands/rebase.rs
lib/src/rewrite.rs

cli: rebase: consolidate call sites of move_commits()

---

lib/src/merged_tree.rs

merged_tree: make `merge_trees()` async

---

CHANGELOG.md
cli/src/cli_util.rs
cli/tests/test_describe_command.rs

cli: put editor-*.jjdescription file in /tmp instead of .jj/repo/

---

docs/technical/conflicts.md

docs: make technical conflicts doc better match our recent thinking

---

cli/src/merge_tools/builtin.rs

merge-tools: builtin: leverage materialized_diff_stream()

---

lib/src/local_working_copy.rs

local_working_copy: avoid a `block_on()` in already async function

---

Cargo.lock
lib/testutils/Cargo.toml
lib/testutils/src/lib.rs

tests: do not shell out taplo to gather forgotten test files

---

CHANGELOG.md
cli/src/merge_tools/builtin.rs

merge-tools: builtin: parse conflict hunks back to merge value

---

CHANGELOG.md
cli/src/commit_templater.rs
cli/tests/test_commit_template.rs
docs/templates.md

A couple of things I'm unsure of:
- ~Where should I create tests for this?~ (nvm, found it)
- Should `key()` and `value()` be the `Trailer` method names?
If applicable:

templates: implement `Commit.trailers()`

---

cli/src/commit_templater.rs

templater: don't attribute method table functions as pub

---

cli/src/merge_tools/builtin.rs

merge-tools: builtin: refactor mapping of binary files

---

cli/src/cli_util.rs

CliRunner: replace start hook by dispatch hook

---

cli/examples/custom-commit-templater/main.rs
cli/examples/custom-operation-templater/main.rs
cli/src/cli_util.rs
cli/src/commands/config/list.rs
cli/src/commit_templater.rs
cli/src/generic_templater.rs
cli/src/operation_templater.rs
cli/src/template_builder.rs
cli/src/templater.rs

templater: convert property to trait object by caller

---

cli/src/commands/diffedit.rs
cli/src/commands/restore.rs
cli/tests/test_diffedit_command.rs
cli/tests/test_restore_command.rs
cli/tests/test_working_copy.rs

restore: do not output "Created ..." message

---

cli/tests/test_config_command.rs
lib/src/config.rs

cli: add "$schema" line when creating new config file

---

Cargo.lock
cli/src/commands/abandon.rs
flake.lock

Also suppresses a warning that slipped into the git-less build.
If applicable:

deps: update flake.lock and Cargo.lock

---

cli/src/commands/status.rs
cli/tests/cli-reference@.md.snap

status: update severely stale command description

---

cli/tests/test_diff_command.rs
lib/src/files.rs

files: make DiffLineIterator omit blank right line following matching+left

---

lib/src/default_index/mod.rs

cleanup: remove fixed clippy bug workaround

---

cli/tests/test_log_command.rs

tests: update short commit id prefix after acd824269f1d

---

lib/src/local_working_copy.rs

working_copy: minimize use of #[cfg(windows)] around executable bit handling

---

cli/src/cli_util.rs
cli/src/commands/bookmark/list.rs
cli/src/commands/bookmark/track.rs
cli/src/commands/config/list.rs
cli/src/commands/evolog.rs
cli/src/commands/file/annotate.rs
cli/src/commands/file/list.rs
cli/src/commands/log.rs
cli/src/commands/operation/diff.rs
cli/src/commands/operation/log.rs
cli/src/commands/operation/show.rs
cli/src/commands/tag.rs
cli/src/commit_templater.rs
cli/src/generic_templater.rs
cli/src/operation_templater.rs
cli/src/template_builder.rs
cli/src/templater.rs

templater: introduce trait for wrapping BoxedTemplateProperty<O> types

---

cli/src/commands/rebase.rs
lib/src/rewrite.rs

rewrite: refactor `move_commits()` arguments, split functions

---

cli/examples/custom-commit-templater/main.rs
cli/examples/custom-operation-templater/main.rs
cli/src/commands/config/list.rs
cli/src/commit_templater.rs
cli/src/generic_templater.rs
cli/src/operation_templater.rs
cli/src/template_builder.rs
cli/src/templater.rs

templater: replace remainders of P::wrap_<type>(), remove old wrap_<type> fns

---

cli/src/complete.rs
docs/core_tenets.md

Fix some typos

---

cli/src/commit_templater.rs
cli/src/template_builder.rs
cli/src/template_parser.rs

templater: port list methods to symbol table

---

lib/src/workspace.rs

workspace: remove `load_working_copy()` from `WorkspaceLoader`

---

docs/tutorial.md

docs: Update tutorial.md using the command in version 0.29.0.

---

cli/src/commit_templater.rs
cli/src/generic_templater.rs
cli/src/operation_templater.rs
cli/src/template_builder.rs
docs/templates.md

templater: allow comparison between optional and non-optional values

---

lib/src/store.rs

store: add `backend()` accessor

---

docs/install-and-setup.md

docs: Add support for installing JJ using the winget command.

---

cli/src/commands/util/gc.rs
cli/tests/cli-reference@.md.snap

cli util gc: fix typo in doc comment

---

CHANGELOG.md
cli/src/commit_templater.rs
cli/tests/test_bookmark_command.rs
cli/tests/test_commit_template.rs
cli/tests/test_git_clone.rs
cli/tests/test_log_command.rs
cli/tests/test_split_command.rs
docs/templates.md

templater: introduce newtype to format ref/remote name in revset syntax

---

.github/PULL_REQUEST_TEMPLATE.md

PR template: include updating tests in checklist

---

cli/src/commands/describe.rs
lib/src/commit_builder.rs

cli, lib: update `MutRepo` references in comments to `MutableRepo`

---

CHANGELOG.md
cli/src/config-schema.json
cli/src/config.rs
cli/src/config/misc.toml
cli/src/diff_util.rs
cli/src/merge_tools/mod.rs
cli/src/ui.rs
cli/tests/sample-configs/invalid/ui.diff-formatter_empty_array.toml
cli/tests/sample-configs/invalid/ui.diff.format_not_in_enum.toml
cli/tests/sample-configs/valid/ui_command-env.toml
cli/tests/sample-configs/valid/ui_multi_arg_cmds.toml
cli/tests/sample-configs/valid/ui_simple.toml
cli/tests/test_diff_command.rs
cli/tests/test_log_command.rs
docs/config.md

cli: unify diff format/tool config variables

---

lib/src/object_id.rs

object_id: remove extra word in doc comment

---

cli/examples/custom-backend/main.rs
cli/examples/custom-command/main.rs
cli/examples/custom-commit-templater/main.rs
cli/examples/custom-global-flag/main.rs
cli/examples/custom-operation-templater/main.rs
cli/examples/custom-working-copy/main.rs
cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/main.rs

cli: replace `ExitCode` by `u8`

---

docs/revsets.md

docs/revsets: fix typo

---

cli/src/commands/describe.rs

This is both more idiomatic and explicit.
If applicable:

cli describe: refactor to use pattern matching

---

cli/src/git_util.rs
cli/tests/test_git_import_export.rs

cli: git: remove broken attempt to align stats, fix "tag" labeling

---

docs/operation-log.md

docs/operation-log: Fix section header casing

---

cli/src/commands/mod.rs
cli/tests/cli-reference@.md.snap

The Markdown docs have been regenerated as well.
If applicable:

cli: sort top-level commands lexicographically

---

docs/community_tools.md

Disclaimer: I am not associated with jjui, but enjoy using it.
If applicable:

docs: add jjui to the list of community tools

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/examples/custom-backend/main.rs
cli/src/commands/file/show.rs
cli/src/commands/fix.rs
lib/Cargo.toml
lib/src/backend.rs
lib/src/conflicts.rs
lib/src/file_util.rs
lib/src/git_backend.rs
lib/src/local_working_copy.rs
lib/src/secret_backend.rs
lib/src/simple_backend.rs
lib/src/store.rs
lib/src/tree.rs
lib/testutils/Cargo.toml
lib/testutils/src/lib.rs
lib/testutils/src/test_backend.rs

backend: make read_file() return a AsyncRead

---

cli/src/commands/fix.rs
cli/src/diff_util.rs
cli/src/merge_tools/builtin.rs
lib/src/absorb.rs
lib/src/annotate.rs
lib/src/conflicts.rs
lib/src/default_index/revset_engine.rs

async: bubble up async-ness from Backend::read_file

---

cli/tests/test_workspaces.rs

test: clean up config strings

---

cli/examples/custom-backend/main.rs
lib/src/backend.rs
lib/src/file_util.rs
lib/src/git_backend.rs
lib/src/local_working_copy.rs
lib/src/secret_backend.rs
lib/src/simple_backend.rs
lib/src/store.rs
lib/testutils/src/test_backend.rs

backend: make write_file() take an AsyncRead

---

docs/tutorial.md

Unfortunately these were manually checked. It would be good to be able to keep the docs up to date automatically in the future with some sort of CLI snapshot tool?
If applicable:

docs/tutorial: minor fixes for consistency

---

docs/install-and-setup.md
mkdocs.yml

docs: move shell completion commands into tabs

---

CHANGELOG.md
cli/src/command_error.rs
cli/src/commands/evolog.rs
cli/tests/test_absorb_command.rs
cli/tests/test_commit_template.rs
cli/tests/test_evolog_command.rs
cli/tests/test_split_command.rs
cli/tests/test_squash_command.rs
cli/tests/test_workspaces.rs
lib/src/evolution.rs
lib/src/lib.rs
lib/tests/runner.rs
lib/tests/test_evolution_predecessors.rs

cli: evolog: show associated operations alongside commits

---

lib/src/default_index/store.rs

index: refactor reindexing function

---

cli/src/cli_util.rs
cli/tests/test_commit_command.rs
cli/tests/test_describe_command.rs
cli/tests/test_diff_command.rs
cli/tests/test_split_command.rs
lib/src/config_resolver.rs

cli: for deprecated configs, say at which source level they were found

---

lib/src/default_index/mod.rs
lib/src/default_index/rev_walk.rs
lib/src/default_index/rev_walk_queue.rs

index: optimize heap push/pop in ancestors query

---

lib/src/default_index/composite.rs
lib/src/default_index/entry.rs

index: in heads_pos(), compare generation when queuing parents

---

docs/revsets.md

docs: mention expressions equivalent to heads() and roots()

---

lib/src/default_index/composite.rs

I implemented this in #6659, but I think it can be a separate PR.
Instead of immediately populating the queue with the parents of all candidate commits, we can push the parents as we iterate over candidate commits, which seems to improve performance slightly.
Benchmark results on Git repo:
```
revsets/heads(tags())           28.238% improvement
revsets/heads(::v2.40.0)        50.456% improvement
```
If applicable:

index: heads_pos(): push parents to queue while finding heads

---

lib/src/default_index/composite.rs
lib/src/default_index/mod.rs
lib/src/default_index/revset_engine.rs

index: make common_ancestors_pos() and heads_pos() return sorted Vec

---

docs/paid_contributors.md

docs: file ben/austin as paid contributors for ERSC

---

.github/workflows/binaries.yml
.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md

github: try building windows-on-arm binaries

---

CHANGELOG.md
lib/src/git_backend.rs

git: pass "--expire" time in to "git gc"

---

cli/src/cli_util.rs

cli: calculate size of immutable descendants by check_rewritable()

---

cli/src/commands/debug/revset.rs
cli/tests/test_debug_command.rs

cli: add "debug revset --no-resolve" /"--no-optimize" flags

---

cli/src/cli_util.rs
cli/src/commands/fix.rs
cli/src/commit_templater.rs
cli/src/diff_util.rs
lib/src/default_index/revset_engine.rs
lib/src/fix.rs
lib/src/rewrite.rs
lib/tests/test_fix.rs
lib/tests/test_rewrite.rs

async: avoid some async blocks by making whole functions async

---

cli/tests/test_revset_output.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: remove redundant intersection/union with none()

---

CHANGELOG.md
cli/src/commands/operation/diff.rs
cli/src/commands/operation/log.rs
cli/src/commands/operation/show.rs
cli/tests/test_operations.rs

cli: op log/show: don't attempt to show diff from auto-merge parents

---

cli/src/commands/git/fetch.rs
cli/tests/test_git_fetch.rs

cli `git fetch`: fix typo in error message

---

lib/src/revset.rs

Split off from #6679.
If applicable:

revset: optimizations for intersections and ranges

---

lib/src/dag_walk.rs
lib/src/default_index/store.rs
lib/src/evolution.rs
lib/src/op_walk.rs
lib/src/repo.rs
lib/tests/test_evolution_predecessors.rs

evolution: fix cycle detection and graph sorting of transitive predecessors

---

CHANGELOG.md
cli/src/commands/evolog.rs
cli/src/commands/log.rs
cli/src/commands/operation/diff.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_evolog_command.rs
cli/tests/test_squash_command.rs
lib/src/evolution.rs
lib/src/graph.rs
lib/tests/test_evolution_predecessors.rs

#6753 (recreated because I deleted the base branch too early, and can no longer reopen. sorry for the noise.)
If applicable:

cli: evolog: accept multiple starting revisions, group nodes topologically #6753 

---

lib/src/default_index/revset_engine.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: add intersection node to backend filter predicates

---

lib/src/revset.rs

revset: mark f1&f2 as filter to fix check for nested filter intersection

---

cli/examples/custom-backend/main.rs
cli/src/cli_util.rs
cli/src/config.rs
cli/src/template_parser.rs
lib/src/backend.rs
lib/src/config.rs
lib/src/default_index/readonly.rs
lib/src/fileset_parser.rs
lib/src/git_backend.rs
lib/src/merged_tree.rs
lib/src/repo.rs
lib/src/revset_parser.rs
lib/src/secret_backend.rs
lib/src/simple_backend.rs
lib/src/store.rs
lib/src/tree.rs
lib/src/workspace.rs
lib/testutils/src/test_backend.rs

address new mismatched_lifetime_syntaxes Clippy lint

---

docs/config.md

Thanks to idealseal on GitHub for the pointer.
If applicable:

docs: fix indentation levels of some items

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/merge_tools/builtin.rs
lib/testutils/Cargo.toml
lib/testutils/src/lib.rs
lib/testutils/src/proptest.rs

This PR was split from #6448 to review and land the bug fixes separately from the property-based testing.
If applicable:

builtin merge-tool: add property-based tests

---

CHANGELOG.md
docs/revsets.md
lib/src/revset.rs
lib/tests/test_revset.rs

revset: expand all() set to include all referenced commits

---

lib/src/id_prefix.rs

id_prefix: if a prefix is ambiguous in small set, don't try full set

---

cli/src/commands/bench/revset.rs
cli/src/revset_util.rs
lib/src/id_prefix.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: remove SymbolResolver abstraction

---

Cargo.lock
lib/Cargo.toml
lib/tests/runner.rs
lib/tests/test_revset_optimized.rs

tests: add proptest that compares optimized revset output

---

cli/src/commands/operation/diff.rs
cli/tests/test_operations.rs
lib/src/dag_walk.rs
lib/src/default_index/store.rs
lib/src/evolution.rs
lib/src/op_walk.rs
lib/tests/test_evolution_predecessors.rs
lib/tests/test_operations.rs

#6754 (recreated)
If applicable:

 cli: op diff: use predecessors information to pair old/new commits #6754 

---

Cargo.lock
Cargo.toml
cli/src/commit_templater.rs
cli/src/operation_templater.rs
cli/src/template_builder.rs
cli/src/templater.rs
cli/src/time_util.rs
lib/src/backend.rs
lib/src/object_id.rs
lib/src/repo_path.rs
pyproject.toml

templater: make some more value types serializable

---

cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/commands/config/path.rs
cli/src/commands/git/root.rs
cli/src/commands/root.rs
cli/src/commands/workspace/root.rs
lib/src/file_util.rs
lib/src/git_backend.rs
lib/src/workspace.rs
lib/tests/test_init.rs
lib/tests/test_workspace.rs

better handling of non-UTF-8 workspace/repository paths

---

lib/src/rewrite.rs

rewrite: deduplicate internal parents while collecting transitive edges

---

Cargo.toml

cargo: enable missing "rc" feature of serde

---

cli/examples/custom-commit-templater/main.rs
cli/examples/custom-operation-templater/main.rs
cli/src/commit_templater.rs
cli/src/template_builder.rs
cli/src/template_parser.rs

templater: refactor handling of alias expansion stack

---

CHANGELOG.md
cli/tests/test_revset_output.rs
docs/revsets.md
lib/src/backend.rs
lib/src/git_backend.rs
lib/src/hex_util.rs
lib/src/object_id.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: add change_id/commit_id(prefix) predicates

---

uv.lock

Updates markdown-include-plugin among other things

docs/uv: update lockfile

---

cli/src/merge_tools/builtin.rs
lib/src/local_working_copy.rs
lib/src/merge.rs
lib/src/merged_tree.rs
lib/tests/test_merged_tree.rs

Make `MergedTree::diff_stream()` sort `foo` before `foo/bar`

---

lib/src/git_backend.rs

git_backend: cache shallow roots

---

cli/src/config.rs
cli/src/template_parser.rs
cli/src/time_util.rs
lib/src/config.rs
lib/src/fileset.rs
lib/src/fileset_parser.rs
lib/src/op_store.rs
lib/src/revset.rs
lib/src/revset_parser.rs

cleanup: replace once_cell::sync::Lazy by std::sync::LazyLock

---

docs/templates.md

docs: document Commit.signature()

---

docs/revsets.md

docs: include another example of `..` vs `::` difference

---

cli/src/template.pest
lib/src/revset.pest

template/revset: mention tree-sitter grammar in pest file

---

docs/revsets.md

docs: `jj diff -r` is no longer an example of single-revision command

---

cli/src/commands/commit.rs
cli/src/commands/diffedit.rs
cli/src/commands/resolve.rs
cli/src/commands/restore.rs
cli/src/commands/split.rs
cli/src/commands/squash.rs
cli/src/complete.rs
cli/src/diff_util.rs
cli/src/merge_tools/mod.rs
cli/tests/test_completion.rs

cli completion: complete `--tool` for diff tools, diff editors, and merge editors

---

lib/src/merged_tree.rs
lib/src/store.rs
lib/tests/test_merged_tree.rs
lib/testutils/src/test_backend.rs

Fix bug I recently introduces in stream diff

---

docs/install-and-setup.md

docs: add scoop to windows installation

---

docs/revsets.md

docs: explain how e.g. the commit_id() revset can override a bookmark

---

lib/src/merged_tree.rs
lib/src/store.rs
lib/tests/test_local_working_copy.rs
lib/tests/test_merged_tree.rs
lib/testutils/src/lib.rs

store: inline tree_builder() function to callers

---

Cargo.lock
Cargo.toml

Closes #6437
Closes #6810
If applicable:

cargo: bump gix to 0.73.0, update its dependencies

---

cli/src/diff_util.rs
cli/tests/test_diff_command.rs

diff stat: ensure bar always has 2 spaces for commits with adds and removes

---

README.md

readme: the name of the binary will probably not change

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
docs/contributing.md
docs/install-and-setup.md
lib/src/conflicts.rs
lib/src/local_working_copy.rs
lib/src/merge.rs
lib/src/merged_tree.rs
lib/src/tree.rs

Update MSRV to 1.85

---

lib/src/default_index/composite.rs
lib/src/default_index/mutable.rs
lib/src/default_index/readonly.rs
lib/src/default_index/store.rs
lib/src/object_id.rs

index: keep hash in bytes, use non-segment type in more places

---

cli/testing/bench-revsets-git.txt

testing: update stale revset names in bench-revsets-git.txt

---

cli/src/commands/split.rs
cli/tests/cli-reference@.md.snap

split: Clarify help text for --destination

---

cli/src/cli_util.rs
cli/src/commands/bookmark/forget.rs
cli/src/commands/bookmark/list.rs
cli/src/commands/git/fetch.rs
cli/src/commands/tag.rs
lib/src/default_index/revset_engine.rs
lib/src/git.rs
lib/src/str_util.rs

This makes it clear that it doesn't give a list of matches.
Pulled out of #6899.
If applicable:

str_util: rename "matches" to "is_match"

---

cli/src/commands/backout.rs
cli/src/commands/revert.rs
cli/src/commands/split.rs
lib/src/absorb.rs
lib/src/merged_tree.rs
lib/src/rewrite.rs
lib/tests/test_local_working_copy.rs
lib/tests/test_merged_tree.rs
lib/tests/test_mut_repo.rs
lib/tests/test_revset.rs

merged_tree: take some arguments by value to reduce cloning

---

lib/src/default_index/revset_engine.rs
lib/src/str_util.rs
lib/tests/test_revset.rs

str_util: add matches_bytes(), use it in diff_contains() revset

---

cli/src/commands/backout.rs
cli/src/commands/diff.rs
cli/src/commands/diffedit.rs
cli/src/commands/new.rs
cli/src/commands/revert.rs
cli/src/commands/split.rs
cli/src/commands/workspace/add.rs
lib/src/absorb.rs
lib/src/commit.rs
lib/src/default_index/revset_engine.rs
lib/src/merged_tree.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/tests/test_eol.rs
lib/tests/test_local_working_copy.rs
lib/tests/test_merged_tree.rs
lib/tests/test_mut_repo.rs
lib/tests/test_revset.rs

More async stuff (mostly merge-/rebase-related)

---

lib/src/default_index/composite.rs

index: use bit set in `is_ancestor_pos()` and `all_heads_pos()`

---

docs/tutorial.md

tutorial: fix incorrect change id in output

---

CHANGELOG.md
cli/tests/test_git_colocated.rs
lib/src/git.rs

git: write empty blob when setting intent to add

---

docs/config.md

I hope this is meets you expectations specified to close #7081 
If applicable:

Add documentation for `git.push-new-bookmarks` and `log-graph-prioritize`

---

CHANGELOG.md
docs/revsets.md
lib/src/default_index/rev_walk.rs
lib/src/default_index/revset_engine.rs
lib/src/revset.rs
lib/tests/test_index.rs
lib/tests/test_revset.rs
lib/tests/test_revset_optimized.rs

Fixes #6606. Not sure if this is the best approach, but I wanted to try it out.
If applicable:

revset: add `first_ancestors()` function

---

lib/tests/test_revset_optimized.rs

tests: add sample of feature branches to revset optimization proptest

---

lib/tests/test_bad_locking.rs
lib/tests/test_commit_builder.rs
lib/tests/test_default_revset_graph_iterator.rs
lib/tests/test_git.rs
lib/tests/test_git_backend.rs
lib/tests/test_index.rs
lib/tests/test_mut_repo.rs
lib/tests/test_operations.rs
lib/tests/test_refs.rs
lib/tests/test_revset.rs
lib/tests/test_rewrite.rs
lib/tests/test_rewrite_transform.rs
lib/tests/test_view.rs
lib/testutils/src/lib.rs

Test helper cleanups

---

CHANGELOG.md
docs/revsets.md
lib/src/revset.rs
lib/tests/test_revset.rs
lib/tests/test_revset_optimized.rs

Resolves #4579.
If applicable:

revset: add `first_parent()` function

---

lib/src/merged_tree.rs

Preparations for making `merge_trees()` concurrent and non-recursive

---

cli/src/commands/debug/index.rs
lib/src/default_index/composite.rs
lib/src/default_index/mod.rs
lib/src/default_index/mutable.rs
lib/src/default_index/readonly.rs
lib/src/default_index/store.rs
lib/src/index.rs
lib/src/repo.rs
lib/tests/test_git_backend.rs

index: prepare for changed-path index calculation and store

---

cli/src/commands/operation/diff.rs
lib/src/annotate.rs
lib/src/default_index/revset_graph_iterator.rs
lib/src/graph.rs

revset_graph: minor cleanup in remove_transitive_edges()

---

lib/src/default_index/revset_graph_iterator.rs

revset_graph: remove transitive edges more to save memory usage

---

Cargo.lock

cargo: update gix dependencies

---

cli/src/commands/abandon.rs
cli/src/commands/describe.rs
cli/src/commands/duplicate.rs
cli/src/commands/git/push.rs
cli/src/commands/new.rs
cli/src/commands/parallelize.rs
cli/src/commands/revert.rs
cli/src/commands/sign.rs
cli/src/commands/simplify_parents.rs
cli/src/commands/split.rs
cli/src/commands/unsign.rs
lib/src/absorb.rs
lib/src/fix.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/tests/test_merge_trees.rs
lib/tests/test_rewrite_duplicate.rs
lib/tests/test_rewrite_transform.rs

Make `transform_descendants()` callbacks async

---

cli/src/commands/debug/mod.rs
cli/src/commands/debug/object.rs

cli: add debug commands for printing commits, operations, etc.

---

lib/src/default_index/changed_path.rs
lib/src/default_index/composite.rs
lib/src/default_index/mod.rs
lib/src/default_index/mutable.rs
lib/src/default_index/readonly.rs
lib/src/default_index/store.rs

This patch doesn't include any file format changes. I'll push the other patches after the release.
If applicable:

index: add data structure for changed-path index

---

CHANGELOG.md
cli/src/commands/file/show.rs
cli/src/config-schema.json
cli/src/config/templates.toml
cli/tests/cli-reference@.md.snap
cli/tests/test_file_show_command.rs

cli: file show: add templating support

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/tests/common/config_schema_defaults.rs
cli/tests/common/mod.rs
cli/tests/datatest_config_schema.rs
cli/tests/datatest_runner.rs
cli/tests/test_config_command.rs
cli/tests/test_config_schema.rs
flake.nix

tests: replace `taplo(1)` and `jq(1)` with Rust

---

CHANGELOG.md
cli/src/config/templates.toml
cli/src/template_builder.rs
cli/tests/test_completion.rs
cli/tests/test_evolog_command.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
cli/tests/test_show_command.rs
cli/tests/test_templater.rs
docs/templates.md

ref: #6492 
Thanks @sergi0g for the inspiration!
If applicable:

log: add an option to anonymize the log output

---

lib/src/config.rs
lib/src/default_index/store.rs
lib/src/file_util.rs
lib/src/git.rs
lib/src/simple_op_store.rs
lib/src/workspace.rs

PathError: rename `error` field to `source`

---

cli/src/commands/operation/diff.rs

diff: Remove unneeded `&`

---

lib/src/local_working_copy.rs

working_copy: Remove `expect(dead_code)`

---

CHANGELOG.md
cli/src/commands/mod.rs
cli/src/commands/touch.rs
cli/tests/cli-reference@.md.snap
cli/tests/runner.rs
cli/tests/test_immutable_commits.rs
cli/tests/test_touch_command.rs

touch: a command to modify some revision metadata

---

docs/glossary.md

docs: add definition for remotes to glossary

---

cli/src/commands/mod.rs
cli/src/commands/undo.rs
cli/tests/cli-reference@.md.snap

cli: fold help comments of "jj undo"

---

CHANGELOG.md
cli/src/commands/git/clone.rs
cli/src/commands/git/fetch.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_git_clone.rs
lib/src/git.rs
lib/src/git_subprocess.rs
lib/tests/test_git.rs

Fixes https://github.com/jj-vcs/jj/issues/4682
~Stacked on top of https://github.com/jj-vcs/jj/pull/7175 so I'm going to keep this as a draft until that PR lands~
If applicable:

cli: fix fetching all tags during `jj git clone`

---

cli/tests/test_global_opts.rs

tests: restore --config* ordering sample from 15c673459f55

---

cli/src/commands/absorb.rs
cli/src/commands/diff.rs
cli/src/commands/evolog.rs
cli/src/commands/interdiff.rs
cli/src/commands/log.rs
cli/src/commands/operation/diff.rs
cli/src/commands/show.rs
cli/src/commands/status.rs
cli/src/diff_util.rs
cli/src/formatter.rs

cli: minor cleanup of DiffRenderer methods

---

lib/src/rewrite.rs
lib/tests/test_rewrite.rs

Make `merge_commit_trees_no_resolve_without_repo()` non-recursive

---

CHANGELOG.md
cli/src/commands/evolog.rs
cli/src/commit_templater.rs
cli/src/config-schema.json
cli/src/config/templates.toml
cli/src/operation_templater.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_absorb_command.rs
cli/tests/test_completion.rs
cli/tests/test_evolog_command.rs
cli/tests/test_log_command.rs
cli/tests/test_operations.rs
cli/tests/test_show_command.rs
cli/tests/test_squash_command.rs
cli/tests/test_templater.rs
docs/config.md
docs/templates.md
lib/src/evolution.rs

cli: evolog: migrate to evolution template type

---

lib/src/default_index/composite.rs

index: remove forwarding function of CompositeIndex::evaluate_revset()

---

CHANGELOG.md
cli/src/commands/undo.rs
cli/tests/cli-reference@.md.snap

Relevant discussion:
https://github.com/jj-vcs/jj/pull/7277#discussion_r2291421321
If applicable:

undo: deprecate the --what flag

---

docs/filesets.md

docs: remove trailing whitespace

---

cli/tests/common/test_environment.rs
cli/tests/test_abandon_command.rs
cli/tests/test_bookmark_command.rs
cli/tests/test_commit_command.rs
cli/tests/test_diffedit_command.rs
cli/tests/test_duplicate_command.rs
cli/tests/test_fix_command.rs
cli/tests/test_git_import_export.rs
cli/tests/test_interdiff_command.rs
cli/tests/test_new_command.rs
cli/tests/test_next_prev_commands.rs
cli/tests/test_operations.rs
cli/tests/test_rebase_command.rs
cli/tests/test_resolve_command.rs
cli/tests/test_restore_command.rs
cli/tests/test_revert_command.rs
cli/tests/test_simplify_parents_command.rs
cli/tests/test_split_command.rs
cli/tests/test_squash_command.rs
cli/tests/test_touch_command.rs

tests: do not use "jj undo" to run multiple tests with the same setup

---

CHANGELOG.md
cli/src/diff_util.rs
cli/tests/test_evolog_command.rs
cli/tests/test_interdiff_command.rs
cli/tests/test_operations.rs

cli: include diff of commit descriptions in inter-diff

---

CHANGELOG.md
cli/src/commands/mod.rs
cli/src/commands/redo.rs
cli/src/commands/undo.rs
cli/tests/cli-reference@.md.snap
cli/tests/runner.rs
cli/tests/test_undo_redo_commands.rs
docs/git-command-table.yml

cli: add redo command

---

docs/FAQ.md

After a change has been accidentally modified, the user may want to recover the original revision with the same commit ID if it was pushed to a remote, not just restore the original contents.
Instead of using `jj restore` to restore contents, recommend using `jj new <PREVIOUS_ID>` to unhide the original commit. This strategy works whether or not the user cares about the original commit ID.
If applicable:

docs: Recommend unhiding revisions in the accidental changes FAQ

---

CHANGELOG.md
cli/src/commands/redo.rs
cli/src/commands/undo.rs
cli/tests/cli-reference@.md.snap

I tried to explain the mental model the users should have in mind briefly.
Cc @senekor

undo/redo cli docs: add details about new behavior

---

cli/src/config-schema.json
cli/tests/sample-configs/invalid/scope_invalid_key.toml
cli/tests/sample-configs/valid/scope.toml
cli/tests/sample-configs/valid/toplevel_when.toml

config-schema: add --when and --scope keys

---

docs/paid_contributors.md

🎉
This may mean that I'm around here a bit less in the near term -- as much as I like being here, there's a lot to do over there -- but we'll see.
Thanks Ben and Scott, https://github.com/jj-vcs/jj/commit/6a22e9acbde7ea66c8f5da33ade5314494474b53 made this a lot easier!
Also, thanks to everyone! Without this community and everyone's work on jj, I don't think ERSC or my job there could exist, at least not in its current form.

paid contributors: add myself as a newly minted ERSC employee

---

CHANGELOG.md
Cargo.lock
Cargo.toml

release: 0.33.0

---

cli/src/commands/help.rs
cli/tests/test_help_command.rs

cli: help: look up subcommand without using error path

---

cli/src/commit_templater.rs
lib/src/revset.rs
lib/tests/test_revset.rs

revset: require SymbolResolverExtension to be Send and Sync

---

docs/contributing.md

doc: add helix configuration in the contributing page

---

cli/src/commands/resolve.rs
cli/src/complete.rs
cli/tests/test_completion.rs

cli complete: resolve: only complete mutable conflicting revisions

---

cli/src/commands/status.rs
cli/tests/cli-reference@.md.snap

status: fix markdown list rendered on a single line

---

cli/src/cli_util.rs
cli/src/command_error.rs
cli/src/commands/git/init.rs
cli/src/commands/git/push.rs
cli/src/commands/log.rs
cli/src/commands/operation/diff.rs
cli/src/commands/resolve.rs
cli/src/commands/status.rs
cli/src/diff_util.rs
cli/src/formatter.rs
cli/src/git_util.rs
cli/src/templater.rs
cli/src/ui.rs

formatter: reimplement LabeledWriter as RAII type

---

cli/src/commands/commit.rs
cli/tests/cli-reference@.md.snap

Suggested in #7429.
If applicable:

cli: commit: explain that `jj describe && jj new` is equivalent

---

.config/codespell-additional-dict

It's used in #7392, and might be useful in the future.
If applicable:

codespell: disallow co-location as well

---

CHANGELOG.md
cli/src/commands/file/show.rs
cli/src/config-schema.json
cli/src/diff_util.rs
cli/src/merge_tools/builtin.rs
cli/src/merge_tools/external.rs
cli/tests/sample-configs/valid/merge.toml
cli/tests/test_new_command.rs
docs/config.md
lib/src/config/misc.toml
lib/src/conflicts.rs
lib/src/default_index/revset_engine.rs
lib/src/files.rs
lib/src/local_working_copy.rs
lib/src/repo.rs
lib/src/store.rs
lib/src/tree.rs
lib/tests/test_conflicts.rs
lib/tests/test_merged_tree.rs

Closes https://github.com/jj-vcs/jj/issues/17
If applicable:

files: add option to resolve conflicts word by word

---

cli/src/commit_templater.rs
cli/src/merge_tools/diff_working_copies.rs
lib/src/annotate.rs
lib/src/config/misc.toml
lib/src/conflicts.rs
lib/src/default_index/revset_engine.rs
lib/src/eol.rs
lib/src/files.rs
lib/src/fsmonitor.rs
lib/src/local_working_copy.rs
lib/src/merge.rs
lib/src/settings.rs
lib/src/tree_merge.rs
lib/src/working_copy.rs
lib/tests/test_git.rs
lib/tests/test_local_working_copy.rs
lib/tests/test_local_working_copy_concurrent.rs
lib/testutils/src/lib.rs

remove Default from some settings structs

---

cli/src/commands/simplify_parents.rs

simplify-parents: call `RevsetExpression::descendants()` using method syntax

---

CHANGELOG.md
cli/src/cli_util.rs
cli/src/commands/commit.rs
cli/src/commands/diffedit.rs
cli/src/commands/restore.rs
cli/src/commands/split.rs
cli/src/commands/squash.rs
cli/src/config/merge_tools.toml
cli/src/diff_util.rs
cli/src/merge_tools/builtin.rs
cli/src/merge_tools/diff_working_copies.rs
cli/src/merge_tools/external.rs
cli/src/merge_tools/mod.rs
cli/tests/test_diff_command.rs
docs/config.md

cli: diff: pass $width parameter to external diff tools

---

lib/src/simple_op_store.rs

op_store: drop support for legacy remote bookmarks without tracking state

---

cli/src/commands/gerrit/upload.rs
cli/src/config/templates.toml
cli/tests/test_commit_template.rs

templates: ensure unique prefixes in format_gerrit_change_id_trailer

---

cli/src/complete.rs

When completion is invoked, in many popular shells (like bash and zsh) `clap_complete` currently sends us the arguments exactly as they are typed, including shell quotes. For example, if the user types:
jj diff -f 'trunk()' ⇥
In order for us to accurately capture the revset, we must strip those quotes.
(Spaces inside the quoted string are handled correctly, for example if the revset is `'fork_point(@ | trunk())'` this is sent as a single argument)
This workaround handles the most common cases that work consistently accross shells, rather than going for maximum accuracy.
If applicable:

complete: ignore shell quotes when parsing command line

---

lib/src/op_store.rs
lib/src/protos/simple_op_store.proto
lib/src/protos/simple_op_store.rs
lib/src/simple_op_store.rs

op_store: serialize proto without constructing empty slot

---

cli/tests/test_gerrit_upload.rs

gerrit: fix a misplaced comment in test

---

cli/src/commands/gerrit/upload.rs
cli/tests/cli-reference@.md.snap

cli: help: remove details from short description of "gerrit upload"

---

docs/tutorial.md

**Disclaimer:** I am the author of "Jujutsu for everyone", so this may be considered self-promotion.

docs: add link to "Jujutsu for everyone" tutorial

---

docs/config.md

Make sure the links render as intended by fixing the order of link definitions, and inserting missing markup.

docs: Fix links in config.md

---

docs/FAQ.md

doc: fix minor typo in FAQ.md

---

docs/git-command-table.yml

Add untrack command for Jujutsu in git command table

---

CHANGELOG.md

changelog: mention new warning for bookmarking empty revision

---

CHANGELOG.md
cli/src/commands/metaedit.rs
cli/tests/cli-reference@.md.snap
cli/tests/test_metaedit_command.rs

metaedit: add --message option, closes #7634

---

docs/FAQ.md

doc: monitor jj log with watchexec

---

lib/src/repo.rs

repo: drop some leading underscores from function names

---

cli/src/commands/debug/object.rs

Add more convenience to `jj debug object view/tree`

---

cli/src/cli_util.rs

cli: when importing Git HEAD, reset working copy to new child commit
