jj-vcs/jj

.github/workflows/build.yml
lib/src/lock.rs
lib/src/working_copy.rs
lib/tests/test_commit_concurrent.rs
lib/tests/test_working_copy.rs
src/commands.rs
tests/test_init_command.rs

Tried to fix some obvious issues on Windows and get tests running.
Example GitHub CI run: https://github.com/quark-zju/jj/actions/runs/642045132

Various Windows fixes

---

lib/tests/test_git.rs

git: properly detect default branch

---

.editorconfig
.github/workflows/build.yml
Cargo.lock
Cargo.toml
benches/diff_bench.rs
lib/Cargo.toml
lib/build.rs
lib/src/diff.rs
lib/src/index.rs
lib/src/lib.rs
lib/src/nightly_shims.rs
lib/src/revset.rs
lib/src/revset_graph_iterator.rs
lib/tests/test_merge_trees.rs

Support stable Rust

---

docs/conflicts.md

[As discussed](https://github.com/martinvonz/jj/commit/423a894cba5c78a3e0cc30431e1dc9152c35bb3b#commitcomment-67049626)

Fix a link from 423a894

---

src/commands.rs

It can be useful in command prompts and scripts to be able to quickly
get e.g. the `jj status` output without spending time committing the
working copy (perhaps because some background process continuously
commits the working copy). One can already do that by passing
`--at-op=<operation ID>`, but then one needs to look up the operation
ID first. That is both extra work for the user/script and it means
there's an extra `jj op log` invocation to get the operation ID. Let's
have a global flag to make it easy and efficient to do.
This is flag is for a niche use case, so I don't think we need to document it (yet, at least).
There are no tests for the flag yet. I need to get around to adding tests for the CLI some day...

cli: add an option to avoid committing the working copy

---

README.md

Completion

---

.github/PULL_REQUEST_TEMPLATE.md

Does this seem reasonable (e.g. not too demanding), @arxanas?

Update GitHub templates

---

src/commands.rs

cli: don't print "Working copy now at:" when it's unchanged

---

README.md

Linux installation deps

---

src/commands.rs
src/ui.rs
tests/test_untrack_command.rs

cli: clarify error message when `jj untrack` argument is not ignored

---

src/commands.rs
tests/test_global_opts.rs

Error on unwanted repo arg

---

lib/src/backend.rs
lib/src/commit_builder.rs
src/testutils.rs
tests/smoke_test.rs
tests/test_global_opts.rs

Predictable hashes in tests

---

lib/src/git_backend.rs
src/commands.rs
tests/test_init_command.rs

Use relative path to .git/ when initializing in existing Git repo

---

.editorconfig
Cargo.lock
Cargo.toml
src/testutils.rs
tests/smoke_test.rs
tests/test_global_opts.rs

Test with `insta`

---

README.md
docs/git-compatibility.md

A few people in different forums asked if there's any reason to use
the native backend and what the reason for its existance is, so let's
document that.

docs: explain that the there's no reason to use the native backend

---

lib/src/diff.rs

Switch from BTreeMap to Vec in diff code

---

src/commands.rs
tests/test_git_push.rs

Disallow pushing conflicts

---

lib/src/commit_builder.rs
lib/src/settings.rs
src/commands.rs
src/testutils.rs
tests/smoke_test.rs
tests/test_git_push.rs
tests/test_global_opts.rs

More test updates

---

src/commands.rs
src/ui.rs
tests/test_init_command.rs

Check out Git HEAD on init

---

lib/src/diff.rs
src/commands.rs

Minor diff cleanup

---

docs/git-compatibility.md
lib/src/gitignore.rs
lib/src/working_copy.rs
lib/tests/test_working_copy.rs
lib/tests/test_working_copy_concurrent.rs
src/commands.rs
src/diff_edit.rs
src/testutils.rs
tests/test_gitignores.rs

.gitignores fixes for #65 & #87

---

CHANGELOG.md

I forgot to do this when I bumped the version number.

release: update release notes for 0.3.1

---

.github/workflows/scorecards.yml

This is a new recommendation for GitHub projects by Google employees.

github: add OSSF Scorecards security scanner

---

.github/dependabot.yml

This was another security recommendation for projects by Google
employees.

github: add a dependabot config

---

CHANGELOG.md

I keep forgetting to update things while doing a release...

release: include the two recent no-op releases in the changelog

---

.github/workflows/build.yml
.github/workflows/nix-linux.yml
.github/workflows/release.yml
.github/workflows/scorecards.yml

Pin GitHub action versions as requested by the security scanner

---

Cargo.lock
Cargo.toml
src/commands.rs

Switch to `clap`'s Derive API

---

CHANGELOG.md
lib/src/repo.rs
lib/tests/test_mut_repo.rs
src/commands.rs
src/testutils.rs
tests/smoke_test.rs
tests/test_git_push.rs
tests/test_gitignores.rs
tests/test_global_opts.rs
tests/test_init_command.rs
tests/test_new.rs
tests/test_untrack_command.rs

`jj new -m`

---

CHANGELOG.md
src/commands.rs
tests/test_log_command.rs

like `hg log -p`, which I think is useful with jj.

log: add -p/--patch option to show diff along with commit meta data

---

CHANGELOG.md
lib/src/git_backend.rs
lib/src/repo.rs
lib/src/testutils.rs
lib/src/workspace.rs
lib/tests/test_init.rs
lib/tests/test_workspace.rs
src/commands.rs
tests/test_git_colocated.rs
tests/test_init_command.rs

Fix for #177

---

lib/src/backend.rs
lib/src/conflicts.rs
lib/src/git_backend.rs
lib/src/local_backend.rs
lib/src/store.rs
lib/src/tree.rs
lib/src/working_copy.rs
lib/tests/test_conflicts.rs
lib/tests/test_merge_trees.rs
lib/tests/test_working_copy.rs
src/commands.rs

Backend conflict path

---

CHANGELOG.md
Cargo.lock
Cargo.toml
lib/Cargo.toml

This release is mostly about the fix for #177, which looks pretty bad
even though I think it is actually harmless. It also has `jj log -p`
contributed by @yuja!

release: release version 0.4.0

---

CHANGELOG.md
src/commands.rs
testing/fake-diff-editor.rs
tests/test_edit_command.rs
tests/test_move_command.rs
tests/test_print_command.rs
tests/test_squash_command.rs

More e2e tests (and a bonus `jj print` command)

---

CHANGELOG.md
src/commands.rs
src/ui.rs
tests/common/mod.rs
tests/test_edit_command.rs
tests/test_git_push.rs
tests/test_global_opts.rs
tests/test_move_command.rs
tests/test_print_command.rs
tests/test_restore_command.rs
tests/test_squash_command.rs
tests/test_ui.rs
tests/test_untrack_command.rs

Partial moves

---

CHANGELOG.md
Cargo.toml
src/commands.rs
src/main.rs
testing/fake-diff-editor.rs
testing/fake-editor.rs
tests/common/mod.rs
tests/test_describe_command.rs
tests/test_global_opts.rs
tests/test_split_command.rs

Make setting of editor more flexible, and add `jj split <paths>`

---

Cargo.toml
lib/Cargo.toml

cargo: specify MSRV (1.57 on lib and 1.58 on CLI)

---

CHANGELOG.md
lib/src/files.rs

merge: fix modify/delete conflict to not resolve

---

CHANGELOG.md
src/commands.rs

Rebasing onto no commits (i.e. onto the root commit) is almost
definitely not what you meant to do if you run `jj rebase` (without
any arguments).

cli: require at least one destination for rebase

---

src/commands.rs
tests/test_rebase_command.rs

Tests for rebase, and some minor fixes

---

CHANGELOG.md
docs/revsets.md
lib/src/revset.rs
lib/tests/test_revset.rs

I'm adding these now mostly because I think I'll use them for #168

Some more revsets functions

---

CHANGELOG.md
lib/src/working_copy.rs
lib/tests/test_working_copy.rs
src/commands.rs
tests/test_git_push.rs
tests/test_new.rs
tests/test_print_command.rs
tests/test_rebase_command.rs

Support for rebasing whole branch onto destination

---

Cargo.lock
lib/Cargo.toml
lib/src/git_backend.rs

cargo: upgrade `uuid` to 1.0.0

---

docs/tutorial.md

Minor documentation change. I'm not sure if this requires updating the changelog or not, as it's really minor, but if necessary please let me know and I can add that.

Remove out-of-date parenthetical in tutorial.md

---

lib/src/dag_walk.rs
lib/src/index.rs
lib/src/revset.rs
lib/src/revset_graph_iterator.rs
lib/src/stacked_table.rs
lib/src/tree.rs
lib/src/workspace.rs

Here are some cleanups you made me think of, @spectral54 :)

Options cleanups

---

CHANGELOG.md
lib/src/rewrite.rs
lib/tests/test_rewrite.rs
tests/test_move_command.rs

Fix a bug where rebase made a branch point to a hidden commit

---

CHANGELOG.md
src/commands.rs
tests/test_move_command.rs
tests/test_restore_command.rs
tests/test_undo.rs

CLI argument cleanup

---

CHANGELOG.md
docs/git-compatibility.md
lib/protos/working_copy.proto
lib/src/matchers.rs
lib/src/working_copy.rs
lib/tests/test_working_copy.rs
lib/tests/test_working_copy_sparse.rs
src/commands.rs
src/diff_edit.rs
tests/test_sparse_command.rs
tests/test_untrack_command.rs

Add support for sparse working copies (#52)

---

lib/src/working_copy.rs

When committing the working copy, we try to not visit ignored
directories (as e.g. `target/` often is), but we need to visit it if
there are already tracked files in it. I initially missed that in
c1060610bda2 and then fixed it in a028f33e3b21. The fix works by
checking if the next path after the ignored path is inside the ignore
path (viewed as a directory). However, I forgot to handle the case
where there are no paths at all after the ignored path. So, for
example, if the `target/` directory should be ignored and it there
were no tracked paths after `target/` in alphabetical order, we would
still visit the directory. That's why the bug reproduced in the
`git-branchless` repo but not in the `jj` repo (because there are
files under `testing/` and `tests/` here).
Closes #247.

working_copy: don't visit whole ignored tree even if last in order

---

lib/src/working_copy.rs

working_copy: switch an `if let Some() { } else { }` to a `match`

---

CHANGELOG.md
docs/revsets.md
lib/src/revset.pest
lib/src/revset.rs

revsets: allow single internal `-` and `+` characters in symbols (#46)

---

tests/smoke_test.rs
tests/test_describe_command.rs
tests/test_edit_command.rs
tests/test_git_push.rs
tests/test_global_opts.rs
tests/test_init_command.rs
tests/test_move_command.rs
tests/test_operations.rs
tests/test_print_command.rs
tests/test_rebase_command.rs
tests/test_restore_command.rs
tests/test_sparse_command.rs
tests/test_split_command.rs
tests/test_squash_command.rs
tests/test_untrack_command.rs
tests/test_workspaces.rs

tests: re-run with `insta` crate version b9d99e87065b

---

src/commands.rs

This is actually enough to fix #248, but I'll continue to work on
error handling for a while. I'd like to at least include the bad
object ID in this type of error messages.
Closes #248.

errors: fix some easy error propagation in `commands.rs`

---

Cargo.toml

cargo: move some test deps to `[dev-dependencies]`

---

CHANGELOG.md
src/commands.rs
tests/test_git_push.rs

Add a mode of pushing with branch taken from change ID 

---

src/commands.rs

cli: don't show `bench`/`debug` subcommands by default

---

lib/src/dag_walk.rs
lib/src/index.rs
lib/src/index_store.rs
lib/src/working_copy.rs
src/commands.rs

cleanup: use `while let Some(...)` instead of checking before popping

---

demos/demo_operation_log.sh
docs/git-comparison.md

docs: update stale references to `-o` argument deleted in 8744015f3305

---

src/diff_edit.rs

diff_edit: delete unused error variant (since 9e9727af4e33)

---

src/commands.rs
tests/test_branch_command.rs

cli: make `jj branch --revision/--delete/--forget` mutually-exclusive

---

CHANGELOG.md
src/commands.rs
src/formatter.rs
src/ui.rs
tests/test_branch_command.rs

cli: `jj branch` can accept any number of branches

---

.github/workflows/build.yml

Run clippy on all targets

---

flake.lock

nix: update lock file to nixpkgs with rust toolchain 1.60

---

.github/workflows/nix-linux.yml

github: don't override nixpkgs version (use the lock file's version) 

---

CHANGELOG.md
src/commands.rs
src/main.rs
tests/common/mod.rs
tests/test_alias.rs
tests/test_branch_command.rs
tests/test_global_opts.rs
tests/test_move_command.rs
tests/test_rebase_command.rs
tests/test_restore_command.rs
tests/test_untrack_command.rs

Exit code improvements

---

CHANGELOG.md
README.md
docs/tutorial.md
src/config.rs
src/lib.rs
src/main.rs
tests/test_global_opts.rs

Allow config in `~/.jjconfig.toml`

---

Cargo.lock
Cargo.toml
lib/Cargo.toml
src/graphlog.rs
tests/test_operations.rs

Fix padding in graphlog at end of chain

---

docs/git-comparison.md

I forgot to update the document in 30f5471fc363.

docs: mention `jj rebase -b` in git-comparison doc

---

src/templater.rs

cleanup: remove some unused lifetimes

---

lib/src/testutils.rs
lib/tests/test_bad_locking.rs
lib/tests/test_commit_builder.rs
lib/tests/test_commit_concurrent.rs
lib/tests/test_conflicts.rs
lib/tests/test_diff_summary.rs
lib/tests/test_git.rs
lib/tests/test_index.rs
lib/tests/test_init.rs
lib/tests/test_load_repo.rs
lib/tests/test_merge_trees.rs
lib/tests/test_mut_repo.rs
lib/tests/test_operations.rs
lib/tests/test_refs.rs
lib/tests/test_revset.rs
lib/tests/test_revset_graph_iterator.rs
lib/tests/test_rewrite.rs
lib/tests/test_view.rs
lib/tests/test_working_copy.rs
lib/tests/test_working_copy_concurrent.rs
lib/tests/test_working_copy_sparse.rs
lib/tests/test_workspace.rs

Test cleanups

---

.github/workflows/build.yml

github: fail CI on clippy warnings

---

src/commands.rs

Fixes #339.
I'm not sure if this change is desirable or not, but it seemed easier to just send a PR for review and see if it's accepted than start a discussion :)
I don't think this requires updating the changelog, but please let me know if that's not the case, and I'll add something there too.

Log names of created branch for `git push --change`.

---

CHANGELOG.md
lib/src/view.rs
src/commands.rs
tests/test_edit_command.rs
tests/test_rebase_command.rs
tests/test_squash_command.rs
tests/test_unsquash_command.rs
tests/test_workspaces.rs

Don't abandoned working copy emptied by `move/squash/unsquash`

---

docs/tutorial.md

replace references to `jj l` with `jj log`

---

src/commands.rs

None of our subcommands have any arguments at the level of the
subcommand family (e.g. no `jj git --foo fetch`), so we don't need to
wrap the `Subcommand` attribute in an `Args` attribute.

cli: remove unnecessary wrapping of `Subcommand` in `Args` struct

---

lib/src/matchers.rs

Add `IntersectionMatcher`

---

README.md
demos/demo_juggle_conflicts.sh
demos/demo_working_copy.sh
docs/branches.md
docs/git-comparison.md
src/commands.rs

docs: update to use new `jj branch` syntax

---

.github/PULL_REQUEST_TEMPLATE.md

github: include reminder about docs in PR template

---

lib/src/working_copy.rs
lib/tests/test_working_copy.rs

Ignore special files when snapshotting working copy

---

Cargo.lock
Cargo.toml

cargo: bump clap from v3.1.18 to v3.2.5

---

docs/git-compatibility.md

docs: explain that we don't support Git hooks

---

src/commands.rs
tests/test_git_clone.rs

On clone, check that destination is an empty dir if it exists

---

src/commands.rs

cli: if clone fails, delete destination directory

---

src/commands.rs

This addresses the issue from the title of #412. I haven't even looked into the rest of the report yet.
If applicable:

cli: fix mention of `jj git pull` to be `jj git fetch`

---

lib/src/git.rs
src/commands.rs
tests/test_git_push.rs

Make `jj git push` print what it's going to push

---

src/commands.rs
tests/test_git_push.rs

Fix two transaction bugs in `jj git push --change`

---

lib/src/commit_builder.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/src/testutils.rs
lib/src/transaction.rs
lib/tests/test_commit_builder.rs
lib/tests/test_merge_trees.rs
lib/tests/test_mut_repo.rs
lib/tests/test_operations.rs
lib/tests/test_revset.rs
lib/tests/test_rewrite.rs
lib/tests/test_view.rs
src/commands.rs

Avoid keeping references from before starting transaction

---

docs/related-work.md

Sturdy came up a while ago on lobste.rs when [jj was being discussed](https://lobste.rs/s/47zztj/jujutsu_dvcs).  I'm not sure if I described it well, or if it's something you want as related-work, especially since the sturdy founder claims to be solving different problems in the very thread.  But it does seem to be doing some similar things to removing the idea of an index/staging area.
If applicable:

Add Sturdy to related work

---

lib/src/conflicts.rs
lib/tests/test_conflicts.rs

conflicts: minimize diffs in materialized conflicts

---

lib/src/workspace.rs

workspace: remove upgrade code for workspace without `.jj/repo`

---

docs/config.md
docs/config.toml

As TOML allows comments I made it into a TOML file that can double as
a template config that someone can just drop in and get started, killing
two birds with one stone.
I'm not sure I got all the settings but it's a start.
docs: Added config settings to documentation.
If applicable:

First attempt at formally documenting available config settings.

---

lib/src/repo.rs
lib/src/store.rs
lib/src/testutils.rs
lib/src/workspace.rs

Make it a little easier to add a new backend

---

lib/src/conflicts.rs
lib/src/revset.rs
lib/src/working_copy.rs
lib/src/workspace.rs
lib/tests/test_merge_trees.rs
src/commands.rs

cleanup: fix some things reported by clippy 1.63

---

lib/src/file_util.rs

tests: don't leave /tmp/file, use tempfile::TempDir for cleanup

---

lib/src/working_copy.rs
lib/tests/test_working_copy.rs

Otherwise a file could be created out of the working copy directory.
This only works for untracked symlinks and sequentially "added" symlinks
and files. For "removed" and "modified" entries, the parent directories are
considered valid and fs::remove_file() will be called. This also doesn't
prevent race conditions caused by concurrent checkouts.
New create_parent_dirs() would be slightly slower than the original because
it traverses directories from the root whereas fs::create_dir_all() does that
from the leaf and exits when reached to a directory.
If applicable:

working_copy: don't follow symlinks while creating parent directories

---

README.md

Link to discord from README

---

docs/git-comparison.md
docs/related-work.md
docs/revsets.md
docs/tutorial.md
docs/working-copy.md

Minor doc updates, mostly about `jj workspace`

---

CHANGELOG.md
README.md
docs/git-comparison.md
docs/tutorial.md
docs/working-copy.md
lib/src/settings.rs
src/commands.rs
tests/test_checkout.rs
tests/test_move_command.rs
tests/test_rebase_command.rs
tests/test_squash_command.rs
tests/test_touchup_command.rs
tests/test_unsquash_command.rs

Disable open commits by default

---

README.md

readme: make link to Discord a button

---

CHANGELOG.md
src/commands.rs
testing/fake-editor.rs
tests/test_describe_command.rs
tests/test_move_command.rs
tests/test_obslog_command.rs
tests/test_squash_command.rs
tests/test_touchup_command.rs
tests/test_unsquash_command.rs
tests/test_workspaces.rs

Make `jj move/squash/unsquash` ask for combined description

---

CHANGELOG.md
src/commands.rs
tests/test_new_command.rs
tests/test_rebase_command.rs
tests/test_squash_command.rs
tests/test_touchup_command.rs
tests/test_unsquash_command.rs

Teach `jj new` to accept multiple revisions, and make `jj merge` delegate to it

---

src/commands.rs
tests/test_new_command.rs

add sanity check to "jj new" parent revisions

---

Cargo.lock
Cargo.toml
deny.toml
lib/Cargo.toml

Our current version of `cpufeatures` so we needed to upgrade at least
that.
If applicable:

cargo: run `cargo update`

---

.github/workflows/dependabot.yml

Hopefully this is the last bit I was missing to get this to work :)
If applicable:

github: give dependabot auto-merge action permission to update PR

---

src/commands.rs

cli: add a `version` command

---

src/commands.rs

cli: document repeated `-d` arguments for `jj rebase`

---

src/commands.rs
tests/test_rebase_command.rs

cli: ensure rebase destinations are unique and not form a merge with root

---

src/config.rs

Fix typo in error message

---

CHANGELOG.md
README.md
lib/src/revset.rs
lib/tests/test_revset.rs
src/commands.rs
tests/test_log_command.rs

add naive implementation of `jj log PATH`

---

.github/workflows/scorecards.yml

github: add new required permissions for ossf/scorecard

---

CHANGELOG.md
docs/git-compatibility.md
docs/operation-log.md
docs/technical/concurrency.md
docs/working-copy.md
lib/src/op_store.rs
lib/src/protos/op_store.proto
lib/src/protos/working_copy.proto
lib/src/repo.rs
lib/src/revset.rs
lib/src/rewrite.rs
lib/src/simple_op_store.rs
lib/src/view.rs
lib/tests/test_init.rs
lib/tests/test_mut_repo.rs
lib/tests/test_revset.rs
lib/tests/test_rewrite.rs
lib/tests/test_view.rs
lib/tests/test_working_copy.rs
lib/tests/test_working_copy_concurrent.rs
lib/tests/test_workspace.rs
src/commands.rs
src/formatter.rs
src/template_parser.rs
src/templater.rs
tests/test_workspaces.rs

Rename "checkout" (noun) to "working-copy commit" in docs and code

---

docs/conflicts.md

docs: describe our unusual conflict marker style

---

lib/src/conflicts.rs

We no longer need body_seen because the header lines are deterministic.
If applicable:

conflicts: simplify state management of parse_conflict_hunk()

---

lib/src/backend.rs
lib/src/commit.rs
lib/src/commit_builder.rs
lib/src/git_backend.rs
lib/src/local_backend.rs
lib/src/rewrite.rs
lib/src/store.rs
lib/src/testutils.rs
lib/tests/test_commit_builder.rs
lib/tests/test_init.rs
lib/tests/test_merge_trees.rs
lib/tests/test_revset.rs
lib/tests/test_rewrite.rs
src/commands.rs

Move root commit handling into backends

---

lib/src/commit.rs
lib/src/index.rs
lib/src/repo.rs
lib/src/rewrite.rs
src/commands.rs

commit: minor cleanup after 010867308714

---

docs/git-compatibility.md

Add hyperlink target for 405

---

lib/src/git.rs
src/commands.rs
tests/test_git_push.rs

Clarify failure to push git refs

---

Cargo.lock
Cargo.toml
examples/custom-command/main.rs
src/cli_util.rs
src/commands.rs
tests/test_global_opts.rs

Update to clap 4

---

lib/src/revset.rs
lib/src/rewrite.rs
lib/src/simple_op_store.rs
lib/tests/test_working_copy.rs
src/cli_util.rs
src/commands.rs

cleanup: rename some more variables from `checkout_*` to ~`wc_`

---

lib/src/index.rs
lib/src/local_backend.rs
lib/src/op_store.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/stacked_table.rs
lib/src/working_copy.rs
src/graphlog.rs
tests/test_init_command.rs

Clippy-suggested cleanups

---

src/commands.rs

This came up in discussion #620.
If applicable:

cli: clarify that the "first" commit created by `split` is the parent

---

src/cli_util.rs
src/commands.rs
tests/test_concurrent_operations.rs

Adjust when snapshotting happens

---

src/commands.rs

See how this looks, @jsoref. I'm happy to update it if it's still unclear.

cli: clarify `jj branch forget` help

---

CHANGELOG.md
Cargo.lock
Cargo.toml
lib/Cargo.toml

It's been several months since the last release and a lot has changed. Probably the biggest change is that open commits are now disabled by default.
If applicable:

release: release version 0.5.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
lib/Cargo.toml

This point of this release is just to trigger the release automation on GitHub.
If applicable:

release: release version 0.5.1

---

.github/workflows/build.yml
.github/workflows/release.yml

github: move off of unmaintained actions-rs actions

---

src/ui.rs

cli: simplify relative_path(), address some ".." handling TODOs

---

docs/git-compatibility.md

docs: fix typo in Git config `core.excludesFile`

---

lib/src/file_util.rs
lib/src/repo_path.rs
src/cli_util.rs
src/commands.rs
src/ui.rs

code move so user file patterns can be resolved in lib crate

---

CHANGELOG.md
docs/revsets.md
lib/src/repo_path.rs
lib/src/revset.rs
lib/tests/test_revset.rs
src/cli_util.rs
src/commands.rs
tests/test_log_command.rs

revset: implement `file(pattern[, candidates])` predicate

---

Cargo.lock
Cargo.toml
src/commands.rs
src/lib.rs
src/progress.rs
src/ui.rs

Progress reporting improvements

---

CHANGELOG.md
docs/revsets.md
lib/src/revset.rs
lib/tests/test_revset.rs
src/cli_util.rs
src/commands.rs

revset: optimize filter expression, remove redundant candidates argument

---

docs/git-compatibility.md

docs: explain that we don't support shallow clones (#675)

---

lib/src/repo.rs

The function has only one caller since 25b922cd0ba6 and it's pretty small. Inlining also means we can reuse the joined paths created in it, so I did that by extracting variables for them.
If applicable:

repo: inline single-user `init_repo_dir()`

---

lib/src/repo.rs

repo: remove unused error type

---

lib/src/repo.rs
lib/src/testutils.rs
lib/src/workspace.rs
lib/tests/test_git.rs
lib/tests/test_workspace.rs
src/cli_util.rs

Some additional work to be done in this area, but this is a start.
If applicable:

Panic less on error

---

CHANGELOG.md
lib/src/git.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/src/workspace.rs
lib/tests/test_git.rs
tests/test_git_colocated.rs

Fix two bugs in `jj git import` (and auto-import when colocated)

---

src/commands.rs

We already have the variant imported and we use it so much that it seems reasonable to use it instead of qualifying it by the `CommandError` type.
If applicable:

cleanup: use imported `UserError` variant instead of qualifying

---

CHANGELOG.md
docs/revsets.md
lib/src/revset.rs
lib/tests/test_revset.rs
src/cli_util.rs
src/commands.rs

revset: resolve file paths at parsing stage, accept multiple file(path, ...)

---

Cargo.lock
lib/Cargo.toml
lib/src/testutils.rs

Saves a dependency.
If applicable:

testutils: replace lazy_static with once_cell

---

lib/src/revset.rs
tests/test_revset_output.rs

revset: refactor function argument handling, report error with span

---

src/commands.rs
tests/common/mod.rs
tests/test_git_clone.rs
tests/test_init_command.rs

Fix crash on `jj init --git-repo=non-existent`

---

lib/src/repo.rs

This is perfect use case of OnceCell per the safety comment in index().
If applicable:

repo: use OnceCell instead of Mutex<Option<_>> to store index

---

src/commands.rs

cli: replace "current checkout" by "working-copy commit"

---

src/commands.rs

Example:
JJ: Enter commit description for the first part (parent).
Better split commit message
JJ: This part contains the following changes:
JJ:   M src/formatter.rs
JJ:
JJ: Lines starting with "JJ: " (like this one) will be removed.

Include file list when editing split commit description

---

src/progress.rs

That is, an error in jj introduced by rebasing, not an error in the implementation of `rebase` :D
If applicable:

cli: fix rebase error

---

CHANGELOG.md

changelog: fix typo ("specity")

---

lib/src/repo.rs

repo: extract unsafe view handling bits to separate struct

---

src/cli_util.rs
src/commands.rs
tests/test_init_command.rs
tests/test_untrack_command.rs

Separate out hints from errors, don't print them in red

---

CHANGELOG.md
lib/src/git.rs
lib/src/repo.rs
lib/src/simple_op_store.rs
lib/src/view.rs
lib/tests/test_bad_locking.rs
lib/tests/test_commit_concurrent.rs
lib/tests/test_git.rs
lib/tests/test_index.rs
lib/tests/test_init.rs
lib/tests/test_load_repo.rs
lib/tests/test_mut_repo.rs
lib/tests/test_operations.rs
lib/tests/test_revset.rs
lib/tests/test_view.rs
lib/tests/test_working_copy.rs
src/cli_util.rs
src/commands.rs
tests/test_git_colocated.rs
tests/test_templater.rs

Fix branch-level conflicts on `git export` (#463)

---

tests/test_git_push.rs

Since we don't have the `git` binary available in the test environment, it's just easier to use `jj` commands to create Git repos.
If applicable:

test_git_push: create Git repo using `jj` commands

---

lib/src/op_heads_store.rs
lib/src/op_store.rs
lib/src/repo.rs
lib/src/transaction.rs

Store full `OperationMetadata` in `Transaction`

---

docs/tutorial.md
src/commands.rs
src/template_parser.rs
tests/test_alias.rs
tests/test_init_command.rs
tests/test_obslog_command.rs

Allow using strings in if-conditions in templates, removing some ugly whitespace

---

docs/tutorial.md

tutorial: add a few missing "(no description set)"

---

CHANGELOG.md
lib/src/repo.rs
lib/src/settings.rs
lib/src/transaction.rs
lib/src/workspace.rs
lib/tests/test_bad_locking.rs
lib/tests/test_commit_builder.rs
lib/tests/test_commit_concurrent.rs
lib/tests/test_git.rs
lib/tests/test_index.rs
lib/tests/test_init.rs
lib/tests/test_load_repo.rs
lib/tests/test_merge_trees.rs
lib/tests/test_mut_repo.rs
lib/tests/test_operations.rs
lib/tests/test_refs.rs
lib/tests/test_revset.rs
lib/tests/test_revset_graph_iterator.rs
lib/tests/test_rewrite.rs
lib/tests/test_view.rs
lib/tests/test_working_copy.rs
src/cli_util.rs
tests/test_operations.rs

Make username@hostname in operation log configurable

---

CHANGELOG.md

changelog: fix typo ("he" instead of "the")

---

Cargo.lock
Cargo.toml
lib/Cargo.toml
src/commands.rs
src/template_parser.rs

cargo: upgrade chrono to version 0.4.23

---

lib/src/revset.pest
lib/src/revset.rs
lib/tests/test_revset.rs

revset: allow empty string literal ""

---

lib/src/revset.rs

Per the discussion in #764.
If applicable:

revset: add comment about subtle optimization issue regarding hidden commits

---

tests/common/mod.rs
tests/test_alias.rs
tests/test_branch_command.rs
tests/test_edit_command.rs
tests/test_global_opts.rs
tests/test_move_command.rs
tests/test_new_command.rs
tests/test_rebase_command.rs
tests/test_restore_command.rs
tests/test_untrack_command.rs

tests: assert result of `TestEnvironment::jj_cmd_cli_error`

---

tests/test_alias.rs
tests/test_global_opts.rs

tests: suppress must_use warning and update cli_error output

---

CHANGELOG.md
lib/src/revset.rs
src/cli_util.rs
src/commands.rs
tests/test_log_command.rs

log: warn if the provided path looks like a revset

---

lib/src/settings.rs
lib/src/transaction.rs
lib/testutils/src/lib.rs
src/cli_util.rs
src/config.rs
src/diff_edit.rs
tests/common/mod.rs
tests/test_concurrent_operations.rs
tests/test_operations.rs

Make operation IDs deterministic in tests

---

lib/src/revset.pest
lib/src/revset.rs
tests/test_revset_output.rs

revset: simplify pasing rule, migrate operator parsing to PrattParser

---

lib/src/git.rs
src/commands.rs

feature: add verbose logging for clone/fetch command

---

docs/contributing.md

I worte up some things I wish I knew when I wrote my first PR.

Document suggestions for a `jj` development environment

---

docs/contributing.md

Polish `jj` development environment suggestions

---

CHANGELOG.md
docs/revsets.md
lib/src/revset.pest
lib/src/revset.rs
tests/test_revset_output.rs

revset: implement function alias expansion

---

src/cli_util.rs
src/commands.rs
tests/test_branch_command.rs
tests/test_git_colocated.rs
tests/test_git_export.rs
tests/test_log_command.rs

Disallow empty strings in revision and branch name arguments

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

changelog: thank people who contributed to a release

---

tests/test_revset_output.rs

tests: update revset error message after 8b00a64ab294 and 48d10d648c0c

---

docs/config.md

docs: clarify diff editor interface

---

lib/src/revset.rs

revset: inline simple RevsetIterators

---

src/commands.rs

The example for the `-b` flag was completely incorrect. It looks like I have copied the example from `-r` and then forgotten to update it. This fixes that, and also adds some more commits to the example to hopefully clarify.
If applicable:

cli: correct and clarify rebase help text

---

CHANGELOG.md
README.md

Originally written by @xxxserxxx.
If applicable:

readme: add some badges

---

src/ui.rs

cli: add missing newline to pager error messages, colorlize error

---

lib/tests/test_view.rs

view: add test merging divergent rewrites results in both commits visible

---

.github/workflows/dependabot.yml

cli/cli#1314 is now marked fixed, so let's see if this works.
If applicable:

github: new attempt at auto-enabling merge of Dependabot PRs

---

docs/config.md
src/commands.rs
src/config.rs
src/ui.rs

cli: split pager arguments, accept array of arguments

---

.github/PULL_REQUEST_TEMPLATE.md
docs/contributing.md

Let me know if you disagree with the text
If applicable:

docs: describe how we do code reviews

---

CHANGELOG.md
lib/src/git.rs
lib/tests/test_git.rs

Improvements to `jj git export`

---

CHANGELOG.md
docs/config.md
docs/config.toml
lib/src/conflicts.rs
lib/src/files.rs
lib/tests/test_conflicts.rs
src/cli_util.rs
src/commands.rs
src/config.rs
src/diff_edit.rs
testing/fake-editor.rs
tests/common/mod.rs
tests/test_resolve_command.rs
tests/test_restore_command.rs
tests/test_touchup_command.rs

As discussed in https://github.com/martinvonz/jj/issues/18.

New `jj resolve` command to use an external merge tool for conflict resolution.

---

CHANGELOG.md
Cargo.toml
lib/Cargo.toml
lib/src/content_hash.rs
lib/src/legacy_thrift_op_store.rs
lib/src/lib.rs
lib/src/local_backend.rs
lib/src/proto_op_store.rs
lib/src/simple_op_store.rs

Upgrade operation log from Thrift to Protobuf

---

CHANGELOG.md
lib/src/git.rs
lib/src/git_backend.rs

Fix crash on Git GC

---

CHANGELOG.md
docs/config.md
src/ui.rs

pager: default to `less -FRX`

---

src/commands.rs

cli: spawn pager after command arguments are validated

---

lib/src/revset.rs

revset: make filter node unary, move candidates to outer intersection

---

src/commands.rs

Use pager for a few more commands

---

src/commands.rs
tests/test_resolve_command.rs

Very minimal version of `jj resolve --list`, good enough for tests. This PR includes https://github.com/martinvonz/jj/pull/842, feel free to just review this one.

Minimal version of `jj resolve --list`.

---

CHANGELOG.md
docs/working-copy.md
src/cli_util.rs
src/commands.rs
tests/test_workspaces.rs

Make update off stale working copy require explicit action from the user

---

flake.nix

Add legacy-thrift feature to nix flake.

---

CHANGELOG.md
Cargo.lock
Cargo.toml
lib/Cargo.toml

Lots of new features and important bugfixes. Thanks, everyone!
If applicable:

release: release version 0.6.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
flake.nix
lib/Cargo.toml
lib/testutils/Cargo.toml

Release version 0.6.1 with dependency on released `thrift` crate

---

CHANGELOG.md
docs/operation-log.md
docs/technical/concurrency.md

I seem to have forgotten to update this when I added support for workspaces a while back.
I made some other little touchups while at it.
If applicable:

docs: mention that the "view" object knows about all workspaces

---

CHANGELOG.md
src/cli_util.rs
tests/test_git_colocated.rs

In colocated case, also export refs on snapshot

---

docs/tutorial.md

I made some other little touchups while at it.
Closes #840
If applicable:

tutorial: mention `jj edit` and when it's useful

---

lib/src/index.rs
lib/tests/test_index.rs

index: add RevWalk variant that can be filtered by generation

---

src/cli_util.rs
tests/test_operations.rs

cli: resolve operation symbol first and apply '-' postfix repeatedly

---

.github/PULL_REQUEST_TEMPLATE.md

Stop telling contributors to add themselves to the changelog

---

.github/workflows/dependabot.yml

Trying the advice from
https://github.com/cli/cli/issues/6695#issuecomment-1348430969
If applicable:

github: new attempt at Dependabot auto-merge

---

src/commands.rs
src/diff_util.rs
src/lib.rs

cli: extract show_diff*() functions and structs to new module

---

lib/src/tree.rs

Just for sanity. It wouldn't matter unless the iterator implements Drop.
https://doc.rust-lang.org/reference/destructors.html
If applicable:

tree: ensure Tree outlives its iterator on dropping self-referential struct

---

examples/custom-backend/main.rs
lib/src/legacy_thrift_op_store.rs
lib/src/op_store.rs
lib/src/proto_op_store.rs
lib/src/repo.rs
lib/src/simple_op_store.rs
lib/src/workspace.rs
lib/tests/test_bad_locking.rs
lib/tests/test_commit_concurrent.rs
lib/tests/test_git.rs
lib/tests/test_index.rs
lib/tests/test_load_repo.rs
lib/tests/test_working_copy_concurrent.rs
lib/tests/test_workspace.rs
lib/testutils/src/lib.rs
src/cli_util.rs

op_store: refactor OpStore with factory semantics

---

benches/diff_bench.rs
lib/build.rs
lib/src/git.rs
lib/src/git_backend.rs
lib/src/index.rs
lib/src/matchers.rs
lib/src/stacked_table.rs
lib/src/working_copy.rs
lib/tests/test_merge_trees.rs
lib/tests/test_revset.rs
lib/tests/test_working_copy.rs
lib/tests/test_working_copy_concurrent.rs
lib/testutils/src/lib.rs
src/cleanup_guard.rs
src/cli_util.rs
src/commands.rs
src/diff_util.rs
src/main.rs
src/progress.rs
src/template_parser.rs
src/templater.rs
src/ui.rs
testing/fake-diff-editor.rs
testing/fake-editor.rs
tests/common/mod.rs

Run new Clippy

---

src/config.rs
src/merge-tools.toml

 extract stock merge-tools config to file, add kdiff3.edit-args

---

src/cli_util.rs
tests/test_checkout.rs

cli: show hint if e.g. checkout revset resolved to multiple revisions

---

lib/src/repo_path.rs
lib/src/revset.rs
src/cli_util.rs
src/commands.rs
src/diff_edit.rs

cleanup: leverage Itertools::try_collect() instead of turbofish

---

lib/src/lib.rs
lib/src/op_heads_store.rs
lib/src/repo.rs
lib/src/simple_op_heads_store.rs
lib/src/workspace.rs
lib/tests/test_git.rs
lib/tests/test_operations.rs
lib/testutils/src/lib.rs
src/cli_util.rs

op_heads_store: refactor into factory semantics

---

docs/contributing.md

docs: touch up contributor guide, mentioning `cargo test --workspace`

---

Cargo.lock
Cargo.toml
lib/Cargo.toml
src/commands.rs

cli: clean up I/O code in edit_description()

---

Cargo.toml

cargo: add testutils to workspace

---

lib/src/revset.pest
lib/src/revset.rs
tests/test_revset_output.rs

revset: parse some hg/git-like operators and show hint

---

src/commands.rs
src/diff_util.rs
testing/fake-editor.rs
tests/test_commit_command.rs
tests/test_describe_command.rs
tests/test_move_command.rs
tests/test_resolve_command.rs
tests/test_split_command.rs
tests/test_squash_command.rs
tests/test_unsquash_command.rs

cli: include diff summary in commit/describe editor content

---

lib/src/backend.rs

backend: deduplicate id newtype impls by using declarative macro

---

lib/src/git.rs

git: diff refs to export without building dummy view

---

examples/custom-command/main.rs
lib/src/commit_builder.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/src/store.rs
lib/src/workspace.rs
lib/tests/test_bad_locking.rs
lib/tests/test_commit_builder.rs
lib/tests/test_commit_concurrent.rs
lib/tests/test_git.rs
lib/tests/test_index.rs
lib/tests/test_init.rs
lib/tests/test_load_repo.rs
lib/tests/test_merge_trees.rs
lib/tests/test_mut_repo.rs
lib/tests/test_operations.rs
lib/tests/test_revset.rs
lib/tests/test_rewrite.rs
lib/tests/test_view.rs
lib/tests/test_working_copy.rs
lib/testutils/src/lib.rs
src/cli_util.rs
src/commands.rs

give `CommitBuilder`s a reference to `MutableRepo`

---

CHANGELOG.md
src/cli_util.rs
src/commands.rs
tests/test_config_command.rs

Partially fixes #531.
If applicable:

Add a "config" command with "list" subcommand

---

src/cli_util.rs

cli_util: fix typo

---

examples/custom-backend/main.rs
examples/custom-command/main.rs
src/cli_util.rs
src/formatter.rs
src/main.rs
src/ui.rs

 cli: create default ui, then reconfigure with loaded user settings

---

lib/src/backend.rs
lib/src/commit_builder.rs
lib/src/conflicts.rs
lib/src/git.rs
lib/src/git_backend.rs
lib/src/index.rs
lib/src/legacy_thrift_op_store.rs
lib/src/local_backend.rs
lib/src/proto_op_store.rs
lib/src/refs.rs
lib/src/revset.rs
lib/src/rewrite.rs
lib/src/simple_op_store.rs
lib/src/tree.rs
lib/src/working_copy.rs
lib/tests/test_git.rs
lib/tests/test_revset.rs
src/cli_util.rs
src/commands.rs
src/diff_util.rs
src/templater.rs

Currently failing these tests:
```
FAIL [   0.930s]                  jujutsu-lib::test_revset test_resolve_symbol_change_id
FAIL [   0.962s]                  jujutsu-lib::test_revset test_resolve_symbol_commit_id
FAIL [   2.316s]                 jujutsu::test_new_command test_new_merge
```
If applicable:

Update Git backend error messaging

---

examples/custom-backend/main.rs
examples/custom-command/main.rs
src/cli_util.rs
src/main.rs
tests/test_global_opts.rs

cli: extract thin wrapper for tracing initialization

---

examples/custom-backend/main.rs
examples/custom-command/main.rs
src/cli_util.rs
src/main.rs

cli: add builder type that handles CLI initialization and teardown

---

src/cli_util.rs
src/commands.rs
src/diff_util.rs
src/merge_tools.rs
src/ui.rs

cli: prepare for ui.settings()/ui.cwd() removal

---

examples/custom-backend/main.rs
examples/custom-command/main.rs
src/cli_util.rs
src/commands.rs
src/ui.rs

cli: move ui.cwd()/settings() to CommandHelper

---

src/cli_util.rs
tests/test_global_opts.rs

cli: do not look up workspace path more than once, reuse WorkspaceLoader

---

CHANGELOG.md
src/commands.rs
src/config/colors.toml
src/templater.rs
tests/test_commit_template.rs
tests/test_log_command.rs
tests/test_templater.rs
tests/test_unsquash_command.rs

This follows up on a [discussion] in a previous PR https://github.com/martinvonz/jj/pull/941.
After using this for a while, I like it.
[discussion]: https://github.com/martinvonz/jj/pull/941#issuecomment-1363551162
If applicable:
- (partial) I have added tests to cover my changes

`jj log`: Replace divergent label with ?? and red color

---

src/cli_util.rs
src/commands.rs
tests/test_git_push.rs

Shorten the git push branch when possible using the short change ID hash

---

src/cli_util.rs
src/commands.rs
src/diff_util.rs
src/formatter.rs
src/merge_tools.rs
src/ui.rs

cli: introduce wrapper to writeln!() a message with label 

---

docs/contributing.md

docs: don't recommend running `cargo fmt` in the background

---

Cargo.lock
lib/Cargo.toml
lib/src/git_backend.rs

drop dependency on "uuid"

---

lib/tests/test_revset.rs

tests: stabilize change id in test_resolve_symbol_commit_id()

---

examples/custom-command/main.rs
src/cli_util.rs
src/commands.rs
tests/test_checkout.rs
tests/test_workspaces.rs

cli: replace short_commit_description() with commit summary template

---

Cargo.lock
Cargo.toml
deny.toml
flake.nix
lib/src/settings.rs
src/commands.rs
src/graphlog.rs

Add sapling graph formatters as an option

---

Cargo.lock
Cargo.toml
flake.nix

Fixes nondeterministic build results.

cargo: specify explicit rev for git dep on dag

---

src/merge_tools.rs

This is the canonical way of forwarding an error message with the "thiserror" crate.
Very minor.
If applicable:

style: use #[error(transparent)] instead of #[error("{0}")]

---

src/commands.rs

cli: fix panic on invalid git.fetch/push config value

---

lib/src/git_backend.rs

By inlining `wite_commit_internal()` into `write_commit()`, we can avoid redoing some steps when we retry. This includes taking the mutex lock, and reading the tree object and parent commits. It also means that we avoid cloning the input commit object, which we otherwise would even in the non-retrying case. I haven't measured if any of this makes a significant difference, but I think it also slightly simplifies the code, so it doesn't have to.
If applicable:

git_backend: avoid redoing some steps when retrying in `write_commit()`

---

lib/src/repo.rs

This is the usual convention (to save on compilation time when not running tests).
If applicable:

repo: move `test_id_index()` into a `tests` module

---

.github/workflows/build.yml

It seems that at least examples are not included in the default set of targets, and we clearly want to check that the examples compile, as that's an important reason we have them. We don't have any tests for the examples yet, but let's add the flag now so we don't forget it later.
If applicable:

github: build and test all targets

---

src/template_parser.rs
src/templater.rs
tests/test_commit_template.rs
tests/test_init_command.rs
tests/test_log_command.rs
tests/test_obslog_command.rs

templater: refactor commit_id/change_id handling

---

flake.nix

This got lost in an unfortunate merge.
Apparently I need to learn better how to use `jj` properly.
If applicable:

Also update MSRV in `flake.nix`

---

docs/github.md

docs: fix some typos in github.md, and reformat it

---

lib/src/index.rs

index: deduplicate binary search functions of commit_id lookup

---

lib/src/git.rs
lib/src/index.rs
lib/src/working_copy.rs

We can't use `bool::then_some()` since it is not stable in 1.61 (our MSRV).
If applicable:

style: use bool::then()

---

lib/src/op_heads_store.rs

refactor: use #[from] on error alternative

---

lib/src/repo.rs

repo: turn IdIndex into sorted Vec, use binary search

---

CHANGELOG.md
src/commands/mod.rs
src/commands/operation.rs
src/diff_util.rs
src/formatter.rs
src/ui.rs

Sanitize ANSI escapes in output

---

CHANGELOG.md
src/cli_util.rs
src/commands/mod.rs
src/template_parser.rs
src/templater.rs

templater: add support for labeled output of structured value types

---

src/template_parser.rs
src/templater.rs

templater: minor structure cleanup

---

README.md

readme: link to Git Merge 2022 talk for info about Google's plans

---

lib/src/repo.rs
lib/src/workspace.rs
src/cli_util.rs
src/commands/mod.rs
tests/test_edit_command.rs

Improve error handling in `MutableRepo::checkout/edit`

---

lib/src/repo.rs
src/templater.rs

repo: proxy shortest unique prefix function through RepoRef

---

src/cli_util.rs
src/commands/mod.rs

cli: move run_mergetool/edit_diff/select_diff to transaction wrapper

---

lib/src/index.rs
lib/src/repo.rs
lib/src/revset.rs
lib/tests/test_revset.rs
src/templater.rs

repo: leverage IdIndex for change id resolution and divergent template

---

tests/test_obslog_command.rs

The regex no longer works and the change ids are no longer random since a few weeks ago.

test_obslog_command.rs: stop removing change ids

---

src/commands/mod.rs
tests/test_squash_command.rs

cli: fix jj squash on empty commit

---

src/template_parser.rs
src/templater.rs

templater: remove Box<dyn> from generic wrappers, parameterize type

---

lib/src/index.rs
lib/src/repo.rs

index: clean up prefix resolution functions

---

CHANGELOG.md
docs/config.md
docs/tutorial.md
src/cli_util.rs
src/commands/config-schema.json
src/commands/mod.rs
src/config/misc.toml
tests/test_alias.rs

rename [alias] to [aliases]

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docs/config.md
flake.nix
lib/src/settings.rs
src/graphlog.rs
tests/test_log_command.rs

Enable Sapling's graphlog styles by default

---

CHANGELOG.md
docs/config.md
lib/src/settings.rs
src/graphlog.rs
tests/test_log_command.rs

Rename `ui.graph.format` to `ui.graph.style`, plus a cleanup

---

docs/config.md

docs: describe color configuration

---

src/template.pest
src/template_parser.rs

templater: clean up method chaining

---

.envrc
flake.lock
flake.nix

The goal would be to address all issues that keep us from using `.envrc`.
If applicable:

Several improvements to the nix flake

---

lib/src/dag_walk.rs

dag_walk: delete unused `common_ancestor()`

---

src/commands/mod.rs
src/template.pest
src/template_parser.rs

templater: disallow empty template term, fix parsing of empty arguments

---

src/template_parser.rs
src/templater.rs

Do we prefer this over explicit TemplateProperty structs?
If applicable:

templater: add newtype to implement property over closure

---

src/template_parser.rs
tests/test_templater.rs

templater: unify parse_commit_term() functions

---

src/commands/config-schema.json

Support new table form of color settings per Martin's suggested in https://github.com/martinvonz/jj/pull/1160#pullrequestreview-1276574115.

Update schema for [colors] to allow either string or table values

---

src/commands/mod.rs
tests/test_split_command.rs

split: give warning when given paths don't match anything

---

CHANGELOG.md
src/cli_util.rs
src/commands/mod.rs
src/template_parser.rs
src/templater.rs
tests/test_checkout.rs
tests/test_commit_command.rs
tests/test_concurrent_operations.rs
tests/test_diff_command.rs
tests/test_duplicate_command.rs
tests/test_edit_command.rs
tests/test_git_colocated.rs
tests/test_log_command.rs
tests/test_move_command.rs
tests/test_new_command.rs
tests/test_squash_command.rs
tests/test_templater.rs
tests/test_undo.rs
tests/test_unsquash_command.rs
tests/test_workspaces.rs

templater: do not complete "(no description set)" by default

---

.github/PULL_REQUEST_TEMPLATE.md

We have forgotten this many times already.
If applicable:

github: add reminder to update config schema in PRs

---

CHANGELOG.md
src/cli_util.rs
tests/test_concurrent_operations.rs
tests/test_edit_command.rs
tests/test_global_opts.rs
tests/test_workspaces.rs

Rename `--no-commit-working-copy` to `--ignore-working-copy`

---

CHANGELOG.md
src/commands/mod.rs
src/template_parser.rs
src/templater.rs
tests/test_global_opts.rs
tests/test_log_command.rs

cli: use label() to highlight "working_copy" commit in log template

---

src/commands/branch.rs
src/commands/mod.rs

Split up `cmd_branch()` and `cmd_config()` into subcommands

---

src/cli_util.rs

Make CliRunner::add_global_args() work before add_subcommand()

---

src/template_parser.rs
src/templater.rs
tests/test_templater.rs

templater: add support for evaluating method arguments

---

src/commands/mod.rs

style: use helper instead of buiding UserError by hand

---

CHANGELOG.md
docs/config.md
src/merge_tools.rs

 cli: allow to set ui.diff/merge-editor arguments inline

---

src/cli_util.rs
src/config.rs
src/merge_tools.rs
src/ui.rs

cli: rename FullCommandArgs to CommandNameAndArgs 

---

lib/src/git_backend.rs

improved error handling of root commit in git backend

---

CHANGELOG.md
docs/config.md
src/config-schema.json
src/diff_util.rs
tests/test_log_command.rs

Rename and document diff-format config

---

Cargo.lock
Cargo.toml

cargo: remove unused 'test-case' dev dependency

---

src/cleanup_guard.rs

style: move unix-specific imports into unix section

---

lib/src/revset.pest
lib/src/revset.rs
src/commands/mod.rs
src/template.pest
src/template_parser.rs

templater, revset: allow trailing comma

---

Cargo.lock

cargo: upgrade `openssl-src` to make `cargo deny` happy

---

examples/custom-backend/main.rs
lib/src/backend.rs
lib/src/commit_builder.rs
lib/src/git_backend.rs
lib/src/index.rs
lib/src/index_store.rs
lib/src/local_backend.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/settings.rs
lib/src/store.rs

Let backends decide root change id and change id length

---

src/cli_util.rs
src/ui.rs

cli: handle last-minute ui.write() error

---

CHANGELOG.md
src/commands/mod.rs

These don't seem used much, and maybe we (or a customized build) will want to use the name in the future.
If applicable:

cli: delete builtin `update/up` aliases

---

lib/src/index.rs

index: remove unused `iter()` function

---

src/cli_util.rs
src/ui.rs

cli: do not report "broken pipe" if pager exits successfully

---

CHANGELOG.md
docs/config.md
src/commands/mod.rs

(Just to get GitHub to actually link it, #1235)
If applicable:

Fix typos and slightly simplify code from #1235

---

src/commands/mod.rs
src/template.pest
src/template_parser.rs

templater: introduce AST structs to prepare for alias support

---

lib/src/revset.rs

revset: remove obsolete silencing of Clippy check

---

CHANGELOG.md
src/cli_util.rs
src/commands/mod.rs
src/config-schema.json
src/config/misc.toml
src/template.pest
src/template_parser.rs
tests/test_templater.rs

implement template aliases

---

CHANGELOG.md
lib/src/hex_util.rs
lib/src/lib.rs
lib/src/repo.rs
lib/src/revset.rs
lib/tests/test_revset.rs
src/cli_util.rs
src/template_parser.rs
src/templater.rs
tests/test_alias.rs
tests/test_commit_template.rs
tests/test_git_colocated.rs
tests/test_git_push.rs
tests/test_init_command.rs
tests/test_log_command.rs
tests/test_obslog_command.rs
tests/test_revset_output.rs
tests/test_split_command.rs

Switch to reverse-alphabet hex digits for change ids

---

docs/tutorial.md

We have made some changes to CLI output that had not made it into the tutorial. It's time to update it, especially with the new change id rendering. Since I'm updating now, and since it's a bit of work to do so, I decided to use GitHub's Hello-World repo instead of jj's own repo as our example.
If applicable:

tutorial: update with recent changes, plus some other editing

---

lib/src/git.rs
lib/src/index.rs
lib/src/index_store.rs
lib/src/refs.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/rewrite.rs
lib/src/view.rs
lib/tests/test_index.rs
lib/tests/test_mut_repo.rs
lib/tests/test_refs.rs
lib/tests/test_revset_graph_iterator.rs
src/cli_util.rs
src/commands/branch.rs
src/commands/git.rs
src/commands/mod.rs

Replace IndexRef by a trait

---

CHANGELOG.md
src/cli_util.rs
src/commands/mod.rs
src/config.rs
src/config/misc.toml
src/config/templates.toml
tests/test_workspaces.rs

config: extract default templates to src/config/templates.toml

---

src/config/templates.toml

cli: move default "show" template to alias

---

src/cli_util.rs
src/ui.rs

Follows up #1253
If applicable:

cli: remove attempt to detect EPIPE caused by bad pager configuration

---

CHANGELOG.md
Cargo.lock
Cargo.toml
lib/Cargo.toml
lib/testutils/Cargo.toml

It's been about 10 weeks and 730 commits since 0.6.0, compared to about 7 weeks and 350 commits between 0.5.0 and 0.6.0, so it's time for a new release. There's been significant user-visible changes and code-quality improvements. Thanks, everyone!
If applicable:

release: release version 0.7.0

---

lib/src/revset.rs
lib/src/revset_graph_iterator.rs

Revset lifetime cleanups

---

docs/config.md

As discussed on issue #1273, pipe usage on the jj config differs from
git and hg.
If applicable:

docs/config.md: add example for using pipes

---

CHANGELOG.md
lib/src/conflicts.rs
lib/tests/test_conflicts.rs
tests/test_obslog_command.rs
tests/test_resolve_command.rs

Include context lines in modify/delete conflicts (#1244)

---

lib/src/tree.rs

More minor cleanups of conflicts code

---

src/template_parser.rs

templater: add abstraction to split "commit" templater

---

CHANGELOG.md
lib/src/conflicts.rs
lib/tests/test_conflicts.rs
tests/test_resolve_command.rs

Fix a bug in roundtripping of conflict via markers

---

docs/config.md

Based on @martinvonz 's suggestion from https://github.com/martinvonz/jj/pull/1263.

`config.md`: Changes to section about TOML

---

docs/operation-log.md

This is based on a discussion in Discord where we realized this isn't documented.

`operation-log.md`: Give a brief description of `@`, `+`, `-`

---

src/commit_templater.rs

commit_templater: make commit/change_id typed again

---

lib/src/revset.rs
lib/src/revset_graph_iterator.rs
lib/src/rewrite.rs
lib/tests/test_revset.rs
lib/tests/test_revset_graph_iterator.rs
src/cli_util.rs
src/commands/mod.rs

Replace `RevsetIterator` by extension trait

---

CHANGELOG.md
docs/config.md
lib/src/settings.rs
src/cli_util.rs
src/commands/operation.rs
src/commit_templater.rs
src/config-schema.json
src/config/templates.toml
src/lib.rs
src/operation_templater.rs
src/template_parser.rs
src/templater.rs
tests/test_operations.rs

implement op-log template

---

src/commands/operation.rs
src/config/colors.toml
src/config/templates.toml

cli: rename op log color labels

---

docs/config.md
src/commit_templater.rs
src/config/templates.toml
src/template_parser.rs
tests/test_commit_template.rs
tests/test_templater.rs

Allow uppercasing change ids

---

src/cli_util.rs
src/commands/git.rs
src/commands/mod.rs

cli: code move to reduce parse_commit_summary_template() call site

---

lib/src/conflicts.rs
lib/tests/test_conflicts.rs

conflicts: fix off-by-one error in materialize_merge_result()

---

lib/src/index_store.rs
lib/src/repo.rs
lib/src/transaction.rs
lib/src/workspace.rs
lib/tests/test_bad_locking.rs
lib/tests/test_commit_concurrent.rs
lib/tests/test_index.rs
lib/tests/test_load_repo.rs
lib/testutils/src/lib.rs
src/cli_util.rs
src/commands/mod.rs
tests/common/mod.rs
tests/test_config_command.rs
tests/test_global_opts.rs

Improved error handling when loading storage backends (and a bit more)

---

CHANGELOG.md
src/cli_util.rs
src/commands/mod.rs
tests/test_concurrent_operations.rs
tests/test_workspaces.rs

cli: snapshot stale working copy before updating

---

lib/src/repo.rs
lib/src/simple_op_heads_store.rs
lib/src/workspace.rs

op_heads_store: let caller create initial operation

---

lib/src/revset.rs
lib/tests/test_revset.rs
src/commands/mod.rs

revset: remove filter_by_diff(), have caller intersect expression

---

docs/templates.md
src/commands/mod.rs
src/commands/operation.rs

docs: document template syntax, keywords and methods

---

lib/src/index_store.rs
lib/src/repo.rs
lib/src/store.rs

Minor index-related cleanups

---

docs/templates.md
src/commit_templater.rs
src/config/templates.toml
src/formatter.rs
src/operation_templater.rs
src/template_parser.rs
src/templater.rs
tests/test_show_command.rs
tests/test_templater.rs

templater: add indent(prefix, content) function

---

docs/revsets.md

Clarify that file() is relative

---

docs/templates.md
src/commit_templater.rs
src/template_parser.rs
src/templater.rs
tests/test_commit_template.rs

templater: add "parent_commit_ids" keyword

---

src/commit_templater.rs
src/operation_templater.rs
src/template_parser.rs

templater: minor property wrapping/chaining cleanup

---

README.md

The project has been my full-time project since around last summer, so it's incorrect to say that it's my 20% project.
If applicable:

readme: don't say that this is my 20% project

---

docs/templates.md
src/template.pest
src/template_parser.rs
src/templater.rs
tests/test_templater.rs

templater: refactor template value handling, add list.join(sep) method

---

SECURITY.md

I've set up a jj-security@googlegroups.com list. The template comes from Google's internal web.
I have no experience with GitHub's Security Advisory database, but it seems like a good practice, so let's use it.
If applicable:

docs: add a SECURITY.md

---

CHANGELOG.md
docs/config.md
src/cli_util.rs
src/commands/mod.rs
src/commands/operation.rs
src/config-schema.json
src/config/misc.toml
src/graphlog.rs
src/progress.rs
src/ui.rs
tests/test_log_command.rs
tests/test_obslog_command.rs
tests/test_operations.rs

cli: add ui.log-word-wrap option

---

lib/src/default_index_store.rs
lib/src/index.rs
src/commands/mod.rs

index: make `jj debug reindex` actually reindex

---

src/commit_templater.rs
src/lib.rs
src/operation_templater.rs
src/template_builder.rs
src/template_parser.rs
src/text_util.rs

templater: extract non-parsing parts to separate module

---

lib/src/default_index_store.rs
lib/src/index.rs
lib/tests/test_index.rs
lib/tests/test_mut_repo.rs
src/commands/mod.rs
tests/test_debug_command.rs

Remove stats() and num_commits() from Index trait

---

lib/src/revset.rs
lib/tests/test_revset.rs

Make revset::ToPredicateFn private

---

src/commands/operation.rs

cli: try to clarify the help texts for `jj op` commands a little

---

docs/tutorial.md

As suggested in #1386.
If applicable:

tutorial: clarify that files need to be saved before closing editors

---

CHANGELOG.md
README.md
flake.nix
src/commands/mod.rs
tests/test_debug_command.rs
tests/test_support_command.rs

Revisit hidden commands

---

docs/templates.md
src/commit_templater.rs
src/operation_templater.rs
src/template.pest
src/template_builder.rs
src/template_parser.rs
src/templater.rs
tests/test_commit_template.rs
tests/test_templater.rs

templater: add `list.map(|x| ...)` syntax

---

lib/src/default_index_store.rs
lib/src/default_revset_engine.rs
lib/src/index.rs
lib/src/revset.rs
lib/src/rewrite.rs
lib/tests/test_revset.rs
src/cli_util.rs
src/commands/mod.rs

Resolve revset symbols before asking index backend to evaluate it

---

CHANGELOG.md
lib/src/commit_builder.rs
lib/tests/test_commit_builder.rs
src/commands/mod.rs
tests/test_describe_command.rs

Add support for resetting author metadata (#328)

---

flake.nix

I've tested it and my guess was right, so pushing the oneline fix
Fixes #1408

nix: fix fish shell completions

---

lib/src/repo.rs
lib/src/revset.rs
lib/tests/test_default_revset_graph_iterator.rs
lib/tests/test_operations.rs
lib/tests/test_revset.rs
src/cli_util.rs
src/commands/branch.rs
src/commands/git.rs
src/commands/mod.rs
src/diff_util.rs

Preparations for moving `ChangeIdIndex` to the revset engine

---

src/commands/mod.rs

cli: call RevsetExpression::evaluate() directly if no symbol resolution needed

---

lib/src/default_revset_engine.rs
lib/src/rewrite.rs
lib/tests/test_default_revset_graph_iterator.rs
lib/tests/test_revset.rs
src/commands/mod.rs

Preparations for removing IndexEntry from Revset

---

docs/templates.md
src/commit_templater.rs
src/operation_templater.rs
src/template_builder.rs
tests/test_commit_template.rs

templater: add "parents" keyword in place of "parent_commit_ids"

---

lib/src/default_index_store.rs
lib/src/default_revset_engine.rs
lib/src/index.rs
lib/src/revset.rs
lib/tests/test_index.rs
src/cli_util.rs
src/commands/mod.rs

Remove some more uses of IndexEntry

---

README.md

readme: remove pointer to closed issue about native backend

---

Cargo.lock
Cargo.toml

cargo: remove unused dependency `predicates` crate

---

src/commands/git.rs

cli: add hint about testing with `ssh -F /dev/null` on SSH errors

---

CHANGELOG.md
docs/revsets.md
lib/src/default_index_store.rs
lib/src/default_revset_engine.rs
lib/src/revset.rs
lib/tests/test_revset.rs
tests/test_revset_output.rs

revset: add latest(candidates, count) predicate

---

.envrc

.envrc: Check for nix before trying to use flake

---

Cargo.lock
Cargo.toml
src/commands/bench.rs
src/commands/mod.rs
testing/bench-revsets-git.txt

Restore `jj bench` commands, and add new ones for revsets

---

docs/git-compatibility.md

docs: finally describe what we mean by "co-located repos"

---

src/commands/bench.rs

cli: run revset bench with fresh (but index-preloaded) repo instance

---

.github/workflows/build.yml

Add CI target with `--all-features`

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

github: add feature request issue template

---

lib/src/default_index_store.rs
lib/src/default_revset_engine.rs
lib/src/index.rs
lib/src/revset.rs
lib/src/rewrite.rs
lib/tests/test_default_revset_graph_iterator.rs
lib/tests/test_revset.rs

Remove repo knowledge from revset engine

---

src/commands/bench.rs

cli: add common bench options, accept multiple revsets

---

src/commands/bench.rs

cli: unify "bench revset"/"revsets" commands

---

lib/src/default_index_store.rs
lib/src/repo_path.rs

I couldn't immediatly figure out a better solution

Work around a couple of false positive for recent nightly clippy

---

lib/src/default_revset_engine.rs
lib/src/revset.rs
src/commands/mod.rs
tests/test_debug_command.rs

revset: remove unneeded lifetime bound, add "debug revset" command

---

lib/src/default_index_store.rs
lib/src/default_revset_engine.rs
lib/src/index.rs
lib/src/revset.rs
lib/tests/test_revset.rs
src/cli_util.rs

revset: remove noop `Present(_)` node handling from `evaluate()`

---

lib/src/default_revset_engine.rs
lib/src/revset.rs
lib/tests/test_revset.rs
testing/bench-revsets-git.txt

revset: better handling of filter union/negation

---

docs/github.md

Add docs on how to use GitHub CLI in repos that aren't co-located

---

build.rs

build: strip newline from "git rev-parse" output

---

src/formatter.rs

If applicable:
- (not planned) I have updated the config schema (src/config-schema.json)

formatter: error out on invalid color names

---

lib/src/default_index_store.rs
lib/src/default_revset_engine.rs
lib/src/index.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/rewrite.rs
lib/tests/test_default_revset_graph_iterator.rs
lib/tests/test_revset.rs
src/cli_util.rs
src/commands/mod.rs
tests/test_debug_command.rs

revset: add "resolved" expression type, resolve visible_heads earlier

---

Cargo.lock

cargo: upgrade off of yanked `crossbeam-channel` version

---

docs/github.md

docs: fix minor typos in GitHub example commands

---

src/commands/mod.rs

docs: remove erroneous home directory prefix from per-repo config path

---

lib/src/default_revset_engine.rs
lib/src/revset.rs

A chain of 4 billion commits is a lot, but it's not out of the question, so let's support it. The current default index will not be able to handle that many commits, so I let that still use 32-bit integers.
If applicable:

revset: bump generation numbers in API to 64 bits

---

docs/related-work.md

docs: mention Sapling as a similar tool

---

lib/src/settings.rs
src/commands/git.rs
src/config.rs
src/merge_tools.rs

settings: add helper to turn ConfigError::NotFound into Option

---

tests/common/mod.rs

tests: fix a typo

---

src/config/templates.toml
tests/test_commit_template.rs
tests/test_global_opts.rs

templates: rename "show" template alias to "builtin_log_detailed"

---

Cargo.lock
lib/src/diff.rs

cargo: upgrade regex 1.7.3 to 1.8.1

---

tests/test_git_import_export.rs

tests: add basic test for undoing git import/export in non-colocated repo

---

docs/revsets.md

docs: clarify that `file()` revsets match recursively

---

Cargo.lock
Cargo.toml
lib/Cargo.toml

cargo: downgrade `tracing` from yanked 0.1.38 to 0.1.37

---

src/cleanup_guard.rs

Fix warnings encountered on non-Unix platforms:
```
Compiling jujutsu v0.7.0 (C:\github.com\71\jj)
warning: unnecessary `unsafe` block
--> src\cleanup_guard.rs:17:29
|
17 |         if let Err(ref e) = unsafe { platform::init() } {    
|                             ^^^^^^ unnecessary `unsafe` block
|
= note: `#[warn(unused_unsafe)]` on by default
warning: function `on_signal` is never used
--> src\cleanup_guard.rs:47:4
|
47 | fn on_signal(guards: &mut GuardTable) {
|    ^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: `jujutsu` (lib) generated 2 warnings
```
If applicable:

Fix Windows-specific warnings in src/cleanup_guard.rs

---

src/cli_util.rs
src/commands/mod.rs
tests/test_move_command.rs
tests/test_squash_command.rs

Warn on `jj squash <revset>`

---

tests/common/mod.rs

More details in comments directly in the code.
If applicable:

Make tests run on windows-gnu

---

src/cli_util.rs
tests/test_abandon_command.rs
tests/test_checkout.rs
tests/test_describe_command.rs
tests/test_diffedit_command.rs
tests/test_duplicate_command.rs
tests/test_edit_command.rs
tests/test_git_clone.rs
tests/test_git_colocated.rs
tests/test_git_import_export.rs
tests/test_init_command.rs
tests/test_move_command.rs
tests/test_new_command.rs
tests/test_rebase_command.rs
tests/test_resolve_command.rs
tests/test_restore_command.rs
tests/test_split_command.rs
tests/test_squash_command.rs
tests/test_unsquash_command.rs
tests/test_workspaces.rs

cli: print parent commit summary on checkout

---

lib/src/git.rs
src/cli_util.rs
src/commands/git.rs
src/merge_tools.rs
tests/test_global_opts.rs

Changes to tracing levels

---

lib/src/tree.rs

When using a sparse working copy (e.g. with no files at all) and updating the working copy from the root commit to a commit with millions of files, we shouldn't have to walk the parts of the diff that doesn't match the sparse patterns. However, we still do the full walk because our `Tree::diff()` currently doesn't care about what the matcher tells us to visit, it only filters out unwanted files after visiting them. This commit fixes that for the special (but common) case of matching nothing in a directory.
I tried also adding special handling for when the matcher says that we should only visit a few entries, but it wasn't clearly better in the cases I tested it on. I'll keep that patch around and might send it if I find some cases where it helps.
If applicable:

tree: if matcher says that tree should be skipped, skip it

---

lib/src/git.rs
src/commands/git.rs

There were two issues on my end:
1. `known_hosts` doesn't seem to be recognized
2. SSH-Agent is ignored despite running
A workaround for 1. is to set the HOME environment variable on Windows, so I added a hint to suggest this. Ideally we would add a `certificate_check` callback to the remote callbacks, but the git2 crate doesn't expose whether the certificate check already succeeded, which makes it useless for this purpose (as we'd be prompting users to accept a certificate even though that certificate is already known to be valid).
As for 2., I changed the behavior from "check SSH Agent if some env variables exist" to "check SSH Agent and only fail if some env variables exist". On Windows SSH Agent doesn't use these env variables (but trying to communicate with it will still work), so …

Fix Git/SSH on Windows

---

lib/src/tree.rs

tree: rewrite recursive diff iterator to not use machine stack

---

docs/git-compatibility.md

docs: co-located mode is not new anymore, but it does have surprises

---

lib/src/revset.rs
lib/tests/test_revset.rs

revset: minor cleanup of symbol resolution code

---

docs/technical/architecture.md

docs: add architecture doc

---

lib/src/stacked_table.rs

stacked_table: do not remove head on empty save_table()

---

lib/src/lock.rs
lib/tests/test_commit_concurrent.rs
lib/tests/test_working_copy_concurrent.rs

cleanup: leverage scoped thread in tests

---

lib/src/git.rs

git: handle lock error that could occur while adding GC-preventing refs

---

tests/test_edit_command.rs
tests/test_git_colocated.rs
tests/test_log_command.rs
tests/test_operations.rs

Various test cleanups

---

src/cli_util.rs
src/commands/mod.rs
src/config.rs
tests/test_revset_output.rs
tests/test_templater.rs

cli: load revset/template aliases in order of config layers

---

lib/src/default_index_store.rs
lib/src/default_revset_engine.rs
lib/src/git.rs
lib/src/id_prefix.rs
lib/src/index.rs
lib/src/repo.rs
lib/src/revset.rs
lib/tests/test_index.rs
src/commands/branch.rs
src/commands/git.rs

revset: add `(CommitId, ChangeId)` iterator, remove `Index::walk_revs()`

---

docs/technical/conflicts.md
lib/src/conflicts.rs
lib/src/local_backend.rs
lib/src/op_store.rs
lib/src/refs.rs
lib/src/rewrite.rs
src/commands/branch.rs
src/commands/mod.rs

cleanup: consistently (?) put removed conflict terms before added ones

---

src/progress.rs

In the Linux repo, this speeds up `jj diff` in a clean working copy from 1.41 s to 881 ms.
If applicable:

progress: update progress only every 10 ms

---

lib/src/default_revset_graph_iterator.rs

I found this commit while cleaning up my repo
If applicable:

revset: minor fixes to documentation of graph iterator

---

lib/src/tree.rs

Respect matcher.visit() when walking entries

---

lib/src/conflicts.rs
lib/src/default_index_store.rs
lib/src/stacked_table.rs
src/merge_tools.rs

Minor cleanups of `Read` from buffers

---

src/cli_util.rs
tests/test_workspaces.rs

cli: add pointer from error message to docs about stale working copy

---

lib/src/conflicts.rs

conflicts: delete unused `conflict_to_materialized_value()`

---

lib/src/tree_builder.rs
lib/tests/test_working_copy.rs

tree_builder: fix directory-file transition + minor cleanup

---

lib/src/tree_builder.rs

tree_builder: clean up `get_base_trees()`

---

CHANGELOG.md

changelog: removing the `jj hide` alias is a breaking change

---

lib/src/dag_walk.rs
lib/src/default_index_store.rs
lib/src/op_heads_store.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/src/transaction.rs
lib/tests/test_commit_concurrent.rs
src/cli_util.rs
src/commands/mod.rs
src/commands/operation.rs

dag_walk: remove unneeded `&` and `Box` from callback arguments

---

CHANGELOG.md
lib/src/transaction.rs
src/cli_util.rs
src/commands/git.rs
tests/test_git_push.rs

Add support for `jj git push -r <revset>` and combining `-r`, `--change`, and `--branch`

---

lib/src/conflicts.rs
src/commands/mod.rs
src/merge_tools.rs
tests/test_resolve_command.rs

Minor cleanups enabled by recent switch to `conflicts::Conflict`

---

docs/technical/architecture.md

Fix invalid code link

---

lib/src/dag_walk.rs
lib/src/operation.rs
lib/src/repo.rs
src/commands/operation.rs

operation: make `op log` lazy

---

src/progress.rs
src/ui.rs

ui: ensure progress completion output is flushed

---

src/commands/mod.rs

docs(commands): adjust option help text for `jj rebase`

---

lib/src/conflicts.rs
lib/src/tree.rs
lib/src/working_copy.rs
lib/tests/test_conflicts.rs
src/merge_tools.rs

More minor conflict cleanups

---

src/progress.rs

progress: use common duration constants

---

lib/src/conflicts.rs
lib/src/store.rs

conflicts: extract methods for converting to/from generic legacy form

---

README.md

README: delete the section about rust version

---

docs/revsets.md

docs: note how our `heads()` and `roots()` revsets differ from hg's

---

lib/src/repo_path.rs
lib/src/tree.rs

micro optimization and cleanup around RepoPath::join()

---

lib/src/default_index_store.rs
lib/src/default_revset_engine.rs
lib/tests/test_index.rs

index: turn CompositeIndex::walk_revs() into position-based API

---

lib/src/conflicts.rs
lib/src/working_copy.rs
lib/tests/test_conflicts.rs
src/commands/mod.rs
src/diff_util.rs
src/merge_tools.rs

conflicts: move `describe_conflict()` etc.  onto `Conflict`

---

lib/src/conflicts.rs
lib/src/files.rs
lib/src/merge.rs

resolve trivial merge of `A+A-B+C-C` to `A`

---

docs/config.md
docs/tutorial.md

docs: describe how to configure `scm-diff-editor`

---

lib/src/conflicts.rs

Preserve diffs when simplifying conflicts

---

lib/src/git.rs

git: on import_refs(), avoid loading git commit object if it's known

---

CHANGELOG.md
src/commands/mod.rs
tests/test_config_command.rs

See commit message. cc @thoughtpolice
If applicable:

feat(config): add `jj config get` for scripting

---

CHANGELOG.md
src/commands/mod.rs
tests/test_chmod_command.rs

cli: new `jj chmod` command to set the executable bit

---

lib/src/default_revset_engine.rs
lib/src/id_prefix.rs

id_prefix: only store first few bytes of keys in IdIndex

---

CHANGELOG.md

changelog: mention fixes for #924 and #1608 (racy change id / snapshot)

---

lib/src/conflicts.rs
lib/src/merge.rs
lib/src/tree.rs
src/merge_tools.rs

Minor conflict cleanups

---

lib/src/conflicts.rs
lib/src/files.rs
lib/src/tree.rs
lib/tests/test_conflicts.rs
src/merge_tools.rs

Add `ContentHunk` newtype & replace `ConflictHunk` by `Conflict<ContentHunk>`

---

lib/src/conflicts.rs
lib/src/files.rs
lib/tests/test_conflicts.rs

files: replace uses of `MergeHunk` by `Conflict<ContentHunk>`

---

src/commands/git.rs

cli: trivial cmd_git_push() cleanup

---

lib/src/revset.rs
src/commands/mod.rs
tests/test_log_command.rs

cli: make log accept multiple -rREVISION expressions

---

lib/src/git_backend.rs

Update init_external to not unwrap() but return an error

---

lib/src/default_revset_engine.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/src/store.rs
lib/src/tree.rs
lib/src/tree_builder.rs
lib/tests/test_merge_trees.rs
lib/tests/test_revset.rs
src/commands/mod.rs
src/commit_templater.rs
src/diff_util.rs

Cache tree objects on write

---

lib/src/backend.rs
lib/src/conflicts.rs
lib/src/tree.rs

More conflict cleanups

---

src/commands/branch.rs
tests/test_branch_command.rs

`branch` CLI: allow `branch delete` to take globs and other minor improvements

---

lib/src/tree.rs

tree: remove useless pinning of Tree object

---

lib/src/git.rs
lib/tests/test_git.rs

git: pass RefName enum to git_ref_filter callback

---

tests/common/mod.rs
tests/test_branch_command.rs
tests/test_config_command.rs
tests/test_git_colocated.rs
tests/test_git_import_export.rs
tests/test_global_opts.rs
tests/test_init_command.rs
tests/test_log_command.rs
tests/test_revset_output.rs
tests/test_split_command.rs
tests/test_squash_command.rs
tests/test_templater.rs

tests: add helper method to capture both stdout/stderr outputs

---

Cargo.lock

Ran `cargo update -p hermit-abi`.
See https://github.com/martinvonz/jj/actions/runs/5458721445/jobs/9934077589?pr=1790
If applicable:

Fix `cargo deny` error

---

lib/src/backend.rs
lib/src/rewrite.rs

rewrite: delete TODOs about labels for each term in a conflict

---

Cargo.toml

cargo: remove `regex` dev-dep duplicated from regular deps

---

examples/custom-backend/main.rs
lib/src/file_util.rs
lib/src/git_backend.rs
lib/src/repo.rs
lib/src/workspace.rs
src/cli_util.rs
tests/test_global_opts.rs

git_backend: propagate load/init errors

---

src/cli_util.rs

I'm not the only author, and it doesn't seem very useful to display that information anyway (if it even appear anywhere).
If applicable:

cli: remove author field from clap command

---

src/cli_util.rs

Avoid cloning arguments when resolving default command and aliases

---

examples/custom-backend/main.rs
lib/src/backend.rs
lib/src/git_backend.rs
lib/src/local_backend.rs
lib/src/repo.rs
lib/src/workspace.rs
lib/testutils/src/lib.rs
tests/test_global_opts.rs
tests/test_init_command.rs

backend: refactor error type, deal with empty .jj repo

---

lib/src/working_copy.rs

working_copy: remove matching that's always against `_`

---

lib/src/tree.rs
src/diff_util.rs

Minor cleanup of `tree::Diff`

---

lib/src/tree.rs

Minor cleanups of `tree.rs`

---

lib/src/conflicts.rs

conflicts: move repeated definition of `c()` in tests to module level

---

src/commit_templater.rs

commit_templater: avoid looking up tree only to get its id

---

lib/src/op_store.rs
src/commit_templater.rs

templater: inline RefTarget::has_add()

---

src/commands/git.rs
tests/test_git_push.rs

cli: refactor handling of push branch targets, warn conflicted branches

---

.watchmanconfig
CHANGELOG.md
Cargo.lock
Cargo.toml
docs/config.md
lib/Cargo.toml
lib/src/fsmonitor.rs
lib/src/lib.rs
lib/src/protos/working_copy.proto
lib/src/protos/working_copy.rs
lib/src/repo_path.rs
lib/src/revset.rs
lib/src/settings.rs
lib/src/working_copy.rs
lib/tests/test_working_copy.rs
lib/tests/test_working_copy_concurrent.rs
lib/tests/test_working_copy_sparse.rs
lib/testutils/src/lib.rs
src/cli_util.rs
src/commands/debug.rs
src/commands/mod.rs
src/merge_tools.rs

feat(fsmonitor): Watchman filesystem monitor implementation

---

lib/src/git.rs
src/commands/git.rs

git: move remove/rename remote logic to library

---

CHANGELOG.md
lib/src/git.rs
lib/tests/test_git.rs

git: consistently ignore unrelated refs on fetch()

---

CHANGELOG.md
lib/src/git.rs
src/commands/branch.rs
src/commit_templater.rs
tests/test_branch_command.rs

templater: include pseudo `@git` targets in branches keyword

---

lib/src/conflicts.rs
lib/src/refs.rs

conflicts, refs: minor code cleanup

---

lib/src/revset.rs
lib/tests/test_revset.rs
tests/test_branch_command.rs

revset: include pseudo `@git` remote in suggestion

---

lib/src/lib.rs
lib/src/protos/mod.rs

Broken in https://github.com/martinvonz/jj/pull/1832. @martinvonz has fixed the repo settings so that this job blocks merging.
If applicable:

fix(docs): fix protobuf job build

---

Cargo.toml

Summary: On x86_64-linux, these options reduce the total number of bytes in the `jj` binary by 40 percent, from 16MiB to 9.8MiB, while having relatively minimal impact on build time, going from 58s to 1m15s.
While `strip=debuginfo` is already the default, `codegen-units=1` is doing all the work here, and seems to have a rather miraculous effect despite not meaningfully hurting compile time too much for me at least. This actually will probably improve performance in some cases too, but it's likely hard to quantify.
Ultimately, with or without this change, the dominant entity taking up most of the compile time for the whole project is `jj-lib` and `jj-cli` crates. A `--timings` report with Cargo indicates almost all dependencies (on my machine) compile within 30s whether or not this change …

feat(cargo): improve --release binary size

---

docs/git-comparison.md

See https://github.com/martinvonz/jj/pull/1847#discussion_r1259132401 for more context.

git-comparison: update git's "remove file" command

---

docs/revsets.md
lib/src/git.rs
lib/src/revset.rs
lib/tests/test_git.rs
lib/tests/test_revset.rs

git: do not export branch named `HEAD`, resolve `HEAD@git` branch

---

lib/src/repo.rs
lib/tests/test_mut_repo.rs

repo: do not discard old working-copy commit if it's pointed by local branch

---

.github/workflows/release.yml
Cargo.toml
flake.nix

github: enable the watchman feature in pre-built binaries

---

lib/src/working_copy.rs
lib/src/workspace.rs
lib/tests/test_working_copy.rs
lib/tests/test_working_copy_sparse.rs
src/cli_util.rs
src/commands/debug.rs
src/commands/mod.rs
src/merge_tools.rs

working_copy: create and propagate `TreeStateError`

---

lib/src/working_copy.rs
lib/tests/test_working_copy.rs
lib/tests/test_working_copy_concurrent.rs
lib/tests/test_working_copy_sparse.rs
src/cli_util.rs
src/commands/debug.rs
src/commands/mod.rs

working_copy: return `Result` from `WorkingCopy::tree_state`/`WorkingCopy::tree_state_mut`

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
lib/Cargo.toml
lib/testutils/Cargo.toml

release: release version 0.8.0

---

lib/tests/test_view.rs

See https://github.com/martinvonz/jj/actions/runs/5569735693/jobs/10173301074
If applicable:

tests: attempt to fix a flaky test

---

lib/src/git.rs
lib/src/op_store.rs
lib/src/refs.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/rewrite.rs
lib/src/simple_op_store.rs
lib/src/view.rs
lib/tests/test_git.rs
lib/tests/test_mut_repo.rs
lib/tests/test_refs.rs
lib/tests/test_revset.rs
lib/tests/test_rewrite.rs
src/commands/branch.rs
src/commands/git.rs
src/commands/mod.rs
src/commands/operation.rs
src/commit_templater.rs

refs: replace most of `Option<RefTarget>` data layout dependency

---

CHANGELOG.md

@mlcui made their first contribution after I drafted the release notes for 0.8.0 and I forgot to update the release notes before merging the PR.
If applicable:

changelog: add @mlcui-google as contributor to 0.8.0

---

docs/contributing.md

Summary: This was some fallout from merging #1851; I missed a few changes I needed to back out for an upcoming diff.
If applicable:

docs: fix contributing.md

---

lib/src/conflicts.rs
lib/src/dag_walk.rs
lib/src/git.rs
lib/src/tree.rs
src/cli_util.rs

cleanup: use let-else now that we're on Rust 1.65+

---

lib/src/git.rs
lib/src/repo.rs
lib/src/revset.rs
lib/src/view.rs
lib/tests/test_git.rs
src/commands/git.rs

view: return RefTarget by reference, clone() by caller

---

lib/src/backend.rs
lib/src/commit.rs
lib/src/commit_builder.rs
lib/src/conflicts.rs
lib/src/default_revset_engine.rs
lib/src/git_backend.rs
lib/src/lib.rs
lib/src/local_backend.rs
lib/src/merged_tree.rs
lib/src/protos/git_store.proto
lib/src/protos/git_store.rs
lib/src/protos/local_store.proto
lib/src/protos/local_store.rs
lib/src/tree.rs
lib/tests/test_merged_tree.rs
lib/testutils/src/lib.rs
src/commands/git.rs
src/commands/mod.rs
src/commit_templater.rs

Initial support for tree-level conflict (reading, merging, listing conflicts)

---

lib/src/tree_builder.rs

tree_builder: leverage `BTreeMap::pop_last()` now that we're on Rust 1.66+

---

lib/src/working_copy.rs

working_copy: remove an unneccessary `Box`

---

lib/src/working_copy.rs

working_copy: remove unused SnapshotError::FileOpenError variant

---

lib/src/git.rs
lib/src/op_store.rs
lib/src/refs.rs
lib/src/simple_op_store.rs
lib/tests/test_rewrite.rs
src/commands/mod.rs
src/commit_templater.rs

refs: minor `Conflict` method cleanup

---

lib/src/default_revset_engine.rs
lib/src/default_revset_graph_iterator.rs
lib/src/revset.rs

graphlog: use IndexPosition until transitive edges get eliminated

---

CHANGELOG.md
Cargo.lock
lib/Cargo.toml
lib/src/default_revset_engine.rs
lib/src/default_revset_graph_iterator.rs
lib/src/lib.rs
lib/src/revset.rs
lib/src/revset_graph.rs
lib/tests/test_default_revset_graph_iterator.rs
lib/tests/test_revset.rs
src/commands/mod.rs
tests/test_abandon_command.rs
tests/test_chmod_command.rs
tests/test_duplicate_command.rs
tests/test_git_colocated.rs
tests/test_new_command.rs
tests/test_rebase_command.rs
tests/test_resolve_command.rs
tests/test_restore_command.rs
tests/test_squash_command.rs
tests/test_templater.rs
tests/test_unsquash_command.rs

graphlog: group commits topologically, place new heads close to fork point

---

lib/src/working_copy.rs

Small steps towards decoupling file states from tree builder in working copy

---

docs/config.md

docs: fix a missed `jujutsu`->`jj-cli` in config docs

---

lib/src/default_index_store.rs
lib/src/op_heads_store.rs
lib/src/operation.rs
lib/src/repo.rs
lib/src/transaction.rs
lib/tests/test_load_repo.rs
src/cli_util.rs
src/commands/debug.rs
src/commands/operation.rs

I didn't actually check to see if it produces a useful error message now since I don't know how to reproduce the one in #1907.
If applicable:

operation: propagate `OpStoreError`

---

lib/src/revset_graph.rs

revset_graph: ignore duplicated entries in emittable stack

---

lib/src/backend.rs
lib/src/op_store.rs
lib/src/simple_op_heads_store.rs
lib/src/simple_op_store.rs
lib/tests/test_operations.rs
lib/tests/test_working_copy.rs
lib/tests/test_working_copy_concurrent.rs
src/commands/operation.rs
src/operation_templater.rs

More error reporting from the operation store

---

lib/tests/test_working_copy.rs

This also lets us compare the resulting tree because the working copy now exactly matches the tree (it used to be that the `.gitignore` file wasn't initially snapshotted).
If applicable:

working_copy: leverage `create_tree()` in test

---

CHANGELOG.md
lib/gen-protos/src/main.rs
lib/src/op_store.rs
lib/src/protos/op_store.proto
lib/src/protos/op_store.rs
lib/src/refs.rs
lib/src/simple_op_store.rs
lib/tests/test_git.rs
lib/tests/test_view.rs
tests/test_concurrent_operations.rs
tests/test_debug_command.rs
tests/test_operations.rs
tests/test_workspaces.rs

simple_op_store: serialize RefTarget in new format (breaks downgrades)

---

lib/src/fsmonitor.rs
lib/src/lock/fallback.rs
lib/src/lock/unix.rs
lib/src/matchers.rs
lib/src/repo.rs
lib/src/rewrite.rs
lib/src/tree.rs
lib/src/working_copy.rs
lib/src/workspace.rs
src/cleanup_guard.rs
src/cli_util.rs
src/commands/mod.rs
src/config.rs
src/diff_util.rs
src/ui.rs

Instrument `jj status`

---

lib/tests/test_working_copy.rs
lib/tests/test_working_copy_concurrent.rs
lib/tests/test_working_copy_sparse.rs
lib/testutils/src/lib.rs

Cleanup of working copy tests

---

lib/src/working_copy.rs

Remove some dependencies on `FileState`s

---

lib/src/working_copy.rs

working_copy: use tree rather than file states to detect if directory is tracked

---

lib/src/working_copy.rs

It's faster to add only files matched by the Watchman matcher to the set of deleted files than to add all files and then removed files not matched. This speeds up `jj diff` with Watchman in the Linux repo from ~530 ms to ~460 ms.
If applicable:

watchman: don't even add non-watchman files to set of deleted files

---

lib/src/default_revset_graph_iterator.rs
lib/tests/test_default_revset_graph_iterator.rs
tests/test_abandon_command.rs
tests/test_chmod_command.rs
tests/test_duplicate_command.rs
tests/test_log_command.rs
tests/test_new_command.rs
tests/test_rebase_command.rs
tests/test_resolve_command.rs
tests/test_restore_command.rs
tests/test_squash_command.rs
tests/test_unsquash_command.rs

revset_graph: preserve original parents order

---

lib/src/commit.rs
lib/src/operation.rs
src/cli_util.rs
src/commands/git.rs
src/commands/mod.rs
src/merge_tools.rs

Fix `cargo +nightly clippy` warnings

---

lib/src/working_copy.rs

Don't rely on executable bit from working copy state on Windows

---

lib/src/working_copy.rs

Reduce dependency on `FileState` some more

---

docs/git-comparison.md

docs: mention `jj split` for `git commit -p` use case

---

lib/src/working_copy.rs
lib/tests/test_working_copy.rs

Ignore .gitignores in ignored paths (#1785)

---

README.md

Someone on HN (justifiably) seemed to think that we only accept questions on Discord.
If applicable:

docs: clarify that GitHub discussions are fine (not only Discord)

---

README.md

clarify documentation about working-copy commit

---

docs/config.md

docs: describe `push.branch-prefix`

---

src/ui.rs

ui: use std::io::IsTerminal instead of crossterm equivalent

---

lib/src/working_copy.rs

working_copy: extract `WorkItem` to top-level `struct`
