- .github/workflows/build.yml
- lib/src/index.rs
- lib/src/nightly_shims.rs
Running `cargo clippy` on main exposes some lint warnings. This stack fixes those warnings and updates the CI job.
If we think that running Clippy twice is too much overhead, we could remove one of them.
> Fix unstable name collision lint warnings

- README.md
Since #85, we load the user's config from a path under
`dirs::config_dir()`. It's probably not obvious to all users where to
put the file, so let's describe that. (I didn't know where to put the
file on my Mac until I looked at the function's documentation.)
> docs: mention user-specific config path on different platforms

- README.md
We don't need the nightly toolchain anymore since #70 (thanks,
@arxanas!).
> docs: use stable Rust toolchain for installation

- Cargo.lock
- Cargo.toml
- src/commands.rs
This avoids some deprecation warnings from `cargo install` (which
picks the latest version instead of the locked version by default).
> cargo: upgrade clap to 3.1.0

- Cargo.lock
- Cargo.toml
- flake.nix
- src/commands.rs
Sorry, I didn't open an issue for this one. It started with a quick Nix fix and evolved. Let me know if you'd prefer it split, etc.
This:
1. adds `clap_mangen` to cargo
2. adds `jj debug mangen` subcommand
3. uses the debug subcommands in the nix expression to enrich the package outputs
`clap_mangen` suggest possibly using in a build task, but I prefer, and wanted to match, the internal debug command pattern already used for completions.
To be honest, I don't know what is normally done to install manpages, hence the lack of README change. Mine just works via nixos/home-manager.
demo: https://asciinema.org/a/zyx09Y2SWz6FuEihbUupl5TP1
- first the nix config for a to-be-upstreamed [home-manager](https://github.com/nix-community/home-manager) module
- `man jj` showing the manpage
- `jj <tab>` …
> debug: add mangen + nix: add completion/manpages to output

- .github/workflows/build.yml
- tests/smoke_test.rs
- tests/test_global_opts.rs
I've forgotten to run `rustfmt` many times (most recently in
572143655866), so let's have CI check for it.
> github: make CI check formatting

- docs/conflicts.md
- docs/technical/conflicts.md
We used to have documention about how conflicts are implemented, but I
removed that a long time ago when I rewrote the README to target users
rather than VCS hackers. Let's have a doc for the VCS hackers (and
curious users) as well, though.
> docs: add technical doc about a conflict design

- docs/git-comparison.md
- docs/git-compatibility.md
> docs: list supported and unsupported Git features

- src/commands.rs
- tests/test_git_push.rs
Open commits are work-in-progress and `jj git push --branch <name>`
therefore errors out if the branch points to an open commit. However,
we don't do the same check if you run `jj git push` to push all
branches. This patch introduces such a check. Rather than error out,
we skip such branches instead.
I didn't make it check for open commits in ancestors. It's quite
unusual (at least in my workflow) to have a closed commit on top of an
open one. We can revisit if users get surprised by it.
> cli: when pushing all branches (the default), skip open commit

- .github/ISSUE_TEMPLATE.md
Now that we have a changelog and I plan to do releases once in a
while, it makes sense again to have the version number in the issue
template.
> github: include version number in issue template again

- CHANGELOG.md
- src/commands.rs
- src/testutils.rs
- tests/test_gitignores.rs
I thought that `std::fs::canonicalize()` expanded "~", but it doesn't
seem to do that, which caused #131. Git seems to do the expansion
itself, so we probably also should. More importantly
`std::fs::canonicalize()` crashes when the file doesn't exist. The
manual expansion we do now does not.
Closes #131.
> cli: expand `~` in `core.excludesFile`, don't crash when missing

- Cargo.lock
- Cargo.toml
- flake.nix
- lib/Cargo.toml
I was able to build a working musl binary with this change, by running
this command:
```
cargo build --release --target x86_64-unknown-linux-musl
```
Thanks to @arxanas for the tip.
> cargo: use libgit2 with vendored OpenSSL (#73)

- Cargo.lock
- Cargo.toml
- lib/Cargo.toml
This release is just to get #131 out and to see if the automated
release builds work now that we use a vendored OpenSSL from libgit2.
> release: bump version to 0.3.1

- .github/workflows/release.yml
My attempt at using rust-build/rust-build.action for release builds
(from bf21e65c5df8) initially seemed promising. However, the produced
musl binary build segfaulted on my Debian machine. I don't know about
the Mac and Windows binaries. I then tried switching to building with
a vendored OpenSSL (cac93e279393), but then the build started failing
(https://github.com/martinvonz/jj/actions/runs/1978730621). I couldn't
figure out why it failed, so I decided to do the build in a more
manual way (without rust-build/rust-build.action), based on
https://github.com/gitext-rs/git-stack/blob/main/.github/workflows/post-release.yml
(thanks to @epage for the example and to @arxanas for the link). I
could simplify it a bit because I'm currently doing the releases via
the GitHub UI (epage's original …
> github: new attempt at setting up automated release builds (#73)

- Cargo.lock
- Cargo.toml
- lib/Cargo.toml
I forgot to bump the version to 0.3.2 before tagging and releasing it,
so the released 0.3.2 has version number 0.3.1 in the source code and
(therefore) reported from `jj --version`. I'm therefore bumping it
from 0.3.1 to 0.3.3 now, so there can be a matching 0.3.3 release.
> release: bump version to 0.3.3 (skipping 0.3.2)

- .github/workflows/build.yml
- .github/workflows/nix-linux.yml
- .github/workflows/release.yml
The new code scanner is complaining that actions have permissions to
do too much. It wasn't obvious to me what permissions the jobs need,
but let's see how this works.
> github: set top-level permissions to readonly for all workflows

- .github/workflows/build.yml
I've found it hard to figure out which actions need which
permissions. GitHub doesn't seem to even document what the permissions
mean. So let's just give Clippy full access.
> github: give Clippy action full permissions

- README.md
Users now have the option of installing from source or directly
installing a binary.
I also corrected some text that effectively said that installing a Nix
flake is not installing from source, but I think it actually does
install from source.
> docs: add pointer to pre-built binary releases (#73)

- .github/workflows/build.yml
Maybe "issues" is the permissions it needs to be able to comment on
pull-requests?
> github: restrict Clippy's access again

- src/commands.rs
I had accidentally given the two positional arguments for `jj git
remote add` the same index. While fixing that, I realized that maybe
`clap` can infer the index based on the declaration order in the
struct. That does indeed seem to work, so I just removed all the
explicit `index` arguments instead.
> cli: don't explicitly indicate positional argument's index

- src/commands.rs
- tests/test_global_opts.rs
I've found it hard to read the `jj help` output because command
options are mixed with global options. This patch fixes that by
putting global options under a separate heading.
> cli: in help output, list global options under separate heading

- src/commands.rs
- src/ui.rs
to make it clear that the formatter is the output after #182.
`parse_file_path()` could also be moved, but not by this series. There may be
a better way to reorganize it and matcher builder.
> cli: move format_file_path(), remove ui argument from diff functions

- .github/workflows/release.yml
This directory doesn't seem to do anything.
I mostly copied and pasted this `release.yml` into git-branchless and it worked nicely on the first try :)
> github: remove `complete` directory for releases

- src/commands.rs
I think I lost the formatting in the upgrade to clap 3.0.
> cli: fix formatting of `jj help rebase`

- CHANGELOG.md
- lib/src/tree.rs
- lib/tests/test_merge_trees.rs
When a directory is missing in one merge input (base or one side), we
would consider that a merge conflict. This patch changes that so we
instead merge trees by treating the missing tree as empty.
> trees: when merging trees and one is missing, treat it as empty

- CHANGELOG.md
- src/ui.rs
- tests/test_init_command.rs
> cli: use `.` in output for current directory instead of empty string

- lib/src/commit.rs
- lib/src/repo.rs
- lib/tests/test_init.rs
- lib/tests/test_mut_repo.rs
- lib/tests/test_working_copy.rs
- src/commands.rs
> cleanup: replace `.tree().id()` by `tree_id()` to avoid looking up trees

- lib/src/op_heads_store.rs
- lib/src/repo.rs
We only need to be able to read operations, so it's better to pass in
just an `OpStore`.
> op_heads_store: don't pass whole `RepoLoader` into `get_heads()`

- lib/src/git.rs
The path to the file that indicates the last export to git was changed
when we added support for multiple workspaces.
> git: fix an obsolete comment about a `.jj/` path

- .gitattributes
Copy of https://github.com/arxanas/git-branchless/pull/375.
Maybe we should mark `flake.lock` as `merge=binary` too?
> build: mark `Cargo.lock` as `binary` for merging

- CHANGELOG.md
- lib/src/git.rs
- lib/src/rewrite.rs
- lib/tests/test_git.rs
- lib/tests/test_rewrite.rs
> git: when importing refs, abandon commits that were abandoned in git

- lib/src/git.rs
> git: avoid creating a `HashSet` only to convert to a `Vec`

- lib/src/git_backend.rs
It seems to me that we have never created a Git index in order to
create a commit, not even in the earliest versions of the code (before
it was moved to Git).
> git_backend: delete obsolete (?) comment about not avoiding use of index

- src/commands.rs
This adds `jj debug operation <operation ID>`, which will print the
operation object and its associated view object.
> cli: add a debug command for showing information about an operation

- CHANGELOG.md
- src/commands.rs
- tests/test_git_remotes.rs
As requested by @talpr. I added this is a separate new command `jj git
remote list`. One could also imagine showing the listing when there is
no sub-command specified to `jj git remote`, but we don't have other
commands that behave that way yet.
Closes #243
> cli: add a command for listing git remotes and their URLs

- lib/src/working_copy.rs
- lib/tests/test_working_copy.rs
- lib/tests/test_working_copy_concurrent.rs
- lib/tests/test_working_copy_sparse.rs
- src/commands.rs
- src/diff_edit.rs
I think I copied the name `write_tree()` from Git, but I find it quite
confusing, since it's not clear if it write a tree to the working copy
or reads the working copy and writes a tree to the store (it's the
former).
> working_copy: rename `write_tree()` to `snapshot`()

- lib/src/working_copy.rs
- lib/tests/test_working_copy.rs
- lib/tests/test_working_copy_concurrent.rs
- lib/tests/test_working_copy_sparse.rs
- src/commands.rs
- src/diff_edit.rs
> working_copy: propagate errors when snapshotting

- src/commands.rs
- tests/test_git_colocated.rs
> Fix crash on automatic import from git

- src/commands.rs
The two PRs were incompatible, but it seems they were allowed to
"merge" (rebase) because the merge was conflict free?
> cli: fix incompatibility between #271 and #273

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/diff_edit.rs
Apparently, I need to pass `--merge` option to use kdiff3 as a diff editor.
We could add `diff-editor-args` or extend `diff-editor` to a list of command
arguments, but we'll eventually add stock merge tools and the configuration
would look like:
[merge-tools.<name>]
program = ...
diff-args = [...]
edit-args = [...]
merge-args = [...]
> diff_edit: load command arguments from merge-tools.<name> config

- src/diff_edit.rs
- testing/fake-diff-editor.rs
No idea why these aren't picked up by CI already.
> cleanup: fix some `cargo clippy` warnings

- lib/src/tree.rs
- src/commands.rs
Tree merges can currently fail because of a failure to look up an
object, or because of a failure to read its contents. Both results in
`BackendError` because of a `impl From<std::io::Error> for
BackendError`. That's kind of correct in this case, but it wasn't
intentional (that impl was from `local_backend`), and we need to
making errors more specific for better error handling.
> errors: use custom error for failed tree merge

- .github/workflows/build.yml
- .github/workflows/nix-linux.yml
The conditions for triggering Nix builds and other builds were
slightly different.
Nix builds triggered by PRs happened on PRs for any branch, not just
the `main` branch. That makes very little difference in practice
because PRs for other branches are very rare. Still, let's be
consistent. I decided to trigger the builds on PRs for any branch.
More importantly, Nix builds triggered by push were only done for
pushes to `master`, which is not what our main branch is called, so
those never happened.
> github: trigger all builds on main branch, and PR for any branch

- CHANGELOG.md
- src/commands.rs
- tests/test_alias.rs
Our support for aliases is very naively implemented; it assumes the
alias is the first argument in argv. It therefore fails to resolve
aliases after global arguments such as `--at-op`.
This patch fixes that by using doing an intial parse of the arguments
with a modified definition of the CLI passed to `clap`. The modified
definition has only global arguments, plus an "external
subcommand". That way we can convince `clap` to parse the global
arguments for us and give us the alias (or real command) and further
arguments back. Thanks to @epage for the suggestion on in
clap-rs/clap#3672. The only minor problem is that it doesn't seem
possible to tell `clap` to parse global arguments that come after the
external subcommand. To work around that, we manually merge any parsed
global argument …
> cli: allow alias after global args

- src/commands.rs
- tests/test_log_command.rs
`log -s/--summary` and `log --git` without `-p` don't do anything. I
also don't think it's very useful to pass these flags in an alias,
where you would then sometimes also pass `-p` to see the diff summary
in the output. We already have the `diff.format` config for that use
case. So let's make both of these flags imply `-p`.
I implemented it by making the `diff_format` variable an
`Option<DiffFormat>`, which is set iff we should show a patch. That
way we have the condition in one place, and the places we use it
cannot forget to check it.
> cli: make `log -s/--git` imply `-p`

- CHANGELOG.md
- README.md
- demos/demo_git_compat.sh
- demos/demo_resolve_conflict.sh
- docs/tutorial.md
- src/commands.rs
The default log output of showing all commits is not very useful when
contributing to an existing repo. Let's have it default to showing
commits not on any remote branch instead. I think that's the best we
can do since we don't have a configurable main branch yet, and we
don't even have per-repo configuration..
Closes #250.
> cli: make `log` show only local commits by default

- CHANGELOG.md
- lib/src/revset.rs
- lib/src/revset_graph_iterator.rs
- lib/tests/test_revset_graph_iterator.rs
- src/commands.rs
- tests/test_log_command.rs
> Teach `jj log` option to show older revisions first

- src/commands.rs
- tests/test_global_opts.rs
This should help make e.g. `squash` discoverable for users who search
the help output for "amend". It should also help users discover the
builtin abbreviations like `st` (for `status`).
> cli: make aliases (for commands and arguments) visible in help

- README.md
- docs/tutorial.md
- src/templater.rs
- tests/smoke_test.rs
- tests/test_alias.rs
- tests/test_concurrent_operations.rs
- tests/test_edit_command.rs
- tests/test_git_colocated.rs
- tests/test_init_command.rs
- tests/test_log_command.rs
- tests/test_move_command.rs
- tests/test_new.rs
- tests/test_rebase_command.rs
- tests/test_restore_command.rs
- tests/test_split_command.rs
- tests/test_squash_command.rs
- tests/test_undo.rs
- tests/test_workspaces.rs
It can be confusing that some commits (typically the working copy)
don't have a description. Let's show a placeholder text in such cases.
> cli: show placeholder text for empty commit message

- src/commands.rs
Mercurial has these aliases, so it will be familiar for Mercurial
users. My only hesitation about adding these aliases is that we might
want the these names for something else in the future. You could
imagine `up` and `down` commands, for example. We still have a long
time before 1.0, so we have plenty of opportunity to make breaking
changes if we think of some other use for the names :)
> cli: add `update` and `up` as aliases for `checkout`

- Cargo.toml
- lib/Cargo.toml
We don't need the `config` crate's support for JSON etc., so let's
just enable the TOML feature. (Trying to import all the JSON, RON,
dependencies etc. into Google's source control was a pain.)
> cargo: use only "toml" feature from `config` crate

- src/commands.rs
It doesn't make much sense to default to restoring to the current
operation.
> cli: make `op restore` require an operation ID

- CHANGELOG.md
- lib/src/repo.rs
- lib/tests/test_mut_repo.rs
- src/commands.rs
- tests/test_new.rs
Some small steps related to #321 (see commit descriptions for details, as usual)
> Improvements to `jj new` (and others)

- lib/src/transaction.rs
- lib/src/working_copy.rs
These assertions were there to catch bugs, but when the bugs happen,
the assertions can obsure the underlying error (as @tp-woven found out
on #258). Let's just print errors instead.
> drop: downgrade two assertions to error messages

- CHANGELOG.md
- lib/src/settings.rs
- src/commands.rs
Fixes #340. ~I haven't updated the changelog yet, this is just an initial implementation to get your thoughts on it (especially the config setting name).~
> Add configuration option to override branch name prefix.

- lib/src/working_copy.rs
- lib/tests/test_working_copy_concurrent.rs
This started as an attempt to make us skip sockets while snapshotting the working copy (#258), but ended up being a mixed bag of cleanups and fixed races, without yet fixing the issue with sockets.
> Working copy improvements

- lib/src/git_backend.rs
- lib/src/op_store.rs
- lib/src/working_copy.rs
- src/commands.rs
The regular `Display` format is (not surprisingly) more user-friendly,
as pointed out by @yuja.
> errors: avoid using `Debug` formatting on error types

- CHANGELOG.md
- lib/src/commit_builder.rs
- lib/src/settings.rs
- lib/tests/test_commit_builder.rs
- src/commands.rs
- tests/test_git_push.rs
This patch prevents perhaps pushing commits with an empty description
or the placeholder "(no user/email configured)" values for
author/committer (#322).
> cli: prevent pushing commits without description, author, or committer

- CHANGELOG.md
- src/commands.rs
- src/config.rs
- src/ui.rs
- tests/test_global_opts.rs
I often redirect the jj output to pager, so I set ui.color = "always" in
config file. This patch allows me to remove such config, and instead specify
--color=always only when needed.
> add --color=always|never|auto option

- CHANGELOG.md
- src/commands.rs
- tests/test_obslog_command.rs
This patch adds `jj obslog -p` for including the diff compared to the
predecessor (the first predecessor if there are several). If the
predecessor's parents are different, then we create a temporary tree
by rebasing the predecessor to have the same parents and we use the
result as base for the diff. That way, we avoid polluting the diff
with the changes caused by the rebase. (I don't think we currently
have any commands that can change both parents and content, so the
diff should always be empty for rewrites caused by a rebase.)
Working on this also reminded me that it'll be really nice when we
replace `jj obslog` by something based on the operation log - I really
miss seeing information about the operation in the output (like `hg
obslog` gets from its obsmarkers).
> cli: teach `obslog` an option to show diff

- lib/src/working_copy.rs
If a file gets replaced by a directory right after list files in a
directory but before we stat the file, we currently crash. Let's
instead treat it as a missing file, using the mechanism introduced for
#258.
If applicable:
> working_copy: don't crash if file becomes directory while snapshotting

- lib/tests/test_working_copy.rs
`OperationId` is only used in `test_snapshot_special_file()`, which
doesn't run (or even  build) on Windows.
If applicable:
> cleanup: fix an unused import on Windows

- CHANGELOG.md
- README.md
- docs/git-comparison.md
- docs/tutorial.md
- lib/src/repo.rs
- lib/src/rewrite.rs
- lib/src/settings.rs
- lib/src/view.rs
- lib/tests/test_mut_repo.rs
- lib/tests/test_rewrite.rs
- src/commands.rs
- tests/test_checkout.rs
- tests/test_edit_command.rs
- tests/test_git_push.rs
- tests/test_global_opts.rs
- tests/test_touchup_command.rs
> Remove open commits (see discussion #321)

- src/commands.rs
- tests/test_diff_command.rs
Since whitespace change is barely visible in color-words diff, I think it
would be too verbose to add "\ No newline at end of file" marker. Let's just
append missing newline to make the command output readable.
If applicable:
> diff: make sure word diff print final newline

- lib/src/conflicts.rs
- lib/src/files.rs
- src/commands.rs
The fix for rustlang/rust#89716 was released in 1.59.0, which is our
MSRV.
If applicable:
> cleanup: remove workaround for fixed `split_inclusive()` bug

- CHANGELOG.md
- docs/git-comparison.md
- src/commands.rs
- tests/test_git_push.rs
Since we now allow pushing open commits, we can implement support for
pushing the "current" branch by defining a "current" branch as any
branch pointing to `@`. That definition of a current/active seems to
have been the consensus in discussion #411.
Closes #246.
If applicable:
> cli: push only branches pointing to `@` by default

- src/commands.rs
The working copy does not get snapshotted by `jj git push`, `jj git
push --all`, and `jj git push --branch`. This fixes that.
We should probably do the snapshotting in a more central place, so we
can't forget it like this, but I'll leave that for later.
If applicable:
> cli: snapshot the working copy before pushing

- CHANGELOG.md
- src/commands.rs
- tests/test_squash_command.rs
- tests/test_unsquash_command.rs
- tests/test_untrack_command.rs
I was initially worried about the cost of always snapshotting the
working copy, so that's why e.g. `jj diff -r <some hash>` doesn't do
it. However, there's been a few caused by missing snapshotting, and
there are still a few (I just noticed it in `jj undo` while writing
this patch). Let's always do the snapshotting and if the user really
doesn't want it, they can pass `--no-commit-working-copy` (which we
should probably rename to `--no-snapshot-working-copy` or maybe just
`--no-snapshot`). That should reduce bugs and make the CLI more
predictable.
Two test cases were affected becasue `jj merge` also didn't snapshot
the working copy.
If applicable:
> cli: snapshot working copy even on e.g. `jj diff -r <some hash>`

- src/commands.rs
- tests/test_workspaces.rs
Otherwise the subsequent command would rerun the checkout, which would fail
if the diff contained added files.
If applicable:
> cli: do not discard working copy changes recovered from stale state

- .github/workflows/build.yml
- Cargo.lock
- Cargo.toml
- deny.toml
- lib/Cargo.toml
The only thing I didn't fix is there's some dupes coming in via criterion and an unmaintained warning for serde_cbor also via criterion. Everything else was fixed, one commit at a time, followed by the cargo-deny config, followed by turning it on as a workflow in CI.
> cargo-deny: use tool to enforce constraints on deps

- .github/workflows/build.yml
> github: remove incorrect "v" prefix in a `cargo-deny-action` hash

- src/commands.rs
We have supported conflicts in the working copy for a long time (since
ea823406541e), but I had forgotten to update a few references to the
old behavior.
If applicable:
> cli: remove some obsolete messages about conflicts

- README.md
We have `rust-version = "1.60"` in `Cargo.toml`, but Cargo doesn't
check that until after dependency resolution, which fails if you have
an older version (I don't know why).
If applicable:
> readme: explain that Rust >= 1.60 is needed

- CHANGELOG.md
- src/commands.rs
I was using a custom `jj log` command and had some trouble finding
the commit `jj merge` created. The default `jj log` command shows it
by default, but my custom one didn't.
If applicable:
> Have `jj merge` output new commit id

- CHANGELOG.md
I suppose it could be seen as a bug fix that we no longer discard a
description without asking, but it was intentionally done the way it
was before.
While at it, I also clarified that the source commit gets abandoned if
it becomes empty.
If applicable:
> changelog: asking for a combined description is a feature, not a bug fix

- CHANGELOG.md
- src/commands.rs
- tests/test_interdiff_command.rs
**Description**
This adds a simple `jj interdiff` command as per https://github.com/martinvonz/jj/issues/23, i.e. compare the changes introduced by two commits, ignoring changes from intervening commits. This is basically a more general form of `jj obslog -p` that doesn't assume that the compared commits are predecessor and successor.
The CLI is based on `jj diff`, which probably won't work as well with the more generalized version suggested in https://github.com/martinvonz/jj/issues/498 and I haven't given much thought to the generalized version yet.
**Things to pay extra attention to:**
- I struggled quite a lot with the wording; I'm not sure how to adequately describe `jj interdiff` except in contrast to `jj obslog` or `jj diff`
- I'm also completely new to Rust, so I expect to have …
> cli: add interdiff command

- .github/workflows/dependabot.yml
To merge a Dependabot PR, I have to enable auto-merge (two clicks,
including one to confim) and then review and approve it. Since our
branch protections require the PR to be approved, it seems that that
should be enough. This patch adds a GitHub action that calls runs the
GitHub CLI to do that. It is based on
https://dev.to/slashgear_/how-to-automatically-merge-dependabot-pull-requests-with-github-actions--30pe
If applicable:
> github: enable auto-merge on Dependabot PRs

- src/commands.rs
I keep explaining the functionality as hiding the commit, so it seems
that `jj hide` is a natural name for it. Let's start by adding it as
an alias. My only hesitation with making `hide` the real command name
and `abandon` an alias that we start phasing out is that it feels more
natural to `abandon` the working copy in order to start working on a
new change than it does to `hide` it.
If applicable:
> cli: add `jj hide` as an alias for `jj abandon`

- .github/workflows/dependabot.yml
It seems that there's no way to just enable auto-merge without
specifying a merge strategy (presumably because some projects allow
several GitHub merge strategies), so I guess we'll have to live with
the strategy being duplicated between here and the project settings.
If applicable:
> github: pass `--rebase` to `gh pr merge` since it requires it

- lib/src/file_util.rs
- lib/src/git_backend.rs
- lib/src/index.rs
- lib/src/lock.rs
- lib/src/simple_op_store.rs
- lib/src/stacked_table.rs
- lib/src/testutils.rs
- lib/tests/test_bad_locking.rs
- lib/tests/test_git.rs
- lib/tests/test_init.rs
- lib/tests/test_workspace.rs
- src/ui.rs
- tests/common/mod.rs
> tests: give stable prefix to temporary dirs, do not persist them

- src/diff_edit.rs
Otherwise directories containing files cannot be removed.
I think making files readonly is enough to tell user that the left side
cannot be edited, but I haven't tested that with Meld. If that's not enough,
we'll probably need to undo set_readonly_recursively() at exit.
If applicable:
> diff_edit: do not make directories readonly, give stable prefix to temp dir

- src/commands.rs
- tests/test_rebase_command.rs
(**UPDATE:** I deleted some no-longer relevant info from this comment) 
This is a fix to a bug in `rebase -r` described below. It also changes the behavior of another rebase test in a way that seems desired to me. 
I'm not friends with Rust yet, so I'm sure the style is not great.
Feel free to just use the test I wrote in here if you prefer a different fix.
Previously, using `rebase -r` on the parent of a merge commit
turned it into a non-merge commit. In other words, starting
with
```
o   d
|\
o | c
o | b
| o a
|/  
o 
```
and doing `rebase -r c -d a` resulted in
```
o d
o b
| o c
| o a
|/  
o 
```
where `d` is no longer a merge commit.
For reference, here's a complete test that passed before this commit (but should NOT pass; see the diff for a test that should pass):
```
#[test]
fn …
```
> Fix `rebase -r` of a parent of a merge commit

- README.md
Fixes two pedantic issues with this paragraph:
* "either" describing more than two things.
* I am not an expert, but I suspect that Pijul supports "automatic rebase".
> Reword paragraph about jj and other VCS in README

- .github/workflows/build.yml
- .github/workflows/scorecards.yml
Dependabot doesn't update the comments, so they go stale very quickly.
If applicable:
> github: remove stale comments indicating action versions

- src/commands.rs
Otherwise 'jj diff [TAB]' doesn't provide completion on my zsh.
If applicable:
> cli: add value_hint to support basic path completion

- src/ui.rs
I had missed that `Ui::write_commit_summary()` still shows open commits in green even when open commits are disabled (as they are by default these days). This patch fixes that.
The user can still override templates to format open commits differently, but I'm not sure it's worth fixing that.
If applicable:
> cli: don't show open commits in green when open commits are disabled

- .github/workflows/scorecards.yml
When I read
https://github.com/ossf/scorecard-action#breaking-changes-in-v2 for 6d7ce74a9a7a, it seems like I misread the "for" as "and" in "`include id-token: write` for `publish_results: true`". The latter is not a permissions, it's another setting we have defined further down.
If applicable:
> github: remove `publish_results` field in wrong place

- src/commands.rs
Commands that take both paths and revisions as arguments take paths as positional arguments and use `-r` for revisions (or more specific options like `--from` and `--to`). It's therefore natural for the user to think that they can run e.g. `jj describe -r abc123`. However, since `jj describe` doesn't accept paths, it doesn't have a `-r` argument either. Let's allow the user to specify a superfluous `-r` that we just ignore.
This handling means that the user could run `jj show -r` (without a revision argument) and it would use the default revision. That's confusing, but at least we won't accept e.g. `jj show -r README.md` (unless `README.md` is a revision), so it's probably okay?
If applicable:
> cli: accept `-r` and ignore where revision is positional

- src/commands.rs
As pointed out by IntelliJ (maybe it came from rust-analyzer or something, I don't know). I also lifted out
`Err(CommandError::UserError())` and extracted a variable.
If applicable:
> cli: lift a return statement out of an if-else block

- lib/build.rs
- lib/src/dag_walk.rs
- lib/src/index.rs
- lib/src/lib.rs
- lib/src/matchers.rs
- lib/src/revset.rs
- lib/src/simple_op_store.rs
- lib/src/stacked_table.rs
- src/commands.rs
- src/lib.rs
- src/template_parser.rs
`extern crate` is no longer needed since edition 2018.
If applicable:
> cleanup: remove `extern crate` declarations

- src/commands.rs
Now that open commits are disabled by default, seeing `close` and `open` in `jj help` is confusing.
I'm a little ambivalent about hiding `jj commit` because it's useful as a way of adding a description and starting a new change with a single command. We can always add a new command for that if we want to.
If applicable:
> cli: hide `jj close/commit` and `jj open/uncommit`

- src/commands.rs
Operation id is quite long and these messages looked noisy with the full hash.
If applicable:
> cli: abbreviate operation id embedded in warning/error messages

- examples/custom-backend/main.rs
- lib/src/backend.rs
- lib/src/git_backend.rs
- lib/src/local_backend.rs
- lib/src/repo.rs
- lib/src/testutils.rs
- lib/src/workspace.rs
- lib/tests/test_bad_locking.rs
- lib/tests/test_commit_concurrent.rs
- lib/tests/test_git.rs
- lib/tests/test_index.rs
- lib/tests/test_init.rs
- lib/tests/test_load_repo.rs
- lib/tests/test_working_copy_concurrent.rs
- lib/tests/test_workspace.rs
- src/cli_util.rs
- src/commands.rs
We're going to want to use a custom commit backend at Google (to read and write commits to the cloud). This series makes that easier to do.
If applicable:
> Make it possible to add a custom commit backend

- src/cli_util.rs
When we resolve aliases and we try to resolve something that is not a real command and not an alias, we currently replicate `clap`'s error message. I don't know why I did that because it seems that we should just stop resolving aliases and let `clap` try to parse what we have resolved at that point. This patch makes that change, thereby removing an additional call to `process::exit()`.
If applicable:
> aliases: when invalid command found, let `clap` handle it

- examples/custom-backend/main.rs
- examples/custom-command/main.rs
- src/cli_util.rs
- src/main.rs
This patch move the call to `process::exit()` out of `create_ui()` by letting that function return a `(Ui, Result<(), CommandError>)`.
If applicable:
> cli: don't call `process::exit()` in `create_ui()`

- flake.nix
I there! I bumped into this while updating my home setup (a flake-based home manager following `main` on nixpkgs and jj). I though it might be useful :)
----
`pkgconfig` has been a alias to `pkg-config` since 2021-01-18, and has started being an error since 2022-09-24.
This commit makes recent nixpkgs versions work, but might make version older than January 2021 break (which is probably not an issue).
If applicable:
> Change `pkgconfig` to `pkg-config`

- lib/src/backend.rs
- lib/src/git_backend.rs
- lib/src/protos/op_store.proto
- lib/src/protos/store.proto
- lib/src/protos/working_copy.proto
- lib/src/working_copy.rs
- src/commands.rs
- src/template_parser.rs
I was reading a draft of "Git Rev News: Edition 91" [1] where Peff mentions some unfinished patches to allow negative timestamps in Git. So I figured I should add support for that before I forget. I haven't checked if libgit2 supports it, so it might be that our Git backend still doesn't support it after this patch.
[1] https://github.com/git/git.github.io/blob/master/rev_news/drafts/edition-91.md
If applicable:
> backend: allow negative timestamps in commits and operations

- lib/src/tree_builder.rs
- lib/src/working_copy.rs
- src/cli_util.rs
- src/diff_edit.rs
Otherwise mtime information could be lost, and snapshot() would always
need to build a tree object.
Closes #554
If applicable:
> cli: always call locked_wc.finish() after snapshotting working copy   

- CHANGELOG.md
- lib/src/settings.rs
- src/commands.rs
- tests/test_log_command.rs
Following the Discord discussion re: short hashes, this PR adds a "default revset" setting to be used
by `jj log` if a revset is not specified.
If applicable:
> add default log revset configuration setting

- Cargo.lock
- lib/Cargo.toml
- lib/src/working_copy.rs
- lib/tests/test_working_copy_concurrent.rs
- src/commands.rs
> working_copy: use OnceCell for lazy instantiation of TreeState, return fields by ref

- README.md
As @huyz noticed, I accidentally lost the undo demo in 0d1bf7cb3b7e. I also didn't update the working-copy demo. This patch fixes that by updating all demos, so we also get the recent styling change from af145c998ea4..
If applicable:
> readme: update asciinema links

- lib/src/working_copy.rs
- lib/src/workspace.rs
- lib/tests/test_workspace.rs
- src/cli_util.rs
For consistency with the tree_state handling. This isn't that simple and
concise compared to the tree_state one, so I'm fine to drop the series.
If applicable:
> working_copy: use OnceCell to manage {operation_id, workspace_id}

- Cargo.lock
- Cargo.toml
- lib/Cargo.toml
- src/commands.rs
I had intended for the `features = ["toml"]` to enable *only* the `toml` feature, but I forgot to disable the default features so it had no effect. This shrinks the binary from 17.4 MiB to 16.8 MiB.
If applicable:
> Reduce dependencies a bit

- lib/src/revset.pest
- lib/src/revset.rs
Previously an expression 'foo-bar-' failed to parse because
1. try first rule: 'foo-bar-' matches (identifier_part+ ~ '-')+, but the trailing '' doesn't match identifier_part+
2. fall back to second rule: 'foo' matches identifier_part+ => (identifier 'foo')
Instead, we need to consume as much (identifier_part ~ '-' ~ ...) as possible before falling back to the identifier_part rule.
I think the trailing + of identifier_part+ is redundant, so removed it as well.
If applicable:
> revset: fix parsing of concatenated-identifier in expression

- src/cli_util.rs
- src/commands.rs
- src/formatter.rs
- src/templater.rs
- src/ui.rs
My plan is to make Ui directly hold
output streams so the color settings can be easily reset.
ui.stdout/stderr_formatter() will create a temporary formatter there.
If applicable:
> cli: minor formatter API/life cleanup

- src/cli_util.rs
- src/commands.rs
- src/formatter.rs
- src/ui.rs
> cli: store bare output streams in ui, create formatter per request

- lib/src/settings.rs
- src/commands.rs
- tests/test_init_command.rs
- tests/test_untrack_command.rs
The native backend is just a proof of concept and there's no real reason to use it other than for testing, so let's reduce the risk of accidentally creating repos using it.
If applicable:
> cli: disallow initializing repo with native backend by default

- src/cli_util.rs
- tests/test_global_opts.rs
This commit adds a reminder in `finish_transaction()` if the user hasn't configured their name and email. That means they'll get a reminder after most mutating commits, except for commands that only snapshot the working copy, and a few more cases.
Closes #530.
If applicable:
> cli: remind the user to configure their name and email

- src/commands.rs
- src/formatter.rs
There's a risk of forgetting to call `remove_label()` and I've wanted to reduce that risk for a long time. I considered creating RAII adapters that implement `Drop`, but I didn't like that that would ignore errors (such as `BrokenPipe`) that can happen while emitting an escape sequence in `remove_label()`. I would ideally have liked Python's context managers here, but Rust doesn't have that. Instead, we get to use closures. That works pretty well, except that we can't return other errors than `io::Error` inside the closures. Even with that limitation, we can use the new `with_label()` method in all but a few cases.
We can't define the `with_label()` method directly in the trait because `&mut self` is not a trait object, so we can't pass it on to the closure (which expects a trait object). …
> formatter: add a `with_label()` helper

- src/commands.rs
I find myself using this argument almost every time, but it's
long to type. At the same time, fish completion does not work well
for `--allow-backwards` for some reason (though I think an alias would
be nice regardless).
> Alias `-B` for `--allow-backwards` in `branch set`

- .github/workflows/release.yml
I think 672f9e85cb1d was correct in saying that we don't need the `$staging/complete` directory, but we do seem to need the `$staging` directory, so let's restore the code for creating that. While at it, I also cleaned up a bit so we use the `$outdir` variable instead of duplicating it.
If applicable:
> github: make release build create staging directory

- src/cli_util.rs
- src/ui.rs
The lifetime parameter didn't seem to be used anywhere except a few tests where it wasn't needed, so presuming there isn't a long-term plan that requires it, this makes the code a bit simpler.
If applicable:
> Simplify Ui lifetimes

- src/ui.rs
Allows easier reuse by future variants of UiOutputPair.
If applicable:
> Less opinionated DynWriteLock

- lib/src/settings.rs
- src/commands.rs
- tests/test_alias.rs
- tests/test_operations.rs
- tests/test_workspaces.rs
Yields a less confusing behavior of `jj log` after pushing a commit.
If applicable:
> Include @ in the default revset

- CHANGELOG.md
- lib/src/repo.rs
- lib/src/view.rs
- lib/tests/test_mut_repo.rs
- src/commands.rs
- tests/test_git_remotes.rs
I regularly reach for this when, upon deciding to contribute to a project, I rename `origin` to `upstream` and add a new `origin` addressing my fork.
If applicable:
> Add git remote rename subcommand

- CHANGELOG.md
- src/commands.rs
- tests/test_git_push.rs
I went back and forth on whether scanning `@-` should be conditional on `@` being empty. Currently leaning towards "no" since you might have made some new changes before remembering you wanted to push, and since a nonempty new commit wouldn't land on a branch anyway unless the branch was explicitly updated.
If applicable:
> cli: search @- for branches to push when @ has none

- CHANGELOG.md
- lib/src/repo.rs
- lib/src/rewrite.rs
- lib/tests/test_mut_repo.rs
- lib/tests/test_revset.rs
- lib/tests/test_rewrite.rs
- lib/tests/test_view.rs
- src/cli_util.rs
- src/commands.rs
- tests/test_edit_command.rs
Prevents `jj edit root` from succeeding, which would otherwise place the repo in a state where every operation panics.
If applicable:
> repo: forbid checking out the root commit

- lib/src/git.rs
- lib/src/settings.rs
- lib/tests/test_git.rs
- src/commands.rs
- src/ui.rs
This makes large fetches significantly more pleasant.
If applicable:
> cli: report fetch progress continuously

- src/progress.rs
This was actually what I meant in my code-review comment but I used the wrong word ("clip") :) I wasn't going to bother changing it, but Clippy nightly just started warning about it.
If applicable:
> progress: use `clamp()` for readability

- lib/src/settings.rs
- src/commands.rs
Sometimes a tagged commit is not in any branch on the remote, but we should still consider them upstream and not include them in the default log template.
This was reported by @colemickens but now that I think about it, I remember seeing such commits in the Git core repo (v1.4.4.5 and a few commits before it were never merged into main).
We don't have a good way of testing this because we don't have a command for creating tags.
Closes #681
If applicable:
> cli: include tags as upstream commits to exclude in default log revset

- src/cli_util.rs
- src/ui.rs
Use the try_*() methods to parse args instead of panic!-ing, and print + exit the process using a new Ui.write_clap_err_and_exit(). The exit code 129 is arbitrarily-chosen (it is what git uses for usage).
With this new abstraction, teach the clap output to respect "ui.color" (--color doesn't seem to be understood). We'll also make use of it when we route output through the pager.
The "errors" returned by try_get_matches_from() can be found at https://docs.rs/clap/latest/clap/error/enum.ErrorKind.html. I've tested:
- no args
- --help
- help subcommand
- --version
- subcommand with --help
- subcommand with bad args
If applicable:
> cli: print clap errors through Ui

- src/cli_util.rs
We try to keep the calls to `exit()` in one place. I seem to just have missed this case in an earlier cleanup.
If applicable:
> cli_util: avoid `exit()` in `handle_command_result()`

- lib/src/repo.rs
> repo: turn off view_dirty flag by enforce_view_invariants()

- lib/src/lib.rs
If I'm reading this attribute correctly, it says that if the `map_first_last` feature is enabled, then we should enable the `map_first_last` feature, which seems like it would not have any effect. We started getting warnings from the nightly compiler about this line because it tries to enable a feature that's stable in that version.
If applicable:
> lib: remove ineffective enabling of `map_first_last`

- src/commands.rs
- tests/test_init_command.rs
> cli: handle init destination error gracefully

- CHANGELOG.md
- docs/config.md
- lib/src/settings.rs
- src/cli_util.rs
- src/ui.rs
- tests/test_global_opts.rs
Unfortunately, TOML requires quotes around the argument. So, the
usage is `jj --config-toml ui.color=\"always\"` in bash. The plan is
to eventually have a `--config` option with simpler syntax for
simple cases.
As discussed in https://github.com/martinvonz/jj/discussions/688.
If applicable:
> Add --config-toml command-line argument for additional TOML config

- src/template_parser.rs
I think this cleanup was enabled by a recent refactoring that replaced a trait object by a type parameter (3392e834863e).
If applicable:
> cleanup: avoid an unnecessary `Box` for argument to formatter

- lib/src/repo.rs
- src/cli_util.rs
- src/commands.rs
`ReadonlyRepo::reindex()` is only used in `jj debug reindex`, and it can be implemented by creating a new instance instead of mutating `ReadonlyRepo`.
If applicable:
> repo: remove last mutating method from `ReadonlyRepo`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- lib/src/git.rs
- lib/tests/test_git.rs
- src/commands.rs
- src/progress.rs
- src/ui.rs
Terminal password prompts don't go through `Ui` because that undermines `rpassword`'s facility for suppressing terminal echo. Not sure it's worth hacking around that, since the terminal's a global resource anyway.
In the long run I'd like to move away from basically aping libgit2 in favor of a more composable async API, but that's major refactoring that shouldn't block basic UI cleanup.
I couldn't come up with a graceful way to prompt for usernames via pinentry, so it's relegated to the password-only case.
If applicable:
> Prompt for credentials when needed

- Cargo.lock
- Cargo.toml
- examples/custom-backend/main.rs
- examples/custom-command/main.rs
- src/cleanup_guard.rs
- src/lib.rs
- src/main.rs
- src/progress.rs
- src/ui.rs
This gets fairly fiddly and unsafe due to threading bounded lifetimes through global state, plus the usual concurrency and signal handling fun times.
We could avoid some of this complexity if we removed the requirement of a lifetime to write to `Ui`, e.g. by mediating I/O through refcounted handles with interior mutability, or bypassing `Ui` and writing control sequences to the terminal directly. Alternatively, we could avoid managing terminal state directly with this helper and reserve it instead for stuff like the pager, which might be easier to keep `'static`. Ultimately, I think the status quo is manageable.
CC @chooglen: I expect this to be useful for cleaning up after the pager.
If applicable:
> Drop+signal guard helper

- docs/revsets.md
- lib/src/revset.rs
- lib/tests/test_revset.rs
> revset: add present(set) predicate that suppresses NoSuchRevision error

- CHANGELOG.md
- docs/branches.md
- src/templater.rs
- tests/test_templater.rs
It's useful to know when you've modified a branch that exists on a remote. A typical case is when you have pushed a branch to a remote and then rewritten it. This commit adds an indication in the `branches` template keyword. A branch that needs to be pushed to a remote now has a `*` at the end (similar to how conflicted branches have a `?` at the end). Note that the indication only considers remotes where the branch currently exists, so there won't be an indication that the branch has not been pushed to a remote.
Closes #254
If applicable:
> templater: indicate if branch needs to be pushed to a remote

- Cargo.lock
- lib/Cargo.toml
- lib/src/backend.rs
- lib/src/content_hash.rs
- lib/src/lib.rs
- lib/src/local_backend.rs
- lib/src/op_store.rs
- lib/src/repo_path.rs
- lib/src/simple_op_store.rs
Product of discussion in #700. First commit could be replaced with a manual impl for the enum, saving a fair bit of churn at the cost of being slightly more error prone. No strong opinion about which would be preferable.
> simple_op_store: hash view/operation data directly

- demos/demo_juggle_conflicts.sh
We need to use the native backend here because of #27, but we shouldn't require the user running the script to have it in their config.
If applicable:
> demos: allow running without `ui.allow-init-native = true`

- lib/src/backend.rs
- lib/src/conflicts.rs
- lib/src/git_backend.rs
- lib/src/local_backend.rs
- lib/src/local_backend_model.rs
- lib/src/local_backend_model.thrift
- lib/src/protos/store.proto
- lib/src/tree.rs
- lib/src/working_copy.rs
- lib/tests/test_conflicts.rs
- lib/tests/test_merge_trees.rs
- lib/tests/test_working_copy.rs
- lib/testutils/src/lib.rs
- src/commands.rs
There are no "non-normal" files, so "normal" is not needed. We have symlinks and conflicts, but they are not files, so I think just "file" is unambiguous.
I left `testutils::write_normal_file()` because there it's used to mean "not executable file" (there's also a `write_executable_file()`).
I left `working_copy::FileType::Normal` since renaming `Normal` there to `File` would also suggest we should rename `FileType`, and I don't know what would be a better name for that type.
If applicable:
> backend: rename `NormalFile` to just `File`

- CHANGELOG.md
- docs/revsets.md
- lib/src/revset.rs
- lib/tests/test_revset.rs
> revset: code cleanup, add empty() predicate to find commits with no file change

- CHANGELOG.md
- lib/src/revset.pest
- lib/src/revset.rs
- tests/test_revset_output.rs
> revset: give higher precedence to intersection/difference operators

- docs/git-comparison.md
It's probably not obvious that `jj move` can be used for the `git commit --fixup` usecase.
If applicable:
> docs: describe `git commit --fixup` equivalent

- CHANGELOG.md
- docs/git-compatibility.md
- lib/src/git.rs
Confirmed working due to the existence of this commit which I pushed using the Github CLI credential helper.
If applicable:
> feature: support git credential helpers

- src/commands.rs
- tests/test_global_opts.rs
> cli: fix crash by "jj <global_opts>" without subcommand

- Cargo.lock
- Cargo.toml
- deny.toml
- src/ui.rs
The `atty` crate seems unmaintained. There's
https://rustsec.org/advisories/RUSTSEC-2021-0145 filed against it, which `cargo-deny` complains about. A fix for that has been open for well over a year without being fixed
(https://github.com/softprops/atty/pull/51). The `is-terminal` crate is a fork of `atty` with that fixed, plus some other changes.
If applicable:
> cli: switch from `atty` crate to `is-terminal`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- lib/Cargo.toml
- src/cli_util.rs
- src/main.rs
- tests/test_global_opts.rs
As discussed in [discord](https://discord.com/channels/968932220549103686/969291218347524238/1043744808709140530) this adds a verbose flag which integrates with the tracing library.
I'm not 100% happy with how the verbose flag gets enabled and would be happy to discuss any approaches for making that cleaner. Right now some early debug/trace logs might get missed out due to when the flag gets actioned.
See #772 for actual instrumentation.
If applicable:
> feature: add verbose flag and tracing library

- lib/src/file_util.rs
- lib/src/git.rs
- lib/src/simple_op_store.rs
- src/ui.rs
- testing/fake-diff-editor.rs
- testing/fake-editor.rs
- tests/test_commit_command.rs
- tests/test_split_command.rs
Adds a test for https://github.com/martinvonz/jj/commit/cf3b6ee2c9c773381c7919c8d95fd8a9262ac562
Also includes fixes to some clippy warnings.
> Test `jj split` commit description prompt

- CHANGELOG.md
- lib/src/git.rs
- lib/tests/test_git.rs
- lib/tests/test_init.rs
- lib/tests/test_working_copy.rs
- src/cli_util.rs
- src/commands.rs
- tests/test_git_colocated.rs
- tests/test_git_export.rs
> On export to git, skip branches that fail instead of erroring out

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/config.md
- docs/config.toml
- lib/src/settings.rs
- src/commands.rs
- src/template_parser.rs
- src/templater.rs
- tests/test_log_command.rs
- tests/test_show_command.rs
This makes the commits logs an extra bit more readable for me, mainly because it doesn't consume as much horizontal space per log line anymore.
Example output:
1. It's a bit awkward having this be a setting since it requires passing the settings throughout the parsing code. If this was the only way of formatting datetimes we could rip all that out but I didn't want to make a unilateral decision there and I wanted to get feedback on it first.
2. I'm also not super happy with having the `chrono::Local::new()` deep in a method and I would have preferred to create a "called_time" or equivalently named variable at the start and pass that through (probably in the Ui or another context object) but that would have been a far deeper refactor which I would have wanted feedback on as well.
3. I'm …
> feature: support relative timestamps as a config option

- CHANGELOG.md
- docs/revsets.md
- lib/src/revset.pest
- lib/src/revset.rs
- lib/tests/test_revset.rs
- src/cli_util.rs
- src/commands.rs
- tests/test_revset_output.rs
Example:
```
[revset-alias]
'M' = 'present("main") | present("master")'
'mine' = 'author("yuya")'
```
Config syntax to bikeshed:
- naming: `[revset-alias]` vs `[revset-aliases]`?
- function alias will need quotes: `'f(x)' = 'x'`
If applicable:
> revset: implement simple symbol alias expansion

- lib/src/git.rs
84b924946f4189960d6d8d7ae2e04d296d272906 switched to requiring both SSH_AUTH_SOCK and SSH_AGENT_PID for an agent to be used. This doesn't seem to be a typical situation, so perhaps it was not intended.
CC @rslabbert
If applicable:
> git: revert change to SSH agent detection

- docs/revsets.md
- lib/src/revset.rs
- lib/tests/test_revset.rs
Because the use of the change id is recommended, any operation should abort
if a valid change id happens to match a commit id. We still try the commit
id lookup first as the change id lookup is more costly.
Ambiguous change/commit id is reported as AmbiguousCommitIdPrefix for now.
Maybe we can merge AmbiguousCommit/ChangeIdPrefix errors into one?
Closes #799
If applicable:
> revset: for short hash, look up both commit and change ids to disambiguate

- lib/src/revset.rs
- lib/tests/test_revset.rs
Follows up c5ed3e14776b. Now change/commit ids are resolved at the same precedence, which means there are at least three types of ambiguity. I don't think we would need to discriminate these.
If applicable:
> revset: merge AmbiguousChange/CommitIdPrefix error into one

- src/cli_util.rs
- src/commands.rs
- tests/test_branch_command.rs
- tests/test_git_colocated.rs
- tests/test_git_export.rs
- tests/test_log_command.rs
> cli: hint about how to recover from failed export of branches

- docs/revsets.md
- lib/src/revset.pest
- lib/src/revset.rs
- lib/tests/test_revset.rs
- tests/test_revset_output.rs
Because a unary negation node `~y` is more primitive than the corresponding
difference node `x~y`, `~y` is easier to deal with while rewriting the tree.
That's the main reason to add RevsetExpression::NotIn node.
As we have a NotIn node, it makes sense to add an operator for that. This
patch reuses `~` token, which I feel intuitive since the other set operators
looks like bitwise ops. Another option is `!`.
The other things to bikeshed:
- Do we still need the infix difference operator `x ~ y`?
(`x & ~y` will be optimized to `Difference(x, y)`)
- Operator naming: negate_op, not_op, complement_op
- Variant naming: Negated(), Not(), NotIn(), Complement()
If applicable:
> revset: add unary negate (or set complement) operator '~y'

- docs/config.md
- docs/config.toml
Also moves the "relative timestamps" section to make merge tool docs from https://github.com/martinvonz/jj/pull/689 fit in better.
This was developed as part of https://github.com/martinvonz/jj/pull/689, but it might make sense to merge it in earlier.
> Miscellaneous improvements to config docs

- CHANGELOG.md
- lib/src/protos/working_copy.proto
- lib/src/working_copy.rs
- lib/tests/test_working_copy.rs
A new FileType, GitSubmodule is added which is ignored. Files or directories having this type are not added to the work queue and are ignored in snapshot.
If applicable:
> Do not delete or track git submodules.

- lib/src/index.rs
This warning used to show up, at least, on Rust nightly:
unused import: `crate::nightly_shims::BTreeSetExt`
> Remove an unused import warning on recent versions of Rust

- lib/src/index.rs
> RevWalk: push all parents and deduplicate later, return early if filled with unwanted

- lib/src/tree.rs
- src/cli_util.rs
- src/commands.rs
- src/diff_edit.rs
- tests/test_resolve_command.rs
Also allows several paths to be specified. By default, `jj resolve`
will find the first conflict that matches provided paths (if any)
and try to resolve it.
> Make optional the path argument to `resolve`, allow partial paths

- lib/src/index.rs
- lib/src/revset.rs
- lib/tests/test_revset.rs
> revset: use filter intersection for tree containing filter (e.g. `set & (filter() | set)`)

- src/commands.rs
- tests/test_git_clone.rs
Otherwise a subsequent git fetch would fail.
If applicable:
> cli: on clone, turn local git remote to absolute path

- .github/workflows/scorecards.yml
Google's security team asked us to remove this use of a PAT. It's apparently supposed to work with it, it's just that it won't be able to check that we bronch protection set up.
If applicable:
> github: make Scorecard security scanner not use access token

- CHANGELOG.md
- src/commands.rs
- tests/test_diff_command.rs
The number of lines in the diff output is unchanged.
This makes diffs a little more readable when the "..." would otherwise hide a single line of code that helps in understanding the surrounding context lines.
This change mostly rearranges the loop that consumes the diff lines, so it can buffer up to num_context_lines*2+1 lines instead of just num_context_lines. There's a bit of extra code to handle times when a "..." replaces the last line of a diff.
Note that `jj diff --git` is unchanged, and will still output `@@` lines that replace a single line of context.
If applicable:
> Do not use "..." between diff chunks when it only replaces 1 line of the diff

- docs/conflicts.md
When importing `conflicts.md` into the Google repo, our internal tools complained that it contained conflict markers. Similarly, if you ever get an actual merge conflict in the file, the working-copy snapshotting would parse our sample conflict markers here, forcing you to work around it. Let's avoid that by indenting the conflict markers. Hopefully readers will understand that the leading space is not part of the markers.
If applicable:
> docs: indent conflict marker examples to not confuse tools

- CHANGELOG.md
- lib/src/revset.rs
- lib/tests/test_revset.rs
> revset: fold nested parents expressions to evaluate lazily

- src/cli_util.rs
- tests/test_global_opts.rs
It can be useful to paginate the help output (e.g. `jj help`) for easy reading. This should also support `--no-pager` for users who prefer not to use pagination, but because of how `clap` parse `help` (and others), this requires changing how we parse global args (see the second commit). As a side-benefit, we can now pass `--color` to `jj help`.
This is still a WIP because this does not have tests.
If applicable:
> Paginate help output

- src/cli_util.rs
- tests/test_alias.rs
> cli: parse early args in/after alias properly

- CHANGELOG.md
- src/commands.rs
- tests/test_obslog_command.rs
The author timestamp is rarely useful (in my experience). The committer timestamp, on the other hand, can be useful for understanding when a change was most recently modified. IIRC, I originally picked the author timestamp to match the email (which is the author's), but it's probably not confusing to use the author email and the committer timestamp. I suspect few users will even reflect on it.
If applicable:
> cli: use committer timestamp instead of author timestamp in log output

- CHANGELOG.md
- src/commands.rs
- src/diff_util.rs
- tests/test_diff_command.rs
- tests/test_log_command.rs
> make `jj log --patch --summary` show both summary and diff

- lib/src/simple_op_store.rs
- lib/tests/test_bad_locking.rs
- lib/tests/test_working_copy.rs
Interestingly, the nightly release doesn't complain about this.
If applicable:
> cleanup: remove an unnecessary borrow reported by Clippy 1.66

- lib/build.rs
Since we call `cargo_out_dir()` - which is the preferred way of using `protobuf_codegen::Codegen` in `build.rs` - our call to `out_dir()` has no effect.
If applicable:
> protobuf: remove ignored call to `out_dir()`

- lib/src/git_backend.rs
Performance on repositories with many commits is limited somewhat by repeatedly stating the tablestore directory to work out what the head is. By caching the table rather than looking it up from disk on every request, we can much more rapidly satisfy requests. 
This avoids the pathological case in #845 where jj operations take several minutes to complete.
This patch doesn't change the normal flow of the write path: that will still always call get_head() on the underlying TableStore, which will stat the directory before writing out changes. It will however empty the cache when the metadata has been written.
Fixes #845.
If applicable:
> git: cache the extra metadata table

- src/commands.rs
I think "append" is the default for `Vec`-type fields.
If applicable:
> cli: remove unnecessary (?) `ArgAction::Append` in `$[clap]`

- src/cli_util.rs
Per https://git-scm.com/docs/gitignore:
> Its default value is $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.
If applicable:
> cli: respect default value of git core.excludesFile

- CHANGELOG.md
- lib/src/refs.rs
- src/commands.rs
- tests/test_git_push.rs
Also creates a short arg `-b` for `--branch`.
I haven't tried to make the code very pretty, but I got tests to pass.
If applicable:
> Allow `jj git push` to push multiple branches/changes at once

- tests/test_move_command.rs
- tests/test_squash_command.rs
- tests/test_unsquash_command.rs
> cli: fix move/squash/unsquash tests to run without source commit description

- CHANGELOG.md
- examples/custom-command/main.rs
- lib/src/commit_builder.rs
- lib/tests/test_mut_repo.rs
- lib/tests/test_operations.rs
- lib/tests/test_revset.rs
- lib/tests/test_rewrite.rs
- lib/tests/test_view.rs
- src/cli_util.rs
- src/commands.rs
- tests/test_checkout.rs
- tests/test_commit_command.rs
- tests/test_concurrent_operations.rs
- tests/test_describe_command.rs
- tests/test_diffedit_command.rs
- tests/test_edit_command.rs
- tests/test_git_colocated.rs
- tests/test_git_push.rs
- tests/test_move_command.rs
- tests/test_new_command.rs
- tests/test_obslog_command.rs
- tests/test_operations.rs
- tests/test_rebase_command.rs
- tests/test_squash_command.rs
- tests/test_status_command.rs
- tests/test_templater.rs
- tests/test_unsquash_command.rs
- tests/test_workspaces.rs
> normalize line ending of commit description set by -m/--message or editor

- .github/workflows/build.yml
- Cargo.lock
- Cargo.toml
- lib/Cargo.toml
- lib/build.rs
- lib/gen-protos/Cargo.toml
- lib/gen-protos/src/main.rs
- lib/src/git_backend.rs
- lib/src/local_backend.rs
- lib/src/proto_op_store.rs
- lib/src/protos/mod.rs
- lib/src/protos/op_store.rs
- lib/src/protos/store.rs
- lib/src/protos/working_copy.rs
- lib/src/repo_path.rs
- lib/src/working_copy.rs
Prost is a far more conformant implementation (https://github.com/stepancheg/rust-protobuf/pull/661 vs. https://github.com/tokio-rs/prost/blob/master/conformance/failing_tests.txt) and appears to be more actively maintained (no commits in protobuf since September, PRs not being reviewed).
If applicable:
> lib: replace protobuf crate with prost

- src/commands.rs
The divergent label is most relevant when the user is about to refer to a commit by its change id.
It's also good to put it far from the `conflicts` label, to reduce confusion between very different concepts that have similar names.
Finally, I think it is a feature rather than a bug that the `divergent` label now upsets the alignment of different lines of `jj log`.
--------
I think this doesn't change any of the screenshots in the repo. If it does, we could consider bundling this with other changes to `jj log` output.
> cmd `jj log`: Move `divergent` label next to the change id

- README.md
Trying to install without providing the `jujutsu` argument causes a conflict.
> Update cargo installation instructions

- lib/src/matchers.rs
- lib/tests/test_diff_summary.rs
- lib/tests/test_revset.rs
> matchers: remove .to_vec() from PrefixMatcher::matches() loop

- src/commands.rs
As far as I can tell it won't hurt anyone to have this alias exist, but will help those of us with old muscle memory.
> commit: add alias `ci` for cvs/svn/hg muscle memory havers

- lib/src/repo.rs
We forgot to actually call `StoreFactories::load_op_heads_store()` to load the right type of `OpHeadsStore` depending on the contents of `.jj/repo/op_heads/type`. That shouldn't have any effect yet since we only have one type so far, and there are no out-of-tree types yet either (clearly, since they would not work).
If applicable:
> repo: load correct `OpHeadsStore` depending on repo's type

- docs/github.md
The document roughly describes some workflows, which help new users to start with github.
@superpippo12 Discord self ping.
[Rendered](https://github.com/PhilipMetzger/jj/blob/push-075ec4ff589b45a89ccf25098371e4ff/docs/github.md)
If applicable:
> [Docs]: Add some more documentation on how to work with github.

- tests/test_config_command.rs
- tests/test_log_command.rs
It turns out we did not have tests that would catch `jj log` failing to mark divergent commits.
> Test `jj log` for divergent commits 

- src/config-schema.json
Can be used with tools like taplo-lsp to show hints & validation in editors/IDEs. Won't apply automatically to config files until it's submitted to schemastore.org, but in the meantime it can be used via a schema directive
(https://taplo.tamasfe.dev/configuration/directives.html#the-schema-directive) or other manual config mechanism.
Context in #879.
If applicable:
> Define config TOML/JSON schema

- README.md
Seems two spots in the README were missed by https://github.com/martinvonz/jj/commit/cc40740fa2bb15ec70799692353c8cad2ffe8f5b from #947.
When not specifying the crate, we get the following error:
```
error: multiple packages with binaries found: gen-protos, jujutsu. When installing a git repository, cargo will always search the entire repo for any Cargo.toml. Please specify which to install.
```
> fix: update cargo install command in readme to specify jujutsu crate

- .github/workflows/release.yml
- Cargo.toml
- README.md
I added support for using a vendored OpenSSL in dbadbd68c022. That was in order to get the musl binary to work. However, it shouldn't be needed on most platforms, and we've had a few reports of issues caused by it. Let's disable it by default and enable it specifically when building the musl binary instead.
If applicable:
> build: don't use vendored OpenSSL by default

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/commands.rs
- tests/test_debug_command.rs
Extends TOML/JSON schema changes from #966 to allow jj to output the schema directly. Context in #879.
If applicable:
> Add "jj debug config-schema" command to output JSON schema

- CHANGELOG.md
- src/commands.rs
- tests/test_resolve_command.rs
This can be prevented by the new `--quiet` option.
If applicable:
> ui `jj resolve`: List remaining conflicts (if any) on success

- README.md
Without it, cargo started erroring out for me after #970 saying it couldn't find openssl without pkg-config being installed.
If applicable:
> Add pkg-config to required Linux dependencies in README

- CHANGELOG.md
- src/commands.rs
- tests/test_resolve_command.rs
The descriptions focus on adds, not the deletions. The deletions are used
to compute the number of deleted files that must be sides of the conflict.
If applicable:
------------------------------------
This is based on top of #975. I am pretty happy with the English of the descriptions. It might be nice to have prettier alignment, though.
There could also be a `--short` option that says the same thing more compactly, e.g. "txt, txt" or "dir, exe" for 2-sided conflicts.
On the other hand, I don't run into conflicts this complex often enough to know what is useful here.
> `jj resolve --list`: Add descriptions of conflict complexity

- CHANGELOG.md
- docs/config.md
- lib/src/settings.rs
- lib/src/workspace.rs
- src/cli_util.rs
- src/config.rs
- src/formatter.rs
- src/ui.rs
- tests/test_config_command.rs
- tests/test_global_opts.rs
- tests/test_log_command.rs
> cli: load configs from .jj/repo/config.toml

- tests/test_git_push.rs
Our change IDs are now predictable in tests.
If applicable:
> tests: drop no-longer-needed filter of change ID

- src/commands.rs
This will match `jj`'s behavior of being unable to resolve such conflicts or to show readable diffs of them, in the pre-#978 state.
This is a fixup of 621293d7c6.
If applicable:
- (not planned)  I have updated the documentation (README.md, docs/, demos/)
- (may happen as part of #978) I have added tests to cover my changes
> `resolve --list`: account for deletions of special files

- CHANGELOG.md
- src/commands.rs
- src/template_parser.rs
- tests/test_operations.rs
If applicable:
- (the docs work as is) I have updated the documentation (README.md, docs/, demos/)
> Have `jj op log` obey `ui.relative-timestamps` option

- lib/src/tree_builder.rs
- src/cli_util.rs
- src/commands.rs
- src/config/colors.toml
- src/ui.rs
- tests/test_resolve_command.rs
`jj status` now looks like this:
If applicable:
> `jj resolve --list` and `jj status`: make conflict output colorful + clippy

- tests/test_commit_template.rs
- tests/test_log_command.rs
I'm about to make some changes to the templater, so let's have a test least a simple test of the current colored output.
If applicable:
> log: add test of colored output

- CHANGELOG.md
- lib/src/workspace.rs
- lib/tests/test_workspace.rs
- src/cli_util.rs
- tests/test_global_opts.rs
> cli: do not search ancestor paths specified by -R/--repository

- src/commands.rs
- tests/test_commit_template.rs
> cli: fix highlighting of checkout commit in "log --no-graph"

- CHANGELOG.md
- src/cli_util.rs
- src/commands.rs
- src/config.rs
- testing/fake-editor.rs
- tests/common/mod.rs
- tests/test_config_command.rs
Part of #531 to define the overall `config` command.
If applicable:
> Add a `config edit` command to open jj config in editor

- src/commands.rs
- tests/test_resolve_command.rs
If all file names are short enough, this will align the conflict
description at 4 spaces past the longest file name, as follows:
```
src/templater.rs            2-sided conflict
src/templater_parsers.rs    2-sided conflict
```
If there is a long file name, conflict descriptions will either start
or column 35 or one space from a file name, whichever is later.
Previously, a single tab was used to separate file name from conflict
description. This didn't look as nice as I hoped when multiple files
are involved. I also don't think `jj` generally uses tabs in output.
The tab uncovered a bug in a watcher program I was using.
If applicable:
> `jj resolve --list`: make output aligned

- src/cli_util.rs
- src/commands.rs
- tests/test_abandon_command.rs
- tests/test_checkout.rs
There are no tests for `jj abandon` currently. I might add some here or in another PR, but not right now.
If applicable:
> `jj abandon`: Report what commit or how many commits were abandoned

- src/merge_tools.rs
- tests/test_diffedit_command.rs
- tests/test_resolve_command.rs
This would have made it a bit easier to  debug a problem somebody had on Discord.
If applicable:
> `jj resolve`: Add debug information to EmptyOrUnchanged error

- flake.nix
Otherwise nix 2.8 and newer will give this error message:
```
>> nix --version; nix run github:martinvonz/jj
nix (Nix) 2.11.1
error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'
```
If applicable:
> Fix `nix run`

- lib/src/index.rs
- lib/src/revset.rs
- lib/src/settings.rs
- tests/test_git_push.rs
`create_no_gc_ref()` is the last remaining dependency on UUID.
If applicable:
> reimplement random ChangeId generator without using UUID

- src/templater.rs
This also prevents the creating of an extra empty String when the description is empty.
If applicable:
> style: description template extractor

- CHANGELOG.md
- docs/tutorial.md
- src/commands.rs
- src/config/colors.toml
- src/template_parser.rs
- src/templater.rs
- tests/test_alias.rs
- tests/test_commit_template.rs
- tests/test_obslog_command.rs
- tests/test_revset_output.rs
The tests are covered by existing ones.
I have chosen yellow as the "(empty)" marker color, maybe you would prefer another one.
Fix #1028.
If applicable:
> Mark empty commits in jj log

- src/commands.rs
- src/lib.rs
- src/template_parser.rs
- src/time_util.rs
i acted upon a `TODO` in the code;
If applicable:
> refactor: separate timestamp related utilities in time_util module

- CHANGELOG.md
- lib/src/revset.rs
- tests/test_git_colocated.rs
This is a partial fix to #814: the crash will no longer happen since the commit id unknown to jj will be considered non-existent.
If applicable:
> No crash for unreachable commit

- lib/src/backend.rs
- lib/src/content_hash.rs
- lib/src/op_store.rs
- lib/src/simple_op_store_model.rs
Dereferencing `self` as `*self` in order to perform patten-matching using `ref` is unnecessary and will be done automatically by the compiler (match ergonomics, introduced in Rust 1.26).
If applicable:
> style: do not dereference self to perform pattern-matching

- Cargo.lock
See https://github.com/martinvonz/jj/actions/runs/3920774270/jobs/6702590941
Hopefully, this will pass the `cargo-deny` check
I just ran `cargo update -p bumpalo`.
> Update `Cargo.lock` to make `cargo-deny` CI happy

- lib/tests/test_revset.rs
- lib/testutils/src/lib.rs
This doesn't change any tests, but could prevent change ids randomly matching commit id prefixes from causing tests to fail in the future.
Follows up on bbd49cdf29, https://github.com/martinvonz/jj/issues/1024 and https://github.com/martinvonz/jj/pull/1033.
@yuja , let me know if you have any concerns.
> Fix random seed in all tests that use `testutils::user_settings`

- src/config/colors.toml
- tests/test_commit_template.rs
1. The "empty" marker from https://github.com/martinvonz/jj/pull/1034 changes from yellow to green. This is not a major change, but looks a little more orthogonal and clear:
2. Fixes https://github.com/martinvonz/jj/issues/528 by changing bright yellow to yellow.
3. Finally, stop using `white` or `bright white` which are hardly visible on bright themes.
`xterm`'s default theme before:
After:
IMO, the goal with this particular theme is to be bearable, not pretty :).
If applicable:
- (postponed) I have updated the documentation (README.md, docs/, demos/)
- (not planned) I have added tests to cover my changes
> Fix issues with bright color themes, change `(empty)` marker color

- CHANGELOG.md
- docs/revsets.md
- lib/src/revset.rs
- lib/tests/test_revset.rs
- branches has the signature `branches([needle])`, meaning the needle is optional (`branches()` is equivalent to `branches("")`) and it matches all branches whose name contains needle as a substring
- remote_branches has the signature `remote_branches([branch_needle[, remote_needle]])`, meaning it can be called with no arguments, or one argument (in which case, it's similar to branches), or two arguments where the first argument matches branch names and the second argument matches remote names (similar to branches, `remote_branches()`, `remote_branches("")` and `remote_branches("", "")` are all equivalent)
If applicable:
> let branches and remote_branches revset functions take arguments

- CHANGELOG.md
- lib/src/gitignore.rs
The existing result of `remove_trailing_space(r#"foobar\\ "#)` is `r#"foobar\\ "#` because it thinks that the trailing space is escaped by the preceeding backslash, while in fact it is the second character of the `r#"\\"#` sequence.
Note that in the rest of the `gitignore.rs` file we correctly handle any escaped character already.
If applicable:
> gitignore: any character can be backslash-escaped

- CHANGELOG.md
- docs/github.md
- src/commands.rs
- src/config.rs
- src/config/git.toml
The `git.fetch` and `git.push` keys can be used in the configuration file for the default to use in `jj git fetch` and `jj git push` operations.
By defaut, "origin" is used in both cases.
For example when developing for this repository I only fetch from "upstream" (martinvonz/jj) and only push to "origin" (samueltardieu/jj). Being able to write this in my configuration file makes it easier.
If applicable:
> config: allow configuration of git remotes for fetch and push operations

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- lib/src/git_backend.rs
- lib/src/repo.rs
- src/commands.rs
- tests/test_abandon_command.rs
- tests/test_duplicate_command.rs
Fixes https://github.com/martinvonz/jj/issues/27, https://github.com/martinvonz/jj/issues/694 and https://github.com/martinvonz/jj/issues/1050
I combined the bugfix PRs with the feature PR into one since they are both ready. If a portion of this PR gets a faster review than the rest, I'll split them again.
Now also includes a minor fix to `jj abandon`: if the same revision is specified several times, it is now only listed once in the output.
If applicable:
> Allow simultaneous rebasing of duplicate commits, duplicating multiple commits, undo after duplicate

- CHANGELOG.md
- docs/config.md
- lib/src/index.rs
- lib/src/repo.rs
- lib/src/settings.rs
- src/commands.rs
- src/template_parser.rs
- src/templater.rs
- tests/test_commit_template.rs
- tests/test_init_command.rs
- tests/test_log_command.rs
- tests/test_obslog_command.rs
This makes it possible to set `ui.unique-prefixes="underscore"` and make `jj` highlight the unique prefix of each ID as follows:
There are some more thoughts in the commit descriptions.
We should make use of https://github.com/martinvonz/jj/pull/962 and make it possible to mark the prefix with underline & color. The current underscore highlight is still useful for tests, at least. I'm not sure how urgent this is.
In fact, I have a **question**: I cautiously kept the default at no highlighting, mainly since the underscores mess up copying and pasting. Was this over-cautious?
The IdIndex created in this PR could immediately be used to find divergent commits and to look up commits by prefix replacing these functions.
https://github.com/martinvonz/jj/blob/50321f851f4ce0f484fcd029b4d04581ad356d …
> Have `jj log` hightlight unique prefixes, `BTree`-based implementation

- lib/src/transaction.rs
- src/commands.rs
I'll send the remainder after #1020 gets merged.
If applicable:
> cli: reorder .start_transaction() bits to allow it to borrow `&mut self`

- CHANGELOG.md
- src/commands.rs
- tests/test_cat_command.rs
`jj cat` better matches `hg cat` and, of course, `cat`. I apparently called it `jj print` when I added it in 7a013a59ae98 because I haven't found `hg cat` useful for actually concatenating files. That's still true, and I don't know if we will ever bother to teach `jj cat` to actually concatenate files, but I think the familiarity of `cat` is more important.
For reference, Git calls it `git show <rev>:<file>`.
I kept `print` as an alias and added a test for it. I also documented the test better.
By the way, I've considered adding a command for writing from stdin directly to a specific commit. If we ever do, it might make sense to call that command `write` (e.g. `echo foo | jj write -r @- README.md`). Then it would make sense to add `read` as an alias to `cat`. I'm not sure that's a good …
> cli: rename `print` to `cat`

- examples/custom-global-flag/main.rs
- src/cli_util.rs
Our internal build at Google needs a custom global flag, which lets the user pass flags into C++ code we use for our custom backends. This provides a way of achieving that.
If applicable:
> cli: add a way to add custom global flags

- examples/custom-backend/main.rs
- examples/custom-command/main.rs
- examples/custom-global-flag/main.rs
- src/cli_util.rs
- src/main.rs
`CliRunner::run()` has been renamed from `CliRunner::run_and_exit()` and returns an `ExitCode` which can be returned from `main()`.
If applicable:
> refactor: return ExitCode from CliRunner::run()

- docs/github.md
During the initial review, we missed that I wrote `detached head`  in the link to https://www.git-scm.com/docs/git-checkout#_detached_head  instead of `detached`. This corrects the link.
> Docs: Fix a dangling ref.

- lib/src/op_heads_store.rs
- lib/src/repo.rs
- lib/src/simple_op_heads_store.rs
- lib/src/transaction.rs
- lib/tests/test_bad_locking.rs
- lib/tests/test_load_repo.rs
- lib/tests/test_view.rs
- src/cli_util.rs
- src/commands/mod.rs
This PR refactors OpHeadsStore into a trait with no LockedOpHeads, and instead a free templated function for resolving conflicts given an externally provided resolver.  It simplifies the internal Arc<> story as well as a bunch of call sites.
If applicable:
> op_heads_store: simplify the OpHeadsStore trait through refactoring

- lib/src/backend.rs
It can be useful in tests to be able to compare two commits or trees. Most other structs already implement equality.
If applicable:
> backend: implement equality for commits and trees

- .envrc
The flake currently has some odd behavior, such as copying .jj and target/, and treating the jj src as an input to the dev shell. This avoids making life rough for direnv users while those are outstanding.
> nix: remove .envrc

- Cargo.lock
- Cargo.toml
- deny.toml
- flake.nix
- src/graphlog.rs
The rendering is now its own crate, so we don't need to depend on the other `dag` code.
If applicable:
> cargo: replace dependency on Sapling's `dag` by `renderdag`

- lib/src/index.rs
- lib/src/repo.rs
> repo: leverage stored index to calculate shortest prefix in commit id space

- CHANGELOG.md
- src/commands/mod.rs
The help strings for fish and zsh were inverted.
If applicable:
> Fix output of `jj debug completion --help`

- src/template_parser.rs
I think this is a remainder of 68ad712e123e "Templater: Combine Change and Commit id templates." It doesn't make sense that description.short() prints the first 12 characters.
If applicable:
> templater: remove string.short() method

- tests/common/mod.rs
I noticed it while considering using this function. I ended up not using it but the change makes a cleaner interface.
If applicable:
> style: make normalize_output() take a &str instead of a String

- CHANGELOG.md
- docs/working-copy.md
- src/commands/mod.rs
- tests/test_workspaces.rs
I needed to find the root of the current workspace and couldn't find a command to do it. Please disregard if there is already a command which does that.
If applicable:
> workspace: add a root subcommand to print the workspace root path

- examples/custom-command/main.rs
- src/cli_util.rs
- src/commands/branch.rs
- src/commands/git.rs
- src/commands/mod.rs
- src/commands/operation.rs
> cli: add transaction wrapper to prevent WorkspaceCommandHelper API misuse

- lib/src/protos/working_copy.proto
- lib/src/protos/working_copy.rs
- lib/src/repo.rs
- lib/src/rewrite.rs
- lib/src/working_copy.rs
- lib/tests/test_commit_concurrent.rs
- lib/tests/test_init.rs
- lib/tests/test_mut_repo.rs
- lib/tests/test_revset.rs
- lib/tests/test_view.rs
- src/commands/git.rs
- src/commands/mod.rs
- tests/test_workspaces.rs
I've preferred "working-copy commit" over "checkout" for a while because I think it's clearer, but there were lots of places still using "checkout". I've left "checkout" in places where it refers to the action of updating the working copy or the working-cop commit.
If applicable:
> cleanup: update more "checkout" to "working-copy commit" and similar

- docs/contributing.md
This is something I wish I had when I first contributed to `jj`.
Let me know if you disagree with the "we recommend" part. It's a big claim, I don't want to include it if it doesn't feel right to somebody.
> `contributing.md`: Add a link to the "Comprehensive Rust" course

- tests/common/mod.rs
- tests/test_diffedit_command.rs
- tests/test_move_command.rs
- tests/test_squash_command.rs
- tests/test_unsquash_command.rs
I would expect `set_up_fake_[diff_]editor()` to create an empty script but it turns out they didn't even create the files. That means that the caller needs to write an empty script to them if they want the fake editors to not do anything. Let's instead write the empty scripts, for a less surprising behavior.
If applicable:
> tests: make fake editor scripts initially empty

- README.md
Our installation instructions don't currently work with Rust < 1.64 because `clap` updated their MSRV to 1.64, and `cargo install` without `--locked` bypasses `Cargo.lock` and selects the version of `clap` that needs Rust 1.64.
If applicable:
> readme: add `--locked` to `cargo install` step

- lib/src/commit.rs
- lib/src/repo.rs
I would expect `Commit::is_empty()` to check if the commit is empty in our usual sense, i.e. that there are no changes compared to the auto-merged parents. However, it would return `false` for any merge commit (and for the root commit). Since we only use it in one place, let's inline it there. The use there does seem reasonable, because it's about abandoning an "uninteresting" working-copy commit.
If applicable:
> repo: inline single-caller, and surprising, `Commit::is_empty()`

- src/commands/mod.rs
- src/template.pest
- src/template_parser.rs
- tests/test_templater.rs
> templater: eliminate redundant empty literals, fix handling of parens

- CHANGELOG.md
- src/commands/mod.rs
- tests/test_split_command.rs
jj split .           => create an empty child
jj split nonexistent => create an empty parent
That would fix #881.
If applicable:
> split: allow creation of empty parent or child

- lib/src/index_store.rs
When building an initial index from an existing Git repo, for example, we walk parents and predecessors to find all commits to index. Part of that code was looking up the whole parent and predecessor commits even though it only needed the ids. I don't know if this has a measurable impact on performance, but it's not really any more complex to just get the ids anyway.
If applicable:
> index_store: don't look up whole commit when only id is needed

- lib/src/working_copy.rs
I don't think there's a good reason not to write the `.jj/working_copy/tree_state` file on init. Being able to assume that the file exists means that we won't need the store object to to lazily load the `TreeState` object. Well, except that `TreeState` keeps an `Arc<Store>`, but I'm trying to change that.
If applicable:
> working_copy: write tree_state file on init

- src/commands/git.rs
- tests/test_git_push.rs
Fix a bug where `jj git push` would print "No current branch." when there is a current branch but it is unchanged. We were conflating the two because we print the message when no updates were performed, instead of only when no branches were found.
> cli: report no updates to current branch

- tests/test_git_colocated.rs
I think this is the same bug as reported in #922, just simplified a bit further. The branches in the repo actually look good after the `undo` operation, but the reverted `master` branch doesn't get exported to the git repo even though our recorded `refs/heads/master` in the repo was moved back. Then the next automatic import on `log` notices that the `master` branch in the git repo still points to the new commit, and that commit becomes visible again.
If applicable:
> tests: demonstrate bug on undo after squash in colocated working copy

- CHANGELOG.md
- docs/config.md
- lib/src/settings.rs
- src/commands/mod.rs
- src/config/colors.toml
- src/template_parser.rs
- src/templater.rs
- tests/test_alias.rs
- tests/test_commit_template.rs
- tests/test_init_command.rs
- tests/test_log_command.rs
- tests/test_obslog_command.rs
- tests/test_revset_output.rs
The above screenshot is now slightly out of date. It's affected by a (no longer present) bug where the ids ended up 10 characters long instead of 12.
This is now rebased on top of @yuja's work. Thanks Yuya, working with the templater is so much more pleasant now!
Some of this is preparation for making the length of the short prefix configurable. I think this would work neatly
with the now-existing support for per-repository settings. 
It should also be quite doable to highlight prefixes in messages outside `jj log` (e.g. in output of `jj duplicate`).
If applicable:
> Highlight unique prefix for each id by showing the rest of it in gray

- src/commands/config-schema.json
This config option was recently added in #1051 (and later renamed from .format to .style), but never added to the schema.
If applicable:
> Add ui.graph.style into config schema

- src/template_parser.rs
- src/templater.rs
> templater: migrate trivial commit keywords to closure wrapper

- src/cli_util.rs
- src/commands/mod.rs
- src/config.rs
- tests/test_config_command.rs
Accept an --include-defaults arg to enable including those.
Listing a nonexistent name is no longer an error, but does output a warning to stderr when no config entries match to explain why there's no other output.
This is another "config list" improvement related to #531.
If applicable:
> Don't output implicit defaults from "config list"

- CHANGELOG.md
- src/commands/config-schema.json
- src/commands/git.rs
- tests/test_git_fetch.rs
The "--remote" option can be repeated, and the "git.fetch" key is now a list.
This would close #1162. I'm not sure I like the asymetry between the "git.push" configuration key, which is a string, and the "git.fetch" one, which is a list. But I understand the need to fetch from several remotes.
If applicable:
> git fetch: accept several remotes

- src/cli_util.rs
We classified all errors from initialization as "The target repo already exists". That's incorrect when the error came from the backend.
If applicable:
> init: provide more info when init fails

- src/cli_util.rs
- src/commands/mod.rs
It's apparently spelled without the second "e".
If applicable:
> cli: fix typo in "rewriteable"

- src/config/colors.toml
It's hard to read dark blue on black, at least with iTerm2's default color scheme. Cyan makes it much more readable. That's the color `cargo` uses. We could also consider coloring only the "Hint:" part like `cargo` does. For errors, `cargo` colors the "Error:" part red and uses bold/bright white for select parts of the message.
If applicable:
> cli: make hints cyan instead of blue

- src/template.pest
- src/template_parser.rs
- src/templater.rs
- tests/test_templater.rs
> templater: add parsing rule for integer literal, add i64 property

- src/templater.rs
Option<P> allows us to embed optional argument property in tuple.
let maybe_arg = maybe_pair.map(|pair| parse(...))?;
chain_properties((self, maybe_arg), |_: &(Context, Option<_>)| ...)
For one optional argument, we can instead switch the property functions:
if let Some(pair) = maybe_pair {
let arg = pair.map(|pair| parse(...))?;
chain_properties((self, arg), |_: &(Context, _)| ...)
} else {
chain_properties(self, |_: &Context| ...)
}
If we have various combinations of optional arguments, using Option<P> would be better.
If applicable:
> templater: add generic wrappers for Option<TemplateProperty>

- CHANGELOG.md
- docs/config.md
- lib/src/settings.rs
- src/commands/mod.rs
- src/config-schema.json
- src/template_parser.rs
- src/templater.rs
- tests/test_commit_template.rs
- tests/test_log_command.rs
The code is a little messy, so this is partially an RFC.
The new option is `ui.log-id-preferred-length`. Setting it to 6
is quite convenient for the `jj` repo, for example. Picture:
If applicable:
> `jj log`: option to specify preferred id length

- CHANGELOG.md
- src/cli_util.rs
- src/commands/mod.rs
- tests/test_checkout.rs
- tests/test_new_command.rs
- tests/test_rebase_command.rs
Eventually, we should be able to rely on `jj op restore` and the ~`--multi`~ (**Update:** `--allow-large-revsets`)
argument should likely be removed. This is a temporary measure until we figure
out https://github.com/martinvonz/jj/issues/922 and the like.
Fixes https://github.com/martinvonz/jj/issues/571
If applicable:
- (N/A) I have updated the config schema (src/commands/config-schema.json)
> `jj rebase` and `jj new`: Allow revsets with multiple commits with new `--allow-large-revsets` argument 

- src/commands/mod.rs
It was already mentioned towards the end of the introductory text, but that's easy to miss.
> Document the fact that `jj rebase` accepts multiple `-d`

- src/template_parser.rs
- tests/test_log_command.rs
This makes them print the shortest unique prefix only.
As discussed in https://github.com/martinvonz/jj/pull/1182#discussion_r1096940258
> Templater: make `shortest` id functions default to 0 length

- tests/test_log_command.rs
The unique-prefixe tests are typically the slowest tests. Here's the end of my `cargo nextest --workspace` output (from an arbitrary run, not best-of-5 or anything):
PASS [   5.129s] jujutsu::test_log_command test_log_prefix_highlight_brackets
PASS [   5.220s] jujutsu::test_log_command test_log_prefix_highlight_styled
PASS [   8.523s] jujutsu::test_log_command test_log_prefix_highlight_counts_hidden_commits
These tests create 50-100 commits in a loop. I think much of it comes from the subprocessing and/or the repeated loading of the repository in the subprocesses. Rewriting them to use `jj duplicate` for creating many commits at once speeds them up. Here are the timings after:
PASS [   2.323s] jujutsu::test_log_command test_log_prefix_highlight_styled
PASS [   2.330s] …
> tests: reduce subprocessing in unique-prefix tests

- src/commands/mod.rs
- src/template_parser.rs
- src/templater.rs
- tests/test_log_command.rs
> templater: reorganize shortest*() methods

- CHANGELOG.md
- src/commands/mod.rs
- tests/test_new_command.rs
I probably missed helper functions that would have made the code prettier. The discussion is in #1155.
If applicable:
> Add `--insert-after` and `--insert-before` to `jj new`

- CHANGELOG.md
- docs/config.md
- src/config-schema.json
- src/config/merge_tools.toml
- src/merge_tools.rs
> expand $left/$right in edit-args, replace all $variable matches

- docs/revsets.md
- lib/src/revset.pest
- lib/src/revset.rs
- tests/test_revset_output.rs
> revset: parse keyword arguments, accept remote_branches(remote=needle)

- CHANGELOG.md
- src/template_parser.rs
- tests/test_templater.rs
I haven't used a proper email address parser as I'm not really sure if it's worth the extra dependency and effort -- thoughts?
If applicable:
> `author`/`committer` templates: add a `username` method

- CHANGELOG.md
- docs/config.md
- lib/src/settings.rs
- src/commands/mod.rs
- src/config-schema.json
- tests/test_log_command.rs
Supported values are,
- `none` for no author information,
- `full` for both the name and email,
- `name` for just the name,
- `username` for username part of the email,
- (default) `email` (or any other gibberish for that matter) for the full email.
If applicable:
> config: add and parse `ui.log_author_format` in the default template

- CHANGELOG.md
- lib/src/git.rs
- tests/test_git_fetch.rs
I have verified that the new test fails before this patch is installed.
This allows a remote to remove a branch "foo" and create a branch "foo/bar". Otherwise, git2 attempts to create the "foo/bar" file t store the head of the branch before removing the "foo" one.
If applicable:
> git fetch: prune old branch names before adding new ones

- src/cli_util.rs
`jj log | head` consistently prints "Error: Broken pipe" for me. I don't know how the output gets printed after the pipe has been closed, but neither `git` nor `hg` prints an error, so I think we shouldn't either.
If applicable:
> cli: don't print error about broken pipe

- src/commands/operation.rs
I find it easier to read the code without the closure and the extra indentation. Instead, leverage `formatter.labeled()`.
If applicable:
> cli: avoid a closure in `op log` code for printing timestamp

- CHANGELOG.md
- docs/config.md
- lib/src/settings.rs
- src/cli_util.rs
- src/config-schema.json
- src/config/templates.toml
- src/template_parser.rs
- src/templater.rs
- tests/test_commit_template.rs
- tests/test_log_command.rs
- tests/test_show_command.rs
> cli: remove config knobs to customize log/show output, suggest template aliases instead

- CHANGELOG.md
- docs/config.md
- docs/config.toml
- lib/src/settings.rs
- src/commands/operation.rs
- src/config-schema.json
- tests/test_concurrent_operations.rs
- tests/test_operations.rs
This seems like a better default for `jj op log`, which is now the only thing this option affects.
If applicable:
> Rename `ui.relative-timestamps` to `ui.oplog-relative-timestamps`, make it default to `true`.

- docs/config.md
Now that we use headers to define `[template-aliases]`, I thought we should explain how they are also equivalent to dotted keys.
Alternatively, we could rewrite them all in the dotted style, but it would look awkward.
If applicable:
> `config.md`: expand on equivalence of headers and dotted keys

- .github/workflows/release.yml
The 0.7.0 release build failed because it didn't find OpenSSL. I don't know much about musl, but I think we added it in order to get a single binary without dependencies, so I think vendoring is what we want.
If applicable:
> release: build Linux (musl) release using vendored OpenSSL

- lib/src/tree.rs
Modify/delete conflicts cannot be automatically resolved, so there's no point in wasting resources calculating the diff(s).
If applicable:
> tree: return early when trying to resolve modify/delete conflict

- lib/src/backend.rs
- lib/src/conflicts.rs
- lib/src/git_backend.rs
- lib/src/local_backend.rs
- lib/src/protos/store.proto
- lib/src/protos/store.rs
- lib/src/tree.rs
- lib/tests/test_conflicts.rs
- lib/tests/test_merge_trees.rs
- lib/tests/test_working_copy.rs
It took a while before I realized that conflicts could be modeled as simple algebraic expressions with positive and negative terms (they were modeled as recursive 3-way conflicts initially). We've been thinking of them that way for a while now, so let's make the `ConflictPart` name match that model.
If applicable:
> Rename `ConflictPart` to `ConflictTerm`

- CHANGELOG.md
- src/commands/git.rs
- tests/test_git_push.rs
Right now, `--deleted` is exclusive of other options, as `--all` is. Should `--deleted` be allowed along with `--all` or `-b` and add to the list of branches in the second situation?
If applicable:
> git push: add --deleted option

- CHANGELOG.md
- src/commands/mod.rs
- tests/test_restore_command.rs
Fixes https://github.com/martinvonz/jj/issues/1228
If applicable:
> cmd: Make `jj restore` (without `--from`) work if `@` is a merge commit 

- CHANGELOG.md
- lib/src/index.rs
- src/commands/mod.rs
- tests/test_rebase_command.rs
This is two-thirds of #1158. (Though, these thirds are likely simpler than the last third)
One application (not the prettiest, but useful until we have `jj sync` at least):
jj rebase -s oldmain+~:main -d main -L
If applicable:
> Allow `jj rebase` to take multiple `-s` or `-b` args

- lib/src/index.rs
- Calling `.into_iter()` on an iterator is a no-op.
- There is no need to wrap index entries into another type to unwrap them right after sorting.
`.sort_unstable_by_key()` could probably be used instead of `.sort_by_key()` here but I'm not familiar enough with this part of the code to confidently change that.
If applicable:
> style: simplify topo_order()

- CHANGELOG.md
- lib/src/git.rs
- lib/tests/test_git.rs
- src/commands/git.rs
- tests/test_git_fetch.rs
The main contribution here are the detailed tests.
There is an outstanding bug with the way `undo` interacts with `jj git fetch --branch`.
Todo:
> cmd: `--branch` option for `git fetch`.

- tests/test_git_fetch.rs
Using the same commit id in multiple remotes makes it harder to see what comes from where.
If applicable:
> test_git_fetch: use different commit ids in different remotes

- CHANGELOG.md
- src/commands/git.rs
- tests/test_git_fetch.rs
Fixes #1308
The problem came from the fact that git refs were not synchronized with the remote branches: removing a remote branch (for example, while removing a remote, let's say branch "main@origin") didn't remove the corresponding git ref (for example "refs/remotes/origin/main"). When re-adding the same remote and re-fetching from it, since the git ref did exist already locally no remote branch was added.
If applicable:
> Sync git refs

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/cli_util.rs
- src/commands/mod.rs
- tests/common/mod.rs
- tests/test_config_command.rs
Uses toml_edit to support simple config edits like:
`jj config set --repo user.email "somebody@example.com"`
Fixes #531.
If applicable:
> Implement "config set" subcommand

- CHANGELOG.md
- docs/config.md
- src/config/templates.toml
- src/template.pest
- src/template_parser.rs
- tests/test_branch_command.rs
- tests/test_checkout.rs
- tests/test_commit_command.rs
- tests/test_commit_template.rs
- tests/test_concurrent_operations.rs
- tests/test_duplicate_command.rs
- tests/test_edit_command.rs
- tests/test_git_colocated.rs
- tests/test_git_fetch.rs
- tests/test_log_command.rs
- tests/test_move_command.rs
- tests/test_new_command.rs
- tests/test_operations.rs
- tests/test_split_command.rs
- tests/test_squash_command.rs
- tests/test_templater.rs
- tests/test_unsquash_command.rs
- tests/test_workspaces.rs
~This basically makes the template syntax more Mercurial-like.  The main difference is that the top-level node isn't a string, but an expression.~
The goal is to eliminate the implicit concatenation rule: `"foo" "bar"`.
If applicable:
> templater: add concat() and infix concatenation operator

- docs/git-compatibility.md
Issues #65 and #87 were both fixed almost a year ago.
If applicable:
> docs: Update section about support for .gitignores

- lib/src/git.rs
- lib/tests/test_git.rs
- src/commands/git.rs
- tests/test_git_fetch.rs
This patch series implements what is necessary to selectively import git references into jj. The first part was implemented by @ilyagr one week ago (avoid fetching uninteresting heads from a remote repo), and this is the second part, which also fixes some bugs:
- `jujutsu_lib::git::import_some_refs()` does the same thing as `git/import_refs()` but ignores all references not matched by a filter. Ignored references will never cause a branch to be added, moved, or deleted in the jj repo. We could merge the functions, but that will be a backwards incompatible change.
- `jujutsu_lib::git::fetch()` uses `import_some_refs()` when filtering is required. A trace has been let in if at some points the regex built from the globs must be analyzed/optimized.
The `CHANGELOG.md` file was not updated, as …
> Import refs with filter

- src/template.pest
My jjconfig is otherwise all indented with tabs and it helps for my
template-aliases to be indented the same way too.
If applicable:
> template: allow tab as whitespace as well

- Cargo.lock
- Cargo.toml
- lib/src/revset.pest
- lib/src/revset.rs
- src/template.pest
- src/template_parser.rs
> revset, template: clean up whitespace rule, parse "\t" and "\r"

- CHANGELOG.md
- lib/src/commit.rs
- lib/src/repo.rs
- src/commands/git.rs
- tests/test_git_push.rs
As discussed on discord: `jj git push` should not push `@-` unless `@` is empty.
*Edit:* a previous version used the `if_chain` crate but this is really not necessary here.
If applicable:
> git push: do not consider @- if @ is not discardable

- src/commands/mod.rs
Until https://github.com/clap-rs/clap/issues/1553 is fixed, I don't think we can do better than alphabetical order (without a lot of work).
If applicable:
> cli: print commands in alphabetical order

- docs/templates.md
- src/cli_util.rs
- src/commands/mod.rs
- src/commit_templater.rs
- src/formatter.rs
- src/template_parser.rs
- src/templater.rs
- src/text_util.rs
- tests/test_templater.rs
TBD: template function syntax (see also the last commit)
* `fill(width, content)` (weird to add optional parameters)
* `fill(content, width)` (hard to read for lengthy content)
* `template`|`string.fill(width)` (method)
If applicable:
> templater: add text wrapping function

- docs/templates.md
- src/template_builder.rs
- src/template_parser.rs
- src/time_util.rs
- tests/test_templater.rs
> templater: cache default time format, add timestamp.format() method

- src/template_builder.rs
- src/template_parser.rs
- tests/test_templater.rs
> templater: merge parse error variants (prepare for `.map(|x| ...)` expression)

- CHANGELOG.md
- src/diff_util.rs
- tests/test_diff_command.rs
- tests/test_log_command.rs
> Make `diff --types` show diff summary as two states

- docs/tutorial.md
Update the tutorial document to refer to the right commit for the working copy.
> Seems like it's referring to the wrong commit?

- lib/src/default_index_store.rs
- lib/src/default_revset_engine.rs
- lib/src/default_revset_graph_iterator.rs
- lib/src/revset.rs
- lib/src/rewrite.rs
- lib/tests/test_default_revset_graph_iterator.rs
- lib/tests/test_revset.rs
- src/commands/mod.rs
> Make revsets iterate over CommitId instead of IndexEntry

- lib/src/diff.rs
When inline changes happen to change just a portion of some multi-byte character, the diff displays changed bytes instead of changed grapheme clusters. This rectifies that.
> Make diffs operate on extended grapheme clusters

- .github/workflows/dependabot.yml
I apparently forgot to update the name when I copied `build.yml`.
If applicable:
> github: fix name of workflow for Dependabot auto-merge

- src/cli_util.rs
- src/config/misc.toml
- src/ui.rs
- tests/test_global_opts.rs
I actually wanted to make `(unset LESS; PAGER=less jj help)` work like it does with git (it seems to set `LESS` to something including `R` if it's not already set) but it got a bit messy. Maybe I'll get back to it later.
If applicable:
> cli: move default ui.pager config to misc.toml

- docs/design/git-submodules.md
Add `docs/technical/git-submodules.md` to capture how we think about submodules, starting with (IMO) the least controversial parts:
- Goals
- A roadmap that provides incremental value
The doc isn't complete, we will add more details and discuss them as they come, e.g. there are no designs yet.
Contributes to https://github.com/martinvonz/jj/issues/494
If applicable:
> docs/technical: add an aspirational Git submodules doc

- CHANGELOG.md
- docs/revsets.md
- lib/src/default_revset_engine.rs
- lib/src/revset.rs
- lib/tests/test_revset.rs
- tests/test_revset_output.rs
The `heads()` revset function with one argument is the counterpart to `roots()`. Without arguments, it returns the visible heads in the repo, i.e. `heads(all())`. The two use cases are quite different, and I think it would be good to clarify that the no-arg form returns the visible heads, so let's split that out to a new `visible_heads()` function.
If applicable:
> revset: split out no-args `head()` to `visible_heads()`

- CHANGELOG.md
- src/commands/mod.rs
- tests/test_squash_command.rs
This prevents an editor opening, and is useful in scripts/tests.
If applicable:
- N/A I have updated the config schema (src/config-schema.json)
> `squash`/`amend`: Add `-m` argument to set description

- CHANGELOG.md
- src/commands/branch.rs
- tests/test_branch_command.rs
Such branches lead to confusing errors on git expoert or push.
I didn't go through the trouble of changing the "cannot rewrite the root commit" message.
If applicable:
> cmd: prohibit creating branches at the root commit

- CHANGELOG.md
- src/progress.rs
With this change, the output looks like this:
```
3% 165.9 Mi at  13.4 MiB/s [█▋                                                   ]
```
Closes #1483.
If applicable:
> cli: include total downloaded size in progress output

- CHANGELOG.md
- docs/revsets.md
- lib/src/default_revset_engine.rs
- lib/src/revset.rs
- lib/tests/test_revset.rs
- testing/bench-revsets-git.txt
This adds `conflicts()` revset that selects commits with conflicts. We may want to extend it later to consider only conflicts at certain paths.
If applicable:
> revset: add a revset function for finding commits with conflicts

- Cargo.lock
- Cargo.toml
- build.rs
- src/cli_util.rs
- src/commands/mod.rs
- tests/test_global_opts.rs
This changes the version number reported by `jj version` from "0.7.0" to something like
"0.7.0-24a512683bc921699575b6a953624b05c068d544a". The hash is added if running in a jj repo or a git repo.
If applicable:
> cli: include commit id from build in version

- lib/src/default_revset_engine.rs
- lib/tests/test_revset.rs
- testing/bench-revsets-git.txt
> revset: remove use of expression builder API from engine, optimize children/dag-range/roots query

- build.rs
After #1493, the hash becomes colored if jj is used to get it at build time and the user configured `color="always"` in jj's config.
If applicable:
> Fixup to ed0b23d: make build.rs not insert color

- tests/common/mod.rs
- tests/test_concurrent_operations.rs
- tests/test_global_opts.rs
- tests/test_operations.rs
The current use of `timestamp.ago()` in the default template makes the tests depend on the current time, which they shouldn't.
If applicable:
> tests: use absolute timestamps in the operation log

- CHANGELOG.md
- docs/config.md
- docs/templates.md
- src/commit_templater.rs
- src/config-schema.json
- src/config/colors.toml
- src/config/templates.toml
- src/formatter.rs
- tests/test_commit_template.rs
- tests/test_obslog_command.rs
This PR has two separate features:
- Support for a "normal" color in the formatter that can override the color of a parent's style.
- Obsolete commits are now labeled as such. This can be useful when, e.g., doing `jj log commit_id`.
If needed, I can split this into two PRs (this may require changing the styling of obsolete commits).
Here is an example of test of `jj obslog` (note: the underlines were later removed):
`jj log`:
<details><summary>Previous version for comparison</summary>
</details> 
I also considered the wording `(Was change_id)` or `change_id (old)`, but I settled on `change_id (obs)` + color.
If applicable:
> commit template/templater/formatter: Label obsolete commits

- docs/config.md
I know that for support reasons, you've preferred documenting the use of `~/.jjconfig.toml` on all platforms (https://github.com/martinvonz/jj/commit/96849da332c809041040371b55eb5b4aaf097330), but as a new user on macOS, I was confused why the alternative `~/.config/jj/config.toml` wasn't working for me and had to dive into the source code.
The value table is borrowed from the upstream dirs library documenation:
- https://docs.rs/dirs/5.0.0/dirs/fn.config_dir.html
Related to https://github.com/martinvonz/jj/commit/0f5e360d96aef041806a89d8e21ab07a0a89545f and https://github.com/martinvonz/jj/issues/233
If applicable:
> docs: explicitly list the platform-specific config paths

- CHANGELOG.md
- README.md
- flake.nix
- src/commands/mod.rs
- tests/test_util_command.rs
I wasn't quite happy with `jj support` but I couldn't think of anything better when I moved the commands from `jj debug` in e2b4d7058daa. Thanks to @ilyagr for suggesting `jj util`.
If applicable:
> cli: rename `jj support` to `jj util`

- CHANGELOG.md
- src/commands/git.rs
- src/config/misc.toml
- tests/test_git_fetch.rs
A simple quick implementation of what I've suggested on discord
If applicable:
I've actually didn't find tests for `jj git push --remote`, so I didn't adjust them, hm
> cmd: when a single remote is defined, default to it for git fetch/push

- CHANGELOG.md
- docs/config.md
- src/cli_util.rs
- src/commands/mod.rs
- src/config-schema.json
- tests/test_alias.rs
- tests/test_global_opts.rs
This is a convenience optimization to improve the default user experience, since `jj log` is a frequently run command. Accessing the help information explicitly still follows normal CLI conventions, and instructions are displayed appropriately if the user happens to make a mistake. Discoverability should not be adversely harmed.
Note that this behavior mirrors [what Sapling does](https://sapling-scm.com/docs/overview/smartlog), where `sl` will display the smartlog by default.
If people are onboard with this change, where else would you recommend that the behavior be documented?
If applicable:
> cli: default to log when no subcommand is provided

- docs/glossary.md
The need for a glossary came up on Discord today.
This needs some more work, but I think this is a good start. I'm still happy to update it if anyone has suggestions, of course. I haven't started sprinkling pointers to the glossary from other places, so users will only discover it by browsing the `docs/` directory.
If applicable:
> docs: add a glossary

- lib/src/default_index_store.rs
- lib/src/default_revset_engine.rs
- lib/src/index.rs
- lib/tests/test_index.rs
It no longer needs to be on the `Index` trait, thereby removing the last direct use of `IndexEntry` in the trait (it's still used indirectly in `walk_revs()`).
If applicable:
> index: remove entry_by_id() from trait

- CHANGELOG.md
- src/commands/mod.rs
Establishing a unique file extension for the temporary files created via `jj describe` helps to ensure that text editors can recognize the filetype and alter settings accordingly. This will open the door for an improved user experience, and allow for setting things like the appropriate text-width/rulers, syntax highlighting of the diff summary (see Git's [commit tree-sitter grammer](https://github.com/the-mikedavis/tree-sitter-git-commit)), easy toggling of the `JJ:` comment lines, etc.
I examined the behavior of filetype detection across a number of common text editors, and the most universally-support mechanism was to have a unique extension that does not include any periods. Meaning that namespacing via something like `.jj.txt` instead, won't always be detected due to inconsistent …
> cli: use a unique file extension for description tempfiles

- tests/test_git_push.rs
I think we should test actually performing the push when possible. I think I initially used `--dry-run` because I thought it wasn't possible to do local pushes with libgit2.
If applicable:
> tests: drop a few unnecessary `--dry-run` from tests

- src/cli_util.rs
- src/commands/mod.rs
- src/main.rs
It should be up to the binary to decide which version it is. One should be able to build the library without specifying a version.
If applicable:
> cli: move `$JJ_VERSION` out of CLI library

- src/config/colors.toml
- src/config/templates.toml
- tests/test_commit_template.rs
- tests/test_operations.rs
This way you can do `jj log -T 'default_log_template + "\n"'` to add a blank line between commits.
If applicable:
> templates: extract default template to an alias

- lib/src/default_revset_engine.rs
- lib/src/revset.rs
- lib/tests/test_revset.rs
> revset: add substitution rule for `roots+++` (but no fast evaluation yet)

- docs/design/git-submodule-storage.md
- docs/design/git-submodules.md
(I really didn't want to write another doc, but I couldn't find a better way to organize my thoughts)
See the doc for details.
A previous, RFC version proposed several candidates and use cases we want to support. Over the course of that discussion, it became clear that supporting non-Git backends was an important goal, which narrowed our options to a single approach, so now the doc just proposes that approach.
> docs/design: propose submodule storage approach

- lib/src/default_index_store.rs
- testing/bench-revsets-git.txt
> revset: fix slow ancestors query `:x--` in mergey history

- Cargo.lock
- lib/Cargo.toml
- lib/src/default_index_store.rs
- lib/src/default_revset_engine.rs
- testing/bench-revsets-git.txt
> revset: do not scan ancestors more than once to evaluate nested children

- tests/test_diff_command.rs
- tests/test_edit_command.rs
> Fix warnings in tests on non-Unix platforms

- src/cli_util.rs
`workspace_root` is [canonicalized](https://github.com/martinvonz/jj/blob/41a2855b4fd84d8811d295dcaa0ea0aa0d5be171/lib/src/workspace.rs#L119), but `cwd` [isn't](https://github.com/martinvonz/jj/blob/41a2855b4fd84d8811d295dcaa0ea0aa0d5be171/src/cli_util.rs#L581). When [working with relative paths](https://github.com/martinvonz/jj/blob/41a2855b4fd84d8811d295dcaa0ea0aa0d5be171/src/cli_util.rs#L749-L760), this leads to issues in Windows: canonicalized paths start with `\\?\`, whereas non-canonicalized paths do not. Therefore, paths were formatted canonicalized, and commands did not accept non-canonicalized paths:
```
$ jj st
Parent commit: bdb62c926e75 canonicalize cwd in cli_util.rs
Working copy : 059c104379cd (no description set)
Working copy changes:
A …
```
> Fix relative paths on Windows

- Cargo.lock
Motivated by including https://github.com/gyscos/zstd-rs/commit/22e359a53f4b577a45ae28bed6a1717c1b0fb6a9, which makes it easier to package jj with a prebuilt libzstd. Not sure why dependabot didn't get this.
> cargo: bump zstd-sys from v2.0.1+zstd.1.5.2 to v2.0.8+zstd.1.5.5

- flake.lock
When combined with https://github.com/martinvonz/jj/pull/1577, enables use of a prebuilt libgit2.
If applicable:
> nix: update nixpkgs for libgit2 1.6

- flake.nix
Requires https://github.com/martinvonz/jj/pull/1578 for prebuilt libgit2 to be accepted by the current version of libgit2-sys (which will otherwise happily vendor away).
> nix: use packaged builds of foreign dependencies

- docs/revsets.md
We currently say that `x..y` is "Ancestors of `y` that are not also ancestors of `x`, both inclusive.". However, it's easy to think that "both inclusive" means that both `x` and `y` are included in the set, which is not the case. What we mean is more like "{Ancestors of `y`, including `y` itself} that are not also {ancestors of `x`, including `x` itself}.". Given that we already define ancestors and descendants as being inclusive on the lines above, and we also give the equivalent expressions using the `x:` and `:y` operators, it's probably best to just skip the "both inclusive" parts.
If applicable:
> docs: don't say "both inclusive" about `x:y` and `x..y` revset endpoint

- flake.nix
Forgot this in #1577. Quality of life improvement for anyone using the flake's dev shell.
> nix: use packaged foreign dependencies in dev shell

- flake.nix
I'm not sure if the macOS dependencies make sense either, but I don't have a mac to test on so I'm leaving them alone.
> nix: remove unnecessary dependencies

- Cargo.lock
- lib/Cargo.toml
- lib/src/lock.rs
- lib/src/lock/fallback.rs
- lib/src/lock/unix.rs
This should completely prevent painful silent timeouts when there's a stale lockfile (e.g. due to ^C on a prior long running operation) on *nix.
I pulled in `rustix` for this because we already indirectly depend on it in a couple places, so the nice ergonomic API is more or less free. Could be trivially swapped out for raw `libc` in the future if we trim things down otherwise.
> lib: use advisory locks on Unix targets

- docs/git-comparison.md
IIUC, the consensus in the Git project is that the overloaded nature of `git checkout` for many use cases was a mistake, and `git switch/restore` are meant to replace it.
If applicable:
> docs: use `git switch/restore` in command-equivalence table

- CHANGELOG.md
- lib/src/git.rs
- lib/tests/test_git.rs
- tests/test_git_colocated.rs
> git: on external HEAD move, do not abandon old branch

- src/progress.rs
Following [this discussion](https://discord.com/channels/968932220549103686/969829516539228222/1105304374584025251) on Discord, this trims the output of the snapshot progress messages so that they can be cleared correctly.
> trim snapshot progress output

- tests/test_git_colocated.rs
> Fix the `test_git_colocated_fetch_deleted_branch` test

- CHANGELOG.md
- docs/config.md
- lib/src/default_revset_engine.rs
- lib/src/id_prefix.rs
- lib/src/lib.rs
- lib/src/revset.rs
- lib/src/settings.rs
- lib/tests/test_id_prefix.rs
- lib/tests/test_revset.rs
- src/cli_util.rs
- src/commands/mod.rs
- src/commit_templater.rs
- src/config-schema.json
- tests/test_commit_template.rs
- tests/test_log_command.rs
- tests/test_obslog_command.rs
> Use shorter ID prefixes in configured revset

- examples/custom-backend/main.rs
- lib/src/backend.rs
- lib/src/git_backend.rs
- lib/src/local_backend.rs
- lib/src/store.rs
- lib/tests/test_commit_builder.rs
- lib/tests/test_revset.rs
> Let backend return possibly adjusted commit on write

- src/commands/mod.rs
- tests/common/mod.rs
These are a couple of tools I made to help with debugging #864. I was only partially successful, but I think they can be useful regardless.
> Add a couple of tools to help with debugging integration tests

- CHANGELOG.md
- docs/git-compatibility.md
- lib/src/git.rs
- lib/tests/test_git.rs
- tests/test_git_colocated.rs
Fixes #864 ("In a git colocated repo, commits are not rebased off of a deleted/moved branch")
**Update:** Some technical details from the commit description:
> This bug concerns the way `import_refs` that gets called by `fetch` computes
> the heads that should be visible after the import.
> 
> Previously, the list of such heads was computed *before* local branches were
> updated based on changes to the remote branches. So, commits that should have
> been abandoned based on this update of the local branches weren't properly
> abandoned.
> 
> Now, `import_refs` tracks the heads that need to be visible because of some ref
> in a mapping keyed by the ref. If the ref moves or is deleted, the
> corresponding heads are updated.
If applicable:
- (n/a) I have updated the config schema …
> Fix #864 (fetching deleted/moved branches in colocated repos)

- lib/src/git_backend.rs
- lib/src/stacked_table.rs
- lib/tests/test_git.rs
> git_backend: add lock to prevent racy change id assignments

- lib/src/git_backend.rs
- lib/tests/test_git.rs
Follows up #1615 
If applicable:
> git_backend: on read_commit(), bulk-update extra metadata table of ancestors

- src/cli_util.rs
- src/commands/mod.rs
- tests/test_concurrent_operations.rs
> cli: reload both repo and wc commit if working copy was updated 

- CHANGELOG.md
- src/commands/mod.rs
- tests/test_sparse_command.rs
- tests/test_untrack_command.rs
`jj sparse` is a bit different from other commands in that its `jj sparse --list` is practically a separate command. Let's make it an actual subcommand for consistency, and so we can more cleanly add additional flags for `jj sparse list` in the future. I moved all the other arguments to `jj sparse set`. I'm not sure if `jj sparse set --reset` would have been better as `jj sparse reset`, but it is technically just updating the sparse patterns just like the other arguments (`--clear`, `--add` , `--remove`).
If applicable:
> cli: make `jj sparse --list` a subcommand

- lib/src/revset.rs
- src/cli_util.rs
- src/commands/mod.rs
I was testing out a codespell alternative for a separate project and thought I'd run it on the jj repo...
> error: `mutliple` should be `multiple`
> error: `visble` should be `visible`
Found via typos:
- https://github.com/crate-ci/typos
If applicable:
> cleanup: fix minor typos in function names

- lib/src/default_index_store.rs
- lib/src/default_revset_engine.rs
- lib/src/index.rs
- lib/src/repo.rs
- lib/tests/test_default_revset_graph_iterator.rs
- lib/tests/test_index.rs
- src/commands/mod.rs
> index: move `Index::as_any()` to `MutableIndex`, clean up references passed to revset engine

- lib/src/files.rs
- lib/src/merge.rs
- lib/src/tree.rs
I don't know why I made it return an owned value. It seems like an unnecessary restriction that the value implements `Clone`, so let's return a reference instead.
If applicable:
> merge: make `trivial_merge()` return a reference

- lib/src/protos/working_copy.proto
- lib/src/protos/working_copy.rs
- lib/src/working_copy.rs
This prepares for allowing the base tree to be a conflict at the root-tree level (#1624).
We could remove the `Conflict` variant completely. I tried doing that and it slowed down `jj diff` by ~3% in the Linux repo with a clean working copy with only mtime bumped on all files.
If applicable:
> working_copy: get conflict id from the current tree

- lib/src/revset.rs
- lib/tests/test_revset.rs
- tests/test_log_command.rs
I made a typo and got something like this:
```
Error: Commit or change id prefix "wl" is ambiguous
```
Since we can tell commit ids from change ids these days, let's make the error message say which kind of id it is. Changing that also kind of forced me to make a special error for empty strings. Otherwise we would have to arbitrarily say that an empty string is a commit id or change id. A specific error message for empty strings seems helpful, so that's probably for the better anyway.
If applicable:
> revset: use different errors for ambiguous commit/change IDs

- Cargo.lock
- Cargo.toml
- tests/test_alias.rs
- tests/test_global_opts.rs
I changed `test_early_args` because the first line no longer has a redundant color reset, so now we test the `Commands:` line instead, which has actual color (well, bold+underline anyway).
If applicable:
> cargo: upgrade `clap` from to 4.1.11 to 4.3.0

- SECURITY.md
Previously, the link wasn't working from Github's rendered markdown.
Another alternative is to add `malto:` to the link, which would make it work. However, I thought that since the email is the most important piece of information in the entire file, we should just write it out.
> SECURITY.md: show the email plainly

- CHANGELOG.md
- docs/config.md
- lib/src/settings.rs
- src/merge_tools.rs
Behold, instructionless diff editing:
If applicable:
> feat(diff): add `ui.diff-instructions` option to suppress `JJ-INSTRUCTIONS` file

- src/commands/debug.rs
- src/commands/mod.rs
- tests/test_debug_command.rs
- tests/test_git_import_export.rs
These are all no-op changes to make testing changes to `op restore` easier
If applicable:
- (n/a) I have updated `CHANGELOG.md`
> Make it easier for tests to refer to operation ids, move debug commands

- lib/tests/test_revset.rs
I opened a bug for the clippy error:
https://github.com/frondeus/test-case/issues/122
> test_revset.rs: disable clippy false-positive warning

- CHANGELOG.md
- lib/src/git.rs
- lib/src/revset.rs
- lib/tests/test_revset.rs
- src/commands/branch.rs
- tests/test_branch_command.rs
- tests/test_git_colocated.rs
- tests/test_git_fetch.rs
- tests/test_git_import_export.rs
Also demos `jj branch forget` behavior with git-tracking branches.
This addresses a portion of #1666 and also includes a commit describing
some nuanced behavior of `jj branch forget` in a test.
If applicable:
- [?] I have updated the documentation (README.md, docs/, demos/)
> Allow listing and resolving `@git` branches

- lib/src/git.rs
- lib/src/repo.rs
> git: make noop import_refs() fast

- examples/custom-backend/main.rs
- lib/src/git_backend.rs
- lib/src/repo.rs
- lib/src/workspace.rs
- lib/tests/test_git.rs
- lib/testutils/src/lib.rs
- src/cli_util.rs
- tests/test_init_command.rs
Before this commit, running `jj init --git-repo=./` in a folder that does not have a .git would cause jj to panick and leave an unfinished corrupted jj repo.
This commit fixes https://github.com/martinvonz/jj/issues/1305
This commit fixes that by changing the call chain to return an error instead of calling .unwrap() and panicking. This commit also adds logic to delete the unfinished jj repository when the git backend initialization failed.
Before this commit, running the above command would result in the following
```
Running `jj/target/debug/jj init --git-repo=./`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -3, klass: 2, message: "failed to resolve path '/Users/kevincliao/github/jj/test-repo/.jj/repo/store/../../../.git': No such file or …
```
> Fix `jj init --git-repo` fails and leaves broken .jj folder

- CHANGELOG.md
- src/commands/branch.rs
- tests/test_branch_command.rs
- tests/test_git_fetch.rs
- tests/test_git_import_export.rs
- tests/test_git_push.rs
This PR shares 3 commits with #1714, I will rebase whichever gets in first on top of the other.
Fixes #1537
If applicable:
> `branch` cli: additional tests and allow defusing deleted branches

- build.rs
- flake.nix
A few minor issues fixed for nix:
- I've found out that after installing jj with `nix profile install` I have `fake-editor` and `fake-diff-editor` installed :) fixed it by making cargo only build the jj executable
- `jj -V` didn't include the commit hash when built/installed with Nix - I did a little env var hack as I'm not entirely sure why it didn't work - just adding git to build env didn't do it so I assume nix build removed the .git folder?.
- Installing through nix does run the tests and I've added `useNextest = true` bit to noticeably speed that up
- Added `rust-analyzer` to the dev shell as the nix way is to not have any dev tools installed globally and have them only be present in the flake - wanted to do that for a while and here's the opportunity.
If applicable:
> nix: dont install fake binaries and fix dirty jj version

- src/commands/branch.rs
- tests/test_branch_command.rs
@ilyagr, can you take a look?
If applicable:
> cli: say "(forgotten)" if branch is listed just because it's in git_refs

- lib/src/git.rs
> git: remove unused `push_commit()`

- CHANGELOG.md
- src/commands/mod.rs
- tests/test_sparse_command.rs
> add `--edit` option to `jj sparse set`

- lib/src/git.rs
- lib/tests/test_git.rs
- src/cli_util.rs
- src/commands/git.rs
- tests/test_git_submodule.rs
We'll need to read `.gitmodules` for most basic submodules operations. Add a simple `.gitmodules` parser, and verify it works by using a new debugging command `jj git submodule print-gitmodules` that reads `.gitmodules` from the working copy (revisions and operations not supported yet).
> Add .gitmodules parser

- docs/related-work.md
- docs/sapling-comparison.md
> docs: add doc comparing jj to Sapling (#1708)

- Cargo.lock
- src/cli_util.rs
> Upgrade clap to 4.3.9

- CHANGELOG.md
- lib/src/git.rs
- lib/src/op_store.rs
- lib/src/refs.rs
- lib/src/revset.rs
- lib/src/rewrite.rs
- src/commands/branch.rs
- src/commands/git.rs
- tests/test_branch_command.rs
> cli: add revset filter to "branch list"

- CHANGELOG.md
- lib/src/git.rs
- lib/src/revset.rs
- lib/tests/test_git.rs
- src/cli_util.rs
- src/commands/branch.rs
- tests/test_branch_command.rs
New approach to fix the bug described in the (now closed) PR #1714
If applicable:
> Fix bug where a forgotten branch couldn't be fetched (v2)

- CHANGELOG.md
- src/commands/operation.rs
- tests/common/mod.rs
- tests/test_git_colocated.rs
- tests/test_git_fetch.rs
- tests/test_git_import_export.rs
- tests/test_undo.rs
This is attempt number ~3-4 to fix #922 and is heavily based on #1541 (two more attempts happened as two versions of #1487). There is a long discussion in that PR, the plan for this PR specifically is discussed towards the end.
The first 2 commits are somewhat unrelated and could be moved to a separate PR. They add tests pertaining to the question of whether we should import/export remote-tracking branches by default in normal repos (see discussion in #1739). It is unfortunate that changes to import/export & git-tracking branches affect push and fetch. However, I thought it might be interesting which of these tests are and are not changed by this PR.
See also #1741 for what tests change if we have this behavior in non-colocated repos as well (making this equivalent to #1541).
This may …
> `jj op undo/restore` no longer restore git-tracking branches by default

- .github/dependabot.yml
This should reduce the number of PRs to review, and the number of uninteresting commits in the repo history.
If applicable:
> github: tell Dependabot to group all deps when possible

- lib/src/backend.rs
- lib/src/tree.rs
This is much simpler and I was slightly surprised that it doesn't have much impact on performance. I tried `jj --ignore-working-copy diff -s --from root --to v5.15` in the Linux kernel repo, and there was perhaps a 1.5% slowdown. In more normal cases (like diffing a single commit against its parent), I couldn't measure any difference at all.
If applicable:
> tree: simplify diff iterator by leveraging `Tree::value()`

- .github/dependabot.yml
It looks like I accidentally applied the grouping only to GitHub actions updates.
If applicable:
> dependabot: also group cargo updates

- lib/src/git.rs
- lib/src/view.rs
- src/cli_util.rs
> view: add default formatting to RefName, use it to print unexported branches

- lib/src/revset.rs
- lib/tests/test_revset.rs
- tests/test_branch_command.rs
> revset: don't resolve deleted branch symbol to empty set, suggest remote branches

- lib/src/dag_walk.rs
- lib/src/git.rs
- src/commands/branch.rs
This is (almost) a result of running
cargo +nightly clippy --workspace --all-targets --fix \
--  -A 'clippy::needless_raw_string_hashes'
with yesterday's nightly clippy.
https://github.com/mitsuhiko/insta/issues/389 causes numerous additional
`needless_raw_string_hashes` warnings, but it will hopefully be fixed soon.
For now, I recommend appending the second line to your invocations if you
use nightly clippy.
> clippy: fix nightly clippy warnings *except* for `needless_raw_string_hashes`

- .github/workflows/build.yml
- .github/workflows/release.yml
- flake.nix
Summary: When building in CI, we just build everything from scratch in the `dev` profile, so just turn off debuginfo and incremental compilation data. These aren't reused, but more importantly take up more space and CPU time to generate; that's more expensive on slower machines and when using The Cloud(TM) to build.
Together, these take a fresh build (`rm -rf target/` ahead of time) from about 40s to 30s on my machine.
> chore(github): reduce compile time in build, nix, and release workflows

- flake.nix
Summary: Nix packages tend to come "full extra pack of batteries"-included, so adding watchman support makes sense. I'll also want it for my own experiments.
> feat(nix): enable watchman support in nix package

- docs/git-comparison.md
`jj diff` works a bit differently to `git diff`, so add more examples of `jj diff` using `--from`.
> git-comparison: add more diff commands

- lib/src/rewrite.rs
It should no longer be needed since e3254fa5c412 "rewrite: don't rewrite the "removed" side of a branch conflict."
If applicable:
> rewrite: do not insert "removed" refs to reverse branch lookup table

- flake.lock
Summary: I need this for another change I'm playing around with, because the newer nixpkgs snapshot has a newer version of a tool. Just do a quick update to get it out of the way.
Maybe one day, Dependabot can help solve this issue...
> chore(nix): nix flake update

- lib/src/refs.rs
- lib/tests/test_refs.rs
- lib/tests/test_rewrite.rs
> refs: migrate `merge_ref_targets()` internals to new `Conflict` type

- lib/src/git.rs
- lib/src/repo.rs
- lib/src/view.rs
- lib/tests/test_git.rs
- lib/tests/test_mut_repo.rs
- lib/tests/test_revset.rs
- lib/tests/test_rewrite.rs
- lib/tests/test_view.rs
- src/cli_util.rs
- src/commands/branch.rs
- src/commands/git.rs
> view: pass `Option<RefTarget>` in to setter functions (prep for migration to `Conflict<T>`)

- flake.lock
- flake.nix
Follow up from #1833 since mold was mentioned. This basically makes all Linux builds faster at no cost; it takes re-linking time for `jj-cli` down to sub-1s for me in all cases in practice.
This is only enabled when `nix develop .` or `direnv` are used to hack on jj. Mold is not enabled for release packaging or builds in any other configuration. So, this is just a pure win for anyone using Nix, because we can ensure that everyone can rely on it.
**NOTE**: ~~This pull request is NOT ready to be merged. As @yuja noted in #1833, there is an upstream bug in mold wrt handling `--debug-strip` that causes *all* debug info to be stripped, killing `RUST_BACKTRACE` in all builds; luckily, the patch is trivial, and I backported it to nixpkgs in NixOS/nixpkgs#243384, which I merged this morning.~~ My …
> feat(nix): use mold by default for linking inside 'nix develop'

- lib/src/git.rs
- lib/src/op_store.rs
- lib/src/refs.rs
- lib/src/rewrite.rs
- lib/src/simple_op_store.rs
- lib/tests/test_git.rs
- lib/tests/test_mut_repo.rs
- lib/tests/test_refs.rs
- lib/tests/test_revset.rs
- lib/tests/test_rewrite.rs
- lib/tests/test_view.rs
- src/cli_util.rs
- src/commands/branch.rs
- src/commands/git.rs
- src/commands/mod.rs
> refs: don't rely on `RefTarget` enum API

- lib/src/git.rs
- lib/src/op_store.rs
- lib/src/refs.rs
- lib/src/repo.rs
- lib/src/revset.rs
- lib/src/rewrite.rs
- lib/src/simple_op_store.rs
- lib/src/view.rs
- lib/tests/test_git.rs
- lib/tests/test_refs.rs
- lib/tests/test_rewrite.rs
- lib/tests/test_view.rs
- src/cli_util.rs
- src/commands/branch.rs
- src/commands/git.rs
- src/commands/mod.rs
- src/commands/operation.rs
- src/commit_templater.rs
> refs: reimplement `RefTarget` as `Conflict<Option<CommitId>>` wrapper

- src/commands/mod.rs
We upgraded to clap 4.1 in 8f1dc490 (cargo: upgrade to clap 4.1, 2023-03-17), and the pipe to `sed` was removed in the README.md file in that same commit. However the documentation was not updated in mod.rs, which leads us to give the obsolete (now incorrect) advice when we run `jj util completion --help`.
See #1393.
If applicable:
> fix zsh completion guidance

- lib/src/protos/working_copy.proto
- lib/src/working_copy.rs
Slows down `jj diff` by ~3% in the Linux repo with a clean working copy with all mtimes bumped.
If applicable:
> working_copy: don't track conflict-ness in state file, use tree object

- lib/src/working_copy.rs
- lib/tests/test_working_copy_concurrent.rs
We don't seem to have any tests that our protection from undetected changes caused by writes happening right after checkout, so let's add one. The test case loops 100 times and each iteration fails slightly more than 80% of the time on my machine (if I remove the protection in `TreeState::update_file_state()`), so it seems quite good at triggering the race.
If applicable:
> working_copy: add test of racy checkout followed by file write

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/cli_util.rs
- src/commands/mod.rs
- src/config.rs
Addresses #1571.
`jj config edit --user` and `jj config set --user` will now pick a default config location if no existing is found.
Platform-specific config directory is preferred over the home directory.
> Allow editing non-existent configs

- src/cli_util.rs
- src/commands/debug.rs
This is to aid debugging in cases like #1907, where the operation object has an invalid view object.
If applicable:
> cli: make `jj debug operation --display operation` work with broken view

- CHANGELOG.md
- docs/config.md
- docs/github.md
- docs/revsets.md
- docs/tutorial.md
- examples/custom-command/main.rs
- lib/src/default_index_store.rs
- lib/src/default_revset_engine.rs
- lib/src/revset.pest
- lib/src/revset.rs
- lib/src/revset_graph.rs
- src/cli_util.rs
- src/commands/bench.rs
- src/commands/branch.rs
- src/commands/git.rs
- src/commands/mod.rs
- testing/bench-revsets-git.txt
- tests/test_abandon_command.rs
- tests/test_branch_command.rs
- tests/test_diff_command.rs
- tests/test_duplicate_command.rs
- tests/test_log_command.rs
- tests/test_rebase_command.rs
- tests/test_revset_output.rs
> Replace `--allow-large-revsets` by `all:` prefix

- CHANGELOG.md
- src/commands/git.rs
- tests/test_git_clone.rs
This adds the new `--colocate` flag to `jj git clone`.
```
jj git clone --colocate https://github.com/foo/bar
```
is effectively equivalent to:
```
git clone https://github.com/foo/bar
cd bar
jj init --git-repo=.
```
Closes #1873 
If applicable:
> Support the option of colocating a git repo with a jj repo

- .github/workflows/build.yml
We run a separate build on CI with the MSRV so we notice if we accidentally break the MSRV. However, as we talked about on Discord, the opposite is very unlikely - that we accidentally break the build with the stable release without breaking the MSRV build. Also, we explicitly run Clippy with the stable release, and formatting with the nightly release. So, let's just do the regular build and tests with the MSRV.
If applicable:
> github: run only with MSRV, not stable

- docs/config.md
- docs/github.md
- docs/revsets.md
- docs/tutorial.md
Since our latest release doesn't support `::`, we shouldn't tell the user to use it.
This commit should be backed out we've released jj 0.9.0.
If applicable:
> docs: revert to using revset operator `:` instead of `::`

- CHANGELOG.md
- src/commands/mod.rs
- tests/test_global_opts.rs
- tests/test_restore_command.rs
This argument can restore a merge commit to the merge of its parents. This allows one to apply the default behavior of `jj restore` to another commit. In other words, `jj restore` without arguments is equivalent to `jj restore -c @`. 
The title was "cmd: Add `-r` argument to `jj restore
The interface is now similar to `jj diffedit`, `jj diff`, etc.
If applicable:
> cli: New `--changes-in` argument to `jj restore`

- src/commands/git.rs
I use `--change` a lot and somehow still didn't think to add a short form until @ilyagr (?) mentioned it somewhere recently.
If applicable:
> cli: add short form `-c` for `jj git push --change`

- CHANGELOG.md
- docs/config.md
- lib/src/working_copy.rs
- src/cli_util.rs
- src/commands/mod.rs
- src/config-schema.json
- src/diff_util.rs
- src/merge_tools.rs
- testing/fake-diff-editor.rs
- tests/common/mod.rs
- tests/test_diff_command.rs
> cli: add option to generate textual diff by external command

- lib/src/workspace.rs
This change allows a custom jj binary to initialize a workspace with a workspace_id other than "default".
If applicable:
> Update init_with_factories to initialize a workspace with a workspace_id other than "default"

- src/commands/mod.rs
This adds the `run` command as described in the doc. The command is hidden for now, to allow in-tree development. 
The next steps are: 
1. Move it to `run.rs`
2. Find a good backend trait
3. Implement the workers
Initial progress on #1869 and #405
If applicable:
> commands: Add `run`.

- flake.nix
Summary: mold apparently breaks linking to several external libraries, meaning that the `jj` binary is useless as it can't load e.g. `libgit2.so` -- but somehow I didn't catch it. Backout until a solution can be pinpointed. We can at least give off a sigh of relief knowing that our link times aren't too bad yet.
Change-Id: I6e1851c339ddc72d32c201a44a7ddc49
If applicable:
> backout of commit e212e10deee96878236c12a565d99abcc18d2fcb

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- lib/gen-protos/Cargo.toml
- lib/testutils/Cargo.toml
This unifies crate dependencies between `jj-lib` and `jj-cli` under the top level `Cargo.toml` file, and transitions those crates to use `{ workspace = true }` instead to specify versions. All of the versions between the two crates were the same, so this just makes the whole thing less error prone.
The net effect here is that deps should just be added to the top level Cargo file, and using it in a package just specifies `workspace = true` and everything should work out. Note that the top-level Cargo file doesn't support `optional = true`; it only lists crate versions, whether or not a crate dependency is optional must still be specified in that crates' Cargo.toml (not the workspace version.)
As a nice side bonus, we can also now aggregate a lot of the metadata itself inside the top level …
> cargo: unify crate dependencies and metadata via workspace

- cli/src/merge_tools.rs
As far as I understand, the difftool is supposed to be readonly, so let's encourage people to no edit the files being diffed.
If applicable:
> merge_tools: make dirs readonly for external difftool

- CHANGELOG.md
- lib/src/git.rs
> git: only try to use ssh-agent once per connection (#1970)

- README.md
- docs/FAQ.md
This answers some questions, which were repeatedly asked in Discord.
[Rendered](https://github.com/martinvonz/jj/blob/push-wmvntxtmkkmm/docs/FAQ.md)
If applicable:
> Docs: Add a FAQ

- cli/src/cli_util.rs
- cli/src/commands/mod.rs
I don't have context for what was "unsafe" about this function to begin with, so thoughts on better names welcome.
If applicable:
> cli: don't call a safe function 'unsafe'

- CHANGELOG.md
- cli/src/commands/mod.rs
- cli/src/commands/operation.rs
- cli/tests/test_log_command.rs
- cli/tests/test_obslog_command.rs
- cli/tests/test_operations.rs
Copied from Mercurial. This isn't a revset predicate since our revset is conceptually unordered.
If applicable:
> cli: add "--limit N" option to log-like commands

- cli/src/commands/branch.rs
- cli/src/config/colors.toml
- cli/src/config/templates.toml
- cli/tests/test_abandon_command.rs
- cli/tests/test_chmod_command.rs
- cli/tests/test_duplicate_command.rs
- cli/tests/test_git_clone.rs
- cli/tests/test_init_command.rs
- cli/tests/test_move_command.rs
- cli/tests/test_new_command.rs
- cli/tests/test_rebase_command.rs
- cli/tests/test_resolve_command.rs
- cli/tests/test_restore_command.rs
- cli/tests/test_squash_command.rs
- cli/tests/test_status_command.rs
- cli/tests/test_unsquash_command.rs
This changes the short commit template and `jj status` to show which commits have branches at them.
I initially had branches come after the description (see "Older version" below), but I think it's more logical to put them next to the other names the commit can be referred by (change and commit id)
I also added a grey `|` before the branches, mostly so that one can tell apart the branches from the description without color (e.g. in tests).
The result looks like this (3rd version)
Some notes:
- The `|` seems vital when branches are shown and color is disabled (not to confuse them with the description), and showing it consistently looks better.
- I tried all the options of whether to have a space before or after the `|`. IMO, this looks best. Without a space before, the `|` blends together …
> Change the short commit template to show branches

- .envrc.recommended
- flake.lock
This is just some housekeeping while I was playing with Ilya's request in #2034; just runs `nix flake update` and in the process migrates us to use [nix-direnv](https://github.com/nix-community/nix-direnv), which is a faster and generally robust tool to replace the built in `use nix` in direnv. There is no need to install anything; the upgrade is atomic.
If applicable:
> nix: do some chores

- CHANGELOG.md
- cli/src/cli_util.rs
- cli/src/config-schema.json
- cli/src/config/misc.toml
- cli/src/ui.rs
- docs/config.md
This was a bit of a chance for me to play with `jj` a bit, so feel free to ignore 😄 
I was basically frustrated with having to pass in `--no-pager` constantly and stumbled upon this [PR](https://github.com/martinvonz/jj/pull/672) where I saw that a `ui.paginate` option was considered and [removed](https://github.com/martinvonz/jj/pull/672#discussion_r1035311775). I felt like adding it back might be a tiny, but helpful change for others like me.
If applicable:
> configs: add the ability to disable paging altogether via `ui.paginate`

- lib/src/default_index_store.rs
- lib/src/default_revset_engine.rs
- lib/tests/test_revset.rs
> revset: remove round-trip conversion from heads() evaluation

- README.md
- cli/src/cli_util.rs
- cli/src/commands/mod.rs
- cli/src/config.rs
- cli/tests/test_global_opts.rs
- docs/config.md
As the more conventional path, users should be directed this way preferentially.
> Update docs and errors to use XDG config path

- cli/src/commands/git.rs
- cli/tests/test_git_clone.rs
> cli: discard "unborn" default branch before checking out fetched head

- cli/src/config/colors.toml
- cli/src/diff_util.rs
- cli/tests/test_diff_command.rs
Empty files can be confusing in diff output. For example:
```
Added regular file file1:
Added regular file file2:
1: foo
```
This commit adds an "(empty)" placeholder instead. Since it's not colored, and doesn't have line numbers, it will hopefully not be mistaken for a file with the contents "(empty)".
If applicable:
> cli: indicate empty files in default diff format

- CHANGELOG.md
- cli/src/cli_util.rs
- cli/src/commands/mod.rs
- cli/tests/test_describe_command.rs
Emulates git's behavior:
https://www.git-scm.com/docs/git-commit#Documentation/git-commit.txt--mltmsggt
Fixes #1931 
If applicable:
_I didn't find anywhere obvious where this should be added_
_I don't believe this is needed as there are no configuration changes_
> Allow repeated `-m` options for multi-paragraph descriptions

- cli/src/commands/mod.rs
- cli/tests/test_describe_command.rs
> cli: trim the description from editor before using it

- cli/src/commands/git.rs
- cli/tests/test_git_push.rs
> cli: include hint when push is not fast-forward

- CHANGELOG.md
- cli/src/commit_templater.rs
- cli/src/config-schema.json
- cli/src/config/colors.toml
- cli/src/config/templates.toml
- cli/tests/test_alias.rs
- cli/tests/test_commit_template.rs
- cli/tests/test_diff_command.rs
- cli/tests/test_init_command.rs
- cli/tests/test_log_command.rs
- cli/tests/test_revset_output.rs
- docs/templates.md
The default template makes root look like this now:
If applicable:
> cli: hide irrelevant information about the root commit in default log templates

- cli/src/commands/git.rs
- cli/src/commands/mod.rs
- cli/tests/test_split_command.rs
- lib/src/settings.rs
> cli: respect `ui.default-description` in split as well

- lib/src/default_index_store.rs
Add type annotation to `vec` to avoid the following build error if you additionally import `bstr`:
```
~/jj> cargo test
Compiling jj-lib v0.8.0 (/home/aspotashev/jj/lib)
warning: unused import: `bstr`
--> lib/src/default_index_store.rs:30:5
|
30 | use bstr;
|     ^^^^
|
= note: `#[warn(unused_imports)]` on by default
error[E0282]: type annotations needed
--> lib/src/default_index_store.rs:564:14
|
564 |             .as_mut()
|              ^^^^^^
565 |             .write_u32::<LittleEndian>(parent_overflow.len() as u32)
|              --------- type must be known at this point
|
help: try using a fully qualified path to specify the expected types
|
563 |         <[u8] as AsMut<T>>::as_mut(&mut buf[parent_overflow_offset..parent_overflow_offset + 4])
| …
```
> Fix build when `bstr` is also imported.

- CHANGELOG.md
- cli/src/cli_util.rs
- cli/src/commands/debug.rs
- cli/src/commands/mod.rs
- docs/github.md
- docs/revsets.md
- lib/src/revset.rs
- lib/tests/test_revset.rs
`mine()` is an alias for `author([user.name])` per the specification given in #1976, although I wonder if it should instead act like `author([user.name]) | author([user.email])`.
If applicable:
> revset: add function mine()

- cli/src/config/colors.toml
- cli/tests/test_commit_template.rs
Bright green really pops on my screen, and I don't think there is a reason for the root commit to be attention-grabbing.
This follows up on https://github.com/martinvonz/jj/pull/2084.
If applicable:
> log template: make root commit green instead of bright green

- CHANGELOG.md
- Cargo.lock
- cli/src/cli_util.rs
- cli/src/commands/mod.rs
- cli/src/config-schema.json
- cli/src/config/misc.toml
- cli/src/merge_tools/external.rs
- cli/src/progress.rs
- lib/Cargo.toml
- lib/src/fmt_util.rs
- lib/src/lib.rs
- lib/src/settings.rs
- lib/src/working_copy.rs
- lib/tests/test_working_copy.rs
- lib/tests/test_working_copy_concurrent.rs
- lib/tests/test_working_copy_sparse.rs
- lib/testutils/src/lib.rs
Still needs a test (and test code updates), but impl should be in good shape for review/feedback.
Future work: similar behavior for binary files.
If applicable:
> Don't snapshot new files larger than 1MiB by default

- CHANGELOG.md
- cli/src/cli_util.rs
- cli/src/commands/git.rs
- cli/src/template_builder.rs
- cli/src/templater.rs
- cli/tests/test_commit_template.rs
- cli/tests/test_git_push.rs
- cli/tests/test_templater.rs
- lib/src/commit_builder.rs
- lib/src/git_backend.rs
- lib/src/settings.rs
- lib/tests/test_commit_builder.rs
- lib/tests/test_init.rs
https://github.com/martinvonz/jj/issues/2094. I went with `JJ_EMPTY_STRING` as the placeholder in `git`, because the word `PLACEHOLDER` seems redundant when you're already using SCREAMING_SNAKE_CASE.
If applicable:
> commits: use empty strings instead of placeholders for missing name or email

- docs/revsets.md
- lib/src/revset.rs
git-branchless calls it a substring, so let's do the same.
FWIW, I copied literal:_ from Mercurial, but it's exact:_ in git-branchless. I have no idea which one is preferred. Since this feature isn't released, we can freely change it if exact:_ makes more sense.
https://github.com/arxanas/git-branchless/wiki/Reference:-Revsets#patterns
If applicable:
> revset: add support for explicit substring:"..." prefix

- CHANGELOG.md
- docs/revsets.md
- lib/src/revset.rs
- lib/tests/test_revset.rs
Per discussion in #2107, I believe "exact" is preferred.
We can also change the default to exact match, but it doesn't always make sense. Exact match would be useful for branches(), but not for description(). We could define default per predicate function, but I'm pretty sure I cannot remember which one is which.
If applicable:
> revset: rename literal:"" prefix to exact:""

- cli/src/cli_util.rs
- cli/src/config.rs
> cli: let custom binaries add extra default configs

- CHANGELOG.md
- cli/src/diff_util.rs
- cli/tests/test_diff_command.rs
This is a first cut at #2066. It needs a better way of getting the terminal width (hardcoded for now to 120) and maybe some tests... I did a few visual comparisons to `git diff` and it looks like it works...
```
jj ❯ COLUMNS=120 git diff --stat 2102de94 e414f3b7
CHANGELOG.md                       |   4 +++
cli/src/cli_util.rs                |  34 ++++++-----------------
cli/src/commands/mod.rs            |  51 +++++++++++++++++-----------------
cli/src/config-schema.json         |   5 ++++
cli/src/config/colors.toml         |   1 +
cli/src/diff_util.rs               |  20 ++++++++++----
cli/src/merge_tools.rs             |  55 ++++++++++++++++++++-----------------
cli/tests/test_describe_command.rs |  89 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++- …
```
> Add jj diffs --stat option

- cli/src/cli_util.rs
- cli/src/commands/debug.rs
- cli/src/commands/mod.rs
- lib/src/revset.rs
- lib/tests/test_revset.rs
> revset: pass all context arguments to `parse()` via an object

- CHANGELOG.md
- cli/src/cli_util.rs
- cli/src/config/merge_tools.toml
- cli/src/merge_tools/external.rs
- cli/testing/fake-diff-editor.rs
- cli/tests/test_diffedit_command.rs
- docs/config.md
Implementation for 3-pane diff as discussed in https://github.com/martinvonz/jj/discussions/1905#discussioncomment-6589673. 
To test it out, patch this PR and try
cargo run -- --config-toml 'ui.diff-editor="meld-3"' diffedit -r @-
If you'd like to try programs other than `meld`, just use a merge tool config that has `$output` in its `edit-args`.
I am also thinking about trying out a conflict resolution interface based on this.
If applicable:
> external diff-editors: allow 3-pane diff, set up `meld-3`.

- docs/config.md
`vimtabdiff` can be much more convenient for diffs with few files. Also, it can be easier to set up for some people (it is a Python script rather than a Vim plugin).
If applicable:
> config.md: update Vim instructions to mention `vimtabdiff`

- cli/tests/common/mod.rs
- cli/tests/test_git_fetch.rs
- cli/tests/test_git_import_export.rs
- cli/tests/test_undo.rs
This is the first commit from https://github.com/martinvonz/jj/pull/2123, which should be
less controversial (even though it is not particularly important either)
> cli tests: Move `current_operation_id` to test_utils

- lib/src/settings.rs
Result of `cargo +nightly clippy --workspace --fix`.
Apparently, the current version will become illegal in a future
version of Rust.
> clippy: add some static lifetimes

- cli/src/diff_util.rs
I just noticed that the comment on the `--stat` option was `//` instead of `///` so it wasn't showing in the output of `-h` or `help`. This fixes it.
If applicable:
> Fix docs for diff --stat

- CHANGELOG.md
- cli/tests/test_status_command.rs
- lib/src/gitignore.rs
- lib/src/working_copy.rs
This addresses #2051.
- Ignore .gitignore files from untracked directories
- Do not allow un-ignoring files within ignored directories
- Make it more clear how GitIgnoreFile works
> Fix .gitignore handling of ignored directories

- Cargo.lock
- Cargo.toml
- cli/tests/test_global_opts.rs
While looking at the help I noticed we were not wrapping long help messages. E.g. 
By enabling the `wrap_help` feature in `clap`, we get nicer help.
If applicable:
> Enable wrapping help in clap

- CHANGELOG.md
- cli/src/template.pest
- cli/src/template_builder.rs
- cli/tests/test_log_command.rs
- cli/tests/test_templater.rs
- docs/templates.md
Add starts_with/ends_with/remove_prefix/remove_suffix/substr methods to string when templating.
**Note: This also adds negative numbers to the template grammar**
If applicable:
> templates: Add more string methods

- cli/src/template_builder.rs
- cli/tests/test_templater.rs
> templater: fix offset of negative substr() index to be char-based

- cli/src/commands/mod.rs
- lib/src/commit.rs
- lib/src/commit_builder.rs
- lib/src/merged_tree.rs
- lib/src/working_copy.rs
> Introduce a builder for merged trees and use it in `jj chmod`

- docs/glossary.md
I was recently tripped up by a question about "where are change ids stored, and in what scope are they valid". Got an answer on Discord, thought I'd add it in the place where I initially searched :)
> docs: Add information about Change ID scope to glossary

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/src/merge_tools/builtin.rs
- cli/src/merge_tools/mod.rs
- lib/src/backend.rs
> merge_tools: create builtin diff editor

- .github/workflows/build.yml
I'm not sure if we need to make this check required yet, but it's certainly good to know.
For example, this checks for broken links for one `md` file to another.
> GitHub build action: check whether `mkdocs` can build docs in PRs

- .github/workflows/release.yml
- mkdocs.yml
For a demo, see https://github.com/ilyagr/jj/releases/tag/0.8.6-tmpdocs and the [jj-0.8.6-tmpdocs-docs-html.tar.gz](https://github.com/ilyagr/jj/releases/download/0.8.6-tmpdocs/jj-0.8.6-tmpdocs-docs-html.tar.gz) link on that page. "-tmpdocs" is part of the version in this example.
I'm not sure how many people would find this useful, but it seems conceivable and was quite easy to do. Perhaps packagers (from the theoretical future) could package this with the binary.
> Github release action: release archived HTML of the docs for offline use

- cli/src/cli_util.rs
- cli/src/commands/branch.rs
- cli/tests/test_branch_command.rs
- lib/src/git.rs
- lib/tests/test_git.rs
> Allow branches on the root commit again

- CHANGELOG.md
- cli/src/commands/mod.rs
- cli/tests/test_alias.rs
- cli/tests/test_next_prev_commands.rs
- lib/src/revset.rs
This is a naive implementation, which cannot deal with multiple children or parents stemming from merges.
For now I'll create a follow-up bug, which someone else can solve. 
Note: I currently gave each command separate a separate argument struct for extensibility. 
Fixes #878
- [n/a ] I have updated the documentation (README.md, docs/, demos/)
> commands: Implement `next` and `prev`

- lib/src/git.rs
> git: split `export_some_refs()` to smaller functions

- CHANGELOG.md
- lib/src/revset.rs
- lib/tests/test_revset.rs
> revset: do not lookup unimported tags or remote branches by unqualified name

- cli/src/commands/mod.rs
- cli/tests/test_abandon_command.rs
> cli: make `jj abandon` print commit info as it was before the command

- README.md
- docs/git-compatibility.md
- docs/technical/concurrency.md
At this point, they are stable enough that I think we should
advertise them and encourage their use. This also explains
some caveats.
If applicable:
> docs: make co-located repos more prominent, explain them better

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/revsets.md
> release: release version 0.9.0

- docs/config.md
- docs/github.md
- docs/revsets.md
- docs/tutorial.md
Now that we're very close to a release, it should be fine to use the new syntax in our documentation. This effecttively backs out 37436f7344d4.
If applicable:
> docs: prefer new revset operator `::` over deprecated `:`

- docs/install-and-setup.md
Now that v0.9.0 is released, it seems appropriate.
> docs: remove v0.7.0 shell completion instructions

- Cargo.toml
This is required for `cargo publish`. It seems better to have it tracked than to do add it whenever we publish.
If applicable:
> cargo: add version number to `jj-lib` dependency

- cli/tests/test_revset_output.rs
- lib/src/revset.rs
> revset: translate symbol rules in error message

- CHANGELOG.md
- docs/revsets.md
- lib/src/revset.rs
- lib/tests/test_revset.rs
Allows `ancestors(rev, n)` in the revset language.
```
⮞ jj log -r 'ancestors(@, 5)'
@  korrtmol sullyj3@gmail.com 2023-09-02 17:37:15.000 +10:00 c9dca8e9
│  (empty) Add test for revset n ancestors
◉  owvqrlnu sullyj3@gmail.com 2023-09-02 17:35:20.000 +10:00 main* HEAD@git 498cd57b
│  Add optional argument n to ancestors() in revset language
◉  yoslkysy sullyj3@gmail.com 2023-09-02 17:09:53.000 +10:00 80456ec4
│  Add generations argument to RevsetExpression::ancestors method
◉  uqwupmro martinvonz@google.com 2023-09-01 16:49:23.000 -07:00 main@upstream e3825495
│  store: don't include cached objects in `Debug` format
◉  ostmnpsu martinvonz@google.com 2023-09-01 16:23:39.000 -07:00 16c897d8
│  conflicts: leverage `Merge::map()` in `materialize_merge_result()`
~
```
See …
> Add optional `depth` parameter to ancestors() revset function

- docs/config.md
mkdocs can't seem to handle backticks in link anchors for out-of-text links.
> config docs: minor fixups

- cli/src/commands/mod.rs
- cli/src/config-schema.json
- lib/src/revset.rs
- lib/src/settings.rs
> use `ancestors(x, depth)` in tests and default revset

- lib/src/git.rs
- lib/src/git_backend.rs
- lib/tests/test_git.rs
> git: add method to import commits, promote them to tree-conflict format

- CHANGELOG.md
- cli/Cargo.toml
- docs/config.md
> cargo: enable the watchman feature by default

- flake.nix
Summary: By default, and to be explicit, the local flake turns off default features. But, https://github.com/martinvonz/jj/commit/70f6e0a452230c050e1eb8ccb7f5471b9ec16112 turned off watchman support for the Nix build by accident. Enable default features so this doesn't happen again.
Change-Id: Ib7dd935eceab328fa5b0333b10368377
If applicable:
> chore(nix): add 'default' features to list of cargo features

- CHANGELOG.md
- cli/src/commands/operation.rs
- cli/tests/test_operations.rs
Seems useful, and makes it consistent with the `jj log` and `jj obslog`.
If applicable:
> cli: add `jj op log --no-graph`

- README.md
- docs/contributing.md
The result is available at https://github.com/ilyagr/jj/tree/web?tab=readme-ov-file#jujutsu-vcs.
I'm not entirely sure when we want to merge this, but I don't have any TODOs left for before that. Also, we could skip the prominent link to the docs website for now if we'd like.
**Update:** I also added some instructions on how to contribute to the docs. Initially, I just wanted to remove the "website is experimental" message from contributing.md, but I ended up doing  a bit more...
> README: announce our docs website to the world + instructions to contribute

- docs/git-compatibility.md
https://github.com/martinvonz/jj/discussions/2230 indicates a lot of interest in this, so we'd probably want to support this officially at some point. Until then, document a script that has worked well-enough for some of us.
Hi! It's me, non-Googler @chooglen. Why did I choose to separate my GitHub accounts in the first place? I don't really know.
> docs: document script to colocate a jj-only repo

- CHANGELOG.md
- cli/src/template.pest
- cli/src/template_parser.rs
- cli/tests/test_log_command.rs
- cli/tests/test_operations.rs
- cli/tests/test_templater.rs
This allows safely getting e.g. multiple descriptions, and knowing where the boundaries are
If applicable:
- N/A I have updated the documentation (README.md, docs/, demos/)
- N/A I have updated the config schema (cli/src/config-schema.json)
> Allow \0 escape for nulls

- docs/contributing.md
> docs: add a section about profiling

- .github/workflows/docs.yml
- .github/workflows/release.yml
Perhaps this will stop Github from showing jj-docs-bot as a very active contributor in https://github.com/martinvonz/jj/pulse. This would probably fair, even though jj-docs-bot tries its best to be a good and helpful bot.
Regardless, this seems to be the standard on Github which has `dependabot[bot]` and `github-actions[bot]`.
----
Let me know if you want me to test this on my own repo before merging. There's a small chance this could break `jj-docs[bot]` somehow, but I doubt it, and it'd be obvious immediately if it did break (as the docs would immediately fail to build).
> github: rename `jj-docs-bot` to `jj-docs[bot]`

- docs/templates.md
We are a little weird about which string escapes we support, and we don't support raw strings.  I thought this might be worth documenting.
Inspired by https://github.com/martinvonz/jj/pull/2251
> templates.md docs: Document string literal format

- cli/src/cli_util.rs
- cli/src/merge_tools/builtin.rs
- cli/src/merge_tools/mod.rs
- cli/tests/test_resolve_command.rs
> merge_tools: create builtin merge editor

- lib/tests/test_bad_locking.rs
@colemickens, let me know if this makes any difference to #2103.
If applicable:
> test_bad_locking: make `merge_directories()` expect non-existent target

- cli/src/merge_tools/builtin.rs
- lib/tests/test_bad_locking.rs
- lib/tests/test_commit_builder.rs
- lib/tests/test_commit_concurrent.rs
- lib/tests/test_conflicts.rs
- lib/tests/test_default_revset_graph_iterator.rs
- lib/tests/test_diff_summary.rs
- lib/tests/test_git.rs
- lib/tests/test_id_prefix.rs
- lib/tests/test_index.rs
- lib/tests/test_init.rs
- lib/tests/test_load_repo.rs
- lib/tests/test_merge_trees.rs
- lib/tests/test_merged_tree.rs
- lib/tests/test_mut_repo.rs
- lib/tests/test_operations.rs
- lib/tests/test_refs.rs
- lib/tests/test_revset.rs
- lib/tests/test_rewrite.rs
- lib/tests/test_view.rs
- lib/tests/test_working_copy.rs
- lib/tests/test_working_copy_concurrent.rs
- lib/tests/test_working_copy_sparse.rs
- lib/tests/test_workspace.rs
- lib/testutils/src/lib.rs
> Use an enum for backend to use in tests

- cli/src/merge_tools/mod.rs
> merge_tools: reorder `editor_args_from_settings`

- cli/examples/custom-backend/main.rs
- lib/src/backend.rs
- lib/src/git_backend.rs
- lib/src/local_backend.rs
- lib/src/store.rs
> backend: move constant functions first

- cli/src/config/revsets.toml
- docs/revsets.md
> cli trunk() revset: fix docs and add `upstream` remote support

- Cargo.lock
- cli/Cargo.toml
Among other things, this prevented `jj` from working with `cargo binstall`.
The trick is taken from
https://github.com/rust-lang/cargo/issues/2911#issuecomment-1483256987.
We could now also remove `--bin jj` from the installation commands in `install-and-setup.md`, but I'm not sure we should. That argument makes it clear that the binary is `jj`, not `jj-cli`.
Fixes #216.
If applicable:
> cargo: stop `cargo install` from installing `fake-editor` & co.

- cli/Cargo.toml
(This is mainly a draft because it is based on #2277)
https://github.com/cargo-bins/cargo-binstall
Note that `jj` will only become installable once the next release
is published to crates.io. For this reason, I am planning to
wait until then before documenting the fact that `jj` can be
installed this way.
At that point, `cargo binstall jj-cli` should be sufficient.
Before then, it's possible to test that this will work by doing
```
cargo binstall jj-cli --force --strategies crate-meta-data \
--log-level debug  --dry-run --manifest-path cli/Cargo.toml
``` 
Without --dry-run, this should install the 0.9 release if run
on `cli/Cargo.toml` form this commit. (You don't need the rest
of the `jj` repo for this to work, you can just download the
`Cargo.toml` and point `--manifest-path` to it)
If …
> cargo: make `jj` installable with `cargo binstall`

- CHANGELOG.md
- cli/src/diff_util.rs
- cli/src/merge_tools/mod.rs
- docs/config.md
> merge_tools: enable `:builtin` as default diff/merge editor

- CHANGELOG.md
- cli/src/commands/mod.rs
> commands: add `--interactive` flag to `jj split`

- cli/src/commands/mod.rs
> cli/commands: Add desc as an alias for description

- cli/src/cli_util.rs
- cli/tests/test_checkout.rs
Resolves issue #2192 
The output of the changed hint is:
```
$ jj checkout letters
Error: Revset "letters" resolved to more than one revision
Hint: The revset "letters" resolved to these revisions:
rmyxvrmv f54150b7 letters?? | (conflict) E ammended
pysvtnpy f9e2e044 letters?? | (conflict) E
This error is due to a conflicted branch. To resolve this, try setting to which revision the branch points to with "jj branch set letters --revision <REVISION>"
```
If applicable:
> cli: hint for conflicted branches and change ids

- cli/LICENSE
- lib/LICENSE
According to https://github.com/clap-rs/clap/pull/2810, the Apache license must be distributed with sources, including with the sources we publish to crates.io.
If applicable:
> cargo: add LICENSE file to each crate we publish

- Cargo.lock
Summary: Dependabot will update all of our "first-party" dependencies that we list in Cargo.toml, but that doesn't mean it will pick up transitive dependencies that might also see minor semver compatible bumps. `cargo update` handles that for us, instead.
Ideally, this would be handled as a separate dependabot flow, but I don't know how to do that...
Change-Id: I12cd2e03e2863abd8ed961304685d276
If applicable:
> chore: run 'cargo update'

- lib/src/working_copy.rs
> watchman: use single-threaded async runtime

- cli/src/cli_util.rs
- cli/src/commands/mod.rs
- cli/src/merge_tools/builtin.rs
- cli/src/merge_tools/external.rs
- cli/src/merge_tools/mod.rs
> merge_tools: pass `Matcher` in for interactive use

- CHANGELOG.md
- cli/src/cli_util.rs
- cli/src/commands/mod.rs
- cli/src/config-schema.json
- cli/src/config/revsets.toml
- cli/tests/test_abandon_command.rs
- cli/tests/test_branch_command.rs
- cli/tests/test_duplicate_command.rs
- cli/tests/test_edit_command.rs
- cli/tests/test_git_fetch.rs
- cli/tests/test_git_push.rs
- cli/tests/test_immutable_commits.rs
- cli/tests/test_restore_command.rs
- cli/tests/test_templater.rs
- cli/tests/test_undo.rs
- docs/config.md
- lib/src/local_backend.rs
- lib/src/revset.rs
I moved most of #2247 into this, since this bit seems less controversial, and I'm not sure when I'll get back to working on the remaining parts (adding `immutable()` and using that in the default log template)
If applicable:
> Add support for configurable set of immutable commits

- cli/src/commands/git.rs
- cli/src/commit_templater.rs
- lib/src/commit.rs
- lib/src/default_revset_engine.rs
> templater: fast-path `empty` and `conflict` to not read trees

- docs/github.md
This adresses #1989
If applicable:
> Docs: Make github.md a bit clearer

- cli/src/merge_tools/builtin.rs
- lib/src/conflicts.rs
- lib/src/files.rs
- lib/src/merged_tree.rs
- lib/src/tree.rs
- lib/tests/test_merged_tree.rs
> Fix propagation of conflict resolution with tree-level conflicts

- cli/src/commands/mod.rs
- lib/src/git.rs
- lib/src/repo.rs
- lib/src/rewrite.rs
- lib/src/view.rs
> git: prep for importing `refs/heads/*` as `@git` remote branches

- CHANGELOG.md
- cli/src/commands/mod.rs
- cli/tests/test_commit_command.rs
> commands: support path arguments to `jj commit`

- CHANGELOG.md
- cli/src/commands/mod.rs
> command: add `--interactive` flag to `jj commit`

- cli/src/cli_util.rs
- cli/src/commands/debug.rs
- cli/src/commands/mod.rs
- cli/src/config-schema.json
- cli/tests/test_branch_command.rs
- cli/tests/test_immutable_commits.rs
- cli/tests/test_log_command.rs
- cli/tests/test_templater.rs
- lib/src/settings.rs
One important bit that remains is to teach the templater a `immutable` (or `mutable`) keyword. That's a bit more complicated because we'll probably need to give revsets a caching iterator so we can quickly check if the `immutable()` revset contains a particular commit without eagerly evaluating it (and without searching from the heads every time).
If applicable:
> Base default log template on `immutable_heads()`

- cli/src/cli_util.rs
- cli/src/commands/git.rs
- cli/src/commands/mod.rs
- cli/tests/test_commit_template.rs
- cli/tests/test_git_colocated.rs
- cli/tests/test_git_fetch.rs
- cli/tests/test_git_push.rs
- cli/tests/test_git_submodule.rs
- cli/tests/test_init_command.rs
- lib/src/git.rs
- lib/tests/test_git.rs
> cli: print commits abandoned by git::import_refs() or fetch()

- cli/src/cli_util.rs
- cli/tests/test_commit_template.rs
- cli/tests/test_git_colocated.rs
- cli/tests/test_git_fetch.rs
- cli/tests/test_git_submodule.rs
The problem is that the first non-working-copy commit moves the unborn current branch to that commit, but jj doesn't "export" the moved branch. Therefore, the next jj invocation notices the "external" ref change, which was actually made by jj.
I'm not sure why we play nice by setting the "current" HEAD, but I *think* it's okay to set the "new" HEAD and reset to the same commit to clear Git index.
If applicable:
> cli: ensure first new HEAD is detached

- cli/src/cli_util.rs
The codespell GitHub action fails because of the typo. I don't know why it started failing now. The comment is 8 months old and the codespell action hasn't been updated in 5 months.
If applicable:
> cli_utils: fix a typo in a comment

- .github/workflows/release.yml
- mkdocs-offline.yml
- mkdocs.yml
The `offline` plugin added to the MkDocs config in commit 772e2b8 ended up changing the directory structure of the website, see the resulting commit 56aec196.
**Before** that commit, the following URLs were valid:
<https://martinvonz.github.io/jj/v0.9.0/revsets>
<https://martinvonz.github.io/jj/v0.9.0/revsets/>
and <https://martinvonz.github.io/jj/v0.9.0/revsets.html> was invalid.
The situation described above should be restored by this commit.
**After** 772e2b8 and before this commit, the following URLs were valid:
<https://martinvonz.github.io/jj/v0.9.0/revsets>
<https://martinvonz.github.io/jj/v0.9.0/revsets.html> and <https://martinvonz.github.io/jj/v0.9.0/revsets/> was invalid.
This commit is likely to break the version switcher between v0.9.0 and newer versions. The breakage would …
> docs: restore directory structure of the website

- cli/src/cli_util.rs
- cli/src/commands/git.rs
- cli/src/commands/mod.rs
- cli/tests/test_git_colocated.rs
- cli/tests/test_git_fetch.rs
- cli/tests/test_git_push.rs
Apparently, it gets too verbose if the remote history is actively rewritten. Let's summarize the output for now. The plan is to show the list of moved refs instead of the full list of abandoned commits.
If applicable:
> cli: don't list commits abandoned by import/fetch, just print the number

- cli/src/cli_util.rs
- cli/src/commands/git.rs
- cli/src/commands/mod.rs
- lib/src/git_backend.rs
- lib/tests/test_git.rs
- lib/tests/test_revset.rs
> git_backend: don't let external callers acquire `Mutex<git2::Repository>`

- cli/src/cli_util.rs
- lib/src/git.rs
> git: extract `export_head_to_git()` to lib function, refactor caller

- docs/index.md
- mkdocs.yml
- pyproject.toml
Before, https://martinvonz.github.io/jj/latest redirected to
https://martinvonz.github.io/jj/latest/install-and-setup.html.
Now, it will direct people to a basic page with a link to
the repo and a few other useful pages.
An additional motivation is the desire to have a homepage to
link to from
https://github.com/martinvonz/jj/pull/2273#discussion_r1331008117.
Better something very basic than nothing.
------------------
I made this in a bit of a rush so that we could merge this before the next release updates the "latest" website section. PTAL, I may have made some mistakes. Also, it's fine if we decide we don't want to merge this.
> docs: create a basic homepage for the docs website

- docs/index.md
The original link would likely be broken by the change to the heading title in https://github.com/martinvonz/jj/pull/2273.
> docs index.md: Make README link a bit more reliable

- CHANGELOG.md
- cli/src/commands/branch.rs
- cli/src/commit_templater.rs
- cli/tests/test_branch_command.rs
- cli/tests/test_git_import_export.rs
- cli/tests/test_git_remotes.rs
- lib/src/git.rs
- lib/src/protos/op_store.proto
- lib/src/protos/op_store.rs
- lib/src/revset.rs
- lib/src/simple_op_store.rs
- lib/tests/test_git.rs
- lib/tests/test_revset.rs
> copy refs/heads to `remote_targets["git"]` to remove special case for `@git` branches

- cli/src/commands/operation.rs
- cli/tests/test_git_colocated.rs
> cli: in colocated repo, don't restore view.git_head on undo

- cli/tests/common/mod.rs
> tests: disable parsing of system CA certificates in CLI tests

- README.md
Summary: Just a small rework of the very top-level frontmatter. Now:
- Uses `<div>` to center things a little
- Adds top-level links to the new homepage, installation guide, and tutorial
- Reworks the disclaimer and 'Introduction' section. After all, a README should first say what the project is! I think this reads much better.
Change-Id: I2d92a21650afec0640add3741d4f20c5
> readme: tidy up the front matter a little

- .github/workflows/nix-linux.yml
- flake.nix
Summary: Since 066032b6e69 was merged, the `nix flake check` build no longer overrides the 'cargo test' profile explicitly, to save disk space. The CI seems to be in a better spot. This will stem the tide for a while hopefully.
However, with that change in place, the `nix flake check` build was essentially a redundant, nearly-identical copy of a normal `nix build` with no differentiating features, except: `RUST_BACKTRACE` is set to 1.
Delete all this code, and remove it from the CI matrix, and instead just export `RUST_BACKTRACE` on the `checkPhase` of the normal `nix build` instead, which is functionally equivalent.
Also does some minor, no-functional-change touchups to `flake.nix` while I was there (whitespace, etc.)
Change-Id: I87336b16e2a0b973343ecbde8ffd7b8f
If applicable:
> nix: merge (now redundant) flake check with normal build

- cli/tests/test_git_import_export.rs
- lib/src/git.rs
Implements the "import" side described in the following diagram.
https://github.com/martinvonz/jj/blob/7f4fe22a987e33cb2d2ef5976080f6f9a1da7024/docs/design/tracking-branches.md#importexport-data-flow
If applicable:
> git: migrate import_refs() to diffing git_refs and known remote refs

- CHANGELOG.md
- cli/src/cli_util.rs
- cli/tests/test_config_command.rs
> Allow TOML arrays and tables to `jj config set`

- CHANGELOG.md
- cli/src/commands/mod.rs
- cli/tests/test_workspaces.rs
Summary: Workspaces are most useful to test different versions (commits) of the tree within the same repository, but in many cases you want to check out a specific commit within a workspace.
Make that trivial with a `--revision` option which will be used as the basis for the new workspace. If no `-r` option is given, then the previous behavior applies: the workspace is created with a working copy commit created on top of the current working copy commit's parent.
Change-Id: I23549efe29bc23fb9f75437b6023c237
If applicable:
> workspace: add '--revision' argument to 'workspace add'

- cli/src/commands/git.rs
$HOME isn't set here, but `dirs` has suitable magic for us already.
Something's still not working on Windows (I get "Error: Failed to authenticate SSH session: ; class=Ssh (23)"), but it's a step in the right direction.
> cli: fix SSH key discovery on Windows

- cli/src/commands/branch.rs
- lib/src/git.rs
- lib/src/repo.rs
- lib/src/view.rs
- lib/tests/test_git.rs
- lib/tests/test_revset.rs
> view: refactor/remove some branch API for ease of migrating to per-remote data structure

- CHANGELOG.md
- cli/src/commands/mod.rs
- cli/tests/test_workspaces.rs
Summary: This allows `workspace forget` to forget multiple workspaces in a single action; it now behaves more consistently with other verbs like `abandon` which can take multiple revisions at one time.
There's some hoop-jumping involved to ensure the oplog transaction description looks nice, but as they say: small conveniences cost a lot.
Change-Id: Id91da269f87b145010c870b7dc043748
If applicable:
> workspace: `workspace forget` multiple names at once

- cli/tests/test_workspaces.rs
Summary: Yuya's changes and mine had a semantic conflict ("merge skew") between the two of them, as b7c7b19e changed the `op log `output slightly, whereas 220292ad included a new test that used `op log` itself.
Generated by `cargo insta review`.
If applicable:
> test_workspaces: fix merge skew from b7c7b19e + 220292ad

- CHANGELOG.md
- cli/src/commands/branch.rs
- cli/src/commands/git.rs
- cli/src/commands/mod.rs
- cli/tests/test_branch_command.rs
- cli/tests/test_git_fetch.rs
- docs/config.md
- lib/src/git.rs
- lib/src/op_store.rs
- lib/src/protos/op_store.proto
- lib/src/protos/op_store.rs
- lib/src/repo.rs
- lib/src/simple_op_store.rs
- lib/src/view.rs
- lib/tests/test_git.rs
- lib/tests/test_mut_repo.rs
- lib/tests/test_revset.rs
- lib/tests/test_rewrite.rs
- lib/tests/test_view.rs
https://github.com/martinvonz/jj/blob/main/docs/design/tracking-branches.md#fetchimport
If applicable:
> implement tracking/non-tracking remote branches for import/fetch

- cli/src/commands/git.rs
> remove redundant workaround for unborn branch on "git clone --colocate"

- cli/examples/custom-backend/main.rs
- cli/examples/custom-working-copy/main.rs
- cli/src/cli_util.rs
- cli/src/commands/mod.rs
- lib/src/local_working_copy.rs
- lib/src/repo.rs
- lib/src/working_copy.rs
- lib/src/workspace.rs
- lib/tests/test_bad_locking.rs
- lib/tests/test_git.rs
- lib/tests/test_local_working_copy.rs
- lib/tests/test_local_working_copy_concurrent.rs
- lib/tests/test_local_working_copy_sparse.rs
- lib/tests/test_workspace.rs
- lib/testutils/src/lib.rs
> Make working copy customizable

- lib/src/git.rs
- lib/tests/test_git.rs
> git: on import_refs(), don't abandon ancestors of newly fetched refs

- CHANGELOG.md
- cli/src/commands/git.rs
- cli/tests/test_git_push.rs
- docs/config.md
- docs/design/tracking-branches.md
- lib/src/git.rs
- lib/src/op_store.rs
- lib/src/refs.rs
- lib/src/view.rs
- lib/tests/test_git.rs
> git: prevent accidental push to non-tracking remote, mark pushed branches as tracking

- cli/src/commit_templater.rs
- cli/tests/test_branch_command.rs
- lib/src/revset.rs
- lib/tests/test_revset.rs
> templater, revset suggestion: take non-tracking branches unrelated to locals

- cli/src/commands/git.rs
- cli/src/commands/mod.rs
- cli/tests/test_git_clone.rs
> git: add `.jj/.gitignore` when creating colocated repo

- CHANGELOG.md
- cli/src/commands/branch.rs
- cli/tests/test_branch_command.rs
- cli/tests/test_git_clone.rs
- cli/tests/test_git_colocated.rs
- cli/tests/test_git_fetch.rs
- cli/tests/test_git_import_export.rs
- cli/tests/test_git_push.rs
- cli/tests/test_undo.rs
> cli: hide non-tracking remote branches by default, `--all` to show all remotes/locals

- docs/git-compatibility.md
Please double-check that this actually matches the behavior of 872265a22.
> git-compatibility.md: adjust instructions to convert to colocated repo to match 872265a22

- Cargo.lock
- cli/Cargo.toml
- cli/src/commands/mod.rs
- cli/src/diff_util.rs
- cli/src/merge_tools/builtin.rs
- cli/src/merge_tools/external.rs
- cli/src/merge_tools/mod.rs
- lib/src/conflicts.rs
- lib/src/git_backend.rs
- lib/src/local_backend.rs
- lib/src/local_working_copy.rs
- lib/src/merged_tree.rs
- lib/src/store.rs
- lib/tests/test_conflicts.rs
> Make conflicts materialization async

- CHANGELOG.md
- Cargo.lock
- cli/src/commands/branch.rs
- cli/src/commands/git.rs
- docs/revsets.md
- lib/Cargo.toml
- lib/src/lib.rs
- lib/src/revset.rs
- lib/src/str_util.rs
- lib/tests/test_revset.rs
> extract StringPattern to module, add glob: pattern to be used in CLI

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- cli/src/cli_util.rs
- cli/src/commands/branch.rs
- cli/src/commands/git.rs
- cli/tests/test_branch_command.rs
- lib/src/revset.rs
- lib/src/str_util.rs
- lib/src/view.rs
> add branch delete/forget glob:pattern, deprecate --glob option

- docs/FAQ.md
> docs: discuss `jj commit -i` in `FAQ.md`

- docs/tutorial.md
This is an alternative to #2409 , as discussed in https://github.com/martinvonz/jj/pull/2409#discussion_r1367839957 .
I found the `rebase` part of the tutorial confusing due to the use of machine-dependent change IDs on an unknown command. #2409 fixes this by referring to changes by their description, but this is un-idiomatic and does not scale to real repositories. The present PR instead explains the `rebase` options before using them, with the clearer long names. All other options in the tutorial are changed to this style for consistency.
> docs/tutorial.md: introduce both long and short names of each option

- cli/src/commands/branch.rs
- cli/tests/test_branch_command.rs
> cli: allow to select branches to track/untrack by string pattern

- cli/tests/test_undo.rs
- lib/src/refs.rs
- lib/src/repo.rs
- lib/src/view.rs
- lib/tests/test_view.rs
> fix undo of "branch track/untrack" to merge state changes

- cli/src/config/templates.toml
- cli/tests/test_abandon_command.rs
- cli/tests/test_branch_command.rs
- cli/tests/test_git_fetch.rs
- cli/tests/test_git_import_export.rs
- cli/tests/test_git_push.rs
- cli/tests/test_undo.rs
This is mainly relevant for `jj abandon` and `jj branch list`. https://github.com/martinvonz/jj/issues/2411
If applicable:
> cli templates: include hidden (AKA abandoned) status in short commit template

- cli/src/config/merge_tools.toml
- docs/config.md
- docs/config.toml
Thanks to @glencbz for noticing that VS Code works fine now as a merge tool, and thanks to @solson for suggesting
`merge-tool-edits-conflict-markers = true`.
If applicable:
> merge_tools.toml: add VS Code as a default merge tool.

- docs/config.toml
It's been changed to `:builtin` some time ago.
I'm actually not sure if this file has much use anymore. Perhaps we should put it inside `config.md` or get rid of it.
If applicable:
> docs/config.toml: update the default diff editor

- cli/src/commands/mod.rs
- cli/src/config/colors.toml
- cli/src/config/templates.toml
- cli/tests/test_checkout.rs
- cli/tests/test_commit_template.rs
- cli/tests/test_restore_command.rs
- cli/tests/test_undo.rs
- cli/tests/test_workspaces.rs
Fixes https://github.com/martinvonz/jj/issues/2411.
Includes a few related changes. In particular, one of the test changes made me think
that "hidden" should override "divergent" in the commit template (this change can be
split into a separate commit or abandoned if it's controversial).
If applicable:
> cli templates: include info on divergent change ids in short commit template

- CHANGELOG.md
- cli/src/commit_templater.rs
- cli/src/operation_templater.rs
- cli/src/template_builder.rs
- cli/tests/test_commit_template.rs
- docs/templates.md
> templater: make branches, tags, git_refs, and git_head return list type

- cli/examples/custom-backend/main.rs
- lib/src/backend.rs
- lib/src/git_backend.rs
- lib/src/local_backend.rs
- lib/src/store.rs
- lib/testutils/src/test_backend.rs
> store: use `block_on` from `pollster` when reading conflicts

- cli/src/commands/mod.rs
- cli/src/commands/new.rs
- cli/src/commands/rebase.rs
- cli/src/commands/resolve.rs
The print_conflicted_paths function could belong either to `resolve.rs` or `status.rs`; I put it into the former for now.
#2452 now depends on this (we can also merge this as part of that PR).
Cc #2465, #2457
> commands: move resolve and rebase code to separate files

- cli/src/commands/debug.rs
- cli/src/commands/resolve.rs
- cli/tests/test_commit_command.rs
- cli/tests/test_describe_command.rs
Also removes a separate warning. I'm not sure why VS Code (and `rust-analyzer`) shows that one to me; running `cargo clippy` does not.
> clippy and rust-analyzer: get rid of warnings

- CHANGELOG.md
- cli/src/cli_util.rs
- cli/src/commands/new.rs
- cli/tests/test_immutable_commits.rs
- cli/tests/test_new_command.rs
> Fix `new --after` ignoring immutable commits + update hint for root commit being immutable

- CHANGELOG.md
- cli/src/commands/mod.rs
- cli/tests/test_workspaces.rs
> cli: make `jj workspace add` preserve all parents of current workspace

- lib/src/backend.rs
- lib/src/git_backend.rs
> git_backend: minor code cleanup + error handling

- CHANGELOG.md
- docs/install-and-setup.md
> Document installation with `cargo-binstall`

- docs/revsets.md
I had to increase indent on two list items for multiple paragraphs to work in
MkDocs.
If applicable:
> revsets.md: clarify string patterns, and file patterns

- docs/glossary.md
- docs/revsets.md
This is mainly motivated by an outdated sentence in `revsets.md`. Let me know if the other change should be discussed separately.
If applicable:
> revsets.md and glossary.md: correct and clarify "visible commits"

- cli/src/formatter.rs
- cli/src/template_builder.rs
- cli/src/text_util.rs
If we create a `ColorFormatter`, add some labels to it, print something using the configured style, and then return early because of an error, we would leave the terminal in a bad state. I think many shells reset color codes after a command returns, but let's still do our best.
If applicable:
> formatter: reset colors on early drop

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/src/cli_util.rs
- cli/tests/test_edit_command.rs
- lib/Cargo.toml
- lib/src/git_backend.rs
- lib/testutils/src/lib.rs
> git_backend: replace git2::Repository with gix::Repository

- docs/FAQ.md
This was brought up as a common point of confusion in a Discord discussion ~2  months ago.
Based on this [conversation][c] in Discord. [Rendered](https://github.com/martinvonz/jj/blob/push-ymrymvkmuyry/docs/FAQ.md#jj-is-said-to-record-the-working-after-jj-log-and-every-other-command-where-can-i-see-these-automatic-saves)
cc @arxanas as I based the answer on your explanation.
If applicable:
[c]: https://discord.com/channels/968932220549103686/968932220549103689/1155973815336177767
> FAQ: Add an entry on how Jujutsu saves changes in the working-copy.

- .github/workflows/codespell.yml
Summary: Codespell actually matches local files at the root of the repo with the `./` prefix, so without it the `skip` field won't match. Fix this for `./target` and `./.jj` directories.
Change-Id: Ibeafd7e400ff3bca9187d62241296060
> github: fix codespell `skip` syntax for directories

- cli/src/commands/interdiff.rs
- cli/src/commands/mod.rs
- cli/src/commands/obslog.rs
- lib/src/rewrite.rs
> Rebase to dest parent

- CHANGELOG.md
- cli/src/cli_util.rs
- cli/src/commands/new.rs
- cli/src/commands/rebase.rs
- cli/src/commands/workspace.rs
- cli/tests/test_workspaces.rs
Summary: A natural extension of the existing support, as suggested by Scott Olson. Closes #2496.
Change-Id: I91c9c8c377ad67ccde7945ed41af6c79
If applicable:
> cli: support multiple `--revision` arguments to `workspace add`

- cli/src/commands/run.rs
This also adds `jobs`, the argument reading the thread count to use and `shell_command`.
While we're at it, make `execute` a no-op and teach `run` to resolve the passed revsets. 
I also fixed my misunderstanding of `Clap` which makes 
`jj run 'echo hello world' -r 'mine() & ~origin@remote' --jobs 4` parse correctly.
If applicable:
> run: Teach run to resolve revsets and about jobs.

- flake.nix
Summary: Apparently this was broken. Maybe I broke it. Maybe something upstream changed and caused a regression. But without it, we get the stable `rustfmt` in the `nix develop` shell environment, not the nightly version. Fix it.
Change-Id: I602ed8e5691c4d48f8db575d62624955
> nix: fix the rustfmt version by using nightly

- flake.nix
Summary: Without `devShell` providing the needed Darwin-specific inputs, `cargo build` does not work inside a `nix develop` or `direnv` environment; libgit2 in particular fails on being able to find the Security framework.
The actual `nix build` invocation however *does* work because we correctly include those dependencies in the package `buildInputs`. So just factor them out, and use them in both places.
Change-Id: I484bf381ca31c29c4c39fb6d184bdd21
> nix: include darwin deps inside `devShell`, too

- cli/src/commands/git.rs
- lib/src/git_backend.rs
- lib/src/workspace.rs
- lib/tests/test_init.rs
> move initialization of colocated git repo to lib

- cli/src/commands/chmod.rs
- cli/src/commands/resolve.rs
- lib/src/conflicts.rs
- lib/src/git_backend.rs
- lib/src/merge.rs
- lib/src/merged_tree.rs
- lib/src/op_store.rs
- lib/src/simple_op_store.rs
- lib/tests/test_merge_trees.rs
> merge: prep for changing internal representation of `Merge` values

- CHANGELOG.md
- cli/src/config-schema.json
- docs/config.md
- lib/src/git.rs
- lib/src/settings.rs
- lib/tests/test_git.rs
> git: add config to disable abandoning of unreachable commits

- README.md
Summary: What was going to just be some minor touch-ups to the existing content ended in another rework of the frontmatter, this time primarily the sales pitch and basic feature explanation.
The motivation here is simple: you should not just encounter a three-word noun that is a hyperlink to pages with 1,000 words actually explaining the three-word noun itself is. It's jarring!
Instead, the frontmatter is longer, expanding on each major selling point and similarity to other tools. It actually *describes* the important, distinct design decisions that tell you what the tool is and does, rather than just link you around a bunch.
For example, one immediate thing is that calling jj a "DVCS" is actually kind of odd when it later becomes apparent that you can have multiple data model and commit …
> readme: improved front matter, part 2

- cli/tests/test_chmod_command.rs
- cli/tests/test_concurrent_operations.rs
- cli/tests/test_debug_command.rs
- cli/tests/test_operations.rs
- cli/tests/test_workspaces.rs
- lib/src/merge.rs
- lib/src/simple_op_store.rs
- lib/tests/test_conflicts.rs
> merge: store negative/positive terms internally in an interleaved Vec

- cli/src/merge_tools/builtin.rs
- cli/src/merge_tools/external.rs
- lib/src/conflicts.rs
- lib/src/files.rs
- lib/src/merge.rs
- lib/src/refs.rs
- lib/src/tree.rs
- lib/tests/test_merged_tree.rs
- lib/tests/test_refs.rs
> merge: remove `Merge::take()`

- .github/scripts/docs-build-deploy
- .github/workflows/build.yml
- .github/workflows/release.yml
- docs/contributing.md
- pyproject.toml
> Website (`poetry` and `mike`)-related updates

- cli/examples/custom-backend/main.rs
- lib/src/backend.rs
- lib/src/git_backend.rs
- lib/src/local_backend.rs
- lib/src/merged_tree.rs
- lib/src/store.rs
- lib/tests/test_merged_tree.rs
- lib/testutils/src/test_backend.rs
This took me a looong time but I think it's finally ready for review.
If applicable:
> Add a concurrent tree-diffing algo

- lib/src/merged_tree.rs
> Clean up concurrent tree diff a bit

- cli/src/merge_tools/builtin.rs
- lib/src/conflicts.rs
- lib/src/files.rs
- lib/src/git_backend.rs
- lib/src/merge.rs
- lib/src/merged_tree.rs
- lib/src/refs.rs
- lib/src/simple_op_store.rs
- lib/src/tree.rs
- lib/tests/test_conflicts.rs
- lib/tests/test_local_working_copy.rs
- lib/tests/test_merged_tree.rs
- lib/tests/test_refs.rs
> merge: micro-optimize `Merge`, clean up constructors

- CHANGELOG.md
- cli/tests/test_git_import_export.rs
- docs/revsets.md
- lib/src/revset.rs
- lib/tests/test_revset.rs
> revset: exclude `@git` branches from `remote_branches()`

- cli/src/commands/run.rs
- lib/src/default_index_store.rs
- lib/src/stacked_table.rs
Remove a couple of unnecessary unsafes:
- The NonZeroUsize is a constant where the unwrap will optimize away anyway and we don't have an unsafe without any good reason there :)
- The other two were simply not needed, lifetimes worked fine, maybe Rust became better since that code was written? NLL? Anyway, they're gone now
---
Was just hacking a bit locally and decided to do a classic unsafe grep :upside_down_face:
Those self-referential iterators could also be refactored I believe (at least with some crate that does that), but it wasn't as low hanging because otherwise you'd have done it instead of transmuting static lifetimes :)
If applicable:
> misc: drop a few low-hanging unsafes

- lib/src/default_index_store.rs
> index: rewrite `CompositeIndex::entry_by_pos()` by leveraging ancestors iterator

- cli/src/commands/commit.rs
- cli/src/commands/describe.rs
- cli/src/commands/split.rs
- cli/src/description_util.rs
- cli/tests/test_commit_command.rs
Renamed `description_template_for_commit` to
`description_template_for_describe` since it's only used in `cmd_describe`.
Renamed `description_template_for_cmd_split` to
`description_template_for_commit` and modified to accomodate empty `intro` argument.
Fixes #2439.
Feel free to request any changes.
If applicable:
> cli: generate commit template after selecting changes

- Cargo.lock
- Cargo.toml
- lib/Cargo.toml
- lib/src/merged_tree.rs
- lib/src/tree.rs
Closes #2127. This is fairly clumsy right now using `with_mut`, so I'm open to alternative ways of writing those cases. Basically, we use it to destructure the struct in question and get immutable/mutable references to all the fields at once.
Feel free to commandeer this PR if you are waiting impatiently, as I'm not sure when I'll get time to respond to feedback.
After this, these are the remaining `unsafe` sites:
https://github.com/martinvonz/jj/blob/084b99e1e2c42c40f2d52038cdc97687b76fed89/cli/src/cleanup_guard.rs#L60
https://github.com/martinvonz/jj/blob/084b99e1e2c42c40f2d52038cdc97687b76fed89/lib/testutils/src/lib.rs#L56
https://github.com/martinvonz/jj/blob/084b99e1e2c42c40f2d52038cdc97687b76fed89/lib/src/repo.rs#L275
The first two look like unavoidable instances of `unsafe` to me. …
> tree: remove unsafe with `ouroboros` for self-referential iterators

- cli/examples/custom-backend/main.rs
- cli/examples/custom-working-copy/main.rs
- lib/src/git_backend.rs
- lib/src/repo.rs
- lib/src/workspace.rs
- lib/tests/test_git.rs
- lib/testutils/src/lib.rs
> repo: pass UserSettings to store factories and initializers

- cli/src/merge_tools/builtin.rs
See the issue #2548 for more context.
It fixes the initially posted issue but it could remain open until [other](https://github.com/martinvonz/jj/issues/2548#issuecomment-1801130741) [related](https://github.com/martinvonz/jj/issues/2548#issuecomment-1806868455) issues are addressed by fixing the integration with `scm-record`, at least until another issue is opened to replace it.
If applicable:
> merge_tools: use `right_file_mode` in `make_diff_files`

- flake.nix
- lib/src/backend.rs
- lib/src/commit_builder.rs
- lib/src/git_backend.rs
- lib/src/local_backend.rs
- lib/src/protos/local_store.proto
- lib/src/protos/local_store.rs
- lib/testutils/src/lib.rs
Recognize signature metadata from git commit objects, implement a basic version of that for the native backend.
Extract the signed data (a commit binary repr without the signature) to be verified later.
---
Third time's the charm :)
This change would be undoubtedly needed for any signing implementation, so might push it to main to make the diffs of any future changes smaller - trying to push the smallest atomic changes.
This time I'm planning to make the actual signature creation part of signing happen outside of the backend, which seems like an obvious idea, but I thought it would be easier to do the other way then
If applicable:
> sign: Implement storage for digital commit signatures

- README.md
A coworker was having trouble finding a link to the jj Discord community. Add it to the top of the document, alongside the other badges, so it's easier to find.
> readme: Add Discord badge to the top of document

- cli/src/cli_util.rs
- cli/src/commands/git.rs
- cli/src/commands/init.rs
- lib/src/git.rs
- lib/tests/test_git.rs
- lib/tests/test_revset.rs
> git: port `git::import_refs()` to gitoxide

- lib/src/default_index_store.rs
> index: make the default log revset (or `heads(tags())`) evaluation faster

- cli/src/commands/mod.rs
Follows up on #2580, cc @Ralith 
I intend to make `jj backout` work the same way after it is renamed to `rollback`, if people on Discord agree.
If applicable:
- (n/a) I have updated `CHANGELOG.md`
- (maybe later?) I have added tests to cover my changes
> Adjustments to the dummy `jj revert` command

- cli/src/commands/branch.rs
- cli/src/commands/git.rs
- cli/src/commands/mod.rs
It is now out of place in mod.rs. It is only used in two places, so I copied it in each of them.
Follows up on @AntoineCezar 's work.
> cli: move `make_branch_term` out of commands/mod.rs

- cli/src/merge_tools/builtin.rs
The `scm-record` library comments say that the `file_mode` is:
> The Unix file mode of the file (before any changes), if available.
This reverts commit ffd6884 and fixes #2591 and #2548.
Note: The `0` file mode in `added` file doesn't concern use because AFAIK jj only reads the executable bit.
> merge_tools: use `left_file_mode` in `make_diff_files`
